### ISSUE TITLE
Very high number of RAC objects alive in memory at all times - Am I leaking stuff?

### ISSUE THREAD

**Issue by JaviSoto** [ReactiveCocoa/ReactiveCocoa#1141]
This is what I'm seeing after running the app for ~10 seconds. It's hard to summarize what the app is doing, but there are a lot of `RACSubscribe`s, these 2 are worth mentioning:
- Every VC on the app (<10 at a time) observes a global model property to set a property on themselves. And then in their `-viewDidLoad` they have other bindings that depend on this property.
- There are ~100 objects in memory that are queried from CoreData and then a `MTLModel` subclass object for each is created from them. These objects wrap the `NSManagedObject` and use `RACObserve` to update their properties whenever the equivalent property changes in their `NSManagedObject`. (_This may sound like a crazy implementation, but it ended up being pretty elegant and I managed to not leak the fact that I'm using CoreData outside of the data storage class_)

Some numbers:

123k living `NSMallocBlock`s ~= 6.5MB. Looking over the stack-traces most seem to come from RAC.
40k `RACCompoundDisposable`s ~= 2.5MB.
13k `RACSubscriber`s ~=  1M
10k `RACDynamicSignal`s
30k `RACDisposable`s
13k `RACPassthroughSubscriber`s
1k `NSKeyValueObservance`s

Screenshot:

![screenshot 2014-02-26 16 28 46](https://f.cloud.github.com/assets/666807/2277725/93e917d2-9f46-11e3-868d-cf0c770352da.png)

**Comment by mdavlet** [comment]
Any improvements on that? Creating 10 RACObserves leads to allocation of 250 RACCompoundDisposables. So it's quite easy to reach 300.000 RACCompoundDisposable objects in MVVM based app.

**Comment by mdiep** [comment]
The code here has moved to https://github.com/ReactiveCocoa/ReactiveObjC, so questions should be directed there. But I don't think there's been any substantial improvement to the Objective-C codebase.
