### ISSUE TITLE
How do you handle commands that require confirmation?

### ISSUE THREAD

**Issue by lukeredpath** [ReactiveCocoa/ReactiveCocoa#1160]
I'm sure there must be a more reactive way of dealing with this but I can't get my head around it.

I have a UIButton that performs a destructive action - a deletion, in this case. My view model has a `deleteCommand` property that returns a command that performs the deletion and wiring the button to the command is straightforward.

However, what I'd really like to happen is when the button is tapped, a confirmation `UIAlertView` is displayed and if the user hits OK, the deletion is performed or if they hit Cancel, it is not.

This "confirmation" behaviour feels like it belongs in the view model as it's a fundamental part of my view's behaviour - I do not want to allow deletion without confirmation first.

However, the specifics of how I obtain that confirmation (e.g. a `UIAlertView`) do not belong in the view model as it shouldn't know anything about the view. It seems like the actual presentation of the alert belongs in the view controller.

So is there a nice, elegant way of doing this, such that I can still have one single RACCommand that represents my deletion with confirmation that I can bind to my `UIButton`?

**Comment by haifengkao** [comment]
@sprynmr I did try your answer. However, there is something puzzling me.
The signal returned by the block will never complete (`self.confirmationCommand.executionSignals.switchToLatest`).  It means the command will always stay in executing mode, so it cannot execute any other commands.

How to you make the following code working in practice?
```
self.deleteCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id objectToDelete) { 
    [return self.confirmationCommand.executionSignals
        switchToLatest]
            flattenMap:^id(NSNumber *confirmed) {
                if(confirmed) {
                    return [self deleteObject:objectToDelete];
                } else {
                    return [RACSignal error:someErrorWithAMessageMaybe];
                }
            }];
}];

```

**Comment by sprynmr** [comment]
@haifengkao add something to control the lifecycle, like a `take:1` after `switchToLatest`

**Comment by sprynmr** [comment]
Also watch out for a retain cycle there. @strongify/weakify your multiple references to `self`
