### ISSUE TITLE
Question: How would you monitor an entire object hierarchy for reactive changes?

### ISSUE THREAD

**Issue by hokster7** [ReactiveCocoa/ReactiveCocoa#1195]
Think of how Google Drive saves your document automatically, no matter what changes you make. I want to implement that sort of auto-saving functionality with ReactiveCocoa.

Let's call our document class `Foobar`. It's got a bunch of fields, and those fields have sub-fields, and those sub-fields may reference to each other, and so on (no cycles though). They're all hooked up to various View Controllers and View Models etc.

This would be possible if I watched practically every field under the `Foobar` object:

``` objc
// Foobar.m
[RACSignal merge:@[
RACObserve(self, field1),
RACObserve(self, field1.subfield1),
RACObserve(self, field1.subfield2),
RACObserve(self, field1.subfield2.subsubfield1),
RACObserve(self, field1.subfield2.subsubfield2),
RACObserve(self, field1.subfield2.subsubfield3),
RACObserve(self, field1.subfield2.subsubfield4),
RACObserve(self, field1.subfield3),
RACObserve(self, field2)
...] doNext:^(id){
   [self save]; // perform automatic saving
}];
```

However, surely there's a better way of doing this. While the code above is not great, for a few reasons.
- it's not that DRY
- if at any point I add any new fields anywhere in the hierarchy, I will also have to remember that I must add an entry to this massive list

Is there a shorter way of expressing "watch this object and all of its subfields"? I'm imagining:

```
RACObserveDeepObjectChange(self);   // sends Unit whenever any field or its subfields is changed
```

Can you see another way to do this?

**Comment by xilin** [comment]
@Coneko Thanks for your reply. But it seems that `RACObserve(self, self)` cannot work?
