### ISSUE TITLE
RACObserving an NSMutableArray

### ISSUE THREAD

**Issue by hokster7** [ReactiveCocoa/ReactiveCocoa#1197]
Basically, I'm trying to do #772 but I call `reloadData` whenever a `NSMutableArray` is edited.

I'm read that `NSMutableArray` doesn't fire off any KVO signals and so RAC cannot react to them.

The question is, then, what's the workaround?

**Comment by haifengkao** [comment]
You can use [KVOMutableArray](https://github.com/haifengkao/KVOMutableArray) to generate signal for NSMutableArray
