### ISSUE TITLE
RACCommand execution signal sends completed on error

### ISSUE THREAD

**Issue by stel** [ReactiveCocoa/ReactiveCocoa#1210]
This problem has already been mentioned in #805 but I would like to clarify whether this is a problem of the framework or am I doing something wrong.

I have the following code that prints "completed" even if the signal failed.

```
RACCommand *command = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
    return [RACSignal error:[[NSError alloc] init]];
}];

[command.executionSignals subscribeNext:^(RACSignal *signal) {
    [signal subscribeCompleted:^{
        NSLog(@"completed");
    }];
}];

[command execute:nil];
```

The documentation says that errors will be sent upon `errors` signal, but is it correct to send completed to `executionSignals`'s signal in this case?

So and whats the best way to handle succeeded commands?

Thanks!

**Comment by haifengkao** [comment]
for future visitors, there is no 3.0 :(

**Comment by wangpeiyan** [comment]
where 3.0 ?

**Comment by andersio** [comment]
For the Objective-C codebase, please visit [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC/).
