### ISSUE TITLE
How to avoid unsubscribe after catch error or resubscribe

### ISSUE THREAD

**Issue by vincentsong** [ReactiveCocoa/ReactiveCocoa#1218]
Hi Guys,

  I have a some code like below

```
RAC(self, A) = [RACObserve(self, B) flattenMap:^id(id param) {
    return [self doSomthingToGetA:param];// this may throw an error
}] catch:^RACSignal *(NSError *error){

    //do some other things
    return [RACSignal return:nil];
}
```

when the error happened, next time I cannot get the signal for B anymore. So my question is there any way to avoid unsubscribe after catch error? Or do I need to use any other methods such as then: or something else?

**Comment by ChaosLin** [comment]
Excellent solution!Thank mdiep :)@mdiep
