### ISSUE TITLE
bufferWhile:

### ISSUE THREAD

**Issue by epatey** [ReactiveCocoa/ReactiveCocoa#1265]
I've recently written `bufferWhile:(RACSignal *)bufferingEnabled` that is very similar to `bufferWithTime:onScheduler:`. Instead of buffering for a period of time, it buffers while `bufferingEnabled` is YES. Like `bufferWithTime:onScheduler` it's critical that it flushes the buffered values when `bufferingEnabled` fires NO.

I've got it working with my own `createSignal:` code, but I think I should be able to do it as a composition with `if:then:else:` and `collect`. What I couldn't figure out, though, was how to make sure the collected values got sent when buffering stopped.

Any thoughts?

**Comment by themackworth** [comment]
@epatey how did this signal end up working out for you?
