### ISSUE TITLE
Instructions for using the library in a project in Xcode

### ISSUE THREAD

**Issue by jobrienski** [ReactiveCocoa/ReactiveCocoa#13]
I'm sort of a newbie to Xcode, but it's not obvious how to include this library in your project.  Some other libraries I have been able to drag and drop into the Frameworks section.  This one seems like you have to install it as a subproject.  When I followed these instructions, however, I got errors: http://yannickloriot.com/2011/04/how-to-install-zxing-in-xcode-4/.  Some instructions in the README.md would be great.
Thanks.

**Comment by hanpagnarith** [comment]
zz
