### ISSUE TITLE
Conform to reactive-streams.org back pressure interface

### ISSUE THREAD

**Issue by Coneko** [ReactiveCocoa/ReactiveCocoa#1320]
Looking up how RxJava switched over to serialising notifications without synchronisation I ended up at reactive-streams.org.

They're trying to design a barebones interface for asynchronous pull-push streams to facilitate interop between stream libraries.

While initially aimed solely at JVM languages they're broadening the scope now: https://github.com/reactive-streams/reactive-streams/issues/45

Back pressure has never been a high priority for us, but we have looked into it a couple of times. Discussing it with other implementers of RX-like libraries could lead us to a nice solution.

**Comment by vyshane** [comment]
Reactive Streams [has just hit 1.0](http://www.reactive-streams.org/announce-1.0.0).

**Comment by kastiglione** [comment]
Thanks @vyshane. However this can be closed. ReactiveCocoa doesn't aim for API compatibility with other stream based libraries.
