### ISSUE TITLE
Incompatible with Pixate Freestyle

### ISSUE THREAD

**Issue by devknoll** [ReactiveCocoa/ReactiveCocoa#1405]
Here's a [reproduction case](https://github.com/nikita-leonov/pixate-associated-objects-issue). Pixate uses swizzling too, so a ```UITableViewCell``` becomes a ```PXUITableViewCell_UITableViewCell``` class.

Right now, you will get a ```[UITableViewCell rac_alias_prepareForReuse]: unrecognized selector sent to instance``` exception on [this line](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoaFramework/ReactiveCocoa/NSObject%2BRACSelectorSignal.m#L85).

I'm not sure if the underlying problem lies in Pixate or ReactiveCocoa. Does anyone know how these frameworks could be made compatible?

**Comment by anton-matosov** [comment]
I am currently trying to reborn `freestyle` project in StylingKit/StylingKit
@jspahrsummers what is the recommended way to swizzle that is compatible with `rac_signalForSelector:`?

**Comment by jspahrsummers** [comment]
Sorry, I no longer contribute to this project, and all of my knowledge about this has been paged out. Maybe one of the other contributors would know.

**Comment by anton-matosov** [comment]
Got it. Thanks for quick reply.

**Comment by anton-matosov** [comment]
I have verified this issue with latest version of https://github.com/StylingKit/StylingKit framework (derivative of freestyle 2.1.4) using the test project from https://github.com/Pixate/pixate-freestyle-ios/issues/125 and issue doesn't exit there. Forwarding works perfectly fine

**Comment by RuiAAPeres** [comment]
@anton-matosov if you need further assistance, please open a new issue.

**Comment by anton-matosov** [comment]
Just For Information: the issue was resolved by using @selector(method:) while forwarding to callSuper(....) instead of _cmd which was modified.
