### ISSUE TITLE
Why does this snippet leak memory ?

### ISSUE THREAD

**Issue by codeboost** [ReactiveCocoa/ReactiveCocoa#1437]
There is this class method:
	
	+ (UIBarButtonItem*)navItemWhichAddsNewAction{

    UIBarButtonItem* addActionButton = [[UIBarButtonItem alloc] initWithImage:[UIImage imageNamed:@"icon_add"] style:UIBarButtonItemStylePlain target:nil action:nil];
    addActionButton.rac_command = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
        return [RACSignal empty];
    }];
    return addActionButton;
}

Then, in viewDidLoad(), I assign the result of this method to the navigationItem:
	
	self.navigationItem.rightBarButtonItem = [MyClass navItemWhichAddsNewAction];
	

If I then profile the app with Instruments, the rac_command block above is always reported as allocated and it doesn't get deallocated when the viewcontroller goes away.

Why ?

**Comment by schickling** [comment]
@codeboost did you find a solution for this eventually?

**Comment by codeboost** [comment]
I can't remember what solution I took in the end. I'll close the issue now.
