### ISSUE TITLE
100% reproducible crash in RACSerialDisposable

### ISSUE THREAD

**Issue by epatey** [ReactiveCocoa/ReactiveCocoa#1455]
When you run the following code with zombies turned on, you will immediately crash sending a `retain` to a deallocated `RACDisposable`.

```objective-c
RACSerialDisposable *serialDisposable =  [[RACSerialDisposable alloc] init];
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
  while (YES) {
    [serialDisposable swapInDisposable:[RACDisposable disposableWithBlock:^{}]];
  }
});

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
  while (YES) {
    NSLog(@"%@", serialDisposable.disposable);
  }
});
```

The issue is that `-[RACSerialDisposable disposable]` is not thread safe. It essentially returns the current value stored in `void * volatile _disposablePtr`. All other code that manipulates `_disposablePtr` does so with the safety of `OSAtomicCompareAndSwapPtrBarrier`.

The following code in `rac_observeKeyPath:options:block:` crashes in my app in the field occasionally because of this bug.
```objective-c
RACCompoundDisposable * (^firstComponentDisposable)(void) = ^{
  return (RACCompoundDisposable *)firstComponentSerialDisposable.disposable;
};
```

I'm working on pull request with a failing unit test and fix. Should be ready within a day.

**Comment by joshaber** [comment]
Fixed by #1456 :boom:
