### ISSUE TITLE
Difference between RACChannelTo and [channelTerminal subscribe:]

### ISSUE THREAD

**Issue by skywinder** [ReactiveCocoa/ReactiveCocoa#1473]
Here is examples of code:
**_1**_

``` objc
RACChannelTerminal *channelTerminal = self.valueTextField.rac_newTextChannel;
RACChannelTerminal *channelTerminal2 = RACChannelTo(self.viewModel, value);
[channelTerminal subscribe:channelTerminal2];
[channelTerminal2 subscribe:channelTerminal];

[RACObserve(self.viewModel, value) subscribeNext:^(id x) {
    NSLog(@"x = %@", x);
}];
```

**_2**_

``` objc
RACChannelTo(self.valueTextField, text)= RACChannelTo(self.viewModel, value);

[RACObserve(self.viewModel, value) subscribeNext:^(id x) {
    NSLog(@"x = %@", x);
}];
```

From description of [RACChannelTo](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/ec8ff5fb5e76358c229f0af9699da9f462843d75/ReactiveCocoaFramework/ReactiveCocoa/RACKVOChannel.h#L50-53) I supposed, that this 2 samples do the same.

But in second case logging is not working, when I start typing something in textField.

Can you clarify, what the difference between this 2 examples?

**Comment by shyboy2012** [comment]
try RACChannelTo(self.viewModel, value) = self.valueTextField.rac_newTextChannel;
