### ISSUE TITLE
Update README with 3.0 changes

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1483]
Include some explanation of the split Objective-C and Swift APIs, because it'll be confusing to anyone starting with the project for the first time.

**Comment by neilpa** [comment]
I started to take a crack at this but the current README focuses heavily on KVO. That doesn't translate to Swift and I'm struggling to come up with good examples for introducing truly new people to the framework.

Anyone on @ReactiveCocoa/reactivecocoa have ideas for Swift-centric examples that we could use as replacements. The equivalent now would invovle `PropertyType` but I'm hesitant to start off with that.

**Comment by jspahrsummers** [comment]
A recurring example that I've really liked is the “throttled search field,” where typing should trigger a network call, but only one at a time, and only when you've paused your typing (or at least enough of an interval has passed).

That sounds like a good way to mix `Signal`s and `SignalProducer`s for illustration, too.

**Comment by jspahrsummers** [comment]
Regarding `PropertyType`, I don't think we can omit it entirely, but I would like to give it lower billing. An example demonstrating a “loading” flag might be illustrative.

**Comment by neilpa** [comment]
> A recurring example that I've really liked is the “throttled search field,” where typing should trigger a network call, but only one at a time, and only when you've paused your typing (or at least enough of an interval has passed).

I like this idea. It also lends itself to starting from a naive approach and slowly building up the different pieces.

**Comment by neilpa** [comment]
I want to call out #2060 here in case there's anything we can do here to limit that sort of confusion.

**Comment by jspahrsummers** [comment]
@neilpa Were you working on this? I'm happy to start on it, but I don't want to conflict with any work that might be in progress.

**Comment by neilpa** [comment]
I barely started to work on it back then and didn't make any real progress.

**Comment by jspahrsummers** [comment]
:ok_hand:
