### ISSUE TITLE
Investigating RAC Performance (with example project)

### ISSUE THREAD

**Issue by twocentstudios** [ReactiveCocoa/ReactiveCocoa#1503]
We've been rewriting portions of the Timehop iOS app in MVVM with ReactiveCocoa. So far we've replaced the settings, sign up, and login screens as well as some lower-level services. However, the primary screen of the app (essentially a table view with varying social media related content types) has presented performance problems in several different places that we haven't been able to work around. We're hoping to get some help narrowing down exactly where these performance problems lie.

> I posted an [issue](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1419) a little while back about one of the specific issues. I ended up replacing all the `RACCommand`s with blocks in the situation I described there.
### [Userlist](https://github.com/timehop/Userlist)

I've tried to strip down a subset of these problems and present them in the smallest possible example project I could. [Userlist](https://github.com/timehop/Userlist) is a single table view app that shows a list of randomly generated names and avatars in stock `UITableViewCell`s. I'm hoping this example project can help illuminate the issues we've been having in the Timehop app.

I would encourage anyone to browse the code, clone the project, and run it on your devices if you've got the time and are interested in helping investigate. I'm going to run through the basics below and talk about what I've found so far.

![screen-shot](https://cloud.githubusercontent.com/assets/603478/4415831/ca6c2852-4532-11e4-9c0d-6efc99c6c77b.png)
### Basics

There's only one model object: `User`. It has a name string and an image URL.

The `UserViewModel` asynchronously converts the image URL into an image.

The `UserCell` displays the name and image of its assigned UserViewModel. Cells are reused normally.

`UserController` generates and returns an array of randomly generated `User` objects in a signal.

`UsersViewModel` fetches the `User`s array from `UserController` and maps this array to an array of `UserViewModel`s.

`UsersViewController` handles the table view, observes the `UserViewModel` array, attaches `UserViewModel`s to `UserCell`s, and lets `UserViewModel`s know when their cells are visible.

`ImageController` wraps `SDWebImage` image network fetching and caching and provides a signal interface.
### Motivations

The view and view model hierarchy is significantly more complicated in Timehop than this example app. It has to handle tap events from deep within view hierarchies, display lots of images (sometimes in embedded `UICollectionView`s), and present several cell layouts too. The goal was to use very modular components at all levels of the view and view model hierarchies, maintain a strict separation of concerns between views and view models, and use ReactiveCocoa conveniences to dramatically reduce the amount and complexity of code in this module. 

My approach so far has been to use as much ReactiveCocoa as I can, and after discovering performance problems, slowly replace ReactiveCocoa with imperative code in sections. Unfortunately, it still hasn't gotten us to a viable point yet.

Userlist purposefully makes liberal use of the ReactiveCocoa conveniences I'd like to use in the Timehop app (e.g. `RACObserve`, RAC bindings,`RACCommand`s, RVM, etc.), in the hopes that someone can tell me I'm doing something wrong with them that's causing problems.
### Goals

I've been testing on 5th gen iPod Touches and an iPhone 4S as the baseline. In a perfect world, I'd like to get to 60fps table view scrolling on both these devices and have the time from vending of models to creation of view models be under a second for someone with ~20 pieces of content. In reality, I'd just like to get to the point where any dropped frames are due to layout/display code that can be progressively enhanced. Or more specifically, it should perform "better" than the current Timehop app.

I'd expect the Userlist to easily do 60fps. My goal in writing this is to find a way to get it there and find a way to apply those lessons to Timehop.
#### Tentative Problem Spaces

I've been doing basic performance tests on the iPhone 4S with Userlist. Userlist presents a couple of the same performance problems I've seen in the Timehop MVVM prototype. As a quick summary, I've partially narrowed these down to:
- Creating many non-trivial view models.
- Creating and executing `RACCommand`s in view models.
- Observations of view model properties by cells.
- Triggering subscriptions based on the `active` property of view models.
#### Test Setup

I've chosen 100 user objects to test with. 100 is a comfortable maximum for the amount of content a Timehop user has. 100 table cells also allows for room to judge scrolling performance. (An even better stress test is 500 user objects though. The particular pain points may be easier to identify with 500.)

Tests were performed with the project building in Release mode. The Core Animation and Time Profiler were added to Instruments. I ran the project on an iPhone 4S.

The first test was a basic load up, scroll down, scroll up, and repeat with a little time in between each scroll.

![userlist-full-run](https://cloud.githubusercontent.com/assets/603478/4415882/1a0f21e2-4534-11e4-985f-afa04dcd69c8.png)
[Instruments trace](http://cl.ly/3z2k1o0U421u) _(updated with symbols)_

In the second test I simply wanted a better visual separation of the user object generation section against the user view model generation. For a quick and dirty solution, I placed a 10 second delay `RACSignal` operation following the random user object generation to accomplish the seperation.

![creating-models-view-models](https://cloud.githubusercontent.com/assets/603478/4415893/462c7450-4534-11e4-8dc5-088e49fc1fa1.png)
[Instruments trace](http://cl.ly/0Z2S203M0Y3Y) _(updated with symbols)_

I'll be the first to admit that I'm not particularly well versed in digging into Instruments (I've learned a lot with this project though!). I'm also not that familiar with the implementation details of ReactiveCocoa. Therefore, I won't speculate too much on what I think is going on.

Memory use is in line with what I would expect. I'm not getting thrashing memory warnings or anything. I imagine in a more complex project I would want to purge the images from each inactive UserViewModel when receiving a memory warning. But in this example, everything seems to be nominal.
#### Imperative Example Benchmark

One thing I haven't done yet is write Userlist in plain MVC without ReactiveCocoa as a benchmark. I've been hesitant because I'm unsure if it will be possible to compare apples-to-apples so to speak. Part of the allure of ReactiveCocoa is the experience writing and maintaining the code, along with the potential for fewer state-related bugs. Each of these is difficult to measure directly. I will go ahead and write it if my relative judgement of what is "slow" on 3-4 year old devices is off (not doubting that it is).
#### Review

Like I mentioned above, my goal is to tackle these performance issues one step at a time. I'd be very grateful for any feedback on the example project or any related lessons learned working with ReactiveCocoa and MVVM in large iOS projects. 

Thanks in advance for any help! (And apologies for the length of this write up.)

**Comment by anton-matosov** [comment]
Did anyone had a chance to check Swift API performance with the reusable cells?

**Comment by NachoSoto** [comment]
I recently went through some optimization work when using signals in `UICollectionViewCell`s. Once I realized (thanks to @jspahrsummers) that the bottleneck was that I was using `SignalProducer.buffer` unnecessarily, and switched to `Signal.pipe`, I can't notice any performance problems :)

**Comment by adc-amatosov** [comment]
Thanks! That sounds great!
