### ISSUE TITLE
How to retrigger an RACReplaySignal when it failed?

### ISSUE THREAD

**Issue by limbo-lab** [ReactiveCocoa/ReactiveCocoa#1547]
I've read [this](http://stackoverflow.com/questions/14066651/how-to-using-reactivecocoa-to-transparently-authenticate-before-making-api-calls/14072445#14072445). The solution is simple yet elegant and powerful. Now the question is: what if the `getToken' signal failed due to network problem or anything else? In which case all of the rest api requests would fail. To retrigger the side effect when an new subscriber coming (the previous batch of subscribers had already been sent error) would probably be better.

**Comment by jerryzhoujw** [comment]
What if token have a duration, the token get from [self getToken] will overdue after a duration.  Looks like the replay will always give the previous token.
