### ISSUE TITLE
2.3.1 broken on 10.7 - new release?

### ISSUE THREAD

**Issue by esad** [ReactiveCocoa/ReactiveCocoa#1556]
Hi,

I'm about to ship an app that uses v2.3.1 of RAC and have just discovered that #1321 also happens on 10.7. 

I tried pointing the current Podspec for 2.3.1 to :head to see if the fix works for 10.7, but the directory structure changed so it won't work.

Is there a new release planned soon?

**Comment by tangyi** [comment]
@Spetruk if my project's deployment target is iOS 7.0, which version should i use?

**Comment by Spetruk** [comment]
@tangyi i use 2.5

**Comment by tangyi** [comment]
@Spetruk  your project's deployment is iOS7? but the document of 2.5 says it not support iOS7. https://github.com/ReactiveCocoa/ReactiveCocoa/tree/v2.5#system-requirements

**Comment by Spetruk** [comment]
@tangyi i found it in my _podfile.lock_. You can try to write in you _podfile_ 
**platform :ios, 7.0**
**pod 'ReactiveCocoa', '~> 2.0'**
