### ISSUE TITLE
ReactiveCocoa does not work well with NewRelic agent (or vice versa)

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#1561]
I didn't investigate it deeply yet, but due to invocation swizzling in RAC and some internal behaviors in NewRelic (http://newrelic.com) agent cause application to froze right after launch. Apparently it is going into infinity loop:
- CPU consumption — https://www.evernote.com/shard/s70/sh/2397ba6c-6aad-447a-bf2b-0d2bee044522/941ccb0eb4d15339ce39f9c790cc72fb
- Stack for Thread 1 — https://www.evernote.com/shard/s70/sh/d7e4c61a-90d6-43ed-a91e-f0bde38bcffe/2deb01702f34b219409d3cfe5dc3ae58

I reported it to NewRelic as well with issue id 117914

**Comment by sprynmr** [comment]
I assume there's been no changes on this on either side? Just ran into the same issue. We'll be reporting it to new relic, but it sounds like they aren't interested in changing it.

**Comment by jspahrsummers** [comment]
The RAC problem is extremely hard (if not impossible) to fix without libffi. The suggested workaround is to use `RACSubject` instead of `-rac_signalForSelector:` for affected code.

**Comment by sprynmr** [comment]
Yeah that's what we're doing. Just cumbersome. Love `signalForSelector` for lifecycle methods. Understood on not wanting to introduce a dependency. Maybe @buchananbryce will throw us some love and add an exception for RAC.

**Comment by fightingmonk** [comment]
Hi @sprynmr. We're not opposed to adding special case support for RAC. We do have to consider the performance implications and how popular the framework is. Please do file a report / request so we've got your vote counted.

**Comment by sprynmr** [comment]
@fightingmonk Noted. We sent our request along through proper channels. Thanks!

**Comment by mdarnall** [comment]
Seeing this issue when using:

```
