### ISSUE TITLE
ReactiveCocoa setup with submodules with latest code

### ISSUE THREAD

**Issue by FawadHa1der** [ReactiveCocoa/ReactiveCocoa#1596]
So this is my setup.

App + static library. I am including ReactiveCocoa as a submodule to the static library. The readme instructions says to use libReactiveCocoa-iOS.a where there is none in the targets only frameworks. When I include the framework I get the error "cannot build module" on ReactiveCocoa.h

**Comment by szl-926929** [comment]
I meet the problem. I use xcode7.do you solve the problem?
