### ISSUE TITLE
Support iOS 7

### ISSUE THREAD

**Issue by kastiglione** [ReactiveCocoa/ReactiveCocoa#1629]
As discussed in #1413 and #1625, it seems there is a discussion to be had about which version of iOS should be RAC's baseline.

It looks to me that RAC itself supports iOS 6 and up, that it's only the switch to an iOS framework in the Xcode project that changed the baseline. Why did we change to a framework over a static library? Is that not favoring new projects over existing ones? Seems like the wrong tradeoff to make. I'm no doubt missing some context to paint the full picture.

Can we not go back to a static library target for iOS? That won't hurt iOS 8 apps.

**Comment by kylerobson** [comment]
@tonyarnold  I looked through the podspecs and only saw one for 3.0 alpha 1 that only supports iOS8. Where is the podspec for using 3.x on iOS7?

**Comment by andersklenke** [comment]
@kylerobson as I read this thread, 3.x is iOS8 and OS X 10.8 only.

**Comment by jspahrsummers** [comment]
With Swift, we definitely won't be able to support a static library, but we could reduce the iOS deployment target—if only to make it clear that we don't inherently require iOS 8.

I took a brief look at this, and it looks like LlamaKit is requiring iOS 8+ right now, so I suppose this is blocked by https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1887.

**Comment by jspahrsummers** [comment]
Oh, but how would importing a Result type even work, then? :confused:

**Comment by jeffasd** [comment]
就是说iOS7不支持了是不是？

**Comment by tangyi** [comment]
@jeffasd 如果是Objective-C的话，接着用2.5版本没问题

**Comment by yinnieryou** [comment]
@jeffasd Yes, iOS 7 is not support. I tried add the source code to my project but it crashed. But you can still use ReactiveCocoa 2.5 which support iOS 7.

**Comment by hunght** [comment]
@jspahrsummers i try to support ios 7, but i don't know what version should be use to support ios 7, could you help me with this ?
