### ISSUE TITLE
Thoughts on "The Great Swiftening" after a few hours playing with it

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#1650]
I recently played around with [RAC 3.0](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/1382) and wanted to share some thoughts :) please keep in mind that this is only after a few hours of use, so most of what I bring up is probably due to me still being too used to `2.0`, and possibly to some lack of understanding on some of the underlying concepts here, so bear with me! :D

First some background: I used RAC 2.0 extensively for Elevate, in Objective-C, and for the past few months in Swift at Khan Academy. It’s obviously not great to have to do dynamic casts from `AnyObject!` all the time, but it’s better than nothing!
So far I’m really excited with what I’ve seen, but hopefully my thoughts can help make the transition to this new version easier for me and for other people :)

I’ve been trying to follow the discussions about the hot/cold separation for a while, and overall I think it’s a huge step forward.
These are some things I didn’t understand very well as I was trying to figure out the internals of each of the two types. I imagine most of these will be explained in the README though.

These are the docs on both:
```swift
/// A stream that will begin generating Events when a sink is attached, possibly
/// performing some side effects in the process. Events are pushed to the sink
/// as they are generated.
///
/// A corollary to this is that different sinks may see a different timing of
/// Events, or even a different version of events altogether.
///
/// Cold signals, once started, do not need to be retained in order to receive
/// events. See the documentation for startWithSink() or start() for more
/// information.
public struct ColdSignal<T> 
```
```swift
/// A push-driven stream that sends the same values to all observers.
///
/// Generally, hot signals do not need to be retained in order to observe the
/// values they send, but there are some exceptions. See the documentation for
/// observe() and HotSignal.weak() for more information.
public final class HotSignal<T>
```

The more I read those, the more confused I am :P Possibly the most important word in those two is `class` VS `struct`. I get that fundamental difference of `value type` ==> `different work per subscriber` VS `reference type` ==> `same to all subscribers`, but I can’t help to get confused by the rest of the docs and some other differences in the two types.

Like I said, it’s possible that I’m still too used to these two different concepts being only one (`RACSignal`), but I was surprised to see that not only they’re different conceptually, but also their APIs and functionality:
- Method to observe values: `start` VS `observe`.
- How values are “streamed”: `Event<T>` VS `<T>`.
- Corollary of the previous point: completion and possible errors VS only values.
- Only `ColdSignal` have `evaluateOn`.

I’m sure there are very good reasons for all that, just thinking aloud! Hopefully other people will get confused by similar things and clearing-up those will help.

This is from the `2.0` docs, which I think explains things really well:
```
Signals are cold by default, meaning that they start doing work
each time a new subscription is added.
This behavior is usually desirable, because it means that data
will be freshly recalculated for each subscriber,
but it can be problematic if the signal has side effects or the
work is expensive (for example, sending a network request).
```

That makes a lot of sense. I’ve used `- [RACSignal replay]` and  `- [RACSignal replayLast]` a lot for cases like described there. 
I thought that being able to use a `HotSignal` explicitly now would be a better way to implement such things, but then I stumbled upon `HotSignal.replay() -> ColdSignal<T>` and my head exploded :boom: Okay, that’s an exaggeration, but it made me question whether I was understanding Hot / Cold or not. I thought `ColdSignal` would replay the sent values to each subscriber? Why would `replay` be a method on `HotSignal` instead of `ColdSignal`?

Something else that I still haven’t completely grasped is memory management. I know it took me a while to completely get it in 2.0, so I’m sure it’s the case for the new version too. However,  how memory is managed differently between Cold/Hot was also not clear at first glance.

I can’t stress this enough though: this is some amazing work. I love how thin the API is, and yet it’s still as powerful as ever. I hope it’s clear that I’m not criticizing the work or anything! just thinking aloud about the things I failed to understand :D

**Comment by jspahrsummers** [comment]
Basically addressed with #1655.
