### ISSUE TITLE
NSNotification RAC  issue

### ISSUE THREAD

**Issue by ghost** [ReactiveCocoa/ReactiveCocoa#1651]
Hello sir,

I use the following method to simplify the notification process below:
[[[NSNotificationCenter defaultCenter] rac_addObserverForName:xx object:nil] subscribeNext:^(NSNotification *notification) {}];

I add the code above in page B, when I do the following: A-> B-> A-> B-> A, when I post the notification, I find the contents inside will be executed twice .

Is there a way to manually remove the listener notifications inside?

Thank you.

**Comment by DaidoujiChen** [comment]
thanks @jspahrsummers,

i am face the same issue.
