### ISSUE TITLE
Migrating from delegate based architecture to signals.

### ISSUE THREAD

**Issue by BowlOfChilli** [ReactiveCocoa/ReactiveCocoa#1659]
This is a bit general question. My app has a search controller and a lot of view controllers which register to searchcontroller's delegate set. There is one shared instance of the search controller but any number of view controllers since all of them need the results. For example a few among them are the map view controller and table view controller display the same result set. 

Any class instance can fire a search and results will be propagated to these client view controllers. Now when I try to migrate this to use Signals and it seems a bit tricky.  I know what a multicast connection is (I think). I have tried it but it there in lies the issue of sharing the new multicast connection with existing view controllers which want the results as well.

more concretely,

Class B invokes a search and in addition to class itself the results need to go to mapview and tableview controllers as well. Class B gets the multicast connection but informing all the clients to subscribe to this new signal seems weird....How would you guys do it ?

 I hope I have explained it. if not I can try again.

**Comment by BowlOfChilli** [comment]
Kind a still stuck on this one, how does one accomplish broadcasting results to multiple view controller? If we make a property on the sharedInstance of the search controller of type RACSignal. Wouldnt that signal be a new one every time a new search request is fired? So cant subscribe to that property then right ?

**Comment by jlawton** [comment]
If I've misunderstood your aims, please let me know, but I think you have a central `SearchController`, which will be called to make searches from somewhere (maybe several places), and you want to update several points of UI with the latest results. If so, there are a few things you might do.

Maybe add a property to hold your latest search results on the search controller. This is nice, because it's obvious that observing this doesn't have side effects. It also caches, which may be good or bad.

```obj-c
@interface SearchController
+ (instancetype)shared;
// Updates every time a search completes. Listen with `RACObserve`
@property (readonly) SearchResult *latestSearchResults;
@end
```

Or maybe something more like `RACCommand`, though the internals of that are a little complex. It's less obvious that subscription doesn't have side effects, but it gives you signals, which might be useful for implementing spinners or whatever.

```obj-c
@interface SearchController
// All searches : signal<signal<SearchResult>>
@property (readonly) RACSignal *searches;
// A single search : signal<SearchResult>
- (RACSignal *)search:(id)query;
@end
```

Or you could try an adapter on an existing controller, using `rac_signalForSelector:fromProtocol:` or look at how `rac_delegateProxy` is created on some object types.

**Comment by BowlOfChilli** [comment]
@property (readonly) RACSignal *searches;
Cant be subscribed to in the sense whenever there is a new search, its a new signal. isnt it ? The older view controller are now subscribed to an older signal. Every search creates a new Signal. Is there a way to avoid it?

**Comment by jlawton** [comment]
Searches is a signal of signals in my example. Every search, it sends a new signal. Underneath, it'll be made by observing a property or using a `RACSubject` or something. That's how you inject searches into the system. It'd be used something like this:

```obj-c
[[controller.searches
    switchToLatest] // Subscribe to the latest results only
    subscribeNext:(SearchResults *results) {
        // Called on every search
    }];
```

or you could take more advantage of the inner signals:

```obj-c
RACSignal *searching = [controller.searches
    map:(RACSignal *search) {
        return [[RACSignal return:@YES]
            concat:[search then:^{ return [RACSignal return:@NO]; }]];
    }];

RAC(self, activitySpinner.hidden) = [searching not];
```

**Comment by BowlOfChilli** [comment]
Thanks for the hint, so now I am using RACCommand which allows me to inject new search parameters via execute I could not find a way through RACSubject. For the caller I return the signal returned from execute which they then subscribe to and all the listening  view controllers do something like this 

    [[[SearchController sharedInstance].searchCommand.executionSignals
      flatten] subscribeNext:^(id x) {
        
    } completed:^{
        
    }];

**Comment by jlawton** [comment]
That seems reasonable to me.
