### ISSUE TITLE
Executing a RACCommand on a background thread can result in a crash

### ISSUE THREAD

**Issue by texel** [ReactiveCocoa/ReactiveCocoa#1660]
I have timer that periodically executes a RACCommand on a background thread. Every now and again, the app crashes while managing KVO notifications for its array of active execution signals. It seems like there's a race condition when something is being deallocated on another thread, but I'm not exactly sure what (if I turn on zombies, the issue strangely doesn't present itself). 

I've ginned up a little app that shows a reduced case: https://github.com/texel/RACTimerCrash

I can work around this by always executing the RACCommand on the main thread (which is probably the intent anyway) but if that's the case then the documentation should probably be updated.

Thanks!

**Comment by joshaber** [comment]
Hopefully fixed by #1627. :pray:

**Comment by texel** [comment]
Verified that this is fixed. Thank you so much!!! :grinning: :star2: :+1:

**Comment by joshaber** [comment]
Awesome, thanks for verifying!
