### ISSUE TITLE
RACSubject / switchToLatest / replayLast

### ISSUE THREAD

**Issue by zdavison** [ReactiveCocoa/ReactiveCocoa#1662]
I have a set of signals that can be re-created at any time, internally, and I'd like to expose these externally through a signal-of-signals so that any subscribers don't need to resubscribe if these internal signals change.

The sensible way to do this seemed to be using `RACSubject`s of signals, and expose external facing signals created from the subjects using `switchToLatest`, eg:

```swift
  public var weight:      RACSignal {
    return _weightSignals.switchToLatest()
  }

 private var _weightSignals  =   RACSubject()

 //// ..... later

    let weight = createSignal()

    _weightSignals.sendNext(weight)
```

However, this poses a few problems, RACSubject doesn't replay values back to new subscribers, so unless subscribers are already subscribed when the first signal is sent, this doesn't work. I thought that using `_weightSignals.switchToLatest().replayLast()` might work, but it doesn't, and I'm unsure exactly why.

This concept also doesn't seem to work anyway, because if i push a new signal through `_weightSignals`, my subscribers don't seem to resubscribe to the new latest, and I'm not sure why that is the case either.

Am I going about this the right way?

**Comment by jspahrsummers** [comment]
I'm confused—are you trying to expose a signal _of signals_ to the external world, or just the merged signal?

**Comment by zdavison** [comment]
I only need the latest signal exposed to the outside world, I'd just like the ability for existing subscribers to be able re-subscribe to the latest signal sent on the internal signal of signals, which is what I thought `switchToLatest` was for, but I feel like I've misunderstood something along the way.

**Comment by jspahrsummers** [comment]
`switchToLatest` will forward events from the inner signal _sent last_, but this is different from replaying. If you don't replay the switched signal, it's like you switched the signal-of-signals separately for each subscriber, and they'll see whichever events are unique to that subscription.

If you want subscribers to always see the latest _signal_ sent, you should `-replayLast` _before_ switching. If you additionally want to replay the values of that latest signal, you also need to replay the switched signal.

**Comment by zdavison** [comment]
So I've actually tried that as well, which was my first inclination, and that doesn't seem to work either, the behaviour I see with the following example:

```swift
  public var switchedSignal: RACSignal {
    return _signals.replayLast().switchToLatest()
  }
  
  private let _signals = RACSubject()
  
  // ........
  
  let newSignal = createSignal()
  _signals.sendNext(newSignal)
  
  switchedSignal.subscribeNext{
    NSLog("FIRED: \($0)")
  }
```

is that the subscription on `switchedSignal` never fires. How I'd expect this to behave is that the `replayLast()` would replay the last inner signal, and `switchToLatest` would forward the values sent by *that* signal onto the subscription.

But it doesn't, so I must be misunderstanding something.

**Comment by jspahrsummers** [comment]
What are you expecting to see appear on `switchedSignal`, in that example? It looks like (depending on the implementation of `createSignal`) you're sending an _empty_ signal to be switched to.

Even if it's not empty, if that inner signal does not replay its values, subscribers to the switched result might miss them.

**Comment by jspahrsummers** [comment]
You may want to check out http://introtorx.com/Content/v1.0.10621.0/12_CombiningSequences.html#Switch. It's for Rx, but the concepts are similar.
