### ISSUE TITLE
Disabling a RACCommand after a successful completion

### ISSUE THREAD

**Issue by amitai-hoze** [ReactiveCocoa/ReactiveCocoa#1666]
Hi, I'm using RAC 2.3.1 (I need iOS 7.0 compatibility). I have accomplished disabling the `RACCommand` after a successful completion by using this code, where `networkRequestSignal` is a cold signal that performs a network request when subscribed to and `validInputSignal` is a signal used to initially enable the command when its input (some text field's text) is valid.

```objective-c
self.connection = [self.networkRequestSignal publish];
self.replaySignal = [self.connection.signal replay];
RACSignal *networkRequestCompletedSignal =
[[RACSignal return:@(FALSE)] takeUntilReplacement:[self.replaySignal then:^RACSignal *{
        return [RACSignal return:@(TRUE)];
    }]];

RACSignal *commandEnabledSignal = [[RACSignal combineLatest:@[[networkRequestCompletedSignal not], validInputSignal]] and];

@weakify(self)
self.networkRequestCommand =
[[RACCommand alloc]
 initWithEnabled:commandEnabledSignal
 signalBlock:^RACSignal *(id input) {
     @strongify(self)
     [self.connection connect];
     return self.replaySignal;
 }];
```

The `initWithEnabled:signalBlock:` command subscribes to the `commandEnabledSignal`, so I'm using the `connection` and the `replay:` to avoid performing the network request when the `RACCommand` initializes. It seems very hacky, is there a cleaner or more correct way of doing this?

Also, using this implementation, it seems I have to retain the `self.connection` or RAC's memory management (in `RACDynamicSignal.m` in `invalidateGlobalRefIfNoNewSubscribersShowUp` in `RACCheckActiveSignals();` according to Xcode's debugger) sets it to `nil`. What am I doing wrong?

**Comment by jspahrsummers** [comment]
In general, that approach seems reasonable (if I understand correctly what you're trying to do), but I'll note that this isn't super useful:

```objc
[self.connection.signal replay]
```

It'll work, but the more idiomatic way to express that is to use `[self.networkRequestSignal multicast:[RACReplaySubject replaySubject]]` instead of `-publish`. Then, `self.connection.signal` will _always_ replay.

**Comment by Tiger6688** [comment]
how about this:
```objectiveC
RACSignal* networkRequestSignalReplay=[self.networkRequestSignal replayLazily];
RACSubject* networkRequestComplete=[RACSubject subject];
RACSignal *commandEnabledSignal=[RACSignal merger:@[validInputSignal,networkRequestComplete]];
@weakify(self)
self.networkRequestCommand =
[[RACCommand alloc]
 initWithEnabled:commandEnabledSignal
 signalBlock:^RACSignal *(id input) {
     @strongify(self)
     return [networkRequestSignalReplay doComplete:^{
                [networkRequestComplete sendNext:@(FALSE)];
     }];
 }];
```

**Comment by amitai-hoze** [comment]
@jspahrsummers thanks! (also for the more idiomatic way, always in search of those.. :+1:)
@Tiger6688 it seems that using a subject to achieve this behavior is, though shorter, less functional and more imperative.. Thanks anyway for your time!

**Comment by jspahrsummers** [comment]
You shouldn't need to store the connection in a property, as long as you capture it strongly in any blocks that you want to use.
