### ISSUE TITLE
list view contains basic info and detail view contains detail info and share same viewModel

### ISSUE THREAD

**Issue by lzyy** [ReactiveCocoa/ReactiveCocoa#1668]
it's hard to conclude the situation in one sentence. suppose there is a Pinterest like app, the waterfall page use a viewmodel like `itemListViewModel`, when an item is tapped, detail view is pushed in, and share the same viewmodel, but the item has more info, so I want to replace the origin basic item to this detail item. but can't find a suitable way to do this.

this is my simplified viewModel

```objc
@interface ItemListViewModel
@property (nonatomic, readonly) NSArray *items;
@property (nonatomic, assign) NSInteger selectedIndex; 
@end
```

when used in a list view, the `items` are basic items (not comments for example), when item 1 is tapped, then detail page will send a request to fetch detail item info, when detail info fetched, i want to replace original basic info, but since `items` is an `NSArray`, i can't do this, but don't want to replace it with `NSMutableArray`, coz when add items into it, it's hard to monitor it.

so what's the property way to handle this situation?

**Comment by jlawton** [comment]
I would say you're right not to make it a mutable array. If you really want to do the replacement, you could use [KVC accessors](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/KeyValueCoding/Articles/AccessorConventions.html#//apple_ref/doc/uid/20002174-SW11), which are observable.

Before you do that, though, why are you mutating your VM? Are you going to use the extra information to update your list display? What do your items look like? Is this detailed info stored in the same type as the basic info, or are there two classes?

**Comment by lzyy** [comment]
@jlawton they are the same class, the item may look like this

```objc
@interface Item: NSObject {
@property propertyA;
@property propertyB;
...
@property propertyZ;
}
```

in basic mode, `property[A-K]` is filled, after fetching from web service a new detail item with `property[A-Z]` filled. now i want to use the new detail item to replace basic item in `items` array, one way is to iterate new item, then fill the new value to the basic model.but it's not elegant and tedious.

**Comment by ahoang** [comment]
If you modify the same instance of the item you've pulled details for, it will update it in the array as well.
