### ISSUE TITLE
Conditional Delay Question

### ISSUE THREAD

**Issue by lightice11** [ReactiveCocoa/ReactiveCocoa#1669]
I'm trying to wrap my head around the ReactiveCocoa framework, but I'm stuck on trying to figure out how to delay conditionally.

For example, I want to set a CADisplayLink pause property to false when an array is empty. Here is how I accomplished this :
        
    RACSignal *changeSignal = [self rac_valuesAndChangesForKeyPath:@keypath(self, projectiles) options:NSKeyValueObservingOptionNew observer:nil];
    
    RAC(self.displayLink, paused) = [changeSignal map:^id(RACTuple *value) {
        return @([((NSMutableArray *)value.first) count] == 0);
    }];

But before I pause the display link, I want to keep animating for a few seconds, so I added a `delay:2.5];` to the end of the map block.

Now I'm running into the problem that it's waiting 2.5 seconds to stop AND start the display link. I only want RAC to pause when I'm setting the `self.displayLink.paused` to `YES` but not when I'm setting it to `NO`.

Is this type of "conditional delay" possible in ReactiveCocoa, and if so, how is it done?

**Comment by joshaber** [comment]
You can use `-flattenMap:` to do this since it lets you return a signal instead of just a single value:

```objc
RAC(self.displayLink, paused) = [changeSignal flattenMap:^id(RACTuple *value) {
    RACSignal *pauseSignal = [RACSignal return:@([((NSMutableArray *)value.first) count] == 0)];
    if (pause) {
        return [pauseSignal delay:2.5];
    } else {
        return pauseSignal;
    }
}];
```

So when we're pausing, we delay 2.5 seconds and then pause. When we're unpausing we immediately send the value through.

**Comment by lightice11** [comment]
Thanks for the quick response! Love what you guys are doing here.
