### ISSUE TITLE
Question about "recursive" mergeMapping (reactive-swift branch)

### ISSUE THREAD

**Issue by codeflows** [ReactiveCocoa/ReactiveCocoa#1670]
Hi everyone. I've been trying out the `reactive-swift` branch of ReactiveCocoa. As I understand it's probably going to be re-written (as per #1655), but I'm going to go ahead and ask a question, which you can feel free to ignore if I should just wait a little bit longer ;)

I'm trying to model incoming UDP messages as a `HotSignal` that different consumers are filtering and mapping, currently causing a deadlock. The basic flow is:

1. Send request
2. Wait for response to arrive on `udpSignal`
3. Based on the response, send second request
4. Wait for second response to arrive on `udpSignal`

Below is some simplified code that causes the thread to hang. Basically the issue seems to be that I'm `mergeMap`:ing the filtered `udpSignal` to another filtered version of itself. Is my approach obviously wrong, or should this somehow work?

```swift
// this is obviously something else in real code
let (udpSignal, udpSink) = HotSignal<String>.pipe()
    
// sendFirstRequest(...)
    
let firstResponse : HotSignal<String> = udpSignal.filter { msg in msg == "Response to first request" }.take(1)
let secondResponse : HotSignal<String> = firstResponse.mergeMap { x in
  // sendSecondRequest("something based on \(x)")
  
  // thread hangs here
  udpSignal.filter { msg in msg == "Response to second request" }.take(1)
}

// simulate receiving first response, causes thread to hang above
udpSink.put("Response to first request")
```

Top of the stack:

```
#0	0x035eca6a in semaphore_wait_trap ()
#1	0x032ae4bf in _dispatch_thread_semaphore_wait ()
#2	0x032a7e4b in _dispatch_barrier_sync_f_slow ()
#3	0x032a7c28 in dispatch_barrier_sync_f ()
#4	0x032a8615 in dispatch_barrier_sync ()
#5	0x006c194d in ReactiveCocoa.HotSignal.observe <A>(ReactiveCocoa.HotSignal<A>)<B : Swift.SinkType>(B) -> ReactiveCocoa.Disposable at HotSignal.swift:108
```

Thanks for any pointers!

**Comment by Coneko** [comment]
It's possible that by the time you try to get the second response the response has already been received. You need to start listening for the response before you send the request.

**Comment by jspahrsummers** [comment]
Recursive signals are not explicitly supported and may deadlock.

This may get fixed at some point, but `delay(0)` should help in the meantime.

**Comment by codeflows** [comment]
@Coneko that's an excellent point! I've only done FRP in JavaScript, so I'm only used to "single-threaded FRP", where this wouldn't be an issue (namely that async responses won't be handled until the current synchronous code block has finished.)

@jspahrsummers adding `delay(0, onScheduler: QueueScheduler())` to `firstResponse` in my example solved the deadlock, thanks a lot!

**Comment by jspahrsummers** [comment]
Recursive signals should be supported now on the `swift-development` branch.
