### ISSUE TITLE
Building ReactiveCocoa as dependency causing issue with UIKit

### ISSUE THREAD

**Issue by NasirMalik** [ReactiveCocoa/ReactiveCocoa#1672]
I have added reactive cocoa project as dependency  via drag and drop in my current project. After following all the steps when it try to build the dependent (Reactive cocoa) project to make a build so that I can build my project it give me error with UIKIT [UIKit/UIKit.h file now found]. When i goto build phases and try to add it manually I cannot see any UIKIT as the development environment is set to My Mac.

**Comment by jspahrsummers** [comment]
Sounds like you've added ReactiveCocoa's Mac framework target instead of the iOS framework target.

**Comment by NasirMalik** [comment]
I added project file as dependency. There is only one project file for both mac and iOS. Now i have done this cocoapods and its working fine,
