### ISSUE TITLE
about ReactiveCocoa CocoaPods?

### ISSUE THREAD

**Issue by leiyong316** [ReactiveCocoa/ReactiveCocoa#1673]
i like use CocoaPods,    how to use?

**Comment by dopcn** [comment]
```
-> ReactiveCocoa (2.4.2)
   A framework for composing and transforming streams of values.
   pod 'ReactiveCocoa', '~> 2.4.2'
   - Homepage: https://github.com/blog/1107-reactivecocoa-is-now-open-source
   - Source:   https://github.com/ReactiveCocoa/ReactiveCocoa.git
   - Versions: 2.4.2, 2.3.1, 2.3, 2.2.4, 2.2.3, 2.2.2, 2.2, 2.1.8, 2.1.7, 2.1.6, 2.1.5,
   2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1, 2.0, 1.9.7, 1.9.6, 1.9.5, 1.9.4, 1.8.1, 1.8.0,
   1.7.2, 1.7.1, 1.7.0, 1.6.0, 1.5.0, 1.4.0, 1.3.1, 1.0.0, 0.17.1, 0.16.1, 0.13.1,
   0.12.0, 0.10.0, 0.9.0, 0.8.0, 0.6.0, 0.5.0, 0.0.1 [master repo]
   - Sub specs:
     - ReactiveCocoa/no-arc (2.4.2)
     - ReactiveCocoa/Core (2.4.2)
     - ReactiveCocoa/UI (2.4.2)
```

**Comment by jlawton** [comment]
The official stance is that the ReactiveCocoa project doesn't support CocoaPods, though the [readme](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/40725eac6f855daef0d585c5480b83923b07e667/README.md#importing-reactivecocoa) does link to some available [podspecs](https://github.com/CocoaPods/Specs/tree/master/Specs/ReactiveCocoa).

**Comment by leiyong316** [comment]
@dopcn  I know ,  I want to say latest version 2.4.4,  CocoaPods 2.4.2,   I want to use 2.4.4 in CocoaPods

**Comment by corristo** [comment]
@leiyong316 you have two options here, either wait until one of podspec maintainers update it, or make local podpsec copy and change the version here, and use local one in your Podfile.

**Comment by corristo** [comment]
@leiyong316 I updated the podspec, enjoy.

**Comment by leiyong316** [comment]
@corristo very thanks
