### ISSUE TITLE
How to get a RACSignal from a ColdSignal<String> to assign with KVO

### ISSUE THREAD

**Issue by KyleLeneau** [ReactiveCocoa/ReactiveCocoa#1674]
Maybe this is a bit premature but I am trying to assign a signal to a key path in order to update a UILabel. I have a `combineLatest` that is producing a coldSignal in my view model but when I try make it into a `RACSignal` for assignment I get odd type checker errors that are throwing me off.

Is this supposed to be working or or should I expect some changes? I have a public repo that I am working on [here](https://github.com/KyleLeneau/swift-mvvm-examples) and specifically I am trying to bind my viewController to my viewModel [here](https://github.com/KyleLeneau/swift-mvvm-examples/blob/master/swift-mvvm-examples/ViewController/DetailViewController.swift). Look around line 35 in this file, the assignSignal is commented out for now.

I am also using the `swift-development` branch of ReactiveCocoa. By the looks of other issues ColdSignal and HotSignal are going to be going away soon.

**Comment by jspahrsummers** [comment]
Without the actual errors you're encountering, it's hard to offer guidance.

**Comment by KyleLeneau** [comment]
I am getting this error: `DetailViewController.swift:35:61: 'String' is not identical to 'U?'`

For simplicity here is the code in a condensed fashion:


    override func viewDidLoad() {
        super.viewDidLoad()
        
        firstNameText.text = "Planet"
        lastNameText.text = "Earth"
        
        self.viewModel.firstName <~! firstNameText.rac_textColdSignal()
        self.viewModel.lastName <~! lastNameText.rac_textColdSignal()
        
        // error is happening right here
        var x = self.viewModel.fullName.asDeferredRACSignal(identity)
        RAC(self.titleLabel as NSObject, "text").assignSignal(x)
    }

The RAC function above is just a struct around holding the key path and object from traditional KVO and "legacy" assign signal to key path stuff.

Here is my view model that I am binding to:
```
import Foundation
import ReactiveCocoa

public class HelloWorldViewModel {
    public var firstName = ObservableProperty("")
    public var lastName = ObservableProperty("")
    
    public var fullName: ColdSignal<String> {
        return combineLatest(firstName.values, lastName.values).map { return "\($0) \($1)" }
    }
}
```

**Comment by jspahrsummers** [comment]
`RACSignal`s can only contain `AnyObject?`, so you'll have to convert your `ColdSignal` type to that first.

**Comment by KyleLeneau** [comment]
Hmm okay that seems to work now. I had to map and cast to an AnyObject?

```
var x = self.viewModel.fullName.map({ "Hello, \($0)" as AnyObject? }).asDeferredRACSignal(identity)
RAC(self.titleLabel as NSObject, "text").assignSignal(x)
```

Thanks for you help! I hope this interface and bridging between objc and swift improves with helpers and the like in future versions of RAC.
