### ISSUE TITLE
Re-connect RACMultiConnection: starting only one async operation and share signal result 

### ISSUE THREAD

**Issue by fabiomassimo** [ReactiveCocoa/ReactiveCocoa#1676]
From issue #828 

I'm facing a kind of same problem with a shared signal that I won't to "re-trigger" when it's needed.
I've tried really hard to solve it with RACMultiConnection but no matter what, I'm always facing the same problem: every time I want to re-trigger my source signal it sends next: to all previous subscribers.

More in detail:

1) the network request is made by a convenience methods that wraps up an old delegate implementation:

```
RACSignal *performRequestSignal =
    [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        // Create data received signal
        RACSignal *dataReceivedSignal = [[self rac_signalForSelector:@selector(dataReceived:forRequest:) fromProtocol:@protocol(MainDataControllerDelegate)] filter:^BOOL(RACTuple *returnTuple) {
            DataRequest *request = returnTuple.second;
            DataResponse *dataResponse = returnTuple.first;
            
            return ((request.type == dataRequest.type) && ([dataResponse.value isKindOfClass:dataResponseClass]));
        }];
        
        // Subscribe
        [dataReceivedSignal subscribeNext:^(RACTuple *returnTuple) {
            DataResponse *dataResponse = returnTuple.first;
            [subscriber sendNext:dataResponse.value];
            [subscriber sendCompleted];
            
        }];
        
        // Create data request failed signal
        RACSignal *requestFailedSignal = [self rac_signalForSelector:@selector(requestFailed:error:) fromProtocol:@protocol(MainDataControllerDelegate)];
        
        // Subscribe
        [requestFailedSignal subscribeNext:^(RACTuple *returnTuple) {
            NSError *error = returnTuple.second;
            [subscriber sendError:error];
        }];
        
        // Trigger the request to API
        [[MainDataController sharedInstance] addRequest:dataRequest delegate:self priority:queuePriority];
        
        return [RACDisposable disposableWithBlock:^{
            [[MainDataController sharedInstance] cancelRequest:dataRequest];
        }];
    }];
    
    return performRequestSignal;
```

2) This method uses previous one to create a convenience signal which we are calling "retrieveThingsSignal"

```
- (RACSignal *)retrieveThings
{
    if (_retrieveDebtors) return _retrieveDebtors;
    
    RACSignal *requestSignal = [self retrieveThingsSignal];
    _retrieveDebtors = [[requestSignal replayLast] finally:^{
        _retrieveThings = nil;
    }];
    
    return _retrieveThings;
```

3) every time I won't to re-trigger the signal a run this code

```
[[self retrieveThings] subscribeNext:^(NSArray *things) {
        @strongify(self);
        self.things = things;
    } error:^(NSError *error) {
        @strongify(self)
        self.things = nil;
    }];
```

My ```self.things``` gets updated accordingly to every time I need to make a new request to ```retreiveThings``` but, by putting a breakpoint inside the 1) step, I'm receiving that the ```next:``` is sent to ALL previous subscribers. If I call ```retrieveThings``` twice, I'm receiving, from that breakpoint, that the base signal is sending ```next:``` to two different subscribers (one will actually run the ```subscribeNext:``` block). If three to three subscribers, and so on...

I can  I prevent this behaviour?

I would like to share the last sent value from my ```retrieveThings``` method without trigger EVERY time the network request but, when needed, I need to clean it such that next subscribe will actually trigger the network request.

**Comment by Tiger6688** [comment]
```objective-C 
 _retrieveDebtors = [[requestSignal replayLast] finally:^{
        _retrieveThings = nil;
    }];
```
when the network request  is "success",replayLast just replay "complete",not the "value", try replay instead

**Comment by jlawton** [comment]
Also from issue #828.

Your problem is that you're using `self` as your delegate, and so you're calling back to the same object for every network call, which is then passed on to all of your signals. Create a new delegate for each request.

After that, something like what you have will work.I'd probably chose to bundle up the cached signal check into `defer:` but that's just a preference in the semantics for me.

```obj-c
- (RACSignal *)retrieveThings
{
    return [RACSignal defer:^{
        @synchronized(self) {
            if (!_cachedSignal) {
                _cachedSignal = [[[self actuallyRetrieveThings]
                    finally:^{
                        @synchronized (self) {
                            _cachedSignal = nil;
                        }
                    }]
                    replayLast];
            }
            return _cachedSignal;
        }
    }];
}
```

You might also need to `@weakify/@strongify` so `self` isn't retained in that scheme.

@Tiger6688 `replayLast` should replay the last value of a completed signal.

**Comment by Tiger6688** [comment]
@jlawton  thanks for your correction!

**Comment by Tiger6688** [comment]
```objective-C
    self.temp=[[[RACSignal return:@1] replayLast] finally:^(void){
        self.temp=nil;
    }];
    
    [self.temp subscribeNext:^(id x){
        NSLog(@"%@",x);
    }
       completed:^{
        NSLog(@"completed");
    }];
    
    
    [self.temp subscribeNext:^(id x){
        NSLog(@"%@",x);
    }
       completed:^{
        NSLog(@"completed");
    }];
//output:
//1
// complete
```

```objective-C
    self.temp=[[[RACSignal return:@1] finally:^{
        self.temp=nil;
    }] replayLast];
    
    [self.temp subscribeNext:^(id x){
        NSLog(@"%@",x);
    }
       completed:^{
        NSLog(@"completed");
    }];
    
    
    [self.temp subscribeNext:^(id x){
        NSLog(@"%@",x);
    }
       completed:^{
        NSLog(@"completed");
    }];
//output:
//1
// complete
//1
// complete
```

**Comment by fabiomassimo** [comment]
@jlawton yes you were right. Now I'm creating a delegate for each request and problem is solved.

@Tiger6688 I think I'll go for replayLast and get rid of manually create che RACMulticastConnection object.

Thanks everybody.
