### ISSUE TITLE
RAC 3.0 readiness question

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#1677]
We are in a company curious what would be the right branch (and revision?) for starting use RAC 3.0? Also could someone explain the readiness of the project, is there any major changes that still going to happen as well as expected timeline?

Thanks for your great work. Really appreciate what you are doing. Kudos from happy RAC 2 users :)

**Comment by joshaber** [comment]
RAC 3 is still undergoing a lot of churn. For example, there's currently an RFC that'd pretty drastically change the work already done: #1655.

I'd highly recommend sticking with RAC 2 for now.
