### ISSUE TITLE
The latest version 2.4.6, it will be updated to cocoapods?

### ISSUE THREAD

**Issue by leiyong316** [ReactiveCocoa/ReactiveCocoa#1687]

**Comment by joshaber** [comment]
We don't use Cocoapods so we rely on the community to keep the podspec up to date.

**Comment by corristo** [comment]
@leiyong316 as far as I can tell from 2.4.5 and 2.4.6 changes https://github.com/ReactiveCocoa/ReactiveCocoa/compare/v2.4.4...v2.4.6, it makes no sense to update the podspec.
