### ISSUE TITLE
Error when using a 3rd party API that implements ReactiveCocoa 

### ISSUE THREAD

**Issue by JinkProject** [ReactiveCocoa/ReactiveCocoa#1690]
I keep getting this error from the SimpleAuth API and it's coming from ReactiveCocoa's use of "LlamaKit". 
"error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker". Anybody know of a fix to this? Issue has been posted in SimpleAuth's 'hub as well.

**Comment by jspahrsummers** [comment]
If you're using CocoaPods, this is probably because it's selecting one of the prerelease, test-only 3.0 tags. Explicitly specify a 2.x version to avoid this error.
