### ISSUE TITLE
Memory increase without bound in racRecursiveScheduler

### ISSUE THREAD

**Issue by JadianZheng** [ReactiveCocoa/ReactiveCocoa#1691]
In my case, I need to do some recurisve thing in the update thread. And I found the memory increse problem without idea to figure it.
Here is the example:
case 1:
```javascript
    [self.dataUpdateScheduler after:[NSDate date] repeatingEvery:1 withLeeway:1 schedule:^{
        NSMutableArray *abc = [NSMutableArray array];
        for (int i = 0; i < 222220; i++) {
            [abc addObject:@"hello"];
        }
    }];
```
case 2:
```javascript
    [self.dataUpdateScheduler scheduleRecursiveBlock:^(void (^reschedule)(void)) {
        NSMutableArray *abc = [NSMutableArray array];
        for (int i = 0; i < 222220; i++) {
            @autoreleasepool {
                [abc addObject:@"hello"];
            }
        }
        reschedule();
    }];
```

Case 1 without memory problem, and 2 has the memory increase problem.
Can anyone help me? Thank you.

**Comment by jspahrsummers** [comment]
Background threads' autorelease pools are generally not drained until the thread goes away. Since `abc` exists in an autorelease pool, that means it may not be destroyed for as long as the thread exists.

If you put the `@autoreleasepool` around the array creation itself, do you still see an issue?

**Comment by JadianZheng** [comment]
I change the example to the follow you say, and the problem still exist.

```
    [self.dataUpdateScheduler scheduleRecursiveBlock:^(void (^reschedule)(void)) {
        @autoreleasepool {
            NSMutableArray *abc = [NSMutableArray array];
            for (int i = 0; i < 222220; i++) {
                [abc addObject:@"hello"];
            }
        }
        
        reschedule();
    }];
```

**Comment by jspahrsummers** [comment]
Do you have a full sample project, or an Instruments trace you can upload?

**Comment by JadianZheng** [comment]
You can new a single view ios project. Replace the view Controller code to the follow. It's just a sample project.

```
#import "ViewController.h"

@interface ViewController ()

@property (nonatomic) RACScheduler *dataUpdateScheduler;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    
    self.dataUpdateScheduler = [RACScheduler schedulerWithPriority:RACSchedulerPriorityDefault name:@"com.RACScheduler.Memory-scheduler"];
    
    [self.dataUpdateScheduler scheduleRecursiveBlock:^(void (^reschedule)(void)) {
        @autoreleasepool {
            NSMutableArray *abc = [NSMutableArray array];
            for (int i = 0; i < 222220; i++) {
                [abc addObject:@"hello"];
            }
        }
        
        reschedule();
    }];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
```

**Comment by JadianZheng** [comment]
Every time the schedule run, seem the follow memory can't not free since next schedule.
![screen shot 2015-01-26 at 11 55 46 am](https://cloud.githubusercontent.com/assets/3894891/5895176/5460b0bc-a552-11e4-8d6a-4293da0a6a1c.png)

**Comment by kkazuo** [comment]
@JadianZheng I can reproduced your problem. If you could edit ReactiveCocoa source, please try commenting out the line below:
ReactiveCocoa/ReactiveCocoa/RACScheduler.m" line 157 of 226
like this:
```
//lock.name = [NSString stringWithFormat:@"%@ %s", self, sel_getName(_cmd)];
```

**Comment by JadianZheng** [comment]
@kkazuo Thank you, everything seem well. And can you tell me, how you found this?

**Comment by kkazuo** [comment]
I have nothing special tool for this. But I try write out my thinking for your interests.
I saw the code block `-[RACScheduler scheduleRecursiveBlock:addingToDisposable:]`.
I feel smell something. There are too many `@autoreleasepool` in one code block.
I search the line that creates autoreleasing newly allocated object, and that fails to be guarded by `@autoreleasepool` block.

**Comment by JadianZheng** [comment]
@kkazuo Thank you.
