### ISSUE TITLE
Unit tests for Objective-C bridging

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1692]

**Comment by NachoSoto** [comment]
I'm going to start writing some of these tests.

**Comment by jspahrsummers** [comment]
@NachoSoto Any interest in doing the rest of the tests here? :smile: 

If not, no worries! Just make sure to unassign yourself, so someone else can pick it up.

**Comment by NachoSoto** [comment]
I've never used RACCommand, so I'm going to let someone else who knows it better do it :)
