### ISSUE TITLE
Consider replacing Signal.Type.pipe with Signal.Type.disposablePipe

### ISSUE THREAD

**Issue by andymatuschak** [ReactiveCocoa/ReactiveCocoa#1700]
Clients will often have to add to the returned signal's disposable, e.g.:

```swift
(signal, observer) = Signal.pipe()
someOtherSignal.observe(observer)
return signal
```

The canonical API should certainly allow—but also should probably encourage—developers to think about the correct memory management.

**Comment by jspahrsummers** [comment]
Related to/dependent upon our resolution to #1701.
