### ISSUE TITLE
Move ReactiveCocoa to ReactiveX

### ISSUE THREAD

**Issue by JosephEarl** [ReactiveCocoa/ReactiveCocoa#1706]
All of the other main RX implementations are under the ReactiveX user and on http://reactivex.io. 
ReactiveCocoa is currently completely separate from these and not listed on the main website.

It would be nice to have an "official" Objective-C implementation and ReactiveCocoa looks like the best so far.

This would necessitate a few changes such moving the repo and renaming to RxCocoa to be consistent with other implementations.

**Comment by jspahrsummers** [comment]
ReactiveCocoa is not an Rx port. It is merely inspired by Rx.
