### ISSUE TITLE
Method overriding/extension via FRP?

### ISSUE THREAD

**Issue by FawadHa1der** [ReactiveCocoa/ReactiveCocoa#1708]
A general FRP question. 

Lets say we have a ViewController in a static library. Now somebody wants to extend the functionality of the class. What is the best reactive way to do it. Method overriding is not the way to go I suspect, right? Or would it be something along the lines of subscribing or chaining to the parent interface's signal and adding functionality via that route?

**Comment by jlawton** [comment]
This question is probably too broad to answer without a more specific use case in mind.

**Comment by jspahrsummers** [comment]
If you're talking about extending the functionality of an exposed _signal_, I agree that overriding is not ideal.

Generally, composition is to be preferred over inheritance.
