### ISSUE TITLE
RACObserve weak reference warning

### ISSUE THREAD

**Issue by 7ynk3r** [ReactiveCocoa/ReactiveCocoa#1709]
Hello!

I'm getting a warning using `RACObserve` during compilation. The root cause is `__weak id target_ = (TARGET);` defined in:

	#define RACObserve(TARGET, KEYPATH) \
		({ \
			__weak id target_ = (TARGET); \
			[target_ rac_valuesForKeyPath:@keypath(TARGET, KEYPATH) observer:self]; \
		})

I tried adding the following inside the macro but it looks like it's not possible (after a little research).

	#define RACObserve(TARGET, KEYPATH) \
	({ \
		#pragma GCC diagnostic push \
		#pragma GCC diagnostic ignored "-Wreceiver-is-weak" \
		__weak id target_ = (TARGET); \
		[target_ rac_valuesForKeyPath:@keypath(TARGET, KEYPATH) observer:self]; \
		#pragma GCC diagnostic pop \
	})

The only solution I found so far is to add the warning to the project but it's not what I would like to do.

Any idea on how to remove this warning?

**Comment by jspahrsummers** [comment]
It sounds like you have the “sending messages to weak variables” warning enabled. We didn't really have that in mind when the weak variable was added to `RACObserve`.

It could probably be fixed by casting to `__strong` (in the macro implementation). Alternatively, you could disable the warning—I personally find that it results in a lot of false positives anyways.

**Comment by JaviSoto** [comment]
I actually implemented this in `libextobjc` (https://github.com/jspahrsummers/libextobjc/pull/71), it seems that you have a version of RAC that points to an older version of `libextobjc`?

**Comment by jspahrsummers** [comment]
@JaviSoto No, that's a different warning (about using a weak variable multiple times). Here, I believe the warning is sending any message to a weak variable—the intention being that it should be made strong first.

**Comment by JaviSoto** [comment]
Oh, sorry, I misread it. I think that's a dumb warning in the first place :( Sending a message to a weak referencer is fine, as long as you don't do refer to it more than once (and you don't dereference the pointer). I would also recommend disabling that warning.

**Comment by 7ynk3r** [comment]
Ok. Thanks!

**Comment by maxsz** [comment]
Xcode 8 now shows this warning: `Unknown warning group '-Wreceiver-is-weak', ignored`.
Should the `_Pragma("clang diagnostic ignored \"-Wreceiver-is-weak\"") \` lines be removed or is there another way to silence this?
