### ISSUE TITLE
Add aliases for <~

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1711]
It seems unlikely that the [compiler bugs with `<~`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/937626d0683a931b85365e3df47e25a44ff43782/ReactiveCocoa/Swift/Property.swift#L128) are going to get fixed before we want to move forward. So, let's add some aliases that give the same functionality.

They may need to be non-overloaded, if that's part of the cause of the compiler issue.

**Comment by joshaber** [comment]
What *are* said compiler bugs?

**Comment by kaybutter** [comment]
Hi. I played around with that operator. I don't get build errors if I use the signal version of the operator in the implementation for the SignalProducer.

Wouldn't something like this work?

https://gist.github.com/kaybutter/49ca54aa020303c05f07

**Comment by jspahrsummers** [comment]
@joshaber https://gist.github.com/jspahrsummers/841a11c10d1a043c1807
@kaybutter Maybe? Would you mind opening a pull request instead?

**Comment by kaybutter** [comment]
No problem. See #1728.
