### ISSUE TITLE
How can i compile reactivecocoa to a bibrary

### ISSUE THREAD

**Issue by leeaken** [ReactiveCocoa/ReactiveCocoa#1712]
i have download the reactivecocoa from github,then i compile the project,but there is some error with the project.so how can i compile reactivecocoa.

![image](https://cloud.githubusercontent.com/assets/8663400/5971589/c8f06718-a883-11e4-8987-c94ac376784c.png)

**Comment by joshaber** [comment]
You need to clone the repository, including its submodules. Simply downloading a zip of the source is not sufficient.

**Comment by leeaken** [comment]
Hi,joshaber,thanks.  but i want to compile the reactivecocoa into a library ,jus like libReactiveCocoa-iOS.a !  I run the script with "script/bootstrap" ,after, i found nothing, where is the  libReactiveCocoa-iOS.a? Can you tell me how to compile?  thanks

**Comment by joshaber** [comment]
Clone the repository and then follow the instructions at https://github.com/ReactiveCocoa/ReactiveCocoa#importing-reactivecocoa.

**Comment by leeaken** [comment]
Hi,joshaber,thanks too!   I have run the "script/bootstrap",it's perfect. and after it,  where is the libReactiveCocoa-iOS.a? Can you tell me where is it? thanks

**Comment by joshaber** [comment]
You'll need to open the project and build that target.
