### ISSUE TITLE
What's this error?

### ISSUE THREAD

**Issue by typhoonbb** [ReactiveCocoa/ReactiveCocoa#1713]
I use CocoaPods to add reactiveCocoa to my project ,Podfile : pod 'ReactiveCocoa', '~> 3.0.0-alpha.1',and then Xcode give me this error ,what should I do?? 
![8470892b-f8fc-49e4-923d-b091eeafda18](https://cloud.githubusercontent.com/assets/8253156/5972752/876d4db8-a899-11e4-9bae-c604dc3d02bb.png)

**Comment by joshaber** [comment]
I'm not sure, but that's almost certainly related to CocoaPods. We don't use CocoaPods so we can't be of much help. I'd recommend asking in their repository (or whatever the appropriate venue is).
