### ISSUE TITLE
Grouping items

### ISSUE THREAD

**Issue by bencochran** [ReactiveCocoa/ReactiveCocoa#1721]
(**Update:** I came to a solution to this below, but would love a pass over it from someone who knows how this all should work a bit better than myself…)

Very new to actually using ReactiveCocoa (as in, started actually using is Friday) so please forgive if I’m thinking about this all wrong.

In general I have a collection of items with two relevant properties. For example (using Swift because I can show it more succinctly):

    struct Item {
        let name: String
        let category: Category
        let type: Type
    }

What I’m attempting to do is group all items into groups by unique category, item pairs. e.g.:

    let grouped = [
        [Item("Lorem", .Book, .Big), Item("Ipsum", .Book, .Big)],
        [Item("Dolor", .Book, .Small)],
        [Item("Sit", .House, .Big), Item("Amet", .House, .Big)]
    ]

Currently I have arrays of the ungrouped items coming across a signal.

The intermediate solution is something like the following:

    [self.itemsSignal map:^(NSArray *items) {
        NSMutableDictionary *groupedItems = [NSMutableDictionary dictionary];
        for (BCItem *item in items) {
            RACTuple *groupKey = RACTuplePack(@(item.category), @(item.type));
            
            NSMutableArray *array = groupedItems[groupKey];
            if (array == nil) {
                array = [NSMutableArray array];
                groupedItems[groupKey] = array;
            }
            [array addObject:item];
        }
        
        return groupedItems; // Or flatten to tuples, or somehow other modify shape of result
    }];

Maybe that’s the best I can do, but doesn’t feel like it really make use of the framework and patterns.

If I imagine what a RAC-native final output might look like, it’s a signal of signals of `tuple(categoy, type, items) (where `items` is a signal or sequence or array depending on implementation).

But I’m not really sure where to start or if that’s even possible (or, quite frankly, desirable). I’d love any tips or relevant further reading.

**Comment by bencochran** [comment]
Went for a walk, did some [gardening](https://ventrellathing.wordpress.com/2013/06/18/the-case-for-slow-programming/), and came away with two things:

1. I don’t need the output to include the category and type as that can be derived from the items themselves. So my output can look like a signal of signals of signals/sequences/arrays.

1. The looping over the array of items requires side-effects by necessity. I can picture a solution that uses a dictionary of `RACReplaySubject`s much like I use the dictionary of `NSMutableArray`s, but I can’t really decide if that actually gains me anything.

**Comment by bencochran** [comment]
Well, lookie there: `groupBy:transform:`. So now I have:

    self.groupedItemsSignal = [self.sortedAllRentalsSignal map:^(NSArray *items) {
        return [items.rac_sequence.signal groupBy:^(BCItem *item) {
            return @(item.category | (item.type << 8));
        }];
    }];

So, then for my exposed `itemGroups` which is an array of `BCItemGroupViewModel`s I do:

    RAC(self, itemGroups) = [[self.groupedItemsSignal
        map:^(RACSignal *signal) {
            return [[[[signal
                       map:^(RACSignal *groupSignal) {
                           return [groupSignal take:1];
                       }]
                       flatten]
                       map:^(BCItem *item) {
                           return [[BCItemGroupViewModel alloc] initWithReferenceItem:item];
                       }]
                       collect];
        }]
        flatten];

And everything’s magic. That last bit got a little hairy with the `flatten`s and `collect`, but I can *almost* fully reason through it all :wink:

I’d love feedback on my solution, if someone has a minute. So I’ll leave this open for a bit. If it’s asking too much, go ahead and close this (or I will in a few days).

**Comment by mitisBlack** [comment]
Didn't look in detail over it, but something immediately looked of: map followed by flatten.
You certainly can do this, but there's a catch. Both flatten and map are implemented with flattenMap as a primitive operation. 
You can think of flattenMap as a primitive operation doing flatten on a map. Using it you can simplify your code and gain a bit of performance. ;)

**Comment by bencochran** [comment]
Ok, I’m satisfied with the solution above. (Plus `flattenMap`. Thanks for catching that, @mitisBlack.)
