### ISSUE TITLE
Reactive Newb

### ISSUE THREAD

**Issue by SandyChapman** [ReactiveCocoa/ReactiveCocoa#1725]
Hi,

I'm hoping to get some criticism on one of my first attempts at doing a reactive design. Essentially what I'm trying to do is reactify the ExternalAccessory framework from Apple. I'll only show a small part as it's one that I've got the most questions about.

Structure:
I have a small demo where I've got a text field that I can input a string into and a button that should submit that text to the external accessory:

    @interface ViewController ()

    @property (nonatomic, weak) IBOutlet UIButton* sendButton;
    @property (nonatomic, weak) IBOutlet UITextField* sendTextField;
    @property (nonatomic, strong) RACSubject* outputDataSignal;

    @end

    ...
    - (void)viewDidLoad {
        [super viewDidLoad];

        self.outputDataSignal = [RACSubject subject];

        @weakify(self);
        EAAccessoryManager* manager = EAAccessoryManager.sharedAccessoryManager;
        void(^accessoryConnected)(EAAccessory*) = ^(EAAccessory* accessory) {
            EASession* session = [[EASession alloc] initWithAccessory:accessory forProtocol:@"my_protocol"];
            [session rac_setOutputSignal:[self.outputDataSignal map:^id(NSString* value) {
                return [value dataUsingEncoding:NSUTF8StringEncoding];
            }]];
        };
        
        [[manager.connectedAccessories.rac_sequence signal] subscribeNext:accessoryConnected];
        [manager.rac_signalForAccessoryConnected subscribeNext:accessoryConnected];
        
        self.sendButton.rac_command = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
            return [RACSignal defer:^{
                @strongify(self);
                [self.outputDataSignal sendNext:self.sendTextField.text];
                self.sendTextField.text = @"";
                return [RACSignal empty];
            }];
        }];
    }

I've defined rac_signalForAccessoryConnected in a category on EAAccessoryManager which creates a signal on the relative NSNotification.
I've defined rac_setOutputSignal in a category on EASession which essentially takes an NSData and writes it to the session's output stream.

Is this the correct way of binding a RACCommand to actually do work with a signal? Is there a better (or more reactive) way to do this?

**Comment by kastiglione** [comment]
> Is this the correct way of binding a `RACCommand` to actually do work with a signal? Is there a better (or more reactive) way to do this?

The way `RACCommand` is being used above doesn't capitalize on the features it provides. In this case, it provides virtually no advantage compared to the standard target/action pattern. If the command were doing long running work, or if you wanted the button to be disabled at times, then those are cases where a command provides value.

**Comment by SandyChapman** [comment]
@kastiglione : So what alternative would you suggest? Define an IBAction and hook it up via IB as is typical? Something just feels off using the standard method when everything else is defined in a functional manner. Are you suggesting that perhaps I should add whatever functionality the would respond to the `outputDataSignal` within the command itself so that the button remains disabled?

I guess what I'm looking to figure out here is if this sort of pattern is the reactive way to do this?

**Comment by SandyChapman** [comment]
I took another stab at doing this and I'm stuck on the RACCommand.

    EAAccessoryManager* manager = EAAccessoryManager.sharedAccessoryManager;
    
    RACSignal* sessionSignal = [[manager.rac_signalForAccessoryConnected
      filter:^BOOL(EAAccessory* accessory) {
          return [accessory.protocolStrings containsObject:@"my_protocol"];
      }]
     map:^id(EAAccessory* accessory) {
         return [[EASession alloc] initWithAccessory:accessory forProtocol:@"my_protocol"];
     }];
    
    RACSignal* sessionActive = [[[RACSignal return:@NO] take:1] then:^RACSignal *{
        return [RACSignal return:@YES];
    }];
    
    RACSignal* dataSignal = [self.sendTextField.rac_textSignal map:^id(NSString* value) {
        return [value dataUsingEncoding:NSUTF8StringEncoding];
    }];
    
    RACSignal* sessionWithDataSignal = [RACSignal combineLatest:@[sessionSignal, self.sendTextField.rac_textSignal, dataSignal]];

    self.sendButton.rac_command = [[RACCommand alloc] initWithEnabled:sessionActive signalBlock:^RACSignal *(id input) {
         ...???...
    }];

So in this scenario I get a stream of EAAccessories connecting which I filter based on my expected protocol. I then map it to produce a stream of EASessions for those accessories.

I now want to combine that session with the sendTextField signal and perform an operation where I take the text as data and push it on the session's stream when the RACCommand is sent, but I'm not sure how to format this.

I know I can reduce it and do my operation in there, but I'm having troubles only triggering the signal once in the RACCommand's signalBlock.

**Comment by SandyChapman** [comment]
@kastiglione :+1: 

Thanks for prompting me to continue on this. I think I've got a much more reactive solution now:

    // Signal fired when an accessory connects and is mapped to a session.
    // This is a multicast connection so that the session isn't don't multiple times per
    // subscriber.
    RACSignal* sessionSignal = [self accessorySessionSignal]; 
    
    // Signal fired when an accessory connects/disconnects so we can maintain a count.
    RACSignal* sessionActive =
    [[RACSignal merge:@[EAAccessoryManager.sharedAccessoryManager.rac_signalForAccessoryConnected,
                        EAAccessoryManager.sharedAccessoryManager.rac_signalForAccessoryDisconnected]]
     map:^id(id value) {
         return @(EAAccessoryManager.sharedAccessoryManager.connectedAccessories.count > 0);
     }]; // Sign
    
    // Make a text replay so we can get the last sent text on demand.
    RACSignal* textSignal = [self.sendTextField.rac_textSignal replayLast];
    
    // Make a data replay so we can get the last sent data on demand.
    RACSignal* dataSignal = [[self.sendTextField.rac_textSignal map:^id(NSString* value) {
        return [value dataUsingEncoding:NSUTF8StringEncoding];
    }] replayLast];
    
    // Finally, merge them all and replay.
    RACSignal* sessionWithDataSignal = [[RACSignal combineLatest:@[sessionSignal, textSignal, dataSignal]] replayLast];
    
    self.sendButton.rac_command = [[RACCommand alloc] initWithEnabled:sessionActive signalBlock:^RACSignal *(id input) {
        return [RACSignal defer:^RACSignal *{
            [[sessionWithDataSignal take:1] subscribeNext:^(RACTuple* tuple) {
                @strongify(self);
                EASession* session = tuple.first;
                NSString* string = tuple.second;
                NSData* data = tuple.third;
                [session.outputStream write:data.bytes maxLength:data.length];
                self.inputTextView.text = [self.inputTextView.text stringByAppendingString:[NSString stringWithFormat:@"\n%@", string]];
                self.sendTextField.text = @"";
            }];
            return [RACSignal empty];
        }];
    }];

In the RACCommand, I'm now replaying to get the last values with a take:1. Then I use those values to do work in the command (such as writing to a stream and eventually sending a network request).

I think I'll be able to work some of the replays out of the equation here, but for now this is working for me.

**Comment by kastiglione** [comment]
I've only just quickly glanced at the latest `RACCommand` above (not the rest, but will look later). So roughly, my advice is to consider this:

In the command block, change the `-subscribeNext:` to a `-doNext:` and return that signal instead of `+empty`. It also wouldn't need to be wrapped in `+defer:`

**Comment by kastiglione** [comment]
Also check out the `RACTupleUnpack` macro.

**Comment by SandyChapman** [comment]
Works great. Thanks for your help, @kastiglione.

**Comment by Spencevail** [comment]
Hey @SandyChapman quick tip for future reference: When you do a multiline code block in markdown you add the 3 back ticks at the beginning and end, but you can also add the language after the opening ``` like this (**I added spaces in between the back ticks here to get this to show up right**):

```
` ` ` objective-c
[someCode youWant:toPresent];
` ` `

```

The output looks a little cleaner, here is your code from earlier:

```objective-c
EAAccessoryManager* manager = EAAccessoryManager.sharedAccessoryManager;

RACSignal* sessionSignal = [[manager.rac_signalForAccessoryConnected
  filter:^BOOL(EAAccessory* accessory) {
      return [accessory.protocolStrings containsObject:@"my_protocol"];
  }]
 map:^id(EAAccessory* accessory) {
     return [[EASession alloc] initWithAccessory:accessory forProtocol:@"my_protocol"];
 }];

RACSignal* sessionActive = // ... signal that's true when a session is active.

RACSignal* dataSignal = [self.sendTextField.rac_textSignal map:^id(NSString* value) {
    return [value dataUsingEncoding:NSUTF8StringEncoding];
}];

RACSignal* sessionWithDataSignal = [RACSignal combineLatest:@[sessionSignal, self.sendTextField.rac_textSignal, dataSignal]];

self.sendButton.rac_command = [[RACCommand alloc] initWithEnabled:sessionActive signalBlock:^RACSignal *(id input) {
     ...???...
}];
```

More details [here](https://guides.github.com/features/mastering-markdown/#syntax).
