### ISSUE TITLE
Best way to inject side effect AFTER a property is updated?

### ISSUE THREAD

**Issue by Spencevail** [ReactiveCocoa/ReactiveCocoa#1731]
So I'm looking at binding the constant value of an `NSLayoutConstraint` to a signal and having my view layout update when that happens. The sequence needs to be:

1. Featured signal sends boolean value
2. That signal is converted to either 0 or 10
3. The constant value of a `NSLayoutConstraint` is set to that value
4. The containing view runs a layout pass on itself and all subviews

I'm wondering a few things:
1. Whats the best way to model steps 1+2 from above using Reactive Cocoa?
2. Is there a clean way to inject a side effect **after** a bound property is updated without having to add another `RACObserve` for that property?
3. Unrelated to ReactiveCocoa, but whats the designated way to update a layout after the constraints are modified?

I have something like this:
```objective-c
RAC(self, featuredViewHeight.constant) = [[RACSignal if:self.featuredSignal
                                              then:[RACSignal return:@(10.0)]
                                              else:[RACSignal return:@(0.0)]]
                                              doNext:^(id x) {
                                                  [self setNeedsLayout];
                                              }];
```

I'm guessing there is a whole lot wrong with this, so any guidance would be appreciated!

**Comment by kastiglione** [comment]
> 2\. Is there a clean way to inject a side effect **after** a bound property is updated without having to add another `RACObserve` for that property?

In your example, the `-doNext:` will be executed **before** the `RAC` assignment.

Besides using a `RACObserve`, you could move assignment into a `-subscribeNext:` to ensure desired ordering:

```objc
[[RACSignal
    if:self.featuredSignal then:[RACSignal return:@(10.0)] else:[RACSignal return:@(0.0)]]
    subscribeNext:^(NSNumber *constant) {
        self.featuredViewHeight.constant = constant.floatValue;
        [self setNeedsLayout];
    }];

I asked something like this before, wanting an operator to support this scenario, but the feedback was that using `RACObserve` was the way to do it with RAC, and I've reconciled with that :)

**Comment by ominiom** [comment]
For this type of situation I've previously added a `-doAroundNext:` operator as a category on `RACSignal`:

```objective-c
- (RACSignal *)doAroundNext:(void (^)(id x, void (^yield)()))nextBlock {
  NSCParameterAssert(nextBlock != NULL);

  return [[RACSignal create:^(id<RACSubscriber> subscriber) {
    [self subscribeSavingDisposable:^(RACDisposable *disposable) {
      [subscriber.disposable addDisposable:disposable];
    } next:^(id x) {
      void (^yielder)() = ^{
        [subscriber sendNext:x];
      };

      nextBlock(x, yielder);
    } error:^(NSError *error) {
      [subscriber sendError:error];
    } completed:^{
      [subscriber sendCompleted];
    }];
  }] setNameWithFormat:@"[%@] -%@", self.name, NSStringFromSelector(_cmd)];
}
```

Calling `yield()` in the `nextBlock` triggers the actual update.

I've found it useful for property changes that need to be animated:

```objective-c
RAC(self.view, backgroundColor) = [... doAroundNext:^(id x, void (^yield)()) {
  [UIView animateWithDuration:0.5f animations:yield];
}];
```

Or anything that needs balanced calls before and after the property assignment - updates to a UITableView backed by an array property, for example:

```objective-c
RAC(self, items) = [... doAroundNext:^(id x, void (^yield)()) {
  [tableView beginUpdates];

  // ...insertions and deletions
  yield();

  [tableView endUpdates];
}];
```

The original problem would look something like:

```objective-c
RAC(self, featuredViewHeight.constant) = [[RACSignal if:self.featuredSignal
                                                     then:[RACSignal return:@(10.0)]
                                                     else:[RACSignal return:@(0.0)]]
                                             doAroundNext:^(id x, void (^yield)()) {
                                               yield();
                                               [self setNeedsLayout];
                                             }];
```

**Comment by Spencevail** [comment]
Hey @ominiom, I like this solution, but I'm a little confused by the implementation. What is `+[RACSignal subscribeSavingDisposable:]`? I'm not seeing that in my version of ReactiveCocoa.

**Comment by kastiglione** [comment]
> What is `+[RACSignal subscribeSavingDisposable:]`?

That's from the old objc RAC 3 development branch, which got scrapped in favor of a Swift version.

**Comment by ominiom** [comment]
@Spencevail It may not be in any versioned release, I've been using the `legacy-objc` branch. Implementing with `subscribeNext:error:completed:` should give the same effect:

```objective-c
- (RACSignal *)doAroundNext:(void (^)(id x, void (^yield)()))nextBlock {
  NSCParameterAssert(nextBlock != NULL);

  return [[RACSignal create:^(id<RACSubscriber> subscriber) {
    [self subscribeNext:^(id x) {
      void (^yielder)() = ^{
        [subscriber sendNext:x];
      };

      nextBlock(x, yielder);
    } error:^(NSError *error) {
      [subscriber sendError:error];
    } completed:^{
      [subscriber sendCompleted];
    }];
  }] setNameWithFormat:@"[%@] -%@", self.name, NSStringFromSelector(_cmd)];
}
```

**Comment by Spencevail** [comment]
This is just what I was looking for. Thanks @ominiom & @kastiglione!
