### ISSUE TITLE
network request retry

### ISSUE THREAD

**Issue by adriantofan** [ReactiveCocoa/ReactiveCocoa#1732]
Hello ,
I have a signal that creates a network requests, processes end returns the resul. Both processing and the network can fail. I want to be able to retry in case of failure. 
```
-(RACSignal)categoriesSignal{
  return [[self categoriesNetworkRequest] 
    flattenMap:^RACStream *(RACTuple* value) {
      NSError* error;
      id result = [decode:value error:&error];
      if (error){
        return [RACSignal error:error];
      }else{
        return [RACSignal return:result];
      }
    }];
}
```
I would like to be able to write [categoriesSignal retry]  and when decoding fails to retry a new network request. It doesn't seems to be working as such because the underlying network request is never retried. Do you have any suggestion on how to achieve this?

**Comment by jspahrsummers** [comment]
This is why you should prefer _cold_ signals. If your network request signal is somehow replayed or multicasted, it can't be retried.

**Comment by adriantofan** [comment]
Thank you for the answer,

Following your idea, I found the source of the error and it is as you told me a cold signal in a underlying library. 

As far as I understand in the general case my example is the good - given that all underlying signals are cold. 

Have a nice day
