### ISSUE TITLE
Crash due to "deallocated while key value observers were still registered"

### ISSUE THREAD

**Issue by Ahti** [ReactiveCocoa/ReactiveCocoa#1733]
I'm currently trying to migrate a little part of an app to MVVM and I'm using RAC for that.

I have a table view controller that displays a bunch of cells representing file downloads.

The code that populates the table view's cells looks like this: 

```obj-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier forIndexPath:indexPath];
    
    AssetTransferItemViewModel *item = self.currentViewModel.items[indexPath.row];
    
    RAC(cell.textLabel, text) = [RACObserve(item, name) takeUntil:[cell rac_prepareForReuseSignal]];
    RAC(cell.detailTextLabel, text) = [RACObserve(item, progressString) takeUntil:[cell rac_prepareForReuseSignal]];
    
    return cell;
}
```

Pretty simple.

Now the problem is that on very rare occasions (the table view is reloaded when a transfer is completed, which may happen as often as every second in my tests), RAC does not seem to let go of the KVO-subscription on a ViewModel. The app crashes with this exception:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x171f8070 of class AssetTransferItemViewModel was deallocated while key value observers were still registered with it. Current observation info: \<NSKeyValueObservationInfo 0x171d8260> ( \<NSKeyValueObservance 0x171f6040: Observer: 0x171f5fc0, Key path: name, Options: \<New: NO, Old: NO, Prior: YES> Context: 0x1dd684, Property: 0x15fb2f30> \<NSKeyValueObservance 0x171d8220: Observer: 0x171d81a0, Key path: progressString, Options: \<New: NO, Old: NO, Prior: YES> Context: 0x1dd684, Property: 0x15f5dbb0> )'

(The crash happens when an autorelease pool is cleared, so no more information to gain from the throw stack).

Since this happens so rarely, I guess some kind of race is involved. The items come from a "container view model" which updates its items from a NSOperationQueue, but all properties that could change from a foreign thread are sent to the main thread via `deliverOn:RACScheduler.mainThreadScheduler` in the view model classes.

Is there anything obvious I am doing wrong/missing? I can post more code if the problem is not diagnosable with what I provided.

**Comment by jspahrsummers** [comment]
Which version of RAC are you using? We've recently fixed some KVO memory management issues, so maybe you don't have those yet.

**Comment by Ahti** [comment]
I recently updated from 2.3.1 to 2.4.4. I thought I saw it happening after I updated but now I can't seem to reproduce it. I'll close this for now and reopen if it does happen again.
