### ISSUE TITLE
Add a PropertyType instance supporting KVC/KVO?

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1738]
I've waffled on this a few times myself, so I'd like to open it up to the larger conversation.

I was originally of the mindset that we should focus on “the Swift way, the right way” for RAC 3.0, and eschew dynamic Objective-C features like KVC and KVO. The problem, of course, is that those features are _really damn useful_.

Even besides their appearances in data binding—for which `MutableProperty` should be a suitable replacement—there are some APIs that require the use of KVO (`NSOperation` and Core Data come to mind). And isn't part of The Promise of RAC™ that we'll unify all these disparate paradigms into one, all-consuming abstraction?

Anyways, I'm highly ambivalent. What does @ReactiveCocoa/reactivecocoa think?

**Comment by andymatuschak** [comment]
I think it's worth doing, but explicitly, and without sugar.

**Comment by robrix** [comment]
Ditto @andymatuschak :point_up:

The utility of the library would be diminished by not integrating with those bits of the platform, and we’d end up writing ad hoc `RACObserve` replacements anyway, and probably getting them wrong.

**Comment by ashfurrow** [comment]
[Guilty as charged](https://github.com/ashfurrow/Swift-RAC-Macros).

**Comment by robb** [comment]
This _could_ be its own µframework though

**Comment by jspahrsummers** [comment]
@robb I think the issue body answers that:

> And isn't part of The Promise of RAC™ that we'll unify all these disparate paradigms into one, all-consuming abstraction?

I like modularity and composability, but do we really want to ask users to bring in different frameworks depending on the _common_ Cocoa paradigms they want to integrate?
