### ISSUE TITLE
Implement merge and mergeMap

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1749]
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/15c2c9a473f5bf09b79061f603cb122a257162e1/ReactiveCocoa/Swift/SignalProducer.swift#L534-L535

Previous implementations in [`swift-before-signal-producers`](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/swift-before-signal-producers) may be of use.

**Comment by saniul** [comment]
You can assign this to me for now, I have implemented `merge` and `mergeMap` but I’m not yet sure if they behave correctly. I’ll implement tests over the weekend.
