### ISSUE TITLE
Implement switch and switchMap

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1750]
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/15c2c9a473f5bf09b79061f603cb122a257162e1/ReactiveCocoa/Swift/SignalProducer.swift#L536-L537

Previous implementations in [`swift-before-signal-producers`](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/swift-before-signal-producers) may be of use.

**Comment by brow** [comment]
I don't think `switch` is a legal identifier in Swift. How about `switchToLatest`?

**Comment by kastiglione** [comment]
`switcheroo`

**Comment by brow** [comment]
You can assign to me since I have #1759 going and plan to finish today.
