### ISSUE TITLE
Implement repeat and retry

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1751]
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/15c2c9a473f5bf09b79061f603cb122a257162e1/ReactiveCocoa/Swift/SignalProducer.swift#L539-L540

Previous implementations in [`swift-before-signal-producers`](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/swift-before-signal-producers) may be of use.

**Comment by NachoSoto** [comment]
I'll try to do this tomorrow! They're the operators I'm most excited about.

**Comment by jspahrsummers** [comment]
Thanks! I've assigned it to you, but feel free to remove yourself if you don't work on it after all.

**Comment by NachoSoto** [comment]
This is finished with #1760 and #1761 :tada: 
That was fun!
