### ISSUE TITLE
Implement timeoutWithError

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1752]
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/15c2c9a473f5bf09b79061f603cb122a257162e1/ReactiveCocoa/Swift/Signal.swift#L687

Previous implementations in [`swift-before-signal-producers`](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/swift-before-signal-producers) may be of use.

**Comment by swizzlr** [comment]
Propose this be closed a la above PR.

**Comment by kastiglione** [comment]
Fixed in #1756

thanks @swizzlr
