### ISSUE TITLE
Upgrade to Swift 1.2

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1753]
Depends upon https://github.com/LlamaKit/LlamaKit/pull/27.

**Comment by almassapargali** [comment]
It's merged!
![856938](https://cloud.githubusercontent.com/assets/1816725/6232936/aad04ff8-b6f9-11e4-9e8d-3f2dd52853af.gif)

**Comment by jspahrsummers** [comment]
I've heard of a lot of issues with Swift 1.2, so I'm thinking this should wait until a second beta or so. We also have [several open PRs](https://github.com/ReactiveCocoa/ReactiveCocoa/pulls?q=is%3Aopen+milestone%3A3.0+is%3Apr) that I don't want to invalidate by migrating right now.

**Comment by tonyarnold** [comment]
Wimp. 

Merrrrrrge it.

**Comment by robrix** [comment]
The majority of the issues are very minor, and easily patched.

I’m a bit puzzled at the last remaining one, tho: Swift is erroring on `DynamicProperty`’s `value` property, both setter and getter, telling me that they override the Objective-C methods `value` and `setValue:` from superclass `NSObject`. The `override` keyword is, however, not accepted.

I do not encounter this in a new project, so I assume it’s set up somewhere in RAC. I’m not sure where it’s getting it from, tho, and apparently neither is Swift:

```
<unknown>:0: note: Objective-C method 'setValue:' defined by method 'setValue' here
```
