### ISSUE TITLE
Is there a good way to "merge" signals from the UITableViewCellViewModels that are currently in a table view? 

### ISSUE THREAD

**Issue by Spencevail** [ReactiveCocoa/ReactiveCocoa#1765]
The problem I'm trying to solve here is that I have a view model property on my custom `UITableViewCell` subclass, and I'd like to have a `RACCommand` on the view model that is executed when a button on the `UITableViewCell` is pressed. Then I'd want to map that to a value from the model via the view model, and then pass that to the `UITableViewController` to handle. I imagine that when I set the view model on the `UITableViewCell` in `-tableView:cellForRowAtIndexPath:` I'd somehow combine the `executionSignals` with those from other viewModels. Then I'd have to remove the added `executionSignals` when the cell is recycled. Maybe I'm way over thinking this and there is another way to handle this situation, but the constraints I'm trying to follow are:

1. The `UITableViewCell` has no reference to the UITableView.
2. The view model has no reference to the `UITableViewCell`.
3. The `UITableViewController` should handle pushing new view controllers onto the navigation stack.
4. Ideally the view model doesn't have any reference to the `UITableViewController`.

Any thoughts/suggestions on the best way to do this?

**Comment by Spencevail** [comment]
*I might have an answer to my own question, but I'm still curious to get outside input.*

One solution would be to have a view model on the `UITableViewController` which the `UITableViewCell`'s view models could have a reference to. That way by having the `UITableViewController` subscribe to a signal on it's view model the signal would go:

User presses button|
:--------------------------------:|
`UITableViewCellButton`| 
⬇ |
`UITableViewCellViewModel`|
⬇|
`UITableViewControllerViewModel`|
⬇|
`UITableViewController`|
⬇|
**New `UIViewController` is pushed onto nav stack**|

 
The `UITableViewControllerViewModel` can handle merging the signals, all of the constraints are held, and this matched the MVVM(C) type of architecture I'm going for. 

I'm gonna leave this open for now for some outside perspective.

**Comment by jspahrsummers** [comment]
That's more or less what I would do, with the difference that I don't think the cell view models should have a _direct_ reference to the view model for the whole table.

Instead, the “parent” view model should have a list of child view models (corresponding to the rows of the table), and can indirectly observe their changes via signals or KVO-able properties.

**Comment by Spencevail** [comment]
The part I'm stuck on is how do you 'observe' the signals of many things that are created and destroyed over time?

IE could you give an example of:
> Instead, the “parent” view model should have a list of child view models (corresponding to the rows of the table), and can indirectly observe their changes via signals or KVO-able properties.
?

**Comment by jspahrsummers** [comment]
@Spencevail Here's [an example](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1370#issuecomment-48145906).

**Comment by Spencevail** [comment]
Awesome, thanks @jspahrsummers!
