### ISSUE TITLE
Combine merge/latest/concat into one operator with a “strategy” parameter?

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1768]
I've been thinking about combining `merge`, `concat`, and `latest` (and their corresponding mapping variants) into one operator—perhaps called `join`—that accepts a choice of joining strategy.

Although it's generally frowned upon to use parameters to _completely_ change the behavior of a function, I think it could be beneficial in this case as a way to force consumers to think about which strategy is most appropriate (vs. RAC 2.x, where almost everyone uses `flattenMap` without thinking about it).

Thoughts?

**Comment by NachoSoto** [comment]
I like the idea :)

**Comment by neilpa** [comment]
What's the rationale for unifying them? In RAC 2 the operator names were inconsistent WRT each other making it harder to draw parallels. In RAC 3 the names are standardized so it should be more obvious that users are making a choice about joining strategy across the three.

**Comment by neilpa** [comment]
We also have strong static typing now. The method signatures immediately convey the difference between signal and signal of signal operators. In RAC 2 everything was just `RACSignal` so that may have led people to avoid some of the "esoteric" operators and default to `flattenMap`.

**Comment by jspahrsummers** [comment]
My concern is awareness—it's easy to only ever learn `merge`, and never fully grok `concat` and `latest`. While we can't force people to understand the distinction, requiring them to _pick one every time_ might help them understand the options and how they differ.

**Comment by mdiep** [comment]
This is a really interesting idea. You could even use associated values to do the equivalent of RAC2's `flatten:`.

**Comment by jspahrsummers** [comment]
The potential downsides that I see are:

- Verbosity
- Inability to add your own join operator “on the same level” (but I don't think this is a big deal in practice)

**Comment by neilpa** [comment]
> Note that they all have the same type signature too, so that doesn't help.

That was my point, but I viewed it as helpful since it's what unifies these operators. They all flatten signals of signals with the method name describing how.

**Comment by kastiglione** [comment]
I've gotta say [this is a pretty good idea](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1241#issuecomment-41232550), but [some people might disagree](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1241#issuecomment-41232753).

**Comment by jspahrsummers** [comment]
@kastiglione :clap: My thinking has probably shifted only because Swift allows us to create closed sum types (enums).

**Comment by mdiep** [comment]
@kastiglione :clap:

**Comment by kastiglione** [comment]
I believe the benefits will outweigh the downsides. :+1:

**Comment by kastiglione** [comment]
> My concern is awareness—it's easy to only ever learn `merge`, and never fully grok `concat` and `latest`.

This is quite common, this week I was explaining them for friend. I agree that a parameterized `join` would improve this a lot.

**Comment by joshvera** [comment]
:-1: fwiw. The enum seems pretty arbitrary as there are a number of other valid `SignalProducer<SignalProducer<T, E>, E>) -> SignalProducer<T, E>` functions. 

How does it prevent someone ignoring the documentation and using `join(Merge)` everywhere? If this is about awareness, why not improve our documentation?

**Comment by jspahrsummers** [comment]
@joshvera The issue isn't documentation, but rather people _not knowing_ that there are these other ways to flatten signals-of-signals. If you use an enum, you get a closed universe of possible ways.

> The enum seems pretty arbitrary as there are a number of other valid `SignalProducer<SignalProducer<T, E>, E>) -> SignalProducer<T, E>` functions. 

I alluded to this [above](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1768#issuecomment-75327932). Honestly, I've never seen any defined except by us.

**Comment by neilpa** [comment]
>> The enum seems pretty arbitrary as there are a number of other valid SignalProducer<SignalProducer<T, E>, E>) -> SignalProducer<T, E> functions.

>I alluded to this above. Honestly, I've never seen any defined except by us.

And if you are creating custom operators you can curry/close on the builtin operator to regain the original signature.

**Comment by brow** [comment]
Another way to force people to look at the list of `merge`-like functions we provide, without introducing a new instantiable type, is to group them all into a struct as static functions.

I sympathize with the aim here. My most insidious bugs in RAC 2 always involved having `flatten` where I meant `switchToLatest`.

**Comment by jspahrsummers** [comment]
> Another way to force people to look at the list of `merge`-like functions we provide, without introducing a new instantiable type, is to group them all into a struct as static functions.

@brow What would be the pros/cons of this versus an `enum`, out of curiosity?

**Comment by brow** [comment]
@jspahrsummers The `struct` gives the user about the same experience -- seeing the available strategies in autocomplete and together in the header/doc. But it wouldn't privilege RAC-defined strategies over user-defined strategies, and the latter could appear in autocomplete (I think?) if placed in an extension to the `struct`.

**Comment by brow** [comment]
Con: the compiler won't check that every static function in the `struct` has the signature of `merge`, whereas it will check that `join` handles every value of the `enum`.

**Comment by jspahrsummers** [comment]
Hmm, yeah, I like the completeness aspect of an `enum`.
