### ISSUE TITLE
Does a channel terminal ever gets `complete`d or `error`ed?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#1769]
Basically what the title says.

I am observing a few sources of data (coming from the network). As well as some user defaults. The latter comes in a form of terminal channel through `rac_channelTerminalForKey:` in `NSUserDefaults` category.

Here's some pseudo code that implements the fetching of data without the terminal channel:

```
RACSignal *fooDataSignal = [self signalForFooData];
RACSignal *barDataSignal = [self signalForBarData];

RACSignal *foobarDataSignal = [RACSignal merge:@[fooDataSignal, barDataSignal]];

[foobarDataSignal 
	subscribeNext:^(NSData *data) {
		[self appendData:data];
	} 
	error:(NSError *)error {
		[self displayError:error]
	} 
	completed:^(void) {
		[self processWholeData];
	}];
```

Now all is fine until the `NSUserDefaults` come in. Ideally I would get the signals from there and depending on the setting that came in, I would modify the, say, `barDataSignal` that would `combineLatest:reduce:` with settings signal value like this:

```
RACSignal *barDataSignal = [self signalForBarData];
RACSignal *barSettingSignal = [[NSUserDefaults standardUserDefaults] rac_channelTerminalForKey:BarDataSettingsKey];

NSData *(^reduceBlock)(NSData *, NSNumber *) = :^NSData *(NSData *data, NSNumber *setting) {
	return [setting boolValue] ? data : nil;
}

RACSignal *setBarDataSignal = [RACSignal combineLatest:@[barDataSignal, barSettingSignal] 
												reduce:reduceBlock
```

However the problem is that in this case the `setBarDataSignal` never gets `completed` signal because only the `barDataSignal` is completed upon receiving the data from the network, not the `barSettingSignal` which seems to be always receiving the signals. This causes my `completed` block to never be called and data gets unprocessed. Any other way to implement this type of functionality?

**Comment by jspahrsummers** [comment]
What would it mean for a user defaults channel to complete? There's no really good time for it to do so.

If you want to create a derived signal that completes at a point of your choosing, check out the `-takeUntil:` operator.

**Comment by eimantas** [comment]
Thanks for the answer. I decided to change the architecture and move the settings signal to the very top and do initial load by calling `replayLast` on it.

I have not tested, but I think the `takeUntil:` operator won't fit here because it will complete the signal and won't send consequent values through the user defaults terminal channel.
