### ISSUE TITLE
Memory not free in [RACScheduler  afterDelay:schedule:]

### ISSUE THREAD

**Issue by JadianZheng** [ReactiveCocoa/ReactiveCocoa#1781]
Try the follow code in sample project, you will find the problem. Hope someone to help.

```
    _disposable = [[RACScheduler scheduler] afterDelay:5 schedule:^{
        NSMutableArray *abc = [NSMutableArray array];
        
        for (int i = 0; i < 300000; i++) {
            [abc addObject:@"Hello, world"];
        }
    }];
```

**Comment by jspahrsummers** [comment]
Can you please provide more details? For example, which objects do you see remaining alive? Why do you expect them to go away?

**Comment by JadianZheng** [comment]
This is a test for this function. I hope the var abc go away after the block is done, but it doesn't. How can I free abc?

**Comment by jspahrsummers** [comment]
`abc` is probably in an autorelease pool, since `+array` is an autoreleasing constructor.

Beyond that, I can't tell you anything more. RAC has no involvement in the lifetime of `abc`.

If you have real code that's exhibiting this issue, can you please share that instead? This sample may not be illustrative.

**Comment by JadianZheng** [comment]
You are right. It's my form, the low understand for ARC.
It seem that the follow code also can't free, no matter how long the demo run...
```
- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSMutableArray *abc = [NSMutableArray array];
    
    for (int i = 0; i < 300000; i++) {
        [abc addObject:@"Hello, world"];
    }
}
```

**Comment by kkazuo** [comment]
Which version of RAC do you use?
I could not reproduce your problem on RAC 2.4.7.
```abc``` did dealloc'ed.

**Comment by kastiglione** [comment]
@JadianZheng Isn't this like #1691 and fixed by #1707? If not, why.

**Comment by kkazuo** [comment]
@JadianZheng "Enable Zombie Objects" is ON?

Please check Xcode Menu > Product > Scheme > Edit Scheme... > Diagnostics > Memory Management

**Comment by JadianZheng** [comment]
Er....The demo I test in simulator, but I found everything is ok in my phone. Seem that the memory management is not the same between them.
