### ISSUE TITLE
What is best advice for default error handling?

### ISSUE THREAD

**Issue by amccarri** [ReactiveCocoa/ReactiveCocoa#1785]
Question: For example I have a library of signals that the app can subscribe to.  If subscribers do not provide an error block, I would like to perform some default error handling.  Is there a preferred way to do this?  Only thing I can think of at this point is extend RACSignal and override RACSignal:createSignal to create a subscriber with a default error block if one was not already created, but that feels wrong.

**Comment by jspahrsummers** [comment]
You can use the `-catch:` operator for this.

**Comment by amccarri** [comment]
I think -catch: is inverse of what I want.  Catch let's me intercept the error and propagate it if I choose.  What I want is to do some default error handling if the subscriber did not provide an error block.

**Comment by jspahrsummers** [comment]
You can choose to return `[RACSignal empty]` from `-catch:` to stop error propagation.

**Comment by amccarri** [comment]
But I don't want to stop the propagation if they subscribed to the error block.  Maybe a better way to phrase the question is, how do I determine if RACSubscriber has an error block?

**Comment by jspahrsummers** [comment]
There's no way to determine that. Signals aren't supposed to care how their subscribers behave.

If you're really worried that consumers won't handle errors, perhaps you could use a block callback somewhere that defaults to _your_ error handling behavior, but which is overridable by them.

But, honestly, that seems like a code smell—consumers should understand the contract of `RACSignal`, which is that zero or more `next` events are sent, followed by `completed` _or_ `error`. If they don't want to interface with that contract, perhaps exposing a RAC-less API would be the way to go.

**Comment by amccarri** [comment]
Yeah I was thinking it was a code smell also, but I'm building this for a group that is very new to Reactive and this is something they were asking for.  Just wanted to make sure there wasn't some RAC way to do this already that I was missing.  Thanks for your quick replies!

**Comment by jspahrsummers** [comment]
No problem!
