### ISSUE TITLE
Add an operator for promoting a NoError signal/producer

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1786]
Signals and producers that are parameterized over `NoError` (i.e., those that cannot send errors) cannot automatically be combined with signals and producers that might error. Instead, you have to lift them using something like:

```swift
producer |> catch { _ in SignalProducer<T, RealError>.empty }
```

… which would not make any sense to most readers (and which does not work on plain `Signal`s). We should add an operator to encapsulate this use case.

/cc @robrix

**Comment by robrix** [comment]
Thinking through the various options here, I think our best bet might be a `map`-style operator which transforms the error:

```swift
func promote<T, E: ErrorType, F: ErrorType>(transform: E -> F)(signal: Signal<T, E>) -> Signal<T, F>
```

We can provide transforms for sufficiently common cases, e.g.:

```swift
func toNSError(error: NoError) -> NSError { return NSError() }
```

Which yields a fairly readable syntax:

```swift
noErrorProducer |> promote(toNSError) |> zipWith(someRACSignal.asSignalProducer())
```

**Comment by jspahrsummers** [comment]
`catch` already exists for error transformation, so I'd specifically like an operator that lifts from `NoError` to `E`.

I also don't think the user should have to specify a lambda, because `NoError` is never instantiated and thus will never be passed into it.

**Comment by robrix** [comment]
1. `catch` exists for signal/producer transformation. It’s `bind` to `promote`’s `map`.

2. The alternatives to passing in a lambda are inference on the return type, passing in a value of the type, passing in the type as a value, and explicitly parameterizing some sort of struct instance instead. All of those are syntactically worse.

**Comment by jspahrsummers** [comment]
Your points are valid, but I really think we should avoid any case where it looks like `NoError` might be instantiated, because it's super confusing.

Actually, does your `toNSError` function above even compile? I think an explicit `NoError` parameter might be disallowed.

**Comment by robrix** [comment]
I don’t think Swift is that smart, but I would love to be mistaken.

**Comment by JaviSoto** [comment]
<img src="https://pbs.twimg.com/media/B-y-K4NUIAE7gYx.png:large" />

**Comment by jspahrsummers** [comment]
Hm, fair enough—it does compile. I could've sworn I ran into a case where that sort of thing wasn't possible.

In any case, my main concern is the clarity of intent.

**Comment by robrix** [comment]
I think `promote(toNSError)` is as clear as it’s going to get, personally. None of these are any better:

- `promote(NSError.self)`
- `promote(NSError())`
- `promote() as Signal<Blah, NSError>`

**Comment by jspahrsummers** [comment]
What about something like `promoteErrorsToMatch(signal: Signal<T, E>)` and a corresponding producer variant? That would clearly express what you're trying to achieve: an error signature that matches a signal you want to combine with.

**Comment by robrix** [comment]
That’s going to require you capture the other thing in a local variable, duplicate it, construct an unnecessary instance of the same type. I also don’t think it’s any clearer, because it doesn’t say anything about the _why_.

**Comment by jspahrsummers** [comment]
What about `errorlessSignal |> Signal<Blah, NSError>.promotion`?

**Comment by robrix** [comment]
Oooooh. Nice one. I dig it!

**Comment by joshaber** [comment]
FWIW, I think passing the type as an argument is more idiomatic. See `unsafeBitCast`.

**Comment by robrix** [comment]
Huh, good point. Didn’t realize anything in stdlib was doing that.

**Comment by jspahrsummers** [comment]
Me neither! We'll go with that, then.
