### ISSUE TITLE
UIImagePickerController and camera privacy settings

### ISSUE THREAD

**Issue by arietis** [ReactiveCocoa/ReactiveCocoa#1787]
Hello!

I was trying to use reactive UIImagePickerController. But there is one problem. In particular, when you restrict access to the camera or photos. 

Actually, it works ok for the camera. (But i still need to use AVAuthorisationStatus to determine privacy settings and do not show the picker in case of failure.) 

For the case with photos i'm getting system controller shown. It tells me that i need to change my privacy settings. It has Cancel button in top right corner. But this button is NOT working. :) So i'm getting frozen till the moment when i relaunch the app. 

Could you check and confirm? Would be nice to have some solution. Thanks. :)

**Comment by jspahrsummers** [comment]
You need to subscribe to [completion](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/bbb024fe1132dee4c8583ab953c7b083029f3f7d/ReactiveCocoa/UIImagePickerController%2BRACSignalSupport.m#L45) in order to tell when the picker has been cancelled.
