### ISSUE TITLE
ignoreValues signal operator

### ISSUE THREAD

**Issue by indragiek** [ReactiveCocoa/ReactiveCocoa#1800]
I'd like to implement the `ignoreValues` signal operator from RAC 2.0 in the `swift-development` branch, but am unsure as to what the type signature should be. I'm inclined to believe it should probably be `Signal<T, E> -> Signal<T, E>` where the resulting signal just doesn't send any values, but there's also a case to be made for `Signal<T, E> -> Signal<(), E>`, as the type signature more clearly indicates that the signal does not send any values. Thoughts?

**Comment by NachoSoto** [comment]
`Signal<T, E> -> Signal<(), E>` would be the right signature :)

**Comment by jspahrsummers** [comment]
I'm a fan of using `map { _ in () }` for this purpose. If you really need to eliminate all occurrences too, you can then `filter` afterwards.

**Comment by indragiek** [comment]
@jspahrsummers That's what I'm doing right now. Do you think this is worth adding an operator for?

**Comment by jspahrsummers** [comment]
I would like to keep the _initial_ Swift API as minimalistic as possible. It's a lot easier to add more operators in the future than to remove them.

**Comment by indragiek** [comment]
Fair enough! I'll revisit this after 1.0 if I find that I'm having to do the `map`/`filter` dance too many times for this purpose.

**Comment by NachoSoto** [comment]
You should be able to define the operator in your module though if you want to avoid the duplication.

**Comment by indragiek** [comment]
@NachoSoto Yup, I'll do that for now :)
