### ISSUE TITLE
Remove convenience functions with next:error:completed:interrupted:

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1801]
What if we removed `start(next:error:completed:interrupted:)` (and the same for `observe(…)`), and forced everyone to accept `Event`s which have to be `switch`ed upon?

This might be marginally inconvenient, but would force consumers to think about all possible events that they should be handling. Hopefully, this could avoid cases where [errors aren't handled](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1785), or it's not realized that a signal might complete, etc.

Also, this is already the direction that RAC has been moving with many of its operator implementations, because it makes code sharing easier (if your behavior in multiple cases is the same, for example).

@ReactiveCocoa/reactivecocoa Thoughts?

**Comment by jspahrsummers** [comment]
Ah, I forgot to mention: the specific thing that inspired this is `Interrupted`, which has no RAC 2.x parallel, so consumers might forget or not know about it. Requiring it to be handled in a `switch` would be one way of solving that problem.

**Comment by NachoSoto** [comment]
How about simply removing the default value `doNothing` for the arguments?

**Comment by jspahrsummers** [comment]
@NachoSoto What does that buy over an `Event`-based version, then? In fact, it seems like it's worse, since you lose the ability to introspect and reuse the `Event` value itself.

**Comment by kastiglione** [comment]
I have no logical arguments to offer, but my feelings say :-1:  However, I'm sure I'd get used to it.

**Comment by joshaber** [comment]
:-1: 

Handling all event types doesn't make sense on all signals. It'd be more annoying than helpful.

**Comment by robrix** [comment]
Agreed that it’d be more annoying than helpful.

I’d honestly rather parameterize signals/producers by the events that can occur, e.g. explicitly specifying `Signal<Result<T, NSError>>` instead of `Signal<T, NSError>`, and dropping `NoError`, and bridging the types in the appropriate combinators (e.g. the combination of any signal and an interruptible signal is interruptible).

I imagine that’s out of scope, so I suggest materializing when you want to be sure you’ve covered all the bases.

**Comment by jspahrsummers** [comment]
> Handling all event types doesn't make sense on all signals.

@joshaber Note that “handling” can mean using a `default:` case in a `switch`, with no logic inside.

> explicitly specifying `Signal<Result<T, NSError>>` instead of `Signal<T, NSError>`

@robrix This makes the API more confusing, IMO, because you'd still need an `Event` type to represent things like completion.

> dropping `NoError`

Er, why's that?

**Comment by robrix** [comment]
> Note that “handling” can mean using a `default:` case in a `switch`, with no logic inside.

I’m :-1: on this _specific_ solution because statements are pretty heavyweight. I think @joshaber’s objection holds, honestly.

> @robrix This makes the API more confusing, IMO, because you'd still need an `Event` type to represent things like completion.
> 
> > dropping NoError
> 
> Er, why's that?

It’d be implicit:

- `Signal<T, E>` → `Signal<Result<T, E>>`
- `Signal<T, NoError>` → `Signal<T>`

You’re right that lifting completion out similarly would more or less amount to capturing it in `Event`, but I’m pretty curious what it would feel like using signals/producers whose types precisely capture whether they will complete or not, etc.

**Comment by jspahrsummers** [comment]
> I’m pretty curious what it would feel like using signals/producers whose types precisely capture whether they will complete or not

Unfortunately, this cannot be captured. The best you can guarantee is, “this won't complete” or “this may complete, but it's not guaranteed,” which isn't very helpful.

Since it's rare to _not_ want completion, I don't think there's much value in having that captured. By contrast, knowing that errors cannot occur can eliminate a large class of problems.

**Comment by adly-holler** [comment]
This is a great idea. The convenience functions prevent the use of trailing closure syntax, so this style would be cleaner. Also opens the door to using Swift pattern matching to differentiate between, say, different Next or Error values.

**Comment by jspahrsummers** [comment]
I'd like to hear @joshaber's (Jerry's) Final Thought before doing anything here or closing it out.

**Comment by brow** [comment]
> The convenience functions prevent the use of trailing closure syntax, so this style would be cleaner.

@adly-holler In my experiments [using RAC 3 for MVVM](https://github.com/brow/sukhasana), 90% of my `start`s are only supplied `next`, so I get to use trailing closure syntax regardless.

Also, 90% of my `SignalProducer`s have error type `NoError`, and I might resent being forced to match error events on those.

**Comment by kastiglione** [comment]
> @joshaber's (Jerry's) Final Thought

![](http://www.reactiongifs.com/r/choofed.gif)

**Comment by adly-holler** [comment]
@brow Like JSS mentioned, handling only nexts would come out to

**Comment by joshaber** [comment]
I'm still :-1:. @adly-holler makes some good points, but there's no reason we can't have both, right?

**Comment by jspahrsummers** [comment]
![](https://s-media-cache-ak0.pinimg.com/originals/c2/da/d1/c2dad18b3329ac267aec980b74c8173e.jpg)
