### ISSUE TITLE
Question: How to bind a property depend on object in cell

### ISSUE THREAD

**Issue by JadianZheng** [ReactiveCocoa/ReactiveCocoa#1803]
```
Class A {
    Class same;
}

Class B :: Class same {
    Property a;
    Property b;
    Property c;
}

Class C :: Class same {
    Property d;
    Property e;
    Property f;
}
```
I need to bing the `property ( a | b | c | d | e | f )` In cell, depend on the `Property same` in `Class A`.

**Here is my current solution:**
    Rewrite the setter of property same in Class A.
``` 
RAC(Lable, text) = [RACObserve(B or C, a | b | ....) takeUntil:self.rac_prepareForReuseSignal];
```

And this performance seem not good enough. Has any way to bind once in `awakeFromNib` ?

**Comment by jspahrsummers** [comment]
Sorry, I'm not exactly sure what you're asking. Can you please share some _real_ code, and then tell us what you would like fixed in it?
