### ISSUE TITLE
How private is RACEXTScope.h?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#1804]
I was fixing the memory leaks in my RAC-enabled code and noticed that I am always passing strong reference to `self`. That's why [probably] I was having growing amount of `RACCompoundDisposable` instances in my #1788 issue with binding objects to cells through `NSUserDefault` key channels.

I checked the code and RAC itself uses `weakify` and `strongify` macros defined in `RACEXTScope.h` which is not part of public interface which means I have to import `<ReactiveCocoa/RACEXTScope.h>` below `<ReactiveCocoa/ReactiveCocoa.h>`.

My question is how much can I rely on the implementation of swapping weak/strong references in the code? Is it planned to be changed in, say, RAC 3.0 or is it safe to use same `weakify`/`strongify` macros in my code too?

**Comment by jspahrsummers** [comment]
RAC exports `@weakify` and `@strongify`. It's fine.

However, the header should be named `EXTScope.h`. I'm guessing it's renamed for CocoaPods—in which case, you might run into problems if you want to switch to the framework distribution in the future.
