### ISSUE TITLE
crash in Release mode with Swift

### ISSUE THREAD

**Issue by seboslaw** [ReactiveCocoa/ReactiveCocoa#1805]
In one of my view controllers I do the following:

```
    override func viewDidLoad() {
        super.viewDidLoad()
		self.nextButton.rac_signalForControlEvents(UIControlEvents.TouchUpInside).subscribeNext({ [unowned self] _ -> Void in
				self.setupWithData((dataTitle: "Test", dataText: "Test2"))
			})
    }
```
This works in Debug mode. However, in versions compiled in Release mode, my app crashes when this view controller gets deallocated. I have to change my code to the following in order to get it running in Release mode:
```
	override func viewDidLoad() {
		super.viewDidLoad()
		self.nextButton.rac_signalForControlEvents(UIControlEvents.TouchUpInside).subscribeNext({ [weak self] _ -> Void in
			if let realSelf = self {
				self.setupWithData((dataTitle: "Test", dataText: "Test2"))
			}
		})
	}

```
The crash seems to occur in 
```
__21-[RACSubscriber init]_block_invoke + 56
```
Does anyone have any idea why that is?

**Comment by NachoSoto** [comment]
`unowned` has been confirmed to be buggy in Swift 1.1, supposedly fixed in 1.2 :)

**Comment by seboslaw** [comment]
@NachoSoto urgh...this is going to be a real PITA since Refactoring in XCode is also not yet supported for Swift :((((

**Comment by NachoSoto** [comment]
I'd recommend replacing all the `unowned`s with `weak` + force unwrapping, which is essentially the same.

**Comment by seboslaw** [comment]
@NachoSoto yup....I'm already on it :) There are a lot of [unowned self]s though :(

**Comment by jspahrsummers** [comment]
Bugs aside, I would recommend `weak self` anyways. There's almost no reason to use `unowned` if weak references are supported.
