### ISSUE TITLE
Strange issue connected with `-(id)item` method

### ISSUE THREAD

**Issue by nmtitov** [ReactiveCocoa/ReactiveCocoa#1806]
Hi,
 
I can't build my project due to strange issue connected with ReactiveCocoa and ARC.
I was working on generic `UITableViewController` app. 

First everything was fine, I created `-(id)item` properties for my `UITableViewCells`. Then I added protocol with single property `@property(weak, nonatomic) id item;`. And since that moment I am unable to build my project. I renamed all my properties to `cellItem`, of course replaced that protocol method with `cellItem` property too. 

But whatever I do, I keep getting this error:

````
~/Users/user/App/Pods/ReactiveCocoa/ReactiveCocoa/RACEvent.m:110:24: Multiple methods named 'item' found with mismatched result, parameter type or attributes
````

I tried to restart Xcode, I removed DerivedData. Guess I need to typecast these `event` objects, but I don't know ReactiveCocoa that much. If I remove this line from ReactiveCocoa everything works fine.

![screen shot 2015-03-04 at 17 22 13](https://cloud.githubusercontent.com/assets/193307/6486452/c1e2b8fc-c293-11e4-906c-03e617d5c17f.png)

**Comment by jspahrsummers** [comment]
I'm not sure which version of RAC you're using, because the latest [does not have](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/d513a59e8f94d6ab5a66e47e92fb4e208ae1c2a0/ReactiveCocoa/RACEvent.m#L110) a property named `item`.

**Comment by nmtitov** [comment]
Thanks for pointing that, I was using latest stable version from CocoaPods which is 2.4.7
