### ISSUE TITLE
NSSet.rac_sequence.signal and scheduler

### ISSUE THREAD

**Issue by paolonl** [ReactiveCocoa/ReactiveCocoa#1809]
Hi,

I have the following method 
```obj-c 
- (RACSignal)fetchAllBooks {
    NSSet *books = [self fetchAuthorizedUser].books;
    return books.rac_sequence.signal;
}
```
which is supposed to first fetch the CoreData User, get his books property (a set of Book instances) and then returning each book as `next` on the returned signal. The issue I am trying to solve here is a CoreData threading issue: rac_sequence.signal sends its nexts on a new scheduler and this triggers sometimes those beautiful errors about fault fulfilment. How can I guarantee that the signal sends next in the scheduler where both the authorised user and books are living? 
I tried `rac_sequence.signalWithScheduler:[RACSheduler currentScheduler]` but the current scheduler is sometimes nil. Would `[RACScheduler immediateScheduler]` guarantee me the thread safety? 

Thanks a lot

**Comment by jspahrsummers** [comment]
Yep, you can indeed use `RACScheduler.immediateScheduler` for this purpose.

The automatic scheduling behavior of `-[RACSequence signal]` is a big wart, but the :ship: has already sailed on that. :disappointed:
