### ISSUE TITLE
Add an operator for mapping errors of a Signal

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1814]
_Originally suggested by @robrix._

We should have an operator that allows the errors of an arbitrary `Signal` to be mapped to some other kind of error. This would be to `catch` what `map` is to `joinMap`.

But this is even more important because `catch` isn't available over `Signal`, so it's difficult to replicate the same functionality without doing it imperatively.

**Comment by iCodesign** [comment]
I'm new to FP.

> This would be to catch what map is to joinMap.

What does this mean here?

And will the method look like this: 

```
public func errorMap<T, E, F>(transform: E -> F)(signal: Signal<T, E>) -> Signal<T, F>
```

or this:

```
public func map<T, U, E, F>(transform: (T, E) -> (U, F))(signal: Signal<T, E>) -> Signal<U, F>
```

Forgive me, I don't know if I'm catching the point.

**Comment by jspahrsummers** [comment]
> What does this mean here?

`joinMap` maps from values to signal producers.
`catch` maps from errors to signal producers.

`map` maps from values to other values.
`mapErrors` would map from errors to other errors.

> And will the method look like this:

It would look more like the former, since there won't be any values (`T` or `U`) to map if an error occurs.

**Comment by iCodesign** [comment]
@jspahrsummers Thanks for the brief explanation. :thumbsup:
