### ISSUE TITLE
Re-add constructor like +[RACSignal defer:] to SignalProducer

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1815]
It's sometimes hard to express imperative things with `SignalProducer`s without an operator like this. Maybe it could be called `run {}` or something action-y like that.

**Comment by NachoSoto** [comment]
How would this ~~defer~~ differ from `SignalProducer`'s `startHandler` constructor?

**Comment by jspahrsummers** [comment]
This function would accept a closure of type `() -> SignalProducer`.

**Comment by iCodesign** [comment]
Is it something like this:

```
public static func defer(producerHandler: ()-> SignalProducer) -> SignalProducer {
	return self { observer, compositeDisposable in
		let diposable = producerHandler().start(observer)
		compositeDisposable.addDisposable(diposable)
	}
}
```

**Comment by jspahrsummers** [comment]
@iCodesign Sort of. That particular sample would require some changes (maybe a different name, using `startWithSignal` instead). Would you be interested in opening a pull request where we can discuss it further?

**Comment by jspahrsummers** [comment]
As I see it, `+[RACSignal defer:]` has three use cases:

1. Performing some work before the stream begins. In RAC 3, you can use `on(started:)` for this.
1. Performing an operation which may succeed or fail. In RAC 3, you can use `SignalProducer.self.try()` for this.
1. Performing some work before _creating_ the stream.

The last case is where I thought we might still want `defer`, but it's actually possible to use `try` for this too. Just return a `Result`, then use `joinMap` to tack on an additional producer based on that result if need be.

So, after thinking about it a bit, I've decided that `defer` is actually not worth including right now.
