### ISSUE TITLE
[Question]Reactive questions(mostly about multicast and subject).

### ISSUE THREAD

**Issue by TimurBK** [ReactiveCocoa/ReactiveCocoa#1816]
I have a localization manager class which can change app language on the fly. It's using ReactiveCocoa and my main concern is that I'm not using some of RAC parts correctly.

First (in [`- (void)configureSignals`][1]): 
        
    + (instancetype)sharedInstance
    {
        static i2KRLMLocalizationManagerObject *sharedInstance = nil;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            sharedInstance = [[[self class] alloc] init];
            [sharedInstance initialConfiguration];
        });
        return sharedInstance;
    }

    - (void)initialConfiguration
    {
        [self configureSignals];
        [self configureAppLocalizations];
    }

    - (void)configureSignals
    {
        RACReplaySubject *subject = [RACReplaySubject replaySubjectWithCapacity:1];
        self.localeConnection = [subject multicast:subject];
        [self.localeConnection autoconnect];
        
        RACReplaySubject *languagesSubject = [RACReplaySubject replaySubjectWithCapacity:1];
        self.languageNamesConnection = [languagesSubject multicast:languagesSubject];
        [self.languageNamesConnection autoconnect];

        RACReplaySubject *languageIndexSubject = [RACReplaySubject replaySubjectWithCapacity:1];
        self.languageIndexConnection = [languageIndexSubject multicast:languageIndexSubject];
        [self.languageIndexConnection autoconnect];
    }

It feels for me that multicast should be used differently(and is used wrong currently, although it works), although I'm not sure how to use it correctly.

Those signals are used to propagate NSLocale, array of supported languages and current language index in that array. I use multicast so that if there is more then 1 subscriber(and probably there may be any number of subscribers), signal will be shared and current values will be just replayed. I'm not sure that signal multicasting itself is idiomatic/correct way. Also I'm not completely sure if connection is needed at all or I can just go with ReplaySubject.

Second (like [here][2]):

    - (void)changeToLocale:(NSLocale *)locale
    {
        [self reloadBundleWithLocaleID:[locale localeIdentifier]];
        [(RACSubject *)[self localeSignal] sendNext:locale];
    }

Cast has to be made now because in interface it's declared as `- (RACSignal *)localeSignal;` and is actually

    - (RACSignal *)localeSignal
    {
        return self.localeConnection.signal;
    } 

I use that getter instead of `self.languageNamesConnection.signal` because if I ever change this to something I wouldn't have to go all over and remove traces of that. But the cast looks just wrong. 

I don't like this cast at all, although not sure how to improve this(since I'm sending values through multicasted signal; and probably get rid of this sending altogether if possible).

  [1]: https://github.com/TimurBK/ReactiveLocalizationManager/blob/master/ReactiveLocalizationManager/i2KRLMLocalizationManagerObject.m#L64
  [2]: https://github.com/TimurBK/ReactiveLocalizationManager/blob/master/ReactiveLocalizationManager/i2KRLMLocalizationManagerObject.m#L158

**Comment by adly-holler** [comment]
Subjects are naturally multicasted, so you could replace the multicast connection property with `@property RACSubject *localeSubject` and subscribe directly to that in place of `localeSignal`. Then you'd have

```objectivec
- (void)changeToLocale:(NSLocale *)locale
{
    [self.localeSubject sendNext:locale];
}
```

**Comment by jspahrsummers** [comment]
Regarding the casting: when we have subjects, we usually create a public signal property:

```objc
@property (nonatomic, strong, readonly) RACSignal *localeSignal;
```

… which is backed by a _subject_ ivar in the implementation:

```objc
RACSubject *_localeSignal;
```

Then, in the implementation, you can send upon `_localeSignal`, but subscribers will use `object.localeSignal`.

All sending on the subject should go through the implementation, though—callers shouldn't have access to it. If you need to send an event from the outside, think of some other way to represent that, like a method which ultimately results in a value being sent upon the subject.

**Comment by TimurBK** [comment]
@adly-holler @jspahrsummers Thank you for quick replies. 

So to summarize(and check if I understood correctly):
1. I don't even need Connection since ReplaySubject is multicasted too and that's what I need.
2. I just need to declare internal ivar/property to avoid casting.(since subject is already internal implementation detail and is exposed as signal).

I don't need to send anything from outside(at least I can't think about such case) since the flow is like this:
Ask manager to change language -> Manager internally does necessary things like reloading bundle etc -> New value is propagated via subject to subscribers.

**Comment by jspahrsummers** [comment]
@TimurBK Yep, that understanding is correct. :zap:
