### ISSUE TITLE
replayLazily and updating values

### ISSUE THREAD

**Issue by mAu888** [ReactiveCocoa/ReactiveCocoa#1819]
Hey there, I'm pretty new to the ReactiveCocoa topic and have a question. I'm firing a network request to obtain data once and sending the response to multiple subscribers using the `replayLazily` signal. This works pretty good. But as I want users to be able to reload data and all subscribers should be notified about that data update, how to achieve this best.

There are two objects consuming `vehiclesSignal`. I'd now like to have some way that one object can trigger a data reload (i.e. `-reloadVehicles`) and both get notified. Is this somehow achievable with `RACMulticastConnection` and `RACReplaySubject`?

```objc
- (RACSignal *)vehiclesSignal
{
    static dispatch_once_t onceToken;
    static RACSignal *instance = nil;

    dispatch_once(&onceToken, ^{
        __weak typeof(self) weakSelf = self;
        instance = [[RACSignal createSignal:^RACDisposable *(id <RACSubscriber> subscriber) {
            __strong typeof(weakSelf) strongSelf = weakSelf;

            [strongSelf.APIClient vehiclesWithCompletion:^(NSArray *vehicles, NSError *error) {
                if (vehicles)
                {
                    [subscriber sendNext:vehicles];
                    [subscriber sendCompleted];
                }
                else
                {
                    [subscriber sendError:error];
                }
            }];

            return [RACDisposable disposableWithBlock:^{
                // void.
            }];
        }] replayLazily];
    });

    return instance;
}
```

Disclaimer: I already found the post about [obtaining an API access token once](http://stackoverflow.com/questions/14066651/how-to-using-reactivecocoa-to-transparently-authenticate-before-making-api-calls/14072445#14072445), but that did not clarify my question about reloading the underlying data.

**Comment by adly-holler** [comment]
`RACCommand` is a pretty great fit here. Something like:

```objectivec
self.reloadVehiclesCmd = [[RACCommand alloc] initWIthSignalBlock:^(id input) {
   return [RACSignal createSignal:^(id <RACSubscriber> subscriber) {
        __strong typeof(weakSelf) strongSelf = weakSelf;
        [strongSelf.APIClient vehiclesWithCompletion:^(NSArray *vehicles, NSError *error) {
            if (vehicles)
            {
                [subscriber sendNext:vehicles];
                [subscriber sendCompleted];
            }
            else
            {
                [subscriber sendError:error];
            }
        }];

        return nil;
    }]
}
```

and then in the calling code, you can either bind the command to a control or execute it manually

```objectivec
self.refreshControl.rac_command = self.reloadVehiclesCmd;
// or manually
[self.reloadVehiclesCmd execute:nil];
```

and interested parties can observe the command's `executionSignals`, `executing`, and `errors` to get multicasted notifications about the results, state, or errors on the command.

**Comment by neilpa** [comment]
See also #827 for another similar example.

**Comment by mAu888** [comment]
So I now tried the following with an `RACCommand`. When I subscribe to the `executionSignals` with `map:`, the block never invokes, though `[subscriber sendNext:vehicles]` is invoked.
Plus is there a way to have following subscribers get already fetched values after the command already finished executing?

To maybe elaborate a bit more on what I want to achieve:
ViewController A subscribes to `vehiclesSignal`
    -> this triggers a network request (as in my version using `replayLazily`)
ViewController B also subscribes to `vehiclesSignal` and receives either the last known response, if the connection executed already, or waits until execution finished and also receives the data (which is also already working with the `replayLazily` approach).

In either controller there is also the possibility to reload the data, which should reload the underlying data and signal to all subscribers that new data is available.

So the data should only be reloaded on users wish, but not if new objects subscribe to the `vehiclesSignal`.

I imagine that the approach with the `RACCommand` will not completely match with my expectations, as I imagine the following would happen:
ViewController A subscribes to `vehiclesCommand.executionSignals` and triggers a data load via `execute:`.
ViewController B subscribes to `vehiclesCommand.executionSignals` and also triggers a data load which may trigger a second request if the command already finished executing.

```
- (RACCommand *)vehiclesCommand
{
    if (nil == _vehiclesCommand)
    {
        __weak typeof(self) weakSelf = self;
        _vehiclesCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
            return [RACSignal createSignal:^RACDisposable *(id <RACSubscriber> subscriber) {
                __strong typeof(weakSelf) strongSelf = weakSelf;
                [strongSelf.APIClient vehiclesWithCompletion:^(NSArray *vehicles, NSError *error) {
                    if ( vehicles )
                    {
                        // sendNext: is invoked but the subscribers to executionSignals never receive any data
                        [subscriber sendNext:vehicles];
                        [subscriber sendCompleted];
                    }
                    else
                    {
                        [subscriber sendError:error];
                    }
                }];

                return (RACDisposable *)nil;
            }];
        }];
    }

    return _vehiclesCommand;
}
```

**Comment by adly-holler** [comment]
Hmmm RACCommand won't give you that replaying behavior natively. To make a signal that view controller B can subscribe to and get the latest/next batch of vehicles, you can do this:
```objectivec
// vehiclesCommand.executionSignals is a signal of signals.
// Use switchToLatest to get events from the most recent execution signal of the command

RACSignal *latestVehicles = [[vehiclesCommand.executionSignals switchToLatest] replayLast];
```
If order to be sure you never miss any vehicles, you've got to create that signal as soon as possible, and keep a strong reference to it somewhere. Whoever owns `vehiclesCommand` should probably own that signal.

About the events not being delivered, make sure you've subscribed to `executionSignals` before the command begins executing and that you `switchToLatest` if you want to get the latest batch of results.

**Comment by mAu888** [comment]
Getting there :-) I now added the `vehiclesSignal` to the class holding the command as follows:
```
_vehiclesSignal = [[self.vehiclesCommand.executionSignals switchToLatest] replayLast];
[self.vehiclesCommand execute:nil];
```

ViewController A & B subscribe to that signal and additionally can `-execute:` the `vehiclesCommand`, that is also exposed as a property. The only nice thing left would be, that the command gets automatically executed once the first subscription is made to the `vehiclesSignal`.
Right now I'm manually firing `-execute` after I create the `vehiclesSignal`.

**Comment by adly-holler** [comment]
Glad it's working for you! Hmm there's not a way to do this that's worth the extra code. One way would be

```objectivec
dispatch_once_t token = (dispatch_once_t)0;
RACCommand *localVehiclesCommand = self.vehiclesCommand; // cheap way around self retain cycle
_vehiclesSignal = [[[self.vehiclesCommand.executionSignals switchToLatest] replayLast] initially:^{
    dispatch_once(&token, ^{
        [localVehiclesCommand execute:nil];
    });
}];
```

**Comment by mAu888** [comment]
That works like a charm. For the sake of completeness my final implementation as follows:

```objc
- (instancetype)initWithAPIClient:(IAAPIClient *)apiClient
{
    self = [super init];
    if ( self )
    {
        _APIClient = apiClient;
        __weak typeof(self) weakSelf = self;
        _vehiclesSignal = [[[self.vehiclesCommand.executionSignals switchToLatest] replayLast] initially:^{
            __strong typeof(weakSelf) strongSelf = weakSelf;
            [strongSelf.vehiclesCommand execute:nil];
        }];
    }
    return self;
}

- (RACCommand *)vehiclesCommand
{
    if (nil == _vehiclesCommand)
    {
        __weak typeof(self) weakSelf = self;
        _vehiclesCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
            return [RACSignal createSignal:^RACDisposable *(id <RACSubscriber> subscriber) {
                __strong typeof(weakSelf) strongSelf = weakSelf;
                [strongSelf.APIClient vehiclesWithCompletion:^(NSArray *vehicles, NSError *error) {
                    if ( vehicles )
                    {
                        [subscriber sendNext:vehicles];
                        [subscriber sendCompleted];
                    }
                    else
                    {
                        [subscriber sendError:error];
                    }
                }];

                return (RACDisposable *)nil;
            }];
        }];
    }

    return _vehiclesCommand;
}
```

Of course I'm open to improvements :-)
