### ISSUE TITLE
RACCommand signals should deliver synchronously when possible

### ISSUE THREAD

**Issue by adly-holler** [ReactiveCocoa/ReactiveCocoa#1820]
Right now, RACCommand uses `deliverOn:RACScheduler.mainThreadScheduler` to shunt events onto the main thread, which means that let's say I have a table view with a `loadNextPageCommand`, and I bind `executing` to a spinner that I show in the footer. As it is right now, the spinner may show for another frame after the command finishes executing and the table view is updated. It would sure be nice to use the delightful `deliverOnMainThread` operator and deliver command events synchronously in some cases.

**Comment by jspahrsummers** [comment]
This is already the case in RAC 3.0 with the `Action` type.

I don't think we can change the semantics of `RACCommand` without considering it a breaking change.

**Comment by adly-holler** [comment]
Hogwash! How's it a change to the semantics? For `executing`, `enabled`, `errors` and `executionSignals` the docs only say "all values will arrive on the main thread."

**Comment by jspahrsummers** [comment]
Performing a command's work synchronously could break some expectations in applications—for example, if they depend upon the fact that the command will not do any work while executing the method that was originally called.
