### ISSUE TITLE
Is 3.0 only support iOS 8.0 and above?

### ISSUE THREAD

**Issue by bagusflyer** [ReactiveCocoa/ReactiveCocoa#1821]
I'd like to use Swift so that I used 3.0.0.alpha.1. But here comes one issue that my app can only run in iOS 8. Is there a way to overcome this issue? Thanks

**Comment by jspahrsummers** [comment]
RAC 3.0 is not ready for production use. Do not use it.

When it is ready, it will only support iOS 8+. Sorry, but it's not worth the effort to support earlier releases when there's a [perfectly usable release](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v2.3.1) already available.
