### ISSUE TITLE
RACChannelTo under Swift in RAC 2.x

### ISSUE THREAD

**Issue by seboslaw** [ReactiveCocoa/ReactiveCocoa#1827]
Hey,

since it took me some time to figure this out, I thought I'd leave a comment for others who struggle with the same issue. Since RACChannelTo is not available under Swift (with Reactive Cocoa v2.x), you have to do the following to setup a two-way binding between e.g. a UISwitch and a model property:

```
let setAlarmTerminal:RACChannelTerminal = self.SetAlarmSwitch.rac_newOnChannel()
let viewModelChannel = RACKVOChannel(target: self.viewModel, keyPath: "setAlarm", nilValue: 0)["followingTerminal"]
setAlarmTerminal.subscribe(viewModelChannel)
viewModelChannel.subscribe(setAlarmTerminal)
```

**Comment by edwardIshaq** [comment]
Thanks for posting that.
what does '["followingTerminal"]' do in this case ? does it act like a subscript of some sort ?

**Comment by edwardIshaq** [comment]
oh cool, it is a subscript: 

extension RACKVOChannel {   
    subscript (key: String!) -> RACChannelTerminal!
}

**Comment by seboslaw** [comment]
Awesome...just fought with this for another 45 min, just to find my own post (above) within a Google search....hooray for brain
