### ISSUE TITLE
The correct way to bind DynamicProperty to a signal

### ISSUE THREAD

**Issue by slabko** [ReactiveCocoa/ReactiveCocoa#1828]
I can bind `MutableProprty` to a signal using `<~` operator. However there is no way to do the same for `DynamicProperty`, even if nothing (technically) prevents from it, since `DynamicProperty` can also be modified. 

Do I miss something?

**Comment by jspahrsummers** [comment]
Nope, you've definitely caught a bug here. Thanks for finding that! :sparkles:

We'll either need to overload the `<~` operator on `DynamicProperty`, or add another protocol type representing mutable properties.

**Comment by slabko** [comment]
I think `DynamicProperty` fall in a really separate category, and generalization is not required here.

However if `PropertyType` meant to be inherited, there is no way to create my own mutable `PropertyType` and take advantage of existing operators and methods. That is where protocol can help. But I don't see any situation when I should inherit `PropertyType`, and even I can imagine it, I think, operators and methods could also be different.

So I don't think we need protocol for that.

**Comment by jspahrsummers** [comment]
`PropertyType` can be used for any observable “property-like” thing. It's also a convenient constraint for an API.

I think we could create a mutable protocol for the same reason, and make the current `MutableProperty` and `DynamicProperty` types conform to it.

**Comment by slabko** [comment]
I don't know. When you create the API, why you need something more than already exist: `MutableProperty` and `PropertyOf`? When we think about creating a `MutablePropertyType` protocol, now we need keep in mind a things like:
Is the object that implements new `MutablePropertyType` class or structure? If it's class, we have to keep weak references for classes, but not structures, since compiler not happy, when you "weakify" a struct. 
And it probably worth it, if people really need more that already exist. Which is, by my opinion, not a case.

Probably, people are going to create a property on top of some low-lever thing. If it's true, and they extend an object, they, I believe, not only responsible for extending operators as well (like <~) but also they want to justify operators behavior.

**Comment by slabko** [comment]
Sorry, I don't really get how #1833 helps here.

**Comment by jspahrsummers** [comment]
I'm afraid I don't understand your objections to having two protocols (`PropertyType` and `MutablePropertyType`). Creating additional types isn't a burden, so what's the issue?

**Comment by slabko** [comment]
I actually though about how the `MutablePropertyType` will be used, and worried, that we need different implementation of operators for value and references implementations (classes and structs), since value type can't be weakified, and reference must be weakified. But I think now, I was wrong, `MutablePropertyType` will never be implemented by a value type. Sorry for extra worries :). I was wrong - `MutablePropertyType` will definitely work here.
