### ISSUE TITLE
Dispose RACSignal when using filters

### ISSUE THREAD

**Issue by hwaxxer** [ReactiveCocoa/ReactiveCocoa#1831]
I have a `UITextField` that needs both local and server validation. I don't want to make unnecessary requests to the server so I am filtering out invalid input. However, if the user is on a slow connection, and a request to the server has been made while the user keeps typing and enters input that **is filtered**, the new signal will fail due to the filter, and the old signal will fire, causing a corrupt state.

The code looks something like this:
```objective-c
[[[[[self.textField.rac_textSignal doNext:^(NSString *textFieldText) {
    self.button.enabled = NO;
  }] filter:^BOOL(NSString *text) {
    return [self isTextValid:text];
  }] throttle:0.5] flattenMap:^RACStream *(NSString *text) {
    return [self signalForRemotelyValidatingText:text];
  }] subscribeNext:^(NSNumber *isValidNumber) {
    self.button.enabled = isValidNumber.boolValue;
  }];
```

The request signal looks something like this:
```objective-c
- (RACSignal *)signalForRemotelyValidatingText:(NSString *)text {
  return [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
    NSURLSessionDataTask *task;
    task = [APIController doSomethingWithText:text
                                      success:^(NSURLSessionDataTask *task) {
                                        [subscriber sendNext:@YES];
                                      } failure:^(NSURLSessionDataTask *task, NSError *error) {
                                        [subscriber sendNext:@NO];
                                      }];
    return [RACDisposable disposableWithBlock:^{
      [task cancel];
    }];
  }];
}
```

I can't figure out how to dispose the request signal when the text changes but I know the filters are part of the problem. Of course I could easily check text equality when my request finishes, but it feels like a bad pattern. I've tried to use `-takeUntil:` and passing the textSignal to the request signal but that doesn't work either. 
Any help is greatly appreciated!

**Comment by powerje** [comment]
It looks to me like you should be sending onComplete after your APIController finishes its work? That is, unless the success/failure blocks can be called multiple times.

**Comment by powerje** [comment]
2 things, I think you probably mean to `[subscriber sendComplete];` after your sendNext calls above. Unless you intend for the APIController to call your success/failure blocks multiple times you probably do want to complete the subscription.

The next thing is I think you want to `switchToLatest` after your `flattenMap` in order to only subscribe to the latest signal generated by `flattenMap`.

**Comment by hwaxxer** [comment]
The `sendCompleted` does nothing, but it might be good practice to put it. And calling `-switchToLatest` after `-flattenMap:` will throw an exception:
```
-switchToLatest requires that the source signal (<RACDynamicSignal: 0x7f81787beef0> name: ) send signals. Instead we got: true
```
Switching to `-map:` and calling `-switchToLatest` has no effect either. 

The problem as I see it is that the signal won't even get that far since it's being filtered. 

The problem boils down to this: how can I dispose the request signal as soon as the `rac_textSignal` sends `-next:`?

**Comment by hwaxxer** [comment]
Finally I managed to solve it using a `RACMulticastConnection` with the final code looking like this:

```
  RACMulticastConnection *connection = [self.textField.rac_textSignal publish];
  [connection connect];

  [[[[[connection.signal doNext:^(NSString *textFieldText) {
    self.button.enabled = NO;
  }] throttle:0.5] filter:^BOOL(NSString *text) {
    return [self isTextValid:text];
  }] flattenMap:^RACStream *(NSString *text) {
    return [[self signalForRemotelyValidatingText:text] takeUntil:connection.signal];
  }] subscribeNext:^(NSNumber *isValidNumber) {
    self.button.enabled = isValidNumber.boolValue;
  }];
```

Not sure if this is the cleanest solution, but it works very well!

**Comment by powerje** [comment]
Oh, right - it would need to switch to map, not flattenMap before switchToLatest.

Anyway, glad you got it sorted out!

**Comment by Pitometsu** [comment]
I got similar issue, but in my case I wish to save old values, not just ignore them: https://github.com/ReactiveCocoa/ReactiveObjC/issues/52
