### ISSUE TITLE
Which branch should I use for Swift development?

### ISSUE THREAD

**Issue by bagusflyer** [ReactiveCocoa/ReactiveCocoa#1835]
I tried on RAC 3.0.0-alpha1, but it doesn't support subscribeNextAs, mapAs, FilterAs like what some articles introduced. Which branch I should use to support Swift? Thanks.

**Comment by jspahrsummers** [comment]
The operators you're describing are not part of ReactiveCocoa. The latest Swift release is [v3.0-alpha.2](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-alpha.2).

**Comment by bagusflyer** [comment]
I see. Thanks.
