### ISSUE TITLE
Subscribe to a signal every time a sampler fire and no subscription is already running.

### ISSUE THREAD

**Issue by robb** [ReactiveCocoa/ReactiveCocoa#1836]
I have two signals, a `sampler` and a Signal that represents a network request.

I'd like to update my model with the latter Signal every time the `sampler` fires, but if a request is already in flight, there is no reason to cancel it. I currently have this:

```objc
RAC(self, model) = [[sampler
    map:^(id _) {
        return [client fetchModel];
    }]
    concat];
```

However, if `sampler` fires frequently (let's say once a second) and `fetchModel` takes longer than that, the requests will keep piling up. Am I missing a simple way to (re-)subscribe to `fetchModel` only if there is no request in progress?

**Comment by neilpa** [comment]
We backported `-shareWhileActive` from the Objective-C RAC 3.0 codebase to RAC 2.0 and have been using it for some time

https://gist.github.com/fouvrai/5540a15c5a1bdcc31787

**Comment by robb** [comment]
That's :sparkles:, but I'm not 100% sure how to make use of it in this case. Could you elaborate? :bow:

**Comment by robb** [comment]
Also, @ReactiveCocoa/reactivecocoa how'd you feel to officially back-port this to 2.x?

**Comment by neilpa** [comment]
It's going to depend a bit on the interaction between your models and networking layers. Our general approach is to have model objects wrap a cold signal from our networking layer in `-shareWhileActive` and store that in a property.

```objc
@interface Model
@property RACSignal* signal;
@end

@implementation Model
- (RACSignal*) signal {
    if (!_signal) {
        _signal = [[self.api networkRequest] shareWhileActive];
    }
    return _signal;
}
@end

/// ... 
RAC(self, property) = [[sampler
    map:^(id _) {
        return model.signal
    }]
    concat];

```

Then it's safe to subscribe that signal multiple times but still only have one actual network request in-flight at a time.

So the only thing for you is to figure out where it makes the most sense to store the wrapped `-shareWhileActive` signal.

**Comment by robb** [comment]
Oh, easier than I thought :gift_heart:

**Comment by neilpa** [comment]
The original discussion around `shareWhileActive` was in #1433 but didn't really go anywhere.

**Comment by jspahrsummers** [comment]
I think #1433 is a good example for why I've been avoiding adding more to the Objective-C codebase. I want to go full-bore on the Swift API, and anything more that we add to the Objective-C API could introduce bugs, and means yet another thing we have to support.

I'm not strictly opposed if there's something that's really important, but I'd like to avoid it as a rule. How do others feel about `-shareWhileActive` in particular?

**Comment by adly-holler** [comment]
This is a really, really awesome operator that I've wanted a couple times. Especially when dealing with frameworks whose behavior handling multiple equivalent requests is not documented – say, Apple's Photos framework or pretty much any photo loading/caching framework.

**Comment by k** [comment]
I would really like this operator as well. Very useful in cases where multiple events could trigger a data update.

**Comment by k** [comment]
@neilpa One question though. Why do you need the `concat` when binding the signal to the property?

**Comment by neilpa** [comment]
Becuase we're creating a signal of signals here. The `-concat` is what flattens the values of the inner `model.signal` into the outer signal for assignment to the property.
