### ISSUE TITLE
Rename joinMap to flatMap for stdlib consistency?

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1842]
`joinMap` predates `flatMap` in the stdlib, but maybe it's worth renaming it to be consistent now.

We would still have our `strategy` parameter, which makes it a little different, but it would at least highlight the parallels.

Thoughts?

**Comment by nomothetis** [comment]
From a theoretical standpoint, `flatMap` is supposed to be the monadic bind. In particular, it's supposed to follow the third monad laws; do all three strategies fulfill that  contract? And do we care?

**Comment by jspahrsummers** [comment]
> In particular, it's supposed to follow the third monad law; do all three strategies fulfill that contract?

I believe all the laws hold for each, but I haven't set out to prove that it is so.

> The main reason I think we might is if we one day see for-comprehensions; I'm not sure what the interaction will be.

That's an interesting point to consider, but I don't think it applies to our `joinMap`/`flatMap` operator, since it wouldn't work by default anyways (due to the presence of the `strategy` parameter)

**Comment by nomothetis** [comment]
That would be fascinating if all three did. It would mean mean that `SignalProducer` is essentially three different monads wrapped in one…I'm not even sure how to deal with that right now. Does this count as code smell? Is this a more common happenstance than I would have expected?

I'll see if I can find time to determine whether all three parameters result in compliant monadic binds.

**Comment by nomothetis** [comment]
For the record, trying to prove anything about code you don't fully understand is very hard. I haven't managed it yet. But I have learned enough to develop an intuition. I suspect `.Merge` and `.Latest` will run afoul of the second law in threaded situations, but I haven't figured out how to use asynchronous controlled producers yet.

So my intuition, that I will keep trying to turn into a proof (or counterproof) is that `flatMap` on `SignalProducer` is `joinMerge` with `.Concat`. The others are useful and interesting, but probably not monadic binds.

If anyone wants to think about creating proof (or counterproof) of this, I'd sure appreciate the help, though.

**Comment by jspahrsummers** [comment]
Interesting! `.Merge` is the one I would've thought _most likely_ to be monadic bind, because it corresponds to LINQ's `SelectMany`, which is _supposed_ to be `>>=`.

Out of curiosity, what are you using to investigate/prove these things? I'd love to take a look.

**Comment by nomothetis** [comment]
Well, remember, I don't fully understand the code, so my intuition could very well be wrong…

I've been using a playground trying to break them. I committed on my own fork, in the monad-tests branch, if you want to check it out. The tests I have only test the second law, and they all work, but the tests themselves are synchronous, so I don't think they would hit the breakage point, if it exists.

**Comment by nomothetis** [comment]
Incidentally, I may be misreading this, but this [article][http://ericlippert.com/2013/04/02/monads-part-twelve/] says this is the `SelectMany` implementation that corresponds to bind:

```csharp
public static IEnumerable<R> SelectMany<A, R>(
  this IEnumerable<A> items, 
  Func<A, IEnumerable<R>> function)
{
  foreach(A outer in items)
    foreach(R inner in function(outer))
      yield return inner;
}
```

Isn't that what `.Concat` does in our case? It goes through each `Signal` until it terminates?

**Comment by jspahrsummers** [comment]
@nomothetis That's the `SelectMany` implementation over `IEnumerable`, which has the luxury of being synchronous. `SelectMany` for `IObservable` is significantly more complex (but still intended to represent `>>=`).

**Comment by Coneko** [comment]
I agree with @jspahrsummers: I think the laws are valid for all three strategies as RAC defines them.

The bad news is it doesn't tell us anything we don't already know: monad laws are properties of `return` and `flatMap` (or `joinMap`). They don't help reasoning about ways of creating signals that aren't `return`, and ways of transforming signals that cannot be expressed with `flatMap`.

**Comment by nomothetis** [comment]
I see. Thanks for the clarification. I haven't had time to play more with the laws and see if they hold, but at this point I'm tempted to trust both of you more than my shaky intuition.

Which brings up the question: if each version of `joinMap` is a valid `flatMap`, `SignalProducer` is actually multiple monads. Does that mean it should have specific subtypes for each `joinMap`?

**Comment by kastiglione** [comment]
> `SignalProducer` is actually multiple monads.

[`return`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/11817446874c82328ed6b8f34d75c38bb359b08b/ReactiveCocoa/Swift/SignalProducer.swift#L43-L48) and [`>>=`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/11817446874c82328ed6b8f34d75c38bb359b08b/ReactiveCocoa/Swift/SignalProducer.swift#L577-L601)

**Comment by nomothetis** [comment]
@kastiglione — 0.o

Okay, I no longer have an opinion on any of this. I need to spend some quality time thinking about everything. :-)
