### ISSUE TITLE
`flatMap` for `Event`

### ISSUE THREAD

**Issue by nomothetis** [ReactiveCocoa/ReactiveCocoa#1843]
We've started writing some RAC 3.0 code, and I noticed there isn't a `flatMap` implementation for `Event`. Given the existence of `materialize` and `dematerialize`, that seems like missing functionality, especially since `map` is implemented. Is there a reason for this, or could I maybe do a pull request and provide an implementation?

**Comment by jspahrsummers** [comment]
I'm not necessarily opposed, but how would you use it? It seems rare outside of `dematerialize` specifically.

**Comment by nomothetis** [comment]
Hmm. Now that I'm thinking about it, it seems like what I have in mind would be very similar to doing something like

```swift
signal |> map(toEvent) |> dematerialize
```

Basically, we have a `SignalProducer<T, E>` that needs to become a `SignalProducer<U,E>`. The thing is, there is no `T->U` function, only a `T -> Result<U, E>`, or, alternatively, `T -> Event<U,E>`. It seems like using the latter allows us to use `Event` as an error propagation mechanism. Is that abusing the notion?

**Comment by jspahrsummers** [comment]
If you have `T -> Result<U, E>`, I would use `tryMap` directly.

**Comment by nomothetis** [comment]
!! I knew that use-case couldn't have been overlooked. Thanks a lot, that's exactly what I was looking for.

**Comment by jspahrsummers** [comment]
No problem!
