### ISSUE TITLE
subscribing to UISegmentedControl selectedSegmentIndex changes

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#1849]
I have an application where a segmented control will determine the source of the data of a UICollectionView.
I'm having trouble writing this concept using ReactiveCocoa.
My initial approach is to subscribe to the changes of signal of the segmentedControl and reload the data.
When reloading the data get the data from the correct source.

so when I do this:
    @IBOutlet weak var mediaTypeSwich: UISegmentedControl!  //With only 2 options 0 and 1

        RACObserve(mediaTypeSwich,"selectedSegmentIndex").subscribeNext { (sender:AnyObject!) -> Void in
            println(sender)
        }

a few strange things happen:
I see the println value change: 
 println(sender)
  0
  1
  -1 

So question 1: why am i getting the value changes not only from the user changes but seems like something else is triggering them from RAC... ?

and question 2: whats the best way to go about doing this ?
Cause the only category i see in reactive cocoa is to create a channel from the SegmentedControl and I haven't yet used channels at this point as I am just starting with RAC.

**Comment by edwardIshaq** [comment]
Even when I create a signal for valueChanged control Event, the segmentedControl stops preserving the selection:

        mediaTypeSwich.rac_signalForControlEvents(.ValueChanged).subscribeNext { (sender:AnyObject!) -> Void in
            println(sender)
        }

**Comment by edwardIshaq** [comment]
I ended up doing:

        mediaTypeSwich.rac_signalForControlEvents(.ValueChanged)
            .flattenMap { (sender:AnyObject!) -> RACStream! in
                let segment = sender as UISegmentedControl
                switch segment.selectedSegmentIndex {
                case 0:
                    return self.photoSignal()
                
                default:
                    return self.videoSignal()
                }
            }
            .deliverOnMainThread()
            .subscribeNextAs{(photosFetchResult: PHFetchResult) in
                self.fetchResult = photosFetchResult
                self.mediaCollectionView.reloadData()
            }

The only issue i have left to resolve is that the signal won't trigger until the user makes a selection.
How can I make it load the default selection first ?

I tried calling this right after but with no success
        mediaTypeSwich.selectedSegmentIndex = 0

**Comment by edwardIshaq** [comment]
I ended up appending this code below the block above to load the data

        //Initial load photos
        photoSignal()
            .deliverOnMainThread()
            .subscribeNextAs(...)

**Comment by jspahrsummers** [comment]
Looks like this got resolved?

**Comment by edwardIshaq** [comment]
Is there a better reactive way to trigger the initial loading of the signal ? Instead of subscribing again to photoSignal ?

**Comment by jspahrsummers** [comment]
You could use something like `-startWith:` or `-rac_signalForSelector:` to generate a signal event immediately or when something happens (respectively).

**Comment by edwardIshaq** [comment]
@jspahrsummers thanks for the answer, I'm not sure exactly how to implement this.
I've called startWith on my signal but now it crashes on "Swift dynamic cast failed" 
Not sure why 

        //Dispense Videos/Photos by selecting an option of the UISegmentedControl
        let segmentSignal = mediaTypeSwich.rac_signalForControlEvents(.ValueChanged)
            .flattenMap { (sender:AnyObject!) -> RACStream! in
                let segment = sender as UISegmentedControl
                switch segment.selectedSegmentIndex {
                case 0:
                    return self.photoSignal()
                
                default:
                    return self.videoSignal()
                }
            }
        
        segmentSignal.startWith(self.photoSignal())

        segmentSignal
            .deliverOnMainThread()
            .subscribeNextAs(refreshCollectionView)


my understanding is that I'm sending the same signal value as if the user pressed on the segmentedControl...

**Comment by jspahrsummers** [comment]
`startWith` is a transformative operator that gives you a new signal, with the value you've provided becoming the initial value of that signal. It can't be used imperatively.

I was trying to suggest that you might want to `startWith` an initial trigger, like your `UISegmentedControl`, before the `flattenMap`.

**Comment by edwardIshaq** [comment]
I ended up using startWith and passing the UISegmentedControl as an argument since thats what my signal was sending. This helped :)
Thanks @jspahrsummers

**Comment by jspahrsummers** [comment]
No problem!
