### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by bpq** [ReactiveCocoa/ReactiveCocoa#1851]
Is there a Swift port of this already out there?

**Comment by JaviSoto** [comment]
ReactiveCocoa 3.0 is in the works. No release date yet. If you're not developing something in production, feel free to check out an alpha at your own risk :smiley:: https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-alpha.3

**Comment by cdzombak** [comment]
And in the meantime, you can use something like https://github.com/ashfurrow/Swift-RAC-Macros to use RAC 2.x in Swift, with sane interop with your ObjC code.
