### ISSUE TITLE
Swift applications written in RAC 3.0

### ISSUE THREAD

**Issue by MichaelMcGuire** [ReactiveCocoa/ReactiveCocoa#1852]
I have a question regarding the future of the `swift-development` branch of RAC.  I will be starting a new application in the coming weeks and was interested in using RAC 3.0.  Being a completely new application, and myself being new to RAC, I'm wondering how "complete" the 3.0 API's are?  As I've been reading tutorials on RAC 2.0, there appears to be functionality present in the older API's not yet in the new API.  An example of this are the myriad of extensions for interacting with Cocoa/Cocoa Touch API's (NSFileHandle, NSUserDefaults, AppKit/UIKit extensions).  Are there plans to do the same for the new Swift API's? Or is the plan for now to use the translation layer between Signal/SignalProducer/Action and RACSignal/RACCommand for that support?

**Comment by jspahrsummers** [comment]
I think we can add APIs like that on an as-needed basis, after the release of RAC 3.0.

Until they exist officially in Swift, the bridging layer should be good enough to get the same functionality.
