### ISSUE TITLE
how to use “rac()" with swift?

### ISSUE THREAD

**Issue by 861645007** [ReactiveCocoa/ReactiveCocoa#1853]
I use swift to complete a project with rac3.0, but I have a problem that I can't use rac().
In object-c, we can use rac() or racobserve(), but I can't use these in swift. 
So, how to use rac? 
Thank you,

**Comment by jspahrsummers** [comment]
You can use one of the `PropertyType` implementations for the same effect. See `DynamicProperty` in particular.

**Comment by 861645007** [comment]
I'm sorry, Sorry, I have not found a way With PropertyType （How to use DynamicProperty?） , I want to use UIKIt the RAC, such as RAC (self.imageView, image) = RACObsever ();

Is there any case be able to reference it？

**Comment by 335g** [comment]
Now, There isn't reference.

Please refer to a [weblog] (http://qiita.com/335g/items/a53e06f543496dba462a) in Japanese.

**Comment by 861645007** [comment]
@335g  thank you

**Comment by 861645007** [comment]
@335g  sorry, I can't found DynamicProperty.
my project gain DynamicProperty with pods.

pod 'ReactiveCocoa', '~> 3.0.0-alpha.1'

**Comment by 335g** [comment]
That's podspec is not certainly support `DynamicProperty`.

If you want to use now, you can use [Release v3.0-alpha3](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-alpha.3) or `swift-development branch` with [Carthage](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-alpha.3). 
Well, I think that it is immediately released.

**Comment by 861645007** [comment]
@3359 soga， thank you
