### ISSUE TITLE
DynamicProperty binding lifetime

### ISSUE THREAD

**Issue by adly-holler** [ReactiveCocoa/ReactiveCocoa#1855]
It seems reasonable that DynamicPropertys should be kept alive at least long enough for the use case 

```swift
DynamicProperty(cell, "imageView.image") <~ myImageSignal
```

to be possible without storing a strong reference to the property. As it is today (`v3.0-alpha3`), that code completely fails – the binding only sticks if you keep the property alive somewhere. Maybe keep it alive until the object will deallocate? Or keep it alive until the run loop ends without a signal bound to it?

**Comment by adly-holler** [comment]
Check out https://github.com/adly-holler/SwiftRACGoogleImages for a (non)working example

**Comment by jspahrsummers** [comment]
Good catch! I agree that the property binding should stay alive as long as the cell or signal in that case.

The `DynamicProperty` itself doesn't necessarily need to, though.

**Comment by Ben-G** [comment]
Just ran into the exact same issue. @jspahrsummers which solution do you have in mind that would not involve keeping the `DynamicProperty` alive?

**Comment by jspahrsummers** [comment]
@Ben-G Sorry, hard for me to describe anything in detail without just implementing it. :wink:

I'll take a look at #1857 and see if that resolves the issue, though.
