### ISSUE TITLE
Chaining dependent signals without parameterization

### ISSUE THREAD

**Issue by ethanlynn** [ReactiveCocoa/ReactiveCocoa#1856]
I've just recently started developing an application with ReactiveCocoa and often feel the need for an operation analogous to Haskell's (>>) function. Basically this function chains together two monads without parameterizing the left-hand monad (i.e., a >> b === a >>= \ _ -> b). Practically this becomes very valuable when you're working with signal's that don't have data, because you can simply chain together sequences of dependent operations without the need for a function that always returns the same signal.

For example, instead of having to write

```objective-c
a.flattenMap(^(...) { return b }).flattenMap(^(...) { return c })
```

or

```objective-c
a.mapReplace(b).flatten.mapReplace(c).flatten
```

you would just write

```objective-c
a.flattenMapReplace(b).flattenMapReplace(c)
```

Ignoring the fact that flattenMapReplace is an awful name for this, I think an operation like this would be very helpful for dealing with event/RACUnit signals since they don't ever require parameterization (unless of course you're decide to break referential transparency in flattenMap).

**Comment by jspahrsummers** [comment]
Were you able to figure out a solution here? We usually use `then()` for this purpose, if I understand the question correctly.

**Comment by ethanlynn** [comment]
`then()` is great for dealing with signals that complete, but I was wondering if there currently is (or should be) an operation very similar to `flattenMap` that doesn't require a block. So, for instance, currently you would have:

```objective-c
[someSignal flattenMap:^(...no relevant arguments...) {
    RACSignal *doesNotRequireArguments = [RACSignal createSignal:...];
    return doesNotRequireArguments
}]
```

This isn't ideal because a new signal and closure are created each time the block is called. The natural solution is to move the signal outside the block:

```objective-c
RACSignal *doesNotRequireArguments = ...;
[someSignal flattenMap:^(...) { return doesNotRequireArguments }]
```

All I was suggesting is that when a block is unnecessary, it would be convenient to have a stream operation that accepts just another stream. The reason this is useful is because `doesNotRequireArguments` might have side effects and needs to be reevaluated each time `someSignal` pushes, but those side effects themselves don't require any contextual information provided by `someSignal`.

For a real world example of how this might be useful, here's some fake networking code:

```objective-c
RACSignal *becomeReachable; // Hot signal that pushes to subscribers each time the network becomes available
RACSignal *signIn; // Signs in over a network, sends either a next and complete or error.
RACSignal *getResource; // Retrieves a resource, sends it via next, and then sends complete

// Now we can create a signal that automatically loads the most recent data from a web service.
RACSignal *latestResource = [[becomeReachable
    flattenMap:^(...) { return signIn }]
    flattenMap:^(...) { return getResource }];

// Or using `bindReplace:___` instead of `flattenMap:^(...) { return ___ }`

RACSignal *latestResource = [[becomesReachable bindReplace:signIn] bindReplace:getResource]
```

**Comment by jspahrsummers** [comment]
In RAC 2.x, you can use the `-mapReplace:` operator for this, followed by `-flatten`. There isn't a corresponding operator in RAC 3 that avoids a closure, though.

Why is the use of a closure undesirable, though? If it has a constant return value, it might even get inlined by the compiler.

**Comment by ethanlynn** [comment]
I agree that an extra closure isn't really a problem in terms of performance, I was just curious if `-mapReplace:`, `-flatten` was common enough that it should be reduced into a single method. The other thing I realize know, and the reason I closed the issue earlier, is that I think I may have been trying to fit too much application functionality into streams (hence the need for so many `-flattenMap:`'s). Although they're a wonderful conceptual aid when it comes to flattening callback trees, untangling dependencies, etc., after a certain point I think adding a little imperative code goes a long way. There's seems to be a happy medium between writing the unpleasant delegate-oriented style CocoaTouch promotes and the more sane stream-oriented approach ReactiveCocoa offers. Either way, I suppose I'll just have to tame my inner Haskeller a while longer. With Swift in the mix now, I'm hoping Apple starts encouraging functional programming and rewriting there own APIs in a more declarative style, but maybe that's just wishful thinking.
