### ISSUE TITLE
Binding to dynamic signal without casting to `AnyObject?`

### ISSUE THREAD

**Issue by Ben-G** [ReactiveCocoa/ReactiveCocoa#1858]
It seems that because the type of `Value` for `DynamicProperty` is `AnyObject?` every signal that wants to bind to a dynamic property needs to be casted to `AnyObject?`.

Looking at the method signature of the bind operator this makes sense:
`public func <~ <T: AnyObject, P: MutablePropertyType, DynamicProperty where P.Value == T>(property: P, signal: Signal<T, NoError>) -> Disposable`

The type of the signal and the value of the property need to match exactly. **Is there no way in Swift to express that any subtype of `AnyObject?` should be acceptable as well?**

Here's a snippet I've been playing around with:

      let signal = post!.likes.producer.lift(map { $0.reduce("") { $1.username } as AnyObject? })
      textProperty = DynamicProperty(object: likesLabel, keyPath: "text")
      textProperty! <~ signal

When casting to `NSString?` or `NSString` instead of `AnyObject?` the compiler complains that the `<~` operator is not applicable for the given types.

Could someone with a better understanding of Swift's type system explain wether the generic constraint I'm looking for is available or not?

**Comment by Ben-G** [comment]
Interesting. I just found out that the issue does not occur when binding the signal directly, without creating an intermediate variable:

    textProperty! <~ post!.likes.producer.lift(map { return self.stringFromUserlist($0) })

**Comment by jspahrsummers** [comment]
On the latest version of `swift-development`, `<~` is defined generically over any `MutablePropertyType`. I'm afraid there's no way to loosen its type constraints specifically for `DynamicProperty`.
