### ISSUE TITLE
Map Command/Action input

### ISSUE THREAD

**Issue by adly-holler** [ReactiveCocoa/ReactiveCocoa#1861]
What's the cleanest way to map the input of a RACCommand, on the view side? For example, I'm writing an MVVM app where navigation commands take `UIResponder` as input, and follow the responder chain up to find an appropriate view controller to call `showViewController` on. This works great for `UIButton.rac_command` but not so great for `UIBarButtonItem.rac_command`. Is there any way to map the input of the command at the assignment site, so I can have the button item execute the command with e.g. my view controller?

**Comment by jspahrsummers** [comment]
You can create another `RACCommand` that wraps your existing one, or else hook up the `UIBarButtonItem` explicitly (with the input you want) instead of using the `rac_command` property.

**Comment by adly-holler** [comment]
OK yeah. It's just a shame that `RACCommand` delivers its updates asynchronously, so wrapping one in another is gonna get weird real fast. I'll probably make some sort of `RACMappedCommand` subclass where you can set an input mapping block.
