### ISSUE TITLE
startOn() Doesn't Execute start() Arguments on the Proper Scheduler

### ISSUE THREAD

**Issue by nebhale** [ReactiveCocoa/ReactiveCocoa#1863]
In the `swift-development` branch, the `startOn()` function doesn't appear to execute `start()` arguments on the proper `Scheduler`.  It's possible that I'm completely misunderstanding how this is supposed to work as I'm learning via code inspection, but the following test case illustrates the problem:

```swift
it("starts on specified scheduler") {
    let propertyA = MutableProperty<Int>(0)
    let propertyB = MutableProperty<Int>(0)

    var valuesA: [Int] = []
    var valuesB: [Int] = []

    propertyA.producer
        |> startOn(QueueScheduler())
        |> start(next: { value in
            expect(NSThread.isMainThread()).to(beFalsy())
            valuesA.append(value)
            propertyB.put(value)
        })

    propertyB.producer
        |> startOn(UIScheduler())
        |> start(next: { value in
            expect(NSThread.isMainThread()).to(beTruthy())
            valuesB.append(value)
        })

    propertyA.put(1)

    expect(valuesA).toEventually(equal([0, 1]))
    expect(valuesB).toEventually(equal([0, 0, 1]))
}
```

Both of the `isMainThread()` expectations fail.  I find this odd, as it appears that the `Scheduler` is changed _after_ the `next` closures are run, rather than before.  Is this just a case of misunderstanding the model on my part?

**Comment by nebhale** [comment]
I've now realized that instead of `startOn()` I should be using `observeOn()`.  Can you give me some insight into the difference between them?  When is it appropriate to use one rather than the other?

**Comment by neilpa** [comment]
Most of the time you're going to use `observeOn`. It controls which scheduler events are delivered on to consumers. `startOn` only controls the scheduler where a producer's setup method is run. This doesn't necessarily affect what scheduler events are delivered on.

This is probably best illustrated with a simple example

```swift
let producer = SignalProducer { observer, disposable in
    // this closure is affected by `startOn`
    let data = someBlockingIO()
    sendNext(observer, data)
    sendCompleted(observer)
}

producer 
    |> startOn(QueueScheduler())
    |> observeOn(UIScheduler())
    |> start ({ next: { value in
        // this closure is affected by `observeOn`
        println(value)
    })

**Comment by nebhale** [comment]
Ah ha. Quite a good example. Thanks for the pointer, and sorry for the noise.
