### ISSUE TITLE
Why isn't replayLazily the default for RACSignals?

### ISSUE THREAD

**Issue by jjbrophy47** [ReactiveCocoa/ReactiveCocoa#1864]

**Comment by jspahrsummers** [comment]
Why do you expect it to be?

**Comment by jjbrophy47** [comment]
Regarding side-effects ... should work done in a signal's handler be idempotent? For instance, I'm currently toggling a switch on tap of a view component - but every subscriber to this signal reruns that code and effectually toggles the switch many times over. Please understand that I'm new to this and wondering if my code is a smell - or I'm misunderstanding FRP. When I put this side effect in the final RAC binding code, it doesn't keep running but then I physically need to move that RAC call to the very end of my viewDidLoad method ....

**Comment by jjbrophy47** [comment]
RACSignal *buttonZeroTouchedSignal = [self.buttonZero rac_signalForControlEvents:UIControlEventTouchUpInside];
    RACSignal *bitZeroSignal = [[buttonZeroTouchedSignal
                                 map:^id(UIButton *bitZero) {
                                     return @(bitZero.selected);
                                 }]
                                startWith:@(0)];
    
    RAC(self.buttonZero, selected) = [bitZeroSignal map:^id(id value) {
        return @(![value boolValue]);
    }];
    
    RAC(self.buttonZero, backgroundColor) = [bitZeroSignal map:^id(NSNumber *bitZero) {
        return [bitZero boolValue] ? [UIColor greenColor] : [UIColor blackColor];
    }];

In this example, I have a signal that responds to a button touch event, and then another signal that subscribes to that event and returns the state of the button. I then use the second signal to change properties on the button itself. How can I do this without using replayLazily? I want the same signal to go to both RAC macro calls. It seems that right now different values are being sent to the two RAC methods.

**Comment by adly-holler** [comment]
This is a little bit oblique to your overall question, but it might be more declarative to bind the button color to its selected state like

```objectivec
RAC(self.buttonZero, backgroundColor) = [RACObserve(self.buttonZero, selected) map:^id(NSNumber *selected) {
    return [selected boolValue] ? [UIColor greenColor] : [UIColor blackColor];
}];
```
Technically UIButton.selected is not documented as KVO compliant, but this works in all current versions of iOS.

Different values are getting sent because the first binding is executing, and updating the button's selected state, and then the second binding is executing, and `bitZeroSignal's map` reads the newly-changed `selected` value from the button.

**Comment by jjbrophy47** [comment]
Awesome that makes a lot more sense, thank you!
