### ISSUE TITLE
How to perform two way binding for Slider?

### ISSUE THREAD

**Issue by onmyway133** [ReactiveCocoa/ReactiveCocoa#1865]
I'm making a player screen, which has current time label, slider. I have PlayerView and PlayerViewModel

In PlayerViewModel (has `timeText` and `sliderValue`)
```
RAC(self, timeText) = [RACObserve(self, sliderValue) map:^id(NSNumber *value) {
        return FPClockStringFromTimeInterval(value.doubleValue);
}];
```

In PlayerView (has `UILabel timeLabel` and `UISlider slider`)
```
RAC(self.timeLabel, text) = RACObserve(self.viewModel, timeText);
RACChannelTo(self.slider, value) = RACChannelTo(self.viewModel, sliderValue);
```

In the PlayerViewModel, I have a AVPlayer and I setup a timer to update `sliderValue`, this makes PlayerView 's slider to update accordingly. All is good

But when I touch the slider to make its value changed, the `viewModel` 's `sliderValue` does not update. It seems on the flow from ViewModel -> View works

I even try dispatching on the main thread (in PlayerView)
```
RACChannelTerminal *viewModelSliderValueTerminal = RACChannelTo(self.viewModel, sliderValue);
    RAC(self.slider, value) = [viewModelSliderValueTerminal deliverOnMainThread];
    [RACObserve(self.slider, value) subscribe:viewModelSliderValueTerminal];
```
but it does not work

How to deal with this?

**Comment by jspahrsummers** [comment]
`UISlider.value` is not KVO-compliant. Most UI properties are not, unless explicitly documented as such.

You'll want to use `UIControlEventValueChanged` instead.

**Comment by onmyway133** [comment]
@jspahrsummers thanks, I go with your solution
