### ISSUE TITLE
The use of rac_description on the input to RACCommand execute: causes problems

### ISSUE THREAD

**Issue by Rupert-RR** [ReactiveCocoa/ReactiveCocoa#1868]
I haven't done a pull request because I'm not sure whether there is perhaps a good reason for this.
Anyway, I am coming across a crash using RAC with Swift when I call ``execute`` on a command passing in an object which doesn't inherit from ``NSObject``. The problem is that the final ``return`` of the method tries to set a name on the connection signal, using the ``rac_description`` of the input. Given that the input is an ``id`` I would have thought that this wouldn't be correct even in pure Objective C if we were to pass in an object not inheriting from ``NSObject``, but this certainly is the case for a pure Swift object.
Is there a reason we are doing this? Wouldn't the description of the command be more pertinent to the connection than its input object?
Thanks in advance for any explanation.
(If this is just an oversight, I'm happy to submit a pull request for it)

**Comment by Rupert-RR** [comment]
A quick browse through the source code has found other instances too (other instances exist but are called on ``self`` which is always an object inheriting from ``NSObject``):
* ``RACEagerSequence return:``
* ``RACSignal+Operations aggregateWithStart::`` (both methods)
* ``RACStream mapReplace:``
* ``RACStream combinePreviousWithStart:``
* ``RACStream ignore:``
* ``RACStream startWith:``
* ``RACStream scanWithStart::`` (both methods)
* ``RACUnarySequence return:``

**Comment by jspahrsummers** [comment]
Hmm, this is a good catch. We haven't really had to worry about objects that don't inherit from `NSObject`, because even proxies end up proxying an `NSObject` in typical Objective-C code.

Swift, of course, changes things. Maybe we could create a (private) global function that checks whether `rac_description` is implemented before calling it?

**Comment by Rupert-RR** [comment]
Excuse my ignorance, but how would that work (especially in Swift)? methods like ``respondsToSelector:`` belong again to ``NSObject`` no? Or are you talking about some kind of global function that the developer can override to do nothing if he is using non-``NSObject`` objects?
Sorry I can't bring any suggestion to the table - I just don't see any reliable way to test for object inheritance in this case.

**Comment by jspahrsummers** [comment]
`-respondsToSelector:` is part of the `<NSObject>` protocol, which Swift objects (and basically any object that wants to play nicely with Objective-C) implement.

**Comment by Rupert-RR** [comment]
Ok, I hadn't realised that. Sounds like a plan then!
