### ISSUE TITLE
rac_valuesAndChangesForKeyPath doesn't send initial value on subscription

### ISSUE THREAD

**Issue by adly-holler** [ReactiveCocoa/ReactiveCocoa#1869]
As of v2.4.7. The docs say it should. Seems like maybe _that's_ the mistake, since there's no talk of what the change info would look like in that case

**Comment by jspahrsummers** [comment]
Yep, this sounds like a documentation bug. Thanks for letting us know!

**Comment by peterstuart** [comment]
Using `NSKeyValueObservingOptionInitial` as the options for `-rac_valuesAndChangesForKeyPath:options:observer:` will send the initial value on subscription. (That's what it looks like `-rac_valuesForKeyPath:observer:`/`RACObserve` are doing to send the initial value, if I'm not mistaken.)

**Comment by jspahrsummers** [comment]
@peterstuart Yep, that sounds right. :+1:

**Comment by kastiglione** [comment]
Resolved by #1878
