### ISSUE TITLE
How to schedule a work but allow it to be cancelled by another signal?

### ISSUE THREAD

**Issue by onmyway133** [ReactiveCocoa/ReactiveCocoa#1870]
When button A is pressed, I want to schedule a work in 5 seconds from now. But when button B is pressed, I want to cancel that work.

I'm using RACScheduler for now, and use RACDisposable to cancel it

```
[[self.buttonA rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(id x) {
        self.disposable= [[RACScheduler mainThreadScheduler] afterDelay:5 schedule:^{
            [self performWork];
        }];
    }];
```

```
[[self.buttonB rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(id x) {
        [self.disposable dispose];
    }];
```

How to make it more declarative? As using `subscribeNext` and `RACDisposable` is not encouraged. How to use `RACSignal` to solve this?

**Comment by eimantas** [comment]
I usually use `takeUntil:` operator with a signal that should cancel the work.

```objective-c
RACSignal *buttonBSignal = [self.buttonB rac_signalForControlEvents:UIControlEventTouchUpInside];
[[self.buttonA rac_signalForControlEvents:UIControlEventTouchUpInside] takeUntil:buttonBSignal];
```

**Comment by onmyway133** [comment]
@eimantas thanks, `takeUntil` solves my problem
