### ISSUE TITLE
What is the difference between defer and createSignal

### ISSUE THREAD

**Issue by onmyway133** [ReactiveCocoa/ReactiveCocoa#1872]
In this article [ReactiveCocoa Concepts for Asynchronous Libraries](http://spin.atomicobject.com/2015/03/19/reactivecocoa-asynchronous-libraries/) the author mentions `defer`

```
- (RACSignal *)calculateTomorrowsDate {
    return [RACSignal defer:^{
        NSDate *tomorrow = [[NSDate date] dateByAddingTimeInterval:24 * 60 * 60];
        return [RACSignal return:tomorrow];
    }];
 }
```

I think I can write it like this, using `createSignal`
```
- (RACSignal *)calculateTomorrowsDate {
    return [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        NSDate *tomorrow = [[NSDate date] dateByAddingTimeInterval:24 * 60 * 60];
        [subscriber sendNext:tomorrow];
        [subscriber sendCompleted];

        return nil;
    }];
}
```

So what is the difference ?

**Comment by jspahrsummers** [comment]
`+defer:` is just a wrapper for `+createSignal:`, but it makes it clearer if you expect to _synchronously_ return _one_ signal, and don't need to implement custom cancellation behaviors.

It just clarifies intent.
