### ISSUE TITLE
Consider using DSL syntax

### ISSUE THREAD

**Issue by onmyway133** [ReactiveCocoa/ReactiveCocoa#1873]
I don't know if RAC 3.0 is using Swift or not, but RAC 2.0 is in Objective-C and it's square bracket chain can confuse readers

Why not use block to support DSL syntax, like [KZPropertyMapper](https://github.com/krzysztofzablocki/KZPropertyMapper), [FTGValidator](https://github.com/onmyway133/FTGValidator), [Masonry](https://github.com/Masonry/Masonry), ...

This allows us to use dot syntax easily

```
[view1 mas_makeConstraints:^(MASConstraintMaker *make) {
    make.top.equalTo(superview.mas_top).with.offset(padding.top); //with is an optional semantic filler
    make.left.equalTo(superview.mas_left).with.offset(padding.left);
    make.bottom.equalTo(superview.mas_bottom).with.offset(-padding.bottom);
    make.right.equalTo(superview.mas_right).with.offset(-padding.right);
}];
```

**Comment by fatuhoku** [comment]
Actually introducing a DSL syntax is likely to be more complex (harder to maintain RAC), less composable, less well type-checked and you don't get the relevant IDE suggestions for free.

If you find RAC unreadable dot syntax and round brackets isn't really your solution.

**Comment by jspahrsummers** [comment]
[RAC 3.0 uses Swift](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-alpha.3).

**Comment by onmyway133** [comment]
@fatuhoku Anyway, I just try to use Dot syntax to see how it helps https://github.com/onmyway133/DotReactiveCocoa, but actually it is just weird, I list a lot of problems that I face. Actually, I still prefer dot syntax in PromiseKit
