### ISSUE TITLE
Pure Swift Library

### ISSUE THREAD

**Issue by iCodesign** [ReactiveCocoa/ReactiveCocoa#1875]
Do you have thought about setting up a pure swift library since we don't usually use the objective-C API of RAC in a Swift Project ?

**Comment by joshaber** [comment]
I'm not sure there's any advantage to doing that. Was there a particular reason you'd like that?

**Comment by iCodesign** [comment]
Well, maybe the objective-C code seems redundant which affects the elegance of code. Is RAC going on with both objective-C and Swift API ?

**Comment by joshaber** [comment]
AFAIK, the only concessions made to the existing Objective-C framework is a thin bridging layer. It doesn't really effect the Swift API at all.

>Is RAC going on with both objective-C and Swift API ?

They'll both co-exist for a while I expect. There are many users of the Objective-C API, GitHub itself included. We can't simply remove it.

**Comment by iCodesign** [comment]
Thanks for the reply.
