### ISSUE TITLE
NSNumber only called for @1 not float values

### ISSUE THREAD

**Issue by UXDart** [ReactiveCocoa/ReactiveCocoa#1879]
Hello
I have this code:
[[RACObserve(self.media, downloadProgress) skip:1] subscribeNext:^(id x) {....

downloadProgress is of type NSNumber * strong property.

I can see in the logs that the value of downloadProgress changes to 0.23 0.34 0.45... until 1
but the signal gets called only for @1 not for the float values.

this didn't happen before, I'm not sure in which version it start happening (I'm using cocoapods)

any idea?

TIA

**Comment by UXDart** [comment]
I'm using 2.4.7

**Comment by mdiep** [comment]
Are you sure the property is fully KVO-compatible?

**Comment by UXDart** [comment]
yes, it was working before... I'm not sure what changed, I know I updated cocoapods the other day. thx
