### ISSUE TITLE
How to implement "replay only on the first subscription " semantic?

### ISSUE THREAD

**Issue by Tiger6688** [ReactiveCocoa/ReactiveCocoa#1880]
How to implement "replay only on the first subscription"?
```objectiveC
    RACReplaySubject* rsub=[RACReplaySubject replaySubjectWithCapacity:2];
    [rsub sendNext:@1];
    [rsub sendNext:@2];
    [rsub subscribeNext:^(id x){
        NSLog(@"sub1:%@",x);
    }];
    
    [rsub subscribeNext:^(id x){
        NSLog(@"sub2:%@",x);
    }];
    
    [rsub sendNext:@4];
//    now the output is:
//    sub1:1
//    sub1:2
//    sub2:1
//    sub2:2
//    sub1:4
//    sub2:4

//and I expect the output is:
//    sub1:1
//    sub1:2
//    sub1:4
//    sub2:4
```

**Comment by jspahrsummers** [comment]
Why do you want this? What are you trying to do?

**Comment by Tiger6688** [comment]
![bdc1111b](https://cloud.githubusercontent.com/assets/8372025/7041393/7e5435dc-de0b-11e4-9afb-bd1477e2370c.jpg)

**Comment by iCodesign** [comment]
Maybe you can filter signals containing `SN` after login.

**Comment by Tiger6688** [comment]
but there is no SN info in the external message.

**Comment by Tiger6688** [comment]
but there is no SN info in the external message.

**Comment by Tiger6688** [comment]
but there is no SN info in the external message.

**Comment by Tiger6688** [comment]
@jlawton @jspahrsummers

**Comment by jspahrsummers** [comment]
Why don't you just use a cold (not replayed) signal for the network request?

**Comment by jlawton** [comment]
I agree that you should try to use a cold signal at the beginning if at all possible.

If you really have to do this, I think you'll have to subscribe early enough and do some buffering and a `createSignal:` manually, but it seems like something is wrong with the design if you can't get a cold signal.

**Comment by Tiger6688** [comment]
thanks everyone!
