### ISSUE TITLE
Why is mapping required when using <~ to bind Signal to DynamicProperties

### ISSUE THREAD

**Issue by ohwutup** [ReactiveCocoa/ReactiveCocoa#1884]
I am attempting to bind a `Signal<String,NoError>` to a `DynamicProperty` of a UILabel's text.

It works great, but _only_ when a call to `map` is inline.

Given the following `Signal<String,NoError>`,
```
lazy var proximityLabelText: Signal<String,NoError> = {
        return self.proximityManager.beacons |> map { beacons in
            switch beacons[0].proximity {
            case .Immediate:
                return "immediate"
            case .Near:
                return "near"
            case .Far:
                return "far"
            case .Unknown:
                return "unknown"
            }
        }
    }()
```

This works:
```
DynamicProperty(object: self.locationLabel, keyPath: "text") <~ self.viewModel.proximityLabelText |> map { $0 }
```
But this throws a compiler error that `Bindary operator '<~' cannot be applied to operands of type 'DynamicProperty' and 'Signal<String,NoError>`:
```
let producer = self.viewModel.proximityLabelText |> map { $0 }
DynamicProperty(object: self.locationLabel, keyPath: "text") <~ producer
```

Is something wrong here or am I missing something?

**Comment by jspahrsummers** [comment]
`DynamicProperty` only allows binding values that conform to `AnyObject`. You'll have to use `NSString` or otherwise map to an `AnyObject` value.

**Comment by ohwutup** [comment]
Thank makes sense, but when I do this:
```
let producer = self.viewModel.proximityLabelText |> map { $0 as NSString }
DynamicProperty(object: self.locationLabel, keyPath: "text") <~ producer
```
it just gives me the same error as before with `NSString` in place of `String`.

**Comment by jspahrsummers** [comment]
Sorry, looks like the type specifically needs to be `AnyObject`. Can you try typing `producer` as `SignalProducer<AnyObject, NoError>`?

**Comment by ohwutup** [comment]
Same error, just now with `AnyObject`

**Comment by jspahrsummers** [comment]
Sorry again, it should be `AnyObject?` (i.e., `Optional<AnyObject>`).

**Comment by ohwutup** [comment]
that works! thanks @jspahrsummers!

**Comment by ohwutup** [comment]
and just for clarity here, the reason why it is needing a `Signal<AnyObject?, NoError>` is because of this? https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/ReactiveCocoa/Swift/Property.swift#L120-L128

**Comment by jspahrsummers** [comment]
@ohwutup Correct. KVC and KVO don't really have any type safety, so the binding reflects that.
