### ISSUE TITLE
Update Result type

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#1887]
Should we migrate our `Result` type before 3.0 given that [LlamaKit](https://github.com/LlamaKit/LlamaKit/blob/master/README.md) probably isn't going to be maintained anymore.

**Comment by jspahrsummers** [comment]
Yeah, I suppose we should use [antitypical/Result](https://github.com/antitypical/Result) here.

/cc @robrix

**Comment by robrix** [comment]
:+1:

**Comment by ikesyo** [comment]
[antitypical/Result](https://github.com/antitypical/Result)'s `Box` is internal, but RAC is using the `Box` type in `Event.swift`. What should we do for it?

**Comment by robrix** [comment]
Just add an internal `Box` type.

**Comment by iCodesign** [comment]
:+1: `Box` is just an internal type to compromise with Swift limitations.
