### ISSUE TITLE
Unrecognized selector for category methods in tests target

### ISSUE THREAD

**Issue by CosynPa** [ReactiveCocoa/ReactiveCocoa#1899]
I'm adding categories for some ReactiveCocoa classes, and I got strange unrecognized selector error in the tests target.

I'm using CocoaPods to link ReactiveCocoa. Podfile:

```
pod 'ReactiveCocoa'
link_with 'myapp', 'myappTests'
```

I see -ObjC is already added as an other linker flag to the main target and tests target by CocoaPods.

The strangest thing is only some instances got this unrecognized selector error. Code:

```
@interface RACSignal (Hello)

- (void)helloSignal;

@end

@interface RACSubject (Hello)

- (void)helloSubject;

@end

@interface RACUnit(Hello)

- (void)helloUnit;

@end
```
 
```
@implementation RACSignal (Hello)

- (void)helloSignal {
    
}

@end

@implementation RACSubject (Hello)

- (void)helloSubject {
    
}

@end

@implementation RACUnit (Hello)

- (void)helloUnit {
    
}

@end
```

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[RACSubject subject] helloSubject];
    [[RACUnit defaultUnit] helloUnit];
    [[RACSignal return:@0] helloSignal];
    [RACObserve(self, window) helloSignal]; // error here
    
    return YES;
}
```

Only the last line gets a "-[RACDynamicSignal helloSignal]: unrecognized selector sent to instance 0x7c0d5f20" error, other category methods work as expected. The code runs in the main target correctly, so it can't be spelling mistake or something like that. The error only occur in the tests target.

Any idea?

**Comment by jspahrsummers** [comment]
Sorry, we don't maintain or support CocoaPods as an installation method, since we don't really use it ourselves. The podspecs that exist are generously provided by third parties.

I'd recommend getting in touch with one of the contributors to that file, who may be able to help further. :disappointed_relieved:
