### ISSUE TITLE
Infix bidning operator `<~` not accessible

### ISSUE THREAD

**Issue by gavrix** [ReactiveCocoa/ReactiveCocoa#1906]
I have XCode6.3  and ReactiveCocoa 3.0-alpa.3 integrated through cocoapods. Turns out custom infix operators defined in a module not visible in main project. (http://stackoverflow.com/questions/27049129/swift-how-to-create-custom-operators-to-use-in-other-modules) 
The only way to workaround this is to redefine infix oeprator somewhere in main project level.

Although this issue is swift specific, there's still some workaround required in RAC to support `<~` semantics accessible from projects using it.

**Comment by nomothetis** [comment]
We are having no problems using the `<~` operator when integrating via Carthage. Maybe this is a Cocoapods issue?

**Comment by jspahrsummers** [comment]
Yeah, the [operator definitions](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/fa50eb340107bea8ac7fde189d9e47594c07924d/ReactiveCocoa/Swift/Property.swift#L162-L219) are public. This seems like a CocoaPods issue.
