### ISSUE TITLE
Issue compiling code with `on`

### ISSUE THREAD

**Issue by nomothetis** [ReactiveCocoa/ReactiveCocoa#1907]
We are trying to inject side effects in some code we're working on, and trying to use the `on` function crashes the compiler with a segfault (code 11). We can reproduce this error with the following snippet:

```swift
public func injectSideEffectsOnNext(processNext:Int -> ()) -> SignalProducer<Int, NoError> {
    return SignalProducer<Int, NoError>(values:[1, 2, 3]) |> on(next: processNext)
}
```
Moreover, it segfaults just as badly if we get rid of the operator:

```swift
public func injectSideEffectsOnNext(processNext:Int -> ()) -> SignalProducer<Int, NoError> {
    return on(next: processNext)(producer:SignalProducer<Int, NoError>(values:[1, 2, 3]))
}
```

Are we doing something wrong, like using `on` in a way that shouldn't be used? Obviously the fact that the compiler is crashing is not our fault, but is there a way to work around this?

**Comment by JaviSoto** [comment]
What version of RAC are you running? is this on Beta 1? I stopped having this crash a while ago.

**Comment by nomothetis** [comment]
Ah, good point. We're on Beta 2. Let me upgrade and see what happens. Thanks!

**Comment by nomothetis** [comment]
Just tested; it works fine on beta 1. Need to keep up with the new goodies. :-)

**Comment by JaviSoto** [comment]
Just to make sure, in your comment earlier you probably meant alpha 2, and it's fixed in beta 2, is that correct?

**Comment by nomothetis** [comment]
Bleh. I suck at this. We were using RAC 3.0-alpha.2. I just upgraded to RAC 3.0-beta.1, and it compiles properly.

**Comment by JaviSoto** [comment]
That makes more sense :) thanks for clarifying, and I'm glad it's resolved!

**Comment by nomothetis** [comment]
:+1:
