### ISSUE TITLE
RACDC 2015

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#1909]
Just like [last year](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1350) and the year before, we want to do some kind of RAC community event during WWDC week (June 8–12).

We don't know what, though, or when. Did you particularly like either of the previous formats, or any aspects of them? Do you have any ideas for something new we should try?

I'd love to hear your thoughts! :pray:

/cc @ReactiveCocoa/reactivecocoa

**Comment by robb** [comment]
I liked yesteryear's RACDC, I thought it was short and sweet.

I'd love to see another State of the Union and maybe some more talks and a Q&A?

**Comment by andymatuschak** [comment]
I’ll be on my honeymoon, but enjoy! :)

**Comment by marlowcharite** [comment]
@andymatuschak congrats. Was last year's events and talks recorded? I'd like to watch those videos. I've given myself the self imposed challenge of completing my next project fully with ReactiveCooca and MVVM. Figured no better way than jumping right in

**Comment by neilpa** [comment]
@marlowcharite https://www.youtube.com/watch?v=kuZ5eR2JcSo&list=PL0lo9MOBetEEXnrrP5pwZxSkGvaDBGdOC

**Comment by kastiglione** [comment]
I'd be in for whatever! Let me know how I can help.

**Comment by marlowcharite** [comment]
@neilpa thank you sir

**Comment by RuiAAPeres** [comment]
I enjoyed last year format as well. Some good stuff being shared.

**Comment by JaviSoto** [comment]
I loved the format from last year as well :)
Just wanted to add that although I imagine you will be able host it at Github this time around as well, I would be happy to coordinate this with my employer if you wanted a bigger space or something :)

**Comment by jspahrsummers** [comment]
@JaviSoto It would be great if you could ask! It'd be cool to change it up. :sparkles:

**Comment by JaviSoto** [comment]
I'll ask tomorrow :)

**Comment by numist** [comment]
I'm in.

In the same spirit as expanded Q&A, it might be handy to host walk-in lab space for people trying to learn RAC by enacting it in their projects. While APIs can be documented and talks recorded, lab mentoring remains a very high impact use of in-person time.

**Comment by kastiglione** [comment]
Love that idea!

**Comment by brow** [comment]
@numist I love that idea, too. If someone is willing to organize that, I'd volunteer for sure.

**Comment by jspahrsummers** [comment]
@numist Great suggestion!

I think a general schedule of:

 1. RAC “State of the Union” (h/t @robb)
 1. _Maybe_ 1–3 other talks
 1. Lots of Q&A time
 1. Lots of lab time

… would be great.

The biggest question now is: when's the best time to do this? I know a bunch of people missed [most of] it last year because of conflicts with WWDC proper. Should we do it outside of WWDC hours? Or is there a particular day that people would be more inclined to skip?

**Comment by kastiglione** [comment]
Probably worth tweeting that question about time of day. It's going to be hard to plan for a skipping-friendly time without a WWDC schedule. Maybe outside WWDC hours is a good place to start.

**Comment by jspahrsummers** [comment]
plz to retweet https://twitter.com/jspahrsummers/status/595392935044120576

**Comment by mattdelves** [comment]
:+1:

**Comment by jspahrsummers** [comment]
I didn't get a ton of replies, but it sounds like there's a general preference for some evening during the week. If we do decide on an evening time, we should probably keep the scheduled time to 2–3 hours (maybe not have any talks but “state of the union”).

I think we should aim for Wednesday evening, or Thursday during the day. How's that sound? Any preference between those two?

**Comment by AvdLee** [comment]
I would like to attend as well. Evening sounds good, what about a pizza session? That's something we do often in the Netherlands. Wednesday evening would be my best option.

**Comment by dpassage** [comment]
There was just an announcement of a Swift panel discussion via Meetup (http://www.meetup.com/swift-language/events/222426718/) scheduled for Wednesday evening with @ashfurrow and others. Scheduling something during WWDC week is Hard, but just an FYI - I'd like to be able to do both. :)

**Comment by robb** [comment]
>  Thursday during the day.

I'd prefer that, but that's just like, my opinion, man.

**Comment by jspahrsummers** [comment]
There are so many other awesome events happening during this week that I think it'll be really hard to find a good day/time that works for everyone, so I'd like to propose a change of plans.

What if we selected _two_ times, and used both times for Q&A plus “lab time?” We wouldn't give talks, but just give people a forum to talk to RAC contributors (which seems like it'd have a higher impact, as @numist pointed out).

Ideally, we could have a couple of venues (or one, at two times) “donated” to us, or sponsored for us, and the Q&A bits recorded.

What about Wednesday evening and Thursday during the daytime?

**Comment by sprynmr** [comment]
Last year's was so good that I'd pretty much make time regardless of when. I would personally like some sort of SOTU and talks as well, but Q&A is good too.

**Comment by robb** [comment]
Yeah, I'm sure it'll be a good time either way yet I wouldn't underestimate the impact of a State of the Union for the broader community who can't be present or don't have immediate lab needs.

**Comment by kastiglione** [comment]
State of the union would be cool, but I just would want to some sort of recorded video that could be watched would be awesome. For those that are interested but can't make it, it would be unfortunate if nothing from the event(s) is available. If talks don't happen, I would be volunteer to help publish content from the events, such as: transcribe Q&A, gather some stories about from labs and blog about them, collaborate on open source projects during lab, etc. 

![](http://www.reactiongifs.com/r/bbym.gif)

**Comment by jspahrsummers** [comment]
Makes sense. Why don't we do:

**Wednesday evening:**

 - Q&A (up to 1 hour)
 - Lab time (unbounded, or depends on the venue)

**Thursday daytime:**

 - SOTU, if it can be recorded
 - 1–2 other talks, if anyone wants to volunteer to give one
 - Q&A (up to 1 hour)
 - Lab time (unbounded)

**Comment by alexbaldwin** [comment]
Sending some emails off in search of venues for 6/10 evening and 6/11 day time that can hold 100+ people. Will post results back here.

**Comment by JaviSoto** [comment]
I'm in touch with the events people at Twitter internally. We don't have anything available for that week for 100+ people, only for up to 75 :*

**Comment by kastiglione** [comment]
@jspahrsummers Do you know how many came to the day slot last year?

Given that there will be one day event and one evening, it's possible that 75 capacity might be enough for the day event.

I would be more than happy to try to see what's I could do at Facebook, but I presume people don't want to necessarily travel that distance.

**Comment by rodericj** [comment]
Throwing http://runway.is (same building as twitter) in the ring. I'm here and could ask if anyone thinks it could be reasonable.

**Comment by jspahrsummers** [comment]
> Do you know how many came to the day slot last year?

@kastiglione No, sorry, but I'm pretty sure we got more than 200 RSVPs. Obviously, many fewer people than that attended, but an attendance cap lower than 100 might result in turning people away unnecessarily/prematurely.

> Given that there will be one day event and one evening, it's possible that 75 capacity might be enough for the day event.

Certainly true, but I'd like to try all of our options for 100+ first.

> I would be more than happy to try to see what's I could do at Facebook, but I presume people don't want to necessarily travel that distance.

Yeahhhh. :confused: Thanks, though!

> Throwing http://runway.is (same building as twitter) in the ring.

@rodericj If they can hold 100+ people, it'd be awesome if you could ask! :sparkles:

**Comment by jspahrsummers** [comment]
I've gone ahead and set up event pages for [Wednesday evening](http://racdc-labs.eventbrite.com) and [Thursday daytime](http://racdc.eventbrite.com).

[if(we)](http://www.ifwe.co) has confirmed that they can host us on Wednesday evening! :tada: Once we figure out the venue for Thursday, I'll update that page too.

If you could tweet about these, or retweet https://twitter.com/jspahrsummers/status/600526398910910464, I'd be much obliged. :smile:

**Comment by jspahrsummers** [comment]
Just a reminder (to myself, if no one else) that the venue for Thursday should have a way to record talks.

**Comment by kastiglione** [comment]
Thanks if(we) folks!

**Comment by jspahrsummers** [comment]
**Thursday agenda:**

1. RAC “State of the Union” by @jspahrsummers
1. TBD
1. TBD
1. TBD
1. Q&A panel with any RAC collaborators who are present and interested in participating
1. Lab time

@JaviSoto @NachoSoto @kastiglione I think all of you expressed interest in giving talks. Any preference about the slot? Do you have a title?

**Comment by MichaelMcGuire** [comment]
![excited](https://cloud.githubusercontent.com/assets/429790/7973953/d04c3336-0a10-11e5-9832-62e09161159a.gif)

**Comment by JaviSoto** [comment]
My TBD/WIP title is "RAC 3, A Real World Use Case", but maybe ReactiveChess would be more fun :D 
I *think* I don't have a preference on the slot, I think I'd like to be at WWDC in the morning cause I'm sure the best talks will be then, what time is each of the slots?

**Comment by NachoSoto** [comment]
I don't have a preference for any of the slots, I'll probably be there all day :)

I think I'll title mine "Functional programming in an imperative world".

**Comment by jspahrsummers** [comment]
> what time is each of the slots?

Not really sure. We start at 11 AM, and when each talk starts totally depends on the length.

@JaviSoto We can do your talk after lunch, if you'd like.

**Comment by NachoSoto** [comment]
And by functional I really meant functional reactive, of course.

**Comment by JaviSoto** [comment]
> @JaviSoto We can do your talk after lunch, if you'd like.

That sounds perfect!

**Comment by kastiglione** [comment]
I have not written anything. I could still try to do a light and short talk contributing.

**Comment by jspahrsummers** [comment]
@kastiglione No pressure. I think we have enough content for the time we're looking to fill.

**Comment by jspahrsummers** [comment]
I've updated the [informal agenda](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1909#issuecomment-108649114) with information for Wednesday too.

Although talks weren't planned, I think I'll give my SotU talk (possibly abbreviated) that night too, since it contains some introductory info that will probably be a good lead-in to the Q&A and labs.

**Comment by iandundas** [comment]
Apologies if answered elsewhere (can't seem to find it) - do you know when/where the State Of The Union talk (and hopefully the others) will be online? Cheers

**Comment by dennisfarandy** [comment]
please make the videos online.. :D

**Comment by ychang-brightcove** [comment]
Looking from videos :+1:

**Comment by mbesnili** [comment]
+1

**Comment by jspahrsummers** [comment]
The videos will be posted when they are available. Don't forget that the video work is being done for free. Please be patient.

**Comment by iandundas** [comment]
For sure - sorry to nag, we were just champing at the bit 🌼

**Comment by MichaelMcGuire** [comment]
So bummed. I had to leave WWDC early on Thursday morning due to a family emergency and missed RACDC 2015 :cry: 

At least I got to accidentally meet @JaviSoto at "The Talk Show" recording when I realized I was sitting right behind him thanks to a picture he tweeted. :smile:

**Comment by seraphcxl** [comment]
Looking for videos +1

**Comment by brow** [comment]
If you've landed here in search of videos, take heed of @jspahrsummers' comment!

> The videos will be posted when they are available. Don't forget that the video work is being done for free. Please be patient.

I'm :lock:ing this now so that participants aren't subjected to an endless drip of +1s.
