### ISSUE TITLE
[Very basic question] How to set up my Xcode project to contributing code?

### ISSUE THREAD

**Issue by barty82** [ReactiveCocoa/ReactiveCocoa#1913]
Hi, ppl.

I'm a huge fan of ReactiveCocoa. So from my latest project, I applied MVVM style with ReactiveCocoa framework. And I really want to be part of this project too.

But thing is I don't know how to set up my Xcode project without using Cocoapod. I don't want to just using it, but I want to do some fixing, and rebuilding the source code every time I run my project. 

I've been trying to research on how to set up the Xcode project. There are some tutorial blogs described  something like how to make a sub-project, or something like how to add header file path and so on. But none of those are working for me. 

Can you teach me the best practice on setting up the personal Xcode project? PLEASE!

I'm looking forward to hearing from you. 
Thank you.

**Comment by jspahrsummers** [comment]
I would recommend [Carthage](https://github.com/Carthage/Carthage), but I'm biased. :stuck_out_tongue_closed_eyes: 

If you don't want to use Carthage, I would recommend adding ReactiveCocoa as a Git submodule, then dragging and dropping `ReactiveCocoa.xcodeproj` into your project or workspace, as described [in the README](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/13b39aba8b07c912235e3f8930e569a3d16caace/README.md#importing-reactivecocoa).

**Comment by barty82** [comment]
Thank you Justine. You are really awesome!
