### ISSUE TITLE
ReadMe to link to ChangeLog

### ISSUE THREAD

**Issue by ninokierulf** [ReactiveCocoa/ReactiveCocoa#1920]
I understand that ReadMe will be updated for the v3 at some point.
But for the moment, for people interested using the rac v3
specially via swift - atleast link to changelog, and a disclaimer that readme is outdated and is still referring to v2.x.

**Comment by jspahrsummers** [comment]
The [releases](https://github.com/ReactiveCocoa/ReactiveCocoa/releases) do link to the changelog, and nothing about the README is “outdated”—it just doesn't mention the Swift API.

I think this is acceptable until we [update the README for real](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1483).
