### ISSUE TITLE
Creating Hot Signal

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#1923]
I can create a cold signal with something along the lines:

```
    return [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        
        [subscriber sendNext:@"Foo"];
        [subscriber complete];
        return nil;
    }];
```
But how about a hot signal, something that independently of the number of subscribers won't start (another characteristic would be lack of `sendComplete` or `sendError`?)? I am aware of `RACMulticastConnection`, but for example `rac_textSignal` from my understanding is a hot signal, but it doesn't seem to make use of  `RACMulticastConnection`.

**Comment by jspahrsummers** [comment]
`RACSubject` is intrinsically a hot signal.

**Comment by RuiAAPeres** [comment]
@jspahrsummers looking at `rac_textSignal` for example, I can see it's a hot signal, by the way I use it and how it behaves, but not from an implementation POV, maybe you could shed some light.

**Comment by Tiger6688** [comment]
hot signal must subscribe before it emit the value. otherwise,you can't get the value. but you can always got the value the cold signal emit.

**Comment by jspahrsummers** [comment]
@RuiAAPeres `-[UITextField rac_textSignal]` is “warm,” because it sends the current value upon subscription as a side effect. If it didn't do that, it would be a hot signal.

You can see that it is because of its dependency upon `-rac_signalForControlEvents:`, which is intrinsically hot as well.

**Comment by neilpa** [comment]
Closing, but please re-open if that doesn't answer your question.
