### ISSUE TITLE
Does takeUntil work as expected? Or I use it incorrecty

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#1931]
Hello,

I have api for loading image
```
-(RACSignal*)imageSignal
{
   return [[[self loadImageSignal] initially:^{
      //
   }] finally:^{
     //cleanup
   }];
}
```
And in cell I have code
```
   [[[api imageSignal] takeUntil: self.rac_prepareForReuseSignal]
    subscribeNext:^(UIImage* image) {
       //
    }];
```
finally is not called in case if cell was prepared for reuse

Is it expected behavior? Or takeUntil preferable to use just with KVO? I agree that it should not call subscribeNext. But why it does not call finally.

**Comment by joshaber** [comment]
It might be clearer if we think about the signal chain involved:

```
loadImageSignal
   |
   |
initially:
   |
   |
finally:
   |
   |
takeUntil:
   |
   |
subscribeNext:
```

`-takeUntil`'s completion flows _down_ the signal chain, not up. The subscriptions to the signals above it are _disposed of_, but they don't complete.

If you need to know about disposal, I recommend you look at `+[RACSignal createSignal:]`.

**Comment by Igor-Palaguta** [comment]
Thanks,

So currently I can say that using takeUntil is dangerous with not KVO signals, as we can break somebody's logic. Will use simple check in subscribeNext instead of takeUntil for such cases.

**Comment by kaybutter** [comment]
Wouldn't setting up the `finally:` after the `takeUntil:` do the trick?

**Comment by Igor-Palaguta** [comment]
Yes finally after is called. But client code does not know what final cleanup api should prepare.

**Comment by joshaber** [comment]
>So currently I can say that using takeUntil is dangerous with not KVO signals, as we can break somebody's logic.

Not really, signals just need to be written in accordance with how RAC is designed :wink:

**Comment by Igor-Palaguta** [comment]
So, in case if I want to clean up something I can wrap loadImageSignal this way:
```
   return [RACSignal createSignal: ^(id<RACSubscriber> subscriber)
           {
              RACCompoundDisposable* disposable = [RACCompoundDisposable compoundDisposable];
              [disposable addDisposable: [self. loadImageSignal subscribe: subscriber]];
              [disposable addDisposable: [RACDisposable disposableWithBlock:
                                            ^{
                                                  //Cleanup
                                            } ] ];
              return disposable;
           }];

```
Am I right?

**Comment by jspahrsummers** [comment]
@Igor-Palaguta Correct, but ideally your `loadImageSignal` would implement those disposal behaviors itself, since it should understand how to clean up after itself.
