### ISSUE TITLE
How can I map() errors?

### ISSUE THREAD

**Issue by Inferis** [ReactiveCocoa/ReactiveCocoa#1938]
I would like to transform errors I get from a signal: for example, the errors received from a web service should be converted to a reduced set of application specific error (optionally containing the original error).

I didn't find an immediate way to do this; I also looked into how `map()` was implemented but it was more complex than I had hoped so I'm asking here first before trying to replicate `RACSignal.bind()` for my own `mapError()`.

Thanks!

**Comment by mdiep** [comment]
You can use `catch` to transform errors. If you want to return a non-error value, you can `return [RACSignal return:value]` from the block. If you want to pass the error through unchanged, you can `return [RACSignal error:error]`.

**Comment by Inferis** [comment]
Thanks, that was *exactly* what I needed.
