### ISSUE TITLE
[UIRefreshControl+RACCommandSupport] RefreshControl does not guarantee to call -endRefresh on main thread 

### ISSUE THREAD

**Issue by liyihe96** [ReactiveCocoa/ReactiveCocoa#1940]
I noticed that if I assign a RACComand, whose `signalBlock` is working on the background thread to the `rac_command` of a `UIRefreshControl`, the refresh control won't call `-endRefreshing` on main thread, so it won't end the animation immediately after the signal sends completed.

**Comment by liyihe96** [comment]
So I added `-deliverOnMainThread` and it works fine now

    	RACDisposable *executionDisposable = [[[[[self
		rac_signalForControlEvents:UIControlEventValueChanged]
		map:^(UIRefreshControl *x) {
			return [[[command
				execute:x]
				catchTo:[RACSignal empty]]
				then:^{
					return [RACSignal return:x];
				}];
		}]
		concat] deliverOnMainThread]
		subscribeNext:^(UIRefreshControl *x) {
			[x endRefreshing];
		}];

**Comment by hhanesand** [comment]
Try submitting a pull request if you want this in the repo :+1:
