### ISSUE TITLE
[Question] Observe signal from UITableViewCell

### ISSUE THREAD

**Issue by iCodesign** [ReactiveCocoa/ReactiveCocoa#1943]
Suppose we have a custom `UITableViewCell` containing a signal which may be triggered by specific action. So what should I do to catch and observe the signal outside the cell?

Example code:
```swift
var cell = tableView.dequeueReusableCellWithIdentifier(identifier) as? UITableViewCell
if cell == nil {
     cell = SomeCell(style: .Default, reuseIdentifier: identifier)
}
// observing signal here may receive multiple events
cell.someSignal |> observe(...)
```

**Comment by BleuShan** [comment]
Just pass a closure to the next parameter of the observe method like:

cell.someSignal |> observe(next: { signalValue in someOperation(signalValue) })

**Comment by iCodesign** [comment]
Problem is that the next closure may receive multiple events after tableview's been reloaded

**Comment by BleuShan** [comment]
Well, even if it's might be suboptimal, you could use takeUntil to complete the signal on tableview reload signal tableView or cell prepare for reuse signal and just re-create the signal(s) after the reload.

**Comment by jspahrsummers** [comment]
We typically solve this by implementing observations like this _in_ the cell itself, and in such a way that they remain valid even when the cell is reused (for example, by allowing and handling `nil` values in a sane way).

Then you don't need `takeUntil` or explicit disposal.

**Comment by iCodesign** [comment]
> in such a way that they remain valid even when the cell is reused (for example, by allowing and handling nil values in a sane way).

That seems not elegant.

And how is `takeUntil ` used in Swift?

**Comment by jspahrsummers** [comment]
The same way it's used in Objective-C.

**Comment by neilpa** [comment]
Closing, but please re-open if that doesn't answer your question.

**Comment by ruandao** [comment]
how to transform from `RACSignal`(the Objective-C version) to `Signal` (the Swift version)

e.g. how to cover `cell.rac_prepareForReuseSignal` to a Singal

    levelSignal
    |> takeUntil( doSomeThingTo(cell.rac_prepareForReuseSignal) )
    |> observe(next: { level in
        ...
        })

thank you!
