### ISSUE TITLE
Example project for RAC 3?

### ISSUE THREAD

**Issue by seanchoe** [ReactiveCocoa/ReactiveCocoa#1944]
Is there any example Swift project written with RAC 3 that I can refer to? I'd like to see example practices for Signal, SignalProducer and Action.

**Comment by MichaelMcGuire** [comment]
I found @adly-holler's [SwiftRACGoogleImages](https://github.com/adly-holler/SwiftRACGoogleImages) to be a great start.

**Comment by seanchoe** [comment]
Great. Thanks much!
