### ISSUE TITLE
[RAC 3.0] tryMap generic E type

### ISSUE THREAD

**Issue by aschuch** [ReactiveCocoa/ReactiveCocoa#1945]
I am trying to get used to the new RAC 3.0 API and create a function that can be used with the `|>` operator, but can not find anything in the docs to help me tackle this specific problem.

```swift
public func foo<T, E>(type: T.Type)(signal: Signal<AnyObject, E>) -> Signal<T, E> {
    return signal |> tryMap { object in
        // Try to create an instance of T
        if let t: T? = ... {
           return success(t)
        }

        // ... otherwise error
        return failure(message: "some error") // This throws a compiler error because NSError != E
    }
}

// usage
someSignalProducer
     |> foo(Bar.self) 
     |> start(next: { println($0) })
``` 

I have already got this working, when substituting occurrences of `E` with a concrete implementation (e.g. `NSError`).

```swift
public func foo<T, E>(type: T.Type)(signal: Signal<AnyObject, NSError>) -> Signal<T, NSError>
```

Is there a way to support a generic error type or do I actually need to add a concrete implementation? Am I missing something?

**Comment by NachoSoto** [comment]
There is no way to instantiate a generic type, as the compiler wouldn't know which initializers are available.

Your approach to creating a custom operator is good though :) what you'll need is for it to take a closure that can create instances of `T`.

I'm not sure I completely understand what `foo` is supposed to do though. Seems like you're trying to convert those `AnyObject`s to `T`s? Maybe what you want is
```swift
if let t = object as? T {
  return success(t)
}
```

But I'm probably misinterpreting your code :)

**Comment by aschuch** [comment]
Hm, I am trying to create an instance of `T` based on the `AnyObject` (array or dictionary) passed from the incoming signal, so I'm afraid a simple `as? T` won't do it (too bad :space_invader:).

I want to keep the incoming signal as generic as possible (not forcing a specific type of `E` to the API user). 
I am not sure how to propagate a potential failure in this case...
RAC 2.0's `tryMap` had an `NSError` passed to its block to handle any failure within the block ([like this](https://github.com/aschuch/Argonaut/blob/master/Argonaut/JSONMapping%2BReactiveCocoa.swift#L25)).

**Comment by NachoSoto** [comment]
> Hm, I am trying to create an instance of T based on the AnyObject (array or dictionary) 

Can you elaborate on that? How would you create an instance of *any* `T` based on `AnyObject` without casting?

**Comment by aschuch** [comment]
Oh, sorry if I wasn't clear enought here :sparkler:. 
I am using [Argo](http://github.com/thoughtbot/argo) to create an optional instance of T, based on the contents of the AnyObject (aka JSON).

**Comment by aschuch** [comment]
To give you a more concrete example, I have pushed my [existing solution](https://github.com/aschuch/Argonaut/blob/master/Argonaut/JSONMapping%2BReactiveCocoa.swift#L84).

**Comment by JaviSoto** [comment]
Oh, I think I implemented a very similar thing recently, let me know if this is what you're after

```swift
private func extractJSONObject<T: JSONDecodable where T.DecodedType == T>(json: JSONValue) -> Result<T, MyErrorType> {
    if let object = T.decode(json) {
        return success(object)
    }
    else {
        return failure(MyErrorType.InvalidJSONStructure(reason: "Couldn't decode object of type \(T.DecodedType.self)"))
    }
}

private func extractJSONObjects<T: JSONDecodable where T.DecodedType == T>(json: JSONValue) -> Result<[T], MyErrorType> {
    if let objects = JSONValue.mapDecode(json) as [T]? {
        return success(objects)
    }
    else {
        return failure(MyErrorType.InvalidJSONStructure(reason: "Couldn't decode objects of type \(T.DecodedType.self)"))
    }
}
```

And then I used it with a signal with `tryMap`:

```swift
public func requestThing() -> SignalProducer<MyModel, MyErrorType> {
    return self.requestURL(URL)
               |> tryMap(extractJSONObjects)
}
```

**Comment by aschuch** [comment]
@JaviSoto yes, basically the same idea :+1:. I guess your `requestURL` need to emit `Signal<JSONValue, MyErrorType>` for this to work?
I am trying to make my function more generic in terms of the error type that needs to be passed in, but I am almost certain that this is not supported...

**Comment by JaviSoto** [comment]
> I guess your requestURL needs to emit Signal<JSONValue, MyErrorType> for this to work?

Yes. I simplified the code I pasted a little bit, but that's basically the case. I have a method that gives me a Producer of NSData (using the `NSURLSession` rac_ category methods), then a function that parses the JSON and maps to JSONValue, basically, and I compose all of them with the pipe-forward operator.

>I am trying to make my function more generic in terms of the error type that needs to be passed in, but I am almost certain that this is not supported...

I'm not sure I follow here. You want to make this function be able to give you different types of errors? Because the function won't be able to create those values (can't create a value of an arbitrary type `E`), you may have to provide a `() -> E` function, sort of like this:

```swift
private func extractJSONObject<T: JSONDecodable, E: ErrorType where T.DecodedType == T>(createError: () -> E)(json: JSONValue) -> Result<T, E> {
    if let object = T.decode(json) {
        return success(object)
    }
    else {
        return failure(createError())
    }
}

```

**Comment by aschuch** [comment]
@JaviSoto Thats what I thought, thanks for the clarification. :boom:  

> You want to make this function be able to give you different types of errors? 

I was thinking to use a custom error type like you did, returning `Signal<T, CustomError>`. However, as a consumer of the method, one could e.g. have a `SignalProducer<AnyObject, NSError>` that should be mapped to an object.
This would not be possible, because `tryMap` requires the `E` to be the same for the input signal and the returned `Result`.  Maybe there is another way to work around this that I am not aware of though...

**Comment by jspahrsummers** [comment]
If you want to overload based on _user-defined_ error types, you should create a protocol that you expect them to follow (for example, a requirement that they support something like `failure()` with a message).

Otherwise, the compiler has no way to know what you want out of that type, and you can't do anything meaningful with it.
