### ISSUE TITLE
Binding properties to SignalProducers

### ISSUE THREAD

**Issue by OscarSwanros** [ReactiveCocoa/ReactiveCocoa#1950]
I'm doing some MVVM.

On my ViewModel, I have this:
```
class ViewModel {
    var info = MutableProperty<String>("")
}
```

And on the ViewController, I want the `viewModel`'s `info` property to be updated when a new value is entered on a textfield.

```
class ViewController: UIViewController {
    var vewModel: ViewModel

    // init, other stuff

    func bindViewModel() {
        self.viewModel.info <~ self.textField.rac_textSignalProducer()
    }
}

extension UITextField {
    func rac_textSignalProducer() -> SignalProducer<String, NSError> {
        return
            self.rac_textSignal().toSignalProducer()
                |> map { $0 as! String }
    }   
}
```

But if fails since the `<~` operator expects to receive `SignalProducer<String, NoError>`.

What's the correct way of doing this? I feel like I'm missing something.

**Comment by LightD** [comment]
it's `catch`, you can check out the example at [SwiftRACGoogleImages] (https://github.com/adly-holler/SwiftRACGoogleImages), it was referenced from another issue as an example of RAC 3.0 in practice.. quite handy actually.. that should answer your question I believe

**Comment by OscarSwanros** [comment]
Thanks!

Here's the code:

```
extension UITextField {
    func rac_textSignalProducer() -> SignalProducer<String, NoError> {
        return self.rac_textSignal().toSignalProducer()
            |> map { $0 as! String }
            |> catch { _ in SignalProducer<String, NoError>.empty }
    }
    
}
```
