### ISSUE TITLE
Build via Carthage failing - building Result-Mac with iOS SDK?

### ISSUE THREAD

**Issue by dpassage** [ReactiveCocoa/ReactiveCocoa#1951]
Perhaps against my better judgement, I'm trying to install ReactiveCocoa edge with Carthage, and the build is failing trying to sign the Result framework. Xcode 6.3.1 on OS X 10.10.3.

My Cartfile looks like:

```
github "ReactiveCocoa/ReactiveCocoa" "swift-development"
```

Which resolved to:

```
github "robrix/Box" "1.2.1"
github "antitypical/Result" "0.4"
github "ReactiveCocoa/ReactiveCocoa" "1b74da605a6717505c93bac66056a052da05511a"
```

The non-verbose output looks like this:

```
*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
*** Downloading Box at "1.2.1"
*** Checking out Result at "0.4"
*** Checking out ReactiveCocoa at "1b74da605a6717505c93bac66056a052da05511a"
*** xcodebuild output can be found in /var/folders/_z/vxkm582x22l475ckgwtg79tm0000gn/T/carthage-xcodebuild.sVuWLH.log
*** Building scheme "Result-iOS" in Result.xcworkspace
*** Building scheme "Result-Mac" in Result.xcworkspace
*** Building scheme "ReactiveCocoa iOS" in ReactiveCocoa.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Digging into the end of the log file, here's what I see, after successfully building the Release-iphoneos framework:

```
=== BUILD TARGET Result-Mac OF PROJECT Result WITH CONFIGURATION Release ===

Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'
```

Now, building the Release framework directly via Carthage works fine. Smells like the issue is in ReactiveCocoa or Carthage....

BTW the RAC 3.0-beta1 tag builds fine.

**Comment by siemensikkema** [comment]
I had this problem and was able to fix it in my case. It was an Xcode problem rather then ReactiveCocoa or Carthage. Xcode could not figure out which distribution certificate to use.
I cleared out old, unused, and revoked certificates but that wasn't enough. I then proceeded to **backup** the remaining ones, removed them from the keychain and figured out which ones I needed and could keep by reimporting them in Keychain.
I believe the reason the RAC 3.0-beta1 version was successful is because Carthage uses the prebuilt version hosted here (where code-signing was skipped?).

**Comment by dpassage** [comment]
I'll check into my certificates, but according to the logs, both ReactiveCocoa and LlamaKit are being built on my local system when I use the beta1 tag.

**Comment by dpassage** [comment]
OK, I just removed all my certificates, then let Xcode download new ones for me. Now I'm getting a slightly different build failure at the end of the logs:

```
Build settings from command line:
    SDKROOT = iphoneos8.3

=== BUILD TARGET Box-Mac OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'
```

WTF?

**Comment by siemensikkema** [comment]
Try: `carthage build --platform iOS` to build for iOS only.

**Comment by siemensikkema** [comment]
I've just encountered the same problem. Result and Box are being a bit stubborn. I'm not sure why. I've been able to compile by manually editing the Result and Box projects and deleting the Mac targets.

**Comment by jspahrsummers** [comment]
This sounds like https://github.com/Carthage/Carthage/issues/418, which I believe @robrix has since worked around in [Result](https://github.com/antitypical/Result).

**Comment by robrix** [comment]
Should be a little better at least, thanks to binary releases.

**Comment by felixjendrusch** [comment]
@robrix Could you please add binary releases for `Result` too?

**Comment by robrix** [comment]
cf https://github.com/antitypical/Result/issues/20

**Comment by dpassage** [comment]
As of beta 4, I can now build and install with Carthage. :tada: 

Thanks!

**Comment by patgdut** [comment]
I use this Cartfile config:
github "antitypical/Result" == 0.5
github "ReactiveCocoa/ReactiveCocoa"

It's working on xCode 7 GM

**Comment by arbipher** [comment]
@patgdut 
It works! thanks!

**Comment by freemansion** [comment]
@siemensikkema your solution 'carthage build --platform iOS' helps me, thanks!
