### ISSUE TITLE
Cleaning up a subscription ? 

### ISSUE THREAD

**Issue by ArEnSc** [ReactiveCocoa/ReactiveCocoa#1955]
I was looking at create signal and I was wondering what the RACDisposable is for ? 

"A disposable encapsulates the work necessary to tear down and cleanup a subscription."  

Can anyone give me a simple example of where this would be used? 
I looked at this 

http://www.slideshare.net/jarsen7/learn-you-a-reactive-cocoa-for-great-good
Slide 46 it put [task cancel] message in there.

I often see it returning nil in many examples.
```objc
[RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
      
        return [RACDisposable disposableWithBlock:^{
            [task cancel] // When would this block be used?
        }];
    }];
```

Can anyone give me an example of where this would be used?  thanks.

**Comment by Tiger6688** [comment]
```objective-C
    __block unsigned subscriptions = 0;
    RACSignal *loggingSignal = [RACSignal createSignal:^ RACDisposable * (id<RACSubscriber> subscriber) {
        subscriptions++;
        [subscriber sendCompleted];
        return [RACDisposable disposableWithBlock:^(void) {
            NSLog(@"dispose");
        }];
    }];
    
    RACSignal *loggingSignal1 = [RACSignal createSignal:^ RACDisposable * (id<RACSubscriber> subscriber) {
        subscriptions++;
        [subscriber sendError:nil];
        return [RACDisposable disposableWithBlock:^(void) {
            NSLog(@"dispose");
        }];
    }];
    // Outputs:
    // subscription 1
    // dispose
    [loggingSignal subscribeCompleted:^{
        NSLog(@"subscription %u", subscriptions);
    }];
    // Outputs:
    // subscription 2
    // dispose
    [loggingSignal1 subscribeError:^(NSError *error){
        NSLog(@"subscription %u", subscriptions);
    }];
    
    // Outputs:
    // dispose
    RACDisposable* d=[loggingSignal1 subscribeNext:^(id x){
        NSLog(@"subscription %u", subscriptions);
    }];
    [d dispose];
```

**Comment by hhanesand** [comment]
Just to clarify @Tiger6688 's example, the `RACDisposable` blocks are called after all subscribers have been notified of the signal completion, or if a signal no longer has any subscribers. For example, if a signal is encapsulating a network request, and all of its subscribers are discarded, it no longer makes sense to complete the network request, so ReactiveCocoa calls the `RACDisposable` block to cancel any work the signal may be performing.

**Comment by ArEnSc** [comment]
Is there an example of a signal that is continuously generated and send out to subscribers ? where I could see this being useful is to cancel a ns operation queue type of encapsulated network request ?

**Comment by ArEnSc** [comment]
Thanks guys I understand how this works now!

**Comment by hhanesand** [comment]
:+1:
