### ISSUE TITLE
[RAC3 Question] How to make a SignalProducer that works on the background but delivers on the main thread

### ISSUE THREAD

**Issue by 0xpablo** [ReactiveCocoa/ReactiveCocoa#1956]
Hi everyone, I'm new to RAC, I've been playing with it for a day and it is impressive. Kudos to the devs!

I am trying to create a `SignalProducer` that performs some work on a background queue, but consumers receive the events on the main thread.

```swift
    func login(username: String, password: String) -> SignalProducer<Void, LoginError> {
        let queueScheduler = QueueScheduler(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0))
        return SignalProducer.try({return self.userNetwork.postLogin(username, password: password)})
            |> on(started: nil, event: nil, next: {n in println("insideNext")})
            |> map(toVoid) // Erase type (User -> ())
            |> mapError(LoginError.fromNetworkError)
            |> startOn(queueScheduler)
    }
```
That's my login function that returns a `SignalProducer`. It calls `userNetwork.postLogin` that returns an `Event<User,NetworkLoginError>` (that call is synchronous).

With that code, when someone starts the `SignalProducer`, the events are delivered on the background queue as expected, but I need them on the main queue. 
Is there any way of getting the events on the main queue (without using `dispatch_after` of course)?

Thanks in advance!

**Comment by 0xpablo** [comment]
I t

**Comment by 0xpablo** [comment]
I think I've found what I was looking for, although if someone thinks I'm not using the APIs the way they were designed I'd appreciate any feedback :)

```swift
        loginInteractor.login("email@domain.com", password: "******")
            |> observeOn(QueueScheduler.mainQueueScheduler)
            |> start(next: {
                println(NSThread.isMainThread()) // prints 'true'
            })
```

Thanks anyway!

**Comment by jspahrsummers** [comment]
`observeOn` is indeed the operator you want here. :+1:
