### ISSUE TITLE
RACSignal best pratice

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [ReactiveCocoa/ReactiveCocoa#1963]
Hi All,

I'm constantly fighting we some "tricky" use cases for which I would like to discuss the best approach.

For example, signal "foo" is used by my table view binder as the fetch signal but also is used by the progress indicator to start / stop animating. The basic idea is that both the table view binder and the progress indicator subscribe to the same signal and only one subscription should occur. 

This is something easy to achieve by returning always the same RACSignal instance and use one of the replay methods to workaround multiple subscriptions, i guess :)

- (RACSignal*) foo
{
    return [self.service fetchData];
}

So, my questions are:

- Should I make foo a property instead of a method ?
- Should I keep foo as a method but use dispatch_once to control the lifetime ?
- Should I leave the replay responsibility to the callers ?
- Is there any other usage pattern for this scenario ?

Thanks in advance,

**Comment by jspahrsummers** [comment]
The general pattern is to store the replayed signal in a property, so all consumers of it get the replayed version (and not the cold signal by accident).

But in this specific case, it sounds like you may want to look more closely at `RACCommand`, which gives you loading information in the form of the `executing` property.

**Comment by vitorhugomagalhaes** [comment]
Thanks for quick reply.
