### ISSUE TITLE
How Signal can be concatenated with other Signal?

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#1965]
My issue is the following. I have two actions, each of them sends its output (the same) type, the results of both outputs should be set to the property. 

There's a concat method for SignalProducer, but it isn't available for Signal. So how my issue can be resolved?

```
let removeURLsAction: Action<[NSURL], [NSURL], NoError>
let exportDocumentAction: Action<NSURL, [NSURL], NoError>

...

let mutableExportedURLs = MutableProperty<[NSURL]>([])
mutableExportedURLs <~ exportDocumentAction.values |> concat(removeURLsAction.values)

let exportedURLs = PropertyOf<[NSURL]>(mutableExportedURLs)
```

**Comment by jspahrsummers** [comment]
See https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1929.
