### ISSUE TITLE
Should flatten operations ignore Interrupted events on inner signals

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#1967]
From the discussion started in #1930

>> @neilpa Since Signals send Interrupted if observed after they've already terminated, those operators wouldn't behave as expected.

> I was thinking about pre-Interrupted world. However, this makes me wonder if an Interrupted event on the inner signals should be ignored rather than "poison" the outer signal in the same way as Error.

**Comment by jspahrsummers** [comment]
Yeah, I think they should. This is a great suggestion. :+1:
