### ISSUE TITLE
What is the analog of startWith for RAC 3.0?

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#1969]
I need to implement analog of NSUserDefaults extension from RAC 2.* which handles notification NSUserDefaultsDidChangeNotification.

**Comment by jspahrsummers** [comment]
You can concatenate a `SignalProducer(value:)` for the same effect.

**Comment by larryonoff** [comment]
Thank you. It looks that it's what I need.
