### ISSUE TITLE
UserDefaultsProperty based on MutablePropertyType

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#1971]
I'm writing now UserDefaultsProperty for ReactiveCocoa 3.0 which acts like RACChannelTerminal. What do you think about the approach? Maybe there's another better architecture approach for the case?

**Comment by larryonoff** [comment]
This is what I initially have.

```swift
import Foundation
import ReactiveCocoa

public class UserDefaultsProperty: MutablePropertyType {
	public typealias Value = AnyObject?

    private var userDefaults: NSUserDefaults {
        return NSUserDefaults.standardUserDefaults()
    }
    
    private let key: String

    public var value: AnyObject? {
        get {
            return userDefaults.objectForKey(key)
        }

        set(x) {
            userDefaults.setObject(x, forKey: key)
        }
    }

	private let observer: Signal<AnyObject?, NoError>.Observer
	public let producer: SignalProducer<AnyObject?, NoError>
    
    public init(key: String) {
        let (producer, observer) = SignalProducer<AnyObject?, NoError>.buffer(1)

        self.producer = producer
        self.observer = observer

        self.key = key

        let userDefaultsDidChangeSignal = NSNotificationCenter.defaultCenter().rac_notifications(name: NSUserDefaultsDidChangeNotification, object: self.userDefaults)
        userDefaultsDidChangeSignal.observe(next: { notification in
            sendNext(self.observer, self.value)
        })

        sendNext(observer, self.value)
    }

    deinit {
        sendCompleted(observer)
    }
}
```

**Comment by jspahrsummers** [comment]
I don't think we should add multi-way bindings to RAC 3.0, but [we could in the future](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1911).

Furthermore, I actually think two-way bindings to `NSUserDefaults` are kind of an anti-pattern. It implies that your code is trying to communicate with itself, but it's doing so very indirectly.

Instead, in the code that modifies the defaults, I'd fire a signal or something that notifies other parts of the code that may care.

**Comment by larryonoff** [comment]
I'm not good in the main ideology of RAC 3.0. If you can provide any link to read about that would be great.

From my current point of view UserDefaultsProperty has the same idea as DynamicProperty.

As far as I understood I can have MutableProperty<T> which is bind on ```NSUserDefaults``` key. I should subscribe on change of this property to update ```NSUserDefaults``` key.

**Comment by jspahrsummers** [comment]
You're right that `DynamicProperty` is a bit of an odd duck—it will notify you about changes that occur _outside_ of the instance, but that's because of how KVO behaves.

I don't think we should be trying to emulate its example. Most `PropertyType`s should only send signal events for changes that go through that property instance, I think.

**Comment by larryonoff** [comment]
So I see the approach for my case now the following.
1. Create private ```MutableProperty```.
2. Wrap it into ```PropertyOf```.
3. Bind ```NSUserDefaults``` notification to the ```PropertyOf```.
4. Create ```Action``` to update ```MutableProperty```.

What do you think? Maybe the same approach will work for KVO?
What do you think about making RAC best practices guide or FAQ for RAC?

**Comment by jspahrsummers** [comment]
> What do you think? Maybe the same approach will work for KVO?

It could work for KVO—it's just weird that we would have one type for KVC and one type for KVO, when they're both based on the same mechanism anyways.

> What do you think about making RAC best practices guide or FAQ for RAC?

We have a list of best practices, it just needs to [be updated for Swift](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/881).

**Comment by neilpa** [comment]
Closing, but please re-open if that doesn't answer your question.
