### ISSUE TITLE
Is there a way to convert value type of PropertyOf(DynamicProperty) to concrete type?

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#1972]

**Comment by jspahrsummers** [comment]
I'm afraid I don't understand the question. Are you asking if there's a way to “unwrap” a `PropertyOf` back into the base type?

If so, the answer is no. This is why it's known as a “type erased” property—you can't recover the original type information.

**Comment by larryonoff** [comment]
Sorry for the unclear question, it looks that you understood my question.

My questions was the following. I have PropertyOf<AnyObject>, I want to map it to another PropertyOf, e.g. PropertyOf<String>.

**Comment by jspahrsummers** [comment]
If you want to map the value in a property, there's no easy way to do that right now. You could just create a new `MutableProperty`, bind a transformed signal (from the original property) to that, then wrap it in `PropertyOf`.

**Comment by larryonoff** [comment]
Should the new method be implemented like ```promoteProperty``` ?

**Comment by jspahrsummers** [comment]
How do you plan to use it? I haven't had a use case for this myself, so I'm having a hard time picturing whether it would be useful to most RAC users.

**Comment by larryonoff** [comment]
It looks that the best case is something like 
```swift
PropertyOf<T>(a) |> map { // convert value to the new type }
```
as results new PropertyOf<newT> created.

**Comment by jspahrsummers** [comment]
I understand how you would call a method/operator like that, but I want to know more about why you're needing to map properties in the first place. Do you have an example usage?

**Comment by larryonoff** [comment]
Let me find the example

**Comment by larryonoff** [comment]
See example below. But I see now that mapping for ```PropertyOf``` or ```MutableProperty``` is unnecessary here.

```swift
let documentURL: MutableProperty<NSURL?>

private let _keywords: MutableProperty<[String]>
var keywordsString: PropertyOf<String> {
   return PropertyOf(_keywordsString)
}
```

```swift
let documentAvailable: SignalProducer<Bool, NoError> = documentURL.producer |> map { $0 != nil }
let keywordsAvailable: SignalProducer<Bool, NoError> = keywords.producer |> map { count($0) != 0 }
let exportDocumentActionEnabled: MutableProperty<Bool> = MutableProperty(false)
exportDocumentActionEnabled <~ combineLatest(documentAvailable, keywordsAvailable) |> map { $0 && $1 }
```

**Comment by jspahrsummers** [comment]
Let's leave it out for now, but we can always revisit this after the 3.0 release.
