### ISSUE TITLE
lazy symbol binding failed: Symbol not found

### ISSUE THREAD

**Issue by gabro** [ReactiveCocoa/ReactiveCocoa#1973]
Hi all,
I installed the latest beta (3.0beta.4) using Carthage.
I linked `ReactiveCocoa`, `Result` and `Box` and added a *Copy Files* phase to copy the frameworks from the `Carthage/Build/iOS` directory.

The project compiles just fine, but as soon as I'm doing this:

```
let email = MutableProperty<String>("")      
email <~ loginView.emailTextField.rac_textSignal().toSignalProducer()
  |> map { $0 as! String }
  |> catch { _ in SignalProducer<String, NoError>.empty }
```

I get a nasty runtime error:

> dyld: lazy symbol binding failed: Symbol not found: __TZF13ReactiveCocoaoi2ltU_S_19MutablePropertyType__FTQ0_GVS_14SignalProducerQ_OS_7NoError__PS_10Disposable_
  Referenced from: /Users/gabro/Library/Developer/CoreSimulator/Devices/8145434A-75E6-49C3-9429-BB517DA2BBDE/data/Containers/Bundle/Application/E7863E58-3CB1-4354-B692-09639FD871E1/hailadoc-ios.app/hailadoc-ios
  Expected in: /Users/gabro/Library/Developer/CoreSimulator/Devices/8145434A-75E6-49C3-9429-BB517DA2BBDE/data/Containers/Bundle/Application/E7863E58-3CB1-4354-B692-09639FD871E1/hailadoc-ios.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa

> dyld: Symbol not found: __TZF13ReactiveCocoaoi2ltU_S_19MutablePropertyType__FTQ0_GVS_14SignalProducerQ_OS_7NoError__PS_10Disposable_
  Referenced from: /Users/gabro/Library/Developer/CoreSimulator/Devices/8145434A-75E6-49C3-9429-BB517DA2BBDE/data/Containers/Bundle/Application/E7863E58-3CB1-4354-B692-09639FD871E1/hailadoc-ios.app/hailadoc-ios
  Expected in: /Users/gabro/Library/Developer/CoreSimulator/Devices/8145434A-75E6-49C3-9429-BB517DA2BBDE/data/Containers/Bundle/Application/E7863E58-3CB1-4354-B692-09639FD871E1/hailadoc-ios.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa

I clearly missed some steps during the framework integration, any idea?

**Comment by NachoSoto** [comment]
Did you try wiping out derived data (`rm -rf ~/Library/Developer/Xcode/DerivedData/`) and building the frameworks again?

**Comment by gabro** [comment]
I did, no luck though 

~ gabriele

**Comment by gabro** [comment]
Apparently this is specific to my project. I tried on a fresh one and I managed to have ReactiveCocoa up and running simply following the instruction on the Carthage readme.
Thanks for the support anyway

**Comment by redfearnk** [comment]
I got this error in a brand new, empty project on the `swift2` branch... Deleting Derived Data does not resolve it. The crash happens on app run. No code has been written yet.

```
dyld: Symbol not found: __TMpSs14DebugPrintable
  Referenced from: /Users/kyle/Library/Developer/CoreSimulator/Devices/5EDC91E1-FCB3-4CF1-AE8B-BA553D8C2612/data/Containers/Bundle/Application/D9D2ACF1-945C-4BBE-BE64-A3DABB0DD6E9/CRUD_FP.app/Frameworks/Box.framework/Box
  Expected in: /Users/kyle/Library/Developer/CoreSimulator/Devices/5EDC91E1-FCB3-4CF1-AE8B-BA553D8C2612/data/Containers/Bundle/Application/D9D2ACF1-945C-4BBE-BE64-A3DABB0DD6E9/CRUD_FP.app/Frameworks/libswiftCore.dylib
 in /Users/kyle/Library/Developer/CoreSimulator/Devices/5EDC91E1-FCB3-4CF1-AE8B-BA553D8C2612/data/Containers/Bundle/Application/D9D2ACF1-945C-4BBE-BE64-A3DABB0DD6E9/CRUD_FP.app/Frameworks/Box.framework/Box
```

**Comment by neilpa** [comment]
If you're using `swift2` you shouldn't be linking `Box` since that dependency was removed.

**Comment by redfearnk** [comment]
Thanks. Deleted the build artifacts from Carthage and rebuilt them. Box was not included this time. Problem resolved.
