### ISSUE TITLE
Is there easy / preferred way of converting from RACSignal (obj c) to Signal (swift)

### ISSUE THREAD

**Issue by huragan** [ReactiveCocoa/ReactiveCocoa#1976]
Hi,

I just started using ReactiveCocoa (v 3.0 beta.3) with Swift so please bare with me. 

What is the best way to convert an RACSignal to a typed Signal? 

Specifically Im asking about the signals returned from UITextField.rac_textSignal()
so far i came up with:
<p><code>
   let usernameSignal = Signal<String, NoError> {
            [weak self] sink in
            self!._usernameField?.rac_textSignal().subscribeNext({ (text: AnyObject!) -> Void in
                if let textString = text as? String {
                    sendNext(sink, textString)
                }
            })
            return nil
        }
</code></p>

**Comment by MichaelMcGuire** [comment]
I would take a look at #1930 and the linked issues from there.

**Comment by huragan** [comment]
@MichaelMcGuire thanks thats very helpful
