### ISSUE TITLE
carthage update error

### ISSUE THREAD

**Issue by MessageDream** [ReactiveCocoa/ReactiveCocoa#1977]
Do you know how to solve this problem? When I use the carthage to get ReactiveCocoa.

*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
Parse error: expected submodule commit SHA in ls-tree output:
[1]    98490 segmentation fault  carthage update .

Cartfile:
github "ReactiveCocoa/ReactiveCocoa" ~> 3.0.4

**Comment by jspahrsummers** [comment]
This looks like a Carthage bug. Could you please [open an issue](https://github.com/Carthage/Carthage/issues/new) there, and include the crash log file from Console.app?
