### ISSUE TITLE
Question - how to create a "stall" operator

### ISSUE THREAD

**Issue by leoschweizer** [ReactiveCocoa/ReactiveCocoa#1978]
Let's assume a scenario where I have two signals:
* one trigger signal which sends `nexts` from time to time and is used to trigger the execution of other code
* one stall signal which sends `@YES` or `@NO` and indicates whether the trigger signal should be delivered or not.

What I want is that while the last value from the stall signal is `@YES`, no value from the trigger signal should be delivered. BUT: the last value of the trigger signal should be "remembered" and delivered once the stall signal turns to `@NO` again.

My best attempt so far was
```
- (instancetype)stallWhile:(RACSignal *)stallSignal {
	return [[[RACSignal
		combineLatest:@[self, stallSignal]
		reduce:^id(RACTuple *triggerInfo, NSNumber *doStall){
			return RACTuplePack(triggerInfo, doStall);
		}]
		filter:^BOOL(RACTuple *tuple) {
			NSNumber *doStall = tuple.second;
			return ![doStall boolValue];
		}]
		map:^id(RACTuple *tuple) {
			return [tuple first];
		}];
}
```
or a little shorter ;)
```
return [RACSignal if:stallSignal then:[RACSignal never] else:[self replayLast]];
```

This is almost what I want. There is just one problem: both approaches re-deliver the last trigger when the stall signal repeatedly changes it's value. In other words, the remembered value from the trigger signal doesn't get consumed. But the last value from the trigger signal should only be delivered once.

I hope my intent is comprehensible. I'm a little out of ideas right now and would appreciate any input how to implement this. Maybe I just don't see the obvious :)

**Comment by neilpa** [comment]
Take a look at `bufferWhile:` in #1265. It's almost what you want but would need a tweak to support a capacity param for the buffer.

It may also be possible to implement your desired behavior in terms of `combineLatestWith:` followed by `scanWithStart:reduce:`.

**Comment by leoschweizer** [comment]
Thanks for the hint. Adapting this idea to support a buffer size (default to 1 in my case) is very straightforward and I ended up with this implementation which seems to do the job just fine:

```
- (RACSignal *)stallWhile:(RACSignal *)stallSignal {
	return [self stallWhile:stallSignal keepLast:1];
}

- (RACSignal *)stallWhile:(RACSignal *)stallSignal keepLast:(NSUInteger)stallBufferSize {
	
	return [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
		
		RACCompoundDisposable *compoundDisposable = [RACCompoundDisposable compoundDisposable];
		
		NSMutableArray *stalled = [NSMutableArray arrayWithCapacity:stallBufferSize];
		__block BOOL stall = NO;
		
		RACDisposable *disableDisposable = [stallSignal
			subscribeNext:^(NSNumber *doStall) {
				@synchronized(stalled) {
					stall = [doStall boolValue];
					if (!stall) {
						for (id value in stalled) {
							[subscriber sendNext:value == [NSNull null] ? nil : value];
						}
						[stalled removeAllObjects];
					}
				}
			}
			error:^(NSError *error) {
				[subscriber sendError:error];
			}
			completed:^{
				[subscriber sendCompleted];
			}];
		
		[compoundDisposable addDisposable:disableDisposable];

		RACDisposable *sourceDisposable = [self
			subscribeNext:^(id x) {
				@synchronized(stalled) {
					if (stall) {
						[stalled addObject:x ?: [NSNull null]];
						while (stalled.count > stallBufferSize) {
							[stalled removeObjectAtIndex:0];
						}
					} else {
						[subscriber sendNext:x];
					}
				}
			}
			error:^(NSError *error) {
				[subscriber sendError:error];
			}
			completed:^{
				[subscriber sendCompleted];
			}];
		
		[compoundDisposable addDisposable:sourceDisposable];
		return compoundDisposable;
		
	}];
	
}
```

But damn... that is a lot of code xD However, the translation of this logic to `combineLatest` / `scanWithStart:reduce:` is also not obvious to me.

**Comment by neilpa** [comment]
> But damn... that is a lot of code xD However, the translation of this logic to combineLatest / scanWithStart:reduce: is also not obvious to me.

Yea, a more succinct solution would be nice. My thought around `scanWithStart:reduce:` was to use it for edge detection of the stall signal since you can recover before and after. Whenever it transitions from running to stalled buffer a nil value. If the trigger changes while stalled replace nil with that value. Then when stalled transitions to running send the buffered value when non-nil. I haven't tried to write the code though so this may be harder than I'm envisioning.
