### ISSUE TITLE
Signal lifetime of NSNotificationCenter.rac_notifications() can't be controlled by consumers side

### ISSUE THREAD

**Issue by ikesyo** [ReactiveCocoa/ReactiveCocoa#1980]
[The documentation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/e38812236b37b2d2b8fda98be1e1ed0cdd0e4f0c/ReactiveCocoa/Swift/FoundationExtensions.swift#L14-L15) of `NSNotificationCenter.rac_notifications()` says:

> This signal will not terminate naturally, so it must be explicitly disposed to avoid leaks.

To dispose the signal, consumers should do it by calling `dispose()` to the disposable returned from the generator closure directly, or by sending a termination event to the observer (sink). But because neither the disposable or the observer is not passed to consumers, it seems that there is no way for them to dispose the returned signal.

Do I understand it correctly?

**Comment by jspahrsummers** [comment]
Yep, this is definitely an issue. Nice catch!

I'm not sure what the best solution is here, honestly. We could return a `SignalProducer`, but that seems kind of silly, or we could return a separate `Disposable` for the consumer to use.

Then again, I guess `SignalProducer` offers more “fidelity” than `Signal`, so maybe it wouldn't be so bad to return it.

**Comment by MichaelMcGuire** [comment]
I hope it's ok for me to chime in here, but I think returning a tuple with both `Signal` and `Disposable` makes more sense and fits in with [the definitions of `Signal`/`SignalProducer`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/CHANGELOG.md#hot-signals-are-now-signals) in the documentation.

**Comment by neilpa** [comment]
Returning `(Signal, Disposable)` is probably more "correct" but in practice a `SignalProducer` is easier to use. The latter composes better and makes it harder for consumers to incorrectly manage the lifetime of the observation.

**Comment by jspahrsummers** [comment]
I've started coming around to the idea of `UIControl`, `NSNotificationCenter`, etc. being classified as producers.

It's a bit of an implementation detail, certainly, but there _is_ a side effect (add/remove target, add/remove observer) involved in “subscription,” and I don't feel bad about faithfully representing that part.
