### ISSUE TITLE
rac_textSignal not work on UITextView

### ISSUE THREAD

**Issue by onmyway133** [ReactiveCocoa/ReactiveCocoa#1981]
I'm writing this in the ViewController, (iOS 8, RAC 2.5)

```
RAC(self.viewModel, text) = [self.textView rac_textSignal]
```

I'm checking that viewModel and textView are not nil, but the text is not set when I type in the textView

**Comment by neilpa** [comment]
Do you have an example project? I wasn't able to reproduce on a new project targeting the master branch.

**Comment by onmyway133** [comment]
@neilpa thanks, I `self.textView.delegate = self` before I bind using RAC, it works

**Comment by schickling** [comment]
Having the same problem. Does `rac_textSignal` has to be implemented via a delegate? It basically makes it impossible to use other another delegate.

**Comment by neilpa** [comment]
@schickling This is more of a general problem with the delegate pattern, there can only be one. In the case of RAC, it's the only way to get changes since like most of UIKit text views don't support KVO.

**Comment by schickling** [comment]
@neilpa Sorry I deleted my comment since I realized I could solve the problem otherwise.
