### ISSUE TITLE
[RAC 3.0] API to throttle a SignalProducer

### ISSUE THREAD

**Issue by robertjpayne** [ReactiveCocoa/ReactiveCocoa#1982]
This is mostly a feature request to add API to allow throttling a SignalProducer's events, though maybe I'm just doing it wrong:

```swift
self.viewModel.loginAction.executing.producer |> start(next: { [weak self] (executing) -> Void in
    self?.formView.submitButton.animating = executing
})
```

In this particular case I want to throttle the event so it fires no more than once every 0.5s.

**Comment by MichaelMcGuire** [comment]
You can use the [throttle operator from `Signal`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/ReactiveCocoa/Swift/Signal.swift#L761-L819) with a `SignalProducer` thanks to the lifting mechanism.

**Comment by neilpa** [comment]
The documentation for 3.0 is still sparse but any unary or binary operators over `Signal` can be lifted to `SignalProducer`s either [directly](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/d3cd58ab57ee14bbabf6fa23072c165d44eaa539/ReactiveCocoa/Swift/SignalProducer.swift#L241-L276) or via [`|>`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/d3cd58ab57ee14bbabf6fa23072c165d44eaa539/ReactiveCocoa/Swift/SignalProducer.swift#L279-L291). The latter is the common practice.

**Comment by robertjpayne** [comment]
Man, my bad on this I was using the throttle operator wrong and getting swift errors so thought it would't work!
