### ISSUE TITLE
[RAC-3.0] Question - am I properly wrapping this NSURLSessionDataTask in a SignalProducer?

### ISSUE THREAD

**Issue by jjoelson** [ReactiveCocoa/ReactiveCocoa#1983]
Hi guys. I'm finding the new Swift API a bit difficult to grok (and I was no wiz in RAC 2 anyway), so I was wondering if someone could help me understand whether I'm doing this correctly:
``` Swift
static func dataTaskSignalProducer(session: NSURLSession, request: NSURLRequest) -> SignalProducer<NSData, NSError> {
        return SignalProducer { sink, disposable in
            let task = session.dataTaskWithRequest(request) { data, response, error -> Void in
                if (response != nil && data != nil) {
                    sendNext(sink, data)
                }
                else {
                    sendError(sink, error)
                }
                sendCompleted(sink)
            }
            
            disposable.addDisposable {
                task.cancel()
                sendInterrupted(sink)
            }
            
            task.resume()
        }
    }
```

My main questions are:
- Am I a handling the disposable correctly? In RAC 2, I would use `disposableWithBlock:`. 
- Do I need to `sendCompleted(sink)` after success and failure (as I have in the example), or should it only be sent when the request succeeds?
- Is my use of `sendInterrupted(sink)` correct?
- If I had another function `static func parseJSON(data: NSData) -> SignalProducer<MyClass, NSError>`, how would I bind that to my first function to download and then parse the data? I susect I need the `|>` function, but I'm having difficulty understanding it.

Any help understanding these questions would be greatly appreciated.

**Comment by MichaelMcGuire** [comment]
You may want to check out the [built-in extension to `NSURLSession`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/ReactiveCocoa/Swift/FoundationExtensions.swift#L29-L50) included in RAC 3.0.  You were pretty close in your implementation.

To answer your questions:
* You do not need to `sendInterrupted` in your disposable block.  In fact, you don't want to, as the disposable will be fired in completed, interrupted and error conditions (I think).
* Only in the success condition would you call `sendCompleted`.  The completed event signals success and that no more events are coming.  
* See above.
* I am doing something similar to this.  Change the signature of your function to `static func parseJSON(signalProducer: SignalProducer<NSData, NSError>) -> SignalProducer<MyClass, NSError>` then you can combine your operators like so:

```
dataTaskSignalProducer(session, request) |> parseJSON |> observe(next: { class in <code here> |)
```

Or more likely wrap up your stuff into an `Action` that can be exposed in a view model layer.

**Comment by neilpa** [comment]
> I am doing something similar to this. Change the signature of your function to static func parseJSON(signalProducer: SignalProducer<NSData, NSError>) -> SignalProducer<MyClass, NSError> 

You can also use `map` to avoid changing the `parseJSON` signature.

```swift
dataTaskSignalProducer(session, request) |> map(parseJSON) |> observe(next: { json in … })
```

**Comment by MichaelMcGuire** [comment]
> You can also use map to avoid changing the parseJSON signature.

You could need to change his function to `static func parseJSON(data: NSData) -> MyClass` then, correct? And since parsing can fail, it might be better to go with `tryMap` with the function becoming `static func parseJSON(data:NSData) -> Result<MyClass, NSError>` and the call becoming:

```
dataTaskSignalProducer(session, request) |> tryMap(parseJSON) |> observe(next: { json in … })
```

**Comment by neilpa** [comment]
@MichaelMcGuire You're right, returning a `Result` is probably the best approach for this.

**Comment by jjoelson** [comment]
Thanks for the responses. It's good to know that there's already a NSURLSession extension built into RAC for this type of thing (and that it's implementation is nearly identical to mine), but this has still been educational for me. 

I don't like the idea of changing the function signature to enable chaining calls; making the parameter `NSData` means the function can be used in more contexts and it's simpler to write unit tests for it. I'm surprised there is not a built in operator to do this in one step given how this seems to pretty much be a monadic bind operation, but adding `map` or `tryMap` is not too cumbersome.

So I suppose `sendInterrupted` is not something I really ever have to worry about sending as long as I'm not implementing my own operator, because the disposable automatically ensures that it is sent?

**Comment by MichaelMcGuire** [comment]
> I don't like the idea of changing the function signature to enable chaining calls; making the parameter NSData means the function can be used in more contexts and it's simpler to write unit tests for it.

@jjoelson couldn't agree more.  I think going with the `static func parseJSON(data:NSData) -> Result<MyClass, NSError>` makes the most sense as it makes best use of existing operators (`tryMap`) and is in no way dependent on RAC (the `Result` type is actual separate from RAC).

**Comment by jjoelson** [comment]
@MichaelMcGuire good point, I think that's even better.

**Comment by neilpa** [comment]
Closing, but re-open if that doesn't answer your question.

**Comment by jjoelson** [comment]
Thanks @neilpa, I forgot to close this one.
