### ISSUE TITLE
[RAC-3.0] Question 2-Way Binding Example?

### ISSUE THREAD

**Issue by aventurella** [ReactiveCocoa/ReactiveCocoa#1986]
I'm assuming 2 way binding is something like this?

```swift

@IBOutlet weak var myNSTextField //...assume it's assigned
var myModelWithMutableProperties // ... assume it's assigned


let inputProducer = myNSTextField.rac_textSignal().toSignalProducer()

myModelWithMutableProperties.someName.producer.start(next: {value in
    self.myNSTextField.stringValue = value
})

inputProducer.start(next: { value in
    myModelWithMutableProperties.someName.value = value as? String
})

```

**Comment by neilpa** [comment]
I would take a look at [ReactiveCocoa/EditableProperty](https://github.com/ReactiveCocoa/EditableProperty) that @jspahrsummers recently started to enable multi-way binding.

**Comment by larryonoff** [comment]
_keywordsString = keywordsStringProperty
        _keywordsString <~ userDefaults.rac_signalForKey(UserDefaultsKeywordsKey)
            |> map { object in
                if let keywords = object as? String {
                    return keywords
                } else {
                    return ""
                }
            }
            |> filter { $0 != keywordsStringProperty.value }

**Comment by larryonoff** [comment]
property = MutableProperty("")
property <~ userDefaults.rac_signalForKey(SomeKey)

**Comment by larryonoff** [comment]
I assume that my code contains extra code, but I have implemented two-way binding for ```NSUserDefaults``` in the following way.

```swift
private let _property: MutableProperty<String>
var property: PropertyOf<String> {
    return PropertyOf(_property)
}
```

```swift
_property = MutableProperty<String>("")
_property <~ userDefaults.rac_signalForKey(SomeKey)

updatePropertyAction = Action<String, String, NoError> {
    userDefaults.setObject($0, forKey: UserDefaultsKeywordsKey)
    userDefaults.synchronize()

    return SignalProducer.empty
}
```

**Comment by aventurella** [comment]
how does `updatePropertyAction` get used?  I don't see the connecting piece of code that makes use of that Action. everything else makes sense in your example.

**Comment by larryonoff** [comment]
It's used somewhere outside, e.g.

**Comment by larryonoff** [comment]
The ```property``` and ```updatePropertyAction``` are implemented inside ViewModel. ```updatePropertyAction ``` is triggered in ViewController. See 
```swift
propertyTextView.rac_textSignal().toSignalProducer()
    |> ignoreError
    |> map { object in
        if let string = object as? String {
            return string
        } else {
            return ""
        }
    }
    |> map { property in
        return self.viewModel.updatePropertyAction.apply(property) |> ignoreError
    }
    |> flatten(FlattenStrategy.Concat)
    |> start()
```

**Comment by larryonoff** [comment]
It would be great if @jspahrsummers comment about the direction of my thoughts.

**Comment by jspahrsummers** [comment]
@larryonoff Seems like that could cause a recursive notification if the thing observing the property is also the thing modifying user defaults.

**Comment by larryonoff** [comment]
@jspahrsummers I agree. This is why NSUserDefaults. rex_signalForKey was written in neilpa/Rex repo. Now it shouldn't cause a recursive notification. 

```swift
extension NSUserDefaults {
    /// Sends value of key when the value is changed
    func rex_signalForKey(key: String) -> Signal<AnyObject?, NoError> {
        let (signal, observer) = Signal<AnyObject?, NoError>.pipe()
        
        // send initial value
        let initial: AnyObject? = self.objectForKey(key)
        sendNext(observer, initial)
        
        // observe other values
        let defaultsDidChange = NSNotificationCenter.defaultCenter().rac_notifications(name: NSUserDefaultsDidChangeNotification, object: self)
        defaultsDidChange.observe(next: { notification in
            let value: AnyObject? = self.objectForKey(key)
            
            sendNext(observer, value)
        }, completed: {
            sendCompleted(observer)
        })

        return signal
            |> skipRepeats { a, b in
                    if let a = a as? NSObject, b = b as? NSObject where a.isEqual(b) {
                        return true
                    } else {
                        return false
                    }
            }
    }
}
```

**Comment by jspahrsummers** [comment]
In any case, it looks like the question here has been answered.
