### ISSUE TITLE
How to create self-cancelable command?

### ISSUE THREAD

**Issue by liyihe96** [ReactiveCocoa/ReactiveCocoa#1987]
I have a toggle button, pretty much the same as the like button on major social app, which toggles the like status. I bind a command which update UI and make network request to the button. Like this.
 
    void (^updatePinLikeStatus)() = ^{
        self.pin.likedCount = self.pin.hasLiked ? self.pin.likedCount - 1 : self.pin.likedCount + 1;
        self.pin.hasLiked = !self.pin.hasLiked;
    };
        
    _likeCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
        // Update UI, then make network request
        updatePinLikeStatus();
        return [[HBAPIManager sharedManager] likePinWithPinID:self.pin.pinID];
    }];
        
    [_likeCommand.errors subscribeNext:^(id x) {
        // rollback when error occurs
        updatePinLikeStatus();
    }];
 However, I want to cancel the previous ongoing execution, which is a network request when the command is executed again. I noticed that firstly I have to set `allowsConcurrentExecution` to YES, and then use `takeUntil:` on the signal returned in the generator block like https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1326 suggested. However, I can't find a way to refer back to the command while creating the command.

**Comment by jlawton** [comment]
If you only allow a single execution actually to go through at any time, you might just be able to cache the disposable. There's probably a much more elegant way, and I haven't tested this.

I'm thinking something like:

```objc
__block RACDisposable *currentExecutionDisposable = nil;

_likeCommand = [[RACCommand alloc] initWithSignalBlock:^(id _) {
    return [[RACSignal createSignal:^(id<RACSubscriber> subscriber) {
        [currentExecutionDisposable dispose];
        currentExecutionDisposable = [doStuff subscribe:subscriber];
    }]
    finally:^{
        currentExecutionDisposable = nil;
    }];
}];
```

**Comment by jspahrsummers** [comment]
@jlawton You can use `RACSerialDisposable` for the same effect, but with atomicity.

**Comment by jlawton** [comment]
Thanks @jspahrsummers. I was worried about races, but forgot about `RACSerialDisposable`.

**Comment by neilpa** [comment]
Closing, but re-open if that doesn't answer your question.
