### ISSUE TITLE
Cannot find an initializer for type 'ColdSignal<T>' that accepts an argument...

### ISSUE THREAD

**Issue by sirvon** [ReactiveCocoa/ReactiveCocoa#1989]
I brought in 'ReactiveCocoa', '~> 3.0.0-alpha.1'
via podfile.

When I build
I am getting this error on ColdSignal.swift file

```swift
 Cannot find an initializer for type 'ColdSignal<T>' that accepts an argument list of type '((_, _) -> _)'
```

**Comment by neilpa** [comment]
This sounds like a CocoaPods issue which isn't directly supported.
