### ISSUE TITLE
Make RAC 3 safe for use in app extensions, e.g. today widgets

### ISSUE THREAD

**Issue by rbeeger** [ReactiveCocoa/ReactiveCocoa#1990]
I'm using RAC 3 in a today widget. The widget is written in Swift and only uses the Swift API. It all seems to work nicely, but the linker always warns me that it is not safe to use ReactiveCocoa in an app extension.

I guess RAC has not "Allow app extension API only" checked in its settings.

I wonder if that could be changed or if - in the case that some part of RAC is really not safe for app extensions - a compatible subset could be extracted.

**Comment by neilpa** [comment]
Sounds reasonable and I don't think RAC uses anything in [this list](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6)

**Comment by NachoSoto** [comment]
Which version is this? We already did this (https://github.com/ReactiveCocoa/ReactiveCocoa/pull/1891). I wonder if it's a regression.

**Comment by rbeeger** [comment]
3.0 beta 4. So it looks like a regression.

**Comment by rbeeger** [comment]
@neilpa That was fast. Thanks! Looking forward to beta 5.
