### ISSUE TITLE
Add logging operators for Signals

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#1991]
I haven't found these methods, so I've implemented some of them.

```swift
public func printNext<T, E>(signal: SignalProducer<T, E>) -> SignalProducer<T, E> {
    return signal
        |> on(next: { println("next \($0)") })
}
```

```swift
public func printError<T, E>(signal: SignalProducer<T, E>) -> SignalProducer<T, E> {
    return signal
        |> on(error: { println("error: \($0)") })
}
```

Should I implement others and do pull request?

**Comment by neilpa** [comment]
For the initial release of RAC 3 we've been trying to stick with a limited set of operators. Personally, I'm ambivalent about adding logging helpers given their simplicity.

That said, I started a [repo yesterday for additional operators](https://github.com/neilpa/rex) that may not fit in RAC proper and would be happy to include these.

**Comment by larryonoff** [comment]
Committed into neilpa/Rex repo.

**Comment by kastiglione** [comment]
Rex looks cool. I had started [a repo like that for RAC 2](https://github.com/kastiglione/LabRAC).

**Comment by kastiglione** [comment]
On the subject of the log operators, I think these arguments should absolutely be part of RAC 3. My argument is that when something wasn't working, it was great to *quickly* drop in one of the ready operators, *without thinking*. It's bad of RAC to say "Imma let you finish debugging, but first write out by hand an operator that does something as mundane as logging. Oh and since you don't know where the problem is, you're probably going to have to write a bunch of these log operators inline all over the place." Not having these operators is a big :-1: for me and is not friendly to adopters. Let's get these in.

**Comment by neilpa** [comment]
Thanks, I realized it was probably needed once I started copy/pasting operators across projects.

**Comment by neilpa** [comment]
@kastiglione Your argument has pushed me out of the ambivalence camp and fully in favor now.

**Comment by kastiglione** [comment]
Cool!

**Comment by JaviSoto** [comment]
I agree these are super useful, especially for new-comers trying to understand what's going on with their signals, debugging etc.

I would recommend the signatures to be something like this however:

```swift
public func printNext<T, E>(message: String = ""), signal: SignalProducer<T, E>) -> SignalProducer<T, E> {
return signal
        |> on(next: { println("\(message): \($0)") })
}
```
That way it's easy to tell apart where the values are coming from if you use this in multiple places.

**Comment by NachoSoto** [comment]
Right, I was going to see that these were really useful in RAC 2 thanks to each operator providing a description. That might be a way to provide context now.

**Comment by neilpa** [comment]
Agree on the signature, but from what I just found [curried default params don't work](https://github.com/neilpa/Rex/commit/a5c573dd8be8cf60ef078c684048aaae54864b6f). Instead you have to rely on overloading if you want to actually use the default values.

**Comment by jspahrsummers** [comment]
Sorry to drive-by this thread (I’ll respond in detail more later), but note that this works:

```swift
producer |> on(event: println)
```

**Comment by larryonoff** [comment]
Ah! This is what I've found in ReactiveCocoa Event.swift file. RAC 3.0 definitely needs FAQ section or updated documentation.
```swift
extension Event: Printable {
	public var description: String {
		switch self {
		case let .Next(value):
			return "NEXT \(value.value)"

		case let .Error(error):
			return "ERROR \(error.value)"

		case .Completed:
			return "COMPLETED"

		case .Interrupted:
			return "INTERRUPTED"
		}
	}
}
```

**Comment by larryonoff** [comment]
I've made improvement of print methods, see pull request neilpa/Rex#8.

**Comment by jspahrsummers** [comment]
> RAC 3.0 definitely needs FAQ section or updated documentation.

This has been called out in all the release notes, and there are [open issues](https://github.com/ReactiveCocoa/ReactiveCocoa/milestones/3.0) capturing the work remaining as well. Contributions are always welcome!

**Comment by larryonoff** [comment]
I close the issue.

Several logging operators are on neilpa/Rex repo. If the team decides to include them into main repo this will be great.

**Comment by jspahrsummers** [comment]
I do think some logging operators should be built in, but I don't know if it will happen for the initial release.

**Comment by jspahrsummers** [comment]
:boot: from the [3.0 milestone](https://github.com/ReactiveCocoa/ReactiveCocoa/milestones/3.0), which will now just contain blocking issues.
