### ISSUE TITLE
Filter with previous and current value

### ISSUE THREAD

**Issue by vikfroberg** [ReactiveCocoa/ReactiveCocoa#1994]
```obj-c
[[[self.secondField.rac_textSignal
    combinePreviousWithStart:self.secondField.text
    reduce:^NSNumber *(NSString *previous, NSString *current) {
        return @(previous.length == 0 && current.length == 0);
    }]
    ignore:@(NO)]
    subscribeNext:^(id x) {
        @strongify(self);
        [self.firstField becomeFirstResponder];
    }];
```

```obj-c
[[[self.secondField.textSignal
    combinePreviousWithStart:self.secondField.text
    reduce:^RACTuple *(NSString *previous, NSString *current) {
        return RACTuplePack(previous, current);
    }]
    filter:^BOOL(RACTuple *tuple) {
        NSString *previous = tuple.first;
        NSString *current = tuple.last;
        return previous.length == 0 && current.length == 0;
    }]
    subscribeNext:^(id _) {
        @strongify(self);
        [self.firstField becomeFirstResponder];
    }];
```
Both solutions feels a bit ugly, is there anything I can do to improve? 
Maybe something like `-[RACSignal filterPrevious:withStart]`.

**Comment by neilpa** [comment]
This is a fine approach and you could create your own `-[RACSignal filterPrevious:withStart]` extension with this implementation. However, I don't think it's a common enough operator to warrant expanding the API surface of RAC.

**Comment by vikfroberg** [comment]
Thanks @neilpa, I totally agree that it's not common enough.

Are you aware of any design decisions on why `map:`, `subscribeNext:` etc. only accept one argument? It should be possible to check if it's a RACTuple and trampoline it's arguments to the block.

**Comment by neilpa** [comment]
> Are you aware of any design decisions on why map:, subscribeNext: etc. only accept one argument?

Not specifically but my guess would be for the sake of simplicity. And as you mention, there is `RACTuple` for helping with this.

**Comment by vikfroberg** [comment]
@neilpa Thanks!

**Comment by jspahrsummers** [comment]
You can use `-reduceEach:` in place of `-map:` when you're expecting a tuple. Other than the input type, they do the exact same thing.
