### ISSUE TITLE
rac_textSignal shadows textViewDidChange implementation

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#1995]
Hello,

Can I use concurrently textViewDidChange & rac_textSignal?

**Comment by jspahrsummers** [comment]
See [the documentation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/eac3f5c06134080bc5e4cfb86c2076f4be8e8c26/ReactiveCocoa/Objective-C/UITextView%2BRACSignalSupport.h#L22-L26) for `-rac_textSignal`, which describes what happens to the delegate.
