### ISSUE TITLE
[RAC 3] Use of SignalProducer breaks swift compiler

### ISSUE THREAD

**Issue by LightD** [ReactiveCocoa/ReactiveCocoa#1998]
>Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

so I have some code, really simple, a wrapper around Alamofire and then I'm mapping and flattening it and some stuff, nothing genius and nothing complicated.. the problem is whenever I use `Signal` class, the compiler doesn't complain.. whenever I just `Cmd+Option+F` and I replace `Signal` with `SignalProducer`, *I am not changing any code, just the use of the classes*, the compiler gives the error above!!

Any thoughts? has anyone faced this problem before? shouldn't the code be compatible? it's literally just the use of `|> map` mostly.. in one case only I'm using `flatten` which is mentioned in #1993

**Comment by LightD** [comment]
ok, so upon further trial and error, I solved it, but I really really don't understand........ I guess it's due to lack of documentation, or my own lack of understanding..
this is my code:
``` swift
    func reactiveRequest(requestConvertible: URLRequestConvertible) -> SignalProducer<JSONRPCResponse, NSError> {
        
        let signal: SignalProducer<JSONRPCResponse, NSError> = SignalProducer { observer, disposable in

            self.request(requestConvertible)
            .responseObject({ (request: NSURLRequest, response: NSHTTPURLResponse?, data: JSONRPCResponse) -> Void in

                if let rpcError = data.error {
                    let nserror = NSError(domain: "com.bebo.rpcerror", code: rpcError.code, userInfo: [NSLocalizedDescriptionKey: rpcError.message])
                    sendError(observer, nserror)
                }
                else {
                    sendNext(observer, data)
                    sendCompleted(observer)
                }

                }, errorHandler: { (error: NSError) -> Void in
                
                    sendError(observer, error)
                })
                //// I LITERALLY JUST ADDED THIS LINE.. FML
                return
            }
        
        return signal

    }
```

all I did is I added a `return` statement..  in the unit tests coverage this doesn't seem to be a requirement.. there isn't a return statement in all the initializations... can someone shed some light?

**Comment by jspahrsummers** [comment]
I'm not sure where the compiler's error reporting fell apart, but the issue is probably the difference in return types between the closure given to `SignalProducer.init` and `Signal.init`. One does not return anything.

**Comment by trauzti** [comment]
This issue was driving me and another iOS developer crazy! Thank you for this solution. 

Adding the return statement fixes this strange compiler error. We thought we had solved this issue by making calling URLString on the URL string for the Alamofire request, but the issue appeared again when we started using an Alamofire router. 

Hopefully people will see this issue if they have an old version of either swift or ReactiveCocoa.

**Comment by RahulKatariya** [comment]
I was having the same issue and yes adding return statement fixed it. 
But i also find out that adding a disposable block also fixes it.
Here is the above modified example with disposable block.

    func reactiveRequest(requestConvertible: URLRequestConvertible) -> SignalProducer<JSONRPCResponse, NSError> {

        let signal: SignalProducer<JSONRPCResponse, NSError> = SignalProducer { observer, disposable in

            self.request(requestConvertible)
            .responseObject({ (request: NSURLRequest, response: NSHTTPURLResponse?, data: JSONRPCResponse) -> Void in

                if let rpcError = data.error {
                    let nserror = NSError(domain: "com.bebo.rpcerror", code: rpcError.code, userInfo: [NSLocalizedDescriptionKey: rpcError.message])
                    sendError(observer, nserror)
                }
                else {
                    sendNext(observer, data)
                    sendCompleted(observer)
                }

                }, errorHandler: { (error: NSError) -> Void in

                    sendError(observer, error)
                })

            disposable.addDisposable {

            }

            }
        return signal
    }

Hope it helps.

**Comment by benji-bou** [comment]
Hi, got the same error 
But the return statement doesn't change anything. However it compiles only when I comment the use of sendError, sendNext, sendCompleted

Here my code

    func loginCredentials(username: String, password: String) -> ReactiveCocoa.SignalProducer<User, NSError> {
        
        let signalProd :  ReactiveCocoa.SignalProducer<User, NSError> = ReactiveCocoa.SignalProducer {(observer:SinkOf, dispose: CompositeDisposable) in
            
            
            Alamofire.request(.POST, "\(self.domain)auth", parameters: ["username": username, "password":password], encoding: ParameterEncoding.JSON, headers: nil).responseObject (nil) { (request :NSURLRequest, response: NSHTTPURLResponse?, user : User?, error: NSError?) -> Void in
                if let userWithKey = user {
                    
                    
                    Alamofire.request(.GET, "\(self.domain)/user/getInfo", parameters: ["api_key": userWithKey.apiKey], encoding: ParameterEncoding.JSON, headers: nil).responseObject (userWithKey) {(request :NSURLRequest, response: NSHTTPURLResponse?, U userRep :User?, error: NSError?) -> Void in
                        if let err = error
                        {
                            println(error)

                            ReactiveCocoa.sendError(observer, err);
                        }
                        else if let userFinal = userRep
                        {
                            ReactiveCocoa.sendNext(observer, userFinal);
                        }
                        else
                        {
                            ReactiveCocoa.sendError(observer, UPHTTPLoaderError.Unknown.nsError);
                        }
                        ReactiveCocoa.sendCompleted(observer)
                    }
                }
            }
        }
        return signalProd
    }
}

**Comment by ikesyo** [comment]
This should be the same as #2106, #2204 and #2257.

**Comment by benji-bou** [comment]
It works the void return in the closure was missing thank you 
The corrected code 

    
    func loginCredentials(username: String, password: String) -> SignalProducer<User, NSError> {
        
        let signalProd :  SignalProducer<User, NSError> = SignalProducer {(observer:SinkOf, dispose: CompositeDisposable) in
            
            
            Alamofire.request(.POST, "\(self.domain)auth", parameters: ["username": username, "password":password], encoding: ParameterEncoding.JSON, headers: nil).responseObject (nil) { (request :NSURLRequest, response: NSHTTPURLResponse?, user : User?, error: NSError?) -> Void in
                if let userWithKey = user {
                    
                    
                    Alamofire.request(.GET, "\(self.domain)/user/getInfo", parameters: ["api_key": userWithKey.apiKey], encoding: ParameterEncoding.JSON, headers: nil).responseObject (userWithKey) {(request :NSURLRequest, response: NSHTTPURLResponse?, U userRep :User?, error: NSError?) -> Void in
                        if let err = error
                        {
                            println(error)

                            sendError(observer, err as NSError);
                        }
                        else if let userFinal = userRep
                        {
                            sendNext(observer, userFinal);
                        }
                        else
                        {
                            sendError(observer, UPHTTPLoaderError.Unknown.nsError as NSError);
                        }
                        sendCompleted(observer)
                    }
                 
                }
            }
            return // The Void return added 
        }
        return signalProd
    }
