### ISSUE TITLE
How to connect an Action to UIButton

### ISSUE THREAD

**Issue by gabro** [ReactiveCocoa/ReactiveCocoa#1999]
Hi,
I'm trying to connect an `Action` to a `UIButton` using `CocoaAction` but I can't seem to make this compile. Here's my attempt:

## ViewModel
```
let email = MutableProperty<String>("")
let password = MutableProperty<String>("")
var loginAction: Action<Void, (String, String, String), NoError>!

init() {
    loginAction = Action(enabledIf: validLoginData) { (_: Void) in
      return combineLatest(self.email.producer, self.password.producer)
    }
    
    loginAction.values.observe { (email, password) in
      println("\(email) \(password)")
    }
}
```

## ViewController
```
    override func viewDidLoad() {
      viewModel.email           <~ loginView.emailTextField.rac_textSignalProducer()
      viewModel.password        <~ loginView.passwordTextField.rac_textSignalProducer()
      viewModel.activationCode  <~ loginView.activationCodeTextField.rac_textSignalProducer()
      
      let loginCocoaAction = CocoaAction(viewModel.loginAction)  
      loginView.loginButton.addTarget(loginCocoaAction, action: CocoaAction.selector, forControlEvents: UIControlEvents.TouchUpInside)      
    }
```

I get a compiler error on the line

```
let loginCocoaAction = CocoaAction(viewModel.loginAction)
```

Here's the message:
> /Users/gabro/Work/buildo/hailadoc/ios/hailadoc-ios/LoginViewController.swift:42:25: Cannot find an initializer for type 'CocoaAction' that accepts an argument list of type '(Action<Void, (String, String, String), NoError>!)'

According to the [changelog for RAC 3.0](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/08a73c888bf02b372e02ed338ecf3352afad3b77/CHANGELOG.md) I should be able to wrap my action with `CocoaAction` in order to attach it to a `UIControl` such as `UIButton`, but I seem to be unable to make this compile.

What am I doing wrong here?

**Comment by ikesyo** [comment]
The [`CocoaAction` initializer you are using](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/9ffe766aa5ed2a50a2a5ac4abcdec4a31ff65f0a/ReactiveCocoa/Swift/Action.swift#L193) can accepts `Input` which is `AnyObject`, but your action `Input` type is `Void` which is not `AnyObject`. You might be able to use the following initializer instead:

```swift
let loginCocoaAction = CocoaAction(viewModel.loginAction, input: ())
```

**Comment by gabro** [comment]
Thank you, that actually compiles, but now I get a runtime error.

```
2015-05-12 15:52:55.967 hailadoc-ios[69944:7010939] -[__NSArrayM execute:]: unrecognized selector sent to instance 0x7f89d9733820
2015-05-12 15:52:55.979 hailadoc-ios[69944:7010939] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM execute:]: unrecognized selector sent to instance 0x7f89d9733820'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106b01c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010679abb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000106b090ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000106a5f13c ___forwarding___ + 988
	4   CoreFoundation                      0x0000000106a5ecd8 _CF_forwarding_prep_0 + 120
	5   UIKit                               0x000000010713dda2 -[UIApplication sendAction:to:from:forEvent:] + 75
	6   UIKit                               0x000000010724f54a -[UIControl _sendActionsForEvents:withEvent:] + 467
	7   UIKit                               0x000000010724e919 -[UIControl touchesEnded:withEvent:] + 522
	8   UIKit                               0x000000010718a998 -[UIWindow _sendTouchesForEvent:] + 735
	9   UIKit                               0x000000010718b2c2 -[UIWindow sendEvent:] + 682
	10  UIKit                               0x0000000107151581 -[UIApplication sendEvent:] + 246
	11  UIKit                               0x000000010715ed1c _UIApplicationHandleEventFromQueueEvent + 18265
	12  UIKit                               0x00000001071395dc _UIApplicationHandleEventQueue + 2066
	13  CoreFoundation                      0x0000000106a35431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	14  CoreFoundation                      0x0000000106a2b2fd __CFRunLoopDoSources0 + 269
	15  CoreFoundation                      0x0000000106a2a934 __CFRunLoopRun + 868
	16  CoreFoundation                      0x0000000106a2a366 CFRunLoopRunSpecific + 470
	17  GraphicsServices                    0x000000010ceeca3e GSEventRunModal + 161
	18  UIKit                               0x000000010713c900 UIApplicationMain + 1282
	19  hailadoc-ios                        0x0000000105e024c7 main + 135
	20  libdyld.dylib                       0x00000001096e7145 start + 1
	21  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I don't know where does that `NSArray` come from, honestly

**Comment by jspahrsummers** [comment]
Seems to be the same issue as #2000.

**Comment by MarcoSero** [comment]
I'm experiencing the same issue on beta-7.

```swift
let addAction = Action<Void, Void, NoError> { value in SignalProducer.empty }
addButtonItem.target = CocoaAction(addAction) { _ in println("button tapped") }
addButtonItem.action = CocoaAction.selector
```

The crash seems to be happening always on a different instance (?)

```
'NSInvalidArgumentException', reason: '-[__NSArrayM execute:]: unrecognized selector sent to instance 0x7f89d9733820'
```
```
'NSInvalidArgumentException', reason: '-[NSISInlineStorageVariable execute:]: unrecognized selector sent to instance 0x7ff058caa480'
```
```
'NSInvalidArgumentException', reason: '-[NSISRestrictedToZeroMarkerVariable execute:]: unrecognized selector sent to instance 0x7fb579cc4350'
```

**Comment by neilpa** [comment]
That class of crash almost always means someone is trying to use a freed object. That's the case here since the `NSControl` only keeps a weak reference on `target` and you aren't storing the `CocoaAction` anywhere else.

**Comment by MarcoSero** [comment]
Ops, you are quite right.
I know this is basic memory management but I wonder whether perhaps there is a way to make it more clear and less prone to error?

**Comment by neilpa** [comment]
We may be able to do something similar to [`DynamicProperty`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/ad1fd34561d3f2f42e0feb420ace5de321906b78/ReactiveCocoa/Swift/Property.swift#L167-L170) but I haven't thought much about it (or if opens up other problems).

**Comment by jspahrsummers** [comment]
We could perhaps tie the lifecycle to that of the underlying `Action`, but that might be confusing in its own right.

**Comment by jspahrsummers** [comment]
Maybe it would be better to expose a `cocoaAction` accessor on `Action`, instead of requiring one to be initialized manually.

**Comment by neilpa** [comment]
:+1: for the accessor idea.

**Comment by schickling** [comment]
What's the best workaround for this at the moment?

**Comment by MarcoSero** [comment]
@schickling you can store the reference of the `CocoaAction` until #2104 gets merged.

**Comment by sammoore** [comment]
I haven't tested this but based on the thread I'd say store the CocoaAction as a property on the VC or view in question, so that it has a lasting strong reference / isn't deallocated, _then_ add it as a target on the UI element.

**Comment by gabro** [comment]
I can confirm that holding a strong reference to the `CocoaAction` instance works.

In my view model I have now something along these lines:

```swift
class SignupViewModel {
  var signupAction: Action<AnyObject?, [String: String], NSError>!
  var cocoaSignupAction: CocoaAction!

  init() {
    signupAction = ...
    cocoaSignupAction = CocoaAction(signupAction)
  }
}
```
