### ISSUE TITLE
Pipe operator for composite disposables

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2001]
This may be crazy talk but I've toyed with `|>`ing disposables from `start` or `observe` into a `CompositeDisposable` and have been liking it. Especially for multiline signal chains where wrapping with `addDisposable` or storing the return value feels like it adds "noise".

```swift
// piped
producer
    |> map { ... }
    |> filter { ... }
    |> start { ... }
    |> disposable

// wrapped
disposable.addDisposable(producer
    |> map { ... }
    |> filter { ... }
    |> start { ... })

// stored
let producerDisposable = producer
    |> map { ... }
    |> filter { ... }
    |> start { ... }
disposable.addDisposable(producerDisposable)
```

Thoughts?

**Comment by neilpa** [comment]
Or perhaps a sander approach the sticks to function application

```
producer
    |> map { ... }
    |> filter { ... }
    |> start { ... }
    |> disposable.addDisposable
```

**Comment by nomothetis** [comment]
That's interesting. We are using an operator too: `+=`, like so:

```swift
disposable += producer
    |> map { ... }
    |> filter { ... }
    |> start { ... }
```

It puts the disposable front and center, which I like less than the pipe, but it separates the memory/lifespan management from the computations, which I like.

**Comment by neilpa** [comment]
`+=` also better conveys the append semantics.

**Comment by neilpa** [comment]
> It puts the disposable front and center

This may not be a bad thing. I've screwed up the lifetime management of disposables more than a few times.

**Comment by nomothetis** [comment]
Speaking of operators, we also use `-->` for both `sendNext` and `sendError` so calls look like `event --> sink` and `error  --> sink`. For complete symmetry we've also added `--|` as a prefix for `sendComplete` like so: ` — |`. We really like `-->`; the jury is still out on `--|`.

I'm happy to contribute a PR with some or all of these if you guys think it might be useful.

**Comment by neilpa** [comment]
> I'm happy to contribute a PR with some or all of these if you guys think it might be useful.

I also spun up an [experimental repo](https://github.com/neilpa/rex) for this sort of thing the other day. You're welcome to open a PR there. If not, I'll probably steal them :wink:

**Comment by jspahrsummers** [comment]
On a personal level, I like the idea of `+=` for this, but I worry about the perception it will create amongst our users. I think we should keep operator overloading and custom operators to a minimum.

@ReactiveCocoa/reactivecocoa Anyone else have thoughts?

**Comment by robrix** [comment]
`+=` is reminiscent of `ExtensibleCollectionType`. I think it’s appropriate usage.

**Comment by jspahrsummers** [comment]
@robrix Good point, but that can't really be used for single-element appending, can it?

**Comment by robrix** [comment]
Ah, no, not any more (used to in one of the 6.0betas I think?).

**Comment by robb** [comment]
`++` for `+=`
