### ISSUE TITLE
Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa

### ISSUE THREAD

**Issue by tomassliz** [ReactiveCocoa/ReactiveCocoa#2002]
I have Xcode 6.3.1. I created new iOS application, added this line in the `Cartfile`:
```
github "ReactiveCocoa/ReactiveCocoa" "v3.0-beta.4"
```

Then I started `carthage update --platform ios` with this output:

```
*** Fetching ReactiveCocoa
*** Fetching Result
*** Fetching Box
*** Downloading Box at "1.2.2"
*** Checking out ReactiveCocoa at "1c8b18751c4af1f3c6003077ff57bed80e184c3a"
*** Checking out Result at "0.4.2"
*** xcodebuild output can be found in /var/folders/3s/5fmt6_0d6zx7m316ynk2_4cr0000gn/T/carthage-xcodebuild.hcjzMu.log
*** Building scheme "Result-iOS" in Result.xcworkspace
*** Building scheme "ReactiveCocoa iOS" in ReactiveCocoa.xcworkspace
```

Then I added ReactiveCocoa.framework in `Linked Frameworks and Libraries` section in General settings for app target. When I try to run application I get this error:

```
dyld: Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Users/deny/Library/Developer/CoreSimulator/Devices/61B28989-B2AB-40B1-8D9F-DCDA5573C43A/data/Containers/Bundle/Application/2FE87141-1D2C-4C42-ABEC-1F0B55FA5A89/ReactiveApp.app/ReactiveApp
  Reason: image not found
```

Exists any way, how to use ReactiveCocoa with Carthage in swift projects?

**Comment by MichaelMcGuire** [comment]
Did you follow the steps listed in the [Carthage README](https://github.com/Carthage/Carthag) under ["If you're building for iOS"](https://github.com/Carthage/Carthage#if-youre-building-for-ios)?

**Comment by tomassliz** [comment]
Yes I followed them.

**Comment by MichaelMcGuire** [comment]
The dependencies for ReactiveCocoa need to be added as well, including Box and Result.

**Comment by tomassliz** [comment]
You're right. Thank you for help.

**Comment by KelvinJin** [comment]
I really want to know why the `copy-framework` step is necessary. In the README, they said it's only there because of the Apple Submission Bug. Why do I need it for development purpose at all. There must be something I'm missing.

**Comment by ikesyo** [comment]
@KelvinJin Embedding frameworks into an app bundle is necessary, without that the app crashes immediately as of the issue. But having both “Copy Files” phase and “Run script” phase of `carthage copy-framework` would be confusing. For that reason, we let the users to have only `copy-fraemwork` step for iOS/watchOS/tvOS apps.

**Comment by KelvinJin** [comment]
@ikesyo Thanks for the clarification. I think I kinda get the point now!:)
