### ISSUE TITLE
I saw your a book, And have a question, I hope accept your help.

### ISSUE THREAD

**Issue by mj230816** [ReactiveCocoa/ReactiveCocoa#2012]
in the book <functional reactive programming on iOS> of 47 page.
the code : 
-(void)prepareForReuse{

[super prepareForReuse];

[self.subscription dispose], self.subscription = nil; 
}

why does use an comma ,rather than an semicolon？

**Comment by JaviSoto** [comment]
In C, statements can be separated in the same line using a comma like that. Splitting into 2 lines with a semi-colon would be equivalent.
