### ISSUE TITLE
Unable to build v3.0-beta.4 with carthage: no such module 'Box'

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2013]
The non-verbose output can be found here: 
https://gist.github.com/memmons-ntst/201af8aa111b8b3e9ad7
 
The relevant part of the build log can be found here:
https://gist.github.com/memmons-ntst/d2b8fb9b3bd2bb4a13fc

The error I see in the build log is :
`Carthage/Checkouts/Result/Result/Result.swift:200:8: error: no such module 'Box'`

This is on a new install of xcode 6.3.1 (6D1002) running on OS 10.10.4.

In case this is a carthage specific issue, I filled one here:
https://github.com/Carthage/Carthage/issues/468

**Comment by jspahrsummers** [comment]
This is probably a Carthage issue. Are you able to import RAC, Result, and Box as subprojects successfully?

**Comment by memmons-ntst** [comment]
For some reason, Carthage refuses to fetch Box. Checkouts/Box is always empty. I finally manually fetched it and everything worked fine from there. I'm able to repro the problem 100% of the time though -- very strange. In any case, this seems like it is a Carthage problem or possibly a problem with Carthage running up against a rate-limit with github. 

I'll close this issue out.

**Comment by cdhoffmann** [comment]
I am having a similar issue, how do you manually fetch? @memmons-ntst
