### ISSUE TITLE
[RAC 3.0] Action.completed Signal

### ISSUE THREAD

**Issue by iv-mexx** [ReactiveCocoa/ReactiveCocoa#2014]
`Action` has the signals `values` and `errors`, sending all values/errors generated from applications of the Action.

Why is there no `completed` signal that sends an event every time one of the `SignalProducers` returned from apply() completes?

At first I thought this might be due to the lifetime of of the signals, but then I understood that the situation for the `errors` signal is similar and (i guess) for that reason does not send the errors as `Error` with `sendError` but as values with `sendNext`. 

### My potential application

My potential application for the `completed` signal would be the following simple Login View:
The viewModel has an `Action` that looks like that

```Swift
loginAction = Action { _ in
    return SignalProducer { (sink, _) in
        API.loginWitUsername(self.username.value, andPassword: self.password.value, withSuccess: {
                sink.put(Event.Completed)
            }, andFailure: { error in
                sink.put(Event.Error(Box(error)))
        })
    }
}
```

#### Working manual solution with `apply`

At first, I was starting the `loginAction` manually from the `IBAction` function:

```Swift
@IBAction func login(sender: UIButton) {
    viewModel.loginAction.apply(sender).start( next: { event in
        println("Next: \(event)")
    }, error: {error in
        println("Error: \(error)")
    }, completed: {
        println("Completed")
    })
}
```

Here I had the chance to subscribe to all Events.

#### With `CocoaAction`

Then I wanted to try the same thing without starting the action explicitely by using `CocoaAction`: 

```Swift
loginButtonAction = CocoaAction(viewModel.loginAction)
loginButton.addTarget(loginButtonAction, action: CocoaAction.selector, forControlEvents:.TouchUpInside)
```

With this approach, there is no direct access to the `SignalProducer` for the `loginAction`, but actually I don't care (I think?) because  its still possible to observe for errors via the `errors` signal of the action:

```Swift
viewModel.loginAction.errors.observe { error in
    println("Error: \(error)")
}
```

But then, there's no `completed` signal for the Action.
I would like to observe for the completion of the login (which is equivalent to a successful login):

```Swift
viewModel.loginAction.completed.observe {
    println("Login Successful")
}
```

Maybe I'm approaching the problem from the wrong angle anyway and theres a better way to achieve this?
I guess it would be possible by sending a `next` event at success before sending `completed`, but later there might be additional information about the login progress (the login might consist of several stages like _authenticate_, _load user data_, ...) that would be sent as `next` Events and sending the success of the login the same way feels a little bit off to me.

**Comment by jspahrsummers** [comment]
This is a very good point. Perhaps `Action` should instead expose an `events` signal that users can `materialize` or `filter` however they want?

/cc @ReactiveCocoa/reactivecocoa

**Comment by neilpa** [comment]
>  Perhaps Action should instead expose an events signal that users can materialize or filter however they want?

:+1: but I think you mean `dematerialize` since `Action` would be sourcing `Signal<Event<T, E>, NoError>` :wink:

**Comment by felixjendrusch** [comment]
Wouldn't something like `executionSignals` (or just `signals`) be more flexible because you can easily choose entire signals? `events` should still be easily constructible by flattening the materialized signals, right?

**Comment by neilpa** [comment]
> Wouldn't something like executionSignals (or just signals) be more flexible because you can easily choose entire signals?

I doubt it given that we've tried to avoid signal-of-signals given the potential pitfalls for missing events on inner signals. Do you have a specific use case in mind here?

**Comment by harrywincup** [comment]
@jspahrsummers Could you please give an example of how to filter `Completed` events as you suggest below?

> Perhaps Action should instead expose an events signal that users can materialize or filter however they want?

I thought maybe I could do something like

```swift
myAction.events |> filter { $0 == Event.Completed }
```

but I get an error: `'((Event<Void, NoError>), Event<T, E>)' is not convertible to 'ErrorType'`, which is a bit mysterious to me as a newbie

**Comment by ikesyo** [comment]
Since `func ==` for `Event` is defined with the `T: Equatable` constraint and the `Void` (`()`) is not an `Equatable`, you can not compare the two events. You should do as follows I think:

```swift
myAction.events |> filter { event in
    switch event {
    case .Completed:
        return true
    default:
        return false
    }
}
```

**Comment by harrywincup** [comment]
@ikesyo That makes perfect sense. Thank you for the quick explanation :)
