### ISSUE TITLE
How do you ignore errors on a SignalProducer?

### ISSUE THREAD

**Issue by KyleLeneau** [ReactiveCocoa/ReactiveCocoa#2018]
I am trying to ignore or replace my errors on a signal producer with no error. The ignoreValues inner variable should result in `SignalProducer<(), NoError>` but I am still ending up with `SignalProducer<(), E>`. This is causing an issue with the takeUntil which expects a `SignalProducer<(), NoError>` as it's  trigger.

    public func throttleSignalWhileInactive<T, E>(signalInput: SignalProducer<T, E>) -> SignalProducer<T, E> {
        let ignoreValues = signalInput
            |> map { _ in return () }
        
        return self.active.producer
            |> takeUntil(signalInput)
            |> combineLatestWith(signalInput)
    }

**Comment by ColinEberhardt** [comment]
I hit exactly the same issue, you cannot instantiate `NoError`, so `mapError` doesn't allow you to perform the required transformation.

As a quick fix I added the following operation:

```
public func toVoidSignal<T, E>(signal: Signal<T, E>) -> Signal<(), NoError> {
  return Signal {
    sink in
    signal.observe(SinkOf {
      event in
      switch event {
      case let .Next:
        sendNext(sink, ())
      default:
        break
      }
    })
  }
}
```

This takes a signal, and simply re-emits its next event.

It can be used as follows:

```
return self.active.producer
      |> takeUntil(signalInput |> toVoidSignal )
      |> combineLatestWith(signalInput)
```

Something a bit more generic, that doesn't ignore the various other events types would probably be more useful, perhaps a `suppressErrors` operation? Anyhow, at least the above code gets you moving!

**Comment by jspahrsummers** [comment]
You can use catch() for this.

**Comment by KyleLeneau** [comment]
@jspahrsummers I was trying for a bit to use catch() but couldn't get that working, would you mind elaborating on how you'd use it in the above? Thanks!

**Comment by ColinEberhardt** [comment]
@KyleLeneau - here's an example:

```
return self.rac_textSignal().toSignalProducer()
      |> map { $0 as! String }
      |> catch { _ in SignalProducer<String, NoError>.empty }
```

From here: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1979#issue-74021079

It's a bit cumbersome.

**Comment by NachoSoto** [comment]
It's cumbersome because it forces users to explicitly deal with errors.

**Comment by jspahrsummers** [comment]
@ColinEberhardt You can generally just say `.empty` and let type inferencing take care of the rest.

I agree with @NachoSoto—this level of explicitness is good, because it forces some thought about what an error should _do_. :wink:

**Comment by MichaelMcGuire** [comment]
Import to note also that the ignoring in the example given is only necessary because it's using the bridging `toSignalProducer` method.  Once (if) AppKit/UIKit extensions are recreated for RAC 3.0, it wouldn't be necessary as the `SignalProducer` for a text control would emit `NoError`.

**Comment by s0mmer** [comment]
Made a small helper for handling this:
```
public func ignoreError<T: Any, E: NSError>(signalProducer: SignalProducer<T, E>) -> SignalProducer<T, NoError> {
    return signalProducer
        |> catch { _ in
            let (innerProducer, _) = SignalProducer<T, NoError>.buffer()
            return innerProducer
        }
}
```

Then I'm able to just do:
`someProducer |> ignoreError`
