### ISSUE TITLE
How do I restart a SignalProducer after an error occurred?

### ISSUE THREAD

**Issue by sebastiangrail** [ReactiveCocoa/ReactiveCocoa#2019]
Given
- two `SignalProducer<String, NSError>`: `name` and `pw`
- a function `login: (String,String) -> SignalProducer<User, NoError>`
- a `SignalProducer<(), NoError>`: `tap`

I want to call `login` with every tap and observe `next` and `error`.

The following works until `login` errors out, after which I don't receive any more events.
```
combineLatest(name, pw)
    |> sampleOn(tap)
    |> flatMap(FlattenStrategy.Merge, login)
    |> start(next:println, error: println)
```

How can I handle the error and allow subsequent login attempts?

I tried `catch` as suggested in [this question](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2018)

**Comment by neilpa** [comment]
There's a [`retry`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/4a44d4675b49fbcbe108608b27cea1e3be4971d0/ReactiveCocoa/Swift/SignalProducer.swift#L689) operator for `SignalProducer`.

```swift
combineLatest(name, pw)
    |> sampleOn(tap)
    |> flatMap(FlattenStrategy.Merge, login)
    |> on(error: println)
    |> retry
    |> start(next: println)
```

However, you may also want to look at [`Action`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/4a44d4675b49fbcbe108608b27cea1e3be4971d0/ReactiveCocoa/Swift/Action.swift) which wraps a `SignalProducer` and exposes signals for next and error events.

**Comment by sebastiangrail** [comment]
Thanks for the quick answer @neilpa 
I ended up writing a `retryForever` function for now.
I'll take a look at `Action` as well.

**Comment by gerardo-navarro** [comment]
@sebastiangrail Could you post a generic `retryForever` function?
