### ISSUE TITLE
RAC3: Succinct MVVM login example 

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2022]
Still trying to wrap my head around RAC3 (without previous exposure to RAC). Given the simple login example below, I'm not understanding the following:

1. What is the correct way to bind the login button to the `requestAccessToSystemSignal()`? Is that even the correct approach or should an Action be used instead?
2. How can the login button be dynamically enabled only when both username and password have a value?
3. How can the loginViewController push to the next VC once verifySystemAccount succeeds?
4. How do we bubble the error back up to the UI if it fails? 
5. How do values pushed to the view model get propagated back to the UI? For example, if the user has logged in previously, then when the view model is initialized it will pull the username from `NSUserDefaults` and that should be displayed in the UI. I realize there currently isn't a two-way-binding mechanism in RAC3 yet, but what's the correct way of dealing with that until then? 
6. How to ensure that verifySystemAccount can't be called again until the previous one finishes?
``` Swift
public class LoginViewModel {
	let username = MutableProperty<String>("")
	let password = MutableProperty<String>("")
	let isLoggingIn = MutableProperty<Bool>(false)

	func requestAccessToSystemSignal() -> SignalProducer<VerifySystemAccountOutputPayload, NSError> {
		return SignalProducer { sink, _ in
			SecurityProvider.verifySystemAccountAsync(username: self.username.value, password:self.password.value,
				failure: {error in
					sendError(sink, error!)
				},
				success: {result in
					self.verifiedSystemAccount = result
					sendCompleted(sink)
				})
		}
	}
}

public class LoginViewController : UIViewController {

	private func bindViewModel() {
		viewModel.username <~ textSignal(usernameTextField!)
		viewModel.password <~ textSignal(passwordTextField!)
	}
}
```

**Comment by jspahrsummers** [comment]
`Action` can resolve most of those questions. I'd take a look at that first.

**Comment by RuiAAPeres** [comment]
@memmons-ntst you can find some examples [here](https://github.com/RuiAAPeres/RACNest)
