### ISSUE TITLE
New Reactive cocoa installation instruction

### ISSUE THREAD

**Issue by alexmaie** [ReactiveCocoa/ReactiveCocoa#2023]
Hey guys,

I wanted yesterday to update an older version of reactive cocoa that's running in an iOS 7 supported app. From what I read in the issue list, version 2.3.1 is the last version that will work with ios 7. Is this true? Also the libreactivecocoa.a file is missing. Whats the new way to integrate reactive cocoa into a project ?

**Comment by neilpa** [comment]
Closing, but re-open if that doesn't answer your question.
