### ISSUE TITLE
RAC3: Calling a function with closures from an Action?

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2025]
Why does Swift insist `Variable 'self.action' used before being initialized` for the following?
```Swift
let action : Action<String, Bool, NSError>
init () {
   action = Action<String, Bool, NSError>(enabledIf:self._loginInputValid) { _ in
      return SignalProducer { sink, _ in
         SecurityProvider.verifySystemAccountAsync(/* some params*/,
            failure: {error in sendError(sink, error!)},
            success: {result in sendNext(sink, true); sendCompleted(sink)})
      }
   }
}
```
Whereas using this code compiles fine:
```Swift
action = Action<String, Bool, NSError>(enabledIf:_loginInputValid) { _ in
   return SignalProducer { sink, _ in
      sendNext(sink, true)
      sendCompleted(sink)
   }
}
```

**Comment by memmons-ntst** [comment]
If I change the `action` to a `var` and initialize `action` with the second example and then reinitialize it with the first example, Xcode no longer complains. Obviously that approach is utterly dumb though, so hoping for some input on mollifying Xcode.

**Comment by MichaelMcGuire** [comment]
The following is compiling fine for me:

```
class ViewModel {
    let action : Action<String, Bool, NSError>
    let _loginInputValid = MutableProperty<Bool>(false)
    
    init() {
        action = Action<String, Bool, NSError>(enabledIf:self._loginInputValid) { (string: String) in
            return SignalProducer { sink, _ in
                SecurityProvider.verifySystemAccountAsync(
                    failure: { error in sendError(sink, error)},
                    success: { result in sendNext(sink, true); sendCompleted(sink)})
            }
        }
    }
}

class SecurityProvider {
    static func verifySystemAccountAsync(#failure: (NSError) -> (), success: (Bool) -> ()) {
        
    }
}
```

It probably has something to do with the `/* some params */` you are leaving out.

**Comment by memmons-ntst** [comment]
@MichaelMcGuire Hrm. The actual func signature is fairly pedestrian:
`public class func verifySystemAccountAsync(inputPayload: Payload, sender: Sender, failure onError: (NSError? -> ())? = nil, success onSuccess : (VerifySystemAccountOutputPayload? -> ())? = nil)`

**Comment by jspahrsummers** [comment]
If you are trying to initialize `Action` with a closure that references `self`, however deeply, the compiler can't prove that `self` won't be used before the assignment finishes. Since Swift disallows partially-initialized objects, it just prevents it from compiling instead.

**Comment by MichaelMcGuire** [comment]
Yep, my guess is that you're referring to `self` when setting the `inputPayload` or `sender` parameters.  

I've been in the habit of using `lazy` to declare the `Action`s in my view models.  I have seen some negativity around `lazy` for good reasons, but I don't think it applies to how I'm using it.  So try something like this:

```
    lazy let action = { 
        return Action<String, Bool, NSError>(enabledIf:self._loginInputValid) { (string: String) in
            return SignalProducer { sink, _ in
                SecurityProvider.verifySystemAccountAsync(
                    failure: { error in sendError(sink, error)},
                    success: { result in sendNext(sink, true); sendCompleted(sink)})
                }
            }
        }
    }()
```
(sorry if there are syntax errors, not actually trying to compile this)

Not sure if anyone out there has any better suggestions on initializing `Action`s in view models.

**Comment by neilpa** [comment]
Closing, but re-open if that doesn't answer your question.
