### ISSUE TITLE
 A question about the name of the stream

### ISSUE THREAD

**Issue by CodingEverydayForFuture** [ReactiveCocoa/ReactiveCocoa#2027]
__block  NSInteger num = 0;
    @weakify(self);
    _signInButton.rac_command = [[RACCommand alloc] initWithEnabled:[RACSignal combineLatest:@[_usernameTextField.rac_textSignal,_passwordTextField.rac_textSignal] reduce:^(NSString *username,NSString *password){
        return @(username.length > 12 && password.length > 6);
    }] signalBlock:^RACSignal *(id input) {
        num ++;
        RACSignal *textSignal = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
             [subscriber sendNext:@"click"];
             [subscriber sendCompleted];
            return nil;
        }];
                
        textSignal.name = [NSString stringWithFormat:@"clickNum:%ld",num];
        return textSignal;
    }];
    [_signInButton.rac_command.executionSignals subscribeNext:^(RACSignal *clickSignal) {
        
        NSLog(@"The current signal:%@",clickSignal.name);
        [clickSignal subscribeNext:^(id value) {
            NSLog(@"____________  %@",value);
        }];
    }];
I want to go to test the name of the racsignal,so I write like this 
 textSignal.name = [NSString stringWithFormat:@"clickNum:%ld",num];
What I want is that  
NSLog(@"The current signal:%@",clickSignal.name);
But the output name here is not what I writed.
Here,clickSignal.name is nil.Why?

**Comment by jspahrsummers** [comment]
You need to set the environment variable `RAC_DEBUG_SIGNAL_NAMES=1` in order for names to be automatically generated. It's behind an environment variable because of the performance cost.
