### ISSUE TITLE
RAC 3: Why does PropertyType have a SignalProducer instead of a Signal?

### ISSUE THREAD

**Issue by jjoelson** [ReactiveCocoa/ReactiveCocoa#2030]
The value of a property seems to me to be a good example of a "hot" signal. What was the reasoning behind giving `PropertyType` a `SignalProducer` rather than a `Signal`?

**Comment by neilpa** [comment]
With `SignalProducer` you can defer evaluation of the contained value until the first subscription. That's not easily done if you were using a `Signal`.

**Comment by jjoelson** [comment]
@neilpa that makes sense. It also just occurred to me that the property sends the current value upon subscription, which means it's actually a cold signal. You wouldn't want the current value re-sent to all observers with each new subscription!

**Comment by neilpa** [comment]
@jjoelson Exactly. If you're familiar with RAC 2 it's essentially `-replayLast` but with more flexibility since you can compute the initial value immediately or on first subscription.
