### ISSUE TITLE
RAC 3: UI DynamicProperty being updated on a background thread

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2031]
So, unfortunately I'm unable to reproduce this problem with a simple test project, but it is 100% reproducible in my working project. A button that is dynamically disabled/enabled based on a signal is being updated on a background thread. As a result it takes some amount of time (~8 seconds) before the UI is updated to reflect the new button state.

 I have a view controller with a property defined as:
```Swift
   private lazy var buttonEnabled: DynamicProperty = {
       return DynamicProperty(object: self.loginButton, keyPath: "enabled")
    }()
```
The property is bound to an action via
```Swift
   buttonEnabled <~ viewModel.loginAction.enabled.producer |> map { $0 as AnyObject }
```
The login action looks like this -- notice the enabledIf:
```Swift
   loginAction = Action<String, Bool, NSError>(enabledIf:self._loginInputValid) { _ in
      return SignalProducer { sink, _ in
         SecurityProvider.verifySystemAccountAsync(/* unimportant params */,
			failure: {error in sendError(sink, error!)},
			success: {sendCompleted(sink)})
         }
      }
```
`_loginInputValid` is setup as follows:
```Swift
   var loginInputValid: PropertyOf<Bool> { return PropertyOf(_loginInputValid)}
   private let _loginInputValid = MutableProperty(true)
   ...
   let notEmptyValidation: Signal<String, NoError> -> Signal<Bool, NoError> = map { string in
      return  count(string) > 0
   }
   combineLatest(username.producer |> notEmptyValidation, 
                 password.producer |> notEmptyValidation, 
                 scope.producer |> notEmptyValidation)
   |> map({username, password, scope in return username && password && scope})
   |> start(next: {valid in self._loginInputValid.value = valid})

```

`verifySystemAccountAsync` does some http requests and json parsing. The closure will come back on a background thread. 

I realize this is a pretty crappy bug report since I can't repro it in a simple project, but there ya go.

**Comment by jspahrsummers** [comment]
Property bindings do not automatically hop threads for you. You'll need to use an operator like `observeOn` to ensure the proper threading semantics.

**Comment by memmons-ntst** [comment]
Ugh. For some reason my assumption was that `DynamicProperty` was more like a `DynamicUIProperty` that was made particularly for observing UI properties. So dumb.

I'll show myself out. Thank you @jspahrsummers

**Comment by jspahrsummers** [comment]
No problem at all!
