### ISSUE TITLE
RAC 3: Action, observing errors and completions

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2033]
If an action fails, I present a `UIAlertController` which is handled in the VCs `showError()` func. Is this the correct way to watch for errors on an action and ensure `showError()` happens on the main thread?
```Swift
viewModel.loginAction.errors.observe(next: {error in self.showError(error)})
viewModel.loginAction.errors
|> observeOn(UIScheduler())
```
In addition once an action completes, how do you observe that? My naive approach, `viewModel.loginAction.values.observe(next: { value in println("\(value)") })`, seems wrong.

**Comment by neilpa** [comment]
Right now the first line subscribes to the errors signal directly. The second expression creates a new signal (that you're not doing anything with) whose events would be delivered on the main thread. This has no effect on the previous lines subscription. Instead you need to combine these two things

```swift
viewModel.loginAction.errors
    |> observeOn(UIScheduler())
    |> observe(next: {error in self.showError(error)})
```

> In addition once an action completes, how do you observe that?

You can't currently but #2014 exists to address that.

**Comment by neilpa** [comment]
#2038 added a unified events signal to `Action`.
