### ISSUE TITLE
Question on v3.0 Binary Compatibility

### ISSUE THREAD

**Issue by priteshshah1983** [ReactiveCocoa/ReactiveCocoa#2034]
After reading some articles online, I got the impression that  warns against binary frameworks written in Swift.

Per https://developer.apple.com/swift/blog/?id=2

> ### Binary Compatibility and Frameworks
While your app’s runtime compatibility is ensured, the Swift language itself will continue to evolve, and the binary interface will also change. To be safe, all components of your app should be built with the same version of Xcode and the Swift compiler to ensure that they work together. 
This means that frameworks need to be managed carefully. For instance, if your project uses frameworks to share code with an embedded extension, you will want to build the frameworks, app, and extensions together. **It would be dangerous to rely upon binary frameworks that use Swift — especially from third parties. As Swift changes, those frameworks will be incompatible with the rest of your app.** When the binary interface stabilizes in a year or two, the Swift runtime will become part of the host OS and this limitation will no longer exist.

It would be great to get some more thoughts on this.

**Comment by neilpa** [comment]
There was a previous discussion of this in Carthage/Carthage#433

**Comment by jspahrsummers** [comment]
Yeah, basically the takeaway is that RAC will break binary compatibility whenever Swift does, and That's Okay™.

**Comment by priteshshah1983** [comment]
Thanks!
