### ISSUE TITLE
RAC3: Deadlock in `switchToLatest`

### ISSUE THREAD

**Issue by stevebrambilla** [ReactiveCocoa/ReactiveCocoa#2035]
When interrupting a signal where `switchToLatest` is used, the atomic `LatestState` can be modified while the lock is already held. I've narrowed it down to a simple test case:

```swift
SignalProducer<Int, NoError>(value: 1)
	|> flatMap(.Latest) { _ in SignalProducer(value: 10) }
	|> take(1)
	|> wait
```

The `LatestState` lock is held when sending the `Next` event, but that same event causes the signal to be disposed by `take(1)`. The `LatestState` is then modified when processing the `Interrupted` event from the disposal, which causes the deadlock.

I'm not 100% sure, but maybe `sink.put(event)` can be done outside of the lock after validating that `isLatestIncompleteSignal(innerSignal)` succeeds?

**Comment by jspahrsummers** [comment]
Thanks for the bug report! I've confirmed this (with the help of your test case) and I'm working on a fix right now.
