### ISSUE TITLE
Add more typealiases

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#2043]
Given a `SignalProducer<T, E>`, there's no easy way to get its associated `Signal` type, or even sink type IIRC. We should add some public typealiases to make stuff like this easier.

Same thing probably applies to `Action`, `PropertyType`, and others.

**Comment by neilpa** [comment]
I started looking at this but I'm not sure it makes things easier. Most contexts require fully specified types and I think using `Signal<T, E>` directly is better than `SignalProducer<T, E>.Signal`. The only place I see an improvement is when already `typealias`ing the producer so you can do `MyProducer.Signal`. Maybe that's enough of an argument in favor of this change.

**Comment by jspahrsummers** [comment]
Yeah, this came up when I wanted to refer to `BuildSchemeProducer.Signal` in Carthage. That one's a PITA to write out.

**Comment by ikesyo** [comment]
I'm digging into it, but `typealias Signal = Signal<T, E>` conflicts with the `class Signal` type. The compiler complains that `Type alias 'Signal' circularly references itself` and `Cannot specialize non-generic type '<<error type>>'`.

Alternatives: `ProducedSignal` or `Result`?

**Comment by jspahrsummers** [comment]
`ProducedSignal` sounds good. :+1:
