### ISSUE TITLE
Tuple of signals: is this the right design?

### ISSUE THREAD

**Issue by StatusReport** [ReactiveCocoa/ReactiveCocoa#2048]
(Syntax is for RAC 2 but since this is a design question it refers to RAC 3 as well)

I'm working on an API that retrieves images from a remote location. The retrieved image can be modified on the server, and there's an notification that is sent after such modification, so the client can download the new image and refresh the view.

If only the image needs to be provided, the API is quite clear: just return a `RACSignal` of images and send the new image upon a change.

The issue is that I require to send a progress signal as well, that, for each fetch, returns a float in `[0, 1]` with the current download progress.

The best API I came up with until now is to return a `RACSignal` of `RACTuple`s, where each tuple contains a signal which sends a single image once it's fetched and a signal which sends the progress. The issues with this approach is that it forces me to subscribe to each new sent signal and that signal handling is nested, such as:

```
[[imageFetcher fetchImage:...] subscribeNext:^(RACTuple *signals) {
  // Subscribe to the signals inside the tuple.
}];
```

To generalize: I have a method that runs a long operation with trackable progress, and want to push updates both about the progress and the result once available.

Suggestions are welcomed!

**Comment by jjoelson** [comment]
In Swift, this is the perfect use case for an enumeration with associated values. So each value sent along the signal will either be a ProgressUpdate with an associated Double representing the progress, or a DownloadCompletion with an associated UIImage. 

This pattern would not be quite so clean in Objective-C, especially given the lack of generics which makes RACSignal difficult enough to use already, so maybe a tuple of signals makes more sense there.

**Comment by StatusReport** [comment]
Well, I'm not sure that encapsulating two different types in an enum is the right solution. This is fine for objects that are being sent once (say, `data` or `error` with network requests). Here a stronger contract is needed regarding which objects are sent when. For example, you'd need to explain to the client that for each fetch result, you send Double values, and only when it reaches `1` a `UIImage` is sent.
I was hoping for a better contract that is defined by interfaces and not words.

Another issue is the fact that you multiplex multiple values to a single signal, so demultiplexing will be required near the subscriber, since in all usage scenarios you'd want to bind a progress bar to the progress and an image view to the image. So you'll need to create two signals from the original signal using `filter:`.

**Comment by jjoelson** [comment]
Well I'm not sure how using separate signals would convey the relationship between the progress and the final image any better, and at the end of the day you have a progress display view which only cares about progress and an image view which only cares about the image, so I don't think it's essential for the client to be aware of the exact order events will come. As for demultiplexing, the Swift compiler will prevent you from ever screwing it up, though I see why that would be a concern in Objective-C. 

For what it's worth, I've tried both ways and found that dealing with one signal is easier on both the implementation and the subscription side. Hopefully others will chime in with their experience dealing with progress updates.

**Comment by StatusReport** [comment]
Thanks @jjoelson. There are many examples of how to use RAC with progress indicator while an operation is in progress (which is easy, since you only need to derive an `inProgress` signal from the signal that returns that operation's result), but I haven't found any reference to dealing with progress updates that contain a value.

**Comment by jspahrsummers** [comment]
I agree that using an `enum` is the ideal solution with the Swift API.

In Objective-C, it's gonna get ugly no matter what, because you can't easily create two cold signals that share the same work.

**Comment by StatusReport** [comment]
Thanks for chiming in @jspahrsummers! I assume I'll have to either send multiple object types over the same signal and use `isKindOfClass:` near the subscriber, or wrap this with some kind of value type that will hold both values :unamused:
