### ISSUE TITLE
Deadlock using a MutableProperty in a view controller

### ISSUE THREAD

**Issue by MichaelMcGuire** [ReactiveCocoa/ReactiveCocoa#2050]
Due to the change in #2042, I'm hitting a deadlock when using a `MutableProperty` in a view controller.   My setup:

1) In my view controller, I have a `var data = MutableProperty<[MyViewModel]?>(nil)`
2) In `viewDidLoad`, I bind the values from an `Action` to the property with `data <~ viewModel.myAction.values`
3) Also in `viewDidLoad`, right after step 2, I use the mutable property's producer to reload the collection view that is reading my `data` property: `data.producer.start(next: { _ in self.collectionView.reloadData() })`
4) And finally in `viewDidLoad`, right step 3, I invoke the `Action` on my view model: `viewModel.myAction.apply(NSDate())`

For ease of reading, here are steps 2-4:

```
    data <~ viewModel.myAction.values
    data.producer.start(next: { _ in
        self.collectionView.reloadData()
    })
    viewModel.myAction.apply(NSDate())
```

The problem is that in the `UICollectionViewDataSource` methods, I read from the `data` property using the `value` property.  Because I'm inside of the event delivery block higher up the chain, I'm getting the deadlock now that locks are not recursive.  The first workaround I can think of is to not use the `MutableProperty` and instead copy the values as they arrive from the action into variables and use those in the data source methods instead.  I guess that works but really feels stateful.  I'm curious if there any other suggestions for how to structure loading of data from a view model inside of a view controller acting as a data source?

**Comment by neilpa** [comment]
This is probably due to the use of `first` in `MutableProperty`'s getter. I'll see if I can narrow this down to a quick repro.

**Comment by neilpa** [comment]
Yea, this'll do the trick

```swift
let (producer, sink) = SignalProducer<Int, NoError>.buffer()
var property = MutableProperty(0)

property <~ producer
property.producer.start(next: { _ in
    println(property.value)
})

sendNext(sink, 10)
```

**Comment by MichaelMcGuire** [comment]
@neilpa Sorry yes, had already figured that out, but was wondering if this is "by design" at this point.  If the implementation of `.value` can be changed to support using it within the block, that'd be great.

**Comment by neilpa** [comment]
I'm looking into a fix. There shouldn't be any "side-effects" when reading the value of a property.
