### ISSUE TITLE
What is the point of SinkOf

### ISSUE THREAD

**Issue by CosynPa** [ReactiveCocoa/ReactiveCocoa#2053]
Since `SinkOf<T>` is just a function `T -> Void`, why don't just use the plain function?

**Comment by kastiglione** [comment]
`SinkOf` is a standard Swift type. It conforms to the protocol `SinkType`, which says:

> Useful mainly when the optimizer's ability to specialize generics outstrips its ability to
specialize ordinary closures. For example, you may find that instead of:
>
> `func f(g: (X)->Void) { ... g(a) ...}`
>
> the following generates better code:
>
> `func f<T: Sink where T.Element == X>(g: T) { ... g.put(a) ...}`

See http://swiftdoc.org/protocol/SinkType/

**Comment by CosynPa** [comment]
@kastiglione Why is the later code better? Because it use generic type?

**Comment by kastiglione** [comment]
I don't have an answer other than the compiler produces more optimal code, as the docs say. If anyone has more info here I'd love to learn more too.

**Comment by jspahrsummers** [comment]
At one point, our observers were `SinkType`s _plus_ some special sauce. That's since changed, so I guess we could conceivably use plain functions now.

I'd be interested in a pull request trying it out, if anyone wants to give that a shot.

**Comment by brow** [comment]
Per @neilpa's [comment](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2101#issuecomment-111848421) on #2101, this should probably be moved out of the 3.0 milestone.

Is there anything keeping us from creating a milestone for the API-breaking release that will support Swift 2? Would it be designated 4.0?

**Comment by jspahrsummers** [comment]
@brow A separate milestone sounds like a good idea. Maybe just title it “Swift 2,” since it may be incorporated into RAC 3.0 if Swift 2 hits production before we've shipped officially.

**Comment by neilpa** [comment]
I've added a milestone and added current issues and PRs to it.

**Comment by brow** [comment]
Nice. Shall we close this now that #2102 is merged to `swift2`, or do we prefer to close only once the change is in a release?

**Comment by jspahrsummers** [comment]
We can close this out, so the milestone progress is accurate.
