### ISSUE TITLE
RAC 3 'on' is not being called on signal producer

### ISSUE THREAD

**Issue by LightD** [ReactiveCocoa/ReactiveCocoa#2060]
I wanna do something (in a different class) when a signalproducer completed.. the only thing I've seen that makes sense to use is the `on` operator, but it's never being called.. here's my code:

``` swift
func startProgress<T,E: ErrorType>(view: UIView, producer: SignalProducer<T,E>) {
        producer |> on(completed: {
            self.hideProgress()
            }, error: { (error: E) in
                self.hideProgress()
            }, terminated: {
                self.hideProgress()
        })   
// CODE TO ADD PROGRESS VIEW AND STUFF
  }
```
and then in my view controller I'm calling that one using the following code:
``` swift
@IBAction func loginBtnPressed(sender: AnyObject) {
        let someWork = SignalProducer<Bool, NoError> { sinkOfObservers, disposable in
            Utils.delay(1) {
                sendNext(sinkOfObservers, true)
                sendCompleted(sinkOfObservers) // THIS IS BEING CALLED
            }
            return // without this, the swift compiler breaks.. is there anything special I should be returning here?
        }
        
        ProgressManager.sharedInstance.startProgress(self.view, producer: someWork)
        someWork |> on( completed: { // just for testing
            Log.debug?.message("completed the signal")  // THIS IS NEVER CALLED
        })
        someWork |> start( completed: {
            Log.debug?.message("completed the signal")  // THIS IS CALLED CORRECTLY
        })

    }

```

I'm not sure what is going wrong, but the `|> on` is never called on neither any of the above.. can someone shed some light? 
What I want to achieve is: The progress manager should get a signal and it should know when the signal completed so it can automatically hide itself from the view..

**Comment by neilpa** [comment]
`on` wraps a `SignalProducer` and returns a new one that you need to use. It doesn't modify the existing one.

**Comment by LightD** [comment]
grrr.. then how can I have multiple subscribers? or perform side effects? can you suggest something please please pwease *_*

**Comment by neilpa** [comment]
One possibility is returning the new `SignalProducer` from `startProgress` and using that since it will have the effects "attached" to it. You might also want to experiment with [`Action`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/c3f9b4729c078d395e638819bdfc8889b9c9d956/ReactiveCocoa/Swift/Action.swift)

**Comment by LightD** [comment]
well.. I ended up wrapping the passed signal to the progress manager with an `Action`, and then calling start on that.. but this is confusing.. why would `on` create a new signal? shouldn't it just observe? because by right, `start` method on `SignalProducer` will fire the signal, so if you call start again, it will fire it again, so you can't observe one `SignalProducer` in 2 different locations.. am I right? 
There should be a way to observe the `Producer` in 2 different places, something that I haven't caught in the framework.. something that naturally should be the `on` operator..
Please correct me if I'm wrong..

**Comment by ikesyo** [comment]
@LightD It seems to me that what you want is `SignalProducer.startWithSignal()` for multiple observers. See also [the section for it in CHANGELOG](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/a96af8c2c06f9e07ac93a0c0dcf9bf10abe0075a/CHANGELOG.md#using-startwithsignal-instead-of-multicasting).

**Comment by jspahrsummers** [comment]
> why would `on` create a new signal? shouldn't it just observe? 

`on`, like almost every other operator in the framework, _transforms_ the signal, injecting the given event callbacks into the stream.

As @ikesyo suggests, `startWithSignal` and `observe` will allow you to add multiple handlers without this transformation behavior.

**Comment by LightD** [comment]
Well, I agree, `SignalProducer.startWithSignal()` might do the job, coz it returns a signal in a block.. so I gave it a shot, and here's the result:
a `Signal` only comes after the execution of the `startWithSignal` block.. but I wanna observe in different classes (i.e: `ProgressManager`), and I couldn't do that because the block didn't return immediately.. why not "return" a pair of `Signal` and `Disposable` instead of passing them back in a closure? It's not easy/straightforward to assign the signal passed in the closure to a variable and pass that to different classes as parameters.....
Also, since *Basic Operators* document is in progress.. the document says use the operator `on` to inject side effects on `SignalProducer` which alone is not true.. to actually receive the events on with the `on` operator, you need to call `start`.. that's the only way that worked.. so I believe the basic operators document should be modified accordingly.......... 

I really only want to perform something completely separate from the signal modification when I receive the `completed` event, that's all, I just wanna receive the completed event, `on` should do it, but it didn't.. and wrapping it in an action did it, but that feels like a hack.. something is missing somewhere, I'm not sure what, but it doesn't make sense to me that `on` doesn't pass the events unless I `start` after `on`........... :disappointed:

**Comment by neilpa** [comment]
> why not "return" a pair of Signal and Disposable instead of passing them back in a closure?

Because this is the only way to guarantee that you can observe the events on the signal before it starts sending events. As a return value there's a potential race that the signal starts sending events before you've actually begun observing.

> to actually receive the events on with the on operator, you need to call start.. 

This is by design. `SignalProducer` represents deferred work that must be explicitly started to do something. The `on` operator is a way to attach additional work/effects to the transformed signal.

**Comment by LightD** [comment]
Alright, fair enough. then the [documentation](https://github.com/iv-mexx/ReactiveCocoa/blob/feature/operators/Documentation/BasicOperators.md#injecting-effects) should be modified, don't you think?

**Comment by neilpa** [comment]
> Alright, fair enough. then the documentation should be modified, don't you think?

No, signal producers are value types and can't be modified. The `on` operator behaves exactly as expected and just like all other operators by returning a new producer.

**Comment by LightD** [comment]
but.... butt.. *_* 
ok here's the what the "in progress `Basic Operators` document" states:
> Side effects can be injected on a SignalProducer with the on operator without actually subscribing to it.

``` swift
producer
    |> on(started: {
            println("Started")
        }, event: { event in
            println("Event: \(event)")
        }, error: { error in
            println("Error: \(error)")
        }, completed: {
            println("Completed")
        }, interrupted: {
            println("Interrupted")
        }, terminated: {
            println("Terminated")
        }, disposed: {
            println("Disposed")
        }, next: { next in
            println("Next: \(next)")
        })
```
which, on it's own, is NOT true (this won't print anything on the console..), unless you either chain it with other operators, or `start` after the `|> on` operator... am I understanding this wrong? I just believe the documentation would be confusing at the moment (especially for first time comers).. I can move the discussion to the pull request if you wish..

**Comment by neilpa** [comment]
> unless you either chain it with other operators, or start after the |> on operator

Not exactly. Chaining with other operators just create transformed producers in the exact same way that `on` works. The above expression is returning a new `SignalProducer` that isn't captured.

```swift
let mapped = producer
    |> map { println($0) }
```

This also doesn't print anything, we've just created a new SignalProducer. The new `mapped` producer still needs to be `start`ed for anything to happen.

**Comment by LightD** [comment]
hmmm ok, that's a great explanation right there, thnx a lot!!
But here's the thing, all that you've mentioned is amazing, but I don't think it's really clear in the document.. I really think it should be slightly clarified.. maybe in the framework overview? I'm not sure where this needs to be mentioned, but what you just explained must be out there somewhere to clear any confusion..

**Comment by neilpa** [comment]
> But here's the thing, all that you've mentioned is amazing, but I don't think it's really clear in the document.. I really think it should be slightly clarified

Yes, we're working on that but this is still a beta library and [labeled as such](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v3.0-beta.7). You can't rely on perfect docs in that case and may need to [dig into the source](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/ad1fd34561d3f2f42e0feb420ace5de321906b78/ReactiveCocoa/Swift/SignalProducer.swift#L355) if things don't work the way you expect.

**Comment by LightD** [comment]
:+1: agreed! I wanted to point it out on the [pull request](https://github.com/iv-mexx/ReactiveCocoa/blob/feature/operators/Documentation/BasicOperators.md#injecting-effects) but I didn't wanna move this discussion there and over crowd that, so I sticked to the discussion here.. 
then I think it's safe to close this issue? I wish I can help writing the documentation :disappointed:, best of luck :smile:

**Comment by neilpa** [comment]
I've added a note to that PR to address this.
