### ISSUE TITLE
RAC 3.0: Observing MutableProperty without side-effects

### ISSUE THREAD

**Issue by patr1ck** [ReactiveCocoa/ReactiveCocoa#2061]
It seems reasonable to want to observe a MutableProperty value as a hot signal instead of having to call start() on it's producer, so that you can avoid triggering side-effects. I can simulate this (I think) by doing something like this:

```swift
        userImage.producer
            |> skip(1)
            |> start(next: {
                if let image = $0 { saveImageInCache(image, accountID: self.userAccountID) }
        })
```

But this feels kind of wrong – is there a better way to do this? Maybe I missed an easy way to convert a SignalProducer to a Signal? I noticed MutableProperty does have an `observer: Signal` property, but it's private, and I imagine with good reason.

I'm new to RAC, so I apologize in advance if this should be obvious, or is a crazy idea for other reasons.

**Comment by neilpa** [comment]
If you need to drive the cache from changes on the property, then this seems like a reasonable approach. The side-effect of the producer on a `MutableProperty` is just the subscription itself. It's more-or-less a hot signal but modeled as a producer so the current value can be sent immediately on subscription.

**Comment by neilpa** [comment]
> I noticed MutableProperty does have an `observer: Signal` property, but it's private, and I imagine with good reason.

IMO, that's a bit misnamed. That's the sink which maintains all the active subscriptions, forwarding to the real observers when an event is sent.

**Comment by patr1ck** [comment]
Cool, thank you! 

I may refactor my code to not load the cache when setting the property (and do it somewhere else) since on second thought it seems that structure might not be sound. Good to know I'm not abusing the framework too badly though. Thanks again!
