### ISSUE TITLE
Convert Signal To SignalProducer

### ISSUE THREAD

**Issue by va3093** [ReactiveCocoa/ReactiveCocoa#2065]
Hey Guys, Love the work on RAC 3 so far. I have been trying it out and got stuck on the following. 

So I am using a 'Hot' Signal from the ```Action.values``` property but would like to create a ```SignalProducer``` that returns the values from the hot signal but also apply some side effects when observed by observers. 

In RAC 2.x I would do something like this...

```
return RACSignal.createSignal({ [weak self](subscriber: RACSubscriber!) -> RACDisposable! in
	/*
	Do some stuff here	
    */
       subscriber.sendNext(hotSignal)
	return RACDisposable()
}).switchToLatest()
```

Is there a way to do this currently. Any feedback would be appreciated. 

Villy

**Comment by ikesyo** [comment]
Hi, thank you for trying the library! Is the following what you are looking for?

```swift
return SignalProducer { [weak self] observer, disposable in
    // Do some stuff here...
    disposable += self?.someAction.values.observe(observer)
}
```

**Comment by va3093** [comment]
Great!. Thank you. That looks good to me. 

Keep up the amazing work!
