### ISSUE TITLE
Universal Framework

### ISSUE THREAD

**Issue by me2clients** [ReactiveCocoa/ReactiveCocoa#2072]
I am trying to create a universal framework or RAC to integrate in my project as ReactiveCocoa.framework but getting different type of compilation or runtime error. 
Can you please upload universal framework file that I can use instead of integrating the RAC project file in my project?

Thanks In Advance.

Nishant

**Comment by jspahrsummers** [comment]
Recent releases all contain a `ReactiveCocoa.framework.zip` archive, which contains a universal iOS framework.

**Comment by me2clients** [comment]
Can you provide me a path to download it ? I have clone the repository and downloaded all submodules but did not get it.

**Comment by NachoSoto** [comment]
You can find them in the [**releases**](https://github.com/ReactiveCocoa/ReactiveCocoa/releases) section of this repo.

**Comment by me2clients** [comment]
Ok, Thanks!

**Comment by me2clients** [comment]
I am getting this error:
dyld: Library not loaded: @rpath/Box.framework/Box
  Referenced from: /private/var/mobile/Containers/Bundle/Application/F2CD2C66-7402-4A0D-ACE8-3F270299A581/Flio.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Reason: image not found

**Comment by jspahrsummers** [comment]
ReactiveCocoa 3 is in beta, and not recommended for production use (as the release notes indicate).

If you really want to use it anyways, you'll also to download and link its dependencies, [Result](https://github.com/antitypical/Result) and [Box](https://github.com/robrix/Box).

You may want to use a dependency manager like [Carthage](https://github.com/Carthage/Carthage) or [CocoaPods](https://cocoapods.org) to do these steps for you.

**Comment by me2clients** [comment]
![screen shot 2015-06-07 at 4 32 40 am](https://cloud.githubusercontent.com/assets/1165864/8021847/5e51df86-0cce-11e5-8c39-53af4518e91b.png)
I am getting attached error while submitting to the apple with V2.5.

**Comment by jspahrsummers** [comment]
Sounds like [rdar://19209161](http://www.openradar.me/radar?id=6409498411401216).

I guess you'll have to use subprojects, then, or else a dependency manager. :confused:

**Comment by me2clients** [comment]
I think there is another issue also. When I downloaded the source code for Version 2.5, it shows both scheme is targeted for OSX platform. Can you please advise ? 
![screen shot 2015-06-07 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/1165864/8023581/e8218396-0d2e-11e5-820c-519138d227b7.png)

**Comment by me2clients** [comment]
Hello Justin,

May I have the update on this ?

Regards,
Nishant

**Comment by me2clients** [comment]
I fixed it. Thanks.
