### ISSUE TITLE
What's the plan for UIKit extensions in v3.0?

### ISSUE THREAD

**Issue by MarcoSero** [ReactiveCocoa/ReactiveCocoa#2074]
I've started using v3.0 and I like the direction is going, but the first thing I immediately noticed was the lack of UIKit extensions.
Is there a plan to add them before 3.0 goes out of beta?

**Comment by neilpa** [comment]
Not for the initial 3.0 release since these can safely be added later. For now you'll have to rely on the Objective-C bridging.

**Comment by MarcoSero** [comment]
Thanks! :+1:
