### ISSUE TITLE
Proposal: revive debounce (the throttle of old)

### ISSUE THREAD

**Issue by heiberg** [ReactiveCocoa/ReactiveCocoa#2075]
The new `throttle` in RAC 3 has a behavior which matches its name better. But sometimes the old RAC 2 `throttle` behavior is just what you need. 

[This issue](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1348) raised the question a while back, and it was suggested that a new issue be opened if anyone wanted a `debounce`-like operation. 

I'd like to upvote the idea.

Example real-world use cases:
- Hide the page control for a scroll view when the user hasn't scrolled for a while.
- Postpone kicking off a slow network search operation until the user has stopped typing in the search field.

**Comment by neilpa** [comment]
I'm in favor of this operator, too many real world scenarios where it's useful. However, I'd want to wait until after a proper 3.0 release since this is additive and we're basically locked on the initial API.

**Comment by jspahrsummers** [comment]
Agreed with @neilpa. :zap:

**Comment by carlosefonseca** [comment]
That would be great! Also updating the docs would be sweet too: https://github.com/ReactiveCocoa/ReactiveCocoa/tree/swift2#throttling-requests :)

**Comment by natestedman** [comment]
Is this a correct implementation of `debounce`?

    public extension SignalProducerType
    {
        @warn_unused_result
        public func debounce(interval: NSTimeInterval, onScheduler scheduler: DateSchedulerType) -> SignalProducer<Value, Error>
        {
            return flatMap(.Latest, transform: { next in
                SignalProducer(value: next).delay(interval, onScheduler: scheduler)
            })
        }
    }

The [Objective-C implementation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/RACSignal+Operations.m#L139) is much more complex, despite `map`, `switchToLatest`, and `delay` all being available, so I feel like I might be missing something here. However, it appears to work, although I've only used it on `mainQueueScheduler`.

**Comment by NachoSoto** [comment]
That looks correct!

**Comment by mdiep** [comment]
That looks like an implementation of `throttle` to me, not `debounce`.

IIUC, If you have a signal that sends 10 values, one every `0.5` seconds, then:

* `throttle(1)` would send 1 value—1 second after the last value was sent
* `debounce(1) would send something like 5 values—1 every second

**Comment by natestedman** [comment]
I think in that case, Swift `throttle` would send two values - let's say the signal's sending ascending integers:

- `throttle`: sends `0` immediately-ish (depending on the scheduler passed), then `9`, 1 second after the signal completes
- `debounce`, or some third term: as you stated it
- `debounce`, or some third term - sends `9`, 1 second after the signal completes

The third case is the one that's useful for me - essentially, waiting until the user stops altering configuration settings before writing them in an expensive way, but today is the first time that I've heard the term "debounce", so it's very likely that I'm using it incorrectly!

**Comment by maelp** [comment]
Would this implementation (derived from `throttle`) work and be more verbose than the above-mentioned one, but perhaps more efficient (in particular with small debounce time) ?

```
extension SignalType {
    /// Debounce values sent by the receiver, so that at least `interval`
    /// seconds pass without new event, then forwards them on the given scheduler.
    ///
    /// If multiple values are received before the interval has elapsed, the
    /// latest value is the one that will be passed on.
    ///
    /// If the input signal terminates while a value is being debounced, that value
    /// will be discarded and the returned signal will terminate immediately.
    @warn_unused_result(message="Did you forget to call `observe` on the signal?")
    public func debounce(interval: NSTimeInterval, onScheduler scheduler: DateSchedulerType) -> Signal<Value, Error> {
        precondition(interval >= 0)
        
        return Signal { observer in
            let state: Atomic<DebounceState<Value>> = Atomic(DebounceState())
            let schedulerDisposable = SerialDisposable()
            
            let disposable = CompositeDisposable()
            disposable.addDisposable(schedulerDisposable)
            
            disposable += self.observe { event in
                if case let .Next(value) = event {
                    var scheduleDate: NSDate!
                    state.modify { state in
                        var mutableState = state
                        mutableState.pendingValue = value
                        scheduleDate = scheduler.currentDate.dateByAddingTimeInterval(interval)
                        return mutableState
                    }
                    
                    schedulerDisposable.innerDisposable = scheduler.scheduleAfter(scheduleDate) {
                        // Get the previous value of the state in previousState, and modify the current state to remove the pending value
                        let previousState = state.modify { state in
                            var mutableState = state
                            if mutableState.pendingValue != nil {
                                mutableState.pendingValue = nil
                            }
                            return mutableState
                        }
                        
                        if let pendingValue = previousState.pendingValue {
                            observer.sendNext(pendingValue)
                        }
                    }
                    
                } else {
                    schedulerDisposable.innerDisposable = scheduler.schedule {
                        observer.action(event)
                    }
                }
            }
            
            return disposable
        }
    }
}

private struct DebounceState<Value> {
    var pendingValue: Value? = nil
}
```

**Comment by rpowelll** [comment]
Has any progress been made with this?

**Comment by mdiep** [comment]
No progress has been made AFAIK. Pull requests welcome!
