### ISSUE TITLE
How to cancel a request after it is completed using +defer

### ISSUE THREAD

**Issue by tranvutuan** [ReactiveCocoa/ReactiveCocoa#2077]
I am creating a signal that request an token using `createSignal` like following

>      -(RACSignal*)requestAnonymousToken {
>        RACSignal   *signal =   [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {`
>        NSString    *strURL =   @"will be replaced by actual url";
>        AFHTTPRequestOperation *operation   =   [[AFHTTPRequestOperation alloc] initWithRequest:          [NSURLRequest requestWithURL:[NSURL URLWithString:strURL]]];
        
>       [operation setRedirectResponseBlock:^NSURLRequest *(NSURLConnection *connection, NSURLRequest *redirectRequest, NSURLResponse *redirectResponse) {
>         // If redirect contains acces_token, catch and process it
>            if ([redirectRequest.URL.absoluteString rangeOfString:@"access_token"].location != NSNotFound ) {
>                [self extractAccessTokenFrom:redirectRequest];
>                [subscriber sendCompleted];
>            }
>            return redirectRequest;
>        }];
        
>        [operation start];
>        return [RACDisposable disposableWithBlock:^{
>            NSLog(@"disposale block requestAnonymousToken");
>            [operation cancel];
>        }];
>         }];
>         return signal;
>      }

I am do some reading about the `+defer` method from this post [https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1499]. 
My question is if I am using `+defer` to create a signal which fetches token like above, how can I cancel a request at the end.

**Comment by Tiger6688** [comment]
```objc
[RACSignal defer:^{
return requestAnonymousToken;
}];
```

**Comment by tranvutuan** [comment]
@Tiger6688 :thanks for reply. However, I still don't get it. does `return requestAnonymousToken` also cancel a request even though we did not do `operation cancel` like I do when using `createSignal`?

**Comment by jlawton** [comment]
@tranvutuan Deferred signals inherit cancelation semantics from the signal returned from the defer block.

When you subscribe to a deferred signal, first, the defer block is called, then you are subscribed to the return value of that block (and you get the associated `RACDisposable`). So, the work done in the defer block isn't cancellable, but any work done in the returned signal is, assuming that that signal returns a suitable `RACDisposable` on subscription.

```objc
[RACSignal defer:^{
    // makeSignal() is called synchronously, and so cannot be cancelled
    RACSignal *deferred = makeSignal();
    // But any cancellable work in the returned signal is still cancellable
    return deferred;
}];
```
