### ISSUE TITLE
RAC3: Using shouldBeEnabled instead of enabled in Action's apply method

### ISSUE THREAD

**Issue by akl32** [ReactiveCocoa/ReactiveCocoa#2078]
Hi all,

I've been reading through RAC3's (very elegant) Swift code, partly to understand how to use the framework, and partly just to learn by immersion how excellent Swift code is written. I've been learning a lot. 

I had a pedantic question about `Action`'s apply method, where you use this closure:

<pre>
if Action.shouldBeEnabled(userEnabled: self.userEnabled.value, executing: self._executing.value) {
    self._executing.value = true
    startedExecuting = true
}
</pre>

Is there any benefit to calling `shouldBeEnabled`, instead of using the existing `enabled` property, which is bound to the return value of `shouldBeEnabled` in `init`? Does it have to do with the possibility of reading the `enabled` property before it's updated by the binding?

Thanks!

**Comment by jspahrsummers** [comment]
Seems like reusing the property should work. This is probably just a holdover from a previous version of the code.
