### ISSUE TITLE
Generic CocoaAction

### ISSUE THREAD

**Issue by Odrakir** [ReactiveCocoa/ReactiveCocoa#2084]
Hi, this library is really great work. 

I'm trying to learn the 3.0 inside out and I have a little question:

Why isn't CocoaAction generic? It seems it shouldn't be too hard to make it so and it would ease the pain of converting the Input data in the inputTransform closure.

Am I missing something?

Thanks.

**Comment by jspahrsummers** [comment]
Generic types cannot be used from Objective-C. `CocoaAction` is meant for Objective-C bridging.

The `Action` type _is_ generic.

**Comment by Odrakir** [comment]
I see. Still this is the only way to bind an Action to an existing UIButton, for example. Right?

My problem comes when transforming the input to the CocoaAction, which is AnyObject to the given input in the plain Action. My code is ugly.

**Comment by Odrakir** [comment]
Well, I guess I'll have to wait and see what those "Objective-C Generics" are 😊

![cg_1cfwviaa97jg png-large](https://cloud.githubusercontent.com/assets/724743/8041824/5b40739a-0e1b-11e5-8395-0b416b762d33.png)

**Comment by NachoSoto** [comment]
Related: #2085

**Comment by Odrakir** [comment]
One step forward, two steps behind...

**Comment by jspahrsummers** [comment]
Yeah, looks like we can't do anything about this.
