### ISSUE TITLE
Incorporate Objective-C generics into RACSignal?

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#2085]
Somebody had to ask, and I couldn't help myself :yum: 

This will probably be great for bridging between Swift signals and Objective-C :)

```
RACSignal<NSData *> *signal = toRACSignal(signalProducer)
```

**Comment by akl32** [comment]
A worrisome quote from the new iBooks volume about Obj-C / Swift 2 interop:

“NOTE

Aside from than these Foundation collection classes, Objective-C lightweight generics are ignored by Swift. Any other types using lightweight generics are imported into Swift as if they were unparameterized.”

Excerpt From: Apple Inc. “Using Swift with Cocoa and Objective-C (Swift 2 Prerelease).” iBooks. https://itun.es/us/utTW7.l

"These foundation classes" are referring to Array, Set, etc.

**Comment by NachoSoto** [comment]
![are you kidding me](https://cloud.githubusercontent.com/assets/685609/8045306/3d581196-0de7-11e5-85fd-a20e54ebf27d.jpg)

**Comment by neilpa** [comment]
Dreams crushed

**Comment by zintus** [comment]
It's still makes sense for objc world

**Comment by rpowelll** [comment]
I guess it all depends on whether the Objective-C API is something we want to continue updating, or whether it's heading towards being in 'maintenance mode'.

**Comment by mciuba** [comment]
Some people claim that generics can also be used with custom classes:

https://twitter.com/arekholko/status/608187695219769344?t=1&cn=cmVjb3NfbmV0d29ya19kaWdlc3RfdHJpZ2dlcmVk&sig=ab9d7b57fa692e82ff0030e42b7e87271fb3a2a1&al=1&refsrc=email&iid=551eb3f36fa34135830793ff66a79d98&autoactions=1433854217&uid=1136915245&nid=244+594

**Comment by neilpa** [comment]
@mciuba They do work with custom classes, our complaint is that they are ignored when bridged to Swift.

**Comment by jspahrsummers** [comment]
This could be useful for the extant Objective-C code, but it might be too confusing when it doesn't bridge to Swift.

**Comment by LightD** [comment]
Would it really be too confusing? from Swift perspective nothing has changed.. but for Obj-C code it would make a lot of difference! I don't see a reason why this shouldn't be a feature in the Obj-C code, am I wrong? :confounded:

**Comment by jspahrsummers** [comment]
@eliperkins pointed out in chat that it's not really possible to represent the types of operators like `-map:` using Objective-C generics, so this discussion might be moot.

**Comment by eliperkins** [comment]
Agreed. You can check out the pretty simple work of throwing a type around a few operations here: https://github.com/eliperkins/ReactiveCocoa/tree/feature/obj-c-generics

That works fine for giving a signal an initial type, but the generics will blow things up when you begin to map to different types. For example:

```objc
RACStream<NSString *> *stream = [RACStream<NSString *> return:@""];
RACStream<NSNumber *> *numberStream = [stream map:^NSNumber *(NSString *value) {
	return @1;
}];
```

Gives you this error: 
![screen shot 2015-06-18 at 11 12 13 am](https://cloud.githubusercontent.com/assets/1051453/8234604/e2f12c4e-15aa-11e5-86e3-2c6baa871154.png)

I thought about exploring a category which has operations which go from type T to type U, letting you parameterize/throw generics around just that category, but Xcode didn't seem too happy with that: 
![screen shot 2015-06-18 at 11 07 32 am](https://cloud.githubusercontent.com/assets/1051453/8234513/71e04332-15aa-11e5-96c5-ce33e69a055e.png)

From the little that I played around with it, it seems that Objective-C's lightweight generics are more for homogenizing collections than for anything really to do with generics in the end :trollface:

**Comment by cdzombak** [comment]
> From the little that I played around with it, it seems that Objective-C's lightweight generics are more for homogenizing collections than for anything really to do with generics in the end :trollface:

That's…disappointing, but I guess to be expected :/

**Comment by mdiep** [comment]
This doesn't look useful based on the limitations described above. Since the Objective-C APIs are considered legacy anyway, I'm closing this.
