### ISSUE TITLE
Version 2.5 Source Code Bug

### ISSUE THREAD

**Issue by me2clients** [ReactiveCocoa/ReactiveCocoa#2086]
I am not sure if you are getting notification on closed issue so creating another issue to draw your attention to very critical issue I am facing with Version 2.5 source code. When I downloaded the source code for Version 2.5, it shows both scheme is targeted for OSX platform. Please find attached screenshot for more detail. Can you please advise ? It is really really urgent. 
![e8218396-0d2e-11e5-820c-519138d227b7](https://cloud.githubusercontent.com/assets/1165864/8044722/1f269494-0e4c-11e5-9092-e079ad52b0c1.png)

**Comment by me2clients** [comment]
Changed the base SDK and it fixed.

**Comment by jspahrsummers** [comment]
The project is not meant to be downloaded as a zip. Please use Git submodules or a dependency manager instead.
