### ISSUE TITLE
Protocol extensions instead of free functions in Swift 2?

### ISSUE THREAD

**Issue by akl32** [ReactiveCocoa/ReactiveCocoa#2087]
Swift 2 allows protocol extensions, which allow you to extend existing protocols by defining and providing default implementations for new methods on those protocols. It sounds like Apple intends to use these extensions to replace its use of free functions like `map`.

Would RAC3 want to do something similar? Essentially, there would have to be, e.g., a `SignalType` protocol, which could then be extended with `map`, `filter`, `skipRepeats`, and so on. Protocol extensions can impose additional constraints on conforming types using `where` clauses, so it would be possible to write something like:

```swift
extension SignalType where Event.T : Equatable {
   func skipRepeats() -> Signal {
      ...
   }
}
```

The upside of doing things this way is that we can use native method-calling syntax instead of pipe-forward syntax. One of the downsides is that it would expose protocols like SignalType and SignalProducerType, when it is not the intention to have users write their own implementations of Signal. It also may be that there's nothing undesirable about the pipe-forward syntax. There are also surely other issues I'm missing.

Thoughts?

**Comment by akl32** [comment]
Inspired by this gist (https://gist.github.com/chriseidhof/a3b6107c5ed829f6515a), thoughts on what a SignalType protocol would look like:

```swift

protocol SignalType {
    typealias T
    typealias E
    var signal: Signal<T, E> { get }
}

extension Signal : SignalType {
    var signal: Signal<T,E> { return self }
}

extension SignalType {
     // can reference T and E here
     func map...
}

extension SignalType where T : Equatable {
    // define methods here for which T must be equatable
   func skipRepeats() -> Signal {

   }
}
```

**Comment by jspahrsummers** [comment]
:+1: I like this idea.

**Comment by rpowelll** [comment]
I'm inclined to agree. It definitely feels like it takes some of the 'magic' away from this stuff, hopefully making it less intimidating to newcomers.

**Comment by prefect42** [comment]
Awesome 👍🏽 👍🏽
