### ISSUE TITLE
`catch` is a reserved keyword in Swift 2.0

### ISSUE THREAD

**Issue by rpowelll** [ReactiveCocoa/ReactiveCocoa#2089]
Like it says on the tin, the following code no longer works in Swift 2.0:
```swift
someSignal
    |> catch { error in
        println("error event: \(error.localizedDescription)")
        return SignalProducer(value: [])
    }
```

**Comment by NachoSoto** [comment]
Thanks for reporting this!

Looks like we'd have to write it as ``` catch `` ` .

I'd recommend renaming the operator to something like `catchErrors` to work around this.

@ReactiveCocoa/ReactiveCocoa what does everyone think?

**Comment by ashfurrow** [comment]
Makes sense to me.

**Comment by neilpa** [comment]
I had assumed we would ship RAC 3 against Swift 1.2, but that would mean creating a RAC 4 to target Swift 2 since they're not backwards compatible.

**Comment by NachoSoto** [comment]
I guess it depends on the timeline for both Xcode 7 and RAC 3.
Given that Swift 2 will be with us for at least a year, I'd be inclined to suggest we bite the bullet and make RAC 3 require Swift 2, but I'd understand if not everyone feels the same way.

**Comment by jspahrsummers** [comment]
We should ship RAC 3.0 against whatever is public/GM. We can release a RAC 4 if we need to. There are a lot of integers for version numbers—we don't need to conserve them.

**Comment by jspahrsummers** [comment]
I think we should rename `catch` to `flatMapErrors` or something like that, by analogy with `mapErrors`.

**Comment by kastiglione** [comment]
> `flatMapErrors`

![](http://www.reactiongifs.com/r/sad1.gif)

**Comment by vincentsong** [comment]
Maybe RAC3.2.0 :dancer:

**Comment by raylillywhite** [comment]
In case anyone else come across this while trying to figure out how to migrate code to the `swift-2.0` branch, it looks like the name that was decided on is `flatMapError` (no `s`)

**Comment by kastiglione** [comment]
> it looks like the name that was decided on is `flatMapError` (no `s`)

![](http://www.reactiongifs.com/r/sad1.gif)

**Comment by neilpa** [comment]
@kastiglione I'm open to alternatives ...

**Comment by kastiglione** [comment]
@neilpa Don't mind me… :stuck_out_tongue_winking_eye:

**Comment by neilpa** [comment]
@kastiglione Damn, was really hoping for a better name though

**Comment by kastiglione** [comment]
@neilpa have we considered emoji?

**Comment by iv-mexx** [comment]
> /// Catches any error that may occur on the input producer, mapping to a new producer
> /// that starts in its place.
> public func :scream:<F>(handler: E -> SignalProducer<T, F>) -> SignalProducer<T, F>  {}

**Comment by neilpa** [comment]
I nominate :sob: and :trollface:

**Comment by dannygreg** [comment]
` public func 😲…` has a good ring to it.
