### ISSUE TITLE
RAC 3: RAC() & RACObserve() equivalents in RAC3?

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2091]
What is the correct way to do this in RAC3?
`RAC(nameLabel, text) = RACObserve(viewModel, name);`

**Comment by MarcoSero** [comment]
I'd recommend reading @ColinEberhardt's article http://blog.scottlogic.com/2015/05/15/mvvm-reactive-cocoa-3.html

**Comment by jspahrsummers** [comment]
This is discussed in [the changelog](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/f6c4777a18a78cb621917a833432d5b8f2da2927/CHANGELOG.md#using-propertytype-instead-of-racobserve-and-rac).

**Comment by MarcoSero** [comment]
Oh nice I had missed that. I think an example there would be useful though.

**Comment by memmons-ntst** [comment]
@ColinEberhardts articles are great. I've learned a lot from them. I understand you can use do this:
```Swift
extension UITextField {
  public var rac_text: MutableProperty<String> {
    return lazyAssociatedProperty(self, &AssociationKey.text) {  
      self.addTarget(self, action: "changed", forControlEvents: UIControlEvents.EditingChanged)
      var property = MutableProperty<String>(self.text ?? "")
      property.producer
        .start(next: {
          newValue in
          self.text = newValue
        })
      return property
    }
  }
  
  func changed() {
    rac_text.value = self.text
  }
}
```
`nameTextField.rac_text <~ viewModel.name`

I'm trying to bind a label, however, which is where I'm getting thrown for a loop.
`nameLabel.rac_text <~ viewModel.name`

I guess I'm wondering to approach binding in the case of controls that can not be edited and thus have no changed event to hang off of. Does it make any sense to define a `UILabel rac_text` extension without the changed target just to be able to bind changes to the viewModel to a label?

**Comment by neilpa** [comment]
You can use `DynamicProperty` for this.

```swift
DynamicProperty(nameLabel, "text") <~ viewModel.name |> map { $0 }
```

Couple of things to note
- The lifetime of `DynamicProperty` is bound to the object that it wraps. No need to store it anywhere.
- The trailing `map` is required since the value type needs to by `AnyObject`

**Comment by memmons-ntst** [comment]
@neilpa Ah, that would be perfect. Isn't is supposed to be this though? 
`		DynamicProperty(object: nameLabel, keyPath: "text") <~ viewModel.name.producer |> map { $0 as AnyObject }`

**Comment by neilpa** [comment]
@memmons-ntst Yea, I just typed that up quickly as an example. Although the `AnyObject` normally isn't needed since the type-checker can figure that out.

**Comment by memmons-ntst** [comment]
Awesome. Thank for the assist!
