### ISSUE TITLE
Add warn_unused_result to transformative operations

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#2092]
This is a Swift 2 annotation that will trigger a warning if the result of a function or method isn't used. We can use this for all operations that return a new `SignalProducer`, for example, to avoid confusion like #2060.

**Comment by neilpa** [comment]
Where did you find this? I don't recall seeing it when going through the Xcode 7 release notes.

**Comment by jspahrsummers** [comment]
It's in [The Swift Programming Language (prerelease)](https://itunes.apple.com/us/book/id1002622538).

**Comment by neilpa** [comment]
Now if only there were a way to diff the old and new swift books.

**Comment by jspahrsummers** [comment]
There's a Document Revision History at the end. :wink:

**Comment by neilpa** [comment]
That's what I get for just looking at the TOC and jumping around to what I thought were the new sections.

**Comment by neilpa** [comment]
There seems to be some limitations to this. I can't get it working with `|>` even with the attribute on the operator function.

```swift
@warn_unused_result func |> <T, E, X>(signal: Signal<T, E>, @noescape transform: Signal<T, E> -> X) -> X { … }
@warn_unused_result func map<T, U, E>(transform: T -> U) -> Signal<T, E> -> Signal<U, E> { … }

let (pipe, _) = Signal<Int, NoError>.pipe()
map { $0 + 1 }(pipe)     // warns
pipe |> map { $0 + 1 }   // no warning
```

I also tried annotating the returned closure from `map` but couldn't get that to compile. I'm going to experiment with #2087 and hopefully this warning will work with protocol extension methods.

**Comment by jspahrsummers** [comment]
Completed in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2111.
