### ISSUE TITLE
Use stdlib `ErrorType`

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2093]
We should replace `ReactiveCocoa.ErrorType` with the stdlib version in Swift 2.

**Comment by NachoSoto** [comment]
And maybe we can implement `nsError` as `self as NSError`, taking advantage of the automatic casting!

**Comment by neilpa** [comment]
We probably don't even need `nsError` or our own protocol at this point.

**Comment by neilpa** [comment]
c.f. antitypical/Result#57

**Comment by iCodesign** [comment]
> We probably don't even need nsError or our own protocol at this point.

Agree since `NSError` conforms `ErrorType` in stdlib.

**Comment by jspahrsummers** [comment]
This seems done now?

**Comment by neilpa** [comment]
Resolved in 62da84c
