### ISSUE TITLE
[RAC3] takeUntil, willDeallocSignal and Swift

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#2095]
I am recently modelling some long-lived signals using RAC in my project. For instance, views register to a globally scoped SignalProducer to response with the Dynamic Type Size. In Objective-C, the elegant way to dispose upon deallocation was `takeUntil self.rac_willDeallocSignal`. However in Swift, the takeUntil operator accepts only ` SignalProducer<T, NoError> ` or `Signal<T, NoError>`, and the ` rac_willDeallocSignal ` produces ` SignalProducer<AnyObject?, NSError> ` instead, which by no means (as far as I understand) I can map it down to ` NoError `. There is no such signal for native Swift objects, either.

So the way left is that I manually maintain a ` CompositeDisposible ` for each object to track all its disposables from the long-lived signal. This is no big deal, but looks less magical. Having said that, I am wish to know if there is a recommended way that I've missed.

Anyway, this leads me to think if target-block observing could be a better Swifty way. For instance, Apple's latest addition to the NSUndoManager API `NSUndoManager.registerUndoWithTarget(_: AnyObject, handler: (AnyObject) -> Void)` works in such way. The NSUndoManager takes and stores only a weak reference to the target, and will automatically deregister a target if a nil reference is found upon the next round of event firing. So in most cases which we capture only `self` or one object for a long lived signal, this seems to be cleaner in code.

Piece of conceptual code:

    Font.typeSize.producer.start(self, next: { this, value in
        this.doSomething(value)
    })

**Comment by neilpa** [comment]
> which by no means (as far as I understand) I can map it down to NoError

You can use `catch` to change the error type.

```swift
// the catch block what actually happen but the compiler doesn't know that
let dealloc = someView.rac_willDeallocSignal.toProducer() |> catch { .empty }
```

**Comment by andersio** [comment]
Thanks for letting me know about the catch operator. Now I've tried to use catch/flatMapError, but this doesn't seem working in Swift 2 with the swift2 branch. The compiler prompts on the takeUntil operator about `Type () does not conform to ErrorType`.

**Comment by neilpa** [comment]
That branch is still very much a WIP. I wouldn't recommend using it yet.

**Comment by andersio** [comment]
I see. I guess I have to stick to my workaround for some time until things settled for Swift 2. Thanks for your kind help. :)

**Comment by neilpa** [comment]
`catch` should still work fine with Swift 1.2.

**Comment by nmtitov** [comment]
Could you tell what does `()` mean in this case and how I can solve this problem:

````
        let touch: SignalProducer<AnyObject?, NoError> = button.rac_signalForControlEvents(.TouchUpInside).toSignalProducer().flatMapError { _ in SignalProducer<AnyObject?, NoError>.empty }
        let scheduler = RACScheduler.mainThreadScheduler();
        let throttle = touch.throttle(0.25, onScheduler: scheduler)
        let touches = touch.takeUntil(throttle)
````

leads to 

````
Cannot invoke 'takeUntil' with an argument list of type '((Signal<(), NoError>).Type)'
````

**Comment by joshbax** [comment]
`()` is an an empty tuple. `Void` is a type alias of the empty tuple, so you need a `Signal<Void, NoError>`

For example, you could use `Signal<Void, NoError>.pipe()` and pass the returned signal into `takeUntil`. Use the observer from `pipe()` to invoke the `takeUntil` trigger. I'm not sure if this applies to what you're doing. Perhaps you want to map the throttle producer to `Void` and use that, but then you'll only receive one touch event and the touch producer will complete. 

Note that you can substitute `()` for `Void` anytime.

**Comment by nmtitov** [comment]
Thank you. I ended up with 

````
let throttle = touch.throttle(0.25, onScheduler: QueueScheduler.mainQueueScheduler).map { _ in () }
````
In this case I can't use Void instead of (), I believe this is because map should return value, not type or type alias.

But later I found out that `throttle` changed from RAC2, so I had to remove `throttle` call.
