### ISSUE TITLE
Deadlock on action.apply ?

### ISSUE THREAD

**Issue by bhowell2** [ReactiveCocoa/ReactiveCocoa#2100]
I was just testing out some basic code with `Action` and I ran into a deadlock. Am I doing something incorrectly here? I can't really tell from the source code that this is an incorrect way to use `Action`. 

The necessary code to reproduce:
**instance vars**
```Swift

var startSearch: MutableProperty<Bool> = MutableProperty(false)
    
lazy var action: Action<String, Void, NSError> = {
        return Action<String, Void, NSError>(enabledIf: self.startSearch, {
            text in
            println(text)
            return SignalProducer<Void, NSError> {
                sink, disposable in
                sendNext(sink, Void())
                sendCompleted(sink)
            }
        })
    }()
```
**viewDidLoad**
```Swift
startSearch <~ textField.rac_textSignal().toSignalProducer() |> map { $0 as! String } |> map { count($0) > 3 } |> catch { _ in SignalProducer<Bool, NoError>.empty }
        
// There is no error until this is introduced.
startSearch.producer.start(next: {
            if ($0) {
                self.action.apply("hey")   // error (deadlock) from this
            }
        })
```

The error:
```
2015-06-11 21:48:19.298 PlaygroundProject[4468:341466] *** -[NSLock lock]: deadlock (<NSLock: 0x7fb9cad23770> 'org.reactivecocoa.ReactiveCocoa.SignalProducer.buffer')
2015-06-11 21:48:19.299 PlaygroundProject[4468:341466] *** Break on _NSLockError() to debug.
```

On another note does anyone have a recommendation of a better way to setup an action and execute something based on text from a textfield or something?

**Comment by jspahrsummers** [comment]
That seems like reasonable usage. Looks like we have a bug.

**Comment by neilpa** [comment]
> That seems like reasonable usage

I'm not so sure. The use of lazy here is hiding the fact that the action is instantiated inside the `startSearch` subscription the first time it sends an event.

Below is a simplified repro that better illustrates the problem.

```swift
let enabled = MutableProperty(false)

enabled.producer.start(next: { _ in
	let action: Action<Int, Int, NSError> = Action(enabledIf: enabled) {
		SignalProducer(value: $0)
	}
})

enabled.value = true
```

The root problem is `Action`'s initializer subscribes to `enabled.producer` leading to a [recursive signal](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2042).

**Comment by bhowell2** [comment]
I do agree with you @neilpa. I've tagged this in #2124 - because i'm not sure if this is desired behavior or not.

**Comment by jspahrsummers** [comment]
Good reduction, @neilpa. We can address #2124, but I agree that recursion looks ill-formed.
