### ISSUE TITLE
Not sure why 'started' event block not called on MainThread

### ISSUE THREAD

**Issue by vincentsong** [ReactiveCocoa/ReactiveCocoa#2105]
Hi guys

   I just had a problem when I want to observe a SignalProducer on UIScheduler, I use 'on' to invoke side effect of 'started' event. Like below:
  note: I ran this code in another thread(GCD queue) rather than main thread then the side effect closure  ran in that queue's thread, don't know why. But 'next' and 'completed' closure ran in main thread as expected, RAC3.0 beta.8
````
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), { () -> Void in
    myNetworkSignalProducer()
            |> observeOn(UIScheduler())
       //  |> startOn(UIScheduler())   <-- tried this but still not ran in main thread
            |> on (started: { println("should run in main thread, but runs in caller's thread")}, <-- this closure should run in main thread
                    next: {println("runs in main thread"),
                    completed: {println("runs in main thread")}})   
            |> start()
})

````

**Comment by ikesyo** [comment]
`observeOn()` takes effect for closures passed to `start()`. For your purpose, you should use `startOn()` instead.

**Comment by neilpa** [comment]
[Be careful](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/362c55c0ef976f7ceccc60e63c3f9001d3384748/ReactiveCocoa/Swift/SignalProducer.swift#L397-L398) when using `startOn` because it may break the producers expectations about which thread it's work is running on.

**Comment by vincentsong** [comment]
@ikesyo thanks, but I found 'next' and 'completed' event closures all runs in main thread, why 'started' closure runs on  the caller's thread, it's confused, they should be consistent isn't it?  While start() doesn't have 'started' event.

**Comment by jspahrsummers** [comment]
`observeOn` will send all _events_ on the specified scheduler. “Starting” is not an event. All events are cases in the `Event` type.

If you want every closure of `on()` to run on the same scheduler, you'll have to use both `startOn` and `observeOn`. Note @neilpa's comment about changing the start scheduler, though.

**Comment by vincentsong** [comment]
sorry for the late reply. I think we can close it. Thanks.
