### ISSUE TITLE
SignalProducer produces weird xcode error

### ISSUE THREAD

**Issue by avalanched** [ReactiveCocoa/ReactiveCocoa#2106]
I have a extension on Alamofire Request

```swift
import Foundation
import Alamofire
import ReactiveCocoa

extension Request {
    
    func createSignalResponseJSON() -> SignalProducer<AnyObject?, NSError> {
        return SignalProducer {
            sink, disposable in
            
            self.responseJSON {
                (request, response, JSON, error) -> Void in
                
                if(error == nil) {
                    sendNext(sink, JSON)
                }
                else {
                    sendError(sink, error!)
                }
                
                sendCompleted(sink)
            }
        }
    }
}
```

which produces the following error

```swift
 ld: file too small (length=0) file '/Users/x/Library/Developer/Xcode/DerivedData/testlib-esbiisvpfxnnpbbriafwkpdkdqpd/Build/Intermediates/testlib.build/Debug-iphonesimulator/testlibTests.build/Objects-normal/x86_64/AlamofireSignal.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I need a signalproducer, but if would change this to a normal signal the error disappears

**Comment by Dominoo** [comment]
I have this one too.... 

Problem is with the usage of "sink". inside of another nested block. I get this error from xcode (my sample code is very similliar I actually went there to report this bug) 

Global is external, but doesn't have external or weak linkage!
i8* ()* @_TFFFC6Rekola9RekolaAPI4authFS0_FT_GV13ReactiveCocoa14SignalProducerPSs9AnyObject_CSo7NSError_U_FTGVSs6SinkOfGOS1_5EventPS3__S4___CS1_19CompositeDisposable_T_auL_4sinkGS5_GS6_PS3__S4___
invalid linkage type for function declaration
i8* ()* @_TFFFC6Rekola9RekolaAPI4authFS0_FT_GV13ReactiveCocoa14SignalProducerPSs9AnyObject_CSo7NSError_U_FTGVSs6SinkOfGOS1_5EventPS3__S4___CS1_19CompositeDisposable_T_auL_4sinkGS5_GS6_PS3__S4___
LLVM ERROR: Broken module found, compilation aborted!

**Comment by avalanched** [comment]
yes indeed, problem solved now, thanks.

**Comment by Dominoo** [comment]
how did you solved it ?

**Comment by avalanched** [comment]
redefine sink, i'm not sure if this is the best approach, but at least it compiles

```swift
func createSignalResponseJSON() -> SignalProducer<AnyObject?, NSError> {
        return SignalProducer {
            sink, disposable in

            let _sink = sink
            self.responseJSON {
                (request, response, JSON, error) -> Void in

                if(error == nil) {
                    sendNext(_sink, JSON)
                }
                else {
                    sendError(_sink, error!)
                }

                sendCompleted(_sink)
            }
        }
    }
```

**Comment by ikesyo** [comment]
Ah, perhaps this is the compiler/type inferencer problem about _single-expression closures with non-Void return types within Void contexts_. So the following should work:

```swift
func createSignalResponseJSON() -> SignalProducer<AnyObject?, NSError> {
    return SignalProducer { sink, disposable in
        self.responseJSON {
            ...
        }
        return // Added.
    }
}
```

See also #1894.

**Comment by Dominoo** [comment]
@ikesyo you are right! Thank you
