### ISSUE TITLE
Simple exemple without two-way binding

### ISSUE THREAD

**Issue by hartbit** [ReactiveCocoa/ReactiveCocoa#2107]
I'm trying to learn and understand ReactiveCocoa, and I'm starting with version 3, in Swift. Can someone show me a simple example of how I would bind a form of text fields with a backing object so that inputs into the text fields update the object and initial values of the object pre populate the text fields. I thought that would require two-way binding, which we don't have.

**Comment by MarcoSero** [comment]
The way I'm doing (which I'm not sure it's the best way) is something like this:

My view has a `MutableProperty` view model

```swift
var viewModel: MutableProperty<ViewModel?> = MutableProperty(nil)
```

and during initialization I setup the binding(s) so that the view is updated when the view model changes:

```swift
currentWeightTextField.rac_text <~ viewModel.producer |> ignoreNil |> map { $0.currentWeight }
```

Then, my viewModel observes the textfield and updates the backing object when necessary:

```swift
view.currentWeightTextField.rac_text.producer
            |> map { Int($0) }
            |> ignoreNil
            |> map { Weight(fromKG: $0) }
            |> start(next: { newWeight in
                self.exerciseSet.weight = newWeight
            })
```

**Comment by jspahrsummers** [comment]
Luckily, AppKit and UIKit don't generate events for programmatically-triggered changes, so the absence of real two-way binding in RAC isn't a big hindrance. This is why @MarcoSero's example works.

**Comment by ldantona** [comment]
This is quite an old thread but I find its topic very interesting.
In the previous example the view model must be aware of the view, which should be a bad thing in a MVVM architecture. In this sense I suppose that a two-way binding between UI and view models must be avoided. My general approach is to bind only the view to the view model (when the latter changes the former is updated consequently) and let the UI communicate with the view models through commands.
Is this a good solution with the latest version of RAC too (I'm still stuck to RAC2)?

**Comment by mdiep** [comment]
> Is this a good solution with the latest version of RAC too (I'm still stuck to RAC2)?

Yes, I think so. RAC5 might have a better solution as we integrate RAC Cocoa extensions.
