### ISSUE TITLE
Subscribe to any event

### ISSUE THREAD

**Issue by shams-ahmed** [ReactiveCocoa/ReactiveCocoa#2109]
I have 5 signals, i would like a event to be triggered for any of these signals without waiting for the each signal to have at least one next event..

i tired to use [RACSignal combineLatest:reduce:] but it doesn't get called some of the signals have not been triggered..

any suggestions or methods to look at?

**Comment by joshaber** [comment]
`+[RACSignal merge:]` will pass through whatever values any of the signals sends, but you lose the knowing which signal the value came from. If you need that, you can use `+[RACSignal combineLatest:reduce:]` but give each of the signals a starting value.

**Comment by MarcoSero** [comment]
To add on @joshaber's answer: you can set the starting value of a signal with `-startWith:`

**Comment by shams-ahmed** [comment]
thanks ill give it a go!
