### ISSUE TITLE
watchOS target support

### ISSUE THREAD

**Issue by MarcoSero** [ReactiveCocoa/ReactiveCocoa#2110]
[I've been trying](https://github.com/ReactiveCocoa/ReactiveCocoa/compare/swift2...MarcoSero:watchos-support?expand=1) to add this but I'm facing a few issues right now.

~~1) I had to update `Result` to the latest master to get its new watchOS target, but now `E` conforms to `ErrorType`, so further (and unrelated to watchOS) changes are required. This is probably part of the work @neilpa has been doing to add protocol extensions https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2099 (correct me if I'm wrong)~~
Rebasing on top of https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2099 fixed this

2) Some macros seem not working ?

![macro error](https://cloud.githubusercontent.com/assets/867996/8227169/c2d1f438-159c-11e5-9616-d17d6ff4d1ce.png)

**Comment by jspahrsummers** [comment]
That looks like a dtrace macro. Those shouldn't be enabled for watchOS.

**Comment by MarcoSero** [comment]
Right. I managed to get it to build by adding the preprocessor macro `DTRACE_PROBES_DISABLED=1` to the watchOS target.
I've opened a PR https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2121

**Comment by mdiep** [comment]
This is fixed as of #2209.
