### ISSUE TITLE
pipe forward operator is unknown

### ISSUE THREAD

**Issue by daniel-shin1104** [ReactiveCocoa/ReactiveCocoa#2115]
Pretty sure this is compiler bug but I found that pipe forward operator `|>` is not exposed properly in my application code.

I replace to use instead custom `|>>` with the same implementation copied from the source, then everything works great.

Is this known issue in XCode?  (i.e exporting custom operator from framework)

I'm currently using 6.3.2 GM

**Comment by neilpa** [comment]
Custom operators work just fine when exported from a framework. Do you have an example project that illustrates this problem?

**Comment by daniel-shin1104** [comment]
I pushed to repo [here](https://github.com/daniel-shin1104/DemoRAC)

Maybe it's related to the way I set up RAC. I kinda did things manually as you can probably see since the installation guide you guys had didn't really chime well for some reason.

Thanks for your help!

**Comment by daniel-shin1104** [comment]
It appears to work fine when importing built **.framework** instead of **.xcodeproj**

**Comment by raylillywhite** [comment]
In case others encounter this issue: were getting an `Operator is not a known binary operator` compile error while using `|>` and it was simply because we needed to `import ReactiveCocoa`

**Comment by Spencevail** [comment]
@raylillywhite thank you! I read your comment and thought "I know I imported that..." scrolled back up to the top and sure enough....whoops!

**Comment by rpowelll** [comment]
I've also seen this or a similar error when a `Signal`'s `ErrorType` parameter isn't `NoError`

**Comment by njovy** [comment]
I get this error as well. When an ErrorType isn't NoError how do you use |> ?

**Comment by Spencevail** [comment]
You can modify the stream using `promoteErrors<T, E: ErrorType>(_: E.Type) -> Signal<T, NoError> -> Signal<T, E>` to go from `NoError` to `NSError`.
