### ISSUE TITLE
Is a retain cycle possible when using 'self' in class method?

### ISSUE THREAD

**Issue by fatuhoku** [ReactiveCocoa/ReactiveCocoa#2116]
e.g. a slightly contrived example...

```objc
+ (void)listenOutForTheUptownFunk {
    [[[Radio songSignal]
        filter:^(Song *song) {
           return song.title isEqualToString:@"Uptown Funk";
        }]
        subscribeNext:^(Song *song) {
            // QUESTION: Is there any retain problem here?
            [self danceToSong:song];
        }];
}

+ (void)danceToSong:(Song *)song {
    // ...
}
```

I just want to do a sanity-check on this one. `self` represents the class in this case, and afaik `Class` do not have storage semantics like normal Objective-C objects. Am I right?

Obviously the syntax of using `self` here raises all the alarm bells when I read the code... but yet surely `@weakify/strongify(self)` is not required here, right?

**Comment by kastiglione** [comment]
You don't have to worry about your class being deallocated, so no.

**Comment by fatuhoku** [comment]
Yes I guess Classes hang around for some time don't they. Thanks @kastiglione.

**Comment by kastiglione** [comment]
You're welcome :+1:
