### ISSUE TITLE
Are there any ways to make several signals into one signal instead of flatten them in Reactive Cocoa

### ISSUE THREAD

**Issue by MaXianqing** [ReactiveCocoa/ReactiveCocoa#2117]
First. Let me introduce the background of my issue. I have several network requests to send.

(RA means Request A, and -----> means the result of the previous request will be sent to the next request)

 - RA---->RB---->RC
 - RD
 - RE---->RF

Here are 3 bundles of requests. Now I want to subscribe the signal that any of the bundles that has the response.

Since every request can be represented as a signal e.g SA, so the signal flow should look like:

 - SA---->SB----->SC
 - SD
 - SE---->SF

Then are there any signals in the Reactive Cocoa to handle this?

What I do now is to flatten map them

    Signal* bundleOne = [[[SA flatternMap:(^RACStream *(NSString* resultOfA) {
                         return SB;
                    }] flatternMap:(^RACStream *(NSString* resultOfB) {
                         return SC;
                    ];

    Signal* bundleTwo = SD;

    Signal* bundleThree = [[[SE flatternMap:(^RACStream *(NSString* resultOfE) {
                         return SF;
                       }]; 

The next step would be that how to create a signal when any of the bundleOne, bundleTwo, bundleThree signals has result.

I have tried

    [[RACSignal merge: @[bundleOne, bundleTwo, bundleThree]] any] subscribeNext:
          ^(id object) {xxx}];
But failed. Because the bundle signal is made up of the flattened signals, and from the implementation of the **any**, it also flattens the signal. So that SA, SB, SC, SD, SE, SF are all flattened and when SA returns, the **any** signal returns. This is not what I want. (I want that SA--->SB--->SC, the final SC returns, the bundleOne returns)

Could any one help me? or Reactive Cocoa doesn't fit for this? I have to resort to the nested block again....

Thanks a lot.

**Comment by bjarkehs** [comment]
Hi, from the README it says the following, which I think may be what you are looking for.

### Chaining dependent operations

Dependencies are most often found in network requests, where a previous request
to the server needs to complete before the next one can be constructed, and so
on:

```objc
[client logInWithSuccess:^{
	[client loadCachedMessagesWithSuccess:^(NSArray *messages) {
		[client fetchMessagesAfterMessage:messages.lastObject success:^(NSArray *nextMessages) {
			NSLog(@"Fetched all messages.");
		} failure:^(NSError *error) {
			[self presentError:error];
		}];
	} failure:^(NSError *error) {
		[self presentError:error];
	}];
} failure:^(NSError *error) {
	[self presentError:error];
}];
```

ReactiveCocoa makes this pattern particularly easy:

```objc
[[[[client logIn]
	then:^{
		return [client loadCachedMessages];
	}]
	flattenMap:^(NSArray *messages) {
		return [client fetchMessagesAfterMessage:messages.lastObject];
	}]
	subscribeError:^(NSError *error) {
		[self presentError:error];
	} completed:^{
		NSLog(@"Fetched all messages.");
	}];
```

**Comment by MaXianqing** [comment]
Yes, I used the flatternMap to make SA, SB, SC as a single bundleOne (as shown in my post). But this only solve the half of the problem. Another half is that, if I have bundleOne, bundleTwo, bundleThree, I want to subscribe any of the above signals' next. That's to say, the bundleOne, bundleTwo, bundleThree are not chained, they are paralleled. Any of them sends the next, I can knows that.

**Comment by mnmaraes** [comment]
If I understood it correctly. All you have to do is merge the three bundles. As in

`[RACSignal merge:@[bundleOne, bundleTwo, bundleThree]]`

The resulting signal should send next whenever any of the three sends next. (Adding any to it makes the signal send next once and then complete).

**Comment by MaXianqing** [comment]
Yes, I want to catch the event once any of the bundleOne, bundleTow, bundleThree, have sent a next event and ignore the error event. The **merge** and **any** is the way that I tried to achieve this. but failed.

**Comment by mdiep** [comment]
It's a little unclear what you were looking for.

If you wanted only the result of the first signal to send a value, you'd do this:

```objc
[[[RACSignal
    merge: @[bundleOne, bundleTwo, bundleThree]]
    take:1]
    subscribeNext:^(id object) {
    }];
```

If you wanted the result from `bundleOne` as soon as all three have completed, you'd do this:


```objc
[[RACSignal zip: @[bundleOne, bundleTwo, bundleThree]]
    reduceEach^(id a, id b, id c) {
       return a;
    }]
    subscribeNext:^(id object) {
    }];
```
