### ISSUE TITLE
Throttle subscription to collection of signals?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#2118]
I have a collection of objects that can be processed using signals. Let's say there are 10 of those signals and what I can do is `merge:` them and wait until all of them complete. However I wanted to throttle the subscription so that 2 of those 10 signals can be subscribed on at the same time. And until one of those 2 signals complete, the subscription to 3rd one cannot be made.

What are the operators (or combination of) I should be looking at?

Edit: I'm using RAC 2.5 with iOS7.

**Comment by jspahrsummers** [comment]
See -flatten:

**Comment by eimantas** [comment]
Thank you!
