### ISSUE TITLE
Code sign error: entitlement 'application-identifier' has value not permitted by provisioning profile

### ISSUE THREAD

**Issue by kypselia** [ReactiveCocoa/ReactiveCocoa#2122]
Hi, 

I am trying to include ReactiveCocoa as a dynamic framework into an iOS 8 app. When I build with Development certificate, no problem: everything runs fine. However, when I build with Enterprise Distribution certificate, I have an error that prevents my app from installing, because the ReactiveCocoa framework has a bundle ID not present in my Entreprise certificate. 

I guess that we are not expected to add org.reactivecocoa.ReactiveCocoa to our app IDs on iTunesConnect to make it work? So what am I doing wrong? 

```
installd[44] <Error>: entitlement 'application-identifier' has value not permitted by provisioning profile 'iOS Enterprise Distribution'
installd[44] <Error>: 0x101c7c000 -[MICodeSigningVerifier performValidationWithError:]: 186: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.8LkOFd/extracted/Payload/AppName.app/Frameworks/ReactiveCocoa.framework identifier = org.reactivecocoa.ReactiveCocoa type = 8> : 0xe8008016 (Entitlements found that are not permitted by provisioning profile)
installd[44] <Error>: 0x101c7c000 -[MIInstaller performInstallationWithError:]: Verification stage failed
```

**Comment by MichaelMcGuire** [comment]
As one that is signing and deploying using an Enterprise Certificate and ReactiveCocoa, I think the problem lies elsewhere.  Are you directly using the certificate in the archive process with Xcode? Or do you have a separate process for signing?

Dynamic frameworks can be included and used inside of enterprise signed apps without issue.  However, if you have a separate signing script, you need to make sure that all the frameworks get signed also.

**Comment by kypselia** [comment]
Hi, thanks for your answer. You are right, when I build and export an archive from Xcode, I don't run into the problem. 

We actually use xctool to build the project (from a Makefile): 
```Makefile
# Compile and package with the release configuration.
archive: clean
	xctool -project $(XCODEPROJ_PATH) -scheme XCam -configuration Release archive -archivePath $(ARCHIVE_PATH)

# Generate the IPA with the release configuration.
export: archive
	xcodebuild -exportArchive -archivePath $(ARCHIVE_PATH) -exportPath $(IPA_PATH) -exportWithOriginalSigningIdentity
```

I think the problem comes from the `exportWithOriginalSigningIdentity` flag.

**Comment by kypselia** [comment]
Fixed by replacing the `exportWithOriginalSigningIdentity` with `exportSigningIdentity` + identityname.
