### ISSUE TITLE
What is the main branch for Swift 2 ReactiveCocoa?

### ISSUE THREAD

**Issue by zubko** [ReactiveCocoa/ReactiveCocoa#2125]
Hey, reactive functional programming looks really interesting,

I want to give a full try of reactive programming and MVVM in a hobby Swift 2 app, which will be released after iOS 9 will be published. 

There are 2 active branches 'swift2' and 'protocol-extensions' both about Swift 2. 
Which one should I use?

As this is a hobby project, I'm more interested to have the most fresh version rather than the most stable one.

**Comment by rpowelll** [comment]
`swift2` is currently the more stable of the two. When `protocol-extensions` is good and ready, it'll be merged into that branch.

**Comment by zubko** [comment]
Thanks for explanation. `swift2` branch is a way to go then.

**Comment by rpowelll** [comment]
:+1:

**Comment by rpowelll** [comment]
No problem. Can someone close this issue?
