### ISSUE TITLE
Fails to compile swift2 branch

### ISSUE THREAD

**Issue by apouche** [ReactiveCocoa/ReactiveCocoa#2126]
Trying to get the swift2 branch rolling but I get a few errors, all related to: `Initializing from a metatype must reference 'init explicitly`

This occurs in the `Signal` and `SignalProduce` classes for class intializer closures ex:
```
public class var never: Signal {
		return self { _ in nil }
	}
```
Needs to become:

```
public class var never: Signal {
		return self.init{ _ in nil }
	}
```

**Comment by neilpa** [comment]
The `swift2` branch hasn't been updated for Xcode 7 beta 2 yet. Was planning on doing that later today.

**Comment by neilpa** [comment]
See 61a648e
