### ISSUE TITLE
[RAC3] Asynchronous processing

### ISSUE THREAD

**Issue by maelp** [ReactiveCocoa/ReactiveCocoa#2128]
Since I'm doing heavy processing in signals, there are times where I want to switch to a background thread to do the processing. It is not yet entirely clear on which thread the processing of the signal uses, since there are different ways to influence this:

 - `startOn`
 - `observeOn`
 - use a `dispatch_async` in eg. a `SignalProducer`

if I do

```swift
signalA // signalA uses a `dispatch_async` and calls `sendNext` and `sendCompleted` on `queueC`
  .startOn(queueSchedulerA)
  .on(next: actionA)
  .observeOn(queueSchedulerB)
  .on(next: actionB)
```

my understanding is:

 - the signal is started on `queueA`
 - then the processing switches to `queueC` through the `dispatch_async`
 - then `actionA` is run on `queueC` (and NOT `queueA` which would be the case if the scheduler could possible send back each `sendNext` or `sendCompleted` on the original queue by using `dispatch_async`)
 - then `actionB` is run on `queueB`

is this correct?

Also when trying to do a heavy computation on another thread, for instance getting the `data` from a signal and doing a big computation to get `result` on a background thread, I wonder if the best practice is

 - create a new Signal working on another thread using the value `data` in the constructor, and using a `flatMap` to merge the result back in the original signal, which seems to include a lot of boilerplate and feels weird to me (I want to process my result with streams in successive `map` calls, rather than building and merging a new signal which feels like "grafting" two signals)

```swift
signalData
  .flatMap({ data in
    return SignalProducer({ observer, disposable in
      dispatch_async(backgroundQueue, {
         // computation
         sendNext(observer, result)
         sendCompleted(observer)
      })
    })
  })
```

 - or do a `observeOn` and a `map`

```swift
signalData
  .observeOn(QueueScheduler(backgroundQueue))
  .map({ data in
    // computation
  })
```

What would you suggest when designing an API, have signals which do pure synchronous computing and let the API user choose the `startOn` and `observeOn` queue he needs, or impose where the processing should happen by using `startOn`, `observeOn` or `dispatch_async` in our API and hide this to user

**Comment by neilpa** [comment]
You're understanding of `startOn` vs `observeOn` vs internal GCD use is correct.

As for API patterns, try to avoid hidden/internal GCD usage. Try to stick with `Scheduler`s, taking them as parameters where appropriate when creating signals. This isn't always feasible, but it plays nicer with the rest of RAC and makes it clear at the call-site where the heavy-lifting is happening. So in your example I would go with the latter approach of using `observeOn` to ensure the intensive computation happens in the background.

**Comment by neilpa** [comment]
Also, depending on the signal, using `startOn` may affect observation since events are delivered on whatever thready they're sent from.

**Comment by maelp** [comment]
Thanks!
