### ISSUE TITLE
Documentation as a Playground

### ISSUE THREAD

**Issue by MarcoSero** [ReactiveCocoa/ReactiveCocoa#2129]
Probably this has already come up but it would be very nice to have an "official" Playground that serves both as documentation and.. well playground to try all the new ReactiveCocoa 3 operators.

**Comment by iv-mexx** [comment]
I think thats a great idea and it was already mentioned briefly in the [Basic Operators PR](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2063#issuecomment-108642904).

Actually, I have all the examples for that document in a Playground, but I don't know what the best way would be to provide the Playground (Needs extra workspace with RAC Framework built) and I just didn't have the time to look into this further...

**Comment by neilpa** [comment]
Once we're on Swift 2 we'll even be able to unify the documentation into a single playground with multiple pages.

**Comment by nikita-leonov** [comment]
Documentation as Playground will be helpful indeed, meanwhile I think it is valuable to have just a  playground with RAC dependency, so user can get his hands dirty with RAC fast. Me and my team members found the following Playground very usable — https://github.com/nikita-leonov/ReactiveCocoaPlayground

**Comment by mdiep** [comment]
Resolved by #2795. And deficiencies can be opened as new issues.
