### ISSUE TITLE
Getting dependencies setup and tests to run for ReactiveCocoa 3.0

### ISSUE THREAD

**Issue by hirad** [ReactiveCocoa/ReactiveCocoa#2132]
I've been trying to clone and study ReactiveCocoa 3 for a while. I'm having a hell of a time getting the dependencies in place (latest issue was Carthage/Carthage#467, and I used submodules to add Box and Quick to the project). The top issues: 

- I'm getting all sorts of Swift syntax errors in the dependencies (I checked out the latest tags from Box and Quick). 
- I can't get the ReactiveCocoa-iOS tests to run. Only the Objective-C tests are picked up by Xcode, and all of those tests fail because `NMBExpectation` "is a forward class declaration". 

There's a lot of new things here for me. Any help in getting this setup right would be much appreciated.

**Comment by neilpa** [comment]
Use `carthage bootstrap --no-use-binaries --use-submodules` to setup the dependencies. `Box` isn't getting checked out because it provides a binary release.

> I'm getting all sorts of Swift syntax errors in the dependencies (I checked out the latest tags from Box and Quick).

Latest tags are not what you want as some of those probably target Swift 2.

> I can't get the ReactiveCocoa-iOS tests to run. Only the Objective-C tests are picked up by Xcode, and all of those tests fail because NMBExpectation "is a forward class declaration".

Probably related to manually setting up the submodules.

**Comment by hirad** [comment]
`carthage bootstrap --no-use-binaries --use-submodules` finally got Carthage to set up the projects properly.

I had to drag the built frameworks into the 'link binary with libraries' section of the ReactiveCocoa targets, and now things seem to be fine and the tests are running. \o/

Thanks!
