### ISSUE TITLE
rac_signalForControlEvents only works once!

### ISSUE THREAD

**Issue by MarvinNazari** [ReactiveCocoa/ReactiveCocoa#2136]
i have this simple signal for signing in user

    func loginSignal(username: String, password: String) -> RACSignal {
        let signal = RACSignal.createSignal({ (subscriber) -> RACDisposable! in
            LKUser.signInWith(username, password: password) { result in
                switch result {
                case .Success(let suc):
                    subscriber.sendNext(suc.value)
                case .Failure(let error):
                    subscriber.sendError(error.value)
                }
            }
            return nil
        })
        return signal
    }

and for my button

    loginButton.rac_signalForControlEvents(UIControlEvents.TouchUpInside).doNext { _ in
                self.loginButton.enabled = false
                SVProgressHUD.showWithStatus("Authenticating", maskType: SVProgressHUDMaskType.Black)
                self.view.endEditing(true)
            }.flattenMap { _ in
                return LKUser.loginSignal(self.usernameField.text, password: self.passwordField.text)
            }.subscribeNext({ _ in
                SVProgressHUD.dismiss()
                self.didLogin()
            }, error: { error in
                self.loginButton.enabled = true
                SVProgressHUD.showErrorWithStatus(error.localizedDescription)
            })

it works perfectly until i get an error so i change the password text and press the login button but it does nothing (the login button is enabled)

**Comment by brow** [comment]
When you `flattenMap`, an error on any inner signal in the receiver becomes an error on the returned signal. That error means no more values are sent on the returned signal, and the subscription to the input signal is disposed. `doNext`'s block isn't going to get called anymore.

Your best best might be to use `catch`/`catchTo` to transmute errors into values that you can watch for downstream.

**Comment by Unihilator** [comment]
So what about reactive cocoa 4? I'm trying to forward event with flatMap after rac_signalForControlEvents and it only works once. But I need to handle error many times. How can I do that?
```swift
self.logInButton.rac_signalForControlEvents(UIControlEvents.TouchUpInside)
        .toSignalProducer()
        .ignoreErrors()
        .flatMap(FlattenStrategy.Concat, transform: {_ in return emailAndPasswordChecksSignal})
        .start { event in
            switch event {
            case .Next(let value):
                print(value)
            case .Failed(let error):
                let alert = UIAlertView(title: "Error", message: error.description, delegate: nil, cancelButtonTitle: "OK")
                alert.show()
                print("")
            default:
                print("")
            }
            print(event)
        }
```

**Comment by andersio** [comment]
`flatMapError` or `materialize` might be the tools you want.
