### ISSUE TITLE
Batched API Signal not completing

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2139]
Hi guys,

I followed the thread on issue #785 and I got a working model of it on swift.
I'm having trouble understanding a few things regarding the behaviors of the RACSignals

```
public typealias NextPageReturn = (nextSignal: RACSignal?, nextValue: AnyObject?)

public func genericBatchedSignal(pageSignal: RACSignal, #nextPageGenerator: (AnyObject!) -> NextPageReturn ) -> RACSignal {
    return RACSignal.createSignal({ (subscriber:RACSubscriber!) -> RACDisposable! in
        pageSignal.subscribeNext({ (next: AnyObject!) -> Void in
            
            let (nextSignal, nextValue: AnyObject?) = nextPageGenerator(next)
            let thisPageSignal = RACSignal.returnValue(nextValue)
            
            if let hasNextSignal = nextSignal {//chain nextPage
                let nextPageSignal = genericBatchedSignal(hasNextSignal, nextPageGenerator: nextPageGenerator)
                thisPageSignal.concat(nextPageSignal).subscribe(subscriber)
            }
            else {//done paging
                nextValue >>>= {//if let ...
                    subscriber.sendNext($0)
                }
                subscriber.sendCompleted()
            }
        })

        return nil
    })
    
}
```

So in this function the "nextPageGenerator" will examine the next value and determine whats the result is and whats the next signal should be if there is one.

The issue is:
(1) The subscriber of genericBatchedSignal gets next values fine but doesn't seem to get the completed call.

(2) i wasn't aware that 
```
thisPageSignal.concat(nextPageSignal).subscribe(subscriber)
```
eventually sends a next value as well ...
When debugging my subscribeNext on the genericBatchedSignal i trace it down to this line

Any help to improve my understanding of the Signals would be appreciated.

Thanks,
Eddie

**Comment by neilpa** [comment]
What's the reasoning for implementing `RACSignal` operators from Swift? Why not use `SignalProducer` which is the new API and much better suited for use in Swift.

That said, either way pagination can be a tricky operator since it involves back-pressure. I would recommend taking a look at the different [`flatten`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/cb1f5bfa19ac0113b59c81e5000148ff4848804f/ReactiveCocoa/Swift/SignalProducer.swift#L908-L1156) operators since those are very close to the behavior you want. Of those, merge would be the easiest to tweak to your needs and will work fine assuming each producer only sends a single value. (I would assume that's the case for a newtork request).

**Comment by edwardIshaq** [comment]
Hi @neilpa ,

I haven't migrated yet to RAC3. i will at some point in the future I'm sure. 
I tried flatten but still didn't get any completed signals ?
Not sure yet why is that...

**Comment by edwardIshaq** [comment]
actually after testing genericBatchedSignal with a different signal it seems to be working fine on its own, the problem turns out from the client using it.
So I am getting a completed signal.

@neilpa I woud love to migrate to RAC3 but from what I've read online its still going to get lots of refactoring and changes before its stable. Any Idea on which stage it is at this point ?
That being said, I am still gonna take it for a spin on a playground project later on.

Thanks

**Comment by neilpa** [comment]
> @neilpa I woud love to migrate to RAC3 but from what I've read online its still going to get lots of refactoring and changes before its stable. Any Idea on which stage it is at this point ?

The RAC3 API is locked at this point. The last missing piece is the long-form documentation but that's being worked on. Also note that the Cocoa bindings are still based on RAC2 but are bridged to RAC3.
