### ISSUE TITLE
chaning signals with -then has a limit

### ISSUE THREAD

**Issue by szotyi** [ReactiveCocoa/ReactiveCocoa#2140]
I have a long signal list where signals depend on each other and they can not be parallelized and I have ran into a limit. After a large number (over 200) it crashes on random places (more in the -[RACCompoundDisposable isDisposable]). I created a small code to reproduce it:
```
- (void)testCount:(NSUInteger)count {
    RACSignal *signal = [RACSignal empty];
    for (NSUInteger j = 0; j < count; j++) {
        signal = [signal then:^RACSignal *(void) {
            return [RACSignal empty];
        }];
    }
    [signal subscribeCompleted:^(void) {
        NSLog(@"done: %@", @(count));
    }];
}
for (NSUInteger i = 0; i < 10; i++) {
    [self testCount:i * 100];
}
```
There are a couple of thousands signals I need to chain together. My code is more complicated and has recursive functions doing this, so not like the upper example, but the logic is the same (I'm using EXTScope macros everywhere). Am I doing something wrong, is there a different approach to this or is this a bug?
Any help is appreciated, thanks

**Comment by szotyi** [comment]
I have found scheduleRecursiveBlock and could make it working. Thx :)

**Comment by brow** [comment]
Is it possible to create a signal of the signals you need to chain, then `concat` that signal? In terms of your test method:

```objc
- (void)testCount:(NSUInteger)count {
  RACSignal *signals = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
    for (NSUInteger j = 0; j < count; j++) {
      [subscriber sendNext:[RACSignal empty]];
    }
    [subscriber sendCompleted];
    return nil;
  }];
  
  [[signals concat] subscribeCompleted:^(void) {
    NSLog(@"done: %@", @(count));
  }];
}
```

**Comment by szotyi** [comment]
Thanks for the comment, I will put this in my bag of choices, but the recursive solution fits my current problem better.
