### ISSUE TITLE
Swift 1.2 or 2?

### ISSUE THREAD

**Issue by iandundas** [ReactiveCocoa/ReactiveCocoa#2141]
I'm about to start a new (hobby, so not super important) project, and I'm torn between RAC2 or going straight to RAC3(beta8), .. and if I'd use RAC3 then I'm is Swift 1.2 or to Swift 2 (beta2) the way to go?

Thanks!

**Comment by iandundas** [comment]
At a guess, RAC3 is aimed at Swift 1.2, and the `swift2` branch won't be merged for some time to come. I'd prefer to go with Swift 2 regardless though, is the `swift2` branch relatively okay, or is it super unstable?

**Comment by neilpa** [comment]
The `swift2` branch will be merged once Xcode 7 hits GM. If you want to be on the bleeding edge, than that branch can be used. You may also be interested in #2099 which is based off the `swift2` branch.

**Comment by iandundas** [comment]
awesome - thanks 👍🏻

**Comment by schickling** [comment]
@iandundas did you get it to work?

**Comment by iandundas** [comment]
No, I couldn't get the `swift2` branch configured/building with Carthage at the time - went back to Swift 1.2 and just used `swift-development` branch, which worked okay
