### ISSUE TITLE
Make State of the Union video/slides available

### ISSUE THREAD

**Issue by iandundas** [ReactiveCocoa/ReactiveCocoa#2142]
> The videos will be posted when they are available. Don't forget that the video work is being done for free. Please be patient.

Fair enough, production done for free etc - but in the meantime, couldn't what's available be uploaded to YouTube as-is? It doesn't have to be perfectly edited, just the raw video and/or slides would be super appreciated - been waiting with baited breath for a few weeks and basically just want to get up to speed with what was announced.

Thanks :)

**Comment by iandundas** [comment]
p.s. not complaining or anything, just asking politely

**Comment by neilpa** [comment]
Nothing new was announced. There's enough updated [documentation](https://github.com/ReactiveCocoa/ReactiveCocoa/tree/cb1f5bfa19ac0113b59c81e5000148ff4848804f/Documentation) to get you started (start with the [`CHANGELOG`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/cb1f5bfa19ac0113b59c81e5000148ff4848804f/CHANGELOG.md) if your're familiar with RAC 2). Once the presentations are released they should supplement this information nicely.

**Comment by jspahrsummers** [comment]
[My slides](https://github.com/jspahrsummers/enemy-of-the-state) have been available since I gave the talk.

We don't have access to the video. GitHub's AV team does, and they'll release it when they have time.

**Comment by iandundas** [comment]
Oh awesome, I didn't know about the slides. Thanks!
