### ISSUE TITLE
Question (RAC 3.0): Websockets and error handling

### ISSUE THREAD

**Issue by thbaja** [ReactiveCocoa/ReactiveCocoa#2143]
I'm trying to use reactive cocoa for communicating with a server that sends json strings through websockets, but I would appreciate any input on structuring this in a sensible manner.

I was thinking of doing something along the lines of the code below, but getting an error would mean the signal will be disposed afterwards and I would not receive any more incoming messages. I would like to keep the signal alive as long as the websocket is alive.

From my understanding `mapError` will just map the error to another type, and since you can't instantiate NoError this is not a solution.
'catch' is only available for SignalProducers but even if I changed to a SignalProducer I would create a new signalProducer which would not be receiving the websocket messages.

So is the below an anti-pattern? Or what would be a good way to structure this?

Thanks

```
 typealias JSONObject = [String:AnyObject]

 srcSignal!
        |> tryMap { string -> Result<JSONObject, NSError> in
            // Convert json string to NSData.
            if let jsonData: NSData = string.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion:false) {
                // Convert NSData to JSONObject.
                if let jsonObject: JSONObject = NSJSONSerialization.JSONObjectWithData(jsonData, options: nil, error:nil) as? JSONObject {
                    return .success(jsonObject)
                } else {
                    return .failure(JSONError.InvalidJSON.nsError)
                }
            } else {
                return .failure(JSONError.InvalidString.nsError)
            }
        }
        |> observe (next: {value in
            sendNext(sink, value)
        }, error: { error in
            sendError(sink, error)
        })

**Comment by neilpa** [comment]
The original `srcSignal` in this example will remain connected (assuming valid references to it). It's only the new signal returned from the application of `tryMap` that will terminate. Note that all signal (and producer) operators return a new signal, they don't mutate the existing one.

**Comment by thbaja** [comment]
Thanks for taking the time to answer @neilpa, much appreciated.

It's doesn't appear from my post above, but what I do with the new jsonObject is to forward it to a SignalProducer.
The SignalProducer will buffer the jsonObjects and interested consumers can subscribe to this producer and filter for what's relevant to them. The idea is that the same websocket connection will be sending different types of messagest (eg. login, chat etc.), and it would be nice to only deserialize a single time for each message. And so the `srcSignal` in the above will remain connected, but not the producer.
Do you have an idea for a better approach?

I guess it could be nice to have something like [Moya](https://github.com/AshFurrow/Moya) but for Websockets.

**Comment by aloco** [comment]
@thbaja How did you solve this? 

I have a similar issue, where I have a websocket connection with socket events wrapped into Signal´s. Since the socket sends JSON objects, I try to parse those within  `attemptMap`. Sometimes the JSON is invalid so the parsing goes wrong and the signal emits an error. After that the Signal returned by `attemptMap` disconnects and I don´t receive socket events anymore.
How did you solve this without resubscribing manually to the socket event signal after an error?

**Comment by neilpa** [comment]
You should `map` to the JSON parse `Result` and send that on the signal instead of bringing the value and error "into the signal" via `attemptMap`

**Comment by aloco** [comment]
Ok so I will go with something like `Signal<Result<SomeWhateverParsed, NSError>, NoError>`. 
Thanks 👍🏻 this makes sense - I can `filter` those Results which are not `Success` after parsing and `map` everything back to `Signal<SomeWhateverParsed, NoError>`
