### ISSUE TITLE
UIKit Extensions for 3.0 - use work-arounds for now? 

### ISSUE THREAD

**Issue by iandundas** [ReactiveCocoa/ReactiveCocoa#2144]
Am I right in thinking that there's no UIKit extensions for 3.0 yet, (but that they're coming)? 

Say I want to build the canonical FRP example of merging the signals from a Username and Password UITextField, I can't find a way to subscribe to a UITextField changes apart from either: 

     textField.rac_textSignal().toSignalProducer()

which seems wrong (switching back to KVO and 2.0 land), or using @ColinEberhardt's unofficial [UIKit extensions](https://github.com/ColinEberhardt/ReactiveTwitterSearch/blob/master/ReactiveTwitterSearch/Util/UIKitExtensions.swift), which again use KVO under the hood, but surface a MutableProperty to make it seem more 3.0:

    textField.rac_text

Just catching up with 3.0 changes and just wanted to double-check (and to document my confusion for any others.. ). Is there any other more correct way, or should I just go with that for now?

Thanks

**Comment by jspahrsummers** [comment]
`rac_textSignal` doesn't have anything to do with KVO. It just uses `-addTarget:action:forControlEvents:`.

As discussed [elsewhere](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2074), 3.0 may be released without the UIKit extensions.

**Comment by iandundas** [comment]
`addTarget` not `addObserver` 😳 I'll contact my optician now.. 
Cool, will use the bridging or whatever for now. Thanks!
