### ISSUE TITLE
Displaying alerts - they have no action

### ISSUE THREAD

**Issue by TanderZA** [ReactiveCocoa/ReactiveCocoa#2145]
i've recently adopted the MVVM paradigm in my current iOS project. So, we know that anything UKKit related should not be in the viewModel and not tied to how the UI is. viewModel should not know anything about the UI it's serving. So I get this.

However in my current viewModel I am handling a login process. I need to let the user know about login errors (I'm handling more than just incorrect credentials entered). I've decided to place this in the viewModel and the reasons for putting it there instead of the controller are these:

Technically its UIKit related (UIAlertView) however it doesn't know anything about the view it's presenting on.
The "okay" button on UIAlertView just dismisses the alert - no action is taken on there.
The ViewController itself handles the action needed as that is UIKit related and does take the user to a different screen.
And lastly the reason I firmly believe it should be in the model is due to the thinking that the model should be the one giving out the errors it has and the VCs should react to them. This way, if I make a new login screen for the iPad - I can plug this model into the VC and not have to handle / write the error code logic again with the related error messages?

One other way of doing this I think is creating an alertSignal of some type that the view controller can subscribe to when there are errors?

**Comment by Odrakir** [comment]
I don't think you should put that kind of code inside the viewModel.

As I use to do it. The viewModel has a login RACCommand which starts the login process, and you subscribe to the errors of this command in the ViewController and handle them properly.
