### ISSUE TITLE
Add a Signal accessor for PropertyType

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#2146]
This would make it clearer that properties can be represented as producers _or_ signals. Of course, using the signal will mean you don't receive the current value upon observation.

**Comment by neilpa** [comment]
:+1: for this idea.

**Comment by ikesyo** [comment]
This is implemented by #2622 and included since the [v4.0.0-RC.2](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.0.0-RC.2) release. Closing.
