### ISSUE TITLE
Merge signals

### ISSUE THREAD

**Issue by maelp** [ReactiveCocoa/ReactiveCocoa#2154]
I have a question about ReactiveCocoa, which happens when I'm trying to build a signal which might optionally merge different values:

```
let signalProducer = SignalProducer<V, E>({ sink, disposable in
    if condition { sendNext(sink, v1) }
    else if condition { sendNext(sink, v2) }
    else if condition { sendNext(sink, v3) }
    else { sendNext(sink, v4) }
    sendCompleted(sink)
})
```

now imagine for some reason I need to replace one of the `v` with a signal, perhaps because I need to do an async call, I have two choices:

- either I rewrite everything as signal of signals and use a `flatten`, which feels weird because I have to rewrite the complete enclosing method simply because I changed one of the branch, eg

```
let signalProducer = SignalProducer<SignalProducer<V, E>, E>({ sink, disposable in
    if condition { sendNext(sink, SignalProducer<V,E>(value: v1)) }
    else if condition { sendNext(sink, v2AsSignal) }
    else if condition { sendNext(sink, SignalProducer<V,E>(value: v3)) }
    else { sendNext(sink, SignalProducer<V,E>(value: v4)) }
    sendCompleted(sink)
}) |> flatten(.Merge)
```

- or I start the signal and bind its listeners on the correct methods, which seem to require boilerplate code and might cause some bug if someone forgets to bind one of the method, eg

```
let signalProducer = SignalProducer<V, E>({ sink, disposable in
    if condition { sendNext(sink, v1); sendCompleted(sink) }
    else if condition {
        let signalDisposable = v2AsSignal |> start(
             error: {e in sendError(sink, e)},
             next: {v in sendNext(sink, v)},
             completed: {sendCompleted(sink)}
        )
        disposable.addDisposable(signalDisposable)
    }
    else if condition { sendNext(sink, v3); sendCompleted(sink) }
    else { sendNext(sink, v4); sendCompleted(sink) }
})
```

Or does this work?

```
let signalProducer = SignalProducer<V, E>({ sink, disposable in
    if condition { sendNext(sink, v1); sendCompleted(sink) }
    else if condition {
        disposable.addDisposable(v2AsSignal |> start(sink))
    }
    else if condition { sendNext(sink, v3); sendCompleted(sink) }
    else { sendNext(sink, v4); sendCompleted(sink) }
})
```

which does the same binding.

my question is:
 - are those the preferred methods?
 - is there a particular reason to use one of those rather than the others?

**Comment by brow** [comment]
Looks like #1-3 are all equivalent. I'd avoid #2 just because it's a needlessly verbose variation on #3. One could prefer either of #1 or #3 depending on taste.

I think #1 can be shortened somewhat (though I haven't compiled this):
```swift
let signalProducer = SignalProducer<SignalProducer<V, E>, E>(value: {
  if condition { return SignalProducer(value: v1) }
  else if condition { return v2AsSignal }
  else if condition { return SignalProducer(value: v3) }
  else { return SignalProducer(value: v4) }
}()) |> flatten(.Merge)
```
(I may be incorrectly imagining that the type parameters to `SignalProducer` can be inferred in the returns.)
