### ISSUE TITLE
MutableProperty.producer

### ISSUE THREAD

**Issue by aschuch** [ReactiveCocoa/ReactiveCocoa#2159]
I am trying to build a live search that hits an API endpoint that responds with search results based on the current search query (from a textfield).

I'd like to kick off a new request every time the `searchText` changes.
My first thought was to use `Action` and apply the new query each time the `searchText` changes.
However, this does not work for this particular use-case because Action does not switch to the latest signal when invoked multiple times. That's by design.

```swift
let searchText = MutableProperty<String>("")

searchText.producer |> start(next: { query in
    searchAction.apply(query).start()
})

searchText.put("foo") // executes searchAction
searchText.put("bar") // does not execute searchAction (by design), because its already running
```

-----

I am now trying to solve this issue by directly reacting to the values sent by `searchText.producer` to kick off a new network request.

```swift
let searchText = MutableProperty<String>("")

searchText.producer
            |> throttle(1.0, onScheduler: QueueScheduler.mainQueueScheduler)
            |> promoteErrors(NSError)
            |> flatMap(.Latest) { query -> SignalProducer<[MyModel], NSError> in
                return HTTPClient.searchRequest(query)
            }
            |> observeOn(QueueScheduler.mainQueueScheduler)
            |> start(next: { models in
                // ok
            }, error { error in 
               // error
            })
```

This works perfectly fine as long as the HTTPClient does not return an error. As soon as an error occurs, the producer is completed, thus stops sending new values.
I initially thought that a `catch` would solve this problem, but the `producer` is completed nevertheless.

Is there another way to basically make the producer act as if it was a hot signal?

**Comment by brow** [comment]
Can you show how you're using `catch`? You'll need to catch on the *inner* signal, because once the signal returned by `flatMap` sends a terminating event, it's game over.

**Comment by aschuch** [comment]
> Can you show how you're using catch? You'll need to catch on the inner signal, because once the signal returned by flatMap sends a terminating event, it's game over.

Ahh, that's it. Thank you so much. I was actually using `catch` on the outer SignalProducer.
However, now another question comes to mind:  How can I inject a side effect in case an API error occurs? Is it reliable to add an `on(error: {})` before the `catch` on the inner signal to e.g. show an info to the user?

```
let searchText = MutableProperty<String>("")

searchText.producer
            |> throttle(1.0, onScheduler: QueueScheduler.mainQueueScheduler)
            |> promoteErrors(NSError)
            |> flatMap(.Latest) { query -> SignalProducer<[MyModel], NSError> in
                return HTTPClient.searchRequest(query)
                    |> catch { _ in
                        SignalProducer<[MyModel], NSError>(value: [])
                    }
            }
            |> observeOn(QueueScheduler.mainQueueScheduler)
            |> start(next: { models in
                // ok
            }, error { error in 
               // error
            })
```

**Comment by brow** [comment]
Yep, `on(error: {})` before `catch` works. If you'd rather detect errors on the outer signal than inject side effects on the inner signals, you could `materialize` the inner signals, which transforms them from `SignalProducer<[MyModel], NSError>` into `SignalProducer<Event<[MyModel], NSError>, NoError>`.

**Comment by aschuch** [comment]
Perfectly makes sense now, thanks a lot. :sparkles:

**Comment by brow** [comment]
No problem!
