### ISSUE TITLE
Let an error fall through Catch 

### ISSUE THREAD

**Issue by avalanched** [ReactiveCocoa/ReactiveCocoa#2164]
Is there a possibility to let an error fall through a catch

    class public func getUserDetails() -> SignalProducer<FBSDKAccessToken, FacebookError> {
        return SignalProducer {
            sink, _ in
            
            let _sink = sink
            
            let hasAccess = FacebookSignal.hasAccess()
            let loginUser = FacebookSignal.loginUser()
            
            hasAccess
                |> FacebookSignal.errorToSignal
                |> start(next: { value in
                    sendNext(_sink, value)
                    }, error:{ error in
                        println(error)
                    }, completed: {
                        sendCompleted(_sink)
                })
            
            
        }
    }
    
    static let errorToSignal : SignalProducer<FBSDKAccessToken, FacebookError> -> SignalProducer<FBSDKAccessToken, FacebookError> = catch({ error in
        if error == .NoToken {
            return FacebookSignal.loginUser()
        }
        return FacebookSignal.hasAccess()
    })

when the error returns NoToken I want the loginUser producer to be started but for any other error it should just fall through to the start(error:{}). momentarily i need to return the default hasAccess() producer which starts the original producer again.

**Comment by ikesyo** [comment]
Just use `return SignalProducer(error: error)`. :wink:

**Comment by avalanched** [comment]
off course :)
