### ISSUE TITLE
Probably wrong Git link in Cocoapods spec

### ISSUE THREAD

**Issue by Avtolic** [ReactiveCocoa/ReactiveCocoa#2166]
Cocoapods.org (https://cocoapods.org/?q=ReactiveCocoa) recommends to use 

    pod 'ReactiveCocoa', '3.0.0-alpha.1'

to install ReactiveCocoa. I am new to cocoapods but it seems that this spec https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/3.0.0-alpha.1/ReactiveCocoa.podspec.json has a link to an outdated fork not to the main repository:

    https://github.com/ashfurrow/ReactiveCocoa.git

Update: I have just checked ReactiveCocoa releases. It seems that https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/3.0.0-alpha.1/ReactiveCocoa.podspec.json is some temp spec and should be removed to not confuse users.

**Comment by NachoSoto** [comment]
You should open this issue directly in the CocoaPods Specs repo, as we don't maintain the podspec ourselves.

**Comment by gabro** [comment]
Hi, the version on the cocoapods website is wrong (I guess it got confused because it's not able to determine whether `beta` is more recent than `alpha`)

I've just pushed a new spec for the RC1 so you can now use

```ruby
pod 'ReactiveCocoa', '3.0-RC.1'
```

There's also specs available for beta 6 and beta 9.

**Comment by gabro** [comment]
@Avtolic relevant: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2166
