### ISSUE TITLE
Carthage, IOS 9, Xcode7b3 install? Is this even possible?

### ISSUE THREAD

**Issue by wm-j-ray** [ReactiveCocoa/ReactiveCocoa#2167]
I've tried to install RAC as sub-module to existing project (not workspace), also get the RAC's Distribution cartfile to build for standalone development.  Run brew doctor, done a re-download and install of xCode from Apple Dev site, all with no success. 

There are different errors depending on which iteration I've tried, but the common thread is the RAC library doesn't build. Nimble and Quick usually do, Llama does on occasion.  

The above is not as specific as I'd like but I've tried multiple times over multiple days and my notes are a hairball with the different combinations.  I apologize. 

Question:  is there some old reliable Obj C build I can point to with a cartfile? I don't want to use  Cocoaoods. Can I just copy in the RAC source to a project (not workspace) to get an Obj C implementation?  I've tried that with no success either. I must be missing a directory or something. 

Thanks so much

**Comment by ikesyo** [comment]
> Question: is there some old reliable Obj C build I can point to with a cartfile? I don't want to use Cocoaoods. Can I just copy in the RAC source to a project (not workspace) to get an Obj C implementation? I've tried that with no success either. I must be missing a directory or something.

[v2.5](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v2.5) is the latest Objective-C implementation of RAC, and that is Carthage compatible. So you could use that with a following `Cartfile` entry: `github "ReactiveCocoa/ReactiveCocoa" ~> 2.5`

**Comment by wm-j-ray** [comment]
Perfect.  A thing of beauty: nice clean build.  Who's better than you?
