### ISSUE TITLE
CocoaAction's executing and enabled properties as SignalProducer

### ISSUE THREAD

**Issue by almassapargali** [ReactiveCocoa/ReactiveCocoa#2169]
I like the idea of `CocoaAction` encapsulating `Action` for UI binding. Though, I'd also love to bind `enabled` property to `UIControl`'s `enabled` property. But since `enabled` on `CocoaAction` is just `Bool` property, I don't get any updates. Of course, I can always use `DynamicProperty` since it sends KVO notifications, but then I'd need to store that property too.

What do you thing about exposing `executing` and `enabled` on `CocoaAction` as SignalProducers? Or am I misusing `CocoaAction`?

**Comment by almassapargali** [comment]
As a side question, what is the place of CocoaAction. Should it go to ViewModel, or should it be only ViewController's thing?

**Comment by jspahrsummers** [comment]
You should get `executing` and `enabled` from the underlying `Action`.

`CocoaAction` is just a wrapper, so it can stored wherever is most convenient for you.

**Comment by almassapargali** [comment]
Thanks, looks like I was giving `CocoaAction` more responsibilities than it should have.
