### ISSUE TITLE
Is swift 2 branch support iOS 7?

### ISSUE THREAD

**Issue by bagusflyer** [ReactiveCocoa/ReactiveCocoa#2170]
The document said it supports iOS 8 and above. But based on my searches it says ReactiveCocoa support iOS 7 and above (because I'm using swift so that iOS 6 will not be supported.). So my question is if swift 2 branch support iOS 7? Thanks

**Comment by bagusflyer** [comment]
I downloaded the project file and built it. I found the outputs are framework. I'm afraid it won't be supported in iOS 7. Am I right?

**Comment by ikesyo** [comment]
Swift codes cannot be built to a static library. So if you'd like to use the lib in a project targeting iOS 7, you must add all the sources directly to your app project (and of course, this is not our official/supported usage).

**Comment by brow** [comment]
> you must add all the sources directly to your app project (and of course, this is not our official/supported usage)

You'd need to modify the sources, too, as they try to `import Result`, etc. I tried to integrate RAC3 into a large project recently and gave up.

Previous discussion of iOS 7 support here:  #1629

**Comment by bagusflyer** [comment]
Thanks. Maybe I should use old version for iOS 7 because I can't give up iOS 7. There are still more than 10% devices are still iOS 7 currently.

**Comment by brow** [comment]
I'm in the same boat with my project. Fortunately, using RAC2 works reasonably well from Swift, minus the macros and compile-time keypath checking. 😭🎻
