### ISSUE TITLE
Build setting PRODUCT_NAME undefined

### ISSUE THREAD

**Issue by carinofan** [ReactiveCocoa/ReactiveCocoa#2171]
Check dependencies

The file “Debug.xcconfig” couldn’t be opened because there is no such file. (/Users/fanming/Downloads/ReactiveCocoa-swift-development/Carthage/Checkouts/xcconfigs/Base/Configurations/Debug.xcconfig)
The file “iOS-Framework.xcconfig” couldn’t be opened because there is no such file. (/Users/fanming/Downloads/ReactiveCocoa-swift-development/Carthage/Checkouts/xcconfigs/iOS/iOS-Framework.xcconfig)
Build setting PRODUCT_NAME undefined

**Comment by mdiep** [comment]
This happens if you don't have xcconfigs, one of the ReactiveCocoa dependencies. You can run `script/bootstrap` to download the dependencies.

**Comment by carinofan** [comment]
Excuse me，my shell point：
*** Bootstrapping...
*** Checking dependencies...
*** Error: xctool not found. Please install it and bootstrap again.

**Comment by mdiep** [comment]
The bootstrap script is failing because it's requiring `xctool`. You can probably work around this by running `git submodule update --init --recursive` instead.

**Comment by carinofan** [comment]
Thank you very much,Today I try CocoaPods,The project is Success
