### ISSUE TITLE
Stateless ViewModels

### ISSUE THREAD

**Issue by coenert** [ReactiveCocoa/ReactiveCocoa#2172]
I am trying to make my ViewModel stateless by mapping the values from different Actions to transformations of my state and then combining these signals to one state signal. But the problem is that all `Action` accessors are a `Signal` and you can't merge them.

I can understand that these accessors are Hot streams cause they don't have side effects but i don't how i could implement this without using SignalProducers.

BTW i am using the latest rac3 beta release

**Comment by ikesyo** [comment]
Could you share some code snippets for more contexts? We may not correctly understand what you are trying.

**Comment by coenert** [comment]
Sure. I'm actually trying to implement [this](https://github.com/jonsterling/Taliban-MVVM) in the new swift api.

If you look at `JSTicTacToeViewModel` it could be something like this in swift:
```swift
protocol TicTacToeViewModelType {
    var playTile: Action<Tile, TicTacToeState -> TicTacToeState, WhateverError> { get }
    var state: SignalProducer<TicTacToeState, NoError> { get }
}
```

He uses the `results` signal property on `RACAction` to compose the `state` property. But that is not possible in the current Swift api because the `values` property on `Action` is an `Signal` and not an `SignalProducer`.

**Comment by ikesyo** [comment]
Just wrapping the `values` signal with a producer would be a help?

```swift
let valuesProducer = SignalProducer { observer, disposable in
    disposable += someAction.values.observe(observer)
}
```

**Comment by coenert** [comment]
Probably, i was more searching for an best practice. I know that this is possible but is this the right way to do it, because in fact the results of an `Action` are a hot stream of events and i thought it would be a bad practice to just wrap an hot stream in a `SignalProducer`s. But if you recommend it i suppose this is the way to do it. Thanks!

I think it would be a huge benefit to have truly stateless view models, but with the current RAC swift api it is just not clear for me how to do it right.(btw i am __really__ thankful for all the work you and the other contributors did on RAC3 :smile:)

**Comment by aehlke** [comment]
Just curious if you've found a better approach here :)

**Comment by kaybutter** [comment]
If it helps, you can merge multiple Signals using something like this:
``` swift
let mergedProducer = SignalProducer(values: [signal1, signal2]).flatten(.Merge)
```
Assuming the signals have matching value and error types.
