### ISSUE TITLE
Using mapErrors to conform to next signal but not for error display

### ISSUE THREAD

**Issue by avalanched** [ReactiveCocoa/ReactiveCocoa#2173]
public func getUserDetails2() -> SignalProducer<GTLPlusPerson?,GoogleError> {
        return SignalProducer { sink, _ in
            let _sink = sink
            self.signIn() // signIn returns a SignalProducer<GTMOAuth2Authentication?,GoogleError>
                |> mapError { error in
                    NSError()
                }
                |> then(self.service.rac_getUser()) // rac_getUser returns a SignalProducer<GTLPlusPerson?,NSError>
                |> mapError { error in
                    GoogleError.UnknownError
                }
                |> start(
                    next: { value in
                        sendNext(_sink, value)
                    }, error: { error in
                        sendError(_sink, error)
                    }, completed: { sendCompleted(_sink) })
        }
    }

I use the mapError to conform to rac_getUser() to align with NSError, then i use mapError again to convert the error from rac_getUser to map it to a GoogleError
But when signIn() sends an GoogleError i don't want to map it but i just need it to conform to the next signal.

Is this possible?

**Comment by ikesyo** [comment]
How about following?

```
public func getUserDetails2() -> SignalProducer<GTLPlusPerson?, GoogleError> {
    return SignalProducer { sink, disposable in
        let getUser = self.service.rac_getUser()
            |> mapError { _ in GoogleError.UnknownError }
        disposable += self.signIn()
            |> then(getUser)
            |> start(sink)
    }
}
```

**Comment by avalanched** [comment]
Yes that works, 

whats the logic behind the adding something to disposable?

**Comment by ikesyo** [comment]
> whats the logic behind the adding something to disposable?

That is for properly propagating a cancellation of the outer producer to the inner producer.
