### ISSUE TITLE
Delaying a signal only for certain values

### ISSUE THREAD

**Issue by kommen** [ReactiveCocoa/ReactiveCocoa#2174]
I have a situation where I want to delay a signal only under certain conditions, i.e with a UIGestureRecognizer state changes should be delayed for some states but not for others.

Example:

```objc
    RACSignal *showInteractionSignal = [[RACObserve(self.panRecognizer, state) map:^NSNumber*(id state) {
        return @([state integerValue] == UIGestureRecognizerStateChanged);
    }] distinctUntilChanged];

    [[RACSignal
        if:showInteractionSignal
        then:[showInteractionSignal delay:0.01]
        else:[showInteractionSignal delay:1.5]]
      subscribeNext:^(id x) {
        [UIView animateWithDuration:0.2 animations:^{
            // animations using x
        }];
    }];
```

This works.

However, notice the `delay:0.01` in the `then` case. If I remove that delay, it doesn't work anymore, because the false value is processed once for the `then` case and after the delay for the `else` case, causing the animations to start immediately.

Why is this? Is there a better solution?

**Comment by kommen** [comment]
Looking at the implementation more closely, it seems the signal in the `then` case fires, before the `if` can switch to the `else` case.

**Comment by mdiep** [comment]
I don't understand what you're actually trying to do. You've only explained your approach, not the problem you're trying to solve. But as you've discovered, you don't want to use the same signal in both the `if` and the `then` or `else`.

**Comment by kommen** [comment]
@mdiep: I want to show a UI element when the pan gesture starts, and hide the element again when the gesture is completed/canceled, but the hide should be delayed by a specified amount of time, while showing the element should happen immediately.

**Comment by mdiep** [comment]
I would probably do something like this:

```objc

[[[[RACObserve(self.panRecognizer, state)
    map:^(NSNumber *state) {
        if (started) return [RACSignal return:state];
        return [[RACSignal return:state] delay:1.5];
    }]
    switchToLatest]
    distinctUntilChanged]
    subscribeNext:^(id x) {
        ...
    }];
```

**Comment by kommen** [comment]
Thanks Matt, that works.
