### ISSUE TITLE
CocoaAction input is always nil

### ISSUE THREAD

**Issue by avalanched** [ReactiveCocoa/ReactiveCocoa#2176]
let action : Action<AnyObject?,AnyObject?,NoError> = Action { input in
            return SignalProducer(value: input)
        }
   
        cocoaAction = CocoaAction(action)
        button.addTarget(cocoaAction, action: CocoaAction.selector, forControlEvents: .TouchUpInside)
        
        action.values |> observe(next: println) // prints 'nil'

i just conver the input to output, I was expecting the button itself as input on the action, but i always get returned nil.

**Comment by almassapargali** [comment]
Apparently `UIButton as? AnyObject?` returns `nil`.
