### ISSUE TITLE
Signal/Subscribable/etc Abstraction

### ISSUE THREAD

**Issue by ashfurrow** [ReactiveCocoa/ReactiveCocoa#2178]
Heyo! So I've been learning more and more about the [original rx extensions](http://reactivex.io) that inspired ReactiveCocoa in an effort to better understand and appreciate RAC and the functional reactive paradigm in general. 

One question I've had that I've not been able to answer through the docs or other issues concerns the abstractions that RAC makes on top of the original extensions. Originally, RAC seems to have reflected the shared rx extensions nomenclature, but it seems to have switched over in 2012. [Observable became Subscribable](https://github.com/ReactiveCocoa/ReactiveCocoa/commit/cb9e29eae6a5f9ccb8fe93bff00aa96854414d17) and the [signal abstraction was introduced](https://github.com/ReactiveCocoa/ReactiveCocoa/commit/1674879724934a3ac281e10e710f53009c68c321). 

I was wondering if anyone around from then would be able to help me understand the motivations behind this move. I know this is a large, open-ended question, and RAC's maintainers are busy, so if anyone could point me in the right direction, I would appreciate it. I'm happy to do some research and report back here for others who might be curious. Thanks a lot!

![](http://gifs.ashfurrow.com/wiggle.gif)

**Comment by jspahrsummers** [comment]
This will probably come up in the course of https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2156. It might be easier to wait for that documentation to be written.

**Comment by ashfurrow** [comment]
@jspahrsummers That sounds like a good idea – let me know if I can be of help. Do you feel we should keep this issue open?

**Comment by jspahrsummers** [comment]
Nah, we can close it out.
