### ISSUE TITLE
how to send the value until the task is done using reactive cocoa

### ISSUE THREAD

**Issue by tranvutuan** [ReactiveCocoa/ReactiveCocoa#2184]
-(RACSignal*)finalPackage {

    RACSignal *endPoint = [[DGConfiguration sharedInstance].apiConfiguration          
    urlTemplate:DGAPIUrlLocalWatchList];` // 1.

    return [[endPointRequestSignal map:^id(NSString *endPoint) { // 2.
        return service([NSURL URLWithString: endPoint]); 
    }].flatten map:^id(NSArray *episodes) { // 3.
        NSMutableArray *info= [NSMutableArray array];
        __block NSArray *result=@[@(9)]; // test value is 9, result will be updated during callback block

        [episodes enumerateObjectsUsingBlock:^(NSDictionary *item, NSUInteger idx, BOOL *stop) {
            [info addObject:@{@"id":item[@"id"],@"links":item[@"links"]}];
        }];
        
        [[DGManager sharedInstance] updateVideoStateWith:info callback:^(NSArray *response) { // 4.
            dispatch_async(dispatch_get_main_queue(), ^{
                NSSortDescriptor *sortDescriptor = [[NSSortDescriptor alloc] initWithKey:@"timeStamp" ascending:NO];
                result  =   [[response sortedArrayUsingDescriptors:[NSArray arrayWithObject:sortDescriptor]] copy];

            });
        }];
        
        return [RACSignal return:result]; // 5.
    }].flatten;
    }

Lets me explain what I am trying to do.
1. I wrap the endPoint url via `endPoint` signal
2. Using `map` to extract url and do a service call (`service([NSURL URLWithString: endPoint])`)
3. Using `map` to extract info from step 2 and create `info` data
4. Do `updateVideoStateWith` with a callback
5. Return a signal which contains `result`

Eventually, when I subcribe to `finalPackage` signal, the return is initialized value which is `9`.I realize that the `updateVideoStateWith` call back will take time to return the result. 

My question is how can I force `return [RACSignal return:result]` wait until the data is updated from callback block. I did tried takeUntilBlock but not sure how to use it. I also think about using switchToLatest but still no luck.

PM : not sure if this post is appropriate at here. I also create a same thread in stackoverflow at [http://stackoverflow.com/questions/31495774/how-to-wait-until-the-task-is-completed-and-then-return-a-signal-reactive-cocoa](here)

**Comment by powerje** [comment]
I think you want to create a signal here:

````
- (RACSignal*)finalPackage {
    return [RACSignal createSignal:^(id<RACSubscriber> subscriber) {
            RACSignal *endPointSignal = [[DGConfiguration sharedInstance].apiConfiguration urlTemplate:DGAPIUrlLocalWatchList];
            [[endPointSignal map:^id(NSString *endPoint) { 
                // map your endpoints to episodes and return the array of episodes
            }]  subscribeNext:^(NSArray* episodes) {
                // Create your initial result array
                [[DGManager sharedInstance] updateVideoStateWith:info callback:^(NSArray *response) { 
                    // Do whatever work you need to do with the response
                    [subscriber sendNext:result];
                    [subscriber sendComplete];                     
                }];
            } error:^(NSError* error) {
                [subscriber sendError:error];
            ]];
            return nil;
        }];
}
````

This will wait until the work is done in your callback before sending the next result to the subscriber.

**Comment by tranvutuan** [comment]
@powerje :thanks for your help. There is one thing I am not so sure that I understand correctly. It is about  `flatten`. If I try without `flatten` before `subcribeNext`, app crashes and the error is 
`-[RACDynamicSignal enumerateObjectsUsingBlock:]: unrecognized selector `.

My assumption is `return service([NSURL URLWithString: endPoint])` is a signal and I can do `subcribeNext` on the signal.Therefore, I dont need `flatten`.But it is not true. Maybe I am missing something else.

**Comment by powerje** [comment]
If you're returning a signal when you're mapping the endPointSignal (hard to tell using the 'id' type) you'll want to flatten it, which you can do by changing the `map` to `flattenMap`. If you don't do that then the value you're sending to the subscribeNext block is actually a RACSignal, which is not what you're expecting here.

Check out https://github.com/ReactiveCocoa/ReactiveCocoa/issues/44 for discussion on when to use `map` vs `flattenMap`.
