### ISSUE TITLE
`throws` overloads for operators using Result

### ISSUE THREAD

**Issue by jspahrsummers** [ReactiveCocoa/ReactiveCocoa#2188]
Should we offer versions of, e.g., `attempt` and `flatMapErrors` that use `throws` instead of `Result`? Out of necessity, these would have to yield a `SignalProducer` parameterized by `ErrorType` (nothing more specific), but maybe folks would find it useful.

**Comment by jarsen** [comment]
I think this would be useful. I found myself writing my own the other day. It is unfortunate of course to have to downgrade to something less specific... but alas such is the state of Swift 2.

**Comment by NachoSoto** [comment]
I feel like we should encourage users to know about their error types. You can always wrap a `throws` closure to return a more specific `Result`.

**Comment by jarsen** [comment]
That's a fair point. Since throws doesn't encourage knowing about types, however, it seems to me it might just lead to contrived `ErrorType`s that all have some sort of `Unknown` case or are so generic they're not much better than a boolean flag. Unless the user makes assumptions about the throwing function.

**Comment by NachoSoto** [comment]
@jarsen somewhere in the codebase you'll have to make an assumption about the error, or do something about it. Better to do that closer to the erroring code :)

**Comment by NachoSoto** [comment]
How does everyone feel about this?

I'd say that we don't need to add anything. People can just use [`Result`](https://github.com/antitypical/Result/blob/master/Result/Result.swift#L26) to convert their `throw`ing functions, which seems like a better place for that kind of conversion than RAC.

**Comment by mdiep** [comment]
At the very least, this doesn't seem like a blocker for 4.0 since it would be adding APIs.

**Comment by NachoSoto** [comment]
👍🏻

**Comment by neilpa** [comment]
I agree with not doing this for now

**Comment by neilpa** [comment]
And maybe not ever. We should leverage the `Result` convenience methods and push people to them where appropriate.

**Comment by NachoSoto** [comment]
Yeah, totally agreed: we already have operators defined in terms of `Result`. How they're materialized / dematerialized is something for that framework.
