### ISSUE TITLE
can not unbind, so...?

### ISSUE THREAD

**Issue by atcuan** [ReactiveCocoa/ReactiveCocoa#2196]
Here is the thing:
In my ViewController 's `viewDidLoad` method, I bind a property to my ViewModel, such as
`RAC(self, data) = RACObserve(self.viewModel, data)`
when I received memory warning. I uninstall the `view` and `viewModel`, like this:
`_view = nil; viewModel = nil`
When next time go back to the ViewController will re-invoke  `viewDidLoad`, which means will bind 
`self.data` twice, will lead to crash. Is there some way to fix my issue? or my pattern is complete wrong?

**Comment by mdiep** [comment]
You should be able to replace it with this:

```objc
RAC(self, data) = RACObserve(self, viewModel.data)
```

Since `self.viewModel` changes, you want to observe `self`'s `viewModel.date`, not `self.viewModel`'s data.

**Comment by mdiep** [comment]
But you may need to use the property accessor to set your properties to `nil` so that the KVO notifications will fire.

**Comment by atcuan** [comment]
@mdiep, Thanks first !
Even I do as you said. It didn't solve my problem.

> But you may need to use the property accessor to set your properties to `nil` so that the KVO notifications will fire.

Yep, When I set my property to nil use accessor in `didReceiveMemoryWarning`, the KVO will fired. But it didn't break the RAC bind relationship. Cause the signal didn't disposed, the next time invoke `viewDidLoad` will run `RAC(self, data) = RACObserve(self, viewModel.data)` again, since self.data already bind once. will crash. 

I thought of move bind code to initialize phase. But it didn't sounds great.
What I wanted is there some way can avoid bind twice or when I handled the memory warning dispose the `RAC` bind signal?

**Comment by mdiep** [comment]
> Cause the signal didn't disposed, the next time invoke `viewDidLoad` will run `RAC(self, data) = RACObserve(self, viewModel.data)` again, since `self.data` already bind once. will crash.

Oh, right. Sorry I missed that detail.

Signals are meant to be declarative—so you should set them up once. It sounds like moving it to the initialization is the correct approach.

Note that you may want to do some work like [this method](https://github.com/ReactiveCocoa/ReactiveViewModel/blob/87af882faaf4606eb450507d8c1239c03d4045be/ReactiveViewModel/RVMViewModel.m#L85) to ignore values while the view isn't loaded.

**Comment by atcuan** [comment]
Finally I fix this problem by inject a signal called [`rac_willHandleMemoryWarningSignal `](https://github.com/atcuan/Reformer/blob/haioo/UIViewController%2BRACExtension/UIViewController%2BRACExtension.h#L35) for `UIViewController`, Then change bind like this:

`RAC(self, data) = [RACObserve(self, viewModel.data) takeUntil:self.rac_willHandleMemoryWarningSignal]`

 It's  just works for me. Any way, thank you :]
