### ISSUE TITLE
MutableProperty Questions

### ISSUE THREAD

**Issue by calebd** [ReactiveCocoa/ReactiveCocoa#2197]
In RAC 2, I had `dynamic` Swift properties and used a combination of `rac_valuesForKeyPath:observer:` and `didSet` to push values into child objects. I also used `didSet` to perform side effects like reloading a collection view after a view model change.

`MutableProperty` is not a value type, so mutating its `value` does not fire `didSet`. It's possible that the best solution is to move everything to RAC. That doesn't answer the "side effects" question though. If I use `<~` to bind a producer to a property can I perform related actions after each next?

Moving my properties to `MutableProperty` also exposes that implementation detail to API consumers such that they can no longer set properties directly, but instead have to go through a property's `value`. That feels a bit odd to me.

I haven't quite figured out what feels good in our code base. What are the recommended best practices around `MutableProperty`?

**Comment by iv-mexx** [comment]
You can use the [on](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/BasicOperators.md#injecting-effects) operator on the property's producer to achieve something similar to using `didSet`. 

I dont have a good answer for your second question though - I for myself just went with using `value` where necessary so far.

**Comment by calebd** [comment]
@iv-mexx Thanks! As a follow up, do you think it's better to use `DynamicProperty` for things like applying text to a label, or is it better to `start(next: ...)` on a property's producer, use `[weak textLabel]` and apply the text directly? It's about the same amount of code and avoids the use of key paths.

**Comment by jspahrsummers** [comment]
@calebd The latter, for sure. Properties are meant mostly for types that _you_ create, and I'd [recommend avoiding `DynamicProperty`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/61de8318e6f9bf91e1dbad9c1f5b4d66a094cca3/CHANGELOG.md#using-propertytype-instead-of-racobserve-and-rac) unless you absolutely need it.

**Comment by neilpa** [comment]
I'll also add that I've started some [UIKit bindings based on properties](https://github.com/neilpa/Rex/tree/master/Source/UIKit) . They're far from complete though and we should eventually have something like this in RAC directly.

**Comment by calebd** [comment]
@jspahrsummers That makes sense. Thanks for the help!

**Comment by SRandazzo** [comment]
Thanks for this thread, it was helpful! 

I am also getting familiar with RAC3/4 and wanted to know what i've written reflects the above suggestions/practices:

In my particular case, my var's "side effect" behavior was to store the data to disk whenever it's set (and attempt to fetch it upon initialization)

```Swift
    var activeUser: MutableProperty<User> = {
        //Retrieve from disk if possible, otherwise use a blank user
        let property = MutableProperty<User>(UserStorage.fetchOnDiskUser() ?? User())
        property.producer.start { (event: Event<User, NoError>) in
            if let user = event.value {
                UserStorage.securelyStoreUserToDisk(user)
            }
        }
        return property
    }()
```
