### ISSUE TITLE
DynamicProperty <~ SignalProducer requires trailing map

### ISSUE THREAD

**Issue by calebd** [ReactiveCocoa/ReactiveCocoa#2198]
I have a `SignalProducer<UIImage?, NoError>` that I want to bind to a `DynamicProperty`. For some reason the binding fails saying that the `<~` operator cannot be applied to those objects. The only way to make it work is to add a trailing `|> map { $0 }` which doesn't make any sense to me. The type of the returned `SignalProducer` is identical with or without the map. Has anyone else seen this behavior?

**Comment by jspahrsummers** [comment]
`DynamicProperty` must be bound to `AnyObject?` _exactly_. A type matching it isn't good enough.

**Comment by neilpa** [comment]
> The type of the returned SignalProducer is identical with or without the map.

Not exactly. The compiler's type-inference is kicking and implicitly upcasting to `AnyObject` and wrapping in an optional.
