### ISSUE TITLE
Question about Bag's implementation [Code spelunking]

### ISSUE THREAD

**Issue by raheelahmad** [ReactiveCocoa/ReactiveCocoa#2199]
I have been looking at RAC’s source code as a way to level up my Swift, and eventually contribute, and had a question.

Looking at an earlier version of `Bag`: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/a6b9ec45510549adc37509077a3759ff3f5f1fe2/ReactiveCocoa/Swift/Bag.swift 

- Why would `RemovalToken` be defined as a closure (and not just a `Uint?`)? Does it have to be a reference type?
- In the closure, why capture `key`’s value and set it to nil, instead of just returning `key`?

(Obviously, this is a low priority issue. Please let me know if I am misusing Issues.) 🙏🏽

**Comment by jspahrsummers** [comment]
Sorry I didn't get a chance to reply to this time. I've been very busy recently.

The TLDR is that the `Bag` identifiers could theoretically wrap around, so the use of the closure ensures that we only remove the original element, not another one that got inserted after it was already removed. Does that make sense?

The [current implementation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/197d3aa1f5a300c1bd449168a08b963f8affda3c/ReactiveCocoa/Swift/Bag.swift) is totally different, in any case.

**Comment by raheelahmad** [comment]
That makes sense. And it clarifies the current implementation as well.

---

Thanks for taking the time to reply. I closed it to bring down the issues count. ⏬
