### ISSUE TITLE
Operator is not a known binary operator

### ISSUE THREAD

**Issue by alexmaie** [ReactiveCocoa/ReactiveCocoa#2202]
I'm trying to use the new RAC 3.0 framework, but I have an issue when I try to use the pipe operator |> . As an example, I copied some code from one of the tests and wanted to run the code in a view controller. I'm always getting the error    Operator is not a known binary operator
```
     var producerA: SignalProducer<Int, NoError>!
        var producerB: SignalProducer<Int, NoError>!
        
        producerA = SignalProducer<Int, NoError>(values: [ 1, 2 ])
        producerB = SignalProducer<Int, NoError>(values: [ 3, 4 ])
        
        let producer = combineLatest([producerA, producerB])
        
        let result = producer |> collect |> single
```

**Comment by jalehman** [comment]
See the last comment of [this](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2115) issue -- I just ran into this myself. Doh!

**Comment by alexmaie** [comment]
Yeah, it works now :) .

Now this is embarrassing. My code was actually working because I had my own bridging header that was importing the old Reactive Cococa header file
