### ISSUE TITLE
Discourage global signals in the Design Guidelines

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2203]
Should we add a section to the best practices for using producers instead of signals for "global" event streams. `NSNotificationCenter` being the prime example (#1980, #2200).

@ReactiveCocoa/reactivecocoa thoughts?

**Comment by neilpa** [comment]
I'll do this post 3.0

**Comment by NachoSoto** [comment]
I disagree with this. There is a reason why `NSNotificationCenter` subscriptions are better represented with a producer, for sure, because they're controlled by the observer. But not all event streams are the same so that would be an invalid generalization IMO.

**Comment by mdiep** [comment]
I agree with @NachoSoto. I don't think that's a valid generalization.
