### ISSUE TITLE
ReactiveCocoa and Monad? (question)

### ISSUE THREAD

**Issue by daniel-shin1104** [ReactiveCocoa/ReactiveCocoa#2210]
I've been enjoying using RAC very much in all my code recently.

But as an imperative programmer, I didn't know a thing about FRP (or even FP for that matter) and thus blind to how RAC is internally implemented. So I delved in Haskell for a few days and learned many great concepts.

Is it safe to assume that `|>` notation is kind of like `>>=` operator in Haskell and that `Signal` and `SignalProducer` is conceptually an 'instance' of `Monad` in that it can be chained to pass data around while plugging in arbitrary manipulative functions given that having types aligned and also in that error propagation is implemented? 

I'm just trying to understand RAC and this whole FRP thing better. Please help! Thanks :)

**Comment by lingoer** [comment]
Yes, Signals are monad, but |> is not the corresponding 'bind' function(>>=) for this monad.
'|>' is much like the 'apply' it chains functions which takes 'Signal'  Type as input.
while >>= chains functions that should take other type 'T' as input and produce 'Signal'.

**Comment by joshaber** [comment]
In the context of RAC, `flatten` is monadic bind (`>>=`).

See #1842 for more discussion on this, and how `SignalProducer` has multiple monad instances (!).

**Comment by daniel-shin1104** [comment]
Thank both of you for clarification.

So I guess since `flatten` is an equivalence of monadic bind, by extension `flatMap` is also considered a monadic bind?

Having said that, I see many patterns that require monadic binds (specifically `flatMap`) chained to form a complete operation like complex networking calls etc.

And this being a recurring pattern, Haskell provides `do` construct as a syntactic sugar. Is there an equivalence to such in RAC? My code starts to look pretty ugly every time I introduce some sort of chained asynchronous operations...

**Comment by joshaber** [comment]
Something like `do` would be great if it were doable and not horribly awkward!

**Comment by daniel-shin1104** [comment]
What I meant was more in the line of having an operator that resembles something like `>>=`. For starters like me, the purpose of `flatMap` was really vague despite its usefulness. Conceiving `flatMap` as something of monadic bind did require for me a deeper understanding of the framework and also for some others too I believe, like this discussion [#448](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/448)

**Comment by lingoer** [comment]
`do`+1
and `then` ?

**Comment by sebastiangrail** [comment]
> In the context of RAC, `flatten` is monadic bind (`>>=`).

isn't `flatMap` monadic bind?

**Comment by joshaber** [comment]
>isn't flatMap monadic bind?

Yup, it's one implementation. And note that it's implemented in terms of `flatten`:
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/6c37b5ef416799a3a2a61ff78f051d5deb0d76b2/ReactiveCocoa/Swift/SignalProducer.swift#L942
