### ISSUE TITLE
missing dependencies build failure

### ISSUE THREAD

**Issue by hunleyexpress** [ReactiveCocoa/ReactiveCocoa#2211]
I followed the instructions to setup per the readme on latest from master (e3c310110d325ddd6cca69cb489f1d7ff3ca71b3). When I add the ReactiveCocoa.xcodeproj to my project and build it fails because it doesn't know how to build the result submodule or box submodule created through Carthage. Adding a simple dependencies group in the main xcodeproj and adding those dependent projects fixes the issue. I can create a pull request, but wasn't positive this was right and why no one else appears to have this issue. I am using xcode 6.4 (6E35b) and building for iOS in an objective-c project.

**Comment by brow** [comment]
Is it possible you skipped this step in the installation instructions?
> 2. Run script/bootstrap from within the ReactiveCocoa folder.

**Comment by hunleyexpress** [comment]
Nope. I ran that. I wasn't sure if it needed to be run with full export context so ran it first with a ". Script/bootstrap" which failed so ran again without the period/start.

**Comment by hunleyexpress** [comment]
I found that even though it all built it crashed on startup because it couldn't load the Box framework dylib. So, I started from scratch and followed the steps. It has the Box.framework and Result.framework in the supporting files and link library list, but it does not know how to build them (my problem from before). It complains in the Mac build, but not the iOS build (because the mac box.framework and result.framework are linked and in the supporting files). I had to add Result.xcodeproj and Box.xcodeproj to my projects dependent libraries just like adding ReactiveCocoa. After that I run into the fact that you can't build and run it from an Objective-C app because of libswiftcore.dylib. I thought ObjC still worked but wasn't getting new features. I am fully willing to believe I am doing something obviously wrong, but not clear what. Going to try using ReactiveCocoa 2.x

**Comment by ikesyo** [comment]
@hunleyexpress 

> After that I run into the fact that you can't build and run it from an Objective-C app because of libswiftcore.dylib. I thought ObjC still worked but wasn't getting new features. I am fully willing to believe I am doing something obviously wrong, but not clear what.

If your target does not contain Swift code at all, you should set “Embedded Content Contains Swift code” (`EMBEDDED_CONTENT_CONTAINS_SWIFT`) to “Yes” for your target build settings.

**Comment by hunleyexpress** [comment]
That is very useful info. Seems like this would be good to add to the
README.md
