### ISSUE TITLE
Rename `T` and `E` to `Value` and `Error`

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2212]
Should we follow the lead that the stdlib made with collection changes in beta 3?

**Comment by NachoSoto** [comment]
I wouldn't be against this.

**Comment by kastiglione** [comment]
What about additional value types, `U`, `V`?

**Comment by neilpa** [comment]
I was initially thinking about the event/signal generics. However, we could probably come up with better context dependent names for those as well. The one exception being the `combineLatest`/`zip` overloads.

**Comment by JaviSoto** [comment]
I think this is the type of thing that aids the newcomers. I'm really glad that Apple is doing this for the Swift stdlib as well.
I'm not as worried about the generic types for the rest of the methods, sometimes maybe `V` will be good enough™, but we can always considered names such as `TransformedValue`
