### ISSUE TITLE
ReactiveCocoa 2.5 with Carthage

### ISSUE THREAD

**Issue by tetriscode** [ReactiveCocoa/ReactiveCocoa#2213]
I'm trying to build ReactiveCocoa 2.5, and ZipZap with Carthage. ZipZap can be imported for simulator and device and compiles successfully. RC can only be built for device. Headers can not be found when compiling for device. 
I'm not sure if this is a project config issue. It appears to have occurred once I ran carthage update.

**Comment by mdiep** [comment]
Can you share your `Cartfile`, `Cartfile.resolved`, the output of `carthage`, and the error from the xcodebuild log?

**Comment by tetriscode** [comment]
Cartfile: 
github "ReactiveCocoa/ReactiveCocoa" == 2.5
github "pixelglow/ZipZap"
Cartfile.resolved: 
github "ReactiveCocoa/ReactiveCocoa" "v2.5"
github "pixelglow/ZipZap" "8.0.4"

Output: 
*** Fetching ReactiveCocoa
*** Fetching ZipZap
*** Checking out ZipZap at "8.0.4"
*** Downloading ReactiveCocoa at "v2.5"
*** xcodebuild output can be found in /var/folders/5z/j_4kts6s68bgy3k6_rpv1xt00000gp/T/carthage-xcodebuild.6e7GCw.log
*** Building scheme "ZipZap (iOS Framework)" in ZipZap.xcodeproj
*** Building scheme "ZipZap (OS X Framework)" in ZipZap.xcodeproj

![screen shot 2015-07-23 at 11 07 06 pm](https://cloud.githubusercontent.com/assets/242747/8867496/96bf3b94-318f-11e5-80e5-85973ee9a06b.png)

If I start this all over with a fresh project, it works. Or if I build for device it works. In the screenshot above, you can see it finds the ZipZap framework just fine, but complains about ReactiveCocoa.h 

![screen shot 2015-07-23 at 11 09 30 pm](https://cloud.githubusercontent.com/assets/242747/8867507/eacf4a58-318f-11e5-81c2-de50b93c8b82.png)

![screen shot 2015-07-23 at 11 10 12 pm](https://cloud.githubusercontent.com/assets/242747/8867516/031b73ac-3190-11e5-9083-3de254657658.png)

**Comment by tetriscode** [comment]
Its not clear to me how this happened, but closing Xcode, then deleting ~/Library/Developer/Xcode/DerivedData/{ProjectName}-* made it work again.
