### ISSUE TITLE
Comparing Signals inner values

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2215]
I have the following:

```
let x1 = SignalProducer <Model, Error>
let x2 = SignalProducer <Model, Error>
```

The `Model` is defined as:

```
struct Model : Comparable {
  let version : Int
}
```

I want to compare both inner values and return a `SignalProducer` with the one with higher version. I tried with `combineLatest`, `zipWith`, but it doesn't feel the right way to go with. Any suggestions?

**Comment by neilpa** [comment]
`combineLatest`/`zip` followed by a `map` are reasonable options depending on if you want all values or pairwise. What don't you like about that approach?

**Comment by RuiAAPeres** [comment]
Maybe it's just my lack of experience in FP. I didn't completely understood your reasoning:

>  depending on if you want all values or pairwise

**Comment by RuiAAPeres** [comment]
So in the end:

```
x1.combineLatestWith(x2).map(max)
```
Thanks @neilpa!  :cake:

**Comment by neilpa** [comment]
I was just mentioning the difference between `combineLatest` and `zip`. The former sends a tuple of the most recent values whenever *any* of the inner signals sends a new value. The latter only sends the _nth_ value once *all* inner signals have sent at least _n_ values
