### ISSUE TITLE
Carthage update Xcode Beta 4

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2216]
When I do:

```
carthage update --platform ios
```

I am getting loads of warnings in the following format:

```
<module-includes>:1:1: warning: umbrella header for module 'ReactiveCocoa' does not include header 
'/Users/ruiperes/Documents/Project/X/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Objective-C/MKAnnotationView+RACSignalSupport.h'
.
.
.
```

Once inside the project:

<img width="509" alt="screen shot 2015-07-24 at 23 55 42" src="https://cloud.githubusercontent.com/assets/949286/8886282/8d4c09ea-325f-11e5-91cd-8a2e3ec844ff.png">

On the cartfile: `github "reactivecocoa/ReactiveCocoa" "swift2"`

**Comment by RuiAAPeres** [comment]
This issue my be related to this commit https://github.com/ReactiveCocoa/ReactiveCocoa/commit/fef4edea8c92363509bb16e4a2613b7a3987d9de#diff-8fad1d07697f66d8d17da19478832e4fR65 cc @MarcoSero

**Comment by RuiAAPeres** [comment]
Using:

`github "reactivecocoa/ReactiveCocoa" "fc54992143255e085371e1bb2e638931e19680e0"`

Works as expected, so I think there is an issue with the above mention commit.

**Comment by MarcoSero** [comment]
Mhm that `#ifdef` was to avoid importing UIKit headers in the watchOS target.

**Comment by ikesyo** [comment]
@MarcoSero watchOS has a subset of UIKit, so that might be the reason.

**Comment by MarcoSero** [comment]
> watchOS has a subset of UIKit, so that might be the reason.

I didn't know that. Where's it documented?

If I had to guess, it seems that when running `carthage update --platform iOS`, `TARGET_OS_WATCH` is defined and thus UIKit extensions don't get imported.

**Comment by jspahrsummers** [comment]
`#elif` does not have the same semantics as `#ifdef`. `#elif` behaves like `#if`, which is a condition check.

**Comment by MarcoSero** [comment]
Ah, makes sense, I missed that!

Would a simple `#elif defined(__IPHONE_OS_VERSION_MIN_REQUIRED)` fix the problem then?

**Comment by ikesyo** [comment]
@RuiAAPeres #2218 was merged, could you check the current `swift2` branch?

**Comment by RuiAAPeres** [comment]
Working like a charm @ikesyo. kudos.

**Comment by ikesyo** [comment]
:sparkling_heart:

**Comment by MarcoSero** [comment]
Thank you @ikesyo :star2:
