### ISSUE TITLE
Build failed using carthage with Xcode Beta 4

### ISSUE THREAD

**Issue by rjourde** [ReactiveCocoa/ReactiveCocoa#2217]
I am using Xcode 7.0 beta, with the following dependencies in my Cartfile:
github "reactivecocoa/ReactiveCocoa" "swift2"
When I run carthage update, I get the following error:

$ carthage update
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "932ac1aabf6d881ead74c4e6911d1271e95d2859"
*** Checking out ReactiveCocoa at "a7f8b028253b30a1184d9c4faa838b7c98606b0e"
*** xcodebuild output can be found in /var/folders/yd/d9k55g554xq0rgfdm9tbxy2r0000gn/T/carthage-xcodebuild.NFa3wH.log
*** Building scheme "Result-iOS" in Result.xcodeproj
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.0'
A shell task failed with exit code 65

Any ideas?

**Comment by mdiep** [comment]
1. Do you have a code signing certificate installed?
2. Is there anything useful in the xcodebuild output?

**Comment by jsslai** [comment]
Did you try to change the ReactiveCocoa-iOS target's Code Signing Identity? I had to change it to Automatic (iOS Developer) because it had changed somehow. Also this might be related: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2218

**Comment by rjourde** [comment]
From the xcodebuild output log:

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos9.0

=== BUILD TARGET Result-iOS OF PROJECT Result WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.0'

@jsslai: I tried to change to Automatic (iOS Developer) and I still have the issue. So I guess it is mandatory to have a valid signing certificate to add the framework with Carthage (#235).

**Comment by ikesyo** [comment]
Carthage/Carthage#235?

**Comment by rjourde** [comment]
@ikesyo: Yes.

Thanks guys.
