### ISSUE TITLE
Is there analog of ReplayLast in RAC3? 

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2222]
ReplayLast was very helpful in BDD tests to separate context initialization from an actual tests cases' its. Is there anything similar in RAC3?

**Comment by nikita-leonov** [comment]
I know how to achieve similar behavior with SignalProducer but it is a lot of boiler plate code.

**Comment by ikesyo** [comment]
[As noted in the CHANGELOG](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/a96af8c2c06f9e07ac93a0c0dcf9bf10abe0075a/CHANGELOG.md#using-signalproducerbuffer-instead-of-replaying), you could/should use `SignalProducer.buffer` with just 1 capacity.

**Comment by nikita-leonov** [comment]
O wow, I totally missed this important piece of information. Apparently there is a ton of answers on the questions that I had. Thanks.
