### ISSUE TITLE
Operator is not a known binary operator

### ISSUE THREAD

**Issue by aputinski** [ReactiveCocoa/ReactiveCocoa#2224]
Trying out the latest `swift2` branch, when I write the following code (lifted from the REDME):

```swift
let textField = UITextField()
let searchStrings = textField.rac_textSignal().toSignalProducer()
  |> map { text in text as! String }
```

I get the following error:

`Operator is not a known binary operator`

I'm building with Carthage on Xcode 7 Beta 4

**Comment by ikesyo** [comment]
`swift2` branch is redesigned with Protocol Extentions and there is no `|>` pipe operator anymore. You could just call `.map()` method instead of that operator and free functions.

**Comment by aputinski** [comment]
Thanks!
