### ISSUE TITLE
swift support help

### ISSUE THREAD

**Issue by shams-ahmed** [ReactiveCocoa/ReactiveCocoa#2225]
does rac v3 support struct and classes etc... for example "rac_valuesForKeyPath" method expects a NSObject type but mine is just a "class". passing self result in a error. in this situation should the class by a subclass of NSObject?

```
class SSShowRoomViewModel {
    var hasNewContentSignal: RACSignal?
    
    init() {
        hasNewContentSignal = RACSignal.rac_valuesForKeyPath("controller.model", observer:self)
    }
}
```

**Comment by NachoSoto** [comment]
`rac_valuesForKeyPath:` is implemented using KVO, which is part of the Objective-C runtime, so only available for `NSObject` subclases.

You'll have to inherit that, or consider a more explicit and type-safe approach like manually forwarding events with a `Signal`.

**Comment by shams-ahmed** [comment]
@NachoSoto thanks ill use NSObject subclass. on a side note 'sendNext:" method allow to send AnyObject would the swift classes work fine?
