### ISSUE TITLE
Manually control SignalProducer

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2228]
Using `NSURLSession`'s function:

```
func rac_dataWithRequest(request: NSURLRequest) -> ReactiveCocoa.SignalProducer<(NSData, NSURLResponse), NSError>
```

When the `NSURLResponse` brings a `statusCode == 304` I would like to `complete` the signal . Would something like this be the appropriate way of doing so:

```
session.rac_dataWithRequest.filter . take (1) . filter { // filter out the statusCode } 
```

Or is there a way to manually tell the `SignalProducer` to `complete`.

**Comment by avalanched** [comment]
you could simply add that in the rac_dataWithRequest implementation

	func rac_dataWithRequest(request: NSURLRequest) -> ReactiveCocoa.SignalProducer<(NSData, NSURLResponse), NSError> {
		return SignalProducer { sink, _ in
			NSURLConnection.sendAsynchronousRequest(request, queue: queue, completionHandler:{ (response: NSURLResponse!, data: NSData!, error: NSError!) -> Void in
		    
				// error check
			
				sendNext(sink,(data,response))
			
				if let httpResponse = response as? NSHTTPURLResponse {
					if httpResponse.statusCode == 304 {
						sendComplete(sink)
					}
				}
			})
		}
	}

**Comment by nomothetis** [comment]
Use `takeWhile`. Something like this (still using Swift 1.2 syntax):

```
session.rac_dataWithRequest
    |> takeWhile { (data, response) in
        if let httpResponse = response as? NSHTTPURLResponse {
            if httpResponse.statusCode == 304 {
                return false
            }
        } else {
            return true
        }
}
```

**Comment by RuiAAPeres** [comment]
That's a good one @nomothetis thanks!
