### ISSUE TITLE
Swift 2 branch and Cocoapods

### ISSUE THREAD

**Issue by bruceflowers** [ReactiveCocoa/ReactiveCocoa#2229]
Does anyone have any tips on how to get the latest swift 2 development branch to install via Cocoapods?  

I know the project as a whole doesn't support them anymore, but maybe someone here has a podspec that already works?  Would be much appreciated...

**Comment by tomtaylor** [comment]
I'd love to know about this as well. @bruceflowers did you get anywhere with it?

**Comment by rexmas** [comment]
+1

**Comment by bruceflowers** [comment]
@tomtaylor I didn't end up using pods after all - ended up converting the whole build to Carthage. Still would be useful to know how to do it via Pods because that may end up being necessary again at some point.

**Comment by tomtaylor** [comment]
@bruceflowers ouch! I'm not quite ready to do that yet. I'll update here if I get a chance to port the podspec.

**Comment by juggernate** [comment]
:+1:

**Comment by tomtaylor** [comment]
OK, this works for me: https://gist.github.com/tomtaylor/bd1dffe0ea59388fdcf2

**Comment by bruceflowers** [comment]
Closing - for now, I'm sticking with a Carthage build but it *may* become necessary to revisit down the road.  Thanks everyone for your input!

**Comment by shams-ahmed** [comment]
Did anyone manage to get this to work in the end?

**Comment by jackywang135** [comment]
pod 'ReactiveCocoa', '~> 4.0.0-RC.1'
