### ISSUE TITLE
Poke holes in this Future<T>

### ISSUE THREAD

**Issue by russbishop** [ReactiveCocoa/ReactiveCocoa#2231]
Not having had time to test it, here is my second attempt at a `Future<T>`; some goals include not making consumers call `start` nor specify the type of the error but the biggest goal is that you can hook up to `signal` at any later time and your signal will get a value. 

I'm sure I am missing some stuff here, pointers would be appreciated. 

I also understand RAC is trying to solve a bigger problem at a higher level of abstraction than Promises/Futures, but in some cases I'm just wrapping an existing async block-based API and want to keep it simple in both the wrapper and for consumers of the value. 

```swift
public final class Future<T> {
    public typealias EventType = Event<T, NSError>
    public typealias SignalType = Signal<T, NSError>

    private let _changeSink: SinkOf<EventType>
    private let _producer: SignalProducer<T, NSError>

    public var signal: SignalType {
        var sig: SignalType?
        _producer.startWithSignal { (s, _) -> () in
            sig = s
        }
        return sig!
    }

    public init(_ f:(fulfill:(T)->Void, reject:(NSError)->Void) -> Void) {
        (_producer, _changeSink) = SignalProducer<T, NSError>.buffer(1)
        dispatch_background {
            f(fulfill: { value -> Void in
                sendNext(self._changeSink, value)
            }, reject: { error -> Void in
                sendError(self._changeSink, error)
            })
        }
    }

    deinit {
        sendCompleted(_changeSink)
    }
}
```

**Comment by neilpa** [comment]
> some goals include not making consumers call `start`

What's the problem with this? It gives the consumer fine-grained control over when the underlying work should be started.

> nor specify the type of the error

This encourages people to ignore errors which is a Bad Thing :tm:

> but the biggest goal is that you can hook up to signal at any later time and your signal will get a value.

This sounds a lot like a property [`Property`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/197d3aa1f5a300c1bd449168a08b963f8affda3c/ReactiveCocoa/Swift/Property.swift#L1-L11)

**Comment by russbishop** [comment]
@neilpa 

>What's the problem with this? It gives the consumer fine-grained control over when the underlying work should be started.

It also allows them to start the underlying work multiple times, creating duplicates. 

>This encourages people to ignore errors which is a Bad Thing :tm:

It also causes a proliferation of type parameters and I don't see how it forces anyone to deal with errors... you don't have to handle the error case when observing a signal. The end result is a crash either way.

>This sounds a lot like a property Property

I think you're right, that is probably what I should be returning if I want that behavior.


Thanks for the comments. I'm starting to get a handle on this stuff; if I do I'll try to write something up from the perspective of "hey you're using futures, here's how to rethink that with RAC".

**Comment by neilpa** [comment]
> It also allows them to start the underlying work multiple times, creating duplicates.

Sometimes this is desirable, e.g. if it fails and you want to retry. 

> It also causes a proliferation of type parameters

Why is this bad? It tells you exactly what errors you can get which is especially nice if they're an enum.

> and I don't see how it forces anyone to deal with errors... you don't have to handle the error case when observing a signal.

True, but if you need to bind to something that expects `NoError` you are then explicitly forced to make a decision, even if that is just to ignore it.

**Comment by russbishop** [comment]
Thanks for answering; it is starting to make sense.
