### ISSUE TITLE
Using unsafeCocoaAction leads to memory leak

### ISSUE THREAD

**Issue by almassapargali** [ReactiveCocoa/ReactiveCocoa#2233]
It's very easy to introduce retain cycle using unsafeCocoaAction, since CocoaAction and Action retains each other.
Also it has naming issue: it suggests to set your own cocoa action to this property of your input isn't Void, thus making it not unsafe anymore.

**Comment by ndonald2** [comment]
+1 to this. The automatic lazy creation of `unsafeCocoaAction` clearly creates a memory leak:

```swift
public lazy var unsafeCocoaAction: CocoaAction = CocoaAction(self) { $0 as! Input }
```

The `CocoaAction` retains `self`, which after the lazy instantiation retains the `CocoaAction`.

**Comment by ndonald2** [comment]
Specifying `unowned` on `action` in the initializer of `CocoaAction` appears to fix the retain cycle:

```swift
	public init<Input, Output, Error>(_ action: Action<Input, Output, Error>, _ inputTransform: AnyObject? -> Input) {
		_execute = { [unowned action] input in
			let producer = action.apply(inputTransform(input))
			producer.start()
		}

		super.init()

		disposable += action.enabled.producer
			.observeOn(UIScheduler())
			.startWithNext { [weak self] value in
				self?.willChangeValueForKey("enabled")
				self?._enabled = value
				self?.didChangeValueForKey("enabled")
			}

		disposable += action.executing.producer
			.observeOn(UIScheduler())
			.startWithNext { [weak self] value in
				self?.willChangeValueForKey("executing")
				self?._executing = value
				self?.didChangeValueForKey("executing")
			}
	}
```

If that seems like a legit fix I can submit a pull request.

**Comment by almassapargali** [comment]
Using `unowned` in `CocoaAction` would make whole `CocoaAction` thing unsafe. I think we should just initialise `unsafeCocoaAction` this way:
```
public lazy var unsafeCocoaAction: CocoaAction = { [unowned self] in
   CocoaAction(self) { $0 as! Input }
}
```
This way, only `unsafeCocoaAction` is unsafe.

**Comment by ndonald2** [comment]
Good point, that seems safer. Though in Swift 2.2 I have repeatedly run into [this issue](http://stackoverflow.com/questions/24177973/why-self-is-deallocated-when-calling-unowned-self) using `unowned` in closure-based lazy variable initialization on classes derived from `NSObject`, so it might need to be `weak` instead.
