### ISSUE TITLE
No such module Result / Box

### ISSUE THREAD

**Issue by Mads-Andersen** [ReactiveCocoa/ReactiveCocoa#2234]
I have followed the installation instructions as described. Builds fails with either "No such module 'Result'" and "No such module 'Box'". What am I doing wrong?

**Comment by neilpa** [comment]
I'm going to assume you set this up manually. You need to also add the Box and Result dependencies to your project like you did for ReactiveCocoa. The `script/bootstrap` should've checked out those at `ReactiveCocoa/Carthage/Checkouts/{Box|Result}`. Then just add the .xcodeproj file and update the embedded binaries in the same manner.

**Comment by iandundas** [comment]
If this is the case for everyone installing manually, can it be added to "Getting started" in the Readme? I don't think it's an obvious step (I also got stuck).

**Comment by Mads-Andersen** [comment]
Thank you! It worked
