### ISSUE TITLE
SignalProducer does not send new events after catch. 

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2235]
It seems that catch does not work as I expect it to work, so I need some clarification. Here is an example project with unit-tests — https://github.com/nikita-leonov/rac3-suppress-error-issue. One of the tests is failing:
```
waitUntil { complete in
    stableProducer.start(next: { _ in
        complete()
    })
    demoStage.sendError()
    demoStage.sendNext()
}
```

I expected it to work properly, as stableProducer implemented as following:
```
public func stableProducer() -> SignalProducer<Void, NSError> {
    return faultyProducer() |> catch { _ in self.faultyProducer() }
}
```

Am I missing something? 

There are other tests as well that show how faultyProducer works as well as stableProducer receiving errors etc. Hopefully it is not a bug but just my misunderstanding.

**Comment by neilpa** [comment]
The problem is `DemoStage` shares one signal across all the producers. Once you send an error event on the inner signal it's going to terminate. All the subsequent observers that attach to the signal won't see any events (except an immediate `Interrupted`) post-termination.

**Comment by nikita-leonov** [comment]
Is there a better way to implement sustainable pipes? I used sinks to dispatch delegate calls to signals. As said in design document signal will be invalidated after the error. Have no idea how to approach it in a better way then. Having everything in sendNext does not look nice.

**Comment by neilpa** [comment]
You could make your pipe send values of `Event<T, NSError>` and dematerialize them into the returned producers.

**Comment by nikita-leonov** [comment]
Sounds like a good plan, in this case the fact that underlaying signals are permanent will be explicit, as there will be no NoError type in signature. Those who will need a error will unwrap/dematerialize them.
I can not find a way to manually crate Event to send into the sink, could you clarify how it could be done?  
Btw the whole materialize / dematerialize section of documentation is absent in RAC3.

**Comment by nikita-leonov** [comment]
Found it. Apparently I need to import Box as well to instantiate it as following:
```
let event: Event<Void, NSError> = Event.Error(Box(NSError()))
```

@neilpa  Is this how you imagined it as well?

**Comment by nikita-leonov** [comment]
Suggested solution fixed the problem. Here is what I ended up with:
```
public class DemoStage {
    private var faultySignal: Signal<Event<Void, NSError>, NoError>
    private var faultyPipe = Signal<Event<Void, NSError>, NoError>.pipe()
    
    public init () {
        faultySignal = faultyPipe.0
    }
    
    public func sendError() {
        let value: Event<Void, NSError> = Event.Error(Box(NSError()))
        ReactiveCocoa.sendNext(faultyPipe.1, value)
    }
    
    public func sendNext() {
        let value: Event<Void, NSError> = Event.Next(Box(()))
        ReactiveCocoa.sendNext(faultyPipe.1, value)
    }
    
    public func faultyProducer() -> SignalProducer<Void, NSError> {
        return SignalProducer { (observer, compositeDisposable) in
            let disposable = self.faultySignal |> dematerialize |> observe(observer)
            compositeDisposable.addDisposable(disposable)
        }
    }
    
    public func stableProducer() -> SignalProducer<Void, NSError> {
        return faultyProducer() |> catch { _ in self.faultyProducer() }
    }
}
```
