### ISSUE TITLE
flattenMap that doesn't close on error

### ISSUE THREAD

**Issue by olenhad** [ReactiveCocoa/ReactiveCocoa#2241]
I have the following pipeline. I set it up once in my `viewDidLoad`.

``` 
   [[self.loginButton rac_signalForControlEvents:UIControlEventTouchUpInside] 
     flattenMap:^RACStream *(id sender) {
        @strongify(self);
        if (![self fieldsValid]) {
            return [RACSignal error:[NSError login_invalidCredentialsError]];
        }
        return [managerLogin loginWithAccount:account password:password];
    }];
```

When an error occurs, the Signal after `flattenMap` will be closed. So when I tap the button again, nothing would happen. However, I don't want the Signal after `flattenMap` to close. What's the best way to write this kind of flow? Should I `materialize` the Signal, and check for errors downstream in the pipeline? Or is there any operator that would perform the block in the flattenMap, and not close if an error occurs?

**Comment by neilpa** [comment]
If you want to handle errors and successes holistically in a downstream `map` block then `materialize` is probably the way to go.

Alternatively, you may be able to convert the login signal to a `RACCommand` and attach that to the buttons `rac_command` property. However, commands in RAC2 aren't always the easiest things to work with.
