### ISSUE TITLE
Carthage update for master failing

### ISSUE THREAD

**Issue by bruceflowers** [ReactiveCocoa/ReactiveCocoa#2247]
Not sure if this is a known issue yet, or even just something I'm doing/expecting to do incorrectly - when running carthage update on master, things work nicely until we hit this (carthage 0.6.0, xcode beta4):

*** Building scheme "Result-iOS" in Result.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/bruceflowers/Documents/git/ReactiveCocoa/Carthage/Checkouts/Result/Carthage/Checkouts/Box/Box/Box.swift
	CompileSwift normal x86_64 /Users/bruceflowers/Documents/git/ReactiveCocoa/Carthage/Checkouts/Result/Carthage/Checkouts/Box/Box/MutableBox.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by mdiep** [comment]
That's a fairly old version of `carthage`, so you might try a newer one. But you haven't provided the actual build error, so it's hard to say what's gone wrong. You probably need to look in the xcodebuild log file.

**Comment by bruceflowers** [comment]
Sorry - updated carthage to 0.7.5 as you were responding - running El Capitan as well, which brew has issues building/installing the latest Carthage.  I'll try getting a recent version running and put up an xcodebuild log after that

**Comment by bruceflowers** [comment]
Ok - I think I see what happened. Master only builds against swift 1.2?

**Comment by mdiep** [comment]
Yup. I think you need to use the `swift2` branch if you want to use Swift 2. :smile:

**Comment by bruceflowers** [comment]
For some reason that wasn't jumping out at me from the documentation that's already up.

Thanks for being so quick to help!
