### ISSUE TITLE
How to flatMap(.Latest) SignalProducer with NoError to another one with error type provided?

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2249]
Current ```flatMap``` implementation expects input and output SignalProducers to have the same error type. Is there a way to workaround this?

I am currently have two signals ```discoverPeripheral: SignalProducer<CBPeripheral, NoError>```  and ```connectPeripheral: SignalProducer<CBPeripheral, NSError>```. My goal that I was trying to achieve with ```flatMap``` is to create a signal producer ```discoverAndConnect: SignalProducer<CBPeripheral, NSError>```.

**Comment by ikesyo** [comment]
`promoteErrors()`?

**Comment by nikita-leonov** [comment]
This is it. Now I do understand scenario of use. I just use promoteErrors before flatMap to adjust it to an expected type of SignalProducer. Thanks.

**Comment by ikesyo** [comment]
:+1:

**Comment by i-schuetz** [comment]
How to do this in the opposite direction, i.e. from a specific error to `NoError`? I also don't find `promoteErrors()`, was this removed in recent versions? Can open a new issue if necessary...
