### ISSUE TITLE
[Question] Receive signals only when not touching a view

### ISSUE THREAD

**Issue by code-wolf** [ReactiveCocoa/ReactiveCocoa#2251]
I want to receive a signal only when a view is currently not being touched.
The most trivial way to accomplish this from my point of view is to create signals for touchesBegan:withEvent and touchesEnded:withEvent, respectively, set a flag in these methods that states that the user is currently touching the screen and use this flag for flitering a valid signal.

    // Set a flag when user starts touching
    RACSignal *touchesBegan = [self rac_signalForSelector:@selector(touchesBegan:withEvent:)];
	[touchesBegan subscribeNext:^(id x) {
		self.viewModel.isTouching = YES;
	}];

    // Reset the flag when touches ended
    RACSignal *touchesEnded = [self rac_signalForSelector:@selector(touchesEnded:withEvent:)];
	[touchesEnded subscribeNext:^(id x) {
		self.viewModel.isTouching = NO;
	}];

    // Execute signal only when the screen is not touched
    RACSignal *signal = RACObserve(self.viewModel, coordinate);
	[[signal filter:^BOOL(id value) {
		return !self.viewModel.isTouching;
	}] subscribeNext:^(NSValue *x) {
		// Execute some code while user is not touching the view ...
	}];

This method basically works but seems a bit clumsy and "not-reactive" to me. Are there any other options   that I have to accomplish this?

thanks!

**Comment by rpowelll** [comment]
You could merge the `touchesBegan` and `touchesEnded` signals into a `isTouching` signal like so:

```objc
RACSignal *touchesBegan = [[self rac_signalForSelector:@selector(touchesEnded:withEvent:)] 
    map:^(NSNumber *)(id value) { 
        return @YES;
    }];

RACSignal *touchesEnded = [[self rac_signalForSelector:@selector(touchesBegan:withEvent:)] 
    map:^(NSNumber *)(id value) { 
        return @NO;
    }];

RACSignal *isTouching = [RACSignal merge:@[ touchesBegan, touchesEnded ]];
```

That might be a little off since I haven't worked with the legacy API in a while, but you get the idea.

The result should be something like this:

```
touchesBegan |-Y----Y---|
touchesEnded |----N---N-|
isTouching   |-Y--N-Y-N-|
```

With that signal, you can do something like this

```objc
RACSignal *signal = RACObserve(self.viewModel, coordinate);

[[[RACSignal 
    combineLatest:@[ signal, isTouching ]
    map: ^(id value, NSNumber touching) {
        return [isTouching boolValue] ? value : nil;
    }] ignoreNil] subscribeNext:^(id value) {
        // Do some work
    }];
```

**Comment by code-wolf** [comment]
Thanks for the reply and the great description! That sounds very good, I'll go this way

**Comment by rpowelll** [comment]
:+1: No problem
