### ISSUE TITLE
[Question] Customizing table view cell

### ISSUE THREAD

**Issue by ldantona** [ReactiveCocoa/ReactiveCocoa#2252]
Hi all,

I have a table view with separators between cells and I want the separator after the last cell not to be visibile.
As I'm modelling table cells with view models, is the following approach correct? I'm not sure whether this is a proper use of map.
```objective-c
@implementation MenuTableViewCell

- (void)awakeFromNib {
    
    [super awakeFromNib];
    
    RAC(self.lblTitle, text) = [RACObserve(self, viewModel.title) map:^id(id value) {
        
        if([self.viewModel.title isEqualToString:@"NEWS"]) {
            self.separator.hidden = YES;
        }
        
        return value;
    }];
    
    RAC(self.imgIcon, image) = RACObserve(self, viewModel.icon);
}
```
Many thanks,
DAN

**Comment by mnmaraes** [comment]
`map` is meant to transform values. I usually try to avoid inserting side-effecting code inside a `map` block. And since you're not transforming the value at all, it's probably not what you want. Use `doNext` instead.

Like so:
```Objective-C
__weak MenuTableViewCell *weakSelf = self
[RACObserve(self, viewModel.title) map:^(NSString *title) {
    MenuTableViewCell *strongSelf = weakSelf

    if([title isEqualToString:@"NEWS"]) {
        strongSelf.separator.hidden = YES;
    }
}];
```

Also, watch out for [retain cycles](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/Legacy/MemoryManagement.md) when capturing `self`.

**Comment by mnmaraes** [comment]
The docs also talks about a different (more RACish) way of doing what you want, however.

```Objective-C
RACSignal *shouldShowSeparatorSignal = [RACObserve(self, viewModel.title) map:^NSNumber *(NSString *value) { 
    return [title isEqualToString:@"NEWS"];
}];

[self.separator rac_liftSelector:@selector(setHidden:) withSignals: shouldShowSeparatorSignal, nil];
```

No weakifying or strongifying of `self` necessary.

**Comment by ldantona** [comment]
Hi @mnmaraes, thanks for your answers!
I personally I find the second solution more hard to read and maintain, but maybe it's just a matter of getting used to.
