### ISSUE TITLE
Array of Signals

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2253]
What would be the best approach to have an array of Signals and while one is being executed, all the others wait. Once it's done (either completed, or error), the next one would start.  So it's would be essentially a Queue with a "maxConcurrentOperationCount" of 1.

**Comment by mnmaraes** [comment]
What you're describing is the Concat operation. Depending on your needs (and API) there are a few ways to use it. Check out the [Docs](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/BasicOperators.md#concatenating).

**Comment by RuiAAPeres** [comment]
:+1: stupidity from my part. Thanks

**Comment by ikesyo** [comment]
Thanks @mnmaraes!
