### ISSUE TITLE
FlattenMap ignore Subscribes

### ISSUE THREAD

**Issue by szweier** [ReactiveCocoa/ReactiveCocoa#2254]
I have a signal that is observing a property (signal1).  When that property changes I want to trigger another signal.  This other signal is a flattenMap on signal1 (call it signal2), so when the property changes I want the flattenMap to trigger.  The problem is I also want to call RAC(self, signal2array) = signal2 without triggering flattenMap (which it seems to do automatically). Is there a way to stop this from making signal2 hot?  Also a subscribeNext on signal2 triggers the same effect.  Is there any way to tell the flatten map to ignore these? Example below.

```
RACSignal *signal1 = RACObserve(self, item);

@weakify(self);
RACSignal *signal2 = [[signal1 ignore:nil]
                                  flattenMap:^RACStream *(id value) {
                                      NSLog(@"do something");
                                  }];
[signals addObject:signal2];
RAC(self, signal2Array) = signal2; //This triggers "do something" to print.

[[RACSignal zip:signals] subscribeNext:^(id _) { //Setting this up triggers "do something" to print as well.
//Stuff happens here
}];
```

Thanks, hopefully I described this well enough.

**Comment by mnmaraes** [comment]
It looks like what you are looking for is `RACMulticastConnection`. Like this:

```Objective-C
RACMulticastConnection *connection = [RACObserve(self, item) publish];
```

Then use `connection.signal` as you would your `signal1` and once you are ready for the underlying work to begin call:
 
```Objective-C
[connection connect];
```

It's important to note, that your signal will become hot at that point, so subscriptions that happen after the call to `connect` might miss the values that came before it.

**Comment by szweier** [comment]
Looks like when I call connect any of the previous items that triggered flattenMap end up triggering it when I call connect.  So this just seems to delay the inevitable.

**Comment by mnmaraes** [comment]
Oh, I see. I misunderstood you.

The idea is is still the same. But instead of calling `publish` on `RACObserve(self, item)` call it on `[[[signal1 ...] flattenMap...] publish]`

**Comment by szweier** [comment]
Looks like that did it.  Thank you.
