### ISSUE TITLE
Unexpected combineLatest behaviour

### ISSUE THREAD

**Issue by ReDetection** [ReactiveCocoa/ReactiveCocoa#2259]
I used to combine signals to implement additional sampling since RAC2 and it worked as expected. However in RAC3 it wont send initial event. What I'm missing?
```Swift
        let sampler = timer(5.0, onScheduler: QueueScheduler.mainQueueScheduler)
            |> map { _ -> () in return () }
        SignalProducer<NSDate, NoError>(value: NSDate())
            |> additionalSampleOn(sampler)
            |> start {
                println("next \(NSDate().timeIntervalSinceDate($0))")
        }
```
`additionalSampleOn` defined as 
```Swift
func additionalSampleOn<T, E>(sampler: SignalProducer<(), NoError>) -> (signal: SignalProducer<T, E>) -> SignalProducer<T, E> {
    return { (signal: SignalProducer<T, E>) -> SignalProducer<T, E> in
        let instantSampler = SignalProducer<AnyObject, NoError>(value: 1)
            |> then(sampler)
            |> promoteErrors(E)
        return signal
            |> combineLatestWith(instantSampler)
            |> map { (a, _) -> T in
                return a
            }
    }
}
```
I'm getting output starting from fifth second
```
next 5.00141900777817
next 10.2307109832764
next 15.001217007637
...
```
Why I'm not getting 0 ? What did I miss?

**Comment by mnmaraes** [comment]
From what I understand `timer` only start sending events after the first interval has passed. And `combineLatest` only sends events once both Producers have sent at least one event.

Try merging the `timer` Producer with `SignalProducer(value: ())` and you should get the behavior you want.

**Comment by ReDetection** [comment]
Correct, `timer` sends event from the fifth second. But please read carefully: before feed `timer` to the `combineLatest` I'm making it instant by sending instant value and concatenating with `timer`, thus `combineLatest` should already has both values.
~~Yes, merging is another way to make `timer` instant, but I find `then` much cleaner.~~ OH SHI, why did I used `then` instead of `concat`? Sorry guys, it's my own fault. :disappointed:
