### ISSUE TITLE
[Question] Playground for Swift2

### ISSUE THREAD

**Issue by mobilinked** [ReactiveCocoa/ReactiveCocoa#2260]
Is there any xcode playground file for studing and testing? Print does not display result for the simple case in playground: 

import Cocoa
import ReactiveCocoa

let (signal, sink) = Signal<String, NoError>.pipe()
sendNext(sink, "testing")

signal.observe(next: { print($0) })

BTW, "|>" gone from swift2, would you please help to let me know what's the replacement or the reason to remove? 

Thanks,

**Comment by LightD** [comment]
As for `Swift2` part, it is replaced with protocol extensions, so it's a dot syntax now..

**Comment by mobilinked** [comment]
@LightD Thanks much, got it.

**Comment by chrisschreiner** [comment]
Also add
```
import XCPlayground

XCPSetExecutionShouldContinueIndefinitely()
```

**Comment by chrisschreiner** [comment]
Perhaps
```
let (someSignal,sink) = Signal<Int,NoError>.pipe()
someSignal.observe(next:print)
sendNext(sink,123)
```
