### ISSUE TITLE
skipRepeats gives compiler error without closure

### ISSUE THREAD

**Issue by avalanched** [ReactiveCocoa/ReactiveCocoa#2261]
I have a MutableProperty with SectionItems (which conform to the Equatable protocol) 

    var sections = MutableProperty<[SectionItem]>([])

When I use skipRepeats operator it gives the following compiler error

    Could not find an overload for '|>' that accepts the supplied arguments

for the following code

        sections.producer
            |> skipRepeats
            |> observeOn(QueueScheduler.mainQueueScheduler)
            |> start(next: { sections in
                // do stuff
            })

but when i specify a skipRepeats closure it compiles

        sections.producer
            |> skipRepeats { $0 == $1 }
            |> observeOn(QueueScheduler.mainQueueScheduler)
            |> start(next: { sections in
                // do stuff
            })

**Comment by NachoSoto** [comment]
That's due to an unfortunate limitation of Swift right now: there is no way to express that `Array` is `Equatable` when `T` is, but there IS an `==` overload for that case, so you're second solution is perfect 👌
