### ISSUE TITLE
[Question] Replacing -rac_signalForSelector in Swift

### ISSUE THREAD

**Issue by gonzalezreal** [ReactiveCocoa/ReactiveCocoa#2262]
I need to subscribe to a signal until another method in an object is called (using the `takeUntil` operator). Before ReactiveCocoa 3 I would have done this using `-rac_signalForSelector` which obviously is not available for Swift types as it uses the Objective-C runtime.

The only way I can come up to implement this use case on a Swift type is using `pipe()` and manually sending the event when the method is called. Is there any other better way?

Thanks in advance.

**Comment by edwardIshaq** [comment]
+1

**Comment by NachoSoto** [comment]
You can still do this by using `-rac_signalForSelector` and `toSignalProducer`. You can see an example of how to use these signals in `ReactiveCocoa 4.x` [in this gist](https://gist.github.com/NachoSoto/25b0003c1b15d7d11a8d#file-signal-extensions-swift-L145).
