### ISSUE TITLE
[Question] (Swift2) - How to ignore error

### ISSUE THREAD

**Issue by mobilinked** [ReactiveCocoa/ReactiveCocoa#2263]
My purpose is that if error be emitted, the executing will ignore the error and then to deal with following next event. Following is the code:

-----------------------------
let (producer, sink) = SignalProducer<String, NSError>.buffer(5)
let error = NSError(domain: "domain", code: 0, userInfo: nil)

producer
    .flatMapError { error in
        SignalProducer<String, NSError>(value: "Error")
    }
    .start(next:print)

sendNext(sink, "First")   // print "First"
sendNext(sink, "Second") // print "Second"
sendError(sink, error) //print "Error"
sendNext(sink, "Three")  // nothing printed 

-----------------------------

What the direct way to process AND IGNORE the error?  (BTW, I did not find catch function in swift2 version)

Thanks,

**Comment by ikesyo** [comment]
> sendError(sink, error) //print "Error"

This is because you returns `SignalProducer(value: "Error")` from your `flatMapError()` closure. For your purpose of just ignoring the error, you should do `flatMapError { _ in SignalProducer.empty() }`.

__FYI:__ The `catch()` operator is renamed as `flatMapError()` in Swift 2 branch, since `catch` is a reserved word in Swift 2 for the sake of its new error handling model.

**Comment by ikesyo** [comment]
> sendNext(sink, "Three") // nothing printed

And this is because `SignalProducer.buffer()` does not handle events after a terminating event (`Error|Completed|Interrupted`) is added to its sink, [which is documented](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/0bfe961701ff69cff8a6f3b77e8e29eae522482d/ReactiveCocoa/Swift/SignalProducer.swift#L108-L110).

**Comment by mobilinked** [comment]
So there is no direct solution to ignore error for Signal Producer?

**Comment by ikesyo** [comment]
If you'd like to ignore errors and use `SignalProducer.buffer()`, why you send a error? It seems to me that there is no need to send a error.

**Comment by mobilinked** [comment]
Give an example: One signal is monitoring something to update local file (or db ...) and emit message to observers. Sometimes the updating to local file failed, but sometimes the updating done correctly. We may want to show success message if succeed, and display error information if failed.

**Comment by mobilinked** [comment]
Of cause, there is other solution to do it. I hope there is direct solution. From the document, it seems there is not. 

Thanks much

**Comment by ikesyo** [comment]
Sending a termination event to observers of a signal finalize the signal, so you can't reuse the signal after the termination event. From the point of view, there is no direct way of you are wondering.

To accomplish what you want, you need a signal of signals or producer of produces. Here is a one possible example:

```swift
let (producer, sink) = SignalProducer<SignalProducer<String, NSError>, NoError>.buffer(5)
let error = NSError(domain: "domain", code: 0, userInfo: nil)

producer
    .flatten(.Concat)
    .flatMapError { error in
        return SignalProducer(value: "Error")
    }
    .start(next:print)

sendNext(sink, SignalProducer(value: "First"))
sendNext(sink, SignalProducer(value: "Second"))
sendNext(sink, Signalproducer(error: error))
sendNext(sink, SignalProducer(value: "Three"))
```

**Comment by mobilinked** [comment]
@ikesyo Great, thanks.

**Comment by ikesyo** [comment]
No problem! :sparkles:

**Comment by chrisschreiner** [comment]
@Ikesyo Comparing to the initial code by @mobilinked, what exactly are you demonstrating in your example? The signal still ends at the error.

**Comment by ikesyo** [comment]
@chrisschreiner I'm sorry, the following is accurate version:

```swift
let (producer, sink) = SignalProducer<SignalProducer<String, NSError>, NSError>.buffer(5)
let error = NSError(domain: "domain", code: 0, userInfo: nil)

producer
	.map { innerProducer in
		return innerProducer.flatMapError { error in
			return SignalProducer<String, NSError>(value: "Error")
		}
	}
	.flatten(.Concat)
	.start(next: print)

sendNext(sink, SignalProducer(value: "First"))
sendNext(sink, SignalProducer(value: "Second"))
sendNext(sink, SignalProducer(error: error))
sendNext(sink, SignalProducer(value: "Three"))
```

**Comment by chrisschreiner** [comment]
Yes, this makes more sense :-) Thank you! @ikesyo
