### ISSUE TITLE
what is the reason of this error -[UIButton rac_signalForControlEvents:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by Sniper-yj** [ReactiveCocoa/ReactiveCocoa#2266]
code:
UIButton *issueBtn = [UIButton buttonWithType:UIButtonTypeCustom];
[issueBtn setTitle:@"commit" forState:UIControlStateNormal];/* set issueBtn's title*/
[issueBtn setTitleColor:[UIColor redColor] forState:UIControlStateNormal];

[[self.issueBtn rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(id x) {

}];/* error is here*/

**Comment by alanjrogers** [comment]
You're not linking ReactiveCocoa properly. See Apple's documentation [QA1490](https://developer.apple.com/library/mac/qa/qa1490/_index.html).

**Comment by Sniper-yj** [comment]
thank you very much~

**Comment by dairuiquan** [comment]
I have same problems,but  my project have other static frameworks  .
