### ISSUE TITLE
Map a SignalProducer<T, NoError> to a SignalProducer that returns errors

### ISSUE THREAD

**Issue by jschmid** [ReactiveCocoa/ReactiveCocoa#2268]
I am not sure if I misunderstand the usage of ReactiveCocoa or if is a "bug".

I am trying to use a `SignalProducer` created from the `rac_notifications()` method. 
`rac_notifications()` returns a `SignalProducer<NSNotification, NoError>`

Now, I want to map the `NSNotification` into a `String`, but the map can fail and return an error.

In a non-RAC environment I would do something like:

    // note: NSNotification

    if let infos = note.userInfo, let code = infos["value"] as? String {
        callback(code, nil)
    } else {
        let error = NSError(...)
        callback(nil, error)
    }

However, `map()` does not allow returning errors. I thought of using `attempMap` to solve the problem.

    signalProducer.attemptMap { note -> Result<String, NoError> in
        if let infos = note.userInfo, let code = infos["value"] as? String {
            return Result<String, NSError>(code)
        } else {
            let error = NSError(domain: "", code: 0, userInfo: nil)
            return Result<String, NSError>(error: error)
        }
    }

But since the type of my `signalProducer` is `SignalProducer<NSNotification, NoError>` I cannot return an NSError. This is [something you could do with RAC 2.0](http://stackoverflow.com/a/18792392/183665).

Do I miss something while mapping/flattening? It is by design that `attemp` does not allow to return another error type?

**Comment by ikesyo** [comment]
`promoteErrors()` is what you want.

**Comment by jschmid** [comment]
Thanks for the answer. Does it make sense to use it like:

    let codeProducer = signalProducer.promoteErrors(NSError).map({ note -> SignalProducer<String, NSError> in
        if let infos = note.userInfo, let code = infos["value"] as? String {
            return SignalProducer<String, NSError>(value: code)
        } else {
            let error = NSError(domain: "", code: 0, userInfo: nil)
            return SignalProducer<String, NSError>(error: error)
        }
    }).flatten(.Merge)

I am note sure the use of SignalProducer as a return value is the correct way to do it. Thanks

**Comment by jschmid** [comment]
Here is a cleaner version:

    let codeProducer = signalProducer.promoteErrors(NSError).attemptMap { note -> Result<String, NSError> in
        if let infos = note.userInfo, let code = infos["value"] as? String {
            return Result<String, NSError>(value: code)
        } else {
            let error = NSError(domain: "", code: 0, userInfo: nil)
            return Result<String, NSError>(error: error)
        }
    }

**Comment by ikesyo** [comment]
Yes, `attemptMap` seems better for that case. :+1: Additionally, you should write as `promoteErrors(NSError.self)` to use it.

**Comment by jschmid** [comment]
Thanks :+1:
