### ISSUE TITLE
Question: Carthage build and project setup 

### ISSUE THREAD

**Issue by bruceflowers** [ReactiveCocoa/ReactiveCocoa#2271]
I've followed the directions in the readme for a Carthage build - I'm using the swift2 branch and xc7b5:

"Or, if you’re using Carthage, simply add ReactiveCocoa to your Cartfile".  I also did the usual Carthage dance of adding of the built frameworks to linked libraries and copy files.

Starting with that, I was able to run a carthage build, but when running the project there are missing dylibs: sometimes Result, sometimes Box.  Is there something else I should be doing to make things work with Carthage?

**Comment by bruceflowers** [comment]
And now it works - I did the usual Carthage dance wrong. Closing

**Comment by bruceflowers** [comment]
Actually - here are potentially two steps I didn't see in the docs for Carthage setup: 

- I believe I still needed to run script/bootstrap?
- I definitely needed to add Result.framework to the project file (link libs and copy files), which I don't see mentioned for that setup.

**Comment by ikesyo** [comment]
> - I believe I still needed to run script/bootstrap?

No need to do that for Carthage usage.

> - I definitely needed to add Result.framework to the project file (link libs and copy files), which I don't see mentioned for that setup.

This is already addressed by #2242 in `master` branch.

**Comment by bruceflowers** [comment]
fair enough - thanks for the quick reply!

**Comment by ikesyo** [comment]
No problem!
