### ISSUE TITLE
[Question] RACObserve works only once

### ISSUE THREAD

**Issue by ldantona** [ReactiveCocoa/ReactiveCocoa#2274]
Hi all,

I'm customizing a table view cell appearance as follows:
```objective-c
- (void)awakeFromNib {
    [super awakeFromNib];
    
    RAC(self.label, backgroundColor) = [RACObserve(self, selected) map:^id(id selected) {
        return selected ? [UIColor blackColor] : [UIColor whiteColor];
    }];
}
```
This seems to work only once at startup, afterwards the return statement is not executed anymore even if the cell selection state changes.
Any idea?

Many thanks,
DAN

**Comment by powerje** [comment]
I assume selected is a BOOL which will translate to an NSNumber. You probably mean to replace `id selected` with `NSNumber* selected` and your return should look like:

`return selected.boolValue? [UIColor blackColor] : [UIColor whiteColor];`

If my understanding is correct `selected` is a valid NSNumber* and as such will always be truthy.

**Comment by ldantona** [comment]
Hi @powerje,
you're probably right, the selected property could not be KVO compliant.
At the moment I've changed that code back to an imperative style.
