### ISSUE TITLE
Event context

### ISSUE THREAD

**Issue by mobilinked** [ReactiveCocoa/ReactiveCocoa#2277]
It (may) is common that the observers need to know
- The data enclosed in the event 
- The context about the event, especially the "sender" of the event

It seems there is no any information about event context with the event flow, would you please help to share the thoughts about this design?

**Comment by ikesyo** [comment]
I'm not sure if that is common, but if you really want it, a wrapper data type might be a help:

```swift
struct ContextualEvent<Value, Error: ErrorType, Context> {
    let event: Event<Value, Error>
    let context: Context
}

// somewhere in your codebase

producer // SignalProducer<Value, Error>
    .materialize() // SignalProducer<Event<Value, Error>, NoError>
    .map { EventWrapper(event: $0, context: aContext) } // SignalProducer<ContextualEvent<Value, Error, Context>, NoError>
```
