### ISSUE TITLE
CocoaAction and Action

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2278]
I am struggling to see which one I should use: `CocoaAction` and/or `Action`. In one hand I want to be able to `execute` manually, independently of the control it is attached to (for example when `viewDidLoad` gets called, I would like to call `execute`/`apply` directly). But on the other hand, from a View perspective, I would like to watch for these (which `CocoaAction` doesn't expose):

```
    public let values: ReactiveCocoa.Signal<Output, ReactiveCocoa.NoError>
    public let errors: ReactiveCocoa.Signal<Error, ReactiveCocoa.NoError>
```

So I come up with this:

```
class ViewModel {
    
    let action : Action<Bar, [Foo], Error>
    let cocoaAction : CocoaAction
    
    init(fooFetcher: FooFetcher<Foo>) {
        
        self.action = Action {
            return fooFetcher.fetch($0)
        }
        
        self.cocoaAction = CocoaAction(self.action, input: someBar)
    }
}
```

This allows me to:

1. Use `execute` directly. (`viewModel.cocoaAction.execute(nil)`)
2. Bind a UI control if I want to.
3. Observe the `values` and `errors`.
4. Fix the input

The `Action` is just lacking the 4): Fix the input. 

Is there a better way to achieve the above, without having to rely on both `Action` and `CocoaAction`?

----

I also played with this idea:

```
    let action : Action<Void, [Foo], Error>
```

The consumer of the ViewModel would then call this `viewModel.fetch()`. The `fetch()` would be defined as:

```
func fetch() {
   self.action().start()
}
```
Is this an acceptable compromise or am I missing something?

**Comment by aehlke** [comment]
You closed this, but I'm curious if you settled on a different approach?

**Comment by RuiAAPeres** [comment]
@aehlke nah, still using this.

**Comment by aehlke** [comment]
I don't think your 2nd approach works - `Action<Void, _, _>` seems impossible, since `action.apply` requires an input. Was it untested pseudocode or am I missing something? I'm trying to do something similar... Thanks.

**Comment by RuiAAPeres** [comment]
@aehlke `action.apply().start()`
