### ISSUE TITLE
How to use `startWithSignal` on signal producer

### ISSUE THREAD

**Issue by LightD** [ReactiveCocoa/ReactiveCocoa#2279]
I have a signal producer that gets a request from the network.. but then for some specific requests, I want to be able to `observe` on the signal generated from `startWithSignal`.. how do I do that? how do I use the `signal` that Is passed in the closure, outside of that class and observe it a few different places in the system?

**Comment by pepibumur** [comment]
Hi @LightD you have different options:
You can subscribe direclty to the signal passed to the closure in `startWithSignal` as you say but you've also another option, on:

- `on` method where you can specify passing a closure what todo in case of different types of events coming, https://github.com/ReactiveCocoa/ReactiveCocoa/blob/6c37b5ef416799a3a2a61ff78f051d5deb0d76b2/ReactiveCocoa/Swift/SignalProducer.swift#L394 . Notice that the method has default parameters so you can you define only the one you need. You can add as many subscriber as you want.

**Comment by LightD** [comment]
thank you @pepibumur :)
