### ISSUE TITLE
[Question] bufferWithTime in RAC 3?

### ISSUE THREAD

**Issue by danishin** [ReactiveCocoa/ReactiveCocoa#2281]
I've been bridging to use `RACSignal.bufferWithTime`. As far as I know there is no equivalence of it in RAC 3? Is there a workaround / trick to imitate the behaviour of `bufferWithTime` using RAC3? 

My case scenario is that I need to track if the user tapped twice in a given short period (to capture double tap). I basically buffer it with about 0.2 seconds and see if there was more than a single tap. FIY, I cannot use `UIGestureRecognizer` since I use third party object which only exposes a single tap API.

Thanks!

**Comment by harrywincup** [comment]
@daniel-shin1104 I read this earlier which has an example of capturing 2 or more quick taps if you search for `buffer(stream.throttle(250ms))` and read the surrounding content.

https://gist.github.com/staltz/868e7e9bc2a7b8c1f754

**Comment by daniel-shin1104** [comment]
Unfortunately, the example made use of RxJS, which has different semantics for `buffer` from RAC3's `SignalProducer.buffer`. The former allows to buffer values with time-based constraints whereas RAC's buffer is to simply _replay_ buffered `Signal`s with explicit length to every new subscribers. I don't think time constrained buffering is supported in RAC3 yet.  :cry:

**Comment by danishin** [comment]
```swift
    signal
      |> map { (NSDate(), $0) }
      |> combinePrevious((NSDate(timeIntervalSince1970: 0), ""))
      |> filter { $1.0.secondsFrom($0.0) < 0.2 }
```

This does the job. Pretty nifty!
