### ISSUE TITLE
MutableProperty behaviour

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2287]
Having the following example:

```
class Foo {
   let signal : Signal<NSString, NoError> 
   let bar: Bar

  init() {
     signal = ... 
     bar = Bar()

     bar.var <~ signal
  }
}
```

And :

```
class Bar {
  let var : MutableProperty<String> = MutableProperty("")
}
```

I was expecting to be able to observe the values coming into `bar` like so:

```
bar.producer.on(next: {print($0)}) 
```

But nothing will ever come. Yet, the `value` will be updated correctly with the `next` events from the Signal

**Comment by pepibumur** [comment]
Hi @RuiAAPeres 
- In the first example you bind a signal to the var attribute. Might it be sending events before being binded?
- How do you track if the value is being updated? You can subscribe to the var, producer attribute and check if at least it's receiving the values

**Comment by mla310** [comment]
`on` returns a new SignalProducer with injected side effects from the `next` closure you provide. If you would like to observe the changes to the value in the MutableProperty you should use `start`. Comes down to SignalProducers being "cold"

**Comment by nikita-leonov** [comment]
Current `on` purpose is to inject side effects into the chain and it is available as free function. You will still need to start it even if you defined it for a chain  `bar.producer |> on(next: {print($0)}) |> start()`. Bringing additional use-cases for `on` like making it a synonym of `start` will be confusing.
