### ISSUE TITLE
Observing action.values is not firing any events

### ISSUE THREAD

**Issue by LightD** [ReactiveCocoa/ReactiveCocoa#2288]
Hi,
In the `ViewModel`'s `init`:
``` swift
        doneSelectingAction = Action<AnyObject, AnyObject?, NSError> { val in
                return UserService.sharedInstance.updateGenres(self.genres) |> map { $0 as? AnyObject }
        }
```
and in the `ViewController`
``` swift
        viewModel.doneSelectingAction.executing.producer |> on(started: {
            ProgressManager.sharedInstance.createProgressView(self.view)
        })
        viewModel.doneSelectingAction.values.observe(completed: {
            ProgressManager.sharedInstance.hideProgressView()
                Utils.ApplicationDelegate().switchToHome()
            }, next: { val in
                debugPrintln(val)
            }, error: { error in
                debugPrintln(error)
            }, interrupted: {
                debugPrintln("interrupted")
        })
```
and this is how i bind it (which is working btw, coz the signal inside the action is being called on the breakpoints):
`self.doneButton.addTarget(viewModel.doneSelectingAction.unsafeCocoaAction, action: CocoaAction.selector, forControlEvents: .TouchDown)`
1. I wanna start progress when the button is clicked, but the first observer on the executing is not being called.. am I using it wrong? how do I get the event of when the action is triggered?
2. I wanna receive the events of the resulting signal inside the action, how do I do that? observing `values` should be doing it, but it's not, I'm not getting any event whatsoever...

Or is this a problem because I'm binding it using `unsafeCocoaAction`? I don't know......

**Comment by LightD** [comment]
Update:
observing `errors` is working, and behaving as expected.. but points mentioned above stand still at their current position.

**Comment by ikesyo** [comment]
> `viewModel.doneSelectingAction.values.observe(completed: { `

The completed event of `Action.values` signal is emitted when the action deallocates, that is not a event of the inner producer. If you want events of the inner producer, you should apply the action by yourself, and start the returned producer as follows:

```swift
@IBAction func didTapButton(sender: UIButton) {
    viewModel.doneSelectingAction.apply(sender)
        |> on(started: { ProgressManager.sharedInstance.createProgressView(self.view) })
        |> start(completed: { ... }, next: { val in ... }, error: { error in ... }, interrupted: { ... })
}
```

**Comment by LightD** [comment]
Thank you @ikesyo, this should be mentioned somewhere in the documentation tho, but you have saved my life for now!! thanks a lot!!
