### ISSUE TITLE
Use of undeclared type 'Wrapped'

### ISSUE THREAD

**Issue by dfirsht** [ReactiveCocoa/ReactiveCocoa#2290]
While trying to compile swift2 branch in xcode beta 5.  The following errors occur

ReactiveCocoa/ReactiveCocoa/Swift/Optional.swift:19:23: Use of undeclared type 'Wrapped'
ReactiveCocoa/ReactiveCocoa/Swift/Optional.swift:18:1: Type 'Optional<T>' does not conform to protocol 'OptionalType'

ReactiveCocoa/ReactiveCocoa/Swift/Action.swift:74:19: 'Output?' does not have a member named 'T'
ReactiveCocoa/ReactiveCocoa/Swift/Action.swift:75:19: 'Error?' does not have a member named 'T'

**Comment by neilpa** [comment]
The Swift 2 branch has been updated to target beta 6. 5cb359c was the last commit that supported beta 5

**Comment by dfirsht** [comment]
ok compiles in beta 6
