### ISSUE TITLE
Capturing one error in a combined signal?

### ISSUE THREAD

**Issue by hirad** [ReactiveCocoa/ReactiveCocoa#2291]
I have two `SignalProducer`s: `A` and `B`. Each of them is responsible for asynchronously fetching some resource. Both are of type `SignalProducer<ResourceType, NSError>`  - if they don't find the resource, they return a specific `NotFound` error. 

In case of success, I want to use both of the results, so I'd normally use `combineLatest`. But in this case, if `B` fails and `A` succeeds, I can create `B`'s resource *using the result from `A`*. So the workflow is:
1. Get A, Get B.

If you got both,
2. Update UI.

Otherwise, if you got A but not B,
2. Create B with A.
3. Update UI.

Otherwise,
4. Show error.

How can I express this? I need access to an error value and a next value at the same time. One thing I considered was transforming B so that in case of error, it'd return nil, then I can check for nil on the combined signal's next. But I don't know how to do this - `catch` doesn't let me turn the "success" value into an optional, and `flatMap` won't let me access the error.

I'm still getting my footing with RAC, so I'm wondering if there's another solution I'm missing?

**Comment by neilpa** [comment]
What you're looking for is [`materialize`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/3fd574c7d89cb04315becff5875fd4f13519ad5d/ReactiveCocoa/Swift/Signal.swift#L407-L415). Use that on `B` to turn the events into values and which you can `combineLatest` with the original `A` signal. Then you can `flatMap` the result of the combined signals handling both errors and success on `B`.

**Comment by neilpa** [comment]
You'll also need to use [`promoteErrors`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/3fd574c7d89cb04315becff5875fd4f13519ad5d/ReactiveCocoa/Swift/Signal.swift#L1092-L1097) on the `materialize`d signal so that the error types match when combining with `A`.

**Comment by hirad** [comment]
Thanks! I did not realize I can use `Signal` functions with `SignalProducer`s using `|>`, so I never looked at those. It all makes sense now!
