### ISSUE TITLE
ReactiveCocoa is not semver compatible

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2293]
I assume that ReactiveCocoa wants to be SemVer compatible (because it uses Carthage as a distribution mechanism). If that is the case release `3.0-RC.1` shoudn't be `3.0.0-RC+1`?

**Comment by ikesyo** [comment]
`1` is a component of the pre-release version, not a build metadata.

**Comment by guidomb** [comment]
According to http://semver.org/

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

By that definition `0-RC` is not a valid as a version number

**Comment by ikesyo** [comment]
`3.0.0` over `3.0` would be more appropriate here. But the characters after a hyphen is a pre-release version, not a part of normal version number. See the section 9.

**Comment by guidomb** [comment]
OK so `3.0-RC.1` should be `3.0.0-RC.1`. I am rising this issues because if you want to automatically parse and compare releases that are semver compatible the current tag name is not compatible with semver. For example using a gem like https://github.com/jlindsey/semantic to parse the version number based on the tag name raises an exception.

Should the tag name be semver compatible?

**Comment by neilpa** [comment]
There's another minor issue here -- capitalized `RC` lexicographically sorts _before_ `alpha` and `beta` causing release candidate builds to have lower precedence.

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by guidomb** [comment]
I think you could add another tag pointing to the same commit ref as `3.0-RC.1` called `3.0.0-rc.1`, edit the release but keep the old tag for compatibility reasons.

**Comment by guidomb** [comment]
Could we say this issue is "closed"?

**Comment by guidomb** [comment]
Well actually I have just realised that there is a new release, v4.0-alpha.1. Following what we have discussed here the tag name should've been `4.0.0-alpha.1` or am I wrong?

**Comment by guidomb** [comment]
//cc @NachoSoto ?

**Comment by mdiep** [comment]
We will try to follow the spec in the future.
