### ISSUE TITLE
Swift 2: Using rac_willDeallocSignal

### ISSUE THREAD

**Issue by harrywincup** [ReactiveCocoa/ReactiveCocoa#2296]
With RAC3, is it correct to use the dealloc signal to "turn off" signal producers, or is there a better way? (I'm new to everything, so really i'm just flailing around here using bits and pieces i've seen people doing)

```
producer.takeUntil(rac_willDeallocSignal().toSignalProducer())
```

It looks like `takeUntil` expects `SignalProducer<(), NoError>` but `.toSignalProducer()` returns `SignalProducer<AnyObject?, NSError>` so it doesn't seem compatible unless I do some conversion?

Honestly, i've got no idea what i'm doing ... but i've struggled to find useful information about how to properly clean things up so if somebody could point me in the right direction i'd really appreciate it :)

**Comment by iandundas** [comment]
+1 - I have the exact same question :) currently trying to work out a way to use `mapError` to change a Signal signature from `NSError` to `NoError` so that I can use takeUntil.

**Comment by iandundas** [comment]
@harrywincup actually, I think [this post](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2018) should cure your ills?

**Comment by harrywincup** [comment]
@iandundas Yeah I was using the manual conversion to `SignalProducer<(), NoError>` but it seems very strange that what used to be 

```
producer.takeUntil(rac_willDeallocSignal)
``` 
is now 
```
producer.takeUntil(rac_willDeallocSignal().toSignalProducer().flatMapError(_ in SignalProducer<(), NoError>.empty).flatMap(.Latest, transform: { _ in SignalProducer<(), NoError>(value: ()) })
```

I assumed (and still do) that I'm doing something crazy and there must be a better way than that. If not, I suppose a helper function can do it :) Thanks!

**Comment by iandundas** [comment]
haha yeah - I’m with you

**Comment by orkenstein** [comment]
So, are there any alternatives to `rac_willDeallocSignal` in **swift**?

**Comment by NachoSoto** [comment]
You can still use `rac_willDeallocSignal` like @harrywincup explained:

```swift
let willDeallocSignal: SignalProducer<(), NoError> = object
  .rac_willDeallocSignal()
  .toSignalProducer()
  .flatMapError { error in
      fatalError("Unexpected error: \(error)") // This is important, you don't want to silently ignore errors.
      return .empty
  }
  .flatMap(.Latest) { _ in () }
```

**Comment by iandundas** [comment]
Sure, but the original question: 

> is it correct to use the dealloc signal to "turn off" signal producers, or is there a better way? 

`rac_willDeallocSignal()` isn't available unless you're descending from NSObject, and is in the deprecated obj-c API, so I'm not sure this was answered.

Do we instead create our own dealloc signal and sendComplete to it in the `deinit` function?

**Comment by neilpa** [comment]
> Do we instead create our own dealloc signal and sendComplete to it in the deinit function?

I can't answer this without more context about what you're trying to achieve. Generally, you don't want to couple a producer's lifetime to some ancillary object's lifetime though.

**Comment by chainone** [comment]
The code I use: 
```        let willDeallocSP = object.rac_willDeallocSignal()
            .toSignalProducer()
            .flatMapError { _ in SignalProducer<AnyObject?, NoError>.empty}
            .map {_ in ()}
```
It is not convenient, but at least it works. I treat it as a temp workaround, the real question is how to do with swift objects?
