### ISSUE TITLE
[Design] "Gating" a Signal(Producer)

### ISSUE THREAD

**Issue by swizzlr** [ReactiveCocoa/ReactiveCocoa#2297]
Given a producer of producers:

```swift
let producerOfProducers: SignalProducer<SignalProducer<T, Error>>
```

Which sends the next inner producer when the prior inner producer completes:

```swift
innerProducer.on(completed: { sendNext(producerOfProducersSink, createAnInnerProducer()) })
```

I want to flatten it in such a way that I get a Signal(Producer) of `T`, but I don't want to `Concat` the darn thing, because then I'll do unnecessary work. I only want to start the subsequent inner producer when an event occurs that indicates I'll need the values on it.

So what I have right now is the following, relying on `sampleOn` as a way

```swift
let startNextProducerSignaller: Signal<(), NoError>
let (flattenedProducerSink, flattenedProducer) = SignalProducer<T, Error>.buffer()
producerOfProducers.startWithSignal { (signal, _) in
        signal.take(1).observe { (next: SignalProducer<T, Error>) in
          next.start { (next: T) in flattenedProducerSink(next) } // error handling goes here :P
        }
        signal.skip(1).sampleOn(startNextProducerSignaller)
          .observe { (next: SignalProducer<T, Error>) in
            next.start { (next: T) in flattenedProducerSink(next) }
          }
      }
```

The problem I have is that `sampleOn` will send the last value for eternity, as far as I can tell through reading the code. Even if `signal` in this example completes, i.e., there are no more inner producers to send, the resulting signal will not send completed until the sampling signal completes as well.

The way I see it, I have a couple of approaches at this point:
1. Attempt to implement `Equatable` and use `skipRepeats()`. I'd probably do this by wrapping the innerProducers in a `struct` to store some state that can be used to uniquely identify the signal producer relative to the domain in which I'm programming.
2. Write my own `sampleOn(_: Signal<(), NoError>, completeOnEitherSignalCompletion: Bool)`. The latter is more attractive, and I wonder if RAC would find such an API interesting or too heavyweight?
3. One of you people tell me that I'm going about this entirely the wrong way.

I'm going to start on 2, but I'm curious to hear what other approaches are available.

**Comment by mdiep** [comment]
> The problem I have is that sampleOn will send the last value for eternity, as far as I can tell through reading the code. Even if signal in this example completes, i.e., there are no more inner producers to send, the resulting signal will not send completed until the sampling signal completes as well.

You could use `takeUntil` to remedy that:

```swift
// You might need some type annotations.
// The flatMap is to prevent the values from being sent.
.sampleOn(startNextProducerSignaller.takeUntil(signal.flatMap { _ in .empty }))
```

> Attempt to implement Equatable and use skipRepeats(). I'd probably do this by wrapping the innerProducers in a struct to store some state that can be used to uniquely identify the signal producer relative to the domain in which I'm programming.

There's a version of `skipRepeats` that takes a block that takes two values and returns a bool. You might be able to use that.

> Write my own sampleOn(_: Signal<(), NoError>, completeOnEitherSignalCompletion: Bool). The latter is more attractive, and I wonder if RAC would find such an API interesting or too heavyweight?

I don't think that's something we want to add to the RAC core. It's not a common operation, and you can easily achieve it as I did above.

> One of you people tell me that I'm going about this entirely the wrong way.

Honestly, it's hard to tell without having a better understanding of what you're actually trying to do.

I'm going to close this issue since it's rather old. (Sorry we didn't back to you in a timely manner!) But feel free to reopen if you would like to discuss more.
