### ISSUE TITLE
[Question] Why doesn't `SignalProducer` have `observe` method unlike `Signal'?

### ISSUE THREAD

**Issue by mesmerizingr** [ReactiveCocoa/ReactiveCocoa#2300]
Subj.

Suppose I want to conditionally start some stream at some point of my application lifetime. I aim to start it on some concurrent queue (so I'd use `startOn`). This thing goes to category of "cold signals" and I would use `SignalProducer` for that.

I want my custom objects be able to subscribe to events emitted from this producer regardless whether the producer has started or not. But the `SignalProducer` doesn't have an `observe` method unlike `Signal` and I can subscribe to it's inner signal only when invoked from `startFromSignal` method which contradicts to my initial design.

Is there any patterns which one should use to achieve this kind of functionality?

Thanks!

**Comment by yusefnapora** [comment]
I'm not very qualified to answer the "why" part of your question, but you can accomplish what you're describing like this:

```swift
let (signal, sink) = Signal<ValueType, ErrorType>.pipe()

// interested parties subscribe to signal

// some time later..
producer.start(sink)
```

Your objects can start observing the signal at any time, and when you're ready to start the producer, you can pass the sink into `start`.  That will forward all events onto the signal, so any subscribers that are `observe`ing the signal will receive them.

Only downside is that you need to keep a reference to the sink around as well as the producer.

**Comment by swizzlr** [comment]
You could try using `on(next: (T) -> ())` to execute an arbitrary block whenever a next event is fired.
