### ISSUE TITLE
Unable to build swift2 branch xcode 7

### ISSUE THREAD

**Issue by ryudice** [ReactiveCocoa/ReactiveCocoa#2301]
Hello, I'm getting the following errors when building swift2 branch with Carthage. I already ran xcode-select to use xcode 7 for building.

The following build commands failed:
	CompileSwift normal x86_64 /Users/robertoyudice/georetail/GeoRetail/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Optional.swift
	CompileSwift normal x86_64 /Users/robertoyudice/georetail/GeoRetail/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Action.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

Carthage file is:

github "ReactiveCocoa/ReactiveCocoa" "swift2"

**Comment by NachoSoto** [comment]
Could you attach the rest of the log to see what the actual error is?

**Comment by neilpa** [comment]
I'm guessing you're using one of the earlier Xcode betas since the failure is in Optional.swift. In beta 6 there was a change that renamed the type parameter for optionals so you'll need to use the most recent beta for the `swift2` branch.

**Comment by ryudice** [comment]
Thanks a lot! that was the problem, didnt realize there was a new version.
