### ISSUE TITLE
Swift 2 XCode 7 beta 6 ... SourceKitService crashes with autocomplete

### ISSUE THREAD

**Issue by harrywincup** [ReactiveCocoa/ReactiveCocoa#2302]
I updated to XCode 7.0 beta 6 and have ReactiveCocoa checked out at 4529365364d9283a243c1632f32a5b875eca982d (swift2) and when RAC-related autocomplete pops up SourceKitService crashes.

Just wondering if that's caused by something in RAC? Anybody else seeing this?

**Comment by NachoSoto** [comment]
Yeah this has been bugging me too. I was actually teaching RAC to someone a few days ago, and lack of autocomplete made it really hard.

This is a regression from beta 5, so I hope it gets fixed... I haven't had time to dig into it more, but it'd be great if someone could get a crash report and file a radar!

**Comment by harrywincup** [comment]
Unfortunately i'm new to XCode and ReactiveCocoa so don't have a clue how to go about finding what the problem is. I can reproduce the SourceKitService crash 100% of the time though so maybe that's helpful to somebody

**Comment by andersio** [comment]
SourceKitService somehow crashes on all extensions on SignalProducers with type constraints. Commenting them out would stop the crashes.

**Comment by schickling** [comment]
Same here.

**Comment by NachoSoto** [comment]
I filed a radar attaching the built framework and a sample source kit crash: http://openradar.me/22596105

**Comment by NachoSoto** [comment]
This is still broken in 7 GM and 7.1 Beta 1...

**Comment by czechboy0** [comment]
Are there any updates on this? I basically commented out all the extensions with type constraints (together with methods that depended on them), which is like a half of `SignalProducer` functionality just to be able to stop the Xcode editor from crashing and get proper autocompletion. Is there any other workaround?

**Comment by NachoSoto** [comment]
This is supposedly fixed in Xcode 7.1 beta 2

**Comment by NachoSoto** [comment]
Fixed in Xcode 7.1, so closing this!
