### ISSUE TITLE
[self.target addObserver:self forKeyPath:self.keyPath options:options context:&RACKVOWrapperContext]; Unit Test Bad Access

### ISSUE THREAD

**Issue by szweier** [ReactiveCocoa/ReactiveCocoa#2308]
Running unit tests for code that works just fine results in bad access on the line 

``` 
[self.target addObserver:self forKeyPath:self.keyPath options:options context:&RACKVOWrapperContext];
```

inside of RACKVOTrampoline.m

Not sure where to go from here.  Any guidance?  

This happens when 
```
RAC(self, property) = signal;
```
is called.

**Comment by ikesyo** [comment]
This is really a duplicate of #1122. `RACKVOTrampoline` was re-implemented in #1627 and this should be fixed from the v2.4.6 release. Closing.
