### ISSUE TITLE
Question: Synchronizing an access to a limited resource

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2309]
I have a various signal producers that could be started concurrently. Inside these signal producers consume limited availability resource. To ensure correctness of operation I need to synchronize consumption. Moreover if some error will happen during one of signal producer execution, I will need to cancel queued signal producers. I already implemented functionality with gcd, as well as nsoperationqueue but both of them does not looks nice. In my understanding RAC is built for solving such problems, but so far I didn't find a better way. Can anyone suggest how to implement it in a pure way, without bringing low-level abstractions? Is it possible with pure RAC? I am using RAC3.

**Comment by mdiep** [comment]
This is an old question, and you haven't given much concrete detail about what you're trying to accomplish. But you can synchronize consumption with `Atomic`. RAC does this quite a bit itself to implement various operators, so you could look at the source for an example.

To cancel related signals, you'll need to use some shared state, like a `Signal.pipe()`. Then you can `merge` that signal with your various signal producers and `sendError` when one of the encounters an error.

**Comment by nikita-leonov** [comment]
Hey. Thanks for an answer. It is definitely old and as result is a little bit less relevant now. I have already some implementation in place for this problem, I still think it is not what normal RAC code should looks like, but as for today it is not critical to refactor it. Suggest solution looks good. I will try your suggestion when I will have enough of buffer to cleanup technical debt. Thanks!

**Comment by mdiep** [comment]
Sorry again about the long delay! Some of the core contributors dropped off somewhat suddenly, leaving a vacuum that took a while to be noticed and filled.

**Comment by nikita-leonov** [comment]
No worries, it was not a complain in any possible way. The main reason for an answer was to clarify that now there will be a slowdown on my side on validation of an answer :) The work that previous and current contributors did is great! RAC is a solution of choice in our company and will be for a long time I think. Thank you very much for your effort.
