### ISSUE TITLE
When Building 3.0 RC1 with Carthage -- framework not found ReactiveCocoa for architecture x86_64

### ISSUE THREAD

**Issue by aventurella** [ReactiveCocoa/ReactiveCocoa#2317]
Carthage downloads the archive for ReactiveCocoa (all platforms):

`*** Downloading ReactiveCocoa at "v3.0 Release Candidate 1"`

When adding this framework to the xcode project via: `Linked Frameworks and Libraries` -> `Add Other` and attempting to build for the iOS Simulator, the build will fail with error:

`ld: framework not found ReactiveCocoa for architecture x86_64`

It also fails when targeting a device itself:

`ld: framework not found ReactiveCocoa for architecture arm64`
`ld: framework not found ReactiveCocoa for architecture armv7`

I guess I'm confused about how to use the archived version of the Framework provided by Carthage in a workspace. Normally I would add the ReactiveCocoa.xcodeproj to my Workspace and everything seemed to go perfectly.

Even when I add a run script phase with the following:

`/usr/local/bin/carthage build --platform "$PLATFORM_NAME" "$SRCROOT"`

And make it happen after `Target Dependencies` it still fails with the above errors.

**Comment by neilpa** [comment]
Are you building an app or a framework. If the former, you should be adding it to the "Embedded Binaries" section. For the latter I would assume this is during tests which requires a "Copy Files" build rule for the framework to where your tests can load it.

**Comment by aventurella** [comment]
It's for a Framework. So I should also do a copy files for the unit tests as well? In order to test this, how can I disable the unit test when it builds the Framework product?

**Comment by neilpa** [comment]
https://github.com/carthage/carthage#adding-frameworks-to-unit-tests-or-a-framework

**Comment by aventurella** [comment]
thanks!
