### ISSUE TITLE
Errors when submitting to AppStore 

### ISSUE THREAD

**Issue by ivan-ushakov** [ReactiveCocoa/ReactiveCocoa#2325]
Sorry, if this already was asked but I can't submit my app to AppStore with ReactiveCocoa framework. Validation process works without errors but when I submit app I see several errors:  Unsupported Architectures (ITMS-90087), Invalid Segment Alignment (ITMS-90209), Invalid Binary (ITMS-90125) and warning about Position Independent Executable (ITMS-90080).

I just added ReactiveCocoa.framework folder to my project (not workspace) and beside submission everything works fine.

**Comment by neilpa** [comment]
If you're using a carthage built binary see step 4 - https://github.com/Carthage/Carthage#if-youre-building-for-ios

**Comment by ivan-ushakov** [comment]
No, I don't use it.

**Comment by ivan-ushakov** [comment]
I already found the reason (http://www.openradar.me/radar?id=6409498411401216):

> If an iOS framework contains a fat binary with simulator (i386/x86_64) and device (ARM) slices, any application that attempts to embed that framework will be rejected from App Store submission.

And nice solution from Daniel Kennett: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode. So I close issue.
