### ISSUE TITLE
dyld_fatal_error on device only with debug, not with release.

### ISSUE THREAD

**Issue by aventurella** [ReactiveCocoa/ReactiveCocoa#2326]
I created a new, empty project, and I have tried both `RC1` and `master` in my Cartfile.
```
github "ReactiveCocoa/ReactiveCocoa" "master"
# github "ReactiveCocoa/ReactiveCocoa" "v3.0-RC.1"
```

This is my only dependency.

Before attempting to run each of the 2 methods described below, I have `Clean`ed the project and cleared the `Derived Data`.

After carthage builds ReactiveCocoa, I have tried two ways of linking the frameworks:

**Method 1**
1) Open Carthage/Checkouts/ in Finder and move each `.xcodeproj` into my workspace
2) From the Products **General** settings, add the 3 Frameworks under `Linked Frameworks and Libraries`
3) Create a new `Run Script` Phase and invoke `carthage copy-frameworks` specifying 3 Framework input files located in `$(SRCROOT)/Carthage/Build/iOS/`
4) Build and Run With the `debug` configuration (the default) set on the scheme.

**Method 2**
1) With no additional projects but my test project in the scheme, From the Products **General** settings, add the 3 Frameworks under `Linked Frameworks and Libraries` using **Add Other** and selecting the 3 Frameworks located in `Carthage/Build/iOS` (Box, Result, ReactiveCocoa)
2) Create a new `Run Script` Phase and invoke `carthage copy-frameworks` specifying the 3 Framework input files located in `$(SRCROOT)/Carthage/Build/iOS/`
3) Build and Run With the "debug" configuration (the default) set on the scheme.

In both cases, running under the `debug` configuration on a **device** results in a `dyld_fatal_error` for the first bit of code that touches `RactiveCocoa`. Running under `debug` on the **simulator** there is no issue.

However! If I switch the scheme's run configuration to `release` and run on the device **everything works**; no `dyld_fatal_error`

I have attached screens of **method 1** above to better illustrate the project setup. Again, the error is only present under the `debug` configuration, **not** the `release` configuration.

#### Setting Links using the Workspace Projects
![workspace_links](https://cloud.githubusercontent.com/assets/75315/9762559/3fd7f010-56b9-11e5-8bdb-9bf79388e355.png)

#### Copy Carthage Frameworks
![copy-frameworks](https://cloud.githubusercontent.com/assets/75315/9762577/5c3983c2-56b9-11e5-9bcd-da0126f63c0d.png)

#### Scheme's Run Configuration
![scheme-run-debug](https://cloud.githubusercontent.com/assets/75315/9762588/6a909e74-56b9-11e5-804b-b6817a6b0a3d.png)

### Example Offending Code (only in debug)
![sample-code](https://cloud.githubusercontent.com/assets/75315/9762681/f20556c4-56b9-11e5-961c-f3f0a06fc1b8.png)

```swift
let producer = SignalProducer<Int, NoError>{ sink, _ in
    sendNext(sink, 99)
    sendCompleted(sink)
}

producer |> start{ value in
    println(value)
}
```

#### The Error (only in debug)
![runtime-error](https://cloud.githubusercontent.com/assets/75315/9762609/898e14be-56b9-11e5-91ad-a1fd3f035a10.png)

**Comment by NachoSoto** [comment]
You've done everything right, but Xcode is a piece of ****, so you need to dig into more implementation details. I imagine you need to set the runtime framework search path: http://stackoverflow.com/a/29281962.
