### ISSUE TITLE
Should we kill the E:ErrorType in Signal/SignalProducer?

### ISSUE THREAD

**Issue by mishagray** [ReactiveCocoa/ReactiveCocoa#2335]
So currently in Swift 2.0 you can't just invoke a Signal<T,E> with a concrete type of 'ErrorType'.  

example:
` func myproducer() -> SignalProducer<String,ErrorType>`
This generates an error as of GM Xcode 7 and reactive cocoa branch "swift2"

Instead RAC 3.0 seems to want to make error handling type safe, but to be honest, this feels like it undermines the beauty of the ErrorResult generic type itself.
AlamoFire's generic result now just has a an error of 'ErrorType'  and doing error handling feels cleaner.

The issue for me seems to be in SignalProducer composition via map/mapError() etc.  

So if I have a SignalProducer that generates a custom ErrorType, say 'MyDiskErrors'.  But I'm composing that with a network stack that may produce 'NetworkErrors'.  Which itself is composed of something producing NSError, it feels SIMPLER to call map() on my producers and allow the Errors to 'cycle up'.

Swift 2.0 has a built in NSError conversion from any ErrorType, so it's easy to cope with unexpected custom ErrorType implementation in the same way you deal with unexpected NSError.  So the value of making ErrorType 'type safe' isn't as important.

This way I can just perform error handling at the 'top' of the Async food chain.   Not at every step in the composition.  Which feels much closer to the swift 2.0 error handling as it's defined.  so I can either just 'throw' or perform a switch to test for each ErrorType I expect.

So now Signal and SignalProducer with just have a signal generic 
`Signal<T>`
`SignalProducer<T>`

you can still do mapError() for cases where you want to catch and translate errors.  But by default map() would just allow any ErrorType value to be used, not a specific concrete one.

**Comment by NachoSoto** [comment]
> Instead RAC 3.0 seems to want to make error handling type safe, but to be honest, this feels like it undermines the beauty of the ErrorResult generic type itself.

> So now Signal and SignalProducer with just have a signal generic 
> `Signal<T>`
> `SignalProducer<T>`

Yes, this is a very important detail of RAC 3's design. Knowing about the error types is just as important as knowing about the emitted types. What you're suggesting is the same as having `Signal<AnyObject!>`, and we all know how problematic that was in `RAC 2`.

> This way I can just perform error handling at the 'top' of the Async food chain. 

You can still do that if you want, but I'd suggest that you consider another approach. If all you get at the top level is an `NSError`, without any sort of information of what errors might have occurred in the process, you're going to have a very hard time responding to them in any sensible way (if you don't believe me, [ask Xcode engineers](https://twitter.com/nachosoto/status/641801044133965824)).

Many of us actually believe very strongly that the flaw is the opposite, `Swift 2` `throws` should be typed, for the reasons I explained above.

**Comment by neilpa** [comment]
I'm very :-1: on anything that pushes error handling to runtime when we can handle it at compile time. Especially with associated values and enums it's trivial to wrap lower level errors and propagate them up.

> They then look at the causes of those failures and find that most bugs were due to bad error handling. 92% of those failures are actually from errors that are handled incorrectly.

http://danluu.com/postmortem-lessons/

**Comment by neilpa** [comment]
> Many of us actually believe very strongly that the flaw is the opposite, Swift 2 throws should be typed, for the reasons I explained above.

Yup. `throws` is only syntactic sugar around a compiler hidden `Result` type that doesn't expose the actual error.
