### ISSUE TITLE
about Manual assignment

### ISSUE THREAD

**Issue by harryzjm** [ReactiveCocoa/ReactiveCocoa#2336]
I am a new user for RAC  
I have a problem about manual assignment  
```objective-c
@property (nonatomic, strong) UISlider *speedSd;

[[self.speedSd rac_newValueChannelWithNilValue:@0] subscribeNext:^(id x) {
        NSLog(@"harry %@", x);
    }];
```
if I do this `self.speedSd.value = 12.f;`  
it have nothing to output  
how can i do about this if i want i do this `self.speedSd.value = 12.f;`  it have output

**Comment by rock88** [comment]
Hi,
When manually set `value` property of UISlider - not triggered UIControlEventValueChanged event.
So, for this example, need also use RACObserve:
```obj-c
[[RACSignal merge:@[[self.speedSd rac_newValueChannelWithNilValue:@0], RACObserve(self, speedSd.value)]] subscribeNext:^(id x) {
    NSLog(@"%@", x);
  }];
```

**Comment by harryzjm** [comment]
@rock88  Thanks for your to give me  a hint.
I write this it can do well:  
`[self.speedSd sendActionsForControlEvents:UIControlEventValueChanged];`
