### ISSUE TITLE
Transforming the error type of a signal on a next event

### ISSUE THREAD

**Issue by erikjalevik** [ReactiveCocoa/ReactiveCocoa#2338]
With RAC3 in Swift 2, I can't figure out how to change the type of a `SignalProducer<T, E>` to `SignalProducer<T, F>` on a `next` event.

I am using `NSURLSession.rac_dataWithRequest` which returns a `SignalProducer<(NSData, NSURLResponse), NSError>`. Now, on each `next` I want to check the `NSURLResponse` for non-200 status codes, and if so, produce an error event on the signal using my `MyError` error type (conforming to `ErrorType`). But if the status code is OK, I want to map the `(NSData, NSURLResponse)` to a `MyModel` object.

So essentially, I have a `flatMap` where I'm trying to convert:

`SignalProducer<(NSData, NSURLResponse), NSError>`

to:

`SignalProducer<MyModel, MyError>`

How do I go about this? I can transform the value on `next` using `map` or `flatMap`, and the error on `error` with `mapError` or `flatMapError`, but can't figure out how to transform the error type on a `next`.

**Comment by ikesyo** [comment]
Something like this? 

```swift
session.rac_dataWithRequest(request)
    .flatMapError { _ in MyError.NetWorkError }
    .flatMap(.Concat) { data, response -> SignalProducer<MyModel, MyError> in
        if (response as? NSHTTPURLResponse)?.statusCode == 200 {
            let model = MyModel(data: data, response: response)
            return SignalProducer(value: model)
        } else {
            return SignalProducer(error: MyError.NetworkError)
        }
    }
```

Since you cannot convert the error type in `flatMap()`, using `flatMapError()` at first is needed.

**Comment by erikjalevik** [comment]
Oh, that simple. For some reason I had got it into my head that flatMapError would not do anything at all on `next` events, and only kick in on an `error` event. But what happens is that it still converts the error type even if no error is sent.

(Which, when I think about it, is of course the only thing it can do since type signatures must be defined at compile-time.)

Thanks!
