### ISSUE TITLE
ReactiveCocoa (swift2 branch) wants Result 1.0 but Result :HEAD is 0.6

### ISSUE THREAD

**Issue by zbeckman** [ReactiveCocoa/ReactiveCocoa#2344]
Just tried to pull the Carthage build for ReactiveCocoa on the swift2 branch. Installed it (by dragging ReactiveCocoa.framework and Result.framework into my Embedded Binaries app.

As soon as I tried to launch the iOS simulator... got this:
```
dyld: Library not loaded: @rpath/Result.framework/Result
  Referenced from: /Users/zbeckman/Library/Developer/CoreSimulator/Devices/FCFAAFBF-1AB4-4223-9BCC-CA91CBDE96DC/data/Containers/Bundle/Application/0594BE74-9087-42D4-9C88-B3C0FFF2C852/Glimpulse.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Reason: Incompatible library version: ReactiveCocoa requires version 1.0.0 or later, but Result provides version 0.6.0
```
Seems like it's trying to depend on something that doesn't exist yet? (Result is 0.6.1 I believe...)

**Comment by NachoSoto** [comment]
Hmm that's very weird. Can you make sure you recompiled `ReactiveCocoa`? `rm -rf Carthage/Build/iOS` and `carthage update --platform ios` again?

**Comment by zbeckman** [comment]
I did. Also tried using a CocoaPod distribution (form ash furrow). Different problems but the same basic theme – linker errors. Been going around in circles on this for quite a while. I am using Xcode 7 GM.

**Comment by zbeckman** [comment]
Just FYI: The pod distribution yields this:
```
2015-09-11 22:09:57.861 XCTRunner[35003:2653747] (dlopen_preflight(/Users/zbeckman/Library/Developer/CoreSimulator/Devices/FCFAAFBF-1AB4-4223-9BCC-CA91CBDE96DC/data/Containers/Bundle/Application/E1F0A159-BC14-45FF-ACBD-17A7F2157DAD/GlimpulseUITests-Runner.app/PlugIns/GlimpulseUITests.xctest/GlimpulseUITests): Library not loaded: @rpath/libswiftCoreLocation.dylib
  Referenced from: /Users/zbeckman/Library/Developer/Xcode/DerivedData/Glimpulse-avhroqmcgyzbiecltqxshdpczkht/Build/Intermediates/CodeCoverage/Glimpulse/Products/QA 1-iphonesimulator/ReactiveCocoa.framework/ReactiveCocoa
  Reason: image not found)
```

**Comment by NachoSoto** [comment]
I've just finished updating this for my project (with 3 platforms) and everything's working.

Did you remove derived data?

**Comment by zbeckman** [comment]
Several times... thoroughly.

Is there anything special I need to do for iOS?

I've noticed that this problem *only seems to affect the iOS User Interface Testing* target. That is my regular unit testing targets work just fine. It's very strange.

**Comment by zbeckman** [comment]
During rebuild, I'm getting several warnings – including one about "you must rebuild with ENABLE_BITCODE":
```
*** Building scheme "ReactiveCocoa iOS" in ReactiveCocoa.xcworkspace
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'
ld: warning: Auto-Linking supplied '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
ld: warning: Auto-Linking supplied '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'
```
I'm wondering if this is the root of the problem? I've run into this before with other libraries – having the wrong flag causes XCTest to fail.

**Comment by NachoSoto** [comment]
I have no idea what's going on, I'm not seeing any of this :/

**Comment by zbeckman** [comment]
OMG. Well – that was painful. Tracked it down after going removing all CocoaPods, and slowly adding them back one at a time. BrightFutures includes a dependency for Result 0.6.1 which was pulling it in and screwing everything else up. Filed an issue: https://github.com/Thomvis/BrightFutures/issues/80. Thanks for your help and sorry for the distraction!

**Comment by NachoSoto** [comment]
Haha that makes sense :)

Glad you managed to track it down!

**Comment by neilpa** [comment]
Out of curiosity, why use both BrightFutures and ReactiveCocoa? Generally you'll want to stick with one Futures/Promises/Rx/etc library.

**Comment by zbeckman** [comment]
Experimental. And I really like the way it models Scala Futures/Promises, and am always trying to get our code base (Swift and Scala) to seem more and more similar.
