### ISSUE TITLE
Xcode 7 GM seed fails to build a basic demo app with ReactiveCocoa

### ISSUE THREAD

**Issue by borland** [ReactiveCocoa/ReactiveCocoa#2346]
I'd like to try out the new ReactiveCocoa, so I followed the instructions on the ReactiveCocoa front page, as follows:

1. Created a new iOS swift project (named ReactiveCocoaDemo) in Xcode 7 GM seed. I did not create a git repository because it's a throwaway project
2. from inside that project's directory, I did `git clone https://github.com/ReactiveCocoa/ReactiveCocoa.git --depth 1`
3. I then did `cd ReactiveCocoa` followed by `script/bootstrap`  
A bunch of stuff followed as it downloaded Box, Nimble, Quick and some other random words
4. Dragged ReactiveCococa.xcodeproj, Box.xcodeproj and Result.xcodeproj into my app's project. I just dragged them in under the ReactiveCocoaDemo sub folder
5. Under my target / General / Embedded Binaries, I added ReactiveCocoa.framework, Box.framework and Result.framework. I noticed there were 2 copies of each.
6. I removed the frameworks and added the second copy of each (as they were Debug-iphoneos and seemed better)
7. Try build the target.

Xcode reports "Build Failed" but there are no errors reported, and no log or error messages of any kind.

If I remove the embedded binaries, then it builds, however this is obviously not useful

I switched back to the other embedded frameworks (which show themselves as ReactiveCocoa-mac, Box-mac, Result-mac) and then the compile works, however it's full of errors. It looks like the code is all still targeting swift 1.2

**Comment by borland** [comment]
OK this ends up being all fine if I git clone the entire repository (not --depth 1) and switch to the 'swift2' branch before I do the script/bootstrap

Not a bug in RAC but perhaps the readme needs some love!

**Comment by NachoSoto** [comment]
@borland Looks like you were building `master`, which does not include the Swift 2 updates (see #2189).

`ReactiveCocoa` is actually going to become `4.0` (#2327) when we merge the swift 2 branch, which should make things more clear:
- RAC 3: Swift 1.2
- RAC 4: Swift 2.0

Sorry that this caused you trouble!
