### ISSUE TITLE
[Question] How to avoid re-executing a SignalProducer's subscription code

### ISSUE THREAD

**Issue by s0mmer** [ReactiveCocoa/ReactiveCocoa#2348]
Hi, I have the following code:

```swift
// Handle view being active/inactive
let active = NSNotificationCenter.defaultCenter().rac_addObserverForName(UIApplicationDidBecomeActiveNotification, object: nil).toSignalProducer()
    |> ignoreError
    |> map { _ in
        true
    }
let inactive = NSNotificationCenter.defaultCenter().rac_addObserverForName(UIApplicationWillResignActiveNotification, object: nil).toSignalProducer()
    |> ignoreError
    |> map { _ in
        false
    }

let viewIsActive = merge([active, inactive])

// Handle fetching of menu by fetching it every time the view gets active.
let menu = viewIsActive
    |> filter { $0 }
    |> promoteErrors(NSError)
    |> flatMap(.Latest) { _ in
        return fetchTodaysMenu()
    }

// Make sure, we're only showing the menu when it's actually the menu of today.
self.shouldHideMenu <~ menu
    |> ignoreNil
    |> ignoreError
    |> map { menu in
        !menu.isTodaysMenu()
    }
```

Where `fetchTodaysMenu()` returns a `SignalProducer<Menu?, NSError>`.

My problem is that (not suprisingly) that every time I bind `menu` to something, the code in `fetchTodaysMenu()` will be run multiple times, because it gets multiple subscriptions. What I would like to do is that every new subscriber to `menu` does not make `fetchTodaysMenu()` perform it´s code. Only the `viewIsActive` should be able to trigger the code of `fetchTodaysMenu()`.

In RAC 2.x I would probably solve this using a combination of `replayLazily` and `replayLast`, but I'm unsure how to do this in RAC 3. I've been playing with `pipe()` and `buffer()`, but without achieving the wanted result.

**Comment by almassapargali** [comment]
What about making `menu` `MutableProperty` and then binding it's `producer` property?

**Comment by s0mmer** [comment]
@almassapargali thanks for this suggestion. This does solve the problem, but it is also somewhat annoying to have to create `MutableProperty`s to avoid this. I'm going for this solution for now, but I'm still interested in other solutions. Thanks again!

**Comment by s0mmer** [comment]
The `replayLazily` operator has now been merged into RAC 4 and I can now use that to solve my problem. See https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2639 for more information. This issue can be closed.
