### ISSUE TITLE
Need a RAC 4 alpha release

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2355]
People are targeting Swift 2 and without a baseline alpha release it's going to be very hard to manage breaking changes across transitive dependencies (c.f. neilpa/Rex#31).

This at least depends on #2356

**Comment by NachoSoto** [comment]
:thumbsup: what's stopping us from doing that right now?

**Comment by neilpa** [comment]
Nothing, I just opened this in case someone else wanted to tackle it before I could get to it.

**Comment by NachoSoto** [comment]
I can do it this evening :)
On Mon, Sep 14, 2015 at 1:53 PM Neil Pankey <notifications@github.com>
wrote:

> Nothing, I just opened this in case someone else wanted to tackle it
> before I could get to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2355#issuecomment-140203073>
> .
>
-- 
Ignacio Soto

**Comment by NachoSoto** [comment]
I drafted a release and uploaded the frameworks. We can publish when #2356 is merged :)

**Comment by neilpa** [comment]
I want to take another pass at the `startWith*` and `observe*` changes before we push it. These were really annoying when I tried to upgrade Rex.

**Comment by neilpa** [comment]
Should also explicitly call out that the API is in flux and will be changing so be ready for that if you depend on it.

**Comment by neilpa** [comment]
Although, I could be convinced that the `startWith*` and `observe*` could be iterated in a later alpha. Especially since we're looking at other big breaking changes -- #2349 and #2360.

**Comment by NachoSoto** [comment]
> I want to take another pass at the startWith* and observe* changes before we push it. These were really annoying when I tried to upgrade Rex.

What was annoying about it?

> Although, I could be convinced that the startWith* and observe* could be iterated in a later alpha. Especially since we're looking at other big breaking changes -- #2349 and #2360.

Yeah, I feel like since 7.0 GM has been out for a few days, we should try to get a release sooner rather than later.

> Should also explicitly call out that the API is in flux and will be changing so be ready for that if you depend on it.

:+1: done

**Comment by neilpa** [comment]
> What was annoying about it?

Doing the conversion by hand was a bit painful and I wasn't satisfied with the resulting code. Maybe it's a matter of preference on pattern matching vs. named closure params. However, if we're going to offer convenience methods for the latter, I want something better.

**Comment by NachoSoto** [comment]
Yeah I agree!
