### ISSUE TITLE
Swift 2 branch Requires XCode 7.1.

### ISSUE THREAD

**Issue by amccarri** [ReactiveCocoa/ReactiveCocoa#2358]
Looks like XCode 7.1 is required to build the Swift 2.0 branch due to Result requiring tvOS sdk.

**Comment by NachoSoto** [comment]
Yeah, this is the same as https://github.com/Carthage/Carthage/issues/754.

I think we're going to have to take the scheme out temporarily until 7.1 is GM, which is annoying.

**Comment by amccarri** [comment]
Also, I was able to get this to work by using —platform iOS.

**Comment by neilpa** [comment]
The `--platform ios` trick only works with carthage 0.8 though.

**Comment by NachoSoto** [comment]
@neilpa I downgraded to 0.8 and I can't get that to work now for some reason 😨though I swear that was working yesterday.

**Comment by amccarri** [comment]
hrrrm? I didn't even see that .9 was out, brew seems to think I have the latest at 0.8.0... anyway with 0.8 it seems to work with carthage update --platform iOS.

**Comment by ikesyo** [comment]
`--platform iOS` with Carthage 0.9.1 and Xcode 7 GM works for me. :astonished:

**Comment by NachoSoto** [comment]
Well this should be fixed with #2359 (thanks @neilpa).
I apologize for the inconvenience!
