### ISSUE TITLE
trying to understand why the compiler is complaining about binding

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2362]
So I'm trying to bind this mutable property to the string signal.

```
func bindViewModel() {
    let stringProp = MutableProperty<String>("")
    let (stringSignal, stringSink) = Signal<String, NoError>.pipe()

    stringProp <~ stringSignal
}
```
My understanding is that the types match with this function signature:
```
func <~<P : MutablePropertyType>(property: P, signal: ReactiveCocoa.Signal<P.Value, ReactiveCocoa.NoError>) -> Disposable
```
Yet the compiler seems confused about which operator to use and prints out this error:
```
error: ambiguous operator declarations found for operator
        stringProp <~ stringSignal
                   ^
```

the types seem to checkout in my opinion but not according to the compiler ... Any idea how to resolve this bind ?

From: http://stackoverflow.com/questions/32592880/having-trouble-binding-mutablepropertystring-to-a-signalstring-noerror-with

**Comment by NachoSoto** [comment]
Hmm yeah that looks correct to me too. Can you add explicit types to all 3 variable declarations to make sure everything is what you expect?

**Comment by edwardIshaq** [comment]
Thanks @NachoSoto I found out the problem is that the compiler is unable to distinguish between 

ReactiveCocoa.<~
and 
it appears the compiler is unable to distinguish between the ReactiveCocoa.<~ and

infix operator <~ {}
public func <~ (rac: RAC, signal: RACSignal) {
    rac.assignSignal(signal)
}
which was create by Created by Colin Eberhardt.

I am not sure yet how to work around it. the arguments are completely different ...

Any un intrusive suggestions, I'm thinking changing the RAC operator to <~~ rather would be easy so to keep ReactiveCocoa.<~ the primary one.

I wonder if adding infix priority would matter ?

**Comment by NachoSoto** [comment]
Where is that other operator defined?

**Comment by edwardIshaq** [comment]
Its defined in my own framework, which is included on the problem file above.
Once i commented out the import statement it compiled correctly

**Comment by NachoSoto** [comment]
Sounds like the easiest solution then is for you to use a different operator so that they don't collide :)

**Comment by edwardIshaq** [comment]
yea, i guess.

I just think its very odd that the compiler can't distinguish between the two as the arguments are clearly different ...

func <~<P : MutablePropertyType> (property: P, signal: ReactiveCocoa.Signal<P.Value, ReactiveCocoa.NoError>) -> Disposable

-VS-
public func <~ (rac: RAC, signal: RACSignal) {

where RAC is defined as:

public struct RAC  {
  var target : NSObject!
  var keyPath : String!
  var nilValue : AnyObject!
  
  public init(_ target: NSObject!, _ keyPath: String, nilValue: AnyObject? = nil) {
    self.target = target
    self.keyPath = keyPath
    self.nilValue = nilValue
  }
  
  
  public func assignSignal(signal : RACSignal) {
    signal.setKeyPath(self.keyPath, onObject: self.target, nilValue: self.nilValue)
  }
}

**Comment by edwardIshaq** [comment]
i found that Ash Furrow already stumbled on this issue 
https://github.com/ashfurrow/Swift-RAC-Macros/commit/57b041d8a99a3e2a90583709ed7ed91f8ca271b8
and solved using the precedence

**Comment by edwardIshaq** [comment]
Now that I've changed the precedence to 93 as in ReactiveCocoa the compiler seems happy. 
No Find/Replace today :)

**Comment by NachoSoto** [comment]
Awesome!

**Comment by edwardIshaq** [comment]
by the way, the precedence has to match exactly for it to work. I thought initially if its lower it would work but neither lower or hight did. So, i guess i learned something.
