### ISSUE TITLE
[Question] Binding a bool from multiple result in Swift

### ISSUE THREAD

**Issue by Lucashuang0802** [ReactiveCocoa/ReactiveCocoa#2364]
I am doing some experiments on ReactiveCocoa in both Objective-C language and Swift. However, I can not find a way to implement the same functionality with Swift

Here is the Objective-C version:

    - (instancetype)init
    {
        self = [super init];
        if (self) {
            
            RAC(self, isLoginButtonEnabled) = [RACSignal combineLatest:@[RACObserve(self, username), RACObserve(self, password)] reduce:^(NSString *newUsername, NSString *newPassword) {
                
                return @(newUsername.length && newPassword.length);
            }];
        }
        return self;
    }

I always got error when I do the same thing with Swift, BTW you need to import [Swift-RAC-Macros][1] in order to get `RAC` and `RACOBserve` in Swift:

    override init() {
        super.init()
            
            
        RAC(self, "isLoginButtonEnabled", false) <~ RACSignal.combineLatest([RACObserve(self, "username"), RACObserve(self, "password")], reduce: {(newUsername: String?, newPassword: String?) -> AnyObject? in
                
            return false;
        })
    }

For this I always get error: 
`(RAC, _) is not convertible to 'RACSignal'`. Can anyone give me how to do that?

  [1]: https://github.com/ashfurrow/Swift-RAC-Macros

**Comment by RuiAAPeres** [comment]
@Lucashuang0802 were you able to solve this?

**Comment by Lucashuang0802** [comment]
@RuiAAPeres I figured that out already. Thanks.
