### ISSUE TITLE
Build problem with v4.0

### ISSUE THREAD

**Issue by MarvinNazari** [ReactiveCocoa/ReactiveCocoa#2365]
Hi, i get /X/Carthage/Build/iOS/ReactiveCocoa.framework/Headers/ReactiveCocoa.h:67:10: 'ReactiveCocoa/MKAnnotationView+RACSignalSupport.h' file not found when i try to build I'm using latest Carthage and ReactiveCocoa v4.0

**Comment by NachoSoto** [comment]
Try cleaning derived data

**Comment by MarvinNazari** [comment]
Still getting the error

**Comment by MarvinNazari** [comment]
Carthage is using ReactiveCocoa.framework.zip and inside the .framework those files are missing
