### ISSUE TITLE
[Question] Framework support for tvOS

### ISSUE THREAD

**Issue by bruceflowers** [ReactiveCocoa/ReactiveCocoa#2374]
This is off topic, but I've successfully built RAC for tvOS and I was wondering how you guys implemented this so I could take a stab and doing the same for a different library.  

Does anyone here have pointers/links for how to add tvOS support to what currently happens to be an iOS framework project?  My goal state would be to build it using Carthage.

**Comment by NachoSoto** [comment]
Yup! See the original #2333 and #2361
