### ISSUE TITLE
RAC4 question. Recommended approach to migrate free functions and replace |>

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2377]
What would be suggested approach to move code like following to a RAC4?
```
    public func connectDevice(deviceType: HuamiType) -> SignalProducer<Device, PeripheralError> {
        return prepareForScanning()
            |> findNearbyDevice(deviceType, RSSI: -60)
            |> connectDevice
            |> discoverServicesForDevice
            |> discoverCharacteristicsForDevice
    }
```

Before I used a |> to apply locally defined functions, it was a pleasant experience. Now I am not sure how to chain it. It definitely would not work with extension for SignalProducerType, as there is a strict type of  SignalProducer expected, as well as chined functions have side effects (opsie, I know this is bad) as they use some entity variables like centralManager etc.

**Comment by NachoSoto** [comment]
Can you show how those functions were defined in `RAC 3`?

> Now I am not sure how to chain it. It definitely would not work with extension for SignalProducerType, as there is a strict type of SignalProducer expected

What do you mean by "as there is a strict type of SignalProducer expected"? If you mean that the `T` has to match a certain type, you can still do that! :) For example:

```swift
extension SignalProducerType where T: YourProtocol {
	public func findNearbyDevice(deviceType: DeviceType, RSSI: Int) -> SignalProducer<T, E> {
		return self.map { value in 
                       // here `value` conforms to `YourProtocol`
                       return ...
                }
	}
}
```

**Comment by calebd** [comment]
I have a similar problem. I have view model properties (`SignalProducer<ViewModel?, NoError>`) that have image producers (`SignalProducer<UIImage, NSError>`). If I `map({ $0?.imageProducer })` I end up with a `SignalProducer<SignalProducer<UIImage, NSError>?, NoError>`. I use the following function to flatten that result:

```swift
func promoteNil<T, E>(producer: SignalProducer<SignalProducer<T, E>?, E>) -> SignalProducer<T?, E> {
    return producer |> flatMap(.Latest, { thing in
        if let producer = thing {
            return producer |> map({ .Some($0) })
        }
        else {
            return SignalProducer<T?, E>(value: nil)
        }
    })
}
```

So now I can do `viewModel.producer |> promoteErrors(NSError) |> map({ $0?.imageProducer }) |> promoteNil` which results in a `SignalProducer<UIImage?, NSError>`.

I have yet to find a way to make that chainable.

**Comment by nikita-leonov** [comment]
@NachoSoto I actually can get ride of state and side effects in my code easily, so self reference is not a problem. What is worries me more is how to deal with protocol extension. There is a requirement for T to be a protocol, but how can I refactor following method signature into extension?
```
func findNearbyDevice(deviceType: DeviceType, RSSI: Int) -> SignalProducer<ReactiveCentralManager, NoError> -> SignalProducer<(deviceType: DeviceType, peripheral: ReactivePeripheral, advertisement: [String: AnyObject]), NoError>
```

While for ```ReacticeCentralManager``` I can define some type, what would be a replacement for a tuple?

**Comment by NachoSoto** [comment]
You can still encode the requirement for `T` being `ReactiveCentralManager`:

```swift
extension SignalProducerType where T == ReactiveCentralManager, E == NoError {
    func findNearbyDevice(deviceType: DeviceType, RSSI: Int) -> SignalProducer<(deviceType: DeviceType, peripheral: ReactivePeripheral, advertisement: [String: AnyObject]), NoError> {
       // `self` here is `SignalProducer<ReactiveCentralManager, NoError>`
    }
}
```

**Comment by nikita-leonov** [comment]
Even more... What if my Signal has type String? What is recommended type to be used?

**Comment by nikita-leonov** [comment]
... ok let me process it I think it will work. Apparently I need to read through the generics, pattern matching and protocol oriented design presentation one more time. Thanks.

**Comment by nikita-leonov** [comment]
It works very well. One more improvement for my lovely codebase. It really made it much more clear.

**Comment by NachoSoto** [comment]
<3

**Comment by nikita-leonov** [comment]
@NachoSoto followup question. I noticed that flatMap defined in SignalProducer, not SignalProducerType, while map and flatten are in SignalProducerType. Could you explain the logic behind this decision? In my particular case I was planning to use flatMap in extension.

**Comment by NachoSoto** [comment]
I think @neilpa originally added some extensions to `SignalProducer` instead (and I followed up with `flatMap`) due to compiler crashes, but it might not be needed anymore.

Can you confirm @neilpa?

**Comment by neilpa** [comment]
Ideally these should either all be defined in terms of the protocol or defined concretely. When I implemented them it wasn't possible either due to compiler crashes or language limitations. I haven't revisited them much since, but should take another pass to see if the implementations can be improved/unified.

**Comment by nikita-leonov** [comment]
@neilpa I created PR #2380 where moved flatMap. However I am not sure that it means it can be merged, as you mentioned about some special scenarios.
