### ISSUE TITLE
Discussion: Testability changes between RAC3 & RAC4

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2379]
I would like to have your opinion regarding current approach in defining custom functions for ```Signal``` & ```SignalsProducer```. Previously with ```|>``` it was possible to locate functions in any place and apply them  as needed. The good thing we had an absolute control on accessibility of this functions, as they were contained in particular class. Now recommended way is extensions for ```SignalType``` and ```SignalProducerType```. This makes this functions be visible everywhere in the code if extensions are not private. To avoid pollution of namespaces we need to make extensions private but this negatively affecting testability. 

As for today I have these functions internal, which worries me a lot when I see all of them in different sections of my code where I not supposed to see them. Is there any alternative? Am I missing somewhere ```apply``` function that allows to chain signals like ```|>``` but just for a user defined scenarios?

**Comment by NachoSoto** [comment]
I'm not sure I understand the question.
> Previously with |> it was possible to locate functions in any place and apply them as needed. 

Nothing has changed. The only difference is that `func`tions aren't free anymore, but you can still control their visibility in the same way.

**Comment by nikita-leonov** [comment]
Previously:
```
public class MyClass {
  public func doSomething(someSignalProducer) {
    someSignalProducer |> processSignal 
    |> doSomethingElese 
    |> start()
  }
  public func processSignal(signalProducer: SignalProducer<Void, NoError>) -> SignalProducer<Void, NoError> { 
    return ...
  }
}
```

In a such setup processSignal had a limited visibility, and was testable easily. Now we have following situation:
```
public class MyClass {
  public func doSomething(someSignalProducer) {
    someSignalProducer.processSignal()
    .doSomethingElese
    .start()
  }
}

public extension SignalProducerType where T == Void, E == NoError {
  public func processSignal(signalProducer: SignalProducer<Void, NoError>) -> SignalProducer<Void, NoError> { 
    return ...
  }
}
```

Testability of ```processSignal``` is the same, but visibility around the code is much bigger, now it is visible all around the project where SignalProducerType is used. Is there a trick how to avoid this?

**Comment by nikita-leonov** [comment]
I am actually happy that we have all methods are not free now, but I would be happy as well to retain apply function for cases as described above.

**Comment by iv-mexx** [comment]
> Testability of processSignal is the same, but visibility around the code is much bigger, now it is visible all around the project where SignalProducerType is used. Is there a trick how to avoid this?

Sorry, I have not played around with that enough to be sure about this, but is this not the kind of problem that [@testable](http://natashatherobot.com/swift-2-xcode-7-unit-testing-access/) is supposed to solve?

Is it possible to declare your extension as private and use @testable to make it visible in your testcase?

**Comment by iv-mexx** [comment]
Ok sorry, it seems that `@testable` does not make `private` functions visible:

> Use @testable import {ModuleName} in your test source code to make all public and internal routines usable by XCTest targets, but not by other framework and app targets.

https://developer.apple.com/library/prerelease/ios/documentation/DeveloperTools/Conceptual/WhatsNewXcode/Articles/xcode_7_0.html

**Comment by nikita-leonov** [comment]
@iv-mexx unfortunately it is not, since we are talking not about external visibility, but about internal visibility. ```processSignal``` will be visible for every ```SignalProducerType``` across whole module except scenarios when he marked as ```private```. When is it ```private``` then ```@testable``` does not help as it works only for internal.

**Comment by nikita-leonov** [comment]
@NachoSoto does my further comment clarified a problem or it is still require additional details?

**Comment by NachoSoto** [comment]
Oh I see what you're saying now. Yeah, unfortunately there is no equivalent way of namespacing methods inside of an extension.

**Comment by nikita-leonov** [comment]
So would it be reasonable reincarnate operator ``|>`` as not-free function ``apply``? I think it is meaningful function that has a lot of real cases to solve. I do understand that API need to be limited, to ensure that it still easy to use, but ``apply`` does not break this rule.

**Comment by neilpa** [comment]
I'm :-1: on adding `apply`. It's useful for those already familiar with FP, but it adds yet another concept for people who aren't which is a lot of users.

**Comment by nikita-leonov** [comment]
Ok. This is what I can do then. I will arrange ``apply`` function as micro-framework on during this weekend. At the point when you decide to add it into RAC I will be happy to move it and make my project obsolete. Or we can even arrange it as sub-project on ReactiveCocoa account. Anyway thanks for a feedback, I do understand that ``apply`` is not easiest thing to understand. Meanwhile it is easier to understand for most of people in compare with ``flatMap`` or ``flatten(.Latest)``.

**Comment by nikita-leonov** [comment]
@neilpa @NachoSoto I agree about additional complexity of `apply`, meanwhile I believe it has its own value for developers. For those who understand how it works and why it is needed I retained `|>` as a protocol extension for `Signal` & `SignalProducer` in a separate project — https://github.com/nikita-leonov/ReactiveCocoaApply
