### ISSUE TITLE
Document how to diagnose compiler type-errors

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2381]
E.g. Breaking apart signal chains with local vars and explicit type annotations. This is a general strategy for type errors but is especially relevant with long chains and I've seen several people get tripped up by it.

**Comment by nikita-leonov** [comment]
We actually planned to put some debugging techniques into our company's coding convention document.  This technique one of many that we planned to describe. I can write this technique as separate document and share it with community. The only thing that with my broken english someone will need to verify grammar afterward. If you are ok I can write it. Thoughts? :)

**Comment by neilpa** [comment]
That's fine. I'm happy to review and help clean it up if you want to take an initial stab at it.

**Comment by nikita-leonov** [comment]
It is interesting. With removing of `|>` errors become less cryptic. Now compilation error happening in the place where you actually wrong, but not somewhere else. I was able to reproduce some bugs that still benefit from breaking down chains into smaller pieces, but it is not so representative anymore as it was before.

**Comment by nikita-leonov** [comment]
So for example case described in the following article — http://blog.scottlogic.com/2015/04/24/first-look-reactive-cocoa-3.html is not actual anymore for a current RAC and current compiler version.

**Comment by nikita-leonov** [comment]
Done. I do not think that provided example in the document is the best one to have, but any old cases that I had before is not require this technique anymore due to updated of compiler. 

Also I think that this document should eventually contain following recommendations described:
* Use of instruments
* Use of DebugSinkOf
* Debugging signals through documenting expectations as test

**Comment by nikita-leonov** [comment]
@neilpa I would like to continue work on other improvements for the document in separate PR. Current PR covers everything what you suggested to document in a current ticket. Is it good for merge or anything else required?

**Comment by neilpa** [comment]
I added a few more notes to that PR. Otherwise really good stuff and feel free to start a new PR based on those changes.

**Comment by nikita-leonov** [comment]
Should we close this issue and create three separate tickets for following items:
- Use of instruments
- DebugSinkOf
- Debugging with tests

?

**Comment by neilpa** [comment]
Yea. And if you're planning on tackling those shortly just feel free to open PRs w/out issues.

**Comment by nikita-leonov** [comment]
k. I will be available for doing this, but not immediately. So I prefer to have it recorded as issues to ensure that tasks will not lost after some time.

**Comment by nikita-leonov** [comment]
I will create tickets later after EOB.
