### ISSUE TITLE
iOS 9 performance issues

### ISSUE THREAD

**Issue by karmeye** [ReactiveCocoa/ReactiveCocoa#2383]
I got major performance degradation on iOS 9 compared to iOS 8. I suspect it's related to these radars and this method:

`[NSObject addObserver:forKeyPath:options:context:] `

* https://openradar.appspot.com/22718949
* https://openradar.appspot.com/22718754

Anyone else who can relate?
I notice it mostly when loading / reloading collection views, which means signals are created and observers added for views, view models and models related to the cells.

**Comment by joshaber** [comment]
Yup, this is a problem for us too. Unclear at this point how we can mitigate it.

**Comment by neilpa** [comment]
facebook/KVOController#72 has a disturbing graph of the problem

**Comment by karmeye** [comment]
@neilpa Ouch, that's looks really bad.

`addObserver` is pretty much the heart of RAC isn't it? 
Guess we're dependent on a fix from Apple. Even if we can somehow mitigate it, its not good enough if its not around O(1).

I'll go dupe these radars.

**Comment by neilpa** [comment]
My guess is they "fixed" the dealloc races that existed in KVO prior to iOS9. Working around those races is the main reason for `KVOController`. There's numerous past issues in this repo that touch on the problem as well.

**Comment by mdiep** [comment]
This was part of the motivation for https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2334.

**Comment by neilpa** [comment]
Sadly, `RACCommand` is likely only a small portion of the general `RACObserve` usage across an app.

**Comment by karmeye** [comment]
Apparently many KVO issues was fixed. 

But this issue has now been "observed" :) No need to dupe more radars:

https://twitter.com/Catfish_Man/status/644928403402018820
https://twitter.com/steipete/status/644903661626331141
