### ISSUE TITLE
[Question] New platform test target linking to wrong instance of a built framework

### ISSUE THREAD

**Issue by bruceflowers** [ReactiveCocoa/ReactiveCocoa#2385]
This is off topic, but I imagine you guys might have seen this now that you've started supporting tvOS...

I’m developing a library which initially only supported iOS, and now I’ve added the tvOS framework and test targets. There are dependencies, and those frameworks have already been built using Carthage, one for each architecture (so there is a discreet .framework instance of each library for iOS and tvOS respectively).  In build phases, I’ve linked only the tvOS-compatible frameworks to the tvOS framework and test targets.

The test classes are shared between both iOS and tvOS test targets. 

Here’s where it gets weird:

When running a test class under the iOS test target which imports a module built for iOS, the tests pass.

When running the same test class under the tvOS test target (which should be linking in the specific tvOS-built version of the module), I get this error:

“Module file was created for incompatible target x84_64-apple-ios8.0…”

First, have you encountered this, and if so, how did you solve it?

**Comment by bruceflowers** [comment]
I've also asked this at https://github.com/Carthage/Carthage/issues/775 in case someone there also has an idea.

**Comment by neilpa** [comment]
Does `tvOS` even support test targets? `watchOS` doesn't so I'm wondering if that's the case here?

**Comment by bruceflowers** [comment]
yep - xcode 7.1 allows for the creation of a tvOS test target, and test cases that don't import a library such as this have no issues so far.
