### ISSUE TITLE
How do I call `on` on Signal?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#2394]
Before I could do something like this:

```
signal
  |> on(next: { _ in /* do stuff */ }
  |> flatMap(.Latest) {
  }
```

How would I approach this pattern in RAC4 now that |> has been removed? I can't seem to find how to lift signals to signal producers.

**Comment by neilpa** [comment]
That's an unintended "hack" for converting signals to producers. We don't want an explicit operator for this behavior because events could be missed when going from hot to cold. However, if `flatMap` is all you need, that operator is available on signals in RAC 4

**Comment by NachoSoto** [comment]
An alternative (and I think more explicit) way to do the equivalent to `on` with `Signal` is to `observe` again :)

**Comment by neilpa** [comment]
Yea, I'm fine with that. What we don't want is an operator in RAC that directly does this because of the potential for unexpected results when missing events.

**Comment by eimantas** [comment]
@neilpa I need to send a value to a related sink in `on` block and then return a different signal producer from `flatMap`.

**Comment by neilpa** [comment]
Because you're starting with an already hot signal you can freely `observe` it multiple times.

```swift
signal.observe { /* send to related sink */ }
signal.flatMap(strategy) |> start { /* do something else */ }
```

**Comment by eimantas** [comment]
I bound the button to a method that does observe/flatMap and now the button "works" only second time it's tapped.
