### ISSUE TITLE
ReactiveCocoa.framework showing as ".framework" in my projects

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveCocoa/ReactiveCocoa#2395]
On a brand new iOS SDK Xcode 7 project, ReactiveCocoa.framework is being shown as `.framework`. Seems like build settings might be a bit skewiff. Installed via Carthage with the `--no-build` option and then manually adding RAC as a subproject of my app's project.

**Comment by neilpa** [comment]
We should just set $PRODUCT_NAME explicitly instead of relying on `xcconfig` if it's not going to inherit it correctly in all configurations.
