### ISSUE TITLE
Include framework dependency binaries in Downloads section for each release

### ISSUE THREAD

**Issue by github-user32** [ReactiveCocoa/ReactiveCocoa#2396]
In the Downloads section of each release at https://github.com/ReactiveCocoa/ReactiveCocoa/releases, it would be handy to include not only the ReactiveCocoa.framework binary, but also the binaries of the other (non-Apple) frameworks it depends on such as Result, Box, etc. 

This would make it possible to start using a ReactiveCocoa release in a project without having to worry about building these dependencies from scratch.

**Comment by RuiAAPeres** [comment]
@github-user32 if you need Result's binaries, you can get them from the Result's repo.
