### ISSUE TITLE
Document use of DebugSinkOf

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#2401]
There are two different sink objects used depends on build configuration. DebugSinkOf and SinkOf. There is no documentation that explaining this specific, as well as how to use this helpful for debugging tool.

**Comment by ikesyo** [comment]
`DebugSinkOf` is removed in RAC 4 because of `SinkType` and `SinkOf` removal in Swift 2 standard lib. So I'm not positive about putting some efforts into it.

**Comment by nikita-leonov** [comment]
Wonderful. Since I planned to invest my own time into document this it is even better.
