### ISSUE TITLE
Convenient way of terminating a hot signal by cold `rac_willDeallocSignal().toSignalProducer()`

### ISSUE THREAD

**Issue by SiarheiBarysenka** [ReactiveCocoa/ReactiveCocoa#2402]
In ReactiveCocoa 2 it was pretty easy to terminate a signal by `rac_willDeallocSignal` with `takeUntil` in spite of target signal being hot or cold.

ReactiveCocoa 3+ provides two different signatures of public methods `takeUntil` for signals and producers. So, the hot `Signal` can be terminated only by hot `Signal` and the cold `SignalProducer` can be terminated only by cold `SignalProducer`.

Since `rac_willDeallocSignal` transforms into signal producer by using `rac_willDeallocSignal().toSignalProducer()`, is there any convenient way of terminating a hot `Signal` by this cold `SignalProducer`?

**Comment by siemensikkema** [comment]
I needed this too and came up with the following:
```swift
protocol SelectorValue {
	var rawValue: Selector { get }
}

enum ViewControllerSelector: Selector, SelectorValue {
	case ViewDidDisappear = "viewDidDisappear:"
}

func ignoreError(_: NSError) -> SignalProducer<(), NoError> {
	return .empty
}

extension NSObject {
	func signalForSelector(selector: SelectorValue) -> Signal<(), NoError> {

		var signal: Signal<Void, NoError>?

		rac_signalForSelector(selector.rawValue)
			.toSignalProducer()
			.map { _ in }
			.flatMapError(ignoreError)
			.startWithSignal {
				signal = $0.0
		}

		return signal ?? Signal.never
	}
}
```
Which I can now use in my view controller's `viewDidLoad` like so:
```swift
someSignal
	.takeUntil(signalForSelector(ViewControllerSelector.ViewDidDisappear))
	.observeNext {
		...
}
```
This works well for me but I'm not sure if Reactive Cocoa gurus will agree with this approach. If not, is there a better way?

**Comment by jamesdo** [comment]
I came across this post to see how to deallocate signals. It seems that the self gets captured inside the Signal blocks. It kinds of gets annoying to write `[weak self]` everywhere and very easy to forget.

Is this the only way to use .takeUntil ?

**Comment by mdiep** [comment]
> is there any convenient way of terminating a hot Signal by this cold SignalProducer?

Not currently. I expect this will improve with RAC5 as we add Cocoa extensions.
