### ISSUE TITLE
ReactiveCocoa pod install: Unable to satisfy requirements for ReactiveCocoa 3.0.0

### ISSUE THREAD

**Issue by thisisjeffwong** [ReactiveCocoa/ReactiveCocoa#2404]
I'm trying to upgrade from 2.4.1 to 3.0.0 but I keep getting this cryptic message:

```
[!] Unable to satisfy the following requirements:

- `ReactiveCocoa (~> 3.0.0)` required by `Podfile`
```

My podfile line is as follows:
```
  pod 'ReactiveCocoa', '~> 3.0.0'
```
(changed from 2.4.1)

Is there some other subdependency that I need to add?

thanks!

**Comment by altyus** [comment]
It appears that ReactiveCocoa 3.0 is being deployed with Carthage and not CocoaPods

**Comment by altyus** [comment]
Two things I had to do in my podfile/project.  Podfile's platform must be 8.0 or higher `platform :ios, "8.0"` and must specify to use_frameworks! `use_frameworks!`

**Comment by palcalde** [comment]
@thisisjeffwong It seems that your project supports ios7 and the 3.0.0 pod version says the min version is 8

**Comment by thisisjeffwong** [comment]
@palcalde 

Yeah, that's it. I did not see any mention of that in the changelog:

https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v4.0-alpha.1/CHANGELOG.md#30

Though I should have figured this was the case by re-reading the Readme.
