### ISSUE TITLE
How to map SignalProducer from one type to another?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#2407]
I want to map the `UITextField`'s textSignal's producer to a different type. Now `toSignalProducer()` returns `SignalProducer<AnyObject?, NSError>`. How can I map it to different type of SignalProducer?

Currently this is my attempt with compilation failure:

```
let fieldProducer = textField.rac_textSignal().toSignalProducer()
    .map { value in
        let string = value as String
        return SignalProducer<Bool, NoError> { o, d in
            sendNext(o, string.length > 0)
        }
    }
```

I think it's really something trivially simple. To my understanding - `map` should take a value from a signal, map it to different value and return a `SignalProducer` with the type of that new value. What am I doing wrong?

**Comment by rpowelll** [comment]
Try something like this:

```swift
let fieldProducer = textField.rac_textSignal()
    .toSignalProducer()
    .map { text in text as! String }
    .map { string in string.length > 0 }
```

**Comment by eimantas** [comment]
Wow, it's even simpler than I thought! This works. Thanks!

**Comment by rpowelll** [comment]
:ok_hand: no problem
