### ISSUE TITLE
Better pattern to slow the number of time subscribeNext is triggered with RACObserve

### ISSUE THREAD

**Issue by JeanLebrument** [ReactiveCocoa/ReactiveCocoa#2408]
Hi,

For my needs, I used `RACObserve` on `currentPlaybackPosition` attribute of the Spotify Player class from the Spotify iOS SDK.

The attribute's value is updated every .2 second by the Spotify Player class. Since I performed an action each time its value is changed, the CPU usage became quite intensive. I decided to find a way to slow down the triggering of my `subscribeNext` to each second.

After some tries, I found this solution:

    RACObserve(player, keyPath: "currentPlaybackPosition")
      .combineLatestWith(RACSignal.interval(1, onScheduler: RACScheduler.mainThreadScheduler()))
      .map({ return ($0 as! RACTuple).first })
      .subscribeNext { [unowned self] interval in
        // DO STUFF
    }

The above code works well but the way I achieved this doesn't satisfy me. I'm wondering if there is a cleaner way to do so. If not, would it be relevant to create a method to `RACSignal` class to hide such a mechanism? For example:

    RACObserve(player, keyPath: "currentPlaybackPosition")
      .interval(1, onScheduler: RACScheduler.mainThreadScheduler())
      .subscribeNext { [unowned self] interval in
        // DO STUFF
    }

If the community thinks so, I would be glad to contribute to ReactiveCocoa by adding this feature!

Best,
Jean

**Comment by eimantas** [comment]
Try `throttle:`. I found out about it from this presentation by @NachoSoto: https://realm.io/news/nacho-soto-functional-reactive-programming/

**Comment by JeanLebrument** [comment]
I already tried `throttle` but didn't work. The `subscribeNext` wasn't call anymore.

I guess `throttle` only triggers `subscribeNext` only if the last event has been sent more than the interval time passed in parameter.

**Comment by iv-mexx** [comment]
Yes, the `throttle` operator in the ObjC API (on `RACSignal`) behaves like [debounce](http://rxmarbles.com/#debounce):
> Sends `next`s only if we don't receive another `next` in `interval` seconds.

The `throttle` operator in the new Swift API (should be what you want, but I don't think theres an equivalent in the ObjC API.

For your use case, maybe `sample` is more appropriate? 

> /// Sends the latest value from the receiver only when `sampler` sends a value.
> /// The returned signal could repeat values if `sampler` fires more often than
> /// the receiver. Values from `sampler` are ignored before the receiver sends
> /// its first value.

```
RACObserve(player, keyPath: "currentPlaybackPosition")
  .sample(RACSignal.interval(1, onScheduler: RACScheduler.mainThreadScheduler()))
  .subscribeNext { [unowned self] sampledPlaybackPosition in
    // DO STUFF
}
```

This should send the current value of `currentPlaybackPosition` every 1 second, no matter how fast `currentPlaybackPosition` changes. Note that this will continue to send `currentPlaybackPosition` even if it does not change, but if I'm correct, so does your first example.

Note, I did not try this in particular, just a similar sample in ObjC.

**Comment by JeanLebrument** [comment]
Thanks for your answer, your solution looks cleaner than mine. Yes you're right about my example: `currentPlaybackPosition` is sent even if it doesn't change. 

Too bad there is no way with Reactive Cocoa to not to have `currentPlaybackPosition` sent when its not changing while using `sample`. Do you think it would be a good idea to add such a feature?

**Comment by iv-mexx** [comment]
> Too bad there is no way with Reactive Cocoa to not to have currentPlaybackPosition sent when its not changing while using sample. Do you think it would be a good idea to add such a feature?

As mentioned, the `throttle` operator in the Swift API behaves exactly how you would expect. Your example would look something like this in Swift: 

```Swift
...
let currentPlaybackPosition = MutableProperty<Float>(0)
...
currentPlaybackPosition.producer
    .throttle(1, onScheduler: QueueScheduler())
    .startWithNext { playbackPosition in
        print("Current Playback Position (throttled): \(playbackPosition)")
}
```

This discards all `next` events that arrive within 1 second after the previous (passed) `next` event.

I'm not sure if there are plan to keep expanding the ObjC API though....

**Comment by JeanLebrument** [comment]
You're right, I was talking about the v2.5

Anyway, I'll upgrade to v3 when my app won't have to be iOS7 compliant. 

Thanks for your help guys.
