### ISSUE TITLE
ReactiveCocoa 4.0-alpha.1 fails to be downloaded with Carthage

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2409]
I don't know if this a ReactiveCocoa or Carthage issue but only for the latest version of Carthage the precompiled version cannot be downloaded.

When executing the following commands

```
mkdir test
cd test
echo 'github "ReactiveCocoa/ReactiveCocoa" "v4.0-alpha.1"' > Cartfile
carthage update
```

I get the following error

```
carthage update
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "76f9a972ed61ff872b731460bc610c8acbfae58c"
*** Downloading ReactiveCocoa at "v4.0-alpha.1"
Failed to write to /Users/guidomb/Documents/projects/wolox/Carthage/Build/iOS/ReactiveCocoa.framework: Error Domain=NSCocoaErrorDomain Code=513 "“ReactiveCocoa.framework” couldn’t be removed because you don’t have permission to access it." UserInfo=0x7fd7b348b600 {NSFilePath=/Users/guidomb/Documents/projects/wolox/Carthage/Build/iOS/ReactiveCocoa.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7fd7b3463a50 "The operation couldn’t be completed. Directory not empty”}
```

If executing `carthage update --no-use-binaries` everything is OK. This happens with `Carthage 0.8.0`.

**Comment by rpowelll** [comment]
From a quick glance at the error, it looks like a problem with UNIX permissions. Does the same error occur when you do a clean build (i.e. deleting the _Carthage_ directory from the root of your project)?

**Comment by calebd** [comment]
It's a Carthage issue. It does not properly parse the tag. Point it at the commit instead for now.

**Comment by guidomb** [comment]
Yes it does occur after deleting the Carthage directory. Also happens is Travis CI. Check this build https://travis-ci.org/Wolox/WLXBluetoothDeviceReactiveExtensions/builds/81877277

**Comment by guidomb** [comment]
@calebd OK I'll do that

**Comment by guidomb** [comment]
@calebd That worked. Also this is not happening anymore with Carthage 0.9.1 so I am closing this issue.

**Comment by mdiep** [comment]
This was fixed in https://github.com/Carthage/Carthage/pull/760, which will be part of the next Carthage release.
