### ISSUE TITLE
The Release scheme should build with optimization turned on

### ISSUE THREAD

**Issue by liscio** [ReactiveCocoa/ReactiveCocoa#2411]
As requested by @neilpa, I'm filing an issue here so it doesn't get dropped on the floor. :)

In a nutshell, the release build of ReactiveCocoa is currently being built with no optimization at all. I would like to see it built instead with whole module optimization enabled on the Swift side, and the standard "Release mode optimization" on the Objective-C side.

Furthermore, the test targets should build using the Debug scheme so that we can take advantage of `@testable` in the unit tests. I _may_ have already done this when I did the `QueueScheduler` stuff, so feel free to ignore this paragraph.

(In a perfect world, Xcode wouldn't require all the dependent targets imported from nested `.xcodeproj` files to use the same configuration, so that we could create a Test configuration that is optimized as well as `@testable`, but _c'est la vie_.)

**Comment by NachoSoto** [comment]
I'm confused, I already did this in #2342

**Comment by liscio** [comment]
@NachoSoto My apologies! @neilpa and I spoke briefly about this the other day and he suggested I file an issue about the missing optimizations. Just double-checked my local copy and they are indeed there.

Carry on, then! ;)

**Comment by neilpa** [comment]
> Tests are still passing :tada: (when manually changed to use optimizations, though I left them turned off)

I mis-interpreted this, thinking he meant for the framework too.

**Comment by NachoSoto** [comment]
Ooooh, I see :)
