### ISSUE TITLE
Signal<AnyObject, NSError> to Signal<AnyObject, NoError>?

### ISSUE THREAD

**Issue by s0mmer** [ReactiveCocoa/ReactiveCocoa#2414]
We have `catch` (or `flatMapError` now in RAC4) for converting a `SignalProducer` that sends `NSError` to `NoError`. How would you do the same with a `Signal`? I see `mapError` but as far as I can tell, it's not possible to use that operator to achieve this? Or am I wrong? 😳

**Comment by nikita-leonov** [comment]
You can get `NoError` signal by use `materialize`. You will not be able to stop signal from completion.

**Comment by NachoSoto** [comment]
Done in #2531

**Comment by s0mmer** [comment]
Sweet, thanks @NachoSoto 🙏
