### ISSUE TITLE
ReactiveCocoa was compiled with optimization error

### ISSUE THREAD

**Issue by andrewschreiber** [ReactiveCocoa/ReactiveCocoa#2415]
At runtime, I observed the following message in my console

ReactiveCocoa was compiled with optimization - stepping may behave oddly; variables may not be available.

Followed by a EXC_BAD_ACCESS crash in the Signal class. XCode 7, Swift 2.0 branch. 

Running 'carthage build' solved the issue. Hope it helps.

**Comment by beforeold** [comment]
@andrewschreiber did you solve it? Hope you can give me some advice.
