### ISSUE TITLE
Subscribing to a completion seems to not work after flattening

### ISSUE THREAD

**Issue by jwilling** [ReactiveCocoa/ReactiveCocoa#242]
Sorry for another basic question which probably is a result of me not understanding the documentation. :wink:

Here's a stripped-down version of what I'm trying to do:

``` objc
[[[RACSignal merge:@[ foo, bar ] ] flattenMap:^id(id value) {
    // do something
    return [self doSomething]; // returns RACSignal
}] subscribeCompleted:^{
    NSLog(@"complete!");
}];
```

In `doSomething` I have something along the following:

```
- (RACSignal *)doSomething {
    RACSubject *subject = [RACSubject subject];
    Turtles *turtles = [Turtles objectsAllTheWayDownUntilYouReachTurtles];
    turtles.completionBlock = ^{
        [subject sendCompleted];
    };    
    return signal;
}
```

According to the documentation, `flattenMap:` seems to be the right tool for the job here, given that I'm flattening multiple streams into one, which is the `RACSignal` returned from `doSomething`. The problem is that the completion never seems to fire, although the completion on my `turtles` is definitely called.

To run a test, I substituted `sendCompleted` with `sendNext:`, and subscribed for next instead of completed on my original chain. It sent next successfully. What is going on?

**Comment by ooopscc** [comment]
If you do need the values from original signal, try to cache the `subscriber` parameter or `subject` object, and `sendCompleted` when the mapped signal complete.

**Comment by jwilling** [comment]
Wow what a blast from the past!
