### ISSUE TITLE
Flatten for Signal<Signal<T, E>, E>

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#2422]
Is there a reason why a function like
```swift
extension SignalType where Value: SignalType, Error == Value.Error {
    public func flatten(strategy: FlattenStrategy) -> Signal<Self.Value.Value, Self.Error>
}
```

would not be possible?

**Comment by joedaniels29** [comment]
I'm looking to define a signal in terms of two other signals. Flatten on signals sounds like an ideal solution, but I am wondering if there's a good way to do this with the current framework. 

suppose I have two signals that send from two buttons by hooking up a `CocoaAction` with an `Action` to an `NSButton`. 
I want to define a PropertyOf to be the current state of the application. This seems pretty basic, but my solutions usually require me to do something like 
```Swift
childAViewController.loginButtonSignal.observeNext{ [weak self] in self.stateProperty.value = $0}
childBViewController.logoutButtonSignal.observeNext{ [weak self] in self.stateProperty.value = $0}
```
I also tried to use a regular `Signal` and `sendNext` within the `observeNext`.
but these don't seem right and indeed seem to lead to deadlock. any guidance?

**Comment by NachoSoto** [comment]
I'm currently working on this!

**Comment by mdiep** [comment]
#2449 was merged, fixing this. :sparkles:
