### ISSUE TITLE
Why is not posible to do flatMap with a different error type in RAC 4.0?

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2424]
I have realized that in RAC 4.0 (at least in 4.0-alpha.1) [flatMap](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift2/ReactiveCocoa/Swift/SignalProducer.swift#L943) only allows to change the value type not the error type. Is there a reason behind this or is a bug?

Lets say I have a `let producerOfInts = SignalProducer<Int, NoError>` and then I have a function `func fetchSomething(value: Int) -> SignalProducer<NSData, NSError>`. Is not possible to do `producerOfInts.flatMap(.Latest, fetchSomething)`. What should I do if I want such behavior?

This was allowed in RAC 3.0's [flatMap](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v3.0.0/ReactiveCocoa/Swift/SignalProducer.swift#L919)

**Comment by neilpa** [comment]
This didn't work in RAC 3, you had to use `catch` to transform the error. That was renamed to `flatMapError` in RAC 4 to avoid ambiguity with the Swift 2 keyword.

**Comment by guidomb** [comment]
So in my previous example the only way to achieve what I want is

```swift
producerOfInt
            .flatMapError { _ in SignalProducer(error: NSError(domain: "", code: 0, userInfo: nil)) }
            .flatMap(.Latest, transform: fetchSomething)
            .startWithNext { data in print(data) }
```

**Comment by ikesyo** [comment]
`.flatMapError { _ in SignalProducer(error: NSError(domain: "", code: 0, userInfo: nil)) }` could be just `.flatMapError { _ in .empty }`

**Comment by guidomb** [comment]
OK I see. Thanks @ikesyo. I think I can close this issue.
