### ISSUE TITLE
Binding to a dynamic property doesn't compile

### ISSUE THREAD

**Issue by czechboy0** [ReactiveCocoa/ReactiveCocoa#2425]
Hi, I'm trying to bind a signal producer sending over `String`s to a `textField`'s `stringValue` property in `NSTableCellView`. However, the compiler refuses to compile this
```
DynamicProperty(object: view.textField!, keyPath: "stringValue") <~ syncerViewModel.status
```
where `syncerViewModel.status` is of type `SignalProducer<String, NoError>`. However, what **does** compile is when I add an extra pointless map at the end, like this
```
DynamicProperty(object: view.textField!, keyPath: "stringValue") <~ syncerViewModel.status.map { $0 }
```

Can someone please explain to me what I'm doing wrong here? I assumed that just mapping to the same type should not change the underlying producer type.

Anyway, what is also frustrating that this doesn't compile:
```
let source: SignalProducer<String, NoError> = syncerViewModel.status
let destination = DynamicProperty(object: view.textField!, keyPath: "stringValue")
destination <~ source
```
error: `Binary operator '<~' cannot be applied to operands of type 'DynamicProperty' and 'SignalProducer<String, NoError>'`

I'm on OS X 10.10.5, Xcode 7 (release version). What am I doing wrong?

**Comment by ikesyo** [comment]
`DynamicProperty` needs `SignalProducer<AnyObject?, NoError>` and `String` itself is not `AnyObject` but can be bridged to that through `NSString`. `map { $0 }` is really bridging from `String` to `NSString?` by the type inferencer. That is the trick.

**Comment by czechboy0** [comment]
Ah, I see, that makes sense, thanks so much! I'll just bridge it explicitly I guess to keep it readable. Thanks again!
