### ISSUE TITLE
Explore a bridging protocol for SignalType and SignalProducerType

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2426]
Lets continue the discussion from #2314 here. Is there a sensible way we can bridge or unify `SignalType` and `SignalProducerType`?

**Comment by nikita-leonov** [comment]
It is interesting. At the beginning there was `RACSignal` afterward there was split to `Signal` and `SignalProducer` to be explicit about hot & cold signals. Now we are trying to join them back. I can  imagine bridging, but unification sound like a step backward. How does unification supports initial idea of splitting?

**Comment by NachoSoto** [comment]
It's not about unifying them again, it's about making them conform to a common protocol as a way to implement the common operators in terms of this protocol. The 2 types will continue to be different! :)

**Comment by nikita-leonov** [comment]
I see. Something in the base to avoid duplication as we see it now and additional specific on a top of it. Sounds reasonable. Thanks for clarification.

**Comment by NachoSoto** [comment]
@neilpa what do you think about taking this out of the initial 4.0 release, but keeping it in our radar for a future release?

**Comment by neilpa** [comment]
This is probably another breaking change and I don't want to rush 4.0. I'd rather get a better alpha cadence going and spend time experimenting some more. I know people wanted it yesterday (or earlier) but we should create an expactions/roadmap doc that we can point people to.

**Comment by Cyclic** [comment]
+1 for roadmap...We are considering RAC 3 vs. 4, and wonder if it makes sense to start working with 4, or just use 3 and port from it later. thanks!

**Comment by NachoSoto** [comment]
What does everyone have in mind for this? I don't think this is possible with the current limitations of Swift. Specifically, without higher-kinded types. What I mean with that is that something like this:
```swift
protocol SignalType {
  typealias Value
  typealias Error: ErrorType

  func operator() -> Self<Value, Error>
}
```
Would not be possible at the moment.

**Comment by bencochran** [comment]
In the original issue, @neilpa mentioned a [converter protocol](https://github.com/antitypical/Result/pull/86#issuecomment-142400985), though I can’t quite see how that helps in this particular case. I agree that I’m having trouble figuring out what a protocol could return without higher-kinded types. (Or `Signal` and `SignalProducer` could be rolled back in to one 🙃)

**Comment by neilpa** [comment]
I hadn't thought it through and didn't want to derail the original issue so I opened this as a placeholder.
