### ISSUE TITLE
[Question] subscribing to any signal result

### ISSUE THREAD

**Issue by ldantona** [ReactiveCocoa/ReactiveCocoa#2430]
Hi all,

when I need to perform some code after the execution of a signal, no matter of its result, am I required to subscribe to both the next and errors events?
```objective-c
        [rac_signal subscribeNext:^(id x) {
            // code
        } error:^(NSError *error) {
            // same code
        }];
```
Is there any convenience method which allows to have one single block?

Thanks,
DAN

**Comment by mdiep** [comment]
If you want to execute the block after the signal terminates—whether it completes or errors—you can use `finally:`. But that won't create a subscription, so you'll need to subscribe to the signal.

**Comment by ldantona** [comment]
Great, thank you!

Would it be something like this?
```objective-c
[rac_signal finally:^(id x) {
    // code
}];
[rac_signal subscribeNext:^(id x) {
}];
```
Does it work in case of a 'collect' of 'concat' signals too?
```objective-c
RACSignal *s = [[RACSignal concat:@[s1, s2]] collect];
[s finally:^{
    // some code
}];
[s subscribeNext:^(id x) {
}];
```

**Comment by mdiep** [comment]
You'd write it all in one go:

```objc
[[[[RACSignal
    concat:@[s1, s2]]
    collect]
    finally:^{
        // some code
    }]
    subscribeNext:^(id x) {
    }];
```

It will execute when the receiver ends, no matter what operators were used to construct it.

**Comment by ldantona** [comment]
There's something not working as expected here:
```objective-c
    RACSignal *s1 = [[self rac_s1] finally:^{
        NSLog(@"s1 done");
    }];
    RACSignal *s2 = [[self rac_s2] finally:^{
        NSLog(@"s2 done");
    }];

    [[[[RACSignal concat:@[s1, s2]] collect] finally:^{
        NSLog(@"collect done");
    }] subscribeNext:^(id x) {
    }];
```
When rac_s1 returns a [RACSignal error:error] the "finally" block of s2 is not executed.
Am I missing anything?

**Comment by ikesyo** [comment]
In that case, `s2` is not subscribed since the previous `s1` does not complete.

**Comment by ldantona** [comment]
How would you execute N consecutive signals and perform some code at the end of the chain, no matter the result of each single one?

**Comment by ldantona** [comment]
I've solved this issue placing every consecutive signal in the finally block of the previous one:
```objective-c
[[self rac_s1] finally:^{
    NSLog(@"s1 done");
    [[self rac_s2] finally:^{
        NSLog(@"s2 done");
        [[self rac_s3] finally:^{
            NSLog(@"s3 done");
            NSLog(@"All done!");
        }];
    }];
}];
```
Thanks everyone :)
