### ISSUE TITLE
get, set, willSet, didSet for properties

### ISSUE THREAD

**Issue by paulyoung** [ReactiveCocoa/ReactiveCocoa#2431]
Given some old code that I'm trying to migrate, I'm at a loss on how to achieve the same thing without drastically changing the interface.

```swift
// Old
let _foos = [Foo]()
let foos =  [Foo]() {
    get {
        return _foos
    }
    set {
        _foos.sort { ... }
    }
}
```

```swift
// New
let foos = MutableProperty<[Foo]>([])
```

Could anyone offer any advice on the best way to do this?

**Comment by NachoSoto** [comment]
I'm :+1: for adding `willSet` as a `T -> T` pure function that can perform transformations before setting a new value in `MutableProperty`.

However, I don't think I understand your example. `get` allows you to declaratively implement a getter, but there is no way to know when the value would implicitly change. If you want to map a property to an existing one you can always use `<~` operator.

**Comment by paulyoung** [comment]
Yeah, I mostly just mentioned `get` since it appears in the original code.
