### ISSUE TITLE
Is there something wrong with my code, the results prints twice?

### ISSUE THREAD

**Issue by whisper-bye** [ReactiveCocoa/ReactiveCocoa#2434]
env: Xcode Version 7.0.1 (7A1001), pod 'ReactiveCocoa', '4.0.2-alpha-1'

this is my test code:
let searchStrings = textField.rac_textSignal().toSignalProducer()
    .map { text in text as! String }

let searchResults = searchStrings
    .observeOn(UIScheduler())

searchResults.start({ results in
    print("Search results: \(results)")
})

this is my target output:
Search results: NEXT 
Search results: NEXT I
Search results: NEXT I 
Search results: NEXT I love
Search results: NEXT I love 
Search results: NEXT I love you
Search results: NEXT I love you 
Search results: NEXT I love you so
Search results: NEXT I love you so 
Search results: NEXT I love you so much
Search results: NEXT I love you so much 

my question is:
1> the results prints twice?

2> and what is the "NEXT" means?

what's wrong with my code? thx

**Comment by jsslai** [comment]
I don't know why it sends duplicates, but you are using start method which sends every Event (Next, Completed, etc.). If you only want to observe next events, use startWithNext.

**Comment by whisper-bye** [comment]
@jsslai 
I guess that's the keyboard auto complete problem

**Comment by CosynPa** [comment]
The results are not actually printed twice. Replace your start method call with this:

```
searchResults.startWithNext { text in
    print("Search results: \"\(text)\" ")
}
```

You'll see

Search results: "" 
Search results: "" 
Search results: "I" 
Search results: "I " 
Search results: "I love" 
Search results: "I love " 
Search results: "I love you" 
Search results: "I love you " 

You see twice because there are some texts with an extra space.

**Comment by whisper-bye** [comment]
thanks all, I fixed it
