### ISSUE TITLE
Cannot invoke 'flatMap' with ...

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2436]
error: cannot invoke 'flatMap' with an argument list of type '(FlattenStrategy, (String) -> SignalProducer<AnyObject?, NSError>)'
        filteredText.flatMap(.Latest){ (text: String) -> SignalProducer<AnyObject?, NSError> in
                     ^
note: expected an argument list of type '(FlattenStrategy, transform: T -> SignalProducer<U, E>)'
        filteredText.flatMap(.Latest){ (text: String) -> SignalProducer<AnyObject?, NSError> in

Where the code looks like:

```
class PlacesViewModel {
    let searchText = MutableProperty<String>("")
}

let viewModel = PlacesViewModel()
let filteredText: SignalProducer<String, NoError> = viewModel.searchText.producer
     .skipRepeats().filter { (query: String) -> Bool in
         query.characters.count > 3
      }
      filteredText.flatMap(.Latest){ (text: String) -> SignalProducer<AnyObject?, NSError> in
          return placesSearchSignal(text).toSignalProducer()
      }

...

func placesSearchSignal(query: String, placeType: PlaceType = .all) -> RACSignal {...}
```
Trying to migrate my current working code to RAC4 i'm hitting this issue where the compiler is complaining about flatMap arguments not matching the signature.

I'm not entirely sure why.

Any help is appreciated.

**Comment by NachoSoto** [comment]
The problem is that the returned producer by your `flatMap` function is trying to change the error from `NoError` to `NSError`, but if you look at the definition of `flatMap`:
```swift
public func flatMap<U>(strategy: FlattenStrategy, transform: Value -> SignalProducer<U, Error>) -> SignalProducer<U, Error> {
	return map(transform).flatten(strategy)
}
```

You can see that errors must match.

To fix this, you can change the error type of the original signal, since it can never emit errors, to make it match:
```swift
filteredText
    .promoteErrors(NSError.self)
    .flatMap(.Latest) { ... }
```

**Comment by edwardIshaq** [comment]
I found out about the error mapping issue but now when I try to compile this code I'm getting an even stranger message: 

Undefined symbols for architecture x86_64:
  "ReactiveCocoa.SignalProducer.flatMap <A, B><C where B: Swift.ErrorType> (ReactiveCocoa.SignalProducer<A, B>)(ReactiveCocoa.FlattenStrategy, transform : (A) -> ReactiveCocoa.SignalProducer<C, B>) -> ReactiveCocoa.SignalProducer<C, B>", referenced from:
      Pop.EventEditPlaceVC.bindViewModel (Pop.EventEditPlaceVC)() -> () in EventEditPlaceVC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by edwardIshaq** [comment]
Trying to decipher the error message:

Undefined symbols for architecture x86_64:
  ReactiveCocoa.SignalProducer.flatMap <A, B><C where B: Swift.ErrorType> (ReactiveCocoa.SignalProducer<A, B>)(ReactiveCocoa.FlattenStrategy, transform : (A) -> ReactiveCocoa.SignalProducer<C, B>) -> ReactiveCocoa.SignalProducer<C, B>
 
 referenced from:
      Pop.EventEditPlaceVC.bindViewModel (Pop.EventEditPlaceVC)() -> () 
	  in EventEditPlaceVC.o

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
=======================

filteredText : SignalProducer<String, NoError>
filteredText.promoteErrors(NSError.self) : SignalProducer<String, NSError>

Breaking down the error message:
ReactiveCocoa.SignalProducer<A, B> =  SignalProducer<String, NSError>
ReactiveCocoa.SignalProducer<C, B> =  SignalProducer<AnyObject?, NSError>
A : String
B : NSError
C : AnyObject?

Seems like all the type match up but not according to the compiler/linker ...

**Comment by edwardIshaq** [comment]
this code actually worked. 
I tried it on a different machine and everything went really good.
I concluded that there was something off with the carthage build, cause when i checked out the project and bootstrapped carthage again it all works fine.

Thanks for your help @NachoSoto
