### ISSUE TITLE
Observe SignalProducer's next and completed events?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#2438]
How can I observe `SignalProducer`'s `next` and `completed` events on RAC4? 

In RAC3 there was `start()` with multiple callbacks for different occasions. Now RAC4 has separate `startWithNext()` and `startWithCompleted()`. Is there a way to combine them both?

**Comment by harrywincup** [comment]
@eimantas I think you can just use `producer.on(next: {}, completed: {}).start()` to tap into those events before starting as normal

**Comment by iv-mexx** [comment]
> In RAC3 there was start() with multiple callbacks for different occasions. Now RAC4 has separate startWithNext() and startWithCompleted(). Is there a way to combine them both?

If you want to handle several cases, you can use

```swift
producer.start { event in
    switch(event) {
    case let .Next(value):
        print("Next: \(value)")
    case let .Error(error):
        print("Error: \(error)")
    case .Completed:
        print("Completed")
    case .Interrupted:
        print("Interrupted")
    }
}
```

**Comment by ikesyo** [comment]
We are now having [`Observer`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v4.0.0-alpha.3/ReactiveCocoa/Swift/Observer.swift) API since alpha 2, so you can write as follows:

```swift
producer.start(Observer(next: { _ in }, completed: {}))
```
