### ISSUE TITLE
trouble extending SignalProducer

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2440]
I'm trying to add an extension to SignalProducer to suppress errors so i can bind it to MutableProperty
but i'm getting 
"Use of undeclared type 'Value'" on the function signature 
I"m not sure why the compiler won't recognize the Value type.
p.s. Same code compiles fine if i append it SignalProducer.swift file in the RAC project.

```
extension SignalProducer {
    
    func suppressError() -> SignalProducer<Value, NoError> {
        return self.flatMapError{ (error: Error) -> SignalProducer<Value, NoError> in
            return SignalProducer<Value, NoError>.empty
        }
    }
}
```

**Comment by NachoSoto** [comment]
> "Use of undeclared type 'Value'" on the function signature 

Which version of `RAC 4` are you using? It's possible that, if you're using `alpha.1`, `SignalProducerType.Value` is `SignalProducerType.T`, because that was changed in a later commit.

**Comment by edwardIshaq** [comment]
I'm on "swift2" branch

**Comment by NachoSoto** [comment]
I'm not entirely sure why you're getting that error.
Can you try to extend `SignalProducerType` instead?
```swift
extension SignalProducerType {
    func suppressError() -> SignalProducer<Self.Value, NoError> {
        return self.flatMapError{ (error: Error) -> SignalProducer<Self.Value, NoError> in
            // Note, I strongly suggest that you don't silently ignore errors.
            // Instead, I'd recommend adding something like `fatalError("Unexpected error: \(error)")`
            return .empty
        }
    }
}
```

**Comment by edwardIshaq** [comment]
working now, the signalProducer version of it.
I guess it had something to do with a bad state of Xcode/Carthage ...
Not entirely sure whats the cause. 
I've been having strange issues with the latest Xcode, i guess u can't innovate without bugs really :)

Thanks @NachoSoto
