### ISSUE TITLE
Where is throttleDiscardingLatest?

### ISSUE THREAD

**Issue by CosynPa** [ReactiveCocoa/ReactiveCocoa#2443]
Will it be added in Swift?

**Comment by NachoSoto** [comment]
What's `throttleDiscardingLatest`?

**Comment by CosynPa** [comment]
@NachoSoto  A signal operator that exists in some old branches, like throttle, but only early event is kept, if a new event comes in a short time, the new event is discarded.

**Comment by iv-mexx** [comment]
If you mean the `throttle` operator of RAC2 (/ ObjC API) which really is the [`debounce`](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2075) operator - its currently being discussed to bring it back in #2075

**Comment by CosynPa** [comment]
Sorry, I didn't check the new throttle operator carefully, so I thought I was the same as RAC 2. But should we have an operator that simply discards latest event instead of delaying it?

For example, I'm listening a message signal, and show a notification when a new message comes. But I don't want to bother the user when a lot of messages are received in the same time. So I'd like to throttle the message signal for 10 seconds. But with the new throttle operator, It will be a little bit strange, because when multiple messages are received within 10 seconds, two notifications will be shown, one is 10 seconds after the other. In this special case, I just want take the first new message event and discard all the later events that come in a short time.

**Comment by RuiAAPeres** [comment]
@CosynPa Rex provides the [debounce](https://github.com/neilpa/Rex/blob/7e0ccfb7297ec9e1222410990e07042aaf441b6a/Source/Signal.swift#L81#L94) operator.
