### ISSUE TITLE
[Question] Subscribing to an executing signal without invoking a new one

### ISSUE THREAD

**Issue by ldantona** [ReactiveCocoa/ReactiveCocoa#2444]
Hi all,

If I have understood correctly subscribing to an executing signal does not invoke the signal again but wait for the next event to be sent (whether it is next, error or complete).

In my scenario I have an app which at startup subscribes to a signal which downloads some data:
```objective-c
[[ServiceManager rac_getData] subscribeNext:^(id x) {
}];
```
Afterwards when the user opens the screen responsible for showing such data, I trigger the same signal with a command:
```objective-c
self.rac_loadCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
    return [ServiceManager rac_getData];
}];
```
I want that if the previous API call is still running, no new call is executed but wait for the previous one to finish.
[ServiceManager rac_getData] is a signal which performs an HTTP request and returns some data or a RACSignal error:
```objective-c
- (RACSignal*)rac_getData {
    if(self.rac_getDataSignal) {
        return self.rac_getDataSignal;
    }
    
    self.rac_getDataSignal = [RACSignal defer:^RACSignal *{
        [[self rac_getRequest parameters:...] map:^id(id value) {
            return value;
        }] catch:^RACSignal *(NSError *error) {
            return [RACSignal error:error];
        }];
    }];
    
    return self.rac_getDataSignal;
}
```
I thought that saving a local instance of rac_getDataSignal in the ServiceManager would be the solution, but I see that every time rac_loadCommand is executed, a new API call starts.
Does my logic make sense?

Many thanks,
DAN

**Comment by CosynPa** [comment]
No, every subscription will trigger the side effect in the creation method of signal (sending an HTTP request in your case). You can subscribe the signal returned by the `replay` operator to avoid multiple side effect of the original signal.

**Comment by ldantona** [comment]
Hi CosynPa,
do you mean to modify the above rac_loadCommand like this?
```objective-c
self.rac_loadCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
    return [[ServiceManager rac_getData] replay];
}];
```
I still see two API calls, nothing seems to be changed :(

**Comment by CosynPa** [comment]
Save this replay signal somewhere

    RACSignal *saved = [[ServiceManager rac_getData] replay];

And use the same saved signal when at startup and when you need it in a command.

    [saved  subscribeNext:^(id x) {
    }];
    self.rac_loadCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
        return saved;
    }];

**Comment by ldantona** [comment]
OMG it works like magic!!
Thank you so much!
Next step: understanding the reply definition meaning :)

> Multicasts the signal to a RACReplaySubject of unlimited capacity, and immediately connects to the resulting RACMulticastConnection.
> Returns the connected, multicasted signal.

Should be: save the current signal somewhere and return that instead of a new one at any new subscription :D

**Comment by ldantona** [comment]
One last thing.
This way after the signal has completed (no matter how many time it has been subscribed) for any following subscription I get the same old result and no new API call is executed.
Would it be correct to set the saved signal at nil in the finally block like this?
```objective-c
- (RACSignal*)rac_getData {
    if(self.rac_getDataSignal) {
        return self.rac_getDataSignal;
    }

    self.rac_getDataSignal = [[RACSignal defer:^RACSignal *{
        [[self rac_getRequest parameters:...] map:^id(id value) {
            return value;
        }] catch:^RACSignal *(NSError *error) {
            return [RACSignal error:error];
        }] ;
    }] finally:^{
        self.rac_getStoresSignal = nil;
    }];

    return self.rac_getDataSignal;
}
```

**Comment by CosynPa** [comment]
Yes, you should set it to nil, I think do it in finally is OK.

**Comment by ldantona** [comment]
For completeness' sake I've found out there's also the replayLazily operator which works much better for situations like this where web service calls are involved (they are executed only at subscription time, whereas with replay the signal is invoked even without a subscription).
