### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by eridbardhaj** [ReactiveCocoa/ReactiveCocoa#2445]
Why you are giving up on official support for CocoaPods, and instead going for Carthage?

**Comment by powerje** [comment]
note: I'm not a ReactiveCocoa team member, but I believe this information is correct

ReactiveCocoa has never officially supported CocoaPods, podspecs have been contributed by the community. The community can continue to maintain podspecs for RAC. In this way ReactiveCocoa will be available on CocoaPods for the foreseeable future.

Carthage was built with the help of many of the developers who work on ReactiveCocoa to be a simpler dependency management tool for Cocoa. It makes sense for the team to use the tool they themselves built which is more in line with their ideas about how a dependency management tool should behave.

**Comment by neilpa** [comment]
What @powerje said.
