### ISSUE TITLE
Can no longer build for tvOS?

### ISSUE THREAD

**Issue by bruceflowers** [ReactiveCocoa/ReactiveCocoa#2446]
Xcode7 beta2 
Carthage 0.9.2
ReactiveCocoa: swift2 branch *or* tvos branch

I'm wondering if anyone can steer me in the right direction here...

With the latest swift2 branch, when building for tvOS, I'm getting a build error for Result:

carthage update --platform tvOS
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "0.6.0-beta.3"
*** Checking out ReactiveCocoa at "ddd26d01b2f8be04e525855523ec61ab3a59ccfb"
*** xcodebuild output can be found in /var/folders/66/7ttbxjv94md42tvryd7ww0fc0000gn/T/carthage-xcodebuild.PKrJGZ.log
*** Skipped building Result due to the error:
Dependency "Result" has no shared framework schemes for any of the platforms: tvOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/antitypical/Result/issues/new

=================================================

For the tvos branch (I recognize it's older, but I tried it anyway just to see):

carthage update --platform tvOS
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out ReactiveCocoa at "b9779be105da600221f010c16fcadaebc3580bd7"
*** Checking out Result at "104c158e01d24fa614873d15f8b41784186fa85a"
A shell task failed with exit code 128:
fatal: reference is not a tree: 62c26e25b9135f28ca0d3238eb961280244c3100

**Comment by ikesyo** [comment]
See #2361.
