### ISSUE TITLE
Cannot invoke toRACCommand

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2447]
I've got the following code but I keep getting a compiler error:
```
    var action: Action<AnyObject?, String, NoError> {

        let saveEnabled = PropertyOf(initialValue: false, producer: viewModel.formValidSignal())
        return Action(enabledIf: saveEnabled) { (button: AnyObject?) -> SignalProducer<String, NoError> in
            return SignalProducer{ sink, disposable in
                sendCompleted(sink)
            }
        }

    }

    let command = toRACCommand(action: action)
```
//cannot invoke 'toRACCommand' with an argument list of type '(action: Action<AnyObject?, String, NoError>)'
I 'm assuming that it has something to do with the Action, but my action is a simple button click that returns a String with NoError.

PS: I'm using Reactive-Cocoa [swift2] branch

**Comment by ikesyo** [comment]
Because the `Output` parameter should be `AnyObject` compatible, you should use `NSString`, not `String`. `String` is a struct and not a object (class type).

**Comment by jakecraige** [comment]
@ikesyo Are there plans to convert the RACCommand API over to Swift so that we can use Swift types? This is a large inconvenience when working with RAC in swift.

**Comment by mdiep** [comment]
`Action`/`CocoaAction` are the Swift equivalents of `RACCommand`.
