### ISSUE TITLE
RAC4.0 Working with optionals.

### ISSUE THREAD

**Issue by DAloG** [ReactiveCocoa/ReactiveCocoa#2451]
I just started migration from RAC2 to RAC4 for swift 2.
I use MVVM pattern, and as I understand, my ViewModels should look like this
```
protocol ExampleViewModel {
    var title: PropertyOf<String> {get}
}
```
Then inside ViewController I define view model property itself.
````
class ExampleViewController: UIViewController {
    let viewModel = MutableProperty<ExampleViewModel?>(nil)
}
```
So this property is `nil` by default and anytime can be changed.

Next I want to bind `title` property to some `UILabel` instance.
```
        self.viewModel.producer.map({ vm -> SignalProducer<String, NoError> in
            guard let vm = vm else {
                return SignalProducer(value: "")
            }
            
            return vm.title.producer
        }).flatten(.Latest).on(next: {self.label.text = $0}).start()
```

At this point i think i made some errors. Because instead of solving this problem in terms of properties i failed down to some details.

What do you think? Is it some better approach for this kind of tasks?

**Comment by a-voronov** [comment]
I'm doing it this way using RAC3 (think it's not that different yet)
```swift
label.rac_text <~ self.viewModel.producer 
	|> ignoreNil
	|> map { vm in vm.title.producer }
	|> flatten(.Latest)
```
or if title is simple String, then 
```swift
label.rac_text <~ self.viewModel.producer 
	|> ignoreNil
	|> map { vm in vm.title }
```
and rac_text idea i've pretty much taken from [this post](http://blog.scottlogic.com/2015/05/15/mvvm-reactive-cocoa-3.html)

**Comment by DAloG** [comment]
Thanks for reply. Ignore nil will not set defaults when ViewModel become nil. But thanks for direction.
Also, is it essential to keep strong reference to MutableProperty?

**Comment by andersio** [comment]
The `on` operator is for injecting side effect. While in your use case it produces the same effect, you may streamline them into `startWithNext(next:)`. On the other hand, IMO it would be more efficient to observe the view model producer, and do all the bindings in bulk.

`MutableProperty` has to be retained if you want to update the values over time, since a terminating event is sent to the sink if it deallocates.

**Comment by andersio** [comment]
By the way, you may shorten your map transform as `.map { $0?.name.producer ?? .init(value: "someValue") }`. :)

**Comment by DAloG** [comment]
Thanks for coalescing operator hint. Missed that one. If I will decide to keep property with text explicitly, how inject side effects like UI updating into them? I mean `ViewController` keep PropertyOf<ViewModel>` and `PropertyOf<String>` for title. And then at `viewDidLoad` I will just bind one properties to another.

**Comment by andersio** [comment]
You may keep a `MutableProperty` in the VC, and start it with an observer that say updates your UILabel. Then you may bind your read-only property from the view model to it. There are two popular ways to do it AFAIK:

1. VC owns the view model. Parent VC injects the VM into the VC when pushed. UI bindings happen in the VC's `viewDidLoad`.
2. VC exposes binding points (`MutableProperty`s), and parent VC does the binding. In other words, VC does not acknowledge the existence of VM.

**Comment by DAloG** [comment]
Great. thanks for help.
