### ISSUE TITLE
ReactiveCocoa not building through Carthage

### ISSUE THREAD

**Issue by marlowcharite** [ReactiveCocoa/ReactiveCocoa#2456]
I have Xcode 7 latest release and I can't seem to build ReactiveCocoa

<img width="850" alt="screen shot 2015-10-09 at 5 15 24 pm" src="https://cloud.githubusercontent.com/assets/5712464/10405787/601f8038-6ea9-11e5-9e1e-19cef9bec360.png">

is Xcode 7 beta required and I just missed that in the docs?

**Comment by mdiep** [comment]
Try explicitly specifying the platforms you'd like to build for. `carthage bootstrap --platform mac,ios` I think you're hitting this because Result added tvOS support, but not all the stable versions of the tooling supports it yet.

If that doesn't work, please post your `carthage version` as well.

**Comment by natalia-osa** [comment]
I've also had this issue on Carthage version 0.7.5. After updating to the newest one (0.11.0) everything is working fine.
