### ISSUE TITLE
Xcode7 upgrade, appear a mistake. I use a ReactiveCocoa v4.0 alpha

### ISSUE THREAD

**Issue by nicknull** [ReactiveCocoa/ReactiveCocoa#2458]
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/ReactiveCocoa.framework/ReactiveCocoa) for architecture arm64

it seems that framework need version at lest be 8.0

**Comment by NachoSoto** [comment]
That is correct.
