### ISSUE TITLE
Swift2: prints within flatMaps are giving me compile errors

### ISSUE THREAD

**Issue by carlosefonseca** [ReactiveCocoa/ReactiveCocoa#2459]
Hi!

I'm trying to figure out how to sequence Signal Producers together and I was going crazy because I couldn't get it to compile. Suddenly I removed the `print()` statements I had in between and it compiled and ran… any idea what's happening here?

```
api.registerUser("name", email: "email", password: "pw")
    .flatMap(.Latest) { user in
        print(user)
        return api.login("email", password: "pw")
    }.flatMap(.Latest) { user in
        print(user)
        return api.createThing("thing")
    }.startWithNext { next in print(next) }
```

`api.registerUser`, `api.login` and `api.createThing` are returning `SignalProducer<ResponseUser, NetworkError>` since I'm just trying to get the structure to work…

The errors I get are
* `Cannot invoke 'flatMap' with an argument list of type '(FlattenStrategy, (_) -> _)'` on the second `flatMap` caused by the first `print`;
* `Cannot convert return expression of type 'SignalProducer<ResponseUser, NetworkError>' to return type 'SignalProducer<Any, NetworkError>' (aka 'SignalProducer<protocol<>, NetworkError>')` on `api.createThing` caused by the second `print`.

Removing the prints makes it work.
I've been using prints everywhere since Xcode crashes when I try to print any vars within ReactiveCocoa. Had no problems until now…

(I'm not sure if I'm doing this correctly, I've only been playing with ReactiveCocoa for a few weeks)

**Comment by mdiep** [comment]
You probably need to explicitly type the inputs and outputs of the blocks that you pass to `flatMap`. It sounds like Swift's type inferencing is having a hard time.

**Comment by carlosefonseca** [comment]
Hmm… just adding `(user:ResponseUser)` made it work.

```
api.registerUser("name", email: "email", password: "pw")
    .flatMap(.Latest) { user in
        print(user)
        return api.login("email", password: "pw")
    }.flatMap(.Latest) { (user:ResponseUser) in
        print(user)
        return api.createThing("thing")
    }.startWithNext { (next:ResponseUser) in print(next) }
```

Yesterday I had tried with `user -> SignalProducer<ResponseUser, NetworkError>` but had the same errors.

Thanks
