### ISSUE TITLE
[RAC4.0] Using PropertyOf<T>

### ISSUE THREAD

**Issue by DAloG** [ReactiveCocoa/ReactiveCocoa#2461]
Hi. Currently I am trying to use PropertyOf<T> as public interface in my ViewModels.
So my `viewModel` look like collection of properties.

Now i have a question about mutation of this properties. As soon as `PropertyOf<T>` is just a lens over some other property, i need to keep link for some `MutableProperty` as well.

What is correct way to extend `PropertyOf<T>` to mutable variant?

**Comment by andersio** [comment]
You may consider using the powerful `lazy` modifier. :p

````
public var _shouldMove = MutableProperty<Bool>(false)
public lazy var shouldMove: PropertyOf<Bool> = .init(self._shouldMove)
````

... and the read-only view is initialised at the first time it is accessed. Note that to use lazy property this way, you must explicitly state the type and also use `self` to reference the stored properties of the instance.

**Comment by iv-mexx** [comment]
Hm, I am currently doing it like that

```
private let _shouldMove = MutableProperty<Bool>(false)
public let var shouldMove: PropertyOf<Bool>
...
init() {
    shouldMove = PropertyOf(_shouldMove)
}
```

but I'm not happy with the amount of Boilerplate code in `init`. Maybe I'll switch over to use `lazy` vars the way you suggest ( @andersio )...

**Comment by andersio** [comment]
By the way, you may want to use `private(set) public` on your `PropertyOf`. Missed that typo. :)

**Comment by iv-mexx** [comment]
Oh yeah, did not know about this, that was actually whats been bothering me before about the `lazy var` method. Thanks! :+1:

**Comment by DAloG** [comment]
Thanks for help. BTW, is this code correct?
```
let a = MutableProperty("")
let b = MutableProperty("")
let c = MutableProperty("")

a <~ b
a <~ c
```
Looks like nobody will check if you introduce some races to this.

**Comment by andersio** [comment]
It is semantically correct. The getter/setter of `MutableProperty` is protected by a recursive lock, so things would still be observed in order.

**Comment by DAloG** [comment]
Sure. You will receive data in some order. But is this intentional? Does binding from two sources have any meaning  at all? I am just curious about complexity which this approach can bring.

**Comment by andersio** [comment]
IMO this should be a by-product of the recursive lock, which is there to keep the signal's stream of value consistent with the property's value across multiple threads in the first place. I think this would be used only in extensions to RAC, like `EditableProperty`. For UI bindings, I can't see why you would not use the two deterministic `combineLatestWith` and `zipWith` operators.

**Comment by sergdort** [comment]
Hey, guys I also have a question related to the MutableProperty-s (ConstantProperty-s). Should I dispose my bindings on reuse of tableViewCell for example? Because <~ operator returns Disposable

**Comment by andersio** [comment]
That's one way. Another way is to use takeUntil with a bridged rac_prepareForReuseSignal, or create your own reuse signal.

However, if you `flatMap` a view model into child producers with the Latest strategy, you do not need to do any of these, since the earlier binding would be ended automatically.

e.g.
```
viewModel.flatMap(.Latest) { $0.name.producer }
// This producer, if started, will terminate the old name producer and observe the new one every time you push a new view model.
```

**Comment by sergdort** [comment]
So I was talking about custom mutable properties on UIKit elements like Colin did in his post http://blog.scottlogic.com/2015/05/15/mvvm-reactive-cocoa-3.html
``` Swift
label.rac_text <~ viewModel.name // here I can store the ref to the Disposable

// Can I do like this ?

label.rac_text <~ viewModel.name.producer.takeUntil(triger)

```

**Comment by andersio** [comment]
In this case, if the label is in a reusable cell, you would need to do this to stop previous bindings and prepare the cell for reuse. Otherwise, the binding to `rac_text` would be dismissed on deallocation of the label, since his code uses MutableProperty underneath.

**Comment by sergdort** [comment]
@andersio Thanks a lot :)
