### ISSUE TITLE
ReactiveCocoa fails to build when Mantle is also depended on

### ISSUE THREAD

**Issue by JRHeaton** [ReactiveCocoa/ReactiveCocoa#2464]
It appears that for some reason, when using CocoaPods, including [Mantle](https://github.com/Mantle/Mantle) as a dependency alongside the latest RAC v4 alpha causes a build failure in the RAC framework target. I'm looking to see if this is an issue with RAC, with Mantle, with pods, or with me, so any insight or help you can provide is appreciated :)

`Podfile`:
```
use_frameworks!
pod 'ReactiveCocoa', '4.0.2-alpha-1'
pod 'Mantle'
```

ReactiveCocoa will build perfectly fine if Mantle is not in the podfile (or podspec in my case, as I'm trying to build a framework that depends on both RAC and Mantle).

Here is a screenshot displaying the error:
![](https://cldup.com/LgM9eLx-oQ.png)

```
/tmp/asdf/Pods/ReactiveCocoa/ReactiveCocoa/Objective-C/NSObject+RACSelectorSignal.m:107:19: error: implicit declaration of function 'rac_getImmediateInstanceMethod' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                Method method = rac_getImmediateInstanceMethod(class, selector);
                                ^
/tmp/asdf/Pods/ReactiveCocoa/ReactiveCocoa/Objective-C/NSObject+RACSelectorSignal.m:107:10: warning: incompatible integer to pointer conversion initializing 'Method' (aka 'struct objc_method *') with an expression of type 'int' [-Wint-conversion]
                Method method = rac_getImmediateInstanceMethod(class, selector);
                       ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

**Comment by NachoSoto** [comment]
Looks like that's a problem with CocoaPods then.

**Comment by JRHeaton** [comment]
Well it's seemingly only happening with this specific dependency pair, which is why I posted it here. I looked to see which file that function was declared in... turned out to be `EXTRuntimeScope.h`, so I did an "open quickly" and saw that both RAC and Mantle include "extobjc". Could this be the issue? 

![](https://cldup.com/60ckSWUY-r.png)

So... I unlocked the files for editing (just to test) and changed the import statements in the RAC source (2 of them causing errors) from:
`#import "EXTRuntimeScope.h"` 
to:
`#import <ReactiveCocoa/EXTRuntimeScope.h>`

and that seemingly let it compile, but it errored at the link stage with this:
![](https://cldup.com/lWjsbzfCGu.png)

Something's up here but I don't know what or how to debug/investigate it efficiently. Any ideas?

**Comment by TiagoVeloso** [comment]
I am experiencing the same issue, but with ReactiveCocoa 2.5.

I get the following.
   ReactiveCocoa/NSObject+RACKVOWrapper.m:49:3: Unknown type name 'rac_propertyAttributes'; did you mean 'mtl_propertyAttributes'?

**Comment by tomtaylor** [comment]
I also have this problem with the same dependencies on `4.0.2-alpha.1`. I appreciate you're not supporting CocoaPods, but maybe one way round this is to add a script to the Cocoapods spec to rewrite the import paths or file names?

**Comment by tomtaylor** [comment]
This issue is also referenced at https://github.com/CocoaPods/CocoaPods/issues/4376.

**Comment by JRHeaton** [comment]
Closing as this is not gonna get fixed on the pods side of things. If anyone out there wants to use Mantle and RAC, I'd recommend using Carthage.

**Comment by Stunner** [comment]
I had RAC already installed via CocoaPods. I installed Mantle via Carthage and no problems so far.
