### ISSUE TITLE
Signal for 2 buttons

### ISSUE THREAD

**Issue by cecilcosta** [ReactiveCocoa/ReactiveCocoa#2467]
I have 2 buttons that work like the radio button. No selection by default, but when the user selects one of them there is always one that is selected. I need a signal for using with `combineLatest` that the user has a selection. How could I do that? I'm using the swift 2 branch.

**Comment by CosynPa** [comment]
I don't think combineLatest is useful here. You can use merge

        let producer0 = button0.rac_signalForControlEvents(.TouchUpInside)
            .toSignalProducer()
            .map { _ in 0 } // map to a value so you know which button is clicked later
        let producer1 = button1.rac_signalForControlEvents(.TouchUpInside)
            .toSignalProducer()
            .map { _ in 1 }
        
        let producers = SignalProducer<SignalProducer<Int, NSError>, NSError>(values: [producer0, producer1])
        let buttonsProducer = producers.flatMap(.Merge) { $0 }
        
        buttonsProducer.startWithNext { [unowned self] buttonIndex in
            if buttonIndex == 0 {
                self.button0.selected = true
                self.button1.selected = false
            } else if buttonIndex == 1 {
                self.button0.selected = false
                self.button1.selected = true
            }
        }

**Comment by olejnjak** [comment]
What about something like this

    button1.selected <~ button2.rac_signalForControlEvents(.TouchUpInside)
        .toSignalProducer()
        .map { _ in !button2.selected }
        .skip(1) // default not selected
    button2.selected <~ button1.rac_signalForControlEvents(.TouchUpInside)
        .toSignalProducer()
        .map { _ in !button1.selected }
        .skip(1) // default not selected

Haven't tried, just an idea.
