### ISSUE TITLE
PropertyOf producer not updating

### ISSUE THREAD

**Issue by aschuch** [ReactiveCocoa/ReactiveCocoa#2470]
_I am using the ReactiveCocoa 4.0 alpha 1._

I am having a hard time to understand the following behaviour of `PropertyOf`.
My `timer` signal emits the current time every second. Based on the code below, I would expect my `timerLabelText` to be updated every second as well. 

```swift
var timer: Signal<NSDate, NoError> = {
    return Signal { sink in
        NSTimer.schedule(1.0) { timer in
            sendNext(sink, NSDate())
        }
        return nil
    }
}()
    
var timerLabelText: PropertyOf<String> {
    let signal = timer.map { date -> String in
        print("mapping time \(date)")
        return "\(date) mapped"
    }
    return PropertyOf(initialValue: "initial", signal: signal)
}
```

However, when I start the `timerLabelText.producer`, the update closure is never called, although the `map` function inside of `timerLabelText ` is invoked.

```swift
timerLabelText.producer.startWithNext { text in
    print(text)
}
```
```
// Log output
initial
mapping time 2015-10-15 09:55:48 +0000
mapping time 2015-10-15 09:55:49 +0000
mapping time 2015-10-15 09:55:50 +0000
mapping time 2015-10-15 09:55:51 +0000
```

Am I missing something here?

**Comment by aschuch** [comment]
After digging around a bit more, it seems like the `timerLabelText.producer` only sends the initial value, then completes. Shouldn't the producer receive all values of the `timer` signal, thus never complete?

```
NEXT initial
COMPLETED
```

**Comment by andersio** [comment]
You need to retain the property. `PropertyOf` taking signals or producers is a wrapper around `MutableProperty`, which sends a completed event when it is deallocated.

**Comment by aschuch** [comment]
@andersio Thanks a lot, marking all `PropertyOf` variables as `lazy` now works as expected. 
:boom: :tada:
