### ISSUE TITLE
Question: Enum filtering

### ISSUE THREAD

**Issue by schickling** [ReactiveCocoa/ReactiveCocoa#2471]
Note: This is not a problem with ReactiveCocoa but rather a question on what would be the best ReactiveCocoa-ish implementation.

Goal: I want generically map a enum `Signal` to a `bool`.

Here is a concrete example:

```swift
enum Color { case Blue, Red, Green }

let signal: Signal<Color>

// ...

let boolSignal = signal
  .map { color in
    return switch {
      case Blue: return true
      case Red: return false
      case Green: return false
    }
```

The generic syntax I imagine for this would be:
```swift
signal.isEnum(.Blue)
```

It something like this even possible in Swift 2?

PS: I know about this `if case .Blue = color` notation.

**Comment by natestedman** [comment]
If your enum conforms to `Equatable`, you could use something like:

    public extension SignalProducerType where T: Equatable
    {
        public func equalTo(value: T) -> SignalProducer<Bool, E>
        {
            return map({ next in next == value })
        }
    }

**Comment by schickling** [comment]
Thanks @natestedman. Works great!
