### ISSUE TITLE
[Rac4] How to use rac_liftSelector with MutableProperty 

### ISSUE THREAD

**Issue by sarunw** [ReactiveCocoa/ReactiveCocoa#2478]
I want to do something like
```
self.rac_liftSelector(Selector("reloadContent:"), withSignalOfArguments: self.viewModel.content.producer)
```
content is MutableProperty String.

It doesn't compile, the method signature required RACSignal, but I don't know how to get that. Used to be RACObserve in RAC2

**Comment by andersio** [comment]
If you really want to use RAC2 primitives, there are bridges.
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/ObjectiveCBridging.swift#L91

But to be frank, while I am not sure if there is any other special requirement, you can probably do it like:
```
self.viewModel.content.producer.startWithNext(self.reloadContent)
// or `start(next:)` if you are using RAC3
```

**Comment by sarunw** [comment]
No, I want to use new `MutableProperty` my content is `let content: MutableProperty<String>("")`

I want to know how to achieve this in RAC3/4 style.

**Comment by andersio** [comment]
Note: RAC4 introduced `startWithNext(next:)` which is just `start(next:)` in RAC3.

`startWithNext(reloadContent)` would do, assuming you just want to pipe the values to `reloadContent:`. You can pass instance methods as closures in Swift. That's said `reloadContent:` has to be of `String -> Void` type.

**Comment by sarunw** [comment]
Its work! Thank you very much :)

**Comment by andersio** [comment]
You may need to be aware of the reference cycle though. If your VC (`self` in this context) retains the view model, using it this way would cause a reference cycle. You may want to wrap it in a block, and capture self as a weak reference.

**Comment by sarunw** [comment]
Something like this ?
```
self.viewModel.content.producer.startWithNext(
            { [weak self] content in
                self?.reloadContent(content)
            })
```

**Comment by andersio** [comment]
Yeah, exactly. :)
