### ISSUE TITLE
[RAC2] Performance issue and huge memory leak in RACCommand

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2479]
I found a perfomance issue and memory leak when using RACCommand. I a real project for a client I have a table that ends up listing around 1000 items. For each table view cell I have a cell view model with several commands. Everything was working fine until the list needed to show 1000 elements. 

The problem is in RACCommand. I created an example project that allocates 1000 cell view models that only have 8 `RACCommand` property. Running that code in the following setup

OS X 10.10.5
MacBook Pro (Retina, Mid 2012)
Processor 2.6 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3

Simulator Version 9.0 (SimulatorApp-620 CoreSimulator-179)

takes almost 6 seconds to allocate the 1000 cell view models.

```objc
@interface CellViewModel : NSObject

@property (nonatomic, readonly) RACCommand * command1;
@property (nonatomic, readonly) RACCommand * command2;
@property (nonatomic, readonly) RACCommand * command3;
@property (nonatomic, readonly) RACCommand * command4;
@property (nonatomic, readonly) RACCommand * command5;
@property (nonatomic, readonly) RACCommand * command6;
@property (nonatomic, readonly) RACCommand * command7;
@property (nonatomic, readonly) RACCommand * command8;

@end

@implementation CellViewModel

- (instancetype)init {
    if (self = [super init]) {
        _command1 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command2 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command3 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command4 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command5 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command6 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command7 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
        _command8 = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
    }
    return self;
}

@end
```

```objc
#import "AppDelegate.h"
#import "CellViewModel.h"

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    NSUInteger cellsCount = 1000;
    NSMutableArray * array = [NSMutableArray arrayWithCapacity:cellsCount];
    NSDate * start = [NSDate date];
    for (NSUInteger i = 0; i < cellsCount; ++i) {
        id cell = [[CellViewModel alloc] init];
        [array addObject:cell];
    }
    NSTimeInterval interval = [[NSDate date] timeIntervalSinceDate:start];
    NSLog(@"Invertal %g for %ld cells", interval, cellsCount);
    
    return YES;
}
```

**Cartfile**
```
github "ReactiveCocoa/ReactiveCocoa" "v4.0-alpha.1"
```

**Cartfile.resolved**
```
github "antitypical/Result" "76f9a972ed61ff872b731460bc610c8acbfae58c"
github "ReactiveCocoa/ReactiveCocoa" "v4.0-alpha.1"
```

After running the for loop, memory reaches ~500mb and after the array is deallocated there are still 180mb leaked objects.

Here is a link to the test project to reproduce this issue. https://dl.dropboxusercontent.com/u/4060090/RACCommandBug.zip

**Comment by neilpa** [comment]
Thanks for a simple repro. I wonder if this is related to some of the recent changes to `RACCommand`. IIRC @mdiep or @joshaber had been making changes in that area.

Even once the memory leak is fixed though, I would highly discourage using 8 commands per cell. They are relatively expensive to create given the number of internal signals they setup. I would also suggest one of the earlier stable releases over the v4 alpha build.

**Comment by guidomb** [comment]
@neilpa I have just found https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1503 so I guess the performance issues would be hard to solve.

It makes sens to only concentrate in the memory leak first and as you said form now on I will avoid using several commands per cell.

**Comment by guidomb** [comment]
@neilpa I am using v4 alpha because the project needs to be compatible with XCode 7 / iOS 9

**Comment by neilpa** [comment]
You could try using the most recent 2.x release if you only need Obj-C. We could also look at making a new 2.x+1 release for Obj-C that builds with Xcode 7.

**Comment by guidomb** [comment]
@neilpa Making a new 2.x realease that builds with Xcode 7 sounds good. As far as I know the 2.x branch is still supported / maintained. The only problem is that currently `Result 0.4.5` is not working with Carthage 0.9.3 and XCode 6.4 but I guess that should be fixed in Result.

**Comment by neilpa** [comment]
> Making a new 2.x realease that builds with Xcode 7 sounds good

Sadly, I don't think this is possible with semantic version only without breaking Xcode 6.4 for the current 2.x builds.

**Comment by guidomb** [comment]
OK so just to be sure I have an Objective-C / RAC codebase and I want to support iOS 9 (which is a must) currently the only option is to use `v4.0-alpha.1`?

**Comment by mdiep** [comment]
Running this through the Leaks tool in Instruments, I don't see any leaked memory.

What leaked objects are you seeing?

**Comment by guidomb** [comment]
<img width="532" alt="screen shot 2015-10-18 at 4 51 04 pm" src="https://github-cloud.s3.amazonaws.com/assets/390645/10566249/7c258898-75b8-11e5-9ca6-fd278ec50fe2.png">

**Comment by guidomb** [comment]
Maybe is not a memory leak but I would expect that to go down lower than 180mb. Shouldn't it be around 50mb after deallocing the array?

Also 500mb seems to be alot for 1000 commands.

**Comment by dapenggao** [comment]
> Given the toolchain/SDK issues we should really just split Obj-C and Swift frameworks and with an explicit third framework for bridging.

I would love to see this happening on RAC4.

**Comment by mdiep** [comment]
> Maybe is not a memory leak but I would expect that to go down lower than 180mb. Shouldn't it be around 50mb after deallocing the array?

Xcode reports that memory usage is 180 MB, but Instruments only reports 20 MB of persistent bytes.

Xcode must be reporting the resident memory size or something. I'm not entirely sure why this would be so different, but AFAICT no memory is leaked.

**Comment by neilpa** [comment]
>> Given the toolchain/SDK issues we should really just split Obj-C and Swift frameworks and with an explicit third framework for bridging.

> I would love to see this happening on RAC4.

This has it's own naming and versioning issues to solve.
