### ISSUE TITLE
Signal<Signal<T, E>, E>.merge()

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#2487]
This is a continuation to #2314. [We now have a way to flatten signals of signals](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2449). However, it's still not trivial to do the equivalent of `SignalProducer(values: [producer1, producer2]).flatten(.Merge)` for a `Signal` of `Signal`s, because creating the outer signal is not trivial.

There was a discussion recently about this, and this is my proposed implementation:
```swift
extension SignalType {
	/// Merges the given signals into a single `Signal` that will emit all values
	/// from each of them, and complete when all of them have completed.
	public static func mergeSignals(signals: [Signal<Self.Value, Self.Error>]) -> Signal<Self.Value, Self.Error> {
		let producer: SignalProducer<Signal<Value, Error>, Self.Error> = SignalProducer(values: signals)
		var result: Signal<Self.Value, Self.Error>!

		producer.startWithSignal { (signal, _) in
			result = signal.flatten(.Merge)
		}

		return result
	}
}
```

What does everything think of adding this to the API?

**Comment by paulyoung** [comment]
@NachoSoto should `merge()` be `merge(signals: [Signal<Self.Value, Self.Error>])`?

**Comment by NachoSoto** [comment]
Errr, you're right! There'd be no way to construct that `Signal`, as I explained 😅

**Comment by paulyoung** [comment]
This would come in really handy for me right now.

**Comment by NachoSoto** [comment]
I'll try to do this tomorrow :)
