### ISSUE TITLE
Create dependencies between SignalProducers

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2490]
The same way `NSOperation` has `addDependency:`. What would be the idiomatic way of doing this with `SignalProducers`? The goal would be for example:

SignalProducerX -> Starts
SignalProducerY  -> Waits for SignalProducerX to finish independently of its outcome

Once SignalProducerX has received the `Completed` event, SignalProducerY would start. The thing is, I would like to have this done at runtime. So after a user does a certain action, a `SignalProducer` would be added into a Queue (FIFO) and would start, when the previous last would complete.

**Comment by ikesyo** [comment]
`then` operator?

**Comment by RuiAAPeres** [comment]
@ikesyo I was using my own `then` operator, so I completely missed that one. My own:

```
    @warn_unused_result(message="Did you forget to call `start` on the producer?")
    func then(next: Self.Value -> ()) -> SignalProducer<Self.Value, Self.Error> {
        return self.on(next: next)
    }
```

**Comment by RuiAAPeres** [comment]
@ikesyo so I would need to keep a reference to the last `SignalProducer` added to the Queue and keep chaining with the `then`.
