### ISSUE TITLE
Include of non-modular header inside in Xcode7.1 with cocoapods 0.39.0

### ISSUE THREAD

**Issue by wsof401** [ReactiveCocoa/ReactiveCocoa#2495]
After I update my Xcode version to 7.1, pod update, It remind me something bottom when I ran my project

![image](https://cloud.githubusercontent.com/assets/3211941/10658905/00e713a4-78ce-11e5-9b58-e610bdee4056.png)

**Comment by alphatroya** [comment]
+ 1, same issue, appears after latest XCode 7.1 update

**Comment by wsof401** [comment]
in my pod file:
```
pod 'ReactiveCocoa', '4.0.2-alpha-1'

**Comment by yxztj** [comment]
same issue here.

**Comment by wanbok** [comment]
+1

**Comment by fabioknoedtbcg** [comment]
+1

**Comment by Ricowere** [comment]
+1

**Comment by ikesyo** [comment]
We don't officially support CocoaPods, please follow the discussions in https://github.com/CocoaPods/CocoaPods/issues/3767 and https://github.com/CocoaPods/CocoaPods/issues/4056.

**Comment by neilpa** [comment]
Also, Xcode 7.1 is still beta and the `swift2` branch only happened to work. It'll continue tracking Xcode 7.0 until 7.1 is out of beta.

**Comment by fabioknoedtbcg** [comment]
hey @neilpa, Xcode 7.1 is out of beta since yesterday.

**Comment by orkenstein** [comment]
@neilpa where did you find posdpec for `swift2`?

**Comment by LvJianfeng** [comment]
same this.

**Comment by neilpa** [comment]
> We don't officially support CocoaPods, please follow the discussions in CocoaPods/CocoaPods#3767 and CocoaPods/CocoaPods#4056.

**Comment by jakecraige** [comment]
This doesn't seem to be exclusively a cocoapods issue. I have a framework set up that depends on this one via a git submodule, when adding my framework to a project I see this error.
