### ISSUE TITLE
New alpha Tag for Xcode 7.1

### ISSUE THREAD

**Issue by jeremiegirault** [ReactiveCocoa/ReactiveCocoa#2497]
Hey everybody,

   I notice there was an issue in xcode 7.1 which was fixed in swift2 branch.
   Would it be possible to create an alpha tag with a working version in order to be able to upgrade our Cartfiles and handle xcode 7.1 breaking changes ? 

Thanks

**Comment by olejnjak** [comment]
+1

**Comment by neilpa** [comment]
I'll try to create a new alpha release this afternoon. Been trying to find the time for about a week.

In the interim you can specify the commit hash directly in the `Cartfile` instead of a tag.

**Comment by olejnjak** [comment]
Great news, but at least my case is to be able to install through Cocoapods :)

**Comment by jeremiegirault** [comment]
@neilpa That's what I did but it's a bit complicated to sync multiple dependencies on a non-semver version number. Carthage cannot pick a good version.
Thank you for the tag however :)

**Comment by olejnjak** [comment]
@jeremiegirault I use this Cartfile which without any problems checks out the most recent commit of `swift2` branch which might not be optimal but as far as I need it works.

    github "ReactiveCocoa/ReactiveCocoa" "swift2"

**Comment by ivan-ushakov** [comment]
@olejnjak I tried your solution but getting compile error:

    *** Fetching ReactiveCocoa
    *** Fetching Result
    *** Checking out Result at "0.6.0-beta.3"
    *** Checking out ReactiveCocoa at "9af5f32b4f9f908ae5f26904fbaf49d0a9039e24"
    *** xcodebuild output can be found in /var/folders/bs/lzt6qqj55xddmfy8k54zm2k00000gn/T/carthage-xcodebuild.a7BThg.log
    *** Building scheme "Result-Mac" in Result.xcodeproj
    *** Building scheme "Result-iOS" in Result.xcodeproj
    *** Building scheme "Result-watchOS" in Result.xcodeproj
    *** Building scheme "ReactiveCocoa Mac" in ReactiveCocoa.xcworkspace
    ** BUILD FAILED **


    The following build commands failed:
    	CompileSwift normal x86_64
    	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    (2 failures)
    /Users/ivan_ushakov/Documents/Projects/Mindarin/Numbers/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:1:8: error: no such module 'Result'
    A shell task failed with exit code 65:
    ** BUILD FAILED **


    The following build commands failed:
    	CompileSwift normal x86_64
    	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    (2 failures)

Could you help me please with it?

**Comment by neilpa** [comment]
@jeremiegirault This is a general problem with development/pre-release dependencies which is why I opened Carthage/Carthage#803

**Comment by olejnjak** [comment]
@ivan-ushakov yeah maybe the main reason is that I build only for iOS platform.

**Comment by ivan-ushakov** [comment]
@olejnjak I tried `carthage build --platform iOS` but error is the same.
Here is my `Cartfile`:

    github "robb/Cartography"
    github "ReactiveCocoa/ReactiveCocoa" "swift2"
    github "realm/realm-cocoa"

**Comment by neilpa** [comment]
[Alpha 2](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.0.0-alpha.2) is out now
