### ISSUE TITLE
Are translations welcomed?

### ISSUE THREAD

**Issue by suzuki-0000** [ReactiveCocoa/ReactiveCocoa#2506]
Currently I'm writing a translation of the README.md to japanese for understanding.
Could I create a pull request I when finish it??

**Comment by neilpa** [comment]
The only problem I see is that it could easily become stale as we change the README. Although, except for major releases, it should be relatively stable so I'm :+1: on adding it.

**Comment by pepibumur** [comment]
@suzuki-0000 a big problem with this would be keeping it updated with new changes. Every major release would involve notifying all the translator in order to keep the documents updated.

**Comment by suzuki-0000** [comment]
It seems a better to wait to become stable version. I just try to translate it to a blog or something first. thanks for your reply.
