### ISSUE TITLE
How to use sendNext with SignalProducer outside of initialization closure

### ISSUE THREAD

**Issue by ryudice** [ReactiveCocoa/ReactiveCocoa#2513]
Hello,
I currentlu have a singleton class in my application with two signal producers, my viewcontrollers will subscribe to this SignalProducers on initialization when needed so they get notify of events, however I'm not sure how to send events to my SignalProducers after they have been initialized? Is there something like .pipe() for signalproducers? The closest I could find is buffer but I dont want the producers to buffer the signals.

**Comment by iv-mexx** [comment]
I think `buffer` is what you are looking for. If you don't want to buffer the events, the actual question is: why do you need `SignalProducer` and not `Signal`? 

If you want to get notified of events just when they occur, `Signal` seems to be the correct choice.

**Comment by ryudice** [comment]
Sorry for replying so late, you are right, I ended up using a signal. Thanks for your help!
