### ISSUE TITLE
Any instructions about import RAC4 source code to project for supporting iOS7

### ISSUE THREAD

**Issue by keywind** [ReactiveCocoa/ReactiveCocoa#2514]
In fact, we really can't give up our iOS7 users because they are almost 15%

I know RAC4 is iOS7 compatible on the source code. I have tried and failed, so do many other developers.

Would you please give some instructions about this?

**Comment by rpowelll** [comment]
As far as I can tell from the README, iOS 7 isn't supported:

> ReactiveCocoa supports OS X 10.9+ and iOS 8.0+

**Comment by keywind** [comment]
@rpowelll 

As @jspahrsummers  said in this post: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1629  

iOS7 is supported when imported as source.

![2015-10-26 10 56 44](https://cloud.githubusercontent.com/assets/782770/10720320/b41b760e-7bd0-11e5-93af-8c16b64397ea.png)

We also have our own stats, and sadly it's 15%

**Comment by CosynPa** [comment]
* Copy ReactiveCocoa and Result source code
* Remove `import Result` statements
* Add header search paths in Xcode to find Objective-C headers
* You should find build errors on some lines with something like `ReactiveCocoa.combineLatestWith`, replace the `ReactiveCocoa` module name with your own module name (usually the project name)
* Remove AppKit files such as NSControl+RACCommandSupport.m from the target (if you are building  on iOS)
* In Xcode target setting -> Build Phases -> Compile Sources, find RACObjCRuntime.m file and add `-fno-objc-arc` compiler flag to compile it without ARC

**Comment by nucauthu** [comment]
> You should find build errors on some lines with something like ReactiveCocoa.combineLatestWith, replace the ReactiveCocoa module name with your own module name (usually the project name)

What should I do if I have two module (two target) one for development, one for production?

**Comment by CosynPa** [comment]
If you have two targets, you can try to add source code to two targets separately, in each target, rename the module name to the target's module name respectively.

**Comment by nucauthu** [comment]
@CosynPa : thank you for your helps. I wonder that does anybody success to import RAC4 to source code? I have a project with swift 1.2 and RAC3. We also need to support ios7. Swift 1.2 goes with xcode 6 runs into compile time problem so we need to upgrade swift 2 (xcode 7, RAC4 as well). I'm afraid that we must spend a lot of time and end up with hopeless to idea with RAC4 and ios7.

**Comment by CosynPa** [comment]
We are using an alpha version of 4.0 with iOS 7

**Comment by CosynPa** [comment]
We were using it with iOS 7. But it will crash when run on an device, see #2637 . So we only support iOS 8 now.

**Comment by nucauthu** [comment]
@CosynPa :+1: Thank you very much for your support. We probably need to stay with RAC3 and swift 1.2 or change back to ObjC. IOS7 still takes about 11% in my country.
