### ISSUE TITLE
Deadlock on `buffer(...)`

### ISSUE THREAD

**Issue by AlexeyDemedetskiy** [ReactiveCocoa/ReactiveCocoa#2515]
Hi. Sorry for giant stack trace. I've caught deadlock when I am try to bind property to signal in signal fire.

At short: 
1) My timer is fired. (#68)
2) I assign new value to mutable property (#62)
3) Controller 1 observe change and decide to push Controller 2. (#19)
4) Controller 2 try to bind to the same signal as Controller 1 minded. (#12)
5) ???.
6) Deadlock.

RAC version 4.0 alpha 1
```
#0	0x000000019ab34c6c in semaphore_wait_trap ()
#1	0x000000019ac0e97c in _os_semaphore_wait ()
#2	0x0000000101d4d428 in _dispatch_barrier_sync_f_slow ()
#3	0x0000000100abe5d0 in static SignalProducer.(buffer<A, B where ...> (SignalProducer<A, B>.Type) -> (Int) -> (SignalProducer<A, B>, (Event<A, B>) -> ())).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:154
#4	0x0000000100aa9050 in partial apply for static SignalProducer.(buffer<A, B where ...> (SignalProducer<A, B>.Type) -> (Int) -> (SignalProducer<A, B>, (Event<A, B>) -> ())).(closure #1) ()
#5	0x0000000100a9f424 in SignalProducer.startWithSignal<A, B where ...>((Signal<A, B>, Disposable) -> ()) -> () at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:247
#6	0x0000000100a63308 in protocol witness for SignalProducerType.startWithSignal<A where ...>((Signal<A.T, A.E>, Disposable) -> ()) -> () in conformance <A, B where ...> SignalProducer<A, B> at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:218
#7	0x0000000100aa95c4 in SignalProducerType<A where ...>.(lift<A><B, C where ...> (A) -> ((Signal<A.T, A.E>) -> Signal<B, C>) -> SignalProducer<B, C>).(closure #1) [inlined] at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:365
#8	0x0000000100aa9540 in partial apply for SignalProducerType<A where ...>.(lift<A><B, C where ...> (A) -> ((Signal<A.T, A.E>) -> Signal<B, C>) -> SignalProducer<B, C>).(closure #1) ()
#9	0x0000000100a9f424 in SignalProducer.startWithSignal<A, B where ...>((Signal<A, B>, Disposable) -> ()) -> () at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:247
#10	0x0000000100ae436c in static <~ infix<A where ...> (A, SignalProducer<A.Value, NoError>) -> Disposable at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Property.swift:232
#11	0x000000010013c58c in Store.bindProperty<A, B><C>(MutableProperty<C>, withLens : (A, (B) -> ()) -> C) -> () at /Users/project/src/Store.swift:38
#12	0x000000010013175c in AddNewLockErrorViewController.store.didset at /Users/project/src/add lock/AddNewLockErrorViewController.swift:45
#13	0x00000001001318e0 in AddNewLockErrorViewController.store.setter ()
#14	0x000000010012feb0 in AddNewLockScanningContoller.prepareForSegue(UIStoryboardSegue, sender : AnyObject?) -> () at /Users/project/src/add lock/AddNewLockSpinnerViewController.swift:53
#15	0x000000010013000c in @objc AddNewLockScanningContoller.prepareForSegue(UIStoryboardSegue, sender : AnyObject?) -> () ()
#16	0x000000018b255c78 in -[UIStoryboardSegueTemplate _performWithDestinationViewController:sender:] ()
#17	0x000000018b255ae0 in -[UIStoryboardSegueTemplate _perform:] ()
#18	0x000000018aecb6a8 in -[UIViewController performSegueWithIdentifier:sender:] ()
#19	0x0000000100130f04 in AddNewLockScanningContoller.(viewDidAppear(AddNewLockScanningContoller) -> (Bool) -> ()).(closure #3) at /Users/project/src/add lock/AddNewLockSpinnerViewController.swift:48
#20	0x000000010012ab30 in thunk ()
#21	0x0000000100af1018 in static Event.(sink<A, B where ...> (Event<A, B>.Type) -> (error : (B) -> ()?, completed : () -> ()?, interrupted : () -> ()?, next : (A) -> ()?) -> (Event<A, B>) -> ()).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift:108
#22	0x0000000100aeff78 in partial apply for static Event.(sink<A, B where ...> (Event<A, B>.Type) -> (error : (B) -> ()?, completed : () -> ()?, interrupted : () -> ()?, next : (A) -> ()?) -> (Event<A, B>) -> ()).(closure #1) ()
#23	0x0000000100a744bc in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#24	0x0000000100ac1a78 in SignalProducer.(startWithSignal<A, B where ...> (SignalProducer<A, B>) -> ((Signal<A, B>, Disposable) -> ()) -> ()).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:238
#25	0x0000000100a744bc in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#26	0x0000000100aef7bc in sendNext<A, B where ...> ((Event<A, B>) -> (), A) -> () at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift:178
#27	0x0000000100a7b21c in SignalType<A where ...>.(take<A where ...> (A) -> (Int) -> Signal<A.T, A.E>).(closure #1).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:600
#28	0x0000000100a70a00 in partial apply for SignalType<A where ...>.(take<A where ...> (A) -> (Int) -> Signal<A.T, A.E>).(closure #1).(closure #1) ()
#29	0x0000000100a744bc in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#30	0x0000000100ac1a78 in SignalProducer.(startWithSignal<A, B where ...> (SignalProducer<A, B>) -> ((Signal<A, B>, Disposable) -> ()) -> ()).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:238
#31	0x0000000100a744bc in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#32	0x0000000100a76720 in SignalType<A where ...>.(map<A><B where ...> (A) -> ((A.T) -> B) -> Signal<B, A.E>).(closure #1).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:212
#33	0x0000000100a71f60 in partial apply for SignalType<A where ...>.(map<A><B where ...> (A) -> ((A.T) -> B) -> Signal<B, A.E>).(closure #1).(closure #1) ()
#34	0x0000000100a74394 in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#35	0x0000000100ac1a78 in SignalProducer.(startWithSignal<A, B where ...> (SignalProducer<A, B>) -> ((Signal<A, B>, Disposable) -> ()) -> ()).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:238
#36	0x0000000100a74394 in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#37	0x0000000100aef7bc in sendNext<A, B where ...> ((Event<A, B>) -> (), A) -> () at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift:178
#38	0x0000000100a76cc4 in SignalType<A where ...>.(filter<A where ...> (A) -> ((A.T) -> Bool) -> Signal<A.T, A.E>).(closure #1).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:235
#39	0x0000000100a71d90 in partial apply for SignalType<A where ...>.(filter<A where ...> (A) -> ((A.T) -> Bool) -> Signal<A.T, A.E>).(closure #1).(closure #1) ()
#40	0x0000000100a74394 in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#41	0x0000000100ac1a78 in SignalProducer.(startWithSignal<A, B where ...> (SignalProducer<A, B>) -> ((Signal<A, B>, Disposable) -> ()) -> ()).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:238
#42	0x0000000100ac0930 in static SignalProducer.(buffer<A, B where ...> (SignalProducer<A, B>.Type) -> (Int) -> (SignalProducer<A, B>, (Event<A, B>) -> ())).(closure #2).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:186
#43	0x0000000101d41d30 in _dispatch_client_callout ()
#44	0x0000000101d4d88c in _dispatch_barrier_sync_f_invoke ()
#45	0x0000000100ac01bc in static SignalProducer.(buffer<A, B where ...> (SignalProducer<A, B>.Type) -> (Int) -> (SignalProducer<A, B>, (Event<A, B>) -> ())).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:189
#46	0x0000000100aef7bc in sendNext<A, B where ...> ((Event<A, B>) -> (), A) -> () at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift:178
#47	0x0000000100ae51c8 in MutableProperty.value.setter at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Property.swift:102
#48	0x0000000100a63894 in protocol witness for MutablePropertyType.value.setter in conformance <A> MutableProperty<A> at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Property.swift:99
#49	0x0000000100aeb344 in static (<~ infix<A where ...> (A, Signal<A.Value, NoError>) -> Disposable).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Property.swift:204
#50	0x0000000100a74394 in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#51	0x0000000100ac1a78 in SignalProducer.(startWithSignal<A, B where ...> (SignalProducer<A, B>) -> ((Signal<A, B>, Disposable) -> ()) -> ()).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:238
#52	0x0000000100a74394 in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#53	0x0000000100a76720 in SignalType<A where ...>.(map<A><B where ...> (A) -> ((A.T) -> B) -> Signal<B, A.E>).(closure #1).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:212
#54	0x0000000100a71f60 in partial apply for SignalType<A where ...>.(map<A><B where ...> (A) -> ((A.T) -> B) -> Signal<B, A.E>).(closure #1).(closure #1) ()
#55	0x0000000100a744bc in Signal.(init<A, B where ...> (Signal<A, B>.Type) -> (((Event<A, B>) -> ()) -> Disposable?) -> Signal<A, B>).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Signal.swift:63
#56	0x0000000100ac1a78 in SignalProducer.(startWithSignal<A, B where ...> (SignalProducer<A, B>) -> ((Signal<A, B>, Disposable) -> ()) -> ()).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:238
#57	0x0000000100ac0a40 in static SignalProducer.(buffer<A, B where ...> (SignalProducer<A, B>.Type) -> (Int) -> (SignalProducer<A, B>, (Event<A, B>) -> ())).(closure #2).(closure #1) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:186
#58	0x0000000101d41d30 in _dispatch_client_callout ()
#59	0x0000000101d4d88c in _dispatch_barrier_sync_f_invoke ()
#60	0x0000000100ac01bc in static SignalProducer.(buffer<A, B where ...> (SignalProducer<A, B>.Type) -> (Int) -> (SignalProducer<A, B>, (Event<A, B>) -> ())).(closure #2) at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:189
#61	0x0000000100aef7bc in sendNext<A, B where ...> ((Event<A, B>) -> (), A) -> () at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Event.swift:178
#62	0x0000000100ae51c8 in MutableProperty.value.setter at /Users/project/Carthage/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/Property.swift:102
#63	0x000000010013bfd0 in Store.(dispatch in _B476A900240ACFD9431014A74E83EFE4)<A, B>(B) -> () at /Users/project/src/Store.swift:28
#64	0x000000010013c9d4 in partial apply ()
#65	0x00000001001243cc in thunk ()
#66	0x00000001001240c8 in (lens(AddNewLock.State, dispatch : (AddNewLock.Action) -> ()) -> LockScannerService.ServiceModel).(closure #2) at /Users/project/src/add lock/BluetoothLockScaner.swift:20
#67	0x000000010012298c in LockScannerService.timerFired() -> () at /Users/project/src/add lock/BluetoothLockScaner.swift:86
#68	0x00000001001229e4 in @objc LockScannerService.timerFired() -> () ()
#69	0x0000000186550324 in __NSFireTimer ()
#70	0x00000001855c8c9c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ ()
#71	0x00000001855c8940 in __CFRunLoopDoTimer ()
#72	0x00000001855c6054 in __CFRunLoopRun ()
#73	0x00000001854f4dc0 in CFRunLoopRunSpecific ()
#74	0x0000000190648088 in GSEventRunModal ()
#75	0x000000018abcef44 in UIApplicationMain ()
#76	0x00000001000c8288 in main at /Users/project/support/main.m:14
#77	0x000000019aa328b8 in start ()
```

**Comment by DAloG** [comment]
I think that problem is in this code. 
```
			if dispatch_get_specific(&queue) != nil {
				replay()
			} else {
				dispatch_sync(queue, replay)
			}
```

**Comment by andersio** [comment]
Did you apply startOn or observeOn to the producer? The deadlock is due to a dispatch_sync call within the scope of an executing dispatch_sync block on the same queue.

**Comment by andersio** [comment]
Based on what I've read, the buffering observer and the replay closure both captures the same serial dispatch queue. However, the later would elide a dispatch_sync call if and only if the current scope is running on the same serial dispatch queue.

In other words, if you start a producer in an observer of it, it would not deadlock if and only if you didn't explicitly make the side effect or observer happen on other threads. I believe this is a case of "limited signal recursion" said in the documentation.

**Comment by DAloG** [comment]
But `start` called on some derived SignalProducer... 
I don't understand in detail what happened inside RAC. Currently i move notification and subscription inside serial queue. This solve issue.
But if you can tell me how to redesign my code to avoid this - it would be helpful

**Comment by Vadim-Yelagin** [comment]
I'm having the same issue.
Correct me if I'm wrong, but I assume that the locking (i.e. dispatch_sync) here is needed only to avoid situations when appending to the buffer inside the buffer's observer leads to incorrect order of events received by the observer.
Adding new observers (i.e. starting the producer) inside another observer should not cause any problems neither with nor without the locking.
Allowing this scenario was the intention behind making the locking recursive. The recursion being limited means that you still cannot append new events while observing the buffer.
However, the way this recursiveness is implemented can still lead to deadlocks when trying to recursively lock, e.g. in case when after that dispatch_sync, another dispatch_sync on another queue (e.g. such a lock in another buffer) was made. After that, the test for "recursiveness" (dispatch_get_specific) is negative and dispatch_sync is called and it deadlocks.

Either way, any implementation of recursive locking with GCD is at least error-prone and considered an anti-pattern.

I have two suggestions to mitigate this. First is to remove the locking altogether. This will fix the unintentional deadlock due to recursiveness implementation, and instead of deadlocking in other cases that could lead to events order inversion, the inversion will actually happen. It probably isn't worse than deadlocking anyway.

Another suggestion is to remove the locking and modify the buffer state in a way that would fix the ordering issue. E.g. so that in all situations the order of event will be correct. The idea is to store a queue of events that are to be immediately passed to each observer, one such queue for every observer. When adding a new observer, insert it into the state together will all of the buffer's content, then proceed to immediate event delivery routine. The routine is to loop while there are events to dispatch, and dispatch them one at a time (that can lead to arbitrary calls of any methods of the buffer, and is done outside of any locks). When appending a new event, insert into the buffer as well as into every observer's queue, then proceed to the same routine.

I'd be glad to try it and make a PR, unless you see any issues with it.

**Comment by Vadim-Yelagin** [comment]
That's essentially my situation when it deadlocks:

	let pp = MutableProperty(MutableProperty(42))
	let p = pp.producer.flatMap(.Latest) { $0.producer }
	p.startWithNext { value1 in
		print("VALUE 1 = \(value1)")
		p.startWithNext { value2 in
			print("VALUE 2 = \(value2)")
		}
	}

This prints "VALUE 1 = 42" and deadlocks.

Note that this doesn't deadlock thanks to limited recursiveness:

	let p = MutableProperty(42).producer
	p.startWithNext { value1 in
		print("VALUE 1 = \(value1)")
		p.startWithNext { value2 in
			print("VALUE 2 = \(value2)")
		}
	}

**Comment by andersio** [comment]
Following the stack trace as much as I can, I managed to reproduce DAIoG's case with the following code snippet.
```
import ReactiveCocoa

let prop1 = MutableProperty<Bool>(false)
let prop2 = MutableProperty<Bool>(false)
let prop3 = MutableProperty<Bool>(false)


prop1.producer.startWithNext { _ in
  prop2 <~ prop1
  prop2.producer.startWithNext { _ in
    prop3 <~ prop1
    prop3.producer.startWithNext { _ in
      print("test")
    }
  }
}

prop1.value = true
```

Behind the scene, the deadlock is caused by `prop3 <~ prop1`. It is because tracing back the call site stack, you have a closure in `prop1`'s serial queue waiting for a blocking call (`dispatch_sync`). Then this blocking call indirectly starts `prop1`'s producer which indirectly calls `dispatch_sync` on the internal serial queue.

One way to break the implicitly these nested calls is to apply `startOn(QueueScheduler())` to an inner binding, e.g.:
```
prop3 <~ prop1.producer.startOn(QueueScheduler())
```

Then the signal starting side effect would run asynchronously on another queue.

**Comment by Vadim-Yelagin** [comment]
@andersio making more things asynchronous is a doom-to-raceconditions panacea for deadlocks

**Comment by andersio** [comment]
@Vadim-Yelagin Just a... nasty workaround.

As far as I understand, the `dispatch_sync` call here is to prevent replaying signals to receive inconsistent result, if a new value happens to be sent at the same time. The state object containing values are not in reference semantics, so the changes made would not be observed by the replaying signal if you do not block them until the replay completes. Let alone the manipulation with regard to capacity limit would prevent the value array to be used safely across threads.

**Comment by Vadim-Yelagin** [comment]
I'm not sure what is the expected behavior wrt buffer capacity in the problematic scenario of inserting new events while reacting to old ones.

**Comment by andersio** [comment]
```
Prevent other threads from sending events while we're replaying
```

Say we are in the process of replaying 100 values, and a new value is being sent at the time when you are looping through the values. If you leave it unprotected, the replaying signal may observe the new value before some of the previous 100 values. The order needs to be preserved.

**Comment by Vadim-Yelagin** [comment]
@andersio Yeah, that's what I was saying and am addressing in my PR. The solution is that the new value goes to the tail of the queue containing some remaining values of those 100 values, instead of going directly to the observer.

**Comment by NachoSoto** [comment]
Why do you need to `start` the same producer inside of `next`?

**Comment by andersio** [comment]
@NachoSoto In DAIoG's case, he wants to share the same timer, modelled as a MutableProperty, among two ViewControllers, which the second View Controller is pushed depending upon the timer fires.

But if the timer is self-counting anyway, perhaps `Signal` is a better tool than a producer with a buffer.

**Comment by neilpa** [comment]
> making more things asynchronous is a doom-to-raceconditions panacea for deadlocks

@Vadim-Yelagin Not at all. The whole point of RAC is to lift mutable state into a value stream. You don't need to do any locking yourself at that point. The internal locking is an implementation detail to ensure that all observers perceive events in the same order and at the same time.

**Comment by Vadim-Yelagin** [comment]
If there's been a lot of consideration of different pitfalls of different approaches, that would be really helpful to have tests that illustrate those pitfalls.
I think I can see how the lock can help when adding an observer on one thread and inserting an event on another thread. But either way this half-hearted implementation of recursive locking (which by itself is an anti-pattern and can't comprehensibly protect from deadlocks when calling arbitrary callback code while locked) doesn't seem like the way to go.
What if instead of having a single lock per buffer we make a lock for every observer and store it in the state in pair with the observer? This way when a new observer is added, only its newly created lock gets locked, which will deadlock if the observer tries to insert a new event, but not if it adds a new observer. When inserting a new event, the locks get locked one-by-one when iterating over observers. This will too deadlock when trying to insert an event, but not when adding a new observer. It's the same desired behavior but without the need for recursive locks.

**Comment by Vadim-Yelagin** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2589

**Comment by Vadim-Yelagin** [comment]
Okay, looks like my idea with multiple mutexes (mutices?) worked and I've fixed it in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2589
Did I miss anything?

**Comment by Vadim-Yelagin** [comment]
Yep, I haven't considered the scenario when multiple thread push events at the same time. This can result in different observers receiving the events in different order (btw there's no notion of "the right" order in this situation). I don't know if this is a valid use case or not, but either way it's treated by wrapping the pushing part (but not the observer-adding part) in a dispatch_sync. Let me do this.
