### ISSUE TITLE
Avoid a second http request.

### ISSUE THREAD

**Issue by cecilcosta** [ReactiveCocoa/ReactiveCocoa#2516]
I have one signal that basically what it does is requesting for a configuration using NSRULSession. When I do a subscribeNext it does the request perfectly fine, however for the second time this request is not necessary anymore. How could I avoid it?

**Comment by RuiAAPeres** [comment]
@cecilcosta do you still need help with your problem?

**Comment by cecilcosta** [comment]
I've solved that, however I'd like to see more solutions.

**Comment by RuiAAPeres** [comment]
@cecilcosta could you show me what you have come with?
