### ISSUE TITLE
SignalProducer(values: S) in RC4

### ISSUE THREAD

**Issue by mbopp** [ReactiveCocoa/ReactiveCocoa#2525]
I seem to be having consistent issues with using the `values:` initializer for a Signal Producer.  

Take the following...
```
func getDocumentProducer() -> SignalProducer<Document, NoError> {
  return SignalProducer { sink, _ in
    if let moc = self.managedObjectContext {
      do {
        let documents = try moc.executeFetchRequest(self.documentsFetchRequest) as! [Document]
        SignalProducer(values: documents)
          .startWithNext { doc in
              sink.sendNext(doc)
            }
      } catch let error as NSError {
        print("Could not fetch Documents \(error.localizedDescription)")
      }
      
    }
  }
}
```
I get an `Cannot invoke 'startWithNext' with an argument list of type '((Document) -> ())`
I may be missing something fundamental, though I believe I was doing something similar in Swift 1.2.  Is it that I have a signal producer that contains a signal producer that actually sends the event?  

Can you point me in the correct direction for doing this common scenario?

Thanks

**Comment by NachoSoto** [comment]
Seems like Swift is having a hard type inferring some of the types. Does it help if you provide it explicitly?
```swift
SignalProducer<Document>(values: documents)
```

You don't need to create that `SignalProducer` inside, however, you can simply forward the values to the `sink` directly:
```swift
let documents = ...
documents.forEach(sink.sendNext)
sink.sendCompleted()
```

**Comment by mbopp** [comment]
I see, yes adding the type does solve the issue.  
```
SignalProducer<Document, NoError>(values:documents)
```

And you are right, it doesn't really make sense in this situation to do another `SignalProducer`. Sometimes I get a little over zealous about being so functional as to never use loops. :/  The bigger thing was that I was running into this issue from time to time, and I hadn't thought to solve it by explicitly stating the type of `SignalProducer`.  So this helps.

Thanks so much!

**Comment by NachoSoto** [comment]
You're welcome! :)
