### ISSUE TITLE
Canceling previous Signals generated by SignalProducer

### ISSUE THREAD

**Issue by mbopp** [ReactiveCocoa/ReactiveCocoa#2529]
I have a `MutableProperty` whose `SignalProducer` creates a fairly lengthy signal of events.  I would like to cancel the previous active signal when a new one is sent. (when the `MutableProperty` changes) so that only the latest one is running.  

I am familiar with the old `switchToLatest` and using `flatten(.Latest)`, however `.flatten` doesn't appear to be a valid method on a `SignalProducer`.  What should I be using in this scenario?

Thanks

**Comment by neilpa** [comment]
Both `flatten` and `flatMap` are valid on `SignalProducer`. You probably need to add extra type-info though to convince the compiler.

**Comment by mbopp** [comment]
I see, it looks like it's because of an `ambiguous reference to flatten` 

when using a `MutableProperty.producer`  where do you add this extra type information to remove the ambiguity?  Given something like...
```
prop.producer.flatten(.Latest).start()
```

**Comment by mbopp** [comment]
If I try to use 
``` (prop.producer as SignalProducer<[Type],NoError>).flatten....```
I get a 'Will always succeed' message and it doesn't seem to resolve the flatten issue.

**Comment by bencochran** [comment]
`flatten` is to be used on a Signal of Signals (or SignalProducer of SignalProducers) such as `SignalProducer<SignalProducer<Type, NoError>, NoError>`. You’re unable to use it because you’re trying to call it on a `SignalProducer<[Type],NoError>`.

What outcome are you trying to achieve?

**Comment by mbopp** [comment]
Okay.  Well, when this `SignalProducer` creates a `Signal`... I want to cancel any existing signals created by THIS `SignalProducer`. So that no more than one `Signal` is active (the last one) at any time.  

In my case, this is to prevent simultaneous url requests doing the same thing.

**Comment by mbopp** [comment]
So, as an alternative approach to do what I'm wanting.  I am assigning a `Disposable` property when starting a signal.  And before starting one again, I check and dispose of the previous one.  Strangely, this doesn't seem to stop the flow of processing for the disposed signal.

**Comment by mbopp** [comment]
Disregard my previous comment.  I think it is disposing as expected.
