### ISSUE TITLE
Workaround compiler ambiguity with flatten and flatMap

### ISSUE THREAD

**Issue by neilpa** [ReactiveCocoa/ReactiveCocoa#2530]
Now that `flatten` and `flatMap` are defined for all combos of signals and producers it's too easy to get ambiguity errors. We may need to consider renaming the operators based on the inner type since I'm pretty sure that's the source of the problem. E.g. x-of-signals is `flattenSignals` and x-of-producers is `flattenProducers`.

**Comment by neilpa** [comment]
c.f. #2529

**Comment by NachoSoto** [comment]
Then we'll need `flatMapSignals` and `flatMapProducers`. Not sure if the cure is worse than the problem :/

**Comment by neilpa** [comment]
That's fine. This is a really annoying bug to deal with because it's not always clear where the compiler needs extra type info. And sometimes the error messages aren't always `ambiguous reference to flatten`. I've also seen something like `cannot convert (_) -> (_) to (_) -> (_)` before. I expect these to be incredibly frustrating for people learning the framework.

**Comment by avalanched** [comment]
same happens if you have multiple return's in flat map

```swift
// Ambiguous use of 'flatMap(_:transform:)'
SignalProducer<String,NoError>(value: "a")
    .flatMap(FlattenStrategy.Latest) {
        switch $0 {
        case "a": return SignalProducer(value: "aa")
        default: return SignalProducer(value: "bb")
        }
    }
    .startWithNext { print($0) }
````

**Comment by NachoSoto** [comment]
I just filed a radar with a reduced example: [rdar://23385956](http://www.openradar.me/23385956).

I don't think I like the idea of changing the names of the methods just to work around it though :/ but I do agree it's hard for newcomers to figure out.

**Comment by neilpa** [comment]
It's not just newcomers. I've spent lots of time dealing with these spurious compiler errors in `flatMap` code because of this issue. And unless you've got good intuition about what the compiler's doing you may just give up because what you're doing _should_ work.

**Comment by NachoSoto** [comment]
LOL Apple closed the radar:
<img width="842" alt="screen shot 2015-11-19 at 16 08 25" src="https://cloud.githubusercontent.com/assets/685609/11288369/3c5e5242-8ed8-11e5-868f-d136c2aa7d52.png">

![are you kidding me](https://cloud.githubusercontent.com/assets/685609/11288376/4511d2f6-8ed8-11e5-9198-dc07dd7c21ac.jpg)

**Comment by NachoSoto** [comment]
I'm going to take this out of 4.0 since it's likely we won't be able to solve it on time.
For the time being I think it could be solved with better documentation instead.

**Comment by Palleas** [comment]
I have this issue on code, I've tried to fix it by being as explicit as possible, but Xcode doesn't want to comply:

```swift
return FetchMemberInfos()
    .send(NSURLSession.sharedSession(), baseURL: AuthenticatedClient.baseURL, key: key, token: token)
    .flatMap(FlattenStrategy.Latest, transform: { (member) -> SignalProducer<Show, RequestError> in
        return SignalProducer<Show, RequestError>(values: member.shows)
    })
```

What is the best way around this? 

Thanks!

**Comment by NachoSoto** [comment]
That looks correct: are you getting an "ambiguous" error? That's probably because some types don't match. I'd recommend splitting up the different statements and looking at what types Swift is inferring.

**Comment by Palleas** [comment]
Yep, that's what I ended up doing, but it doesn't happen every time but when it does, it's always with the `flatMap` of Signal and SignalProducer... That's something that needs to be fixed at Swift level, right?

**Comment by avalanched** [comment]
yes `RxSwift` has the same problem [documented](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md#debugging-compile-errors)

**Comment by NachoSoto** [comment]
Well this issue in particular refers to an ambiguity created by RAC's duality, which is nonexistent in `Rx`.

**Comment by nickvelloff** [comment]
@NachoSoto Hi! I'm new to RAC and have this issue as well. It just appeared after updating to `4.2.x`. 
<img width="826" alt="screenshot 2016-06-03 13 01 22" src="https://cloud.githubusercontent.com/assets/885369/15791366/c3246840-298b-11e6-8671-4a96c5d6eeff.png">

Any ideas? 🙇

**Comment by mdiep** [comment]
I'm going to close this because I don't think we should take any action on it. Hopefully Swift provide some mechanism to help us with this at some point. But I don't think we should rename the operators.

**Comment by nickvelloff** [comment]
@mdiep in the referenced issue you actually got me past my issue with this, in case anyone else hits this. Thanks!
