### ISSUE TITLE
Issue archiving app with reactiveCocoa linker issue

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2532]
I'm trying to archive my app and I got this linking error message:

ld: bitcode bundle could not be generated because '.../myApp/Carthage/Build/iOS/ReactiveCocoa.framework/ReactiveCocoa' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

My Cartfile:
> cat Cartfile
github "ReactiveCocoa/ReactiveCocoa" "9af5f32b4f9f908ae5f26904fbaf49d0a9039e24" //swift 2 branch
github "SwiftyJSON/SwiftyJSON"

Any idea how to resolve this issue ?

**Comment by NachoSoto** [comment]
Let's try 2 things:
- Can you change to `RAC`'s `master` branch? `swift2` is no longer in development, it's already being merged into `master` :)
- What version of `Carthage` are you using?

**Comment by edwardIshaq** [comment]
Thanks @NachoSoto
I upgraded carthage to version 0.9.4, that seemed to be the issue...
but I will point to master now that you mentioned it.

**Comment by NachoSoto** [comment]
Awesome.

For reference, I imagine this works thanks to [this feature in `Carthage`](https://github.com/Carthage/Carthage/pull/839), setting `BITCODE_GENERATION_MODE` to `bitcode`.
