### ISSUE TITLE
Question - How to convert Signal to SignalProducer?

### ISSUE THREAD

**Issue by danishin** [ReactiveCocoa/ReactiveCocoa#2539]
I've recently started to convert from RAC 3 to RAC 4 and found out that `takeUntil` on `SignalProducer` now accepts `SignalProducer` as opposed to `Signal` in RAC 3.

This is my current method in `extension SignalType` and it feels pretty hackish:
```
func toSignalProducer() -> SignalProducer<T, E> {
  return SignalProducer { (sink, _) in
    self.observe(
      next: { t in sendNext(sink, t) },
      completed: { _ in sendCompleted(sink) }
    )
  }
}
```
Can I improve this? Thanks!

**Comment by ikesyo** [comment]
There is a `takeUntil` overload of `SignalProducer` that takes a `Signal` from v4.0.0-alpha.2: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v4.0.0-alpha.2/ReactiveCocoa/Swift/SignalProducer.swift#L557

**Comment by danishin** [comment]
Time for an update! Thanks :+1:

**Comment by danishin** [comment]
Just for curiosity, is my approach of converting `Signal` to `SignalProducer` sub-optimal? Can this be done better? I see most interoperability between `Signal` and `SignalProducer` comes by `lift`ing `Signal`'s operators to accept `SignalProducer`. Is converting `Signal` to `SignalProducer` frowned upon?

**Comment by NachoSoto** [comment]
This is already available in the framework! :)
```swift
let producer = SignalProducer(signal: signal)
```
That essentially creates a producer with no side effects (see #2449)
