### ISSUE TITLE
how to raise an error in signal or signal producer when map

### ISSUE THREAD

**Issue by dennisfarandy** [ReactiveCocoa/ReactiveCocoa#2540]
hey do you know how to raise an error in map function for signal or signal producer?

the case is I want to map some JSON to Model in signal producer after network request, but the function to JSON to my Model can be optional if I got wrong JSON, and I want to send an `ErrorType` if I got Nil value

**Comment by ikesyo** [comment]
If you'd like to switch the contexts, you should use `flatMap` instead of `map`.

**Comment by dennisfarandy** [comment]
so your suggestion, I should create new signal and send Nil value with `ErrorType` with `flatMap`?

**Comment by ikesyo** [comment]
Just a something like that:

```swift
let networkRequestProducer: SignalProducer<AnyObject, NSError> = ...
networkRequestProducer
    .mapError { error in MyError.NetworkError(error) }
    .flatMap(.Merge) { JSON -> SignalProducer<MyModel, MyError> in
        if let model = MyModel.decode(JSON) {
            return SignalProducer(value: model)
        } else {
            return SignalProducer(error: MyError.DecodeError(JSON))
        }
    }
```

**Comment by dennisfarandy** [comment]
+1 @ikesyo nice one.. i think `attemptMap ` look nicer.. never heard about `attemptMap` before.. thank you

**Comment by ikesyo** [comment]
No problem!
