### ISSUE TITLE
Q: Advantages to RAC-esque project/repo setup?

### ISSUE THREAD

**Issue by JRHeaton** [ReactiveCocoa/ReactiveCocoa#2541]
Howdy, I have a question. I'm currently building a framework of my own, also with dependencies, that I plan to let people install via Carthage, so I'm asking this from my own curiosity in wanting to know best practices around Carthage + framework targets, etc.

I figured I'd look to RAC for the ideal example of a Carthage-supporting project setup, since there are mutual contributors I believe between the two projects. I noticed that the RAC project, while still using the Carthage-checked-out Result project, it does so via manual integration of that project in Xcode, which if I am understanding/observing correctly, means that even if Carthage has built Result in `Carthage/Build/$platform`, the RAC project needs to re-build its own version to link against. So, each time someone is integrating RAC via Carthage as a dependency to their project, it's potentially taking 2x the time for compilation of Result (though it's a super small library with minimal time impact in this regard).

What are the advantages to setting up a project this way? The clear one to me was that you have access to source files of dependency projects right in the navigator, indexed by Xcode with symbols accessible via "jump quickly". Are there more reasons? I'm genuinely really interested, so any notes you can provide are greatly appreciated 😊

Thanks!

**Comment by ikesyo** [comment]
I believe the reason is to support the installation way of using git submodule (or subtree?), not to force the users to use Carthage for integrating the library.
