### ISSUE TITLE
[Feature request]: Add a signal to PropertyType

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#2543]
I think this was debated at some point but I can't find any other issue.

It would be nice if `PropertyType` also exposed a `Signal<Value, NoError>`. Of course we can do `property.producer.skip(1)`, but it would be nice to have its own method to expose this with the right *no-side-effects* semantics.

**Comment by neilpa** [comment]
I would take this a step further to say that `PropertyType` should conform to both `SignalType` and `SignalProducerType`.

**Comment by NachoSoto** [comment]
Yes, absolutely! But that's going to require higher-kinded types so that things like `SignalType.map` can return `Self<Value, Error>`.

**Comment by neilpa** [comment]
Nope, [`SignalType` exposes `signal: Signal<Value, Error>`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/49d75631c0daf4c470cb5d9c5efb8b1d19aab05c/ReactiveCocoa/Swift/Signal.swift#L144-L156) and doesn't use `Self` because of that.

**Comment by NachoSoto** [comment]
> I would take this a step further to say that `PropertyType` should conform to both `SignalType` and `SignalProducerType`.

What I mean is that operators, like `map`, [are implemented on `SignalType`, but they can't return `Self<Value, Error>`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L214).

If `PropertyType` were to conform to `SignalType`, for example, doing `property.map` would return a `Signal`, which is wrong. It should return another property of the same type.

That's why I'm saying that unfortunately what you suggest is not possible right now.

**Comment by neilpa** [comment]
> they incorrectly return Signal.

I wouldn't call this incorrect given that this is a language limitation and there's nothing we can do to workaround it.

**Comment by NachoSoto** [comment]
For sure, hence the italic :)

**Comment by paulyoung** [comment]
It was originally brought up in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2146. I wish I had this all the time but never got around to it.

**Comment by NachoSoto** [comment]
@neilpa do you have any further thoughts on this?

Given that, as I explained, we can't make it conform to `SignalType` yet, seems like an appropriate temporary solution to simply add a `Signal`.

This isn't blocking `4.0` though, of course.

**Comment by neilpa** [comment]
Nope, we should just go ahead and add it.
