### ISSUE TITLE
Why I can't find ```RACObserver```

### ISSUE THREAD

**Issue by AntiMoron** [ReactiveCocoa/ReactiveCocoa#2546]
I'm using ReactiveCocoa version ```2.5```
codes written in ```swift 2.0```

I can't find ```RACObserver```,is it replaced by some other implementation?
I'm new to this library,give me some clue plz.

**Comment by CosynPa** [comment]
Did you mean RACObserve? It's a macro, and can't be used in Swift. Use rac_valuesForKeyPath:observer: instead.

**Comment by greyspot09** [comment]
This should be helpful to you [Swift-RAC-Macros](https://github.com/ashfurrow/Swift-RAC-Macros/blob/master/ReactiveCocoaBindings.swift)

**Comment by AntiMoron** [comment]
thx guys,I solved my problem.
