### ISSUE TITLE
timer slowing down 

### ISSUE THREAD

**Issue by ohbargain** [ReactiveCocoa/ReactiveCocoa#2552]
Hi, 

I was using timer function to update code and found out that the interval fluctuated after a short while. 
I am using swift2 branch and I was going to use this to update write and read from NSStream that connects to another device via tcp.

This is my test code:

    var lastTime = CACurrentMediaTime()
            
    self.disposables +=
        timer(0.1, onScheduler: QueueScheduler.mainQueueScheduler)
            .startWithNext {  _ in
                let now = CACurrentMediaTime()
                let elapsed = now - lastTime
                print("elapsed: \(elapsed)")
                lastTime = now                        
            }

For first minute, the console looks like this:

    elapsed: 0.101776816998608
    elapsed: 0.10644376900018
    elapsed: 0.0976122470019618
    elapsed: 0.100516430000425
    elapsed: 0.0964744779994362
    elapsed: 0.0976001640010509
    elapsed: 0.103091541997856
    elapsed: 0.128684066999995
    elapsed: 0.102833709999686
    elapsed: 0.0651955749999615
    elapsed: 0.106709908999619

After a while, the console looks like this:

    elapsed: 0.0967637920039124
    elapsed: 0.968163173994981
    elapsed: 1.01991867900506
    elapsed: 0.0110245599935297
    elapsed: 1.17587676100084
    elapsed: 0.0242212410012144
    elapsed: 0.769977828000265
    elapsed: 0.0300382109999191
    elapsed: 0.418253449002805
    elapsed: 0.117165812996973
    elapsed: 0.114252193001448
    elapsed: 0.319600923998223
    elapsed: 2.02189024600375
    elapsed: 0.977711211999122
    elapsed: 0.0311842459996114
    elapsed: 0.968759989002137

I have tried to put the code in different scheduler and the result is similar.

Is this a expected behaviour and should I go with other approach? 

I'd appreciate it if anyone could suggest different approach.

**Comment by ohbargain** [comment]
I was running 10.11.2 beta3 when this happened. After reverting back to stable release (10.11.1). The problem went away. Closing this.

**Comment by NachoSoto** [comment]
This might be something we want to file a radar for though.
