### ISSUE TITLE
Build failed on Debug but not on Release

### ISSUE THREAD

**Issue by rizumita** [ReactiveCocoa/ReactiveCocoa#2555]
I tried building a framework linked RAC4 installed by Carthage.
Xcode built failed on Debug configuration with the following message. But on Release configuration, Xcode succeeded in building.
```
Undefined symbols for architecture arm64:
  "direct generic type metadata pattern for ReactiveCocoa.MutableProperty", referenced from:
      type metadata accessor for ReactiveCocoa.MutableProperty<Swift.Bool> in Todoist.o
  "ReactiveCocoa.MutableProperty.__allocating_init <A> (ReactiveCocoa.MutableProperty<A>.Type)(A) -> ReactiveCocoa.MutableProperty<A>", referenced from:
      TodoistKit.Todoist.authorize (TodoistKit.Todoist)(cliendID : Swift.String, scope : Swift.String, logIn : ReactiveCocoa.Action<__ObjC.NSURL, (code : Swift.String, state : Swift.String), __ObjC.NSError>) -> () in Todoist.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

How do I build the framework with RAC4 on Debug configuration?

**Comment by ikesyo** [comment]
Would you mind sharing `Todoist.swift` source or another minimized reproducible case?

**Comment by rizumita** [comment]
Todoist.swift is the following.
```
import Foundation
import ReactiveCocoa
public struct Todoist {
    public static let sharedInstance = Todoist()
    func f() {
        _ = MutableProperty(true)
    }
}
```

The error occurred by this minimum code.

I did
1. Create iOS Framework project by Xcode
2. Create Cartfile 
3. Run `carthage update`
4. Add frameworks to Linked Frameworks of the project.
5. Create Todoist.swift
6. Build

Cartfile
```
github "ReactiveCocoa/ReactiveCocoa" "v4.0.0-alpha.3"
github "Alamofire/Alamofire" ~> 3.0
github "LoganWright/Genome"
github "kishikawakatsumi/KeychainAccess"
github "CocoaLumberjack/CocoaLumberjack"
```

**Comment by rizumita** [comment]
I cloned master branch of RAC and I built and archived this by Carthage.
I replaced RAC framework occurred the error with the archived framework, then Xcode built my project successfully.

**Comment by rizumita** [comment]
@ikesyo 
I ran 'carthage update' after I remove 'DerivedData' folder, then my project got built successfully.
