### ISSUE TITLE
ReactiveCocoa 4 release date

### ISSUE THREAD

**Issue by anton-matosov** [ReactiveCocoa/ReactiveCocoa#2556]
What is the planned date for ReactiveCocoa 4 release, if any?

**Comment by ramirez** [comment]
No date planned yet?

**Comment by jakecraige** [comment]
I'm not sure how strict they are doing milestones but there is a [milestone with open issues](https://github.com/ReactiveCocoa/ReactiveCocoa/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0)

**Comment by eimantas** [comment]
All issues are resolved and from recent pull requests it seems that they're hunting typos in the documentation.

@NachoSoto - any update on this issue? May be a date?

**Comment by NachoSoto** [comment]
I'd love to get #2639 in. Other than that I think we're ready for an official 4.0 release :D

**Comment by mdiep** [comment]
What about #2640?

**Comment by NachoSoto** [comment]
Agreed, I put that in `4.0` and added `Help Wanted`. I can do it if I have some free time, but help is welcome!

**Comment by mdiep** [comment]
Both #2639 and #2640 are in. :sparkles:

**Comment by NachoSoto** [comment]
I'll make a release this evening! :dancer:

**Comment by eimantas** [comment]
This can probably be closed now? RC2 release notes have a week deadline for bugs before the final release .)

**Comment by NachoSoto** [comment]
Yup. I have an event in my calendar to make the final release next Wednesday, as long as no major issues are found :tada:
