### ISSUE TITLE
Carthage zip missing .bcsymbolmap file

### ISSUE THREAD

**Issue by tomtaylor** [ReactiveCocoa/ReactiveCocoa#2558]
Carthage 0.9.4 and later support Bitcode, and include a `.bcsymbolmap` file to map the symbols to whatever is going on inside Bitcode. The current 4.0.0-alpha.3 zip file is missing it, so if you try and archive and submit to Apple you'll get a message about a missing `1290D3C6-C985-36B4-9511-5CD12AD9FF5B.bcsymbolmap` file.

**Comment by NachoSoto** [comment]
Thanks!

We'll make sure to use Carthage 0.10 for the next release :)

**Comment by eimantas** [comment]
Just to clear up - if I build the RAC with Carthage and get the bcsymbolmap file - should I copy it as an iOS bundle resource?

**Comment by ikesyo** [comment]
We are now including `bcsymbolmap` files. Closing.

> Just to clear up - if I build the RAC with Carthage and get the bcsymbolmap file - should I copy it as an iOS bundle resource?

`carthage copy-frameworks` copies the `bcsymbolmap`s as well, so you don't need to worry about it.

**Comment by eimantas** [comment]
👍
