### ISSUE TITLE
`scan` and initial value

### ISSUE THREAD

**Issue by mbrandonw** [ReactiveCocoa/ReactiveCocoa#2561]
I think it's pretty common for reactive frameworks to implement `scan` so that it immediately emits its initial value, e.g. the whole Rx family. This is very useful for setting up initial state. To me it's the FRP way of getting around putting display code in a function that gets called when the view is initialized and then again when things start happening.

Here's an example for a producer, but I would expect it to be the same for signals:

```swift
SignalProducer<Int, NoError>(values: [1, 2, 3]).scan(0, +).start { print($0) }
```

That prints `1, 3, 6` where I would expect `0, 1, 3, 6`.

Thoughts on changing `scan` to have this behavior?

**Comment by neilpa** [comment]
> I think it's pretty common for reactive frameworks to implement scan so that it immediately emits its initial value, e.g. the whole Rx family.

Nope, other Rx libraries [implement `scan` the same way](http://www.introtorx.com/Content/v1.0.10621.0/07_Aggregation.html#Scan).

> That prints `1, 3, 6` where I would expect `0, 1, 3, 6`.

How would this work in the general case? Remember that the type signature for the accumulator is `(U, T) -> U`. In your example both `T` and `U` are of type `Int` so it's easy to think that we can generate an initial `0` value. However, there are many other cases where `T` is another type that isn't default constructible so we have to wait for the first value from the signal.

**Comment by mbrandonw** [comment]
Ah, did not check Rx .NET, but it is indeed true that `scan` works as I described in RxJS and RxJava:

http://reactivex.io/documentation/operators/scan.html

<img width="640" alt="scanseed" src="https://cloud.githubusercontent.com/assets/135203/11279425/9605e87e-8ebe-11e5-84bf-463ae444b09b.png">

Not quite sure I understand your hypothetical. `scan` currently needs an initial value (which would be of type `T` in your terms), so this wouldn't add any more restrictions. 

The general case is to simply emit `initial` value immediately and then the first accumulation after the signal emits for the first time.

**Comment by NachoSoto** [comment]
You can always start emitting that value:

```swift
let producer = SignalProducer<Int, NoError>(values: [1, 2, 3])
SignalProducer<Int, NoError>(value: 0)
    .concat(producer)
    .scan(0, +)
    .start { print($0) }
```

You can simplify this even more by creating a simple `startWith` operator as well.

Personally I don't have a preference, I think if we were to change this some people would want the opposite behavior and they'd need `.skip(1)`.

What I do feel strongly about is avoiding a second operator to cover both options, since the opposite one can be easily accomplished.

**Comment by neilpa** [comment]
> Not quite sure I understand your hypothetical. scan currently needs an initial value (which would be of type `T` in your terms)

Nope, it's of type `U` which is the value you're accumulating. A better name than "initial value" is really the "accumulator seed".

> Personally I don't have a preference, I think if we were to change this some people would want the opposite behavior and they'd need .skip(1).

I do have a strong preference for not changing this. There should be a 1-1 mapping for values on the input to emitted values on the output when `scan`ning. This is especially important and obvious with empty signals where you wouldn't expect that to generate an output value.

**Comment by NachoSoto** [comment]
> I do have a strong preference for not changing this. There should be a 1-1 mapping for values on the input to emitted values on the output when scanning. This is especially important and obvious with empty signals where you wouldn't expect that to generate an output value.

Makes sense :+1:

**Comment by mdiep** [comment]
Makes sense to me too :+1:

**Comment by kastiglione** [comment]
Interestingly, RxJava [overloads `scan`](http://reactivex.io/RxJava/javadoc/rx/Observable.html#scan(rx.functions.Func2)).

```java
Observable<T> scan(Func2<T,T,T> accumulator);
Observable<R> scan(R initialValue, Func2<R,? super T,R> accumulator);
```

**Comment by mbrandonw** [comment]
> Nope, it's of type U which is the value you're accumulating. A better name than "initial value" is really the "accumulator seed".

Our `U`s and `T`s are a little mixed up. Roughly thinking of scan as  `scan(Signal<U>, T, (T, U) -> T) -> Signal<T>` I don't see any constructibility problems with `T` as by definition we are given one from the outset. That is the value I expected to be emitted immediately.

After thinking about it a bit I do see there is a problem with this definition of `scan` on `Signal` that is specific to Reactive Cocoa's separation of cold and hot. By emitting the initial value immediately no one could observe that value. So this is something that could only live in a producer, and so definitely not worth the change. 

I will close this issue now. Thanks for the discussion.
