### ISSUE TITLE
ActionType for protocol extension?

### ISSUE THREAD

**Issue by danishin** [ReactiveCocoa/ReactiveCocoa#2564]
I'm looking for a way to extend `Action` with protocol extension like we can with `SignalProducerType` / `SignalType`. Something like the following:

```
extension Action where Error == NoError {
  func exec(input: Input) -> SignalProducer<Ouput, Error> { 
    apply(input).flatMapError { _ in SignalProducer<Input, NoError>.empty }
  }
}
```
But it won't work since AFAIK, swift doesn't support constraining by type parameters (but only through abstract types). 

How should I go about doing this? Should I implement custom `protocol` like `ActionType` for wrapping `Action` class?

**Comment by NachoSoto** [comment]
I don't see why we shouldn't have `ActionType`, seems like a good idea!
