### ISSUE TITLE
Cocoapods spec versions RAC4 beta

### ISSUE THREAD

**Issue by startupthekid** [ReactiveCocoa/ReactiveCocoa#2566]
The latest release on this repo is listed as `v4.0.0-alpha-3` but if you do a search for ReactiveCocoa on the Cocoapods website, the latest version that comes up is `v4.0.4-alpha-1`. Now I know that the podspecs for RC have always been added by 3rd parties so I presume that's why the version discrepancies. What I find most odd, and slightly irksome, is that `4.0.4` doesn't include a lot of the changes from `4.0.0` such as renaming error to failed, etc.

My questions are:

1) Who's responsible for adding the podspecs and why is the cocoapod on such a different version from the master repo?
2) Is the latest version still stand at `4.0.0-alpha-3`?
3) I have no experience with Carthage and I assume you guys have a good reason for using it over Cocoapods. However in the future, would it be possible for the ReactiveCocoa team to be the only ones generating the podspec and pushing to Trunk so that version discrepancies like this don't happen in the future?

**Comment by NachoSoto** [comment]
> 2) Is the latest version still stand at 4.0.0-alpha-3?

The source of truth for `ReactiveCocoa` releases [**is this repository**](https://github.com/ReactiveCocoa/ReactiveCocoa/releases). So the latest version as of today, is `4.0.0-alpha.3`.

>  would it be possible for the ReactiveCocoa team to be the only ones generating the podspec and pushing to Trunk so that version discrepancies like this don't happen in the future?

We're not interested in maintaining [a duplicated configuration file](https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/2.3.1/ReactiveCocoa.podspec.json). The source of truth is this repository and the Xcode project contained within it.

However, somebody (not sure who that is at the moment) is already maintaining a 3rd-party pod spec for `RAC` :)

**Comment by startupthekid** [comment]
Not only maintaining a 3rd-party pod but apparently they're in the future, given by what version their on ;)

Good to know though where the source of truth lies, much less confusing.

**Comment by NachoSoto** [comment]
> Not only maintaining a 3rd-party pod but apparently they're in the future, given by what version their on ;)

AFAIK that's because they needed to update the `podspec` to correct something, so they needed to bump the version.
