### ISSUE TITLE
Writing a Scheduler dedicated to CoreData actions 

### ISSUE THREAD

**Issue by Palleas** [ReactiveCocoa/ReactiveCocoa#2567]
Hello, 

I'm working on an application in which I'm inserting/updating data using CoreData. To make sure CoreData doesn't explode in my face, I wrote a Scheduler dedicated to performing CoreData actions, using the `performBlock` method.

```swift
class PersistenceScheduler: SchedulerType {
    let context: NSManagedObjectContext

    init(context: NSManagedObjectContext) {
        self.context = context
    }
    
    func schedule(action: () -> ()) -> Disposable? {
        let disposable = SimpleDisposable()
        
        context.performBlock { () -> Void in
            guard !disposable.disposed else {
                return
            }
            
            action()
        }
        return disposable
    }
}
```

I'm using it like this, where the `client.fetchShows()` method returns a stream of TV Shows resulting from a call to a webservice : 

```swift
let importScheduler = PersistenceScheduler(context: importMoc)
return client
            .fetchShows()
            .flatMap(FlattenStrategy.Latest, transform: { (show) -> SignalProducer<StoredShow, NSError> in
                return SignalProducer { observable, disposable in
                    observable.sendNext(StoredShow.showInContext(importMoc, mappedOnShow: show))
                    observable.sendCompleted()
                }.startOn(importScheduler)
            })
```

As you can see there is nothing really fancy. The problem I have is that my `action` is never performed because my `SimpleDisposable` is marked as disposed by the time the block passed to `performBlock` is executed.

Any idea? Am I missing something in my Scheduler? I've based my implementation on the QueueScheduler that works pretty much the same way.

The whole application is [available here](http://github.com/palleas/rewatch) and specifically my [DownloadController](https://github.com/Palleas/Rewatch/blob/master/Rewatch/Domain/DownloadController.swift#L42-L73)

Thanks for your help, please let me know if I can provide more context.

**Comment by NachoSoto** [comment]
The implementation of the `SchedulerType` looks perfectly correct to me (and I love the idea btw!), so I'm not sure what can be going on.

The only thing I can think of is that `fetchShows` is emitting more than one value, which is making `.Latest` dispose the prior `SignalProducer`.

Can you try adding `.on(next:)` to debug that?
```swift
return client
            .fetchShows()
            .on(next: { print("Received shows: \(shows)" }) // does this print more than one value?
            .flatMap(FlattenStrategy.Latest, transform: { (show) -> SignalProducer<StoredShow, NSError> in
                    ...
            })
```

**Comment by Palleas** [comment]
Indeed, I'm getting multiple values (I added an emoji because I'm **that** fun in real life):
```
💣 Received shows: Show(id: 5010, name: "Arrow")
💣 Received shows: Show(id: 159, name: "Doctor Who (2005)")
💣 Received shows: Show(id: 7942, name: "Gotham")
💣 Received shows: Show(id: 8857, name: "How to Get Away with Murder")
💣 Received shows: Show(id: 5878, name: "Marvel\'s Agents of S.H.I.E.L.D.")
💣 Received shows: Show(id: 6001, name: "Orange Is the New Black")
💣 Received shows: Show(id: 10881, name: "The Delivery Man")
💣 Received shows: Show(id: 8339, name: "The Flash (2014)")
💣 Received shows: Show(id: 5986, name: "Under the Dome")
```

Does this mean I'm using the wrong Flatten Strategy then?

**Comment by NachoSoto** [comment]
> Does this mean I'm using the wrong Flatten Strategy then?

No! `.Latest` can be appropriate if that's the semantic you're looking for :) but what that means is that the `SignalProducer` created for all shows, until the last one, will be disposed. The only one that shouldn't be is `5986`. Is that what you're observing?

If you want to emit `StoredShow` results for all shows you might want to consider using `.Concat`, if you care about the order, or .`Merge` if you don't.

**Comment by Palleas** [comment]
> The only one that shouldn't be is 5986. Is that what you're observing?
Yup! 

I replaced the ".Latest" with ".Merge" because indeed I don't really care about the order. The import seems to be working smoothly but I didn't perform any extended tests. My Scheduler issue seems to be fixed though. Thanks a lot!

**Comment by NachoSoto** [comment]
Awesome!
