### ISSUE TITLE
observe producer of MutableProperty on UIScheduler()

### ISSUE THREAD

**Issue by aloco** [ReactiveCocoa/ReactiveCocoa#2568]
Hi,

I am facing a weird issue, not sure of the cause - maybe it´s my faulty understanding of concepts and therefore a noob question. Anyway, I hope someone can help me out here ✌🏼.

I want to observe a `MutableProperty` and therefore update some UI related stuff on `Next` events. So I went with this:

```        
listViewModel.listProperty.producer.observeOn(UIScheduler()).startWithNext { [weak self] list in
    self?.preselectListItem()
}
```
 `preselectListItem()` determines the index of my current item within the `list` and selects the related `NSIndexPath` of a `UITableView`. 

The value of `listProperty` can be set by various threads. To ensure that `preselectListItem` is always called on the main thread, I added `observeOn(UIScheduler())` 

BUT, the tableView does not update visually (but the method is called). To test things, I added the following and the tableView updates correctly:
```        
listViewModel.listProperty.producer.observeOn(UIScheduler()).startWithNext { [weak self] list in
    dispatch_async(dispatch_get_main_queue()) {
        self?.preselectWifi()
    }
}
```
I compared the calling threads and although they are both `Thread 1` the queue name is different.

without dispatch_get_main_queue
![screen shot 2015-11-23 at 16 11 31](https://cloud.githubusercontent.com/assets/11661125/11340752/ba570c96-91ff-11e5-9651-f13ae920ca13.png)
with dispatch_get_main_queue
![screen shot 2015-11-23 at 16 31 45](https://cloud.githubusercontent.com/assets/11661125/11340758/c45fbd8c-91ff-11e5-8c66-77c6a6e87553.png)

I am not sure if that makes a difference, but in fact that the tableView only gets updated by adding `dispatch_get_main_queue` something is wrong here 🤔. 

PS: In my testcase, the value of `listProperty` is set from the main thread

**Comment by NachoSoto** [comment]
The baking queue doesn't make a difference.

Is the `preselectWifi` being called in the first case? Something else has to be happening. It's possible that you have a race condition (we can't know without looking at the rest or the code), and the extra run-loop jump works around it.

**Comment by aloco** [comment]
Hi thanks a lot for the fast response. During the creation of a reduced demo testproject I figured out what went wrong. There is also an `Action` which pulls the list from a server. As a side effect, the value of `listProperty` is set within this `Action`. Unfortunately, I reload the tableView within the `action.apply().startWithNext` callback and since the value of `listProperty` is set as side effect, it fires before the reload happened 🙈(at that moment the tableView has no content). As you said, the extra run-loop jump worked around this 😁 Thanks for the hint!
