### ISSUE TITLE
Trouble integrating ReactiveCocoa with a WatchOS App

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2581]
Hello, 
I've bee trying to get ReactiveCocoa into a new project for WatchOS but had some issues with the build.
Is there any known issues with that at this time? 
is there a good resource to learn more if things are different with WatchOS and ReactiveCocoa ?

Thank you

**Comment by NachoSoto** [comment]
> Is there any known issues with that at this time? 

There are no known issues at the time. I'm personally using it myself for a watch OS 2 app.

> is there a good resource to learn more if things are different with WatchOS and ReactiveCocoa ?

Nothing should be different in `RAC` for `watchOS`. If you can provide some more details about the troubles you're encountering we can help :)

**Comment by edwardIshaq** [comment]
So here is the first Issue i was having.
Including it with the iOS App for start:
1- I added the Carthage/build/iOS/ReactiveCocoa.framework + Result.framework. to the 
2- Added the script to the build phase

for some reason the compiler is complaining about the version under: 
Carthage/Build/watchOS
which is not the one I've added to the project as I mentioned in step (1)

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/edward/Workspace/Swift/Tennis/Carthage/Build/watchOS/ReactiveCocoa.framework/Headers/ReactiveCocoa.h"
        ^
/Users/edward/Workspace/Swift/Tennis/Carthage/Build/watchOS/ReactiveCocoa.framework/Headers/ReactiveCocoa.h:67:10: error: 'ReactiveCocoa/MKAnnotationView+RACSignalSupport.h' file not found
        #import <ReactiveCocoa/MKAnnotationView+RACSignalSupport.h>
                ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```

**Comment by NachoSoto** [comment]
Can you try removing your derived data directory and trying to build again?

**Comment by edwardIshaq** [comment]
I just tried that i'm still getting the same error:
```<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/edward/Workspace/Swift/Tennis/Carthage/Build/watchOS/ReactiveCocoa.framework/Headers/ReactiveCocoa.h"
        ^
/Users/edward/Workspace/Swift/Tennis/Carthage/Build/watchOS/ReactiveCocoa.framework/Headers/ReactiveCocoa.h:67:10: error: 'ReactiveCocoa/MKAnnotationView+RACSignalSupport.h' file not found
        #import <ReactiveCocoa/MKAnnotationView+RACSignalSupport.h>
                ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```

I also tried adding the WatchOS to the Watch extension target had other issues as well..

**Comment by edwardIshaq** [comment]
btw, I started a new project, reactiveCocoa iOS worked fine on the app.
on the WatchApp:
1- i added the WatchOS frameworks to the watch-extension target.
2- added the run-script

```
dyld: Library not loaded: @rpath/libswiftCoreImage.dylib
  Referenced from: /Users/edward/Library/Developer/CoreSimulator/Devices/B8520D30-23E9-4551-BE18-B17E30804C53/data/Containers/Bundle/Application/4B4A6E87-AE87-47E8-B84A-9C94E5232E9D/edward.ishaq.Untouched.watchkitapp.app/PlugIns/Untouched WatchKit Extension.appex/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Reason: image not found
```

**Comment by NachoSoto** [comment]
The library not loaded problem is because you need to embed the framework in the target, probably using [`copy-frameworks`](https://github.com/Carthage/Carthage#if-youre-building-for-ios).

Since a fresh project is working fine I'm inclined to say that you're existing project is misconfigured. Since it's trying to import the wrong file, I think you have [the wrong `TARGETED_DEVICE_FAMILY`](https://github.com/jspahrsummers/xcconfigs/blob/master/watchOS/watchOS-Base.xcconfig#L15) on your `watchOS` target.

**Comment by edwardIshaq** [comment]
So your comment makes sense:
I looked at the copy-frameworks and you're right I AM copying the iOS files (copy-paste)  
so I changed it to:
$(SRCROOT)/Carthage/Build/watchOS/ReactiveCocoa.framework
$(SRCROOT)/Carthage/Build/watchOS/Result.framework

but now it compiles and tries to start running when I get this error:
```
dyld: Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: /Users/edward/Library/Developer/CoreSimulator/Devices/B8520D30-23E9-4551-BE18-B17E30804C53/data/Containers/Bundle/Application/1BA2B1E6-A82C-453D-BF92-63713179BE15/edward.ishaq.Untouched.watchkitapp.app/PlugIns/Untouched WatchKit Extension.appex/Untouched WatchKit Extension
  Reason: image not found
```

Do i need to change something in the *run Search path* ? 
which is currently configured: 
$(inherited)
executable_path/Frameworks
executable_path/../Frameworks

**Comment by edwardIshaq** [comment]
Looking into the **Frameworks** folder under the path above shows these frameworks.

* libswiftCore.dylib
* libswiftCoreGraphics.dylib
* libswiftCoreLocation.dylib
* libswiftDarwin.dylib
* libswiftDispatch.dylib
* libswiftFoundation.dylib
* libswiftObjectiveC.dylib
* libswiftUIKit.dylib
* libswiftWatchKit.dylib

so I tries to include the frameworks in **Embedded Binaries** 
I'm still getting the same message as above. It sounds like path problem. Isn't that what *rpath* is all about? pointing to the location of the frameworks at runtime ?

**Comment by mdiep** [comment]
This is pretty old, so I'm going to close it. Feel free to reopen if you're still having trouble.
