### ISSUE TITLE
"This application is modifying the autolayout engine from a background thread..."

### ISSUE THREAD

**Issue by ton03** [ReactiveCocoa/ReactiveCocoa#2584]
Hi,

I have the ff. versions:
- Swift version `2.1 (swiftlang-700.1.101.6 clang-700.1.76)`,
- Xcode version `7.1.1 (7B1005)`, and
- ReactiveCocoa `v4.0.0-alpha.4`

I understand that I'm using an alpha version of ReactiveCocoa, but I was only planning on using simple functionalities. I just wanted a stable (or stable enough) version for Swift 2.1. If anyone could suggest a version I could use that would fix this issue, it would be very awesome and much appreciated. :)

Anyway, this is the warning I'm getting, and this delays some view changes that should happen when properties in the view model changes

    2015-12-02 11:05:59.028 My_Project [291:24217] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
     Stack:(
        0   CoreFoundation                      0x000000018537cf60 <redacted> + 148
        1   libobjc.A.dylib                     0x0000000199f2ff80 objc_exception_throw + 56
        2   CoreFoundation                      0x000000018537ce90 <redacted> + 0
        3   Foundation                          0x000000018639b2d8 <redacted> + 88
        4   Foundation                          0x0000000186221a1c <redacted> + 56
        5   Foundation                          0x000000018621d5dc <redacted> + 260
        6   UIKit                               0x000000018b173158 <redacted> + 964
        7   UIKit                               0x000000018b17457c <redacted> + 788
        8   UIKit                               0x000000018b243740 <redacted> + 480
        9   UIKit                               0x000000018b240708 <redacted> + 172
        10  UIKit                               0x000000018b240978 <redacted> + 96
        11  UIKit                               0x000000018b240e3c <redacted> + 80
        12  UIKit                               0x000000018b2453d0 <redacted> + 492
        13  UIKit                               0x000000018b24453c <redacted> + 148
        14  UIKit                               0x000000018b24447c <redacted> + 284
        15  UIKit                               0x000000018ad74d40 <redacted> + 444
        16  UIKit                               0x000000018ad74e14 <redacted> + 60
        17  UIKit                               0x000000018ad74f54 <redacted> + 28
        18  UIKit                               0x000000018ad74504 <redacted> + 100
        19  UIKit                               0x000000018a910098 <redacted> + 996
        20  UIKit                               0x000000018a90fc9c <redacted> + 28
        21  UIKit                               0x000000018ac8f184 <redacted> + 108
        22  UIKit                               0x000000018ac882d4 <redacted> + 1328
        23  UIKit                               0x000000018ac89d94 <redacted> + 4644
        24  UIKit                               0x000000018ac8c800 <redacted> + 472
        25  UIKit                               0x000000018aa09ea0 <redacted> + 184
        26  My_Project                          0x000000010001897c _TFFC12My_Project19LoginViewController20setLoginButtonStatusFS0_FOOS_8ZMStatus5LoginT_L_9showAlertfTSS7messageSS_T_ + 648
        27  My_Project                          0x0000000100014944 _TFC12My_Project19LoginViewController20setLoginButtonStatusfS0_FOOS_8ZMStatus5LoginT_ + 1268
        28  My_Project                          0x00000001000185c4 _TFFC12My_Project19LoginViewControllerP33_0F2BE433B04F21AD1BCFFDB4160B2DAA11initSignalsFS0_FT_T_U0_FOOS_8ZMStatus5LoginT_ + 320
        29  My_Project                          0x0000000100018478 _TTRXFo_dOO12My_Project8ZMStatus5Login_dT__XFo_iS1__dT__ + 36
        30  ReactiveCocoa                       0x000000010020cea0 _TTRGRq_13ReactiveCocoa18SignalProducerType_XFo_iqq_S0_1T_dT__XFo_iqq_S0_1T_iT__ + 40
        31  ReactiveCocoa                       0x00000001001a9494 _TFZFO13ReactiveCocoa5Event4sinku0_Rq0_Ss9ErrorType_FMGS0_q_q0__FT5errorGSqFq0_T__9completedGSqFT_T__11interruptedGSqFT_T__4nextGSqFq_T___FGS0_q_q0__T_U_FGS0_Q_Q0__T_ + 640
        32  ReactiveCocoa                       0x00000001001a71b0 _TPA__TFZFO13ReactiveCocoa5Event4sinku0_Rq0_Ss9ErrorType_FMGS0_q_q0__FT5errorGSqFq0_T__9completedGSqFT_T__11interruptedGSqFT_T__4nextGSqFq_T___FGS0_q_q0__T_U_FGS0_Q_Q0__T_ + 264
        33  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        34  ReactiveCocoa                       0x00000001001d7b08 _TFFC13ReactiveCocoa6Signalcu0_Rq0_Ss9ErrorType_FMGS0_q_q0__FFFGOS_5Eventq_q0__T_GSqPS_10Disposable__GS0_q_q0__U_FGS2_Q_Q0__T_ + 1752
        35  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        36  ReactiveCocoa                       0x00000001001d802c _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___iT__XFo_iGS1_q_q0___dT__ + 40
        37  ReactiveCocoa                       0x000000010020c994 _TFFV13ReactiveCocoa14SignalProducer15startWithSignalu0_Rq0_Ss9ErrorType_FGS0_q_q0__FFTGCS_6Signalq_q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 388
        38  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        39  ReactiveCocoa                       0x000000010020ac78 _TFFZFV13ReactiveCocoa14SignalProducer6bufferu0_Rq0_Ss9ErrorType_FMGS0_q_q0__FTSi_TGS0_q_q0__FGOS_5Eventq_q0__T__U0_FGS2_Q_Q0__T_U_FT_T_ + 1100
        40  ReactiveCocoa                       0x00000001001961cc _TTRXFo__dT__XFdCb__dT__ + 44
        41  libdispatch.dylib                   0x0000000101481c68 _dispatch_client_callout + 16
        42  libdispatch.dylib                   0x000000010148d81c _dispatch_barrier_sync_f_invoke + 164
        43  ReactiveCocoa                       0x000000010020a768 _TFZFV13ReactiveCocoa14SignalProducer6bufferu0_Rq0_Ss9ErrorType_FMGS0_q_q0__FTSi_TGS0_q_q0__FGOS_5Eventq_q0__T__U0_FGS2_Q_Q0__T_ + 776
        44  ReactiveCocoa                       0x00000001001a8d4c _TF13ReactiveCocoa8sendNextu0_Rq0_Ss9ErrorType_FTFGOS_5Eventq_q0__T_q__T_ + 252
        45  ReactiveCocoa                       0x00000001001b5434 _TFC13ReactiveCocoa15MutablePropertys5valueq_ + 280
        46  My_Project                          0x00000001000320d8 _TFFC12My_Project14LoginViewModel18validateLoginInputFS0_FT_T_U_FPSs9AnyObject_T_ + 2160
        47  My_Project                          0x00000001000336a4 _TTRXFo_oPSs9AnyObject__dT__XFo_iPS___dT__ + 32
        48  ReactiveCocoa                       0x000000010020cea0 _TTRGRq_13ReactiveCocoa18SignalProducerType_XFo_iqq_S0_1T_dT__XFo_iqq_S0_1T_iT__ + 40
        49  ReactiveCocoa                       0x00000001001a9494 _TFZFO13ReactiveCocoa5Event4sinku0_Rq0_Ss9ErrorType_FMGS0_q_q0__FT5errorGSqFq0_T__9completedGSqFT_T__11interruptedGSqFT_T__4nextGSqFq_T___FGS0_q_q0__T_U_FGS0_Q_Q0__T_ + 640
        50  ReactiveCocoa                       0x00000001001a71b0 _TPA__TFZFO13ReactiveCocoa5Event4sinku0_Rq0_Ss9ErrorType_FMGS0_q_q0__FT5errorGSqFq0_T__9completedGSqFT_T__11interruptedGSqFT_T__4nextGSqFq_T___FGS0_q_q0__T_U_FGS0_Q_Q0__T_ + 264
        51  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        52  ReactiveCocoa                       0x00000001001d7b08 _TFFC13ReactiveCocoa6Signalcu0_Rq0_Ss9ErrorType_FMGS0_q_q0__FFFGOS_5Eventq_q0__T_GSqPS_10Disposable__GS0_q_q0__U_FGS2_Q_Q0__T_ + 1752
        53  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        54  ReactiveCocoa                       0x00000001001d802c _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___iT__XFo_iGS1_q_q0___dT__ + 40
        55  ReactiveCocoa                       0x000000010020c994 _TFFV13ReactiveCocoa14SignalProducer15startWithSignalu0_Rq0_Ss9ErrorType_FGS0_q_q0__FFTGCS_6Signalq_q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 388
        56  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        57  ReactiveCocoa                       0x00000001001d7b08 _TFFC13ReactiveCocoa6Signalcu0_Rq0_Ss9ErrorType_FMGS0_q_q0__FFFGOS_5Eventq_q0__T_GSqPS_10Disposable__GS0_q_q0__U_FGS2_Q_Q0__T_ + 1752
        58  ReactiveCocoa                       0x00000001001d89ac _TFFFeRq_13ReactiveCocoa10SignalType_S_S0_3mapu__Rq_S0__Fq_FFqq_S0_1Tqd__GCS_6Signalqd__qq_S0_1E_U_FFGOS_5EventQ_QQPS0_1E_T_GSqPS_10Disposable__U_FGS2_QS3_1TS4__T_ + 252
        59  ReactiveCocoa                       0x00000001001d703c _TPA__TFFFeRq_13ReactiveCocoa10SignalType_S_S0_3mapu__Rq_S0__Fq_FFqq_S0_1Tqd__GCS_6Signalqd__qq_S0_1E_U_FFGOS_5EventQ_QQPS0_1E_T_GSqPS_10Disposable__U_FGS2_QS3_1TS4__T_ + 208
        60  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        61  ReactiveCocoa                       0x00000001001d7b08 _TFFC13ReactiveCocoa6Signalcu0_Rq0_Ss9ErrorType_FMGS0_q_q0__FFFGOS_5Eventq_q0__T_GSqPS_10Disposable__GS0_q_q0__U_FGS2_Q_Q0__T_ + 1752
        62  ReactiveCocoa                       0x00000001001d81b0 _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___dT__XFo_iGS1_q_q0___iT__ + 36
        63  ReactiveCocoa                       0x00000001001d802c _TTRG0_Rq0_Ss9ErrorType_XFo_iGO13ReactiveCocoa5Eventq_q0___iT__XFo_iGS1_q_q0___dT__ + 40
        64  ReactiveCocoa                       0x000000010020c994 _TFFV13ReactiveCocoa14SignalProducer15startWithSignalu0_Rq0_Ss9ErrorType_FGS0_q_q0__FFTGCS_6Signalq_q0__PS_10Disposable__T_T_U0_FGOS_5EventQ_Q0__T_ + 388
        65  ReactiveCocoa                       0x00000001001ac6e4 _TTRXFo_iGO13ReactiveCocoa5EventTCSo6NSDataCSo13NSURLResponse_CSo7NSError__dT__XFo_oGS0_TS1_S2__S3___dT__ + 44
        66  ReactiveCocoa                       0x00000001001ac400 _TTRXFo_oGO13ReactiveCocoa5EventTCSo6NSDataCSo13NSURLResponse_CSo7NSError__dT__XFo_iGS0_TS1_S2__S3___dT__ + 56
        67  ReactiveCocoa                       0x00000001001a8d4c _TF13ReactiveCocoa8sendNextu0_Rq0_Ss9ErrorType_FTFGOS_5Eventq_q0__T_q__T_ + 252
        68  ReactiveCocoa                       0x00000001001ac248 _TFFFE13ReactiveCocoaCSo12NSURLSession19rac_dataWithRequestFS0_FCSo12NSURLRequestGVS_14SignalProducerTCSo6NSDataCSo13NSURLResponse_CSo7NSError_U_FTFGOS_5EventTS3_S4__S5__T_CS_19CompositeDisposable_T_U_FTGSqS3__GSqS4__GSqS5___T_ + 312
        69  ReactiveCocoa                       0x00000001001ac468 _TTRXFo_oGSqCSo6NSData_oGSqCSo13NSURLResponse_oGSqCSo7NSError__dT__XFdCb_dGSqS__dGSqS0__dGSqS1___dT__ + 92
        70  CFNetwork                           0x0000000184a87510 <redacted> + 32
        71  CFNetwork                           0x0000000184a99ff4 <redacted> + 296
        72  Foundation                          0x00000001862a4374 <redacted> + 16
        73  Foundation                          0x00000001861f71a0 <redacted> + 96
        74  Foundation                          0x00000001861e73e8 <redacted> + 604
        75  Foundation                          0x00000001862a6768 <redacted> + 224
        76  libdispatch.dylib                   0x0000000101481c68 _dispatch_client_callout + 16
        77  libdispatch.dylib                   0x000000010148e780 _dispatch_queue_drain + 1036
        78  libdispatch.dylib                   0x0000000101485958 _dispatch_queue_invoke + 464
        79  libdispatch.dylib                   0x0000000101490898 _dispatch_root_queue_drain + 760
        80  libdispatch.dylib                   0x0000000101490590 _dispatch_worker_thread3 + 132
        81  libsystem_pthread.dylib             0x000000019a961470 _pthread_wqthread + 1092
        82  libsystem_pthread.dylib             0x000000019a961020 start_wqthread + 4
    )

**Comment by andersio** [comment]
The problem is about the nature of `MutableProperty`. It has a buffering producer with it, so while values are sent synchronously, the observers attached to it are in fact being called on its own private serial queue, but not the main thread UIKit requires.

**Comment by andersio** [comment]
Applying `.observeOn(UIScheduler())` to the producer should an easy way to mitigate the issue. That's said you have to be careful if the asynchrony might cause race conditions.

**Comment by ton03** [comment]
Perfect! This solves my issue (for now, I hope it doesn't happen again, ever.) I'm not too worried about race conditions yet, but it's good to have that in mind.

**Comment by Vadim-Yelagin** [comment]
@andersio @ton03 By the look of the stack trace it appears that you use `NSURLSession.sharedSession().rac_dataWithRequest` and put its result into a `MutableProperty`. The thing is, `NSURLSession.sharedSession()` calls its completion block on a non-main thread by default. It means that the signal producer's observer is called on that thread as well, and the mutable property is being set on the same thread, which in turn means that the property is observed on that thread as well, and this where your UI code is. Applying `.observeOn(UIScheduler())` to the producer is the right solution here, however it has nothing to do with `MutableProperty` using a private queue in its implementation.
