### ISSUE TITLE
Update CocoaPods spec for latest alpha

### ISSUE THREAD

**Issue by mpurland** [ReactiveCocoa/ReactiveCocoa#2590]
Here's a PR: https://github.com/CocoaPods/Specs/pull/13666

**Comment by NachoSoto** [comment]
Thanks!

**Comment by mpurland** [comment]
@NachoSoto So will the updated spec be updated on CocoaPods trunk?

**Comment by NachoSoto** [comment]
We don't maintain that ourselves. Looks like @ashfurrow is on top of that though?

**Comment by ashfurrow** [comment]
Yup, discussing it on another issue with @mpurland
