### ISSUE TITLE
Update to RAC 4

### ISSUE THREAD

**Issue by lc-git** [ReactiveCocoa/ReactiveCocoa#2593]
I want to use SignalProducer instead of RACSignal in one file. But the new implementation gives me an error "Cannot invoke 'Failure' with an argument list of type (NSError)". Anyone has idea about this?

Previous implementation:
extension RACSignal {

    /// Get given JSONified data, pass back objects
    func mapToObject(classType: JSONAble.Type) -> RACSignal {
        func resultFromJSON(object:[String: AnyObject], classType: JSONAble.Type) -> AnyObject {
            return classType.fromJSON(object)
        }

        return tryMap({ (object, error) -> AnyObject! in
            if let dict = object as? [String:AnyObject] {
                return resultFromJSON(dict, classType: classType)
            }

            if error != nil {
                error.memory = NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.Data.rawValue, userInfo: ["data": object])
            }

            return nil
        })
    }
}

New implementation:

extension SignalProducer {
    
    /// Get given JSONified data, pass back objects
    func mapToObject(classType: JSONAble.Type) -> SignalProducer<JSONAble, E> {
        func resultFromJSON(object: [String: AnyObject], classType: JSONAble.Type) -> JSONAble {
            return classType.fromJSON(object)
        }

        return attemptMap {
            object -> Result<JSONAble, E> in
            if let dict = object as? [String: AnyObject] {
                return .Success(resultFromJSON(dict, classType: classType))
            }
            
            return Result.Failure(NSError(domain: MoyaErrorDomain, code: MoyaErrorCode.Data.rawValue, userInfo: nil))
        }
    }

**Comment by ikesyo** [comment]
Since you are specifying `E` as the error type, you should pass an instance of `E` to `Result.Failure` or wrap the `NSError` into an instance of `E`. Closing.
