### ISSUE TITLE
Feedback on NSProcessInfo.performExpiringActivityWithReason RAC wrapper implementation

### ISSUE THREAD

**Issue by JaviSoto** [ReactiveCocoa/ReactiveCocoa#2595]
Hi! And Happy Swiftmas day!

I recently found myself needing to request a task assertion to ensure that some work could finish running even if the app was background and suspended. Instead of repeating the same implementation all over the place, I considered creating an extension for `SignalProducer` that would ensure that the work performed by the original producer happened in the context of an `NSProcessInfo` "activity".

This is my current implementation:

```swift
extension SignalProducerType {
    public func continueWhenApplicationIsBackgrounded(activityReason reason: String) -> SignalProducer<Self.Value, Self.Error> {
        return SignalProducer { observer, disposable in
            NSProcessInfo.processInfo().performExpiringActivityWithReason(reason) { expired in
                if expired {
                    // TODO: The producer may never start if we get expired = true initially!
                    // Maybe send an error in that case?
                    disposable.dispose()
                }
                else {
                    let dispatchGroup = dispatch_group_create()
                    dispatch_group_enter(dispatchGroup)

                    self.on(event: { event in
                        switch event {
                            case .Next: ()
                            case .Completed, .Interrupted, .Error: dispatch_group_leave(dispatchGroup)
                        }
                    })
                    .start(observer)

                    dispatch_group_wait(dispatchGroup, DISPATCH_TIME_FOREVER)
                }
            }
        }
    }
}
```

My first question would be: does anybody have any experience using `performExpiringActivityWithReason`? This is completely unrelated to RAC, but Apple's documentation is very lacking.
It seems that the work that you perform in the block that they invoke needs to happen serially, and the activity is considered finished when you return from that block (hence the use of a `dispatch_group`).

But the part that I'm trying to wrap my head around is: is this a correct implementation of a `SignalProducer` operator. The block that you pass to `performExpiringActivityWithReason` is documented to be called on a private concurrent queue. By calling `self.start()` there, am I braking the contract from the caller in case they use `startOn()`?

Lastly, what are some guidelines on how to treat the `disposable` that you get when creating a new `SignalProducer` this way?

Thanks in advance :-)

**Comment by NachoSoto** [comment]
> By calling self.start() there, am I braking the contract from the caller in case they use startOn()?

If they apply a `startOn` operator after this, they will receive events in that scheduler. In other words: the `observer` will be another wrapped `SignalProducer` that will schedule those events through that `Scheduler`.

> Lastly, what are some guidelines on how to treat the disposable that you get when creating a new SignalProducer this way?

I'm not an expert on this at all, but I did notice that you forgot to attach the `disposable` created by the subscription to the outer one:
```swift
disposable += self
    .on(...)
    .start(observer)
```

Other than that, this implementation looks good to me!

**Comment by neilpa** [comment]
In a past project I wrote a [similar operator for RAC 2 with `[UIApplication beginBackgroundTaskWithExpirationHandler]`](https://gist.github.com/neilpa/5d47d807a2552edff116) which fits a bit nicer with the producer model if you can use that instead. If not, you need to be careful with where that `dispatch_group_leave` happens. I would avoid using `on` and explicitly forward the events to the observer and only after that do the leave.

**Comment by JaviSoto** [comment]
> If they apply a startOn operator after this, they will receive events in that scheduler. In other words: the observer will be another wrapped SignalProducer that will schedule those events through that Scheduler.

But what if they call `-startOn` BEFORE invoking my method?

```swift
producer
  .startOn(scheduler)
  .continueWhenApplicationIsBackgrounded(activityReason: "reason")
```

>which fits a bit nicer with the producer model if you can use that instead

I might end up using that at the moment, since I have access to the UIApplication at the moment, and because it's better documented and I've used it in the past so it'll have more predictable behavior for me... Thanks for sharing that code snippet!

**Comment by JaviSoto** [comment]
Going with this now:

```swift
extension SignalProducerType {
    public func continueWhenApplicationIsBackgrounded(taskName taskName: String, timeoutError: Self.Error) -> SignalProducer<Self.Value, Self.Error> {
        return SignalProducer { observer, disposable in
            let application = UIApplication.sharedApplication()

            var taskID: UIBackgroundTaskIdentifier?

            let endTask = {
                if let taskID = taskID {
                    application.endBackgroundTask(taskID)
                }

                taskID = nil
            }

            taskID = application.beginBackgroundTaskWithName(taskName, expirationHandler: {
                observer.sendError(timeoutError)
                disposable.dispose()
                endTask()
            })

            disposable += self.start() { event in
                switch event {
                    case .Next(let value):
                        observer.sendNext(value)
                    case .Error(let error):
                        observer.sendError(error)
                        endTask()
                    case .Interrupted:
                        observer.sendInterrupted()
                        endTask()
                    case .Completed:
                        observer.sendCompleted()
                        endTask()
                }
            }
        }
    }
}
```

**Comment by JaviSoto** [comment]
In case somebody finds this issue by searching and needs to implement this in terms of `NSProcessInfo.self.performExpiringActivityWithReason(_:)` to use in an extension, this is the implementation I'm using now:

```swift
extension SignalProducerType {
    public func continueWhenApplicationIsBackgrounded(taskName taskName: String, timeoutError: Self.Error) -> SignalProducer<Self.Value, Self.Error> {
        return SignalProducer { observer, disposable in
            NSProcessInfo.processInfo().performExpiringActivityWithReason(taskName) { expired in
                guard !expired else {
                    observer.sendFailed(timeoutError)
                    disposable.dispose()
                    return
                }

                let dispatchGroup = dispatch_group_create()
                dispatch_group_enter(dispatchGroup)

                disposable += self.on(event: { event in
                    switch event {
                        case .Next: ()
                        case .Completed, .Interrupted, .Failed: dispatch_group_leave(dispatchGroup)
                    }
                })
                    .start(observer)

                dispatch_group_wait(dispatchGroup, DISPATCH_TIME_FOREVER)
            }
        }
    }
}
```
