### ISSUE TITLE
Implementing not() operator

### ISSUE THREAD

**Issue by vojto** [ReactiveCocoa/ReactiveCocoa#2608]
Hey guys,

I'm quite new to ReactiveCocoa,

but I wanted a `not()` operator in order to do something like this:

```swift
startButton.rac_hidden = model.canStart.not()
```

Where `visible` is `AnyProperty<Bool>`.

Here's the best I could do:

```swift
extension PropertyType where Value == Bool {
    func not() -> SignalProducer<Bool, NoError> {
        return self.producer.map { value in
            return !value
        }
    }
}
```

It works!

Does it look good? What would be the proper way to do it?

**Comment by vojto** [comment]
Here's revision #2:

```swift
extension PropertyType where Value == Bool {
    func not() -> SignalProducer<Bool, NoError> {
        return self.producer.not()
    }
}

extension SignalProducerType where Value == Bool {
    func not() -> SignalProducer<Bool, Self.Error> {
        return self.map { value in
            return !value
        }
    }
}

```

**Comment by NachoSoto** [comment]
The implementation looks good!

However, note that for now we're not interested in adding more operators like this to the API until RAC is stable.

**Comment by vojto** [comment]
Noted – will just keep it in my own library and here in PR for people who would like to use it to.

Could you please give me some pointers on  implementing `equals` operator? To go like:

```swift
sunImage.rac_hidden <~ weather.producer.equals("Sunny")
```

I could implement one specific to `String`s, but how about a general equals? 

I was hoping for something along these lines:

```swift
extension SignalProducerType {
    func equals(other: Value) -> SignalProducer<Bool, Self.Error> {
        return self.map { value in
            return value == (other as Value)
        }
    }
}
```

**Comment by SandyChapman** [comment]
@vojto I think you'll need to constrain `Self.T` (or is it `Self.Type` in the mainline branch?) to the `Equatable` protocol in order to use `==` in the body like this.

**Comment by NachoSoto** [comment]
You can do constraint `Self` to be `Equatable` so that you can call `==`:
```swift
extension SignalProducerType where Self.Value: Equatable {
    func equals(other: Value) -> SignalProducer<Bool, Self.Error> {
        return self.map { $0 == other }
    }
}
```

**Comment by vojto** [comment]
That works great. I'm adding my `empty()` implementation for checking when value equals nil, if somebody needs it.

```swift
extension SignalProducerType where Value: OptionalType {
    func empty() -> SignalProducer<Bool, Self.Error> {
        return self.map { value in
            return value.optional == nil
        }
    }
}
```

Closing, problem solved!
