### ISSUE TITLE
ObjectiveCBridging.md says you can get a signal from a signalproducer by calling start, doesn't appear to be the case.

### ISSUE THREAD

**Issue by chrishulbert** [ReactiveCocoa/ReactiveCocoa#2610]
In here:
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/ObjectiveCBridging.md

It says that: ```Hot” RACSignals cannot be directly converted into Signals, because any RACSignal subscription could potentially involve side effects. To obtain a Signal, use RACSignal.toSignalProducer followed by SignalProducer.start, which will make those potential side effects explicit```

Which sounds great and makes sense. However when you call `mySignalProducer.start()` (RAC4) it returns a `Disposable` not a Signal as the docs above suggest.

Thanks

**Comment by andersio** [comment]
Use `startWithSignal` if you need the underlying signal.
