### ISSUE TITLE
Sending a failure event from a map block

### ISSUE THREAD

**Issue by chrishulbert** [ReactiveCocoa/ReactiveCocoa#2611]
Hi all,
In the readme.md, it has an example of a network request, then a JSON parsing map step like so:'

    let searchResults = searchStrings
    .flatMap(.Latest) { (query: String) -> SignalProducer<(NSData, NSURLResponse), NSError> in
        let URLRequest = self.searchRequestWithEscapedQuery(query)
        return NSURLSession.sharedSession().rac_dataWithRequest(URLRequest)
    }
    .map { (data, URLResponse) -> String in
        let string = String(data: data, encoding: NSUTF8StringEncoding)!
        return self.parseJSONResultsFromString(string)
    }
    .observeOn(UIScheduler())

I'm concerned about the `!` after the string parser. We all know that the backend service might send string-parseable (or in a more typical use case) non-json parseable data for some reason. Currently with my non-RAC code i simply call completion with a failure case result enum in that case. With RAC i'm assuming it'd be best to send a failure event in this case. But i don't see how it's possible to raise a failure from the body of a map block? Am i missing something?

Thanks a lot

**Comment by NachoSoto** [comment]
You'd have to work at a *higher level of abstraction*: instead of mapping values to values, you'd need to map values **to signals**, so that you can opt into returning a signal that emits an error:
```swift
.flatMap(.Latest) { (data, URLResponse) -> String in
    return SignalProducer<String, SomeErrorType>.attempt {
        return Result(
               String(data: data, encoding: NSUTF8StringEncoding).map(self.parseJSONResultsFromString),
               failWith: SomeErrorType.DecodingError
        )
    }
}
```

Let me know if that helps! I'm happy to elaborate more if needed :)

**Comment by chrishulbert** [comment]
Thanks a lot, that makes sense.
