### ISSUE TITLE
error: GNU-style inline assembly is disabled

### ISSUE THREAD

**Issue by mixalich7b** [ReactiveCocoa/ReactiveCocoa#2613]
Xcode displays this error when I'm trying to compile iOS application with WatchKit Extension for device. It has started after update Xcode to version 7.2.
ReactiveCocoa 2.5, file RACCompoundDisposable.m, line 149.

**Comment by kastiglione** [comment]
I suggest we remove the dtrace providers, if they're indeed the cause of problems. I doubt anyone is both using RAC 4 and also tracing the old ObjC implementation.

**Comment by mdiep** [comment]
The Swift and Objective-C APIs will be split going forward (#2807), so this won't be an issue.
