### ISSUE TITLE
[Feature Request] Atomic.modify for MutableProperty?

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#2615]
In some circumstances, one might modify a MutableProperty based on its previous value, e.g. a counter. While so far in my own tests I haven't faced any out of sync situation, it still has a chance to go out of track on paper, since the getter and setter of `MutableProperty.value` is not protected by the same locking attempt. I wonder if a similar offering to `Atomic.modify` could be introduced to `MutableProperty`.

e.g.
```
let oldValue = property.modify { $0 + 1 }
```

**Comment by NachoSoto** [comment]
I think that would be valuable! :)
