### ISSUE TITLE
ReactiveCocoa.h file not found

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#2623]
Hello,

Finally have chance to switch from RAC2 to RAC4! Like it so much! Thanks! But have following issue:

pod 'ReactiveCocoa/Core', '4.0.0-RC.1'
During compilation appears error that ReactiveCocoa.h file not found, as it is located in ReactiveCocoa/UI

**Comment by RuiAAPeres** [comment]
Please let us know if you are still having issues.
