### ISSUE TITLE
Why is the compiled framework so big?

### ISSUE THREAD

**Issue by DavdRoman** [ReactiveCocoa/ReactiveCocoa#2625]
I'm pretty sure this is a silly question, but I just can't figure out why `ReactiveCocoa.framework` and its `dSYM` are so huge when installed through Carthage (about 27mb each), making my app much bigger as well.

Am I missing anything here?

**Comment by eimantas** [comment]
run this on frameworks' binary (not package)

    $ lipo -info ReactiveCocoa

This is what I get:

    Architectures in the fat file: ReactiveCocoa are: i386 x86_64 armv7 arm64 

So the size comes basically because of fat framework binary that contains all possible architectures. If you're using carthage, it should strip out unused architectures depending on the build architecture.

**Comment by NachoSoto** [comment]
@eimantas that's exactly right! So it's so big because the `.framework` actually contains 4 different copies of the binary, but they'll be stripped out using `carthage copy-frameworks` when submitting your app.

**Comment by DavdRoman** [comment]
Makes sense, thanks guys! :+1:
