### ISSUE TITLE
What is the best practices to create a UIImageView click signal?

### ISSUE THREAD

**Issue by soapsign** [ReactiveCocoa/ReactiveCocoa#2626]
I am very new to this framework and I only know we have ```rac_signalForControlEvents()``` for ```UIButton```. I wonder how to do that on a ```UIImageView``` or ```UILabel```.
Any help?

**Comment by NachoSoto** [comment]
Like you said, `UIImageView` is not a `UIControl`. I'd recommend either using a `UIButton` with a `UIImage`, or attaching a `UITapGestureRecognizer` to the `UIImageView` and using `rac_gestureSignal`.

**Comment by soapsign** [comment]
Thanks for the prompt reply.
