### ISSUE TITLE
Factor out SchedulerType and associated components?

### ISSUE THREAD

**Issue by swizzlr** [ReactiveCocoa/ReactiveCocoa#2627]
I find many reasons to use SchedulerType outside of RAC code, mostly for its beautiful abstraction and isolation of time as an implicit dependency.

If I created a repository for this purpose, and opened a PR migrating RAC to use it as a dependency, would it be accepted?

**Comment by NachoSoto** [comment]
Normally I'd say that it's a good idea, but like I pointed out in #2579, the maintenance cost is too high for this to be worth it, unfortunately. Once we can use the new package manager everywhere hopefully this stuff will be trivial.

**Comment by swizzlr** [comment]
Okay, how about if it were submoduled? Built as part of RAC, but available separately? I really want the SignalProducerTypes in my Linux life now ;(

**Comment by neilpa** [comment]
This is only part of the broader question about how to structure RAC so it will work better cross-platform. I'd rather not make any premature changes until the dust begins to settle with the package management tools.
