### ISSUE TITLE
Question about meging 2 signals to 1 singal

### ISSUE THREAD

**Issue by soapsign** [ReactiveCocoa/ReactiveCocoa#2630]
I wonder why we can only [merge](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/BasicOperators.md#merging) ```Signal Producer``` but not ```Signal```. 
Any reason behind this limitation?

**Comment by andersio** [comment]
`flatten` with `FlattenStrategy.Merge` is available on `Signal`.

https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Flatten.swift

**Comment by soapsign** [comment]
That function is converting the signal to signal producer then return the signal to me. I want to know why the intermediate transform from signal to signal producer is necessary,

**Comment by NachoSoto** [comment]
@soapsign that's just an implementation detail so that we can reuse code and define operators only once.

**Comment by NachoSoto** [comment]
@soapsign merging `Signal`s is possible now! We just haven't updated the docs:

```Swift 
Signal.merge([signal1, signal2])
```

**Comment by soapsign** [comment]
Thanks!
