### ISSUE TITLE
Question about buffer

### ISSUE THREAD

**Issue by craigzour** [ReactiveCocoa/ReactiveCocoa#2633]
Hi guys,

I created a buffer of 10 elements and I would like to subscribe to the producer in order to retrieve all elements contained in the buffer every time I add an element to it.

I have not been able to find a solution about this scenario... Can you guys give me some help ?

Thanks.

**Comment by NachoSoto** [comment]
Can you elaborate what you mean by this?
> I would like to subscribe to the producer in order to retrieve all elements contained in the buffer every time I add an element to it.

`start`ing the producer will emit all the items that have been buffered so far. Is that no what you want?

**Comment by craigzour** [comment]
I am gonna add some code.

First I create my buffer:
```
let (bufferedSignalProducer, bufferedSignalObserver) = SignalProducer<String, NoError>.buffer(10)
self.someProperty.producer.start(bufferedSignalObserver)
```

Then I would like to do a "startWithNext" on "bufferedSignalProducer.producer" so that I receive and array of "String" (all buffered values) each time a new value is sent to "bufferedSignalObserver".

Is that explanation more explicit ?

**Comment by avalanched** [comment]
This is not how the buffer works

the producer buffers the values that are send to the observer before you subscribe to it.

        let (producer, observer) = SignalProducer<String, NoError>.buffer(10)
        observer.sendNext("hello")
        observer.sendNext("world")
        producer.startWithNext { print($0) } // prints hello, world
        observer.sendNext("reactive") // prints reactive

**Comment by craigzour** [comment]
@avalanched Oh ok I see ! Thanks you !
