### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by gkaimakas** [ReactiveCocoa/ReactiveCocoa#2636]
Are there plans to support cocoapods officially ?

**Comment by KennedyChiang** [comment]
actually i not really senior,so i'm not sure what can i do.

**Comment by NachoSoto** [comment]
We're not interested in officially maintaining support for it, but a few contributors are helping with that. You can see why in [other issues](https://github.com/ReactiveCocoa/ReactiveCocoa/issues?utf8=%E2%9C%93&q=is%3Aissue++CocoaPods)
