### ISSUE TITLE
Crash in Atomic.lock() on iOS7

### ISSUE THREAD

**Issue by impopappfactory** [ReactiveCocoa/ReactiveCocoa#2637]
Hi,

I tried to start using RAC4 in my project targeting iOS7, but soon stumbled on presumably a memory corruption when running on an actual iPhone4/iOS7 device.

The code is pretty straightforward:
```Swift
class InitialConnectViewControllerBehavior
{
    // ...
    typealias SignalControllerFinished = Signal<Void, NoError>
    let (controllerFinished, pipeControllerFinished) = SignalControllerFinished.pipe()
    func observeControllerFinished(finished: ()->()) {
        // crashing line
        controllerFinished.observe(SignalControllerFinished.Observer(completed: finished, interrupted: finished))
    }
}    
```

It runs fine on iOS8-9 devices and on Simulator.

Relevant crash logs:
[DuduKids  29-12-15 15-13.crash.txt](https://github.com/ReactiveCocoa/ReactiveCocoa/files/75584/DuduKids.29-12-15.15-13.crash.txt)
[DuduKids  31-12-15 15-11.crash.txt](https://github.com/ReactiveCocoa/ReactiveCocoa/files/75583/DuduKids.31-12-15.15-11.crash.txt)

<img width="1383" alt="screen shot 2015-12-31 at 15 26 32" src="https://cloud.githubusercontent.com/assets/6030289/12065186/e871b018-afd2-11e5-8b80-30fac2631fa6.png">

I tried replacing spinLock in Atomic.swift with NSRecursiveLock, and memory corruption becomes even more evident:
<img width="1382" alt="screen shot 2015-12-31 at 15 30 05" src="https://cloud.githubusercontent.com/assets/6030289/12065222/7549cb9c-afd3-11e5-86d6-7741a1ab39cd.png">

Especially here, in Atomic.init(), _lock is not set to a correct value:
<img width="1366" alt="screen shot 2015-12-31 at 16 04 06" src="https://cloud.githubusercontent.com/assets/6030289/12065476/56398ada-afd8-11e5-82d2-3eb72cc20296.png">

I haven't found out possible reason for this yet, and to me it looks more like a Swift/iOS7 bug rather than ReactiveCocoa bug. Just wanted to hear your opinion regarding this before filing a bug with Apple.

Thanks!

**Comment by NachoSoto** [comment]
iOS 7 doesn't support frameworks, how are you linking RAC into your app?
Thanks for the report in any case! Did you try running your app with the address sanitizer? That might unveil the source of the problem.

**Comment by impopappfactory** [comment]
iOS7 actually runs apps with dynamic/embedded frameworks, although AppStore would reject them anyway. So I'm just adding all .swift/*.m source files into the main target instead. :(

Address Sanitizer is not able to run on iOS7 device for some reason:
```
AddressSanitizer debugger support is active. Memory error breakpoint has been installed and you can now use the 'memory history' command.
==2783==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.
```

If this is actually an issue in Swift/iOS7 runtime then I'd rather back off to objective-c early.
I'll probably file a bug with Apple anyway.

Thanks and will greatly appreciate if there are other thoughts on this.

p.s. Merry NY eve to everyone! )
