### ISSUE TITLE
Remove SignalProducer.buffer capacity Int.max default

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#2640]
Pointed out by @JaviSoto in #2639:
I think we should remove this maximum. It's probably common for people to not think about this capacity and leave the default, wasting memory.

This would be a breaking change, so it would be great to get in for 4.0.

What does everyone think?

**Comment by JaviSoto** [comment]
My suggestion:

Create an overloaded version that doesn't take the size parameter, and outputs a warning saying "this may not be what you want". This version calls the other version with the current default. The other version doesn't have a default and forces you to specify a value.

**Comment by JaviSoto** [comment]
And then eventually we remove that first version

**Comment by NachoSoto** [comment]
I don't think that's necessary, we can introduce this breaking change before `4.0`. Users relying on the default value will just need to provide a value, forcing them to make a decision, which is good!

**Comment by JaviSoto** [comment]
👍
On Sun, Jan 3, 2016 at 12:17 PM NachoSoto <notifications@github.com> wrote:

> I don't think that's necessary, we can introduce this breaking change
> before 4.0. Users relying on the default value will just need to provide
> a value, forcing them to make a decision, which is good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2640#issuecomment-168537834>
> .
>
-- 
Javier Soto
