### ISSUE TITLE
observe and observe next sending wrong kind of events in v4 RC 1

### ISSUE THREAD

**Issue by JaidevSoin** [ReactiveCocoa/ReactiveCocoa#2642]
Heya, I'm getting weird behaviour and would love some advice:

In my ViewController:

    self.editAction = CocoaAction(viewModel.editAction, input: ())
    self.editButton.action = CocoaAction.selector
    self.editButton.target = editAction

In my ViewModel:

    editAction = Action {_ in
      return SignalProducer(value: true)
    }
    
    editAction.events.observe { event in
      switch event {
      case .Completed:
        print("observe: Completed")
      case .Failed(_):
        print("observe: Failed")
      case .Next(_):
        print("observe: Next")
      case .Interrupted:
        print("obsesrve: Interrupted")
      }
    }

    editAction.events.observeNext { event in
      switch event {
      case .Completed:
        print("observeNext: Completed")
      case .Failed(_):
        print("observeNext: Failed")
      case .Next(_):
        print("observeNext: Next")
      case .Interrupted:
        print("observeNext: Interrupted")
      }
    }

Now, the "return SignalProducer(value: true)" should mean that each time I tap the editButton, two events are sent: a next and a complete.

So I expect the console output to be:

    observe: Next
    observeNext: Next
    observe: Completed

Instead I am getting:

    observe: Next
    observeNext: Next
    observe: Next
    observeNext: Completed

Which indicates that .observe is being sent two next events (it should get a next, then a complete), and observeNext is being sent both a next event and a complete event (it should only get a next event right?).

If I try and observe just completion:

    editAction.events.observeCompleted {
      print("observeCompleted")
    }

observeCompleted is never logged to the console.

Is there something I am missing here?

Thanks!

**Comment by avalanched** [comment]
Its because ```action.events``` is a Signal on its own that forwards ```Event<Output, Error>``` produced on the SignalProducer in the Action. it uses a ```Next``` Event on the Signal to do so

so what you actually get as output when observing the events is Event<Event<Bool, NoError>, NoError>; if you print it out you get
```
NEXT NEXT true
NEXT COMPLETED
```

when you use observeNext you go straight to the event Produced by the producer inside the action.

**Comment by JaidevSoin** [comment]
Ah yup, got it now. Thanks for the explanation!

**Comment by JaidevSoin** [comment]
Is there a recommended way of converting that ```Event<Event<Value, Error>, Error>``` back into a plain ```Event<Value, Error>```, or is that not a sensible (or meaningful) thing to do? I've been playing around a little with flatMap, but I just can't get the syntax right, an example would be awesome if you could.

Thanks!

**Comment by avalanched** [comment]
by using ```observeNext``` you omit the outer Event

**Comment by JaidevSoin** [comment]
Ah sorry, I didn't make myself very clear. I'm looking for whether it's possible to do this in a fluent like way. Observe next terminates the method chain.

I can write an extension, but wanted to make sure that I haven't missed something else obvious first.

Cheers!

**Comment by ikesyo** [comment]
It seems that `Action.values` is what you want.
