### ISSUE TITLE
Couldn't find platform family in Info.plist

### ISSUE THREAD

**Issue by ton03** [ReactiveCocoa/ReactiveCocoa#2644]
Hi,

I'm getting this error when I validate my archive:

```
Couldn't find platform family in Info.plist CFBundleSupportedPlatforms or Mach-O LC_VERSION_MIN for ReactiveCocoa
```
I'm using `v4.0.0-alpha.4`

Thanks!

**Comment by carlosefonseca** [comment]
You probably already fixed it but I'll leave it here for someone else…

The fix is looking in the "Copy Bundle Resources" build phase and deleting all of the .dSYM files.
