### ISSUE TITLE
Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by ivan-ushakov** [ReactiveCocoa/ReactiveCocoa#2648]
I my project is Objective C only and I use master version in my Cartfile and when I build and run project, it works fine. 
Here is my Cartfile:

    github "ReactiveCocoa/ReactiveCocoa" "master"

But when I submitted file to AppStore, I got crash report from Review Team:

    Version:             8 (1.2)
    Code Type:           ARM-64 (Native)
    Parent Process:      launchd [1]

    Date/Time:           2016-01-08 17:42:38.38 -0800
    Launch Time:         2016-01-08 17:42:38.38 -0800
    OS Version:          iOS 9.2 (13C75)
    Report Version:      105

    Exception Type:  EXC_BREAKPOINT (SIGTRAP)
    Exception Codes: 0x0000000000000001, 0x00000001200d9088
    Triggered by Thread:  0

    Filtered syslog:
    None found

    Dyld Error Message:
    Dyld Message: Library not loaded: @rpath/libswiftCore.dylib
      Referenced from: /private/var/mobile/Containers/Bundle/Application/4654BAE2-CF40-45F1-AE74-8E537DF7B92B/My.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
      Reason: image not found
      Dyld Version: 370.6

    Binary Images:
    0x100068000 - 0x10008bfff My arm64  <4d60b4aaf9b536848cc009212b6d573e> /var/mobile/Containers/Bundle/Application/4654BAE2-CF40-45F1-AE74-8E537DF7B92B/My.app/My
    0x1000c0000 - 0x10020bfff ReactiveCocoa arm64  <f42212ee0c46318885eae9f7164a464a> /var/mobile/Containers/Bundle/Application/4654BAE2-CF40-45F1-AE74-8E537DF7B92B/My.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
    0x100830000 - 0x10083ffff Result arm64  <507f2dcea9793a778a08e2edb54c3b14> /var/mobile/Containers/Bundle/Application/4654BAE2-CF40-45F1-AE74-8E537DF7B92B/My.app/Frameworks/Result.framework/Result
    0x1200d8000 - 0x120107fff dyld arm64  <9e98992ceed735e2ac4784cb28efe7c1> /usr/lib/dyld

I found several questions about `libswift_stdlib_core.dylib` on SO and one of solutions is `Embedded Content Contains Swift Code` flag. I don't understand why I need it in pure Objective C project. Could you please help me?

**Comment by ikesyo** [comment]
> I found several questions about libswift_stdlib_core.dylib on SO and one of solutions is Embedded Content Contains Swift Code flag. I don't understand why I need it in pure Objective C project. Could you please help me?

The step is stated in the [README](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/v4.0.0-RC.1/README.md#getting-started):

> If your application target does not contain Swift code at all, you should also set the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting to “Yes”.

That is because if an application does not contain Swift codes at all, Xcode does not embed Swift runtime into the app, but embedded libraries (in this case `ReactiveCocoa`) might requires the runtime. If `EMBEDDED_CONTENT_CONTAINS_SWIFT` is set to “Yes”, Xcode always embeds the runtime even if the app has no Swift codes.

**Comment by ivan-ushakov** [comment]
Thank you for reply and sorry for my inattentionю
