### ISSUE TITLE
how can i use it only in swift? about not import the objective-c part.

### ISSUE THREAD

**Issue by michaelmou** [ReactiveCocoa/ReactiveCocoa#2653]

**Comment by AquaGeek** [comment]
I'm not sure I understand what you're asking. You can just use the Swift API if that's what you want to do (i.e. avoid the `RAC...` Objective-C classes). Is there a specific reason you want to exclude the Objective-C code?

**Comment by neilpa** [comment]
You'd have to fork it and do some surgery to delete all the ObjC bits. I experimented a while ago with this to see how much smaller it made the library.

https://github.com/neilpa/ReactiveCocoa/tree/nuke-objc

That may be of use but it's woefully out of date now.

**Comment by ikesyo** [comment]
This is now tracked in #2807. Closing.

**Comment by michaelmou** [comment]
@neilpa ok,thanks
