### ISSUE TITLE
Crash when get  UIButton.rac_command

### ISSUE THREAD

**Issue by Unihilator** [ReactiveCocoa/ReactiveCocoa#2654]
``` swift 
let button1 = UIButton(frame: CGRect(x: 0, y: 0, width: 2, height: 2))
button1.rac_command.toAction()
```

Console: fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by iv-mexx** [comment]
What do you want to achieve? 

The button does not have a default command set, so `rac_command = nil`. You are supposed to set the command that should be executed by the button. So usually you create a `RACCommand` (or an `Action` and use `toRACCommand`) and set that as `rac_command` of the button.
