### ISSUE TITLE
Action iteration?

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#2655]
So, if I have an array of profiles and need to grab profile images for each, what's the correct RAC 3.0 approach to this? 

May Initial though was something like: 

```Swift
   viewModel.fetchProfilesAction.values
	.observeOn(UIScheduler())
	.observeNext( {[weak self] results in
                self?.fetchProfiletImages(results)
	})

    private func fetchProfileImages(profileIDs: [String]) {
        for (_, profileID) in profileIDs.enumerate() {
            viewModel.fetchImageAction.apply(profileID).start()
        }
    }

    viewModel.fetchImageAction.values
      .observeOn(UIScheduler())
      .observeNext( {[weak self] results in
           self?.refreshProfileImages(results)
        })

```

Which would call the func `fetchProfileImages` after the viewModel returns the array of profiles via `viewModel.fetchProfilesAction value` observer. Pretty sure this won't work though; seems like iterating through the profileIDs and calling `fetchImageAction` like that would only fetch a single time. :confused:

What's the general approach given a pair of actions -- one which returns a collection of items and another which needs to perform an action for each of those items?

**Comment by avalanched** [comment]
An ```Action``` is disabled when executing, when the inner producer is completed the ```Action``` stops executing, making it enabled again. 

Just start the inner producer directly and if you want a single observer, you can add them to a buffer.
```swift
let imageBuffer = SignalProducer<UIImage,NoError>.buffer()

func fetchImageProducer(id:String) -> SignalProducer<UIImage, NoError> {
    return SignalProducer { observer, disposable in
        // fetches image here
    }
}

for id in elements {
    fetchImageProducer(id).start(imageBuffer.1)
}
```
