### ISSUE TITLE
'if / else' construction in Reactive Cocoa

### ISSUE THREAD

**Issue by Otbivnoe** [ReactiveCocoa/ReactiveCocoa#2658]
Hello! I want to create if/else construction by Reactive Cocoa. I have the code : 

![screen shot 2016-01-18 at 3 31 14 pm](https://cloud.githubusercontent.com/assets/4833198/12291113/21ec7a92-ba07-11e5-8e63-c00d753210aa.png)

In that construction called rac_testYES signal, but it's something strange because if:[RACSignal return:@0] return NO. Can  you explain me, what i'm doing wrong.

**Comment by mdiep** [comment]
`if:then:else:` takes an `NSNumber` for its first argument. If that number evaluates to true using `-[NSNumber boolValue]`, then the `then` signal is used; else the `else` signal is used`. `[@0 boolValue]` is false.

**Comment by Otbivnoe** [comment]
![screen shot 2016-01-13 at 21 54 15](https://cloud.githubusercontent.com/assets/4833198/12299283/d9056074-ba37-11e5-83e0-fa50c2aac5f0.png)

If I run this code I will see two messages in log (YES then NO). Why do I see YES message? if:then:else: takes RACSignal - NO for first argument. I just want to rac_YES function is not called, only rac_NO. Sorry, I really don't understand it.

**Comment by mdiep** [comment]
Because `-rac_YES` is called in either case—it has to be called because its return value is an argument to `-if:then:else:`. But the signal that it returns won't be subscribed to.

**Comment by Otbivnoe** [comment]
I understand it! Thank you so muсh ! :)
