### ISSUE TITLE
One RACSignal used at one time

### ISSUE THREAD

**Issue by Otbivnoe** [ReactiveCocoa/ReactiveCocoa#2661]
I have a test example with one button. When user presses the button is called *RAC_request* and request is executing. If user presses this button many times for a short time, many requests will be execute asynchronously. I want to create logic to previously signal cancelled when new request is executing. I know that exists `switchToLatest` in Reactive Cocoa, but I can't do that logic work correctly. How do this by RAC?

**Comment by twocentstudios** [comment]
Sounds like you're looking for `.flatMap(.Latest, transform: producerTransform)`, where `.Latest` is now a `FlattenStrategy` of the `flatMap` operator.
