### ISSUE TITLE
Retain cycle when using SignalProducer.buffer ?

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2662]
Given the following classes

```swift
import ReactiveCocoa

class MyClassA {
    
    let property = "Hola"
    var count = 0
    
    deinit {
        print("MyClassA deinit")
    }
}

class MyClassB<T> {
    
    let str = "GATO"
    
    init(producer: SignalProducer<T, NoError>) {
        
        
        let a = MyClassA()
        producer.start { [unowned self] event in
            switch event {
            case .Next(_):
                print("\(a.property) \(a.count) \(self.str)")
                a.count += 1
            case .Interrupted:
                print("Interrupted")
            case .Failed(_):
                print("Failed")
            case .Completed:
                print("Completed")
            }
            
        }
    }
    
    deinit {
        print("MyClassB deinit")
    }
}
```

Can anybody explain me why when I pass a producer that was obtained using the `buffer` method the instance of `MyClassA` never gets freed?

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        // This works perfectly
        let property = MutableProperty(0)
        let b = MyClassB(producer: property.producer)
        print(b)
        property.value = 1
        property.value = 2
        property.value = 3
        

        // This generates a retain cycle
        let (producer, observer) = SignalProducer<(), NoError>.buffer()
        let bb = MyClassB(producer: producer)
        
        print(bb)
        observer.sendNext(())
        observer.sendNext(())
        observer.sendNext(())

        return true
    }
```

**Comment by NachoSoto** [comment]
The `start` method is getting a strong reference of `a: MyClassA`, and since the producer does not complete, the reference is always there.
If you add `observer.sendCompleted()` you'd see that `a` is correctly deallocated.

**Comment by guidomb** [comment]
That I understand but Why the producer never completes? Shouldn't it send an interrupt event when there are no references. After the app delegate method is executed no one has a strong reference to the producer nor the observer (that was returned after invoking `buffer`).

Maybe I'm missing something but it isn't clear to me how the subscription created by the `start` method inside `MyClassB` is kept alive.

**Comment by NachoSoto** [comment]
That's the memory model of `Signal`: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L16

**Comment by guidomb** [comment]
OK so just to be clear the producer and the observer returned by `buffer` do reference each other but the cycle is broken when a termination event is sent to the observer. Am I right?

**Comment by NachoSoto** [comment]
Exactly.

**Comment by guidomb** [comment]
Perfect, thanks for taking the time to clarify this!
