### ISSUE TITLE
CocoaPod Error - Unable to find a specification for

### ISSUE THREAD

**Issue by raulsilvamx** [ReactiveCocoa/ReactiveCocoa#2663]
When execute pod update or pod install get the next error
[!] Unable to find a specification for `ReactiveCocoa`

I checked CocoaPods Specs and has a Error (Failed to load latest commit information)

Could you fix this error please?

![captura de pantalla 2016-01-15 a las 12 46 22 p m](https://cloud.githubusercontent.com/assets/710990/12363493/50ec2880-bb86-11e5-8d26-9df7012e9731.png)

**Comment by twocentstudios** [comment]
Give this a shot: `pod 'ReactiveCocoa', '= 4.0.0-RC.1'`
