### ISSUE TITLE
How's the right way to change the definition of a signal but keeping the subscribed observers up to date.

### ISSUE THREAD

**Issue by minuscorp** [ReactiveCocoa/ReactiveCocoa#2668]
Hello.

How's the right way to subscribe to a signal that maybe is not created yet (because is the result of combining some others and that isn't done yet) and keeping the subscribers receiving next events to the most recent signal definition?

With cod, I've done this but don't know if that's the right way:

```swift
let instantCurrent: MutableProperty<Float> = MutableProperty<Float>(0.0)
let instantVoltage: MutableProperty<Float> = MutableProperty<Float>(0.0)
var instantPower: Signal<Float,NoError> = Signal<Float,NoError>.never

init() {
    zip(instantCurrent.producer.filter{ $0 > 0.5 }, instantVoltage.producer).map{ $0 * $1 }.startWithSignal{ signal in instantPower = signal.0 }
}
```

And in other class I get subscribed to that ```instantPower``` and I'm assuming that the observing won't get anything because the signal is ```.never``` until I redefine the Signal and starts sending events.

But I got an error in the previous ```init()``` some lines later (just sometimes, not always):

```swift
self.batteryRemainingTime = combineLatest(averagePowerSignal, remainingEnergySignal).filter{ power, energy in return power > 0.0 }.map{ power, energy in  energy / power}
```

Is this produced because the definition of the ```instantPower``` signal changes its definition while ```combineLatest``` is being executed and for that reason this line should be moved into the ```.startWithSignal{ signal in instantPower = signal.0 ... }```?

**Comment by avalanched** [comment]
when you redefine ```instantPower``` your observer won't get copied over to the new signal.
you can make a ```Signal<Value,Error>.pipe()``` that you can add as an observer on your event streams.

**Comment by minuscorp** [comment]
How do I assign the result of the zip to the ```instantPower``` signal or let its subscribers to start receiving events when the zip has been done?

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group

**Comment by avalanched** [comment]
```swift
let (signal, observer) = Signal<Float,NoError>.pipe()
zip(floatProducerA, floatProducerB).map { /*to Float*/ }.start(observer)
signal.observeNext { print($0) }
```

**Comment by amccarri** [comment]
Maybe instead of assigning a new signal value to instantPower, you use switchToLatest to change the signal.  Sorry I’m not as versed yet in RAC under Swift, but generally whenever I want to subscribe to a different signal on the fly based on some other condition, switchToLatest works pretty well.  I think in RAC 4 it’s .flatten(.latest).

**Comment by minuscorp** [comment]
Thank you very much both of you. Didn't knew that start() could feed an already created signal. Thank you!

Jorge Revuelta Herrero
Software Engineer
BISITE Research Group
