### ISSUE TITLE
CocoaAction not firing second time

### ISSUE THREAD

**Issue by olbrichj** [ReactiveCocoa/ReactiveCocoa#2674]
Hey,

I'm creating an action:

    updateAction = Action<String, String, NoError>() { _ in
                return SignalProducer { sink, _ in
                    self.updateSignal.value = true
                    self.model.allDataSignalProducer().startWithNext { data in
                        self.updateSignal.value = false
                        sink.sendCompleted()
            }
        }
    }

and connect it to a UIRefreshControl:

    refreshAction = CocoaAction(viewModel.updateAction, input: "")
    refreshControl?.addTarget(refreshAction, action: CocoaAction.selector, forControlEvents: .ValueChanged)

the refreshAction is a class variable so I have a strong reference for it.

Refreshing the tableView the first time works fine, but the second time is entirely ignored. The RefreshControl is still displayed.

I've found a similar issue on here, but I'm sending a completed event.. so I'm not entirely sure, what I'm doing wrong.

Oh and how would I handle sideeffects like .endRefreshing on the RefreshControl? Currently I'm using 

    viewModel.updateAction.events.dematerialize().observeOn(UIScheduler()).observeCompleted{ _ in
        self.refreshControl?.endRefreshing()
    }

but I guess it will only fire once, as completed will kill the signal right?

Thanks :)

**Comment by ikesyo** [comment]
Since you `dematerialize` the `events` signal, the resulting signal will entirely complete at the first execution of the source action. You should write it as follows instead not to complete the signal you are observing:

```swift
viewModel
    .updateAction
    .events
    .observeOn(UIScheduler())
    .observeNext { [weak self] event in
        // `if event.isTerminating` might be more appropriate.
        if case .Completed = event {
            self?.refreshControl?.endRefreshing()
        }
    }
```
