### ISSUE TITLE
Understanding .then() in RAC 4

### ISSUE THREAD

**Issue by mbopp** [ReactiveCocoa/ReactiveCocoa#2675]
I think I understand the general concept of then... however when ever I use it I get an error along the lines of `Produces exptected type...; did you mean to call it with '()`
<img width="381" alt="datamanager_swift" src="https://cloud.githubusercontent.com/assets/727071/12487074/9591d280-c033-11e5-8868-ac44d021bd25.png">

Example abbreviated Snippet....
```
func ... -> SignalProducer<SomeExpectedObject, NSError> {

SignalProducer(values: arr)
      .then {
          SignalProducer(value: someExpectedObject).promoteErrors(NSError)
        }
```
So I may be mis understanding.  Can you help clear up how I would use this method?

Thanks!

**Comment by mbopp** [comment]
If it helps clarify the question at all... I generally resort to using something like
```
      .SignalProducer(values: arr)
      .collect()
      .flatMap(FlattenStrategy.Latest) { arr in
          SignalProducer(value: processCheck).promoteErrors(NSError)
        }
```

**Comment by NachoSoto** [comment]
The argument passed to `then` is not a closure, because it doesn't need to be :)
In your second solution, notice that you're ignoring `arr`. That's when `then` can be simpler, since you don't care about the values emitted by the first `SignalProducer`.

```swift
SignalProducer<SomeExpectedObject, NSError>(values: arr)
      .then(SignalProducer(value: someExpectedObject).promoteErrors(NSError))
```

**Comment by mbopp** [comment]
Ah, perfect.  Thanks for helping me figuring that one out @NachoSoto

**Comment by NachoSoto** [comment]
No problem :+1:
