### ISSUE TITLE
question : how to call signal producer that depend to different signal producer

### ISSUE THREAD

**Issue by dennisfarandy** [ReactiveCocoa/ReactiveCocoa#2676]
I have 2 signal producer like this

`func textSignal() -> SignalProducer(String?,NoError)`

and

`func searchSignal(text:String?) -> SignalProducer([User]?,NSError)`

how do I call searchSignal after textSignal called but without nested signal like :

```
textSignal().startWithNext { (text) in
    searchSignal(text).startWithNext { (users) in
        // do something here
    }
}
```

is that possible?

**Comment by dennisfarandy** [comment]
solve with `promoteErrors`. Found it! :)

**Comment by benji-bou** [comment]
Hi,
Tell me if i'm mistaken but you could use flatMap
textSignal().flatMap(FlattenStrategy.Latest, transform: { (text) -> SignalProducer<[User]?,NSError> in
    return searchSignal(text);
}).startWithNext({(users:[User]?) in 
//Do Something
})

Best regard

**Comment by benji-bou** [comment]
Ho sorry I didn't saw your "Without nested" 
^^

**Comment by dennisfarandy** [comment]
```
textSignal()
.promoteError(NSError.self)
.flatMap( .Latest, transform: { (text) -> SignalProducer<[User]?,NSError> in
     return searchSignal(text)
})
.startWithNext ({(users:[User]?) in 
     //Do Something
})
```
missing promoteError :) thats my real problem..
