### ISSUE TITLE
Is ReactiveCocoaVersionNumber extraneous?

### ISSUE THREAD

**Issue by Bogidon** [ReactiveCocoa/ReactiveCocoa#2681]
It seems like the version is not being incremented in the project file. I assume this is intentional. However this causes `ReactiveCocoaVersionNumber` which is declared in `ReactiveCocoa.h` to report an inaccurate version -- which is potentially confusing.

Maybe the version could be updated or `ReactiveCocoaVersionNumber` removed? No big deal anyway.

**Comment by NachoSoto** [comment]
That's automatically generated by `Xcode` on every target, even though [nobody really uses it](https://github.com/search?q=FOUNDATION_EXPORT+const+unsigned+char&type=Code&utf8=✓).

If there were a simple way to maintain a single source of truth for the version number I'd agree with you, we should update this, but considering that these constants aren't really useful for anything I don't think it's worth it.

**Comment by Bogidon** [comment]
Got it @NachoSoto! Thanks for the clarification :+1:
