### ISSUE TITLE
RAC4 Backwards compatibility with RAC2.X

### ISSUE THREAD

**Issue by codyrobb** [ReactiveCocoa/ReactiveCocoa#2682]
Hi!

We are still on a mainly Objective-C and have been waiting for RAC4 to become official to start using it with Swift. 

I'm wondering if this, from the RAC3.0 release notes is still true in RAC4.

> ReactiveCocoa 3.0 includes the first official Swift API, which is intended to eventually supplant the Objective-C API entirely.
>
>However, because migration is hard and time-consuming, and because Objective-C is still in widespread use, 99% of RAC 2.x code will continue to work under RAC 3.0 without any changes.

If so it might be nice to add to the release notes. Looking forward to using the new version, you guys do great work! :+1:

**Comment by NachoSoto** [comment]
Oooh good point! It is still true, we'll add it to the release notes :+1:

**Comment by NachoSoto** [comment]
Thanks for bringing this up. I've drafter the `4.0` release, but we'll need to add a section for `4.0` to the [`CHANGELOG`](CHANGELOG.md) before we release it. I can do it later today, but help would be appreciated!
Rough list of things to mention:
- `SignalType` and `SignalProducerType`
- Protocols defined in protocol extensions (new syntax)
- Full support for `flatten`ing all the things.
- New operators
- `replayLazily`
- Enhancements to `PropertyType`

And I'm sure I'm missing a few things.

**Comment by NachoSoto** [comment]
Working on this now!
