### ISSUE TITLE
cocoadocs for RAC4

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2683]
Hi guys, 
I've been using cocoaDocs with Dash to lookup API's on reactiveCocoa and I see that it gets updated and all so thank you guys for keeping things in good shape. 

The issue that I'm trying to figure out, is why I can't seem to find any of the Swift documentation on ReactiveCocoa. I only see the readME doc but I can't browse specific classes like SignalProducer.

Any idea if there is a solution for this ?

**Comment by NachoSoto** [comment]
Thanks! I filed that here: https://github.com/CocoaPods/cocoadocs.org/issues/404 (don't let the URL fool you, the issue does exist :P)

**Comment by edwardIshaq** [comment]
Thanks. I'll keep an eye on that issue
