### ISSUE TITLE
Signal operator for non nominal types?

### ISSUE THREAD

**Issue by eimantas** [ReactiveCocoa/ReactiveCocoa#2685]
This is probably more of a Swift question than RAC, but how do I define operators to signals sending events with non-nominal types?

I know I can add operators through extensions using `where` clause like this:

```
extension Signal where Value: BooleanType {
 ...
}
```

But is it possible to do that for, say, tuples?

**Comment by avalanched** [comment]
```swift
extension SignalType where Value == (BooleanType, BooleanType) {
    ...
}
```

**Comment by RuiAAPeres** [comment]
@eimantas if @avalanched answered your question please close this issue.
