### ISSUE TITLE
Unit test SignalProducers

### ISSUE THREAD

**Issue by AvdLee** [ReactiveCocoa/ReactiveCocoa#2686]
Is there an option to unit test signalProducers?
I've got many signalProducers for network requests, which implement error observing. I want something like this:

    func testFailure(){
        ///...
        viewModel.signalProducer.startWithError(myError)
        ///...
    }

Now my viewModel failure handling never gets covered. I'm not looking for a stubbed response implementation, which could fix this, but more a ReactiveCocoa solution for this.

**Comment by NachoSoto** [comment]
You can't modify `SignalProducer`s, that would just give you a new producer. What you probably want is create a dummy view model with custom data, and with a producer created with `SignalProducer(error: myError)`.

**Comment by AvdLee** [comment]
hmm, yeah that would probably be my best shot here. I was curious about any other ways to do this

**Comment by NachoSoto** [comment]
If you can provide more details about what your data layer looks like I might be able to give more ideas.

**Comment by AvdLee** [comment]
Well, it's a really basic example. It's an example project for the network library we're using internally. I've created a viewModel with a network call for UI testing. It's basically not more then this:

```swift
final class ViewModel : NSObject {
    
    dynamic private(set) var ipOrigin:String?
    
    func IPCallProducer() -> SignalProducer<IPResponse, Moya.Error> {
        return ExampleAPI.IPCall.request().mapResponseToObjectOfType(IPResponse).doNext({ [weak self] (ipResponse) -> () in
            self?.ipOrigin = ipResponse.origin
        }).on(failed: { [weak self] (error) -> () in
            self?.ipOrigin = "IP not found"
        })
    }
}
```

As I'm aiming for 100% code coverage, I also want this failed blocked to be called by an unit test.

**Comment by iv-mexx** [comment]
To make your ViewModel more testable, you could inject the Dependency of `ExampleAPI` and use a mocked one for testing that behaves as you like for the Testcase. 

I dont know enough about Moya, but I would draft it something like this:

Have a protocol that is used in the `IPCallProducer()` method: 

```swift
protocol APIRoutType {
    func request() -> SignalProducer<IPResponse, Moya.Error>
}
```

and modify the ViewModel: 

```swift
final class ViewModel : NSObject {
    
    dynamic private(set) var ipOrigin:String?
    
    func IPCallProducer(route: APIRoutType = ExampleAPI.IPCall) -> SignalProducer<IPResponse, Moya.Error> {
        return route.request() // Do the necessary transformations
    }
}
```

(You would need to make whatever you get from `APIRoute.IPCall` conform to `APIRoutType`)

By using a default value for the parameter, you can still use the method as you did before for normal use, but for tests you can inject another instance that conforms to `APIRoutType`, so you could have a failing one: 

```swift
struct FailingTestRoute {
    // Just returns a SignalProducer that fails immediately
    func request() -> SignalProducer<IPResponse, Moya.Error> {
        return SignalProducer<IPResponse, Moya.Error>(error: Moya.Error())
    }
}
```

and in a testcase you use it like this:

```swift
func testViewModel() {
    ViewModel().IPCallProducer(route: FailingTestRoute())
}
```

**Comment by AvdLee** [comment]
interesting! Quite simpel though, seems suitable. Will try that out!

**Comment by AvdLee** [comment]
Above fix did the trick for me
