### ISSUE TITLE
Upgrade Result and remove NoError

### ISSUE THREAD

**Issue by NachoSoto** [ReactiveCocoa/ReactiveCocoa#2693]
This is part of `Result` now: https://github.com/antitypical/Result/pull/132

cc @mdiep, thanks for making a `Result` release!

**Comment by eimantas** [comment]
I've upgraded to 4.0.1 and now I need to `import Result` wherever I use signals (or producers) with `NoError`. Was this the intention of this fix?

**Comment by eimantas** [comment]
Nevermind. My question is addressed in #2704.
