### ISSUE TITLE
Is there any test case to test the lifetime of the observing closures?

### ISSUE THREAD

**Issue by CosynPa** [ReactiveCocoa/ReactiveCocoa#2698]
For example

signal.observeNext { x in }

The closure { x in } should not be retained after the signal terminates.

**Comment by NachoSoto** [comment]
I don't think there's [any test covering that in particular](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoaTests/Swift/SignalLifetimeSpec.swift), but I agree it would be a great thing to test!

**Comment by NachoSoto** [comment]
Done in #2701.
