### ISSUE TITLE
Not compiling with Xcode 7.3 beta 2

### ISSUE THREAD

**Issue by anivaros** [ReactiveCocoa/ReactiveCocoa#2699]
Xcode 7.3 beta 2
ReactiveCocoa - 2.5

Framework linked via cocoapods

<img width="1420" alt="screen shot 2016-02-01 at 19 24 31" src="https://cloud.githubusercontent.com/assets/873387/12723357/2592da70-c91a-11e5-8194-6c900eacd8b6.png">

[buildlog.txt](https://github.com/ReactiveCocoa/ReactiveCocoa/files/112569/buildlog.txt)

**Comment by NachoSoto** [comment]
Please search for existing issues before opening a new one. This is already tracked in https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2684

**Comment by jklausa** [comment]
@NachoSoto I don't think this is the same issue. I *think* that #2684 relates to Swift 2.2 support and problems therein, while this is about RAC 2.5 and some new diagnostics that Xcode 7.3 introduces.

I'm assuming that RAC2.5 is effectively EOL and you have no interest in looking into it anyway? 

On the off chance you do:
AFAICT removing the `__weak` annotations from headers fixes the Xcode errors But my knowledge about Obj-C storage semantics edge-cases runs out at this point. I have no idea if removing it from headers but keeping it in the implementation changes the memory semantics from the original file.

**Comment by apparentsoft** [comment]
Why does it say that the file uses manual reference counting? Probably the user's project is not ARC, at least not that file?

Unrelated, can you even mark method parameters as __weak? What does it do?

**Comment by jklausa** [comment]
>Why does it say that the file uses manual reference counting? Probably the user's project is not ARC, at least not that file?

The file in screenshot is `NSObject+RACPropertySubscribing.h`: https://github.com/ReactiveCocoa/ReactiveCocoa/blob/2.x-maintenance/ReactiveCocoa/NSObject%2BRACPropertySubscribing.h#L81

>Probably the user's project is not ARC, at least not that file?
My project is using ARC, so ¯\_(ツ)_/¯ 

>Unrelated, can you even mark method parameters as __weak? What does it do?

I have no idea - that's what I meant by "knowledge about Obj-C storage semantics edge-cases" running out. 

(if it's not clear by now: I'm having the same issue and I've "worked around" it by removing the `__weak` declarations from the header - I'd be happy to submit a PR if someone who's more knowledgable than me in ARC confirms that it doesn't change the behaviour of the code.)

**Comment by jklausa** [comment]
Eh, nevermind. I think @apparentsoft was right and the OP was including RAC from non-ARC project/file.

What caused the issue for us was that we had `include <ReactiveCocoa/ReactiveCocoa.h` in our `Prefix.pch` - and this caused the Xcode diagnostic to (probably incorrectly) mark it. 

Ripping out RAC from precompiled header fixed it - so this doesn't seem to be a RAC issue after all. Sorry for any confusion caused.

**Comment by anivaros** [comment]
> Probably the user's project is not ARC, at least not that file?
My project under ARC and RAC in Pods project, which under ARC too

**Comment by iworkcloud** [comment]
Do not put the pre-compiled headers can be
