### ISSUE TITLE
Make it work for scripts, or `LLVM ERROR: Program used external function '__TMPdV13ReactiveCocoa14SignalProducer' which could not be resolved!`

### ISSUE THREAD

**Issue by maelp** [ReactiveCocoa/ReactiveCocoa#2703]
I'm trying to use ReactiveCocoa in a script, doing the following

- `echo 'github "ReactiveCocoa/ReactiveCocoa" ~> 4.0' > Cartfile`
- `carthage update`
- `vim script.swift`

```
#!/usr/bin/swift -F Carthage/Build/Mac/

import Foundation
import ReactiveCocoa

let r = SignalProducer<Int, NSError>(values: [1, 2, 3, 4])
  .map { t in print(t) }
  .start()
```

- `chmod u+x script.swift && ./script.swift`

```
LLVM ERROR: Program used external function '__TMPdV13ReactiveCocoa14SignalProducer' which could not be resolved!
```

I know it is possible to load frameworks like this because I could successfully use <https://github.com/izqui/Taylor> in a similar script

I think this has to do with how the `.swiftmodule` is compiled. Could it be possible to change the build to make it possible to use ReactiveCocoa in scripts ?

This post describes a possible solution <https://medium.com/@moski/building-a-web-server-in-swift-d184001ff18e#.djey4ui9c>

**Comment by NachoSoto** [comment]
I've seen this issue is. Unfortunately I don't think there's anything in our control to fix this, so I suggest you file a radar with Apple. `.swiftmodule` is an implementation detail.

I tried this myself and I'm getting a different error:
<img width="453" alt="screen shot 2016-02-02 at 2 57 27 pm" src="https://cloud.githubusercontent.com/assets/685609/12767318/4a41330a-c9bd-11e5-8589-1619cae1e293.png">

Which tells me that maybe `-F Carthage/Build/Mac/` isn't actually working, so the error you're getting is because it's picking up some other version from your derived data directory :/

**Comment by maelp** [comment]
Isn't it something to do with using `-emit-module` as a build option?

**Comment by maelp** [comment]
Perhaps you need to `chmod u+x file.swift` and do `./file.swift` instead of `swift file.swift`

**Comment by NachoSoto** [comment]
> Perhaps you need to chmod u+x file.swift and do ./file.swift instead of swift file.swift

I tried that too, then I get your error: 
```
Program used external function '__TMPdV13ReactiveCocoa14SignalProducer' which could not be resolved!
```

> Doesn't it have something to do with using -emit-module as a build option? -F Carthage/Build/Mac seems to be working because if you use this it will work:

¯\_(ツ)_/¯

**Comment by maelp** [comment]
Yes, we get the same error -- but all the info I've seen (check <https://medium.com/@moski/building-a-web-server-in-swift-d184001ff18e#.djey4ui9c>) seem to link this to properly building the `.swiftmodule` -- not sure how to set that in the `.xcodeproj` so it is done automatically, but I think this was an issue in `izqui/Taylor` and they solved it like this

**Comment by maelp** [comment]
https://github.com/izqui/Taylor/issues/19

**Comment by maelp** [comment]
Comparing <https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa.xcodeproj/project.pbxproj#L2811> and <https://github.com/izqui/Taylor/blob/master/Taylor.xcodeproj/project.pbxproj#L454> I see this difference:

- Taylor:

```
E1ED7D0E1B9CA92600D7E37E /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
...
				DYLIB_COMPATIBILITY_VERSION = 1;
				DYLIB_CURRENT_VERSION = 1;
				DYLIB_INSTALL_NAME_BASE = "@rpath";
				FRAMEWORK_SEARCH_PATHS = (
					"$(inherited)",
					"$(PROJECT_DIR)/Carthage/Build/Mac",
					"$(PROJECT_DIR)/Carthage/Build/iOS",
				);
...
			};
			name = Release;
		};
```

- ReactiveCocoa

```
A9B3155B1B3940610001CB9C /* Release */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = A97451351B3A935E00F48E55 /* watchOS-Framework.xcconfig */;
			buildSettings = {
...
				DYLIB_COMPATIBILITY_VERSION = 1;
				DYLIB_CURRENT_VERSION = 1;
...
			};
			name = Release;
		};
```

No `DYLIB_INSTALL_NAME_BASE`, could it be linked?

**Comment by dmcrodrigues** [comment]
@maelp @NachoSoto this no longer crashes with Xcode 7.3.1 and ReactiveCocoa 4.2.1.

**Comment by NachoSoto** [comment]
Yup, this is indeed fixed.
