### ISSUE TITLE
4.0.1 possibly breaks semver?

### ISSUE THREAD

**Issue by natestedman** [ReactiveCocoa/ReactiveCocoa#2704]
Since `4.0.1` removes the `NoError` type in favor of `Result`'s implementation, after `carthage update` from version `4.0.0`, none of my files with:

- `import ReactiveCocoa`, no `import Result`, and `NoError` used somewhere.
- explicit `ReactiveCocoa.NoError` referenced (which I originally added to fix compiler ambiguity in files with both `import ReactiveCocoa` and `import Result` when using `ReactiveCocoa` `4.0.0` and `Result` `1.0.2`, both of which define `NoError`).

...compile anymore. For the first, I need to add `import Result`, and for the second I need to remove the `ReactiveCocoa.` prefix.

**Comment by NachoSoto** [comment]
That's true :/ I feel like everything is a breaking change in Swift these days. I guess it's kind of late to amend this, and it shouldn't be a problem in the long term, right?

**Comment by JaviSoto** [comment]
Can this be fixed by exposing a:

```Swift
public typealias Result = Result.Result
```

?

**Comment by NachoSoto** [comment]
You mean `public typealias NoError = Result.NoError`?

**Comment by neilpa** [comment]
Technically there could still be fully-qualified usages (e.g. `ReactiveCocoa.NoError`) but that should cover nearly all the cases.

**Comment by JaviSoto** [comment]
Sorry, I meant:

```Swift
public typealias NoError = Result.NoError
```

**Comment by mdiep** [comment]
I'm not sure. There's some definitely weirdness around this.

Here's what prompted me to do the release after getting some :+1:s in slack:

1. https://github.com/Carthage/Commandant made a similar change to use Result's `NoError`

2. I went to upgrade Commandant in Carthage. When I'd done so, I got an error in _ReactiveTask_ that `NoError` was ambiguous.

3. I tried to disambiguate by specifying `Result.NoError`, but then got an error that `Result` was generic and I hadn't specified the types. (Even though `Result` in that context is supposed to refer to the module and not the class.)

4. After updating ReactiveCocoa, everything just worked again.

I'm really sorry if this caused problems for everyone. :disappointed: 

---

```swift
public typealias NoError = Result.NoError
```

This yields the same error:

```
Swift/SignalProducer.swift:4:21: error: reference to generic type 'Result' requires arguments in <...>
typealias NoError = Result.NoError
                    ^
<unknown>:0: note: generic type 'Result' declared here
```

**Comment by NachoSoto** [comment]
Having another built `ReactiveCocoa` in derived data would make Xcode pick it up (did I ever mention how much Xcode sucks?), so maybe that's what happened to you.

**Comment by guidomb** [comment]
@mdiep What do you mean after updating ReactiveCocoa? I am using `4.0.1` and I am experiencing the same problem you described. I nuked `~/Library/Developer/XCode/DerivedData`, clean build and nothing changed.

**Comment by mdiep** [comment]
> What do you mean after updating ReactiveCocoa?

Running `carthage update` to get 4.0.1 fixed the issue I was seeing.

**Comment by guidomb** [comment]
Mmm that didn't solve the problem for me

**Comment by JaviSoto** [comment]
Should be fixed by https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2711

**Comment by JaviSoto** [comment]
@mdiep I'm curious where you tried to add that public typealias and why it didn't work for you.

**Comment by mdiep** [comment]
It seems that this works:

```swift
import enum Result.NoError

public typealias NoError = Result.NoError
```

but this doesn't:

```swift
import Result

public typealias NoError = Result.NoError
```

I didn't even know `import enum` was a thing!

**Comment by eabadjiev** [comment]
@NachoSoto do you plan to release this change soon? `4.0.1` forces me to import `import enum Result.NoError` in all RC files.

Also, will be very helpful to `4.0.1` update changes notes to link this issue and to advice users to quickly workaround with:
```
import enum Result.NoError

public typealias NoError = Result.NoError
```

**Comment by NachoSoto** [comment]
Thanks @eabadjiev. I've updated the release notes to indicate this, linking to this issue. I just mentioned that you need to `import Result` now, which I don't think is that big of a deal.

I considered updating the docs but I'm not sure there's a convenient place to include this.
