### ISSUE TITLE
How to observe method invocation in ViewModel?

### ISSUE THREAD

**Issue by gerardo-navarro** [ReactiveCocoa/ReactiveCocoa#2705]
Hi, I'd like to observe/listen to the invocation of the following method in the RecipeSwipingViewModel:
```
func fillSwipingQueueWith(recipeSwipingCards: [RecipeSwipingCardVM]) { ... }
```

Unfortunately, I cannot get this to work, although I guess it is a pretty common use case. I tried several variations of this:
```
self.viewModel.rac_signalForSelector("fillSwipingQueueWith")...
self.viewModel.rac_signalForSelector("fillSwipingQueueWith:")...
self.viewModel.rac_signalForSelector(Selector("fillSwipingQueueWith:"))...
self.viewModel.rac_signalForSelector("fillSwipingQueueWith:", fromProtocol:NSProtocolFromString("RecipeSwipingViewModel")...
```
What am I missing? Is it actually possible to listen to the method invocation inside another object (without a protocol)? Help is highly appreciated.

Cheers, Gerardo

**Comment by mdiep** [comment]
You probably need to mark the method with `@dynamic` or `@objc` so that the method dispatch happens through the Objective-C runtime. Otherwise Swift is probably doing a static dispatch.

**Comment by gerardo-navarro** [comment]
Thanks a lot. Declaring the method as `dynamic func fillSwipingQueueWith(recipeSwipingCards: [RecipeSwipingCardVM]) { ... }` helped. Be aware that it is not possible to subscribe to private selectors ...
