### ISSUE TITLE
How to wait for a login request to complete with multiple observers

### ISSUE THREAD

**Issue by jarrodrobins** [ReactiveCocoa/ReactiveCocoa#2706]
Hi folks, 

I've mostly been using ReactiveCocoa in the past to simply bind views and view models, and now I'm trying to take the plunge and use it throughout a new project but I'm having trouble getting my head around a couple of things. 

What I want to do is this - 
- Have a networked login request that every other network request needs to call first. 
- If multiple requests are made, they all need to wait until log in completes (eg, let's say I've got a Tab Bar Controller and I quickly tap between them before log in finishes; I don't want multiple login requests fired.)

I've spent a bit of time exploring a few options like queues, looking into things like `flatMap(.Latest)` but if I'm completely honest - I have no idea what I'm doing! :astonished: 

Below's a very basic, dumb implementation which is quickly hacked together and very likely badly implemented. If someone could give me a few pointers into what I need to change it'd be enormously appreciated. My `doSomething` method obviously logs in first, but if multiple calls are made at once they don't wait until the first one finishes as I need them to. 

Can I do something with the `loginValid` property? 

(Also, pointers on generally how I should be structuring this stuff would be great - I'm sure I'm doing many stupid things with this code) 

Thanks! 

```
class FakeBackend: BackendType {

    private var loginResponse = MutableProperty<LoginResponse?>(nil)
    private let loginValid = MutableProperty<Bool>(false)
    
    private var loginProducer: SignalProducer<LoginResponse, NSError>! // <-- implicitly unwrapped optional? Yuck
    
    init() {
        loginValid <~ loginResponse.producer.map { $0 != nil }
        
        loginProducer = SignalProducer { [weak self] observer, disposable in
            guard let _self = self else { return }
            
            if let loginResponse = _self.loginResponse.value {
                print("Already have login details")
                observer.sendNext(loginResponse)
                observer.sendCompleted()
            } else {
                print("Don't have login details, go get them")
                _self.logIn().start(observer)
            }
        }
    }
    
    func doSomething() -> SignalProducer<HomeResponse, NSError> {
        return loginProducer
            .then(SignalProducer<HomeResponse, NSError> { observer, dispoable in
              
                let homeResponse = HomeResponse(title: "My title is this")
                
                observer.sendNext(homeResponse)
                observer.sendCompleted()
            })
    }
    
    private func logIn() -> SignalProducer<LoginResponse, NSError> {
        return SignalProducer { observer, disposable in
            
            print("Calling network login")
            delayToMainThread(1.0, closure: { [weak self] () -> () in
              
                guard let _self = self else { return }
                
                let loginResponse = LoginResponse(accessToken: "MyAccessToken")
            
                _self.loginResponse.value = loginResponse
                
                observer.sendNext(loginResponse)
                observer.sendCompleted()
            })
        }
    }
}
```

**Comment by hh-components** [comment]
I think it's better to use a NSLock

something like below 

    var headers = MutableProperty(["TICKET":"", "DEVICE":""])

    func GET(path:String!, params:[String: String]) -> SignalProducer<[String: AnyObject], NSError> {
        let reqSignal = SignalProducer<[String: AnyObject], NSError> {
            sink, dispose in
            manager.request(Router.GET(path: path, params: params))
            .validate()
            .responseHHJSON({ (response) -> Void in
                if let error = response.result.error {
                    sink.sendFailed(error)
                } else {
                    sink.sendNext(response.result.value!)
                    sink.sendCompleted()
                }
            })
        }
        
        return reqSignal.flatMapError { (error) -> SignalProducer<[String: AnyObject], NSError> in
            return HHHttp.refreshAT()
            }.then(reqSignal)
    }

    private static func refreshAT() -> SignalProducer<[String: AnyObject], NSError> {
        return SignalProducer<[String: AnyObject], NSError> {
            sink, dispose in
            if atLock.tryLock() {
                Alamofire.Manager.sharedInstance.request(.POST, "http://example.com/passport/auth/refresh")
                    .responseHHJSON({ (response) -> Void in
                        if let error = response.result.error {
                            sink.sendFailed(error)
                        } else {
                            let v = response.result.value!["data"]
                            headers.value.updateValue(v!["at"] as! String, forKey: "TICKET")
                            sink.sendCompleted()
                        }
                        atLock.unlock()
                    })
            } else {
                headers.signal.observe(Observer(next: { value in
                    print("get headers from local: \(value)")
                    sink.sendCompleted()
                }))
            }
        }
    }

The point is when facing with parallel requests, only one of them could trigger a refresh token request, others wait for token refreshed signal, i.e. a MutableProperty in above code

As u can see, reqSignal gets an Error of not authorized, and we flatMap that error (catch in RAC2 and 3) to a refreshToken Signal, when it completed, we request again, this time everything will be OK 

    return reqSignal.flatMapError { (error) -> SignalProducer<[String: AnyObject], NSError> in
        return HHHttp.refreshAT()
        }.then(reqSignal)

**Comment by RuiAAPeres** [comment]
@jarrodrobins have you found a solution to your problem, if so please close this issue. If on the meantime you haven't, be sure to let us know!

**Comment by jarrodrobins** [comment]
@RuiAAPeres I haven't found a clean solution to this problem that uses RAC properly, though it's not something I've looked at for a while if I'm honest. I'm still relatively new at RAC and thought tackling a non-trivial problem would be a good way to learn it since it seemed like the sort of thing it'd be able to simplify.

Though perhaps it's harder than I realised as my more FRP experienced colleagues don't seem to know of a nice clean way of doing it either!

In the meantime I've just gotten around it in other ways (such as just having a big fat loading screen while logging in, though it's hardly ideal).

**Comment by RuiAAPeres** [comment]
@jarrodrobins let me give you hand then! ☺️

You have two common problems:

1. N blocks of work, depending on the previous one (`N`th depends on (`N - 1`)th).
2. You want to avoid doing a block of work multiple times, but do it once and cache it. 

Fortunately RAC excels at both (compared to GCD/NSOperations).

The **1.** use case is normally solved with the `flatMap` operator with the `.Latest` strategy.  So it would look like this:

````
loginSignalProducer.flatMap(.Latest, transform: { loginResponse in 
   return createOtherServiceSignalProducer(loginResponse)
})
```

To make it pure and avoid mutable state, the `loginResponse` object is passed to your `createOtherServiceSignalProducer`. This `createOtherServiceSignalProducer` could be a function with a signature resembling this: `LoginResponse -> SignalProducer<HomeResponse , Error>`. 

The **2.** step has been solved by #2639 (and I advise you reading the whole PR). You will notice that the initial solution for @NachoSoto's problem, was via a property as well (**and it can still make sense in your case!** Hence recommending reading the PR). I haven't used this operator, myself, so I would recommend [testing its behaviour in a controlled environment](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoaTests/Swift/SignalProducerSpec.swift#L1977#L2009) and [carefully read its description](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L1186#L1206). 

In any case, it could look like this (**not tested the code**):

```swift
class FakeBackend: BackendType {

    private let loginProducer: SignalProducer<LoginResponse, NSError >

    init() {
        loginProducer = logIn().replayLazely(1)
    }

    func homeResponse() -> SignalProducer<HomeResponse, NSError> {
        return loginProducer.flatMap(.Latest, transform: homeResponse)
    }

    private func homeResponse(loginResponse: LoginResponse) -> SignalProducer<LoginResponse, NSError> {

            return SignalProducer<HomeResponse, NSError> { observer, dispoable in

                let homeResponse = HomeResponse(title: "My title is this")

                observer.sendNext(homeResponse)
                observer.sendCompleted()
            }
    }

    private func logIn() -> SignalProducer<LoginResponse, NSError> {
        return SignalProducer { observer, disposable in

            print("Calling network login")
            delayToMainThread(1.0, closure: { [weak self] () -> () in

                guard let _self = self else { return }

                let loginResponse = LoginResponse(accessToken: "MyAccessToken")

                _self.loginResponse.value = loginResponse

                observer.sendNext(loginResponse)
                observer.sendCompleted()
            })
        }
    }
}
```

I am unsure why you are doing something like `delayToMainThread`, but there are better of ways of [deferring](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L741#L743)/[cancelling](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L602#L604) work.

**Comment by jarrodrobins** [comment]
Wow, thanks for the super detailed response @RuiAAPeres! I'm currently at work but will have a look into this in the next day or two and see how I go.

The `delayToMainThread` is merely a placeholder to mimic networking in my toy example. It'd never be used in real code! But you are correct that there are better ways to handle it. ;-)

**Comment by jarrodrobins** [comment]
OK, I got around to taking a look at this, and it works beautifully! Thanks very much. Here's my tidied up version of the code for anyone who might be interested -

```
class FakeBackend: BackendType {

    private var login: SignalProducer<LoginResponse, NSError>
    
    init() {
        login = SignalProducer { observer, disposable in
            print("Logging in...")
            
            // we'd actually make a network call here, but for demo purposes
            // let's just return some dummy data.
            let loginResponse = LoginResponse(accessToken: "MyAccessToken")
            
            print("Logged in!")
            
            observer.sendNext(loginResponse)
            observer.sendCompleted()
        }.replayLazily(1)
    }
    
    func loadHomeScreen() -> SignalProducer<HomeResponse, NSError> {
        return login
            .flatMap(.Latest, transform: homeResponse)
    }
    
    private func homeResponse(loginResponse: LoginResponse) -> SignalProducer<HomeResponse, NSError> {
        return SignalProducer<HomeResponse, NSError> { observer, disposable in
            print("Aaaand, we've gotten our HomeResponse.")
            
            let homeResponse = HomeResponse(title: "My title is this")
            observer.sendNext(homeResponse)
            observer.sendCompleted()
        }
    }
}
```
