### ISSUE TITLE
Create a signal producer that is immediately interupted

### ISSUE THREAD

**Issue by CosynPa** [ReactiveCocoa/ReactiveCocoa#2709]
We have signal producer initializers and static functions that create a signal producer that immediately fails, immediately completes, or immediately sends a next. So why there is not initializer to create a signal producer that is immediately interrupted?

**Comment by mdiep** [comment]
Usually the absence of something means that someone hasn't needed it yet. But in this case, I'm not sure why you'd want a producer that immediately interrupts, or what exactly that would mean.

**Comment by CosynPa** [comment]
I was doing a flatMap to immediately interrupted producer.

    producer.flatMap(.Latest) { [weak self] x -> SignalProducer<Int, NoError> in
        if self == nil {
            return SignalProducer { observer, _ in
                observer.sendInterrupted()
            }
        } else {
            return // a normal signal producer
        }
    }

After read your post, I rethought about it, maybe usually there is no difference from `SignalProducer.empty`?

**Comment by mdiep** [comment]
Usually you'll want empty here. I think interrupted would end the signal, so you'd stop listening for new `x`s.

**Comment by neilpa** [comment]
Actually, [inner interrupted events are ignored](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/860564659d594b6e4ac944472587d6b0e0ba5387/ReactiveCocoa/Swift/Flatten.swift#L63-L64) on `flatten`ed signals. However, the idiomatic approach is to return `empty`.
