### ISSUE TITLE
Equivalent of the Elm's foldp function and past dependent signals in RAC

### ISSUE THREAD

**Issue by AlexanderKaraberov** [ReactiveCocoa/ReactiveCocoa#2712]
As far as I know, ReactiveCocoa borrowed a lot of FRP concepts from the [Elm](http://elm-lang.org) language. I'm interested in the equivalent of the Elm's [foldp](http://package.elm-lang.org/packages/elm-lang/core/1.1.0/Signal#foldp) ("fold from the past") function, which:
> Create a past-dependent signal. Each update from the incoming signals will be used to step the state forward. The outgoing signal represents the current state.

In the Elm Architecture it  actually is used to update application state. [Here](http://elm-lang.org/guide/reactivity) we can read: 
> All of the state of our application lives in the foldp, and we mainly use signals on the borders to route incoming and outgoing events.

**Comment by neilpa** [comment]
The equivalent RAC operator is [scan](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/860564659d594b6e4ac944472587d6b0e0ba5387/ReactiveCocoa/Swift/Signal.swift#L692-L698).

**Comment by RuiAAPeres** [comment]
@AlexanderKaraberov if @neilpa's answer helped you, please close this issue. 👍
