### ISSUE TITLE
Question: How to disregard events when other event is executed?

### ISSUE THREAD

**Issue by gerardo-navarro** [ReactiveCocoa/ReactiveCocoa#2724]
Let's say you are observing a property that changes quite often, e.g. a queue that should be refilled when it is below a threshold?

```
queue.rac_valuesForKeyPath("count", observer: self)
  .toSignalProducer()
  .filter({ (queueCount: AnyObject?) -> Bool in
     let newQueueCount = queueCount as! Int
     return newQueueCount < 10
  })
  .on(next: { _ in
     // Refilling the queue asynchronously and takes 10 seconds
     self.refillQueue(withItemCount: 20)
  })
  .start()
```
When the queue is empty, the next handler will be triggered and fills the queue. While filling the queue, the SignalProducer sends a new next event because the count property changed to 1 – and another and another. But I do not want the next handler to be triggered. Instead, I'd like it trigger once everytime the queue falls below that threshold.

How can I do this in the best way? Are there any helpful event stream operations? Any ideas?

Cheers,

Gerardo

**Comment by nmtitov** [comment]
As a guess, you could create two signal producers, one filtering `newQueueCount >= 10` and the other tracking `newQueueCount < 10`. Then use `combineLatest` to get results once both get their `next`. If I'm right, you'll get `next` every time once your queue was longer than 10, but then dropped down to 9 or less.

**Comment by iv-mexx** [comment]
I think you could use [`skipRepeats`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L712).

If you do something like this

```swift
bufferCount  // Sends every change in the buffer count
  .map { $0 > threshold }  // Sends true / false for every buffer-count change
  .skipRepeats() // Sends true / false only when there's a change from true -> false or false-true
  .filter{ !$0 } // Sends only false every time the buffer count changes from above threshold to below threshold
  .startWithNext { _ [weak self] in self?.refillQueue() }
```

it should refill the queue every time the queue count falls from above threshold to below threshold. I guess it will also refill the queue initially if the queue count is initially below the threshold, because `skipRepeats` will always pass the first value.
Beware, I just wrote this here and did not test it.

**Comment by ikesyo** [comment]
Closing since this was answered already.
