### ISSUE TITLE
New signal is created when cell is resued

### ISSUE THREAD

**Issue by mankatcheung** [ReactiveCocoa/ReactiveCocoa#2725]
I'm making a tableView with custom tableViewCell which contains a button. Whenever I click on the button, a event is sent through the signal and print a sentence.
```swift
// ViewController.swift
func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCellWithIdentifier("CustomCell", forIndexPath: indexPath) as! CustomCell
    cell.buttonClickedSignal?.startWithNext { _ in
        print("button at cell \(indexPath.row) is clicked")
    }
}

// CustomCell.swift
class CustomCell: UITableViewCell {
    private let button: UIButton = UIButton()
    var buttonClickedSignal: SignalProducer<AnyObject?, NSError>?

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        self.addSubview(self.button)
        self.likeButtonTouchSignal = self.button.rac_signalForControlEvents(.TouchUpInside).toSignalProducer()
    }
}
```

However, after scrolling the tableview and then clicking on a button, it printed out more than one sentence even I only click on one button.
```
button at cell 0 is clicked
button at cell 1 is clicked
button at cell 2 is clicked
button at cell 0 is clicked
```
I wonder whether it's the problem due to reuse of cell. Am I doing anything wrong?

**Comment by avalanched** [comment]
`cell.buttonClickedSignal.takeUntil(cell.rac_prepareForReuseSignal)`

**Comment by gkaimakas** [comment]
Had a very similar issue the other day

I was creating a new signal producer that did some work depending when events came from some signals, and the producer was firing events multiple times as if it somehow kept a history of all the previous events fired. The first time it fired 1 event, the 2 time 2 an so on

**Comment by joshbax** [comment]
@gkaimakas 
Assuming this signal producer gets started when the central manager receives a connected peripheral? If the peripheral goes through a quick disconnect/reconnect cycle, which happens often with the hardware I'm using, then you may unintentionally start that producer repeatedly adding unwanted observers to your stream signals. 
Not sure if that applies, but I had to deal with a similar issue because of odd hardware behavior.
