### ISSUE TITLE
Missing short `on` methods

### ISSUE THREAD

**Issue by AvdLee** [ReactiveCocoa/ReactiveCocoa#2726]
Right now, when using the `on` method, you'll get an autocompletion showing the following:

<img width="679" alt="screen shot 2016-02-16 at 17 36 04" src="https://cloud.githubusercontent.com/assets/4329185/13083103/e337e146-d4d3-11e5-9bc4-59b4098e20b1.png">

When you only need next and failed, you have to remove all other completions each time.
Somehow I'm missing the good old `doError`, `doNext` etc.

I'm thinking about a feature request to add methods like:

```swift
extension SignalProducer {
    func onNext(nextClosure:(object:Value) -> ()) -> SignalProducer<Value, Error> {
        return self.on(next: nextClosure)
    }
    
    func onFailed(callback:(error:Error) -> () ) -> SignalProducer<Value, Error> {
        return self.on(failed: { (error) -> () in
            callback(error: error)
        })
    }
}
```

Curious about the meaning of others, am I the only one finding this annoying?

**Comment by NachoSoto** [comment]
This seems more like an IDE issue. I agree it's annoying to have to remove the extra parameters you don't need, but I think it's not worth introducing and maintaining unnecessary overloads.
