### ISSUE TITLE
Signal based on MutableProperty not completing

### ISSUE THREAD

**Issue by edwardIshaq** [ReactiveCocoa/ReactiveCocoa#2727]
I have SignalProducer based on a MutableProperty.
Which in my understanding would not complete by itself.

let property = MutablePropert<String>("")

let flatMappedSignal = 
property
  .producer
  .flatMap(FlattenStrategy.Latest) { str in 
     return signalFrom(str) //Which does complete if run alone
}

What I"m seeing is that flatMappedSignal is not Completing even though the signalFrom(...) does complete if fired alone.

Any idea what might be happening here ? 
My goal is that flatMappedSignal would complete once the signalFrom would complete as well.

From FlattenStrategy comments: 

>     /// Only the events from the latest input producer should be considered for
    /// the output. Any producers received before that point will be disposed of.
    ///
    /// The resulting producer will complete only when the producer-of-producers and
    /// the latest producer has completed.

I'm honestly having trouble deciphering the comment.
what would be the "producer-of-producers" in this case ? 
the flatMappedSignal?

**Comment by CosynPa** [comment]
The "producer-of-producers" is equivalent to the `property.producer` in this context, i.e. the `flatMappedSignal` will complete only when the `property.producer` and the latest `signalFrom(str)` has completed.

**Comment by edwardIshaq** [comment]
okay, so this bit is more clear now.
So in your opinion, what would be the best way to complete the signal? if based  on producer-of-producers ? 
Should I wrap it in another signal that terminates on some arbitrary criteria ?

**Comment by CosynPa** [comment]
a `MutableProperty`'s `producer` will complete when the property deinit.

**Comment by ahmadbaraka** [comment]
As it has been pointed out, `flatMappedSignal` does not complete because it will only complete when the property `deinit` and the latest `signalFrom(str)` completes as well.

It's not clear what you're trying to implement but I have a suggestion if _you want to have a signal to run only once when your property changes_, I would use:

```
let property = MutableProperty("")

let flatMappedSignal =  property.producer
.skip(1) //Skip initial/current value if needed
.take(1) //Take only 1 change
.flatMap(FlattenStrategy.Latest) { str in 
return signalFrom(str) //Which does complete if run alone
}
```
You may need to filter Indistinct changes as well.

**Comment by edwardIshaq** [comment]
Thank you guys for pointing out this info.

I guess take 1 would do the trick. I might have to re-evaluate the structure of this signal.
