### ISSUE TITLE
Proper use of replayLazily in ReactiveCocoa 4

### ISSUE THREAD

**Issue by steffendsommer** [ReactiveCocoa/ReactiveCocoa#2728]
After reading that `replayLazily` was [added](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2639) to ReactiveCocoa 4, I wanted to try it out, but after experiencing some issues, I'm hoping to get some advice.

I have the following:
```swift
        let fetchMenu = Menu.fetchTodaysMenuFromCacheOrRemote(self.menuAPI)
            .replayLazily(1)

        let menuProducer = merge([active, inactive])
            .filter { $0 }
            .mapError { _ in
                return Menu.FetchMenuError.UnknownError
            }
            .flatMap(.Latest) { _ in
                return fetchMenu
            }
```

The type of `menuProducer` is `SignalProducer<Menu, FetchMenuError>`. Basically the intention of the above code is: whenever the view gets active I want to fetch the menu. Because there are multiple subscribers to `menuProducer` I've added the `replayLazily` in order to avoid executing this code multiple times when the subscribers come in.

Although the above code works, the issue is that now, when the user puts the app into the background and bring it back to the foreground, a menu is not fetched. This is obviously because of `replayLazily`. So.. how do I avoid running this code multiple times when multiple subscribers subscribe to this producer, but still being able to run the code every time the view gets active?

**Comment by mdiep** [comment]
It looks to me like you want to move the `replayLazily` inside the `flatMap`.

```swift
  let fetchMenu = Menu.fetchTodaysMenuFromCacheOrRemote(self.menuAPI)

        let menuProducer = merge([active, inactive])
            .filter { $0 }
            .mapError { _ in
                return Menu.FetchMenuError.UnknownError
            }
            .flatMap(.Latest) { _ in
                return fetchMenu.replayLazily(1)
            }
```

As you wrote it, the menus will only every be fetched once. As I wrote it, they'll be fetched once per state change.

**Comment by s0mmer** [comment]
Thanks for helping out @mdiep! This was also something I looked into, however doing that, does not seem to fix my problem. Actually, moving the `replayLazily` inside the `flatMap` and not having it at all results in the same output if the `Menu.fetchTodaysMenuFromCacheOrRemote()` function is set to print in the console.

So basically, the suggested approach will re-execute the `Menu.fetchTodaysMenuFromCacheOrRemote()` for each subscriber being added to `menuProducer`. In this case the log will ouput
```
menu loaded
menu loaded
menu loaded
menu loaded
```

Because I'm adding 4 subscribers to `menuProducer`.

**Comment by mdiep** [comment]
Oh, right. Sorry. It should be outside the `flatMap`.

```swift
  let fetchMenu = Menu.fetchTodaysMenuFromCacheOrRemote(self.menuAPI)

        let menuProducer = merge([active, inactive])
            .filter { $0 }
            .mapError { _ in
                return Menu.FetchMenuError.UnknownError
            }
            .flatMap(.Latest) { _ in
                return fetchMenu
            }
            .replayLazily(1)
```

How embarrassing for me. :relaxed:

**Comment by s0mmer** [comment]
Doing that will never fetch the menu - the log will never print anything and a breakpoint in the `flatMap` will never be hit. I'm not sure I understand why?

**Comment by mdiep** [comment]
That looks correct to me. It's hard to say why it's not working without seeing the rest of the code.

**Comment by s0mmer** [comment]
I *think* I've narrowed it down to `active` and `inactive` causing the error:

```swift
let active = NSNotificationCenter.defaultCenter().rac_addObserverForName(UIApplicationDidBecomeActiveNotification, object: nil)
    .toSignalProducer()
    .map { _ in
        true
    }

let inactive = NSNotificationCenter.defaultCenter().rac_addObserverForName(UIApplicationWillResignActiveNotification, object: nil)
    .toSignalProducer()
    .map { _ in
        false
    }
```

If I replace those signals with e.g:
```swift
let (activeInactiveProducer, observer) = SignalProducer<Bool, NSError>.buffer(Int.max)
```

Then it seems to work. Is there any limitation on e.g. `rac_addObserverForName` that would explain this behaviour?

**Comment by NachoSoto** [comment]
> Then it seems to work. Is there any limitation on e.g. rac_addObserverForName that would explain this behaviour?

Hmm I can't think of anything. Can you add logs to see if `active` and `inactive` are emitting values the way you expect?

**Comment by s0mmer** [comment]
Removing `replayLazily` makes the menu fetch trigger when putting the app in the background/foreground as expected (also verifying using logs).

If it helps, the source file can be viewed [here](https://github.com/s0mmer/TodaysReactiveMenu/blob/feature/update-json-decoder/TodaysReactiveMenu/ViewModel/TodaysMenuViewModel.swift#L74).

**Comment by s0mmer** [comment]
@mdiep & @NachoSoto: I managed to reproduce the problem with a very small amount of code:

```swift
// Handle view being active/inactive
let active = NSNotificationCenter.defaultCenter().rac_addObserverForName(UIApplicationDidBecomeActiveNotification, object: nil)
    .toSignalProducer()
    .on(next: { _ in
        print("active")
    })

let inactive = NSNotificationCenter.defaultCenter().rac_addObserverForName(UIApplicationWillResignActiveNotification, object: nil)
    .toSignalProducer()
    .on(next: { _ in
        print("inactive")
    })

let foo = merge([active, inactive])
    .on(next: { _ in
        print("merged active/inactive next")
    })
    .replayLazily(1)

foo.startWithNext { _ in
    print("1st subscriber received next")
}

foo.startWithNext { _ in
    print("2nd subscriber received next")
}
```

**Without** adding the `replayLazily()`, the log will show (as expected):
```
active
merged active/inactive next
1st subscriber received next
active
merged active/inactive next
2nd subscriber received next
```

As soon as I add the `replayLazily()`, no output is shown in the console. Unless I'm misunderstanding the operator, I would expect each subscriber to receive the next value whenever the `active`/`inactive` changes. Any input is highly appreciated.

**Comment by mdiep** [comment]
Yeah, this looks like a bug to me. I can reproduce it.

**Comment by NachoSoto** [comment]
Weird, I don't know what to make of this, or what part exactly is failing, so I don't know how to even write a failing test :/

**Comment by mdiep** [comment]
The merge isn't a necessary part of the test. The signal inside the `replayLazily` is subscribed to before the `next` is sent, but it doesn't propagate for some reason. Seems to be an issue with RAC2 + `toSignalProducer` + `replayLazily`?

**Comment by NachoSoto** [comment]
@s0mmer does this happen if you use `NSNotificationCenter.rac_notifications` instead of the `RAC 2` method + `toSignalProducer`?

**Comment by s0mmer** [comment]
@NachoSoto using `NSNotificationCenter.defaultCenter().rac_notifications(UIApplicationDidBecomeActiveNotification)` and `NSNotificationCenter.defaultCenter().rac_notifications(UIApplicationWillResignActiveNotification)` using the same example as before, results in the same.

**Comment by steffendsommer** [comment]
🎉 Thanks for helping out @NachoSoto and @mdiep - looking forward to give it a try with the fix.
