### ISSUE TITLE
Alamofire integration for ReactiveCocoa 4, and a list of ReactiveCocoa4 projects?

### ISSUE THREAD

**Issue by victorlin** [ReactiveCocoa/ReactiveCocoa#2729]
Hey guys, I am using ReactiveCocoa 4 for my company's iOS project with Alamofire, search around didn't find any library for integration at this moment, only found it mentioned at #2697

So I built our own here:

https://github.com/envoy/ReactiveAlamofire

can be used easily like this

```Swift
import Alamofire
import ReactiveCocoa
import ReactiveAlamofire

Alamofire.request(.GET, "http://httpbin.org/get?foo=bar")
    .responseProducer()  // Make the Alamofire.Request to a ResponseProducer (SingalProducer)
    .parseResponse(Request.JSONResponseSerializer()) // Parse response with JSONResponseSerializer
    .startWithNext { resp in
        print(resp.result.value)
    }
```

Is there any place I can look for ReactiveCocoa 4 relative projects? or I can post it on? so that I don't need to rebuild the wheel if somebody already built it and it fits our need.

**Comment by eimantas** [comment]
There's `NSURLSession.rac_dataWithRequest()` that accepts `NSURLRequest` as a parameter. It returns a signal producer that has `<(NSData, NSURLResponse), NSError>` data types. I use it with no need for Alamofire. Usually it takes one `map` method to make my own generic error handling and parsing into JSON (or extra `map` calls to other data types).

**Comment by victorlin** [comment]
@eimantas The reason I want to have Alamofire integration despite there is already `NSURLSession.rac_dataWithRequest()`, is I want to leverage parsers and other handy stuff, like server trust policy

```Swift
let serverTrustPolicies: [String: ServerTrustPolicy] = [
    "api.example.com": .PinCertificates(
        certificates: ServerTrustPolicy.certificatesInBundle(),
        validateCertificateChain: true,
        validateHost: true
    )
]
// default manager
self.manager = Alamofire.Manager(
    serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies)
)
```

I can also use `request.validate` for status validation. Another reason is I want to provide some handy pattern for sending requests, for example, I have one `paginate` pattern for iterating over pages

```Swift
    /**

     Returns a SignalProducer which generates result of page over pages
      - Parameter onScheduler: the scheduler pagination to run on
      - Parameter nextRespProducer: the function accepsts an optional response argument, when it's nil, it means it's the first page,
                                   then the function should return the first ResponseProducer, when it's not nil, the function should parse the response
                                   and return ResponseProducer for the next page. If there is no next page, it should return nil
      - Returns: SignalProducer for pagination ResponseProducer

     Example:

     ```
     SignalProducer<(NSData, NSURLResponse), NSError>.paginate(UIScheduler()) { resp in
        // resp is nil, return the ResponseProducer for the first page
        guard let wrappedResp = resp else {
            return api.getEntries(0, limit: 10)
        }
        // if we don't have next page, just return nil
        guard let offset = nextPageOffset(wrappedResp) else {
            return nil
        }
        // return the ResponseProducer for the next page
        return api.getEntries(offset, limit: 10)
     }
        .flatten(FlattenStrategy.Concat) // flatten all ResponseProducer by concat
        .startWithNext { (data, resp) in
            // page by page data will be sent here
        }

     ```

    */
    @warn_unused_result(message="Did you forget to call `start` on the producer?")
    static func paginate(scheduler:SchedulerType, nextRespProducer: ((resp:Value?) -> PageResponseProducer?)) -> SignalProducer<PageResponseProducer, Error> {
        return SignalProducer<PageResponseProducer, Error> { (observer, disposable) in
            var setupRespProducer:((respProducer:PageResponseProducer) -> PageResponseProducer)!
            setupRespProducer = { (respProducer:PageResponseProducer) -> PageResponseProducer in
                return respProducer
                    // We need to delay in scheduler, otherwise if the ResponseProducer returns an immediate
                    // value, as we are already processing an event, it will result in dead lock
                    .observeOn(scheduler)
                    .on(event: { event in
                        switch event {
                        case let .Next(value):
                            if let nexProducer = nextRespProducer(resp: value) {
                                observer.sendNext(setupRespProducer(respProducer: nexProducer))
                            } else {
                                observer.sendCompleted()
                            }
                        case .Interrupted:
                            observer.sendInterrupted()
                        case .Completed:
                            break
                        case let .Failed(error):
                            observer.sendFailed(error)
                        }
                    })
            }

            disposable.addDisposable {
                observer.sendInterrupted()
            }

            if let firstRespProducer = nextRespProducer(resp: nil) {
                observer.sendNext(setupRespProducer(respProducer: firstRespProducer))
            }
        }
    }
```

it's not added into the lib though, issue opened here https://github.com/envoy/ReactiveAlamofire/issues/1

**Comment by aehlke** [comment]
Check out Moya

**Comment by RahulKatariya** [comment]
Checkout [Reactofire](https://github.com/RahulKatariya/Reactofire) by me. It is built on ReactiveCocoa, Gloss and Alamofire.

**Comment by justinmakaila** [comment]
[Moya](https://github.com/Moya/Moya) is the bomb. Provides support for all common response mapping, and also is easily extensible because it provides a straight RAC integration via `ReactiveMoya`
