### ISSUE TITLE
Action lead to memory leak

### ISSUE THREAD

**Issue by killa123** [ReactiveCocoa/ReactiveCocoa#2730]
```swift
class ViewModel {
    var action:Action<Void,Void,NoError>?
    
    init() {
        action = Action(actionLeakSignal) //leak
        action = Action(actionSignal()) //no leak
    }
    
    func actionSignal() -> () -> SignalProducer<Void,NoError> {
        return {
            return SignalProducer.empty
        }
    }
    
    func actionLeakSignal() -> SignalProducer<Void,NoError> {
        return SignalProducer.empty
    }
}
```

when I use the ```actionLeakSignal``` to init the Action, ```executeClosure``` has a strong reference to ViewModel instance.
I have to use ```actionSignal``` which return a closure,but I think the method look like dirty.I hope it will exist a elegant method to avoid the leak

**Comment by filblue** [comment]
It has nothing to do with action. If the `actionLeakSignal` does not depend on ViewModel instance, make it static. Otherwise action holding strong ref to VM is the correct behaviour.

**Comment by ikesyo** [comment]
Yes, this is not a issue of ReactiveCocoa itself. Closing this. Thanks for the answer @filblue!
