### ISSUE TITLE
Do not hide keyboard on pressing return button

### ISSUE THREAD

**Issue by jasvindersingh-evon** [ReactiveCocoa/ReactiveCocoa#2734]
Hello,

My project is a mix of Swift and Objective C.

I am using ReactiveCocoa 2.1.8 version in my project. I have added it using pods and added the header file in Bridging Header.

I have 2 text fields named Email & Password. I want to use Keyboard "Next" button when I am on Email Field and "Go" Button when I am on Password Field.

I am using the below code to move to the Password field. Added all this code in `viewDidLoad`

```
emailField.rac_signalForControlEvents(UIControlEvents.EditingDidEndOnExit).subscribeNext({ (AnyObject) -> Void in
            passwordField.becomeFirstResponder()
        })
```

When I am on Password Field. I am displaying Keyboard with "Go" button as the return. I don't want to hide the keyboard if there is no text in the Password field. But with the below code it is hiding always. I have given becomeFirstResponder but still the keyboard is hiding.

```
passwordField.rac_signalForControlEvents(UIControlEvents.EditingDidEndOnExit).subscribeNext({ (AnyObject) -> Void in
        if (self.passwordField.text?.characters.count > 0){
            self.logInFromEmail(self.loginBtn)
        }else{
            self.passwordField.becomeFirstResponder()
        }
    })
```

Please help me. I do not want to hide the keyboard on "Go" button when no text is there in Password Field

**Comment by RuiAAPeres** [comment]
```swift
passwordField.rac_signalForControlEvents(UIControlEvents.EditingDidEndOnExit).subscribeNext({ (AnyObject) -> Void in
        if (self.passwordField.text?.characters.count > 0){
            self.logInFromEmail(self.loginBtn)
        }else{
            self.passwordField.becomeFirstResponder()
        }
    })
```

Looking at your code, there is nothing that would make the keyboard resign. You must have something else that is making it behave this way. Do a quick search for `.resignFirstResponder()` or `.endEditing(true)` in your file. 

Also, you should be careful with retain cycles:

1. You probably have a strong ref to the `passwordField`. (via a strong property, or because it is retained by its super view which you retain).
2. You reference it inside the `subscribeNext`. 

So:

```swift
passwordField.rac_signalForControlEvents(UIControlEvents.EditingDidEndOnExit).subscribeNext {[weak self] _ in
        
        guard weakSelf = self else { return }

        if (weakSelf.passwordField.text?.characters.count > 0){
            weakSelf.logInFromEmail(weakSelf.loginBtn)
        }else{
            weakSelf.passwordField.becomeFirstResponder()
        }
    } 
```
