### ISSUE TITLE
Send current next/interrupted/error/whatever immediately when adding an observer

### ISSUE THREAD

**Issue by davedelong** [ReactiveCocoa/ReactiveCocoa#2736]
I've got a simple signal to report on what applications are currently running:

    public let RunningApps: Signal<Array<NSURL>, NoError> = {
        let property = DynamicProperty(object: NSWorkspace.sharedWorkspace(), keyPath: "runningApplications")
        let producer = property.producer.map { $0 as? Array<NSRunningApplication> ?? [] }
            .map {
                $0.map { $0.bundleURL! }
            }
            .skipRepeats { $0 == $1 }
    
        let (signal, _) = producer.start()
        return signal
    }()

(I added a `.start()` method to `SignalProducerType` that returns the `Signal` and `Disposable` as a tuple)

When I attach an observer to this signal, I'd like that observer to immediately get notified about what applications are currently running.  How would I do this?

**Comment by davedelong** [comment]
I have other examples of Signals that don't do what I want that are just regular signals (created with `Signal.pipe()`); this is not limited to just `SignalProducers`.

**Comment by davedelong** [comment]
For example:

    public let SymlinkSignal: Signal<NSURL, NoError> = {
        let (s, d) = Signal<NSURL, NoError>.pipe()

        fileMonitor.handler = { _ in
            d.sendNext(resolvedSymlinkURL())
        }
    
        d.sendNext(resolvedSymlinkURL())
        return s.skipRepeats()
    }()

**Comment by NachoSoto** [comment]
You're going in the right direction, but the last part is what's giving you trouble: converting the stream to a `Signal`. `Signal`s are **controlled by the emitter**, and **they guarantee that all subscribers will see the same version of the the events over time**. For this reason, if you want to make the stream always start with its latest value you'll want to expose the `SignalProducer` instead. Alternatively, you might want to expose the `PropertyType` instead, so that clients can either get the current value, or subscribe to its `.signal`.

**Comment by davedelong** [comment]
So it sounds like I should be exposing *everything* as `SignalProducers` instead, so that things that want information can generate their own individual signals, instead of having everyone schlep off the same signal?

**Comment by davedelong** [comment]
(Thinking out loud)

But how would this play in to other parts of my app where signals are controlled by finite resources (I'm using `dispatch_sources` to monitor file events, and then surface those up through to signals). Would I need to make my dispatch sources send the events to the Producers instead of the Signals?

**Comment by NachoSoto** [comment]
> So it sounds like I should be exposing everything as SignalProducers instead

Not everything! Things like button touches are a good example of a `Signal`. Or anything that you want a guarantee that won't have side effects on subscription.

> so that things that want information can generate their own individual signals, instead of having everyone schlep off the same signal?

Hmm what do you mean? 

> (I'm using dispatch_sources to monitor file events, and then surface those up through to signals). Would I need to make my dispatch sources send the events to the Producers instead of the Signals?

That sounds like a good case for `Signal`, unless you want to control lifetime via side effects of a producer.

**Comment by davedelong** [comment]
> > so that things that want information can generate their own individual signals, instead of having everyone schlep off the same signal?
>
> Hmm what do you mean?

As I understand it, a `SignalProducer` is like a generator of signals. In the case of the `RunningApps` signal, I have a single signal, and everyone mooches off the same signal by calling `observeNext` on the signal itself.

But if I change it to a `SignalProducer`, then that means that everyone actually gets their own unique `Signal` (one observer per signal vs many observers per signal).

Is the logic to observe the key path duplicated in each signal? Or is each generated signal still controlled by the producer, which is doing the observing?

And wouldn't I still have the same problem? I would call `start` on the `SignalProducer`, get back a signal, but then when I call `observeNext` on that signal, nothing would get reported...

> > (I'm using dispatch_sources to monitor file events, and then surface those up through to signals). Would I need to make my dispatch sources send the events to the Producers instead of the Signals?
> 
> That sounds like a good case for Signal, unless you want to control lifetime via side effects of a producer.

Then how would I make those dispatch_source-controlled signals send the current value as soon as something begins observing it?

**Comment by NachoSoto** [comment]
> Is the logic to observe the key path duplicated in each signal? Or is each generated signal still controlled by the producer, which is doing the observing?

That's right, there would be no duplication, the source would still be the producer.

> And wouldn't I still have the same problem? I would call start on the SignalProducer, get back a signal, but then when I call observeNext on that signal, nothing would get reported...


That's right. That "start" overload you created is only useful if you don't care about that. Otherwise, that's the reason why `startWithSignal` takes a block. What you probably want to use is `startWithNext`, for example.

> Then how would I make those dispatch_source-controlled signals send the current value as soon as something begins observing it?

Oh, if you need them to buffer events then you do need a producer.

**Comment by davedelong** [comment]
OK, so in the case of my `SymlinkSignal` above, I'd make that a producer by doing:

    public let SymlinkSignal: SignalProducer<NSURL, NoError> = {
        let (producer, observer) = SignalProducer<NSURL, NoError>.buffer(1)
        fileMonitor.handler = { _ in
            observer.sendNext(resolvedSymlinkURL())
        }
        observer.sendNext(resolvedSymlinkURL())
        return producer.skipRepeats()
    }()

And then I'd observe it by doing:

    SymlinkSignal.startWithNext {
        print("symlink changed: \($0)")
    }

Trying that it makes it look like it's doing what I want.

**Comment by NachoSoto** [comment]
Exactly!

You can simplify it since the observer doesn't outlive the producer creation by using the other `SignalProducer` initializer (writing from my phone, I can write that in more detail later).

But this should do what you want :)

**Comment by davedelong** [comment]
In the case, the Observer does outlive the creation; it gets captured by the `handler` on my `FileMonitor` object and gets used to relay changes from the `FileMonitor` to the `SignalProducer`, right?

Is `.buffer` the common way to create custom `SignalProducers` like this?

**Comment by davedelong** [comment]
Oh, here's another question as I'm converting my Signals to Producers. I have the following Producer wrapping an `NSMetadataQuery`:

    public let SpotlightSignal: SignalProducer<Array<NSMetadataItem>, NoError> = {
        let q = NSMetadataQuery()
        q.predicate = NSPredicate(fromMetadataQueryString: "kMDItemCFBundleIdentifier == '\(aBundleIdentifier)'")
        q.searchScopes = [NSMetadataQueryIndexedLocalComputerScope]
        q.operationQueue = NSOperationQueue.mainQueue()
    
        let nc = NSNotificationCenter.defaultCenter()
        let producer = nc.rac_notifications(nil, object: q)
            .map { _ in
                q.results as? Array<NSMetadataItem> ?? []
            }
            .skipRepeats { $0 == $1 }
    
        q.startQuery()
        return producer
    }()

`NSMetadataQuery` reports its results via `NSNotifications`, so I'm using the `rac_notifications` method to tap in to those events (so I'm not creating the Producer myself).

Is there a way I can indicate (for efficiency) that the query shouldn't start until a Signal gets produced by the Producer? As it currently stands, I just have to start the query immediately, even though I don't have any observers yet.

**Comment by JaviSoto** [comment]
Hi @davedelong!

The trick is to delay the creation of the resource, in this case the `NSMetadataQuery`, until the `SignalProducer` is started (aka it has a subscriber). The constructor for `SignalProducer` you want is the one that gives you an `Observer` and a `CompositeDisposable`. The observer allows you to manually send events through the signal, and you can think of the producer in terms of RAII, and this disposable allows you to add "work" to happen when this producer is going to be teared down. But in this case you can rely on `rac_notifications` to do most of the work like so:

```swift
public let SpotlightSignal = SignalProducer<Array<NSMetadataItem>, NoError> { observer, disposable in
    let q = NSMetadataQuery()
    q.predicate = NSPredicate(fromMetadataQueryString: "kMDItemCFBundleIdentifier == '\(aBundleIdentifier)'")
    q.searchScopes = [NSMetadataQueryIndexedLocalComputerScope]
    q.operationQueue = NSOperationQueue.mainQueue()

    let nc = NSNotificationCenter.defaultCenter()
    disposable += nc.rac_notifications(nil, object: q)
        .map { _ in
            q.results as? Array<NSMetadataItem> ?? []
        }
        .skipRepeats { $0 == $1 }
        .start(observer)
}
```

**Comment by davedelong** [comment]
@NachoSoto sorry, I wasn't clear. I meant is there a way to delay the start of the `NSMetadataQuery` (`q.startQuery()`) until the Producer generates the first Signal?

**Comment by davedelong** [comment]
@JaviSoto thanks, I hadn't thought of that approach. But doesn't that approach mean that I'd have a new `NSMetadataQuery` created for every Signal generated by the Producer?

**Comment by JaviSoto** [comment]
It would, so if the resulting producer is started multiple times, the side effects would happen multiple times. It's hard to say without seeing the rest of your code around this what you would need, but it's possible you may want to check out replayLazily
