### ISSUE TITLE
how can i use it only in swift?

### ISSUE THREAD

**Issue by GLChan** [ReactiveCocoa/ReactiveCocoa#2737]
how can i use it only in swift?

**Comment by joedaniels29** [comment]
What does the question mean? is it not sufficient to just 
```swift 
import ReactiveCocoa
```
and then not touch the Objc stuff?

**Comment by RuiAAPeres** [comment]
I'm guessing you are worried about the Objc codebase,  but it's fine. You can use any of the setup methods presented [here](https://github.com/ReactiveCocoa/ReactiveCocoa#getting-started). Once you have that, you just need to:

```swift
import ReactiveCocoa
```

I also would like to mention that ReactiveCocoa's Swift codebase uses [Result](https://github.com/antitypical/Result) as its only dependency. So in case you are using the  `NoError` type, don't forget to:

```swift
import Result
````
