### ISSUE TITLE
ReactiveCocoa 4 wrong use CocoaAction

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#2742]
I have next code in ViewController for understand CocoaAction:
```Swift
        let action = Action<AnyObject, String, NSError> { _ in
        return SignalProducer<String, NSError> { observer, _ in
                observer.sendNext("hello world")
                observer.sendCompleted()
            }
        }

        action.values.observeNext { (p) -> () in
            print(p)
        }

        let cocoaAction = CocoaAction(action) { (sender) -> AnyObject in
            print("CocoaAction")
            return self
        }
        btn.addTarget(cocoaAction, action: CocoaAction.selector, forControlEvents: UIControlEvents.TouchUpInside)
```

If I press button do nothing... But if I replace create cocoaAction on
```Swift
let cocoaAction = action.unsafeCocoaAction
```
It work! Why don't work my code with create CocoaAction from code?

In this case in would be work, but if my action will be input type kind of String, Void etc I will not use func unsafeCocoaAction... So I want to try what am I doing wrong?

**Comment by avalanched** [comment]
That is normal retain/release behaviour

from the docs concerning the `addTarget:action:forControlEvents` method:
> When you call this method, target is not retained.

When using `unsafeCocoaAction` you retain the `CocoaAction` in the `Action` object.
So you can solve this issue by retaining the `cocoaAction`.

**Comment by ikesyo** [comment]
> So you can solve this issue by retaining the `cocoaAction`.

This clearly answers the question, thank you @avalanched! Closing.
