### ISSUE TITLE
UIWebView binding using ReactiveCocoa 4

### ISSUE THREAD

**Issue by marysmech** [ReactiveCocoa/ReactiveCocoa#2743]
I'm using for binding `UIKit` extension from Colin Eberhardt (https://github.com/ColinEberhardt/ReactiveTwitterSearch/blob/master/ReactiveTwitterSearch/Util/UIKitExtensions.swift). It works nice for `UILabel` etc.

My app using `UIWebView` so I need to bind `UIWebView`. I'm not sure how to do that. Currently in my non reactive code, I'm using method `loadHTMLString` for loading content to my webView but I have no idea how to bind webView with ViewModel.

Do anybody know how to bind UIWebView?

**Comment by avalanched** [comment]
binding functions is fairly easy.

```swift
SignalProducer<(String, NSURL?),NoError>(value: ("http://www.google.be", nil))
    .startWithNext(webView.loadHTMLString)
```

**Comment by marysmech** [comment]
Thank you for your answer. I'm trying bind my `UIWebView` in my `UIViewController` with my ViewModel. For `UILabel` I do binding:

In ViewModel I have
`var title = MutableProperty<String>("")`

and in ViewController is binding
`self.articleDetailView.titleLabel.rac_text <~ self.articleViewModel.title`

Can i do something like that with `UIWebView`?

**Comment by avalanched** [comment]
Yes you can bind a MutableProperty to `loadHTMLString`

if you have this in the ViewModel
`var url : MutableProperty<NSURL>`

you can bind it as such:
`url.producer.map { NSURLRequest($0) }.startWithNext(webview.loadRequest)`

**Comment by marysmech** [comment]
This is exactly what i needed. Thanks a lot.
