### ISSUE TITLE
how to validate a text field only after the first text insertion

### ISSUE THREAD

**Issue by marcelomp** [ReactiveCocoa/ReactiveCocoa#2746]
Hi I am using ReactiveCocoa 2.5

I have a UITextField which is of obligatory filling, but I only want the field to be considered invalid if empty, after the user first type.

e.g.: suppose the user type a text and then erase all the text, now the text field should signal as invalid because It's content is of 0 length.

How do I express that scenario? 

my actual wrong code looks like this

```
RAC(self.viewModel, CEP) = self.tfCEP.rac_textSignal;
    
    RACSignal *CEPSignal = RACObserve(self.viewModel, CEP);
    
    RAC(self.tfCEP, isValid) = [CEPSignal map:^NSNumber*(NSString *value) {
        return @(value.length > 0);
    }];
```

**Comment by JaviSoto** [comment]
You could skip the first value with `skip: 1]`

**Comment by marcelomp** [comment]
Thanks very much it was so simple!
