### ISSUE TITLE
Reactiv Cocoa   dyld:Symbol not found:__NSArray0_

### ISSUE THREAD

**Issue by raykington** [ReactiveCocoa/ReactiveCocoa#2754]
**# I can run this project at iOS 9.1 but crash on iOS  8.4.  Is this means This ReactiveCocoa framework only support9.1 
The crash reason:**
: _NSArray0 Referenced from: /private/var/mobile/Containers/Bundle/Application/12D3C7C5-E14E-4150-AD4B-4DD58230DB7B/FenYouShopping.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa (which was built for iOS 9.1) Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation in /private/var/mobile/Containers/Bundle/Application/12D3C7C5-****-4150-AD4B-4DD58230DB7B/FenYouShopping.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa

**Comment by rpowelll** [comment]
Hey can I ask how you're adding ReactiveCocoa to your app? It'd help us diagnose the issues you're running into a little better.

**Comment by raykington** [comment]
I added it by Cocoapods

**Comment by rpowelll** [comment]
I threw together an example project using Carthage and didn't encounter any issues running on the 8.1 simulator. The CocoaPods specs for ReactiveCocoa aren't officially maintained so they tend to have occasional issues, though @ashfurrow might be able to provide some help here since I'm pretty sure he's currently maintaining them.

**Comment by ashfurrow** [comment]
Looks similar to https://github.com/CocoaPods/CocoaPods/issues/3773 but I can't be certain without more details. The ReactiveCocoa team probably prefer to have us discuss CocoaPods-specific problems at https://github.com/mhuusko5/Podspecs which is where the podspec is being maintained. Sorry to be a pain, but could I ask you to re-open you issue there and provide as much technical detail as possible? Xcode version, OS X version, CocoaPods version, and the contents of your Podfile would be :100:

**Comment by raykington** [comment]
Xcode Version 7.1.1 (7B1005) and OS X 10.11. cocoa pods version 0.39.0 
This is contents of Podfile:

 # Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FenYouShopping' do
use_frameworks!
pod 'ReactiveCocoa','~> 4.0.2-alpha-1''
pod 'Masonry'
end

**Comment by RuiAAPeres** [comment]
@raykington were you able to solve this?
