### ISSUE TITLE
How to create a signal containing an array of values, corresponding to a streaming data frame

### ISSUE THREAD

**Issue by edowson** [ReactiveCocoa/ReactiveCocoa#2755]
I have a array of values representing a frame of data, generated from a signal processing block.

I would like to send the entire frame, each time the entire array is updated, but I do not know how to go about doing this.

Here is how I'm initializing the array:

`// Allocate a 16-bit data buffer of size 8.`
`ssize_t  sizeDataBuffer = 8;`
`int16_t  *dataBuffer     = (int16_t *) calloc(sizeDataBuffer, sizeof(int16_t));`

and here is how I go about updating the contents of the array:

`// Initialize the contents of the data buffer.`
`for (ssize_t i = 0; i < sizeDataBuffer; i++) {`
`  dataBuffer[i] = i+1;`
`}`

I need to generate a signal corresponding the entire array (frame), as soon as all array elements have been updated.

A subscriber to the signal will need to take each frame, extract each value and print them out.

How can I go about setting up a producer, such that a RACSignal is generated each time the entire array has been updated and stream the entire frame as a signal?

**Comment by RuiAAPeres** [comment]
I am unsure what you mean with:

> I need to generate a signal corresponding the entire array (frame),

You mean you need a `SignalProducer<[Frame], NoError>`, or `SignalProducer<SignalProducer<[Frame], NoError>, NoError>`? 

In the first case, you can simply:

```swift
let producer = SignalProducer<Frame, NoError> { o, d in 

   ssize_t sizeDataBuffer = 8;
   int16_t *dataBuffer = (int16_t *) calloc(sizeDataBuffer, sizeof(int16_t));

   for (ssize_t i = 0; i < sizeDataBuffer; i++) {
      dataBuffer[i] = i+1;
   }
    
   o.sendNext(dataBuffer)
   o.sendCompleted()
}
```
