### ISSUE TITLE
UIButton RAC binding

### ISSUE THREAD

**Issue by Otbivnoe** [ReactiveCocoa/ReactiveCocoa#2756]
I started study MVVM pattern with Reactive Cocoa and now I have some unclear situation. I want to bind `enable` property of button with my model and bind `rac_command` also. Here is a my code :

    RAC(self.loginButton, enabled) = RACObserve(self.viewModel, loginButtonEnabled);
    RAC(self.loginButton, rac_command) = RACObserve(self.viewModel, loginCommand);

    - (RACCommand *)rac_loginCommand {
        return [[RACCommand alloc] initWithSignalBlock:^RACSignal *(id input) {
            return [RACSignal empty];
        }];
    }

But it's doesn't work. 

    'Signal <RACDynamicSignal: 0x7f805bf05b30> name:  is already bound to key path "enabled" on object <Button: 0x7f805bc3eae0;

Hope someone can help me.

**Comment by iv-mexx** [comment]
When setting the `rac_command` property of the Button this is done automatically for you. 
To be more precise: Buttons `enabled` property is automatically bound to the Commands enabled, so you should create your command accordingly:

```ObjC
- (RACCommand *)rac_loginCommand {
    return [[RACCommand alloc] initWithEnabled:loginButtonEnabled,
                                   signalBlock:^RACSignal *(id input) {
        return [RACSignal empty];
    }];
}
```

**Comment by Otbivnoe** [comment]
@iv-mexx Thanks!
