### ISSUE TITLE
Custom RACScheduler 

### ISSUE THREAD

**Issue by Gladkov-Art** [ReactiveCocoa/ReactiveCocoa#2772]
Base on [https://robots.thoughtbot.com/reactive-core-data](https://robots.thoughtbot.com/reactive-core-data), I have create subclass of RACQueueScheduler in order to run cold signals on NSManagedObjectContext's queue. My CoreDataScheduler class looks like: 

```
@interface CoreDataScheduler : RACQueueScheduler

@property(nonatomic, readonly)NSManagedObjectContext *context;

- (instancetype)initWithContext:(NSManagedObjectContext *)context;

@end
```

```
@implementation CoreDataScheduler

- (instancetype)initWithContext:(NSManagedObjectContext *)context
{
	if (self = [super init]) {
		_context = context;
	}
	return self;
}

- (RACDisposable *)schedule:(void (^)(void))block
{
	NSParameterAssert(block);
	
	RACDisposable *disposable = [[RACDisposable alloc] init];
	
	[self.context performBlock:^{
		if (disposable.disposed) {
			return;
		}
		block();
	}];
	
	return disposable;
}
```
Then I'm trying to run signal on that thread (code is simplified, I've removed some logic):
```
RACScheduler *coreDataScheduler = [[CoreDataScheduler alloc] initWithContext:self.privateManagedObjectContext];
[[RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
		SomeObject *object = [self.privateManagedObjectContext objectWithID:self.managedObject.objectID];
		NSLog(@"%@",object.ssid);
		return nil;
	}] subscribeOn:coreDataScheduler];
```

So when I try to print object's property, core data multi-threading assertions fires. That means that signal's body is executed not on `self.privateManagedObjectContext`'s queue. 
I have checked it, I set breakpoints inside `performBlock` in `schedule:` method of `CoreDataScheduler` and in signal's body, indeed threads were different.

Need your advice

**Comment by Gladkov-Art** [comment]
It seems that `deliverOn:` is working properly with my `RACScheduler`.

**Comment by mdiep** [comment]
So you don't need help?

**Comment by Gladkov-Art** [comment]
I need help, my `CoreDataScheduler` still doesn't work with `subscribeOn:`. I need my `didSubscribe` to run on `NSManagedObjectContext`'s queue.

**Comment by mdiep** [comment]
Do you have an example project that exhibits the issue?

That looks correct. And `subscribeOn:` is pretty simple, so I don't see how things could go wrong. Without seeing a project, I'm not sure how to figure out the issue.

**Comment by Gladkov-Art** [comment]
Sorry for late answer, I have created example project that has the same issue.
[Example.zip](https://github.com/ReactiveCocoa/ReactiveCocoa/files/209849/Example.zip)

**Comment by ikesyo** [comment]
@Gladkov-Art At first, you don't need to extend `RACQueueScheduler`. Just extend `RACScheduler` instead. Then, the actual problem is that you are directly calling the given block in overridden `schedule` method. You should perform the given block using `performAsCurrentScheduler` defined in `RACScheduler+Subclass.h`. That did the trick.

**Comment by Gladkov-Art** [comment]
Thanks a lot!
