### ISSUE TITLE
Semver problems with ReactiveCocoa and Swift

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2773]
I know this has been discussed but just to let you know, all my projects included ReactiveCocoa using Carthage with the following entry in the Cartfile:

```
github "ReactiveCocoa" ~> 4.0.1
```

My understanding of how `~>` and semver works is that this would allow carthage to update reactive cocoa versions as long as they are backward compatible. Which is not the case for `4.1.0` because we are still using Xcode 7.2 and Swift 2.1 and updating our dependencies (which are all included like this) made all our builds to break due to this change.

I guess the only solution would be to have a mayor version for each Swift release if you want to maintain semver. At least until Apple provides ABI stability.

**Comment by mdiep** [comment]
We had a discussion about this [here](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2760#discussion_r56915295).

**Comment by guidomb** [comment]
I see. I still think that mayor release would have been more appropriate but I guess that is water under bridge.

**Comment by mdiep** [comment]
I think in the future we should do a major release when making breaking Swift changes.
