### ISSUE TITLE
Request: Podspec for ReactiveCocoa 4.1

### ISSUE THREAD

**Issue by minuscorp** [ReactiveCocoa/ReactiveCocoa#2774]
Hello.

I'm glad to see that the team released the 4.1 version, but CocoaPods doesn't have that version yet. Can somebody update a new podspec?

Thank you very much.

**Comment by adomanico** [comment]
Would recommend adding Carthage to your project for ReactiveCocoa. It's quite easy and works well with Cocoapods

**Comment by mdiep** [comment]
I would not recommend using Carthage and CocoaPods simultaneously. Dependency managers find compatible versions of all your dependencies. If you're managing dependencies with multiple systems, you won't know whether you're using compatible versions.

**Comment by adomanico** [comment]
Fair point, gotta watch for conflicting dependencies.

For my use case migrating all of our decencies to Carthage just isn't feasible, so having Carthage just for ReactiveCocoa has worked well

**Comment by minuscorp** [comment]
As @mdiep said, we're not able to maintain both CocoaPods and Carthage at the same time. So I make a request to the ReactiveCocoa's team to include a proper Podspec to the repository or maybe someone else who has experience with CocoaPods can help with this.

**Comment by ikesyo** [comment]
It looks like v4.1 on CocoaPods exists now. Closing. :smiley:
