### ISSUE TITLE
could not build module 'ReactiveCocoa'

### ISSUE THREAD

**Issue by tingxins** [ReactiveCocoa/ReactiveCocoa#2778]
In Xcode, i find that it could not build module 'Reactive Cocoa' ; but the project can building succeed.

**Comment by tingxins** [comment]
![screen shot 2016-04-06 at 10 19 15](https://cloud.githubusercontent.com/assets/17563998/14303957/78a5bee0-fbe1-11e5-9d2c-087104b1c9ce.png)

**Comment by mdiep** [comment]
Xcode's live issues are just wrong sometimes. If it builds successfully, then everything is fine.

**Comment by tingxins** [comment]
Yes. I Force Quit my Xcode, And reopen it, it's just fine. thanks
