### ISSUE TITLE
[RAC 2.x] incorrect output of switchToLatest when sending values on different scheduler

### ISSUE THREAD

**Issue by StatusReport** [ReactiveCocoa/ReactiveCocoa#2781]
I have a signal of signals that is being subscribed on the main scheduler. The signals that are sent on this signal are being subscribed on the default scheduler, and I'm using `switchToLatest` to switch to the values of the latest signal.

So the configuration is as follows:
```objc
RACSignal *signalA = [[RACSignal return:@"foo"]
    subscribeOn:[RACScheduler scheduler]];

RACSignal *signalB = [[RACSignal return:@"bar"]
    subscribeOn:[RACScheduler scheduler]];

__block NSMutableArray *values = [NSMutableArray array];
RACSubject *subject = [RACSubject subject];
[[subject
    switchToLatest]
    subscribeNext:^(id x) {
      [values addObject:x];
    } completed:^{
      NSAssert([values.lastObject isEqual:@"bar"]);
    }];

[subject sendNext:signalA];
[subject sendNext:signalB];
[subject sendCompleted];
``` 

Given the definition of `switchToLatest`, one would assume to have the last value of the `values` array to be equal to `@"bar"`. However, running this sample code in a loop raises an exception fairly quickly.

Is this considered a well-defined input for RAC (having signal of signals with different schedulers)? If so, I can try and work on a fix.

Note that the above question is also relevant for RAC 4, although it seems that the `switchToLatest` logic there is different and doesn't use `takeUntil:` like RAC 2.x (additional information on why this was the design decision will be appreciated, as a backport of this may be a potential fix).

**Comment by mdiep** [comment]
Yes, that should work AFAICT. What exception do you get?

**Comment by StatusReport** [comment]
I meant that the assert the my code fails.

**Comment by StatusReport** [comment]
After digging some more, it seems that the issue stems from the fact that `switchToLatest` is using `takeUntil:` to dispose the subscription to a signal once a new signal arrives. So in the code example above, the subscription to `signalA`, which happens on the default scheduler, is disposed when a multicast connection signal that is subscribed on the main scheduler is fired (see `switchToLatest` implementation). This obviously leads to a possible race condition where the second signal is sent over `subject`, and the `takeUntil:` operator disposes the subscription just after `sendNext:` is called.

In the context of `takeUntil:` this makes complete sense, as the possible race condition is transparent to the client, but in `switchToLatest` it seems like a bug.

**Comment by mdiep** [comment]
Can you explain that again? I lost you here:

> This obviously leads to a possible race condition where the second signal is sent over subject, and the takeUntil: operator disposes the subscription just after sendNext: is called.

:confused:

**Comment by StatusReport** [comment]
Yes, sorry for the cryptic explanation. It took me a while to formalize it in a readable manner 😄 

If we'll take a look at `switchToLatest`'s [implementation](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/RACSignal+Operations.m#L797-L817), we'll see that it is implemented by a `flattenMap:` on the input signal, where `takeUntil:` is operated on each signal that is sent over the input signal:
```objc
RACDisposable *subscriptionDisposable = [[connection.signal
	flattenMap:^(RACSignal *x) {
		NSCAssert(x == nil || [x isKindOfClass:RACSignal.class], @"-switchToLatest requires that the source signal (%@) send signals. Instead we got: %@", self, x);

		// -concat:[RACSignal never] prevents completion of the receiver from
		// prematurely terminating the inner signal.
		return [x takeUntil:[connection.signal concat:[RACSignal never]]];
	}]
	subscribe:subscriber];
```

Additionally, `connection` is published from `self`, so it is subscribed on the same scheduler of `self`.

Now, if `connection.signal` and `x` are being subscribed to on the same scheduler, everything is fine, since we enforce serial execution and therefore we know that if `self` sent a value, then the subscription to `x` will be terminated before the previous `x` can send additional values.

However, consider what happens when `connection.signal` and `x` are sending their values on separate schedulers: in this case there may be a context switch after a new `x` is sent and returned from `flattenMap:` and the operation of the `takeUntil:` operator that should dispose the subscription to the previous `x`.

This is depicted in the following event chain:
```
Thread 1:  A		B									A disposal

Thread 2:           				A is sending value

Thread 3:					B is sending value
```

So the result is that there's a point in time where there's a subscription both to A and B, which is against the contract of `switchToLatest`.

Does that make more sense?

**Comment by StatusReport** [comment]
Guys, ideas? This is a potential bug in RAC 4, as far as I can tell from reading the code (haven't tested it though).

**Comment by mdiep** [comment]
This is still on my todo list; I just haven't found time for it yet. I'll get back around to it as soon as I can.

**Comment by mdiep** [comment]
This certainly looks like a race condition to me.

I think the solution is to not use `takeUntil:` and not multicast `self`. We need to be sure that the subscription to A is completed/disposed before sending values from B. AFAICT that means closing over some local state and probably sending a completed event to a subscriber for A.

Are you still interested in trying to fix this? Do you have enough to go on?

I'm still trying to understand the RAC 4 code.

**Comment by mdiep** [comment]
I don't think RAC 4 has this problem because it sends interrupted events immediately and the disposable for A is disposed before the subscription to B.

**Comment by StatusReport** [comment]
I'm interested in fixing this. I have an initial fix in the works, which is also way faster than the current `switchToLatest` implementation, since it's subscribing to the signals directly and not using `takeUntil:` which is quite slow. I need to go over some edge cases and add some tests and then I'll submit a PR.

**Comment by mdiep** [comment]
💖

**Comment by StatusReport** [comment]
It seems that there are more issues that prevent me from solving this, especially #2951. Once it will be merged (if it will be merged) I'll fix this as well.

**Comment by mdiep** [comment]
Closing in favor of https://github.com/ReactiveCocoa/ReactiveObjC/issues/5.
