### ISSUE TITLE
Only next events are forward to an action's observer

### ISSUE THREAD

**Issue by nmarisi** [ReactiveCocoa/ReactiveCocoa#2784]
As far as I can see, only the next events are forwarded to an action's observer. So for example, completed events are ignored.

Here's an example:
```
buttonAction = Action<Bool, Void, NoError>() { value in

    return SignalProducer<Void, NoError> { observer, _ in
        dataProvider.addNewTestProduct()

        observer.sendNext()
        observer.sendCompleted()
    }
```

Observing the events signal: 
```
vm.buttonAction.events.observeCompleted {
    print("observed completed")
}
vm.buttonAction.events.observeNext {
    print("observed next")
}
```
The print statement for the completed event is never triggered (unless the action is deallocated).

It's clear on Action.swift ( line 119), that this is actually happening:

```
signal.observe { event in
	observer.action(event.mapError { .ProducerError($0) })
	self.eventsObserver.sendNext(event)
}
```

Is this intended behaviour? Shouldn't the action be forwarding Completed, Failed and Interrupted events too?

**Comment by ikesyo** [comment]
This is intended behavior. Since the signature is `Signal<Event<Output, Error>, NoError>`, you can observe the inner producer's Completed events as:

```swift
vm.buttonAction.events.observeNext { event in
    switch event {
    case let .Next(value): ... // A Next event from the inner producer
    case .Completed: ... // A Completed event from the inner producer
    default: break
    }
}
```
