### ISSUE TITLE
Help understanding memory management

### ISSUE THREAD

**Issue by mbrandonw** [ReactiveCocoa/ReactiveCocoa#2785]
Hello all, i'm trying to understand the memory management of RAC, and figure out when/why I should need to explicitly manage disposables or use `takeUntil` for ending a signal. Take the following view controller and view model that speak to each other:

```swift
class MemoryController: UIViewController {
  let viewModel = MemoryViewModel()

  override func viewDidLoad() {
    super.viewDidLoad()

    self.viewModel.showAlert
      .observeOn(UIScheduler())
      .observe { [weak self] event in 
        print(event)
        self?.dismissViewControllerAnimated(true, completion: nil)
      }
  }

  @IBAction
  func buttonPressed() {
    self.viewModel.buttonPressed()
  }
}

class MemoryViewModel {
  let (buttonSignal, buttonObserver) = Signal<(), NoError>.pipe()
  func buttonPressed() {
    buttonObserver.sendNext()
  }

  let showAlert: Signal<String, NoError>

  init() {
    self.showAlert = self.buttonSignal.map { "HELLO!" }
  }
}
```

The view controller simply tells the view model when a button is pressed, and the view model communicates back a string to print via a signal. When the controller dismisses both the controller and view model have their `deinit`s called, so that's good. However, the `print(event)` only prints a `.Next` event, and never a `.Completed`.

Now, the signal in the view model is long living, but if I understand https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2603 correctly, the signal should complete itself when nothing is holding onto it anymore.

So, do I understand that PR and memory management correctly? What am I missing?

I will note that if I change the long living signal to a `MutableProperty` then the `.Completed` event is sent.

**Comment by RuiAAPeres** [comment]
> (...) figure out when/why I should need to explicitly manage disposables or use takeUntil for ending a signal.

[You shouldn't explicitly manage memory](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/DesignGuidelines.md#prefer-managing-lifetime-with-operators-over-explicit-disposal). 

> However, the print(event) only prints a .Next event, and never a .Completed.

That's the expected behaviour of a hot signal (which is what you are using via a `Signal`). Could you check if `Interrupted` is being sent?

**Comment by mbrandonw** [comment]
Neither completed nor interrupted will emit.

**Comment by mdiep** [comment]
> Now, the signal in the view model is long living, but if I understand #2603 correctly, the signal should complete itself when nothing is holding onto it anymore.

That doesn't appear to be the case, as `Signal` doesn't have a `deinit`.

But I also don't think that would be correct. A button shouldn't _complete_ just because no one is listening.

**Comment by mbrandonw** [comment]
Ah, maybe that's my misunderstanding... Is it expected for the signal to be released even though it did not send a terminating event?

**Comment by mdiep** [comment]
I believe that's the expectation. You're welcome to argue that it shouldn't be.

**Comment by mbrandonw** [comment]
Ok, I was assuming that not getting a terminating event meant that the signal was leaking. I will try to confirm that isn't the case. Will close for now.

Thanks!
