### ISSUE TITLE
Adding Capability for Catching Errors on Signals/Producers

### ISSUE THREAD

**Issue by Ben-G** [ReactiveCocoa/ReactiveCocoa#2786]
With this issue I'd like to discuss the idea of adding an operator to RAC that allows us to provide an error handler in order to transform an error producing signal into one that cannot produce errors.

In our codebase we have a very similar extension to the one by @NachoSoto here: https://gist.github.com/NachoSoto/25b0003c1b15d7d11a8d#file-signal-extensions-swift-L72-L82

More generally it potentially would be nice to provide a catch operator, that provides a handler for failure events and transforms the signal / producer into one that cannot produce errors.

I think this would be similar to the `catch` implementation of RAC 2.

I'm thinking of something along these lines:

```
extension SignalType {
    public func catchErrors(errorHandler: (Error -> Void)) -> Signal<Self.Value, NoError> {
        return self.flatMapError { error in
            errorHandler(error)

            return .empty
        }
    }
}
```

This is also somewhat related to the discussion in #2766, which requires catching errors in order to bind signals to UIKit components.

A potential downside is that this extension encourages handling errors with side effects, but practically this is how most errors (even in RAC code) are handled today.

Thoughts?

**Comment by mbrandonw** [comment]
I do something similar, but I let the operator take an optional mutable property and if an error occurs it is sent to the property. I do this so that I can later treat errors like signals.

However, I will say that I'm very interested in how other people handle this situation. Is there a way to more declaratively deal with errors?

**Comment by RuiAAPeres** [comment]
@Ben-G I think [Rex](https://github.com/neilpa/Rex) would be a better place for this. Your operator, can easily be constructed with a `flatMapError` and doesn't really provide a unique behaviour.

**Comment by mdiep** [comment]
I'd be more inclined to add an `ignoreErrors` operator and suggest you use that in combination with `.on(failed:)`. But I think there's something to be said for making people write a `flatMapError` and make a conscious decision.

If we're going to make something easier than that, I think it needs to be something that's a good decision. Make good habits easy and bad habits hard.

**Comment by Ben-G** [comment]
Originally I thought of `ignoreErrors` as well. Then I thought it would likely incline users to ignore errors. It seems like most users never want to fully ignore errors, but instead trigger some sort of side-effect: log message, analytics event, alert, etc. 

The suggested operator is intended for these scenarios. But I do understand that there isn't strong support for adding this to the RAC core.

However, if #2766 were to move forward, wouldn't RAC need an operator similar to the one suggested here? Or would you prefer `flatMapError` for binding to UI components as well?

**Comment by mdiep** [comment]
FWIW, I think #2766 is likely to get built into a separate framework so that RAC proper can focus on a cross-platform reactive framework.

I'm not sure I'd say I prefer `flatMapError`, but (1) it can handle errors however you'd like and (2) I don't see any obviously better operators to include in RAC.

I do think it'd make sense to include an operator that says "I don't know what errors to expect here or more to handle them". It could return `NoError` and the errors could be exposed somewhere else (e.g., a static signal on `Signal`) along with file/line information. Then your app could log those to the console or send them to a server. Not sure what I'd call that though.

**Comment by RuiAAPeres** [comment]
@Ben-G @mdiep  FYI, Rex provides the ([ignoreError](https://github.com/neilpa/Rex/blob/master/Source/SignalProducer.swift#L63#L66)). A quick example where`ignoreError` is useful is you want to bind them ([<~](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L280#L293)) to a mutable property.

**Comment by JaviSoto** [comment]
This is what I use:

```swift
extension SignalProducerType {
    @warn_unused_result(message="Did you forget to call `start` on the producer?")
    public func ignoreErrors(replacementValue replacementValue: Self.Value? = nil, andDo block: (Self.Error -> ())? = nil) -> SignalProducer<Self.Value, NoError> {
        return self.flatMapError { error in
            log.debug("Ignoring error: \(error)")

            block?(error)
            return replacementValue.map(SignalProducer.init) ?? .empty
        }
    }

    @warn_unused_result(message="Did you forget to call `start` on the producer?")
    public func redirectErrorsToObserver(observer: Observer<Self.Error, NoError>, replacementValue: Self.Value? = nil) -> SignalProducer<Self.Value, NoError> {
        return self.flatMapError { error in
            observer.sendNext(error)

            if let value = replacementValue {
                return SignalProducer(value: value)
            }
            else {
                return SignalProducer.empty
            }
        }
    }
}
```

Not more importantly the `replacementValue` parameter: I think defaulting to converting the producer to an empty producer may not be what you want.

**Comment by RuiAAPeres** [comment]
@Ben-G if any of the proposed suggestions have helped you, please close this issue.

**Comment by RuiAAPeres** [comment]
@JaviSoto It could also be useful to push those two operators to Rex's codebase. I will happily do it for you, if you agree.

**Comment by Ben-G** [comment]
@RuiAAPeres Like the idea of having @JaviSotos operators available in Rex. Thanks for the helpful input!

**Comment by larryonoff** [comment]
What about adding ```ignoreError``` operator from Rex into the main ReactiveCocoa repo?
