### ISSUE TITLE
UIControl rac_signalForControlEvents will cause "memory leak"

### ISSUE THREAD

**Issue by vagase** [ReactiveCocoa/ReactiveCocoa#2787]
If subscribe and dispose the signal returned by UIControl's `rac_signalForControlEvents` over and over again, we can find that there are many `RACCompounedDisposable` objects are allocated and not released via Instruments.

The problem is: (UIControl+RACSignalSupport.m L28 - L35)

```
[self.rac_deallocDisposable addDisposable:[RACDisposable disposableWithBlock:^{
	[subscriber sendCompleted];
}]];

return [RACDisposable disposableWithBlock:^{
	@strongify(self);
	[self removeTarget:subscriber action:@selector(sendNext:) forControlEvents:controlEvents];
}];
```

There are two RACDisposable are created while subscribing, the first one is added to  `self.rac_deallocDisposable`, the second one is returned to callee. When the callee disposes the second RACDisposable object, it just remove the target and action. But the first RACDisposable still be retained by `self.rac_deallocDisposable`, not got released.

**Comment by mdiep** [comment]
Good catch! Would you be interested in opening a PR to fix test?

**Comment by RuiAAPeres** [comment]
@vagase would you be able to provide a PR for this issue? Or it's something you would prefer us to do?

**Comment by vagase** [comment]
Ok, I'd like to provide a PR soon.
