### ISSUE TITLE
Keyword "associatedtype" could not be recognized

### ISSUE THREAD

**Issue by taojigu** [ReactiveCocoa/ReactiveCocoa#2796]
I just git clone ReactiveCocoa  to local.

But in "ResultType.swift" , the Keyword "associatedtype"  could not be  recognized.

**Comment by ikesyo** [comment]
Looks like you are using Xcode 7.2. As noted in the [v4.1 release note](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.1.0), the current `master` requires Xcode 7.3 to be built.
