### ISSUE TITLE
ReactiveCocoa not compatible with Blockskit ?

### ISSUE THREAD

**Issue by xushichen** [ReactiveCocoa/ReactiveCocoa#2799]
ReactiveCocoa use UIAlertView crash, 
Blockskit user UIAlertView no crash.

**Comment by RuiAAPeres** [comment]
@xushichen could you elaborate and describe a bit more your problem? If you could provide a stack trace and maybe how you are using Blockskit in conjunction with RAC, would definitely help!

**Comment by xushichen** [comment]
ReactiveCocoa and  Blockskit in the same project, Use ReactiveCocoa create UIAlertView Will crash.
`UIAlertView *alertView = [[UIAlertView alloc] initWithTitle:@"" message:@"Alert" delegate:nil cancelButtonTitle:@"YES" otherButtonTitles:@"NO", nil];
[[alertView rac_buttonClickedSignal] subscribeNext:^(id x) {
    if ([x intValue] == 1) {
        NSLog(@"you touched NO");
    } else {
        NSLog(@"you touched YES");
    }
}];
[alertView show];`
[http://i.stack.imgur.com/Tebxf.jpg](url)

**Comment by RuiAAPeres** [comment]
@xushichen do you hold a reference to the `alertView`?
