### ISSUE TITLE
SignalProducer from an AnyProperty is completed as soon as the AnyProperty is out of scope

### ISSUE THREAD

**Issue by fchaillou** [ReactiveCocoa/ReactiveCocoa#2803]
Hello everyone,
First thanks for this great project !

I just wanted to expose an issue we encountered while using AnyProperty.
Sometime, we just want to get the underlying SignalProducer using the producer method and not keeping a reference to the property.
When we do that, as soon as the AnyProperty is deallocated, our SignalProducer is completed even if we still have an observer on it.

Here is an example test case that show the issue :

````swift
    func createProperty() -> SignalProducer<Int, NoError> {
        let producer =  SignalProducer<Int, NoError> { (observer, disposable) in
            dispatch_after(2, dispatch_get_main_queue()) {
                observer.sendNext(5)
            }
        }
        
        let initialProperty = AnyProperty(initialValue: 1, producer: producer)
        
        return AnyProperty<Int>(initialValue: initialProperty.value * 2, producer: producer.map{ $0 * 2 }).producer
    }
    
    func test_any_property() {
        let expectation = self.expectationWithDescription("Test")
        let property =  createProperty()
        
        property
            .producer
            .on(next: {print($0)})
            .on(completed: { print("completed") })
            .skip(1)
            .take(1)
            .startWithNext{ value in
            XCTAssertEqual(value, 10)
            expectation.fulfill()
        }
        
        self.waitForExpectationsWithTimeout(10.0, handler: nil)
    }
    
}
````
This test prints 2 and then completed and obviously fails because the value 5 is never sent from the SignalProducer.

It doesn't feel like this is the desired behavior, i would expect the SignalProducer to say alive until either it finishes naturally (reaching end of values) or being disposed using the Disposable returned from the startWithNext.

This seems to come from the fact that the AnyProperty is actually creating a Mutable Property and this MutableProperty sends completed in deinit {} but i'm honestly not sure how to fix it.

Thanks for your help !

**Comment by RuiAAPeres** [comment]
The `AnyProperty` here:

` return AnyProperty<Int>(initialValue: initialProperty.value * 2, producer: producer.map{ $0 * 2 }).producer`

Gets immediately out of scope so it's released (you can make the `AnyProperty` be a class and confirm that `deinit` is being called). As you said, once the `MutableProperty` is released, it will send complete to its [inner observer](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/32238d7f5829bc758a3c818f22a377db968d33bf/ReactiveCocoa/Swift/Property.swift#L91), so the `SignalProducer` will complete ([here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Property.swift#L171)) . The `MutableProperty` created by the `AnyProperty` is retained [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/32238d7f5829bc758a3c818f22a377db968d33bf/ReactiveCocoa/Swift/Property.swift#L40#L44) (remember that the `SignalProducer` is tied to the `Observer` [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/32238d7f5829bc758a3c818f22a377db968d33bf/ReactiveCocoa/Swift/Property.swift#L135)). So the release goes like this: `AnyProperty -> _value + _producer + _signal -> MutableProperty`
If you do this instead:

```swift

func createProperty() -> AnyProperty<Int> {
    let producer =  SignalProducer<Int, NoError> { (observer, disposable) in
        dispatch_after(2, dispatch_get_main_queue()) {
            observer.sendNext(5)
        }
    }

    let initialProperty = AnyProperty(initialValue: 2, producer: producer)

    return AnyProperty<Int>(initialValue: initialProperty.value * 2, producer: producer.map{ $0 * 2 })
}
```

The `AnyProperty` will be retained for the duration of your test (which is 10.0 seconds) and will pass the assert. 

It's also important to note that the `SignalProducer` you are using here (you called it `property`, but it's actually a `SignalProducer` and you are just returning `self` when you call `.producer`):

```swift
property
            .producer
            .on(next: {print($0)})
            .on(completed: { print("completed") })
            .skip(1)
            .take(1)
            .startWithNext{ value in
            XCTAssertEqual(value, 10)
            expectation.fulfill()
        }
```

Is tied to [this](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/32238d7f5829bc758a3c818f22a377db968d33bf/ReactiveCocoa/Swift/Property.swift#L91). If you comment out that line, it will never complete. 

---

Now that we got that out of the way:

> It doesn't feel like this is the desired behavior, i would expect the SignalProducer to say alive until either it finishes naturally (reaching end of values) or being disposed using the Disposable returned from the startWithNext.

Your "naturally" here is tied to the `MutableProperty`, that gets released, so it completes.

> This seems to come from the fact that the AnyProperty is actually creating a Mutable Property and this MutableProperty sends completed in deinit {} but i'm honestly not sure how to fix it.

Your "fix" is to hold a strong reference to your `AnyProperty`.
