### ISSUE TITLE
Lazily call 'then' for chaining SignalProducers

### ISSUE THREAD

**Issue by gbrhaz** [ReactiveCocoa/ReactiveCocoa#2805]
I have two SignalProducers. The second one relies upon the other fetching something and setting a property elsewhere. Unfortunately, in order for this to work I have to wrap the second SignalProducer in another SignalProducer like so:

```
return SignalProducer {
            sink, _ in
            
            self.create().start {
                event in
                sink.forwardEvent(event)
            }
        }
```

Because the `create` method gets the property that the first signal sets, the first signal needs to finish. With the way `then` works, all code gets executed straight away, and then the signals are chained, but if something is referenced that hasn't yet been set, the app will obviously crash. 

What is the solution to this problem? I'd rather not have the above code because it looks ugly and adds so much noise.

**Comment by RuiAAPeres** [comment]
The solution would be:

```swift
let producer = firstProducer.flatMap(.Latest) { value in 
   return self.create(value)
}
```

This is slightly different than what you showed, but the idea is to instead not rely in outside state. `self.create` will create the next producer you need. 

If you really need to change the state outside, you could:

```swift
let producer = firstProducer
                      .on(next { value in // set outside state})
                      .flatMap(.Latest) { value in 
                          return self.create(value)
                      }
```

Or instead [share a producer](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2706#issuecomment-210437061) that would bind both outside state and pass its value to create the second producer.

> With the way then works, all code gets executed straight away, and then the signals are chained, but if something is referenced that hasn't yet been set, the app will obviously crash.

**Comment by gbrhaz** [comment]
`flatMap` does indeed work. I'm curious what the point of `then` is now...

You're right, outside state is extremely frustrating at this point. I like the idea of `replayLazily`. Do you know of any additional use-cases outside of the one you made the comment on?

**Comment by RuiAAPeres** [comment]
Then `then` operator doesn't pass the inner value of the producer. It's goes a bit with this idea:

> I don't care about what happens with this, as long as it completes (no errors) and then replace with the second operator. 

e.g:

```swift
firstProducer.then(secondProducer)
```

As long as the `firstProducer` completes, the second will begin normally. This is useful when there is a dependency between two producers, but the second one, doesn't depend on the output of the first.

> I like the idea of replayLazily. Do you know of any additional use-cases outside of the one you made the comment on?

Most of the cases where you need to share a producer would fit.
