### ISSUE TITLE
Split Objective-C and Swift APIs going forward

### ISSUE THREAD

**Issue by tonyarnold** [ReactiveCocoa/ReactiveCocoa#2807]
Hey guys, look you know I ❤️ you, and I :heart: ReactiveCocoa, but lately I've been seeing someone else. The library is small, it's simple, and while it's not as robust or mature as ReactiveCocoa is, the straightforward API makes it a bit lovely to work with. I'm not going to [name names](https://github.com/ReactiveKit/ReactiveKit)… we're both bigger than that. 

Correct me if I'm wrong, but maintaining both an Objective-C and Swift API for RAC is a bit of a burden, right? Perhaps going forward it's worth thinking about slimming ReactiveCocoa down to just support Swift. I'm sure you guys feel the pull of writing things in Swift as much as I do 😀 

Obviously there's a lot of people reliant on the Objective-C APIs (myself included, for some rather large projects) but if there's support for this idea, splitting the language support up into separate repos/projects might be a good first step?

What do you think?

**Comment by iv-mexx** [comment]
👍 for splitting the ObjC and Swift APIs. 

One thing to keep in mind though is the interoperability between both. 
Theres not only projects that use the ObjC API and projects that use the Swift API, but also projects that use both. 
I myself have at least one big project that uses both APIs and relies heavily on [ObjectiveCBridging.swift](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/ObjectiveCBridging.swift)

I guess for me it would work to have 3 repos/projects: 

* ReactiveCocoa Swift
* ReactiveCocoa ObjC
* ReacitveCocoa Swift <-> ObjC Bridge

**Comment by carlossless** [comment]
Well, to offer a thirsty rando counter question: What's the benefit of splitting the two?
Not to be dismissive, but it seems like that would impose a bunch of busy work (both for maintainers and framework consumers), with no currently tangible gain.

**Comment by neilpa** [comment]
So the core Swift library can support non-apple platforms where we won't have Obj-C/Cocoa.

**Comment by carlossless** [comment]
@neilpa that's all the convincing I need.

**Comment by ikesyo** [comment]
> So the core Swift library can support non-apple platforms that don't have Obj-C/Cocoa.

In SwiftPM, we can exclude some source files in `Package.swift` and can use `#if SWIFT_PACKAGE` for conditional compilation, so this is not necessarily needed for that purpose.

**Comment by dmcrodrigues** [comment]
I'm all in favor of this splitting which already exists but not formally:
> RAC’s Objective-C API and Swift API are entirely separate, but there is a bridge to convert between the two.

I think we could follow the approach of [Reactor](http://projectreactor.io) which clearly separates:

- Reactor Core
- Reactor IO
- Reactor Add-ons

ReactiveCocoa would become the core containing only the Swift API and then we could create a new project for Objective-C (dependent of the core) containing the Objective-C API but also the bridge between the two. Each project can then opt-in based on their requirements which project should import, only the core or include the Objective-C (basically what we have today).

This splitting can help the support of non-Apple platforms but also make ReactiveCocoa more efficient (in terms of compilation) to any project not using the Objective-C API.

**Comment by mdiep** [comment]
I like the idea of separating into 3 repositories: Swift, Objective-C, and Swift<->Objective-C Bridge.

I see the following benefits:

- Separate versioning of Objective-C and Swift APIs, which removes the maintenance burden of the `2.x-maintenance` branch.
- Separate issues and PRs for what are really 2/3 separate codebases, which removes some overhead for maintainers in understanding new issues and the state of outstanding issues.
- Separate documentation, which will hopefully make things clearer for framework users.
- Allows people to receive notifications and be active contributors for only one of the platforms.
- Potentially makes it easier for the Swift code to be cross-platform.

If we're going to do this, Swift 3.0 / RAC 5.0 would be the time to remove the Obj-C APIs from the Swift repo. The ReactiveCocoa name becomes a little unfortunate as RAC becomes cross-platform with Swift. But I suppose that's just an artifact of history.

Since Obj-C and the bridge are essentially deprecated, I think it makes sense to move those and leave Swift here. I'm not sure what we'd call the Objective-C repository. ReactiveCocoaObjC? ReactiveObjC?

@ReactiveCocoa/reactivecocoa Can I get 👍s and 👎s about this proposal? A written response would be helpful if you're 👎.

**Comment by robb** [comment]
👍 That sounds like a good idea to me

**Comment by kastiglione** [comment]
Great proposal @mdiep!

Would it be possible to transition without the repo split and just with versioning? Specifically, could RAC 5 delete all the deprecated ObjC and associated bridging? RAC 4 could live on, with bug fixes and Swift language compatibility changes being applied. This would affect those who are currently using the bridging, and only so far as the differences between RAC 4 and RAC 5. I don't know what RAC 5 would have, if the differences between v4 and v5 are slim, then this approach might be the simplest approach. There are "only" problems with this approach if both A) there are big differences between v4 and v5, and B) if there's a significant/vocal user base of ObjC bridging.

**Comment by kastiglione** [comment]
Also, thinking about this reminded me the Cocoa extensions are predominantly in ObjC. Would a Swift only RAC still continue to include Cocoa extensions? This makes me wonder what RAC's goals should be. There's talk in this thread about non-Apple platforms, which could lead to Cocoa extensions being a separate repo. There might be benefits to this, but there could also be downsides.

Personally I'm super 👎 on support for non-Apple platforms. My preference would be to see RAC keep it's focus on application development for the following reasons:

1. Supporting non-Apple platforms seems like an idealistic, not pragmatic choice
2. Seems premature, _today_ anyway
3. Spreads RAC contributor resources thinner
4. From experience, RAC kills it at UI programming – is that true for non-UI, I remain skeptic

I can see the devil's advocate arguments against these. My stance is mostly a quick gut-feel, and I expect there will be good points in both directions.

**Comment by mdiep** [comment]
> Would it be possible to transition without the repo split and just with versioning? Specifically, could RAC 5 delete all the deprecated ObjC and associated bridging?

Hmm…

We need to maintain the Obj-C version and the bridging; otherwise large Obj-C codebases will be left in the lurch. GitHub Desktop, for example, is still largely Obj-C and it will be a long time before it's Swift only (if it ever is). Unless the bridging is maintained and kept current with RAC's Swift code, the app won't build with the next version of Xcode.

This might not affect many users, but it will affect them hugely.

> Would a Swift only RAC still continue to include Cocoa extensions? This makes me wonder what RAC's goals should be. There's talk in this thread about non-Apple platforms, which could lead to Cocoa extensions being a separate repo. There might be benefits to this, but there could also be downsides.

We've already started to pursue keeping Cocoa extensions in a separate repo (c.f. #2790).

Mostly, I think it makes sense to keep the RAC core tightly-focused on the types and operators. Moving the UI-specific bindings doesn't seem like a big inconvenience, but it allows contributor groups to be distinct, focuses bug reports, and allows this repository to be cross-platform (even if it's not yet).

From my perspective, separate repos would encourage a wider side of contributors, not spread the existing resources thinner.

**Comment by mdiep** [comment]
Alternate proposal:

4 repositories:

* Swift (cross-platform)
* Objective-C (RAC 2.x)
* Swift <-> Objective-C Bridge
* Cocoa bindings (built on top of the Swift framework)

The Cocoa bindings would remain in this repo (it _is_ ReactiveCocoa, after all). Existing users could upgrade to RAC 5 by adopting the major changes and adding the Swift framework to their project (ideally with the help of Carthage) or just switch to the Swift framework if they don't need Cocoa bindings.

This creates a clear space for some of the current Swift APIs that depend on Objective-C (`DynamicProperty`, `rac_notifications…`, etc.). It also creates a space to showcase one of the things that RAC is great at: UI programming. Hopefully we could start adopting functionality from @neilpa's [Rex](https://github.com/neilpa/Rex) into ReactiveCocoa/ReactiveCocoa then (cf #2790).

As an added bonus, the Swift framework wouldn't be called _ReactiveCocoa_ (a confusing name if it's meant to be cross-platform).

**Comment by mdiep** [comment]
It sounds like people are on board with splitting into 4 repos.

But there's been some disagreement (voiced elsewhere) about whether the Swift code or the Cocoa bindings should remain in _this_ repository as ReactiveCocoa.

If the Swift code stays here, then:

1. The Swift code retains the ReactiveCocoa brand
  - This could be good in that the existing name is associated with the new core
  - But the Swift code has nothing to do with Cocoa
2. The UI repo needs a new name. 
  - It should convey that it has to do with Cocoa
  - ReactiveCocoaUI seems like the best option here. But suggestions are welcome.

If the Cocoa code stays here then:

1. The Cocoa code retains the ReactiveCocoa brand
  - ReactiveCocoa can have the same association with Cocoa users
  - Most existing users will probably want to use the Cocoa code anyway
  - ReactiveCocoa obviously has to do with Cocoa
2. Swift repo needs a new name
  - ReactiveSwift seems like the obvious choice
  - This mirrors the proposed `ReactiveObjC` repo nicely
  - Swift code won't have the name recognition

What do people think?

**Comment by erikprice** [comment]
> If the Swift code stays here, then:
>
> 1. The Swift code retains the ReactiveCocoa brand
>  * This could be good in that the existing name is associated with the new core
>  * But the Swift code has nothing to do with Cocoa

Is it important that the existing name is associated with the core? Some people might want to use only the core, but as you stated later, it's likely that most users will be doing Cocoa programming. The core could have its own name, "ReactiveCore" or something like that. Not sure how important it is that the Swift core have the name recognition?

**Comment by neilpa** [comment]
I agree with @erikprice. The Cocoa code should retain the brand and depend on the new swift core framework to reduce the migration burden for existing users.

**Comment by RuiAAPeres** [comment]
> (...) to reduce the migration burden for existing users.

That's a very good point.

**Comment by kastiglione** [comment]
I too am with

> 1\. The Cocoa code retains the ReactiveCocoa brand

ReactiveSwift seems fine too.

**Comment by andersio** [comment]
I wonder how we should configure the new ReactiveCocoa targets. The RAC API bridging would require ReactiveObjC. So if we do not create dedicated set of targets that strips off the bridging, we would still end up having to compile ReactiveObjC.

**Comment by mdiep** [comment]
This has been done! 🎉
