### ISSUE TITLE
"textField?.rac_textSignal().map"  not working

### ISSUE THREAD

**Issue by taojigu** [ReactiveCocoa/ReactiveCocoa#2809]
ExampleCode : https://github.com/taojigu/SwiftExample
In **TestRAC2** Project

        self.textField?.rac_textSignal().map({ (objc) -> AnyObject! in
            print("map \(objc)");// Never print this line
            return objc;
        })
        
        self.textField?.rac_textSignal().subscribeNext({ (objc) in
            print("suscribe next \(objc)");  //This line could be print
        });

**Comment by RuiAAPeres** [comment]
```
self.textField?.rac_textSignal().map({ (objc) -> AnyObject! in
     print("map \(objc)");// Never print this line
     return objc;
})
```

You never subscribed to the signal, so it's the expected behaviour.

Instead:

```
self.textField?.rac_textSignal().map({ (objc) -> AnyObject! in
     print("map \(objc)");
     return objc;
    })
.subscribeNext({ (objc) in
     print("suscribe next \(objc)"); 
});
```
