### ISSUE TITLE
Ambiguous reference to member toRACSignal()

### ISSUE THREAD

**Issue by cgomezmendez** [ReactiveCocoa/ReactiveCocoa#2810]
I'm trying to return an RACSignal that I can use in my objective c code, I've tried various ways. EX:

<pre>
@objc
    class func getPosts() -> RACSignal {
        let (signal, observer) = Signal<String, NSError>.pipe()
        return signal.toRACSignal()
    }
</pre>

<pre>
@objc
    class func getPosts() -> RACSignal {
        return SignalProducer {
            observer, disposable in
            
        }.toRACSignal()
    }
</pre>

But xcode allways says the same ambiguous reference to member toRACSignal.

My podfile looks like this:
<pre>
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Bebler' do
    pod 'ComponentKit', '= 0.14'
    pod 'ReactiveCocoa', '~> 4.1.0'
    pod 'AFNetworking', '~> 3.1'
    pod 'Alamofire', '~> 3.3'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'KeychainSwift', '~> 3.0'
end
</pre>

I have Xcode version 7.3

Edit:
also tried this:
<pre>
@objc
    class func getPosts() -> RACSignal {
        let signalProducer: SignalProducer<String, NSError> =  SignalProducer {
            observer, disposable in
            
            }
        return signalProducer.toRACSignal()
    }
</pre>

same result.

**Comment by dmcrodrigues** [comment]
Your `Signal` or `SignalProducer` needs to produce values that conform to protocol `AnyObject` to be converted in a `RACSignal`. Reference [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/ObjectiveCBridging.swift#L84-L94).

**Comment by RuiAAPeres** [comment]
@cgomezmendez This would work:


```swift
let signal = aProducer.map{ $0 as AnyObject }.toRACSignal()
```
