### ISSUE TITLE
Add public NSObject.willDeallocSignal extension property

### ISSUE THREAD

**Issue by ikesyo** [ReactiveCocoa/ReactiveCocoa#2813]
Arisen in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2811#issuecomment-213005356.

**Comment by mdiep** [comment]
Is `NSObject` available on linux? Or should this be included in something like Rex instead?

**Comment by andersio** [comment]
`NSObject` is available in the Swift reimplementation of Foundation. But I don't think the behaviour of `rac_willDeallocSignal` can be replicated, since there is no Objective-C runtime available in the standard Linux port.

**Comment by mdiep** [comment]
This is resolved by the new lifetime API.
