### ISSUE TITLE
Progressive collect operator

### ISSUE THREAD

**Issue by startupthekid** [ReactiveCocoa/ReactiveCocoa#2815]
I opened [a question on SO](http://stackoverflow.com/questions/36783941/reactivecocoa-4-progressive-collect-operator) about this but it could potentially be an incredibly useful operator to have, allowing for the ability to composite stream values into array chunks that work can be processed on.

Function contract:

- aggregates values into an array, similar to `collect`
- values that pass the filter are appended to the previous list
- values that fail the filter are push onto the next sequence and previous sequence is sent

Example usage would be:

```swift
someProducer.aggregateWhile { $0 == someValue }

let (signal, observer) = Signal<Int, NoError>.pipe()

observer.sendNext(5) // no output
observer.sendNext(5) // no output
observer.sendNext(42) // outputs [5, 5] then [42]
observer.sendNext(5)  // outputs [5]
observer.sendCompleted()

signal.aggregateWhile { $ == 5 }.observeNext { print($0) }

// Output: 
// [5, 5]
// [42]
// [5]

```

Essentially what I want is given a value stream of say, 1, 2, 3, 4, 5, 6, the ability to arbitrarily chunk that data based on a filter condition. Depending on my filter the output could look like `[1, 2]`, `[3, 4, 5, 6]` or `[1]`, `[2, 3, 4, 5, 6]`, whatever you want really.

What do you guys think? Something worth taking a look at?

**Comment by mdiep** [comment]
What sort of thing are you using this for?

**Comment by startupthekid** [comment]
@mdiep I want to use it to perform operations on lists of `CMSampleBuffer` objects that are being read in via an `AVAssetReader`. In my particular use case, I need to aggregate a certain number of buffers, that range from 2 to 4 seconds where each frame in that list returns positive for face detection (via `CoreImage`), then crop the each frame to the respective face, and write that list as a separate video file. So for example, if a video file has 4 instances where a face is detected for 2 - 4 seconds, I'd generate four smaller videos from the original asset. 

The reason I'd like a progressive aggregator that sends chunks on a conditional basis is as you can imagine, reading in videos is memory intensive and if you have about 250+ frames in memory at once, you can crash the application and being able to build up a list of frames as they come in and then immediately process that list/write it to file would help to keep my memory imprint low.

**Comment by mdiep** [comment]
What condition would you use in that case? Would a fixed-size buffer like #2817 meet your need?

**Comment by startupthekid** [comment]
Not quite because that requires knowing the number of values you'll be taking beforehand.

**Comment by dmcrodrigues** [comment]
> - aggregates values into an array, similar to collect
> - values that pass the filter are appended to the previous list
> - values that fail the filter are push onto the next sequence and previous sequence is sent

@startupthekid considering this, shouldn't the output be `[5, 5]` and `[42, 5]`? 

`42` fails the filter so it goes to the next sequence and the previous one is sent, then comes `5` which matches the filter so it will be aggregated into the current sequence which currently contains `[42]`. Am I right?

**Comment by startupthekid** [comment]
Yeah that's true, made a mistake there.

**Comment by dmcrodrigues** [comment]
Well, that means we can have this behaviour with #2835 if it goes forward 😃
