### ISSUE TITLE
Better way to do bindings

### ISSUE THREAD

**Issue by jozsef-vesza** [ReactiveCocoa/ReactiveCocoa#2818]
I've been trying to dig into ReactiveCocoa, and FRP in general. I really like RAC as a framework, but I've been struggling with the "mental shift":  I _can_ get things to work, but I don't feel like I'm doing them the _right_ way, and would love some clarification.

I have the following view model API:

```swift
public protocol ViewerViewModelType {
    var title: AnyProperty<String> { get }
    var currentPage: AnyProperty<NSData> { get }
    var canMoveForward: AnyProperty<Bool> { get }
    var canMoveBackwards: AnyProperty<Bool> { get }
    func moveForward()
    func moveBackwards()
}
```

I bind the properties of my view controller in the following way:

```swift
DynamicProperty(object: self, keyPath: "title")
    <~ viewModel.title.producer.map { $0 as AnyObject }
DynamicProperty(object: backButton, keyPath: "enabled")
    <~ viewModel.canMoveBackwards.producer.map { $0 as AnyObject }
DynamicProperty(object: forwardButton, keyPath: "enabled")
    <~ viewModel.canMoveForward.producer.map { $0 as AnyObject }
```

Also, I'm triggering view model functions like this:

```swift
@IBAction func previousPage(sender: AnyObject) {
    viewModel.moveBackwards()
}
@IBAction func nextPage(sender: AnyObject) {
    viewModel.moveForward()
}
```

While these do the job, I have a feeling that there's a better way to approach this.

- is it possible to bind AppKit/UIKit objects to my view model in a nicer way? Something like:

```swift
backButton.enabled <~ viewModel.canMoveBackwards
```

- is there a better way to trigger commands/actions on the view model?

Anything, that can point me to the right direction, is much-much appreciated! 👍

**Comment by RuiAAPeres** [comment]
@jozsef-vesza `CocoaAction` and `Action` is probably what you want, since they take into consideration the enable state (more specifically the `CocoaAction`). Check [this example](https://github.com/RuiAAPeres/RACNest/blob/32549b7d3afd417d46b7435415779e7c9cd5cd46/RACNest/ViewControllers/Form/Components/FormViewModel.swift), let us know if you need further assistance.

**Comment by jozsef-vesza** [comment]
@RuiAAPeres thanks, you've definitely pointed me in the right direction. Modified my VM to expose `CocoaAction` properties:

```swift
public final class ViewerViewModel: NSObject, ViewerViewModelType {
    
    public let currentPage: AnyProperty<NSData>
    public let title: AnyProperty<String>
    public let moveForward: CocoaAction
    public let moveBackwards: CocoaAction
    
    public init(comic: ComicType) {
        
        let comic = MutableProperty(comic)
        
        let index = MutableProperty(0)
        
        let mutableCurrentPage = MutableProperty(comic.value.pageData[0])
        mutableCurrentPage <~ index.producer.map { return comic.value.pageData[$0] }
        currentPage = AnyProperty(mutableCurrentPage)
        
        let mutableTitle = MutableProperty("")
        mutableTitle <~ index.producer.map { return comic.value.title + " " + "(\($0 + 1)/\(comic.value.pageData.count))" }
        title = AnyProperty(mutableTitle)
        
        let canMoveForward = MutableProperty(true)
        canMoveForward <~ index.producer.map { return $0 != comic.value.pageData.count - 1 }
        let canMoveBackwards = MutableProperty(false)
        canMoveBackwards <~ index.producer.map {
            return $0 != 0
        }
        
        let moveForwardAction = Action<Void, Void, NoError>(enabledIf: canMoveForward) { _ in
            return SignalProducer { observer, disposable in
                index.value += 1
                observer.sendCompleted()
            }
        }
        
        moveForward = CocoaAction(moveForwardAction, input: ())
        
        let moveBackwardsAction = Action<Void, Void, NoError>(enabledIf: canMoveBackwards) { _ in
            return SignalProducer { observer, disposable in
                index.value -= 1
                observer.sendCompleted()
            }
        }
        
        moveBackwards = CocoaAction(moveBackwardsAction, input: ())
        
        super.init()
    }
}
```

This seems a bit more "RAC", since values are bound to each other.

In my VC I now have this:

```swift
DynamicProperty(object: self, keyPath: "title")
    <~ viewModel.title.producer.map {$0 as AnyObject}

forwardButton.target = viewModel.moveForward
forwardButton.action = CocoaAction.selector

backButton.target = viewModel.moveBackwards
backButton.action = CocoaAction.selector
```

Everything works well, just one minor follow-up question: although the actions won't fire, when they are disabled, the button's state does not reflect this (you can press the button, but it doesn't do anything). is this a known thing?

**Comment by RuiAAPeres** [comment]
@jozsef-vesza no, the button should be disabled. Could you have set, by mistake, the same asset for enabled/disabled?

**Comment by jozsef-vesza** [comment]
I don't think so. My first solution:
```swift
DynamicProperty(object: backButton, keyPath: "enabled")
    <~ viewModel.canMoveBackwards.producer.map { $0 as AnyObject }
```
disables the `NSButton` correctly (since I'm setting the key directly, I assume), but this second one doesn't.

**Comment by s0mmer** [comment]
@jozsef-vesza Consider looking into [Rex](https://github.com/neilpa/Rex) which adds some convenient UI bindings.

**Comment by jozsef-vesza** [comment]
@RuiAAPeres @s0mmer thank you both for the suggestions, I'm quite happy with the solution I got with Rui's help. Will definitely check out Rex as well. As my question is resolved, I think it's safe to close this issue (the `NSButton` issue is not really relevant to the question).
