### ISSUE TITLE
How to bind to an NSPopupButton?

### ISSUE THREAD

**Issue by xgalaxy** [ReactiveCocoa/ReactiveCocoa#2820]
Hello,

What would be the best way to bind to an NSPopupButton. What I need is to get the index of the selected value and store it in a MutableProperty. Should I be using Action for this?

Thanks

**Comment by mdiep** [comment]
`NSPopUpButton` doesn't have a lot of options. It looks like you can either use target/action or bindings.

I would probably try to expose a `MutableProperty` property in an `NSPopUpButton` extension (like [Rex](https://github.com/neilpa/Rex/) does). That should be relatively straightforward by binding the `NSPopUpButton` to the property.

Alternatively, you could add a private object that does the binding and provides some notifications that you can hook up to.

`Action`s are analogous to functions; I don't think they're relevant here.

Feel free reopen if you need more help!

**Comment by ianbytchek** [comment]
@xgalaxy have you solved this?
