### ISSUE TITLE
How do i bind Viewmodel methods to ViewControllers 

### ISSUE THREAD

**Issue by vishal91** [ReactiveCocoa/ReactiveCocoa#2821]
Hi , 

i am trying to implement Facebook/google login with MVVM and ReactiveCocoa. Please can you help how to bind methods to viewcontrollers . 
`FBSDKLoginManager().logInWithReadPermissions(["public_profile", "email", "user_friends"], fromViewController: nil) { (FBSDKLoginManagerLoginResult!, NSError!) in
     }`

and how to pass viewcontroller in this method if its implemented in Viewmodel ?

**Comment by RuiAAPeres** [comment]
@vishal91 Could you give a bit more detail about the issue you are having?

**Comment by vishal91** [comment]
@RuiAAPeres I am having a viewModel and ViewController. ViewController containts UIViews with facebook /Google login buttons. I want when the user clicks on any of the button . It should call the methods which are lying in viewModel and tell view controller when the execution is complete , So that it can push the new viewcontroller. I can do that succesfully with callbacks. But i want to rely on reactiveCocoa totally for this app.

**Comment by RuiAAPeres** [comment]
@vishal91 a `CocoaAction` is what you are looking for. I would advise looking at [this](https://github.com/RuiAAPeres/RACNest/blob/32549b7d3afd417d46b7435415779e7c9cd5cd46/RACNest/ViewControllers/Form/Components/FormViewModel.swift).  Specifically how the [`CocoaAction` is created ](https://github.com/RuiAAPeres/RACNest/blob/32549b7d3afd417d46b7435415779e7c9cd5cd46/RACNest/ViewControllers/Form/Components/FormViewModel.swift#L53#L55) via a [`Action`](https://github.com/RuiAAPeres/RACNest/blob/32549b7d3afd417d46b7435415779e7c9cd5cd46/RACNest/ViewControllers/Form/Components/FormViewModel.swift#L31#L42).

**Comment by vishal91** [comment]
@RuiAAPeres 

`        signupView.fbBtn.rex_pressed  <~ SignalProducer(value: viewModel.loginWithfacebook(self, completion: { (executed) in
            self.navigationController?.pushViewController(ROnboardingViewController(state:.emailSignup,model:self.viewModel), animated: true)
        }))`

rex_pressed is not the member

**Comment by RuiAAPeres** [comment]
`rex_pressed` is coming from [here](https://github.com/neilpa/Rex/blob/master/Source/UIKit/UIButton.swift).

**Comment by vishal91** [comment]
@RuiAAPeres :Thanks for your help. But whats the need to make that action. 
can't we use CocoaAction directly/

If you can tell me how to achieve in this.. i think i will get it .

viewmodel : Action<input:ViewController,output:Bool,NSError> i want to define one action like this . 

viewcontroller : CocoaAction in which i can send the viewcontroller as a parameter . 

And how to write function in that actions .

**Comment by RuiAAPeres** [comment]
Both initialisers, take an `Action`, so you need to create your own. It shouldn't be difficult:

```swift
let producer: SignalProducer<Bool, NSError> = // your producer

let action: Action<UIViewController, Bool, NSError> = Action { viewController in 
    // do something with your input 
   return producer
}

// from your `UIViewController`
let cocoaAction = CocaAction(action, input: self)
```

**Comment by vishal91** [comment]
`    let producer:SignalProducer<Bool, NSError>
    var fbLoginAction:Action<ROnboardingViewController,Bool,NSError> = Action { viewController in
        FBSDKLoginManager().logInWithReadPermissions(["public_profile", "email", "user_friends"], fromViewController: viewController, handler: { (result:FBSDKLoginManagerLoginResult!, error:NSError!) in
            if (error == nil){
                let fbloginresult : FBSDKLoginManagerLoginResult = result
                if(fbloginresult.grantedPermissions.contains("email")){
                    if((FBSDKAccessToken.currentAccessToken()) != nil){
                        FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "id, name, first_name, last_name, picture.type(large), email"]).startWithCompletionHandler({ (connection, result, error) -> Void in
                            if (error == nil){
                                print(result)
                                //                                self.email = result.email
                                //                                self.name = result.name
                                return producer
                            }
                        })
                    }
                    
                }
            }

        })`

Showing error cannot convert Void to SignalProducer. How to define SignalProducer ? Sorry for these question. Kind of stuck.

**Comment by RuiAAPeres** [comment]
Something like this:


```swift
let toProducer: ROnboardingViewController -> SignalProducer<Bool, NSError> =  { viewController in 

    FBSDKLoginManager().logInWithReadPermissions(["public_profile", "email", "user_friends"], fromViewController: viewController, handler: { (result:FBSDKLoginManagerLoginResult!, error:NSError!) in
      guard error != nil else { return SignalProducer(error: error) }

      let fbloginresult : FBSDKLoginManagerLoginResult = result
      if(fbloginresult.grantedPermissions.contains("email")){
            if((FBSDKAccessToken.currentAccessToken()) != nil){
                  FBSDKGraphRequest(graphPath: "me", parameters: ["fields": "id, name, first_name, last_name, picture.type(large), email"]).startWithCompletionHandler({ (connection, result, error) -> Void in

                        guard error != nil else { return SignalProducer(error: error) }

                        print(result)
                        return SignalProducer(value: true)
                     }
                 })
            }
      }
}

let fbLoginAction:Action<ROnboardingViewController,Bool,NSError> = Action(toProducer) 
```

**Comment by vishal91** [comment]
This is also giving lots of error . Thanks for help . 👍

**Comment by RuiAAPeres** [comment]
@vishal91 could you tell me what errors are showing? 😞

**Comment by vishal91** [comment]
![screenshot 2016-04-25 20 32 30](https://cloud.githubusercontent.com/assets/3819785/14788303/ea15b2e0-0b24-11e6-93b6-e2171fefc49a.png)

**Comment by RuiAAPeres** [comment]
@vishal91 I updated the code snippet. But it seems to me it's just a matter of closing parenthesis/brackets.

**Comment by vishal91** [comment]
error: cannot convert value of type '()' to closure result type 'SignalProducer<_, _>'

**Comment by vishal91** [comment]
I tried learning ReactiveCocoa. Can you please suggest some good tutorials.

**Comment by RuiAAPeres** [comment]
The examples in [RACNest](https://github.com/RuiAAPeres/RACNest) are pretty decent, but I am bit biased. You can find a ton of stuff [here](https://gist.github.com/JaviLorbada/4a7bd6129275ebefd5a6) as well.  ✨

Hope I was able to help! I am closing this issue now.
