### ISSUE TITLE
RACDC 2016

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2824]
The same way the generous folks at Github organised RACDC2015 ( #1909 ), I think it would be awesome to repeat it this year as well. ✨

What do you guys think? @ReactiveCocoa/reactivecocoa

**Comment by NachoSoto** [comment]
I think that would be great. Between work 👔 and flying 🛩 I don't think I'll have time to prepare anything this year, but would still love to attend 👍

**Comment by kastiglione** [comment]
Count me in too.

**Comment by JaviSoto** [comment]
Count me in :) I could speak if others are interested (perhaps show how the Fabric app was built using RAC)

**Comment by RuiAAPeres** [comment]
I am up for a talk as well, I think the biggest issue is the venue.

**Comment by mdiep** [comment]
I didn't win a WWDC ticket, so I won't be there. 😞

**Comment by amccarri** [comment]
I managed to get a WWDC ticket.  Would love to chat about RAC stuff, even if it's just informal hanging out at a bar talking about RAC. :)

**Comment by KyleLeneau** [comment]
I did not win a WWDC ticket but live in the bay area and would love to attend something like this if it happens this year.

**Comment by DavdRoman** [comment]
I didn't get a ticket this year, but there's a really good chance I'll be in SF that week for all other events 😄

**Comment by brow** [comment]
Yes! I won't be able to prepare a talk, but I'd love to do "labs" again.

**Comment by JaviSoto** [comment]
I could try to get Twitter to sponsor a venue. What head-count do you think we would have?

**Comment by kastiglione** [comment]
📟 @joshaber 📟

**Comment by RuiAAPeres** [comment]
@javi perhaps we could go the other way around. How many people can you host? I think even if it's something small (< 30) it would still be great!

**Comment by Coneko** [comment]
@RuiAAPeres Time for the RACDC lottery? 👯

**Comment by RuiAAPeres** [comment]
@coneko unfortunately Bill Graham is already booked. :P

**Comment by JaviSoto** [comment]
@RuiAAPeres I believe I could host to up to like 70 people. Seeing how many people attended last year that should be enough?

**Comment by RuiAAPeres** [comment]
@JaviSoto that would be awesome! ❤️

**Comment by JaviSoto** [comment]
I'm gonna put in a request :) What day would work best? Perhaps Wednesday June 15th at ~10am?

**Comment by RuiAAPeres** [comment]
@JaviSoto Whatever makes it easy for you. Having a venue is already a win!

**Comment by JaviSoto** [comment]
I filed a request for this, let's see what happens :)

**Comment by AvdLee** [comment]
Trying to fix my flight, but will definitely be there if I'm around!

**Comment by mdiep** [comment]
I've had a change of plans and will be in SF. So I'll plan to attend if this happens! 🎉

**Comment by RuiAAPeres** [comment]
@mdiep niiiiice. 👯

**Comment by liscio** [comment]
I'll be in SF with a golden ticket in-hand, but mid-week in the morning is tougher to swing during conference hours. Wednesday is usually when "the good labs" (audio, media, accelerate, anything to do with Mac) start.

If I'm unable to make whatever you folks plan, I'd love to meet up after hours somewhere.

**Comment by JaviSoto** [comment]
@ReactiveCocoa/reactivecocoa Hey all! I just wanted to confirm that I got Twitter (Fabric) to host RACDC16 at Twitter HQ in SF on June 15th from 10am to 3pm, lunch will be provided for as well :)

I'll be posting more details, let me know if you have any questions / requests!

**Comment by alanjrogers** [comment]
I'm hoping to be in SF around WWDC (just not 100% yet). If I make it, I'll definitely attend RACDC!

**Comment by tonyarnold** [comment]
I'll be in SF for WWDC, and would love to say thanks to a few of you fine folk while I'm there. Count me in!

**Comment by robb** [comment]
I might just make it after all 🎉

**Comment by nikita-leonov** [comment]
@JaviSoto Is there any list where we need to RSVP? RAC is popular, it is possible that there will be more people than twitter can fit ;)

**Comment by JaviSoto** [comment]
@nikita-leonov Hi! Sorry for the delay :( I'm still working on the logistics with Twitter, but we're gonna put out a sign-up page as soon as possible :)

Just to confirm: RACDC16 will be hosted at Twitter HQ June 15th from 10am to 3pm.

**Comment by aschuch** [comment]
Is there any chance RACDC16 is going to be video recorded and/or live-streamed as well?

**Comment by mdiep** [comment]
In case anyone missed it, registration is [here](https://www.eventbrite.com/e/reactivecocoa-developer-conference-2016-tickets-25798882151).

I'm going to close the issue now that this is organized. 😄
