### ISSUE TITLE
"not" signal not accept 'nil'

### ISSUE THREAD

**Issue by krypt-lynx** [ReactiveCocoa/ReactiveCocoa#2825]
This behavior highly limit usage of this signal.

For example I not able to use it before observed value is assigned:
`RAC(self.disclosureIndicator, hidden) = [RACObserve(self, item.showDisclosureIndicator) not];`

**Comment by krypt-lynx** [comment]
I'm not sure about "legacy":
NSAssert still there:
https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/RACSignal%2BOperations.m#L1285

**Comment by ikesyo** [comment]
That is just about **Objective-C API**, not about Swift API.

**Comment by krypt-lynx** [comment]
swift api is just wrapper around of ObjC, no?

**Comment by ikesyo** [comment]
> swift api is just wrapper around of ObjC, no?

Completely no.

**Comment by ikesyo** [comment]
`[[RACObserve(self, item.showDisclosureIndicator) ignore:nil] not]` would help.

**Comment by krypt-lynx** [comment]
Thanks for the hint

**Comment by mdiep** [comment]
`-[RACSignal not]` intentionally doesn't accept `nil`. You need to `map` or `ignore:` to provide a value for `nil`s.

**Comment by krypt-lynx** [comment]
It not fits with usual objc behavior, there you can send message to nil and receive nil (or 0, NO) as result
