### ISSUE TITLE
Different behaviour between DynamicProperty and KVO

### ISSUE THREAD

**Issue by dmcrodrigues** [ReactiveCocoa/ReactiveCocoa#2829]
I noticed a difference of behaviour between KVO and a `DynamicProperty` and I don't know if is something that we should expect since the purpose of the property is to wrap changes from a `dynamic` property or one defined in Objective-C using KVC and KVO.

With KVO, changes are propagated synchronously which gives a chance to any registered observer to act upon that change before it completes. With a `DynamicProperty` that behaviour is not achievable because at [a certain point](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/RACSubscriptionScheduler.m#L38) RAC dispatches the propagation of the next value asynchronously in another queue unless that change occurs in the main-thread where, in that case, everything works in a synchronous manner as expected.

Here's an example to demonstrate this behaviour.

```swift
import ReactiveCocoa

class SomeObject: NSObject {
    dynamic var x: Int = 0
}

let instance = SomeObject()

DynamicProperty(object: instance, keyPath: "x")
    .signal
    .observeNext { next in
        assert((next as! Int) == instance.x)
        // Perform some work...
        NSThread.sleepForTimeInterval(2)
}

let queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)

dispatch_async(queue) {

    instance.x = 10

    instance.x = 20

    instance.x = 30
}
```

Another thing to notice is that if we use a `MutableProperty`, everything works as expected, each observer is synchronously notified about the next value and the execution doesn't proceed until all have been notified and handled the change. That's something that we should also expect for a `DynamicProperty`? In my opinion it should behave the same way and replicating the behaviour that we have with KVO.

**Comment by mdiep** [comment]
I'm honestly not sure.

I think RAC does this to guarantee that the changes are processed serially—to prevent two values from being sent simultaneously. But this can also be achieved using a lock like `MutableProperty` does. So I don't see why `DynamicProperty` would need to work this way.

Would you be interested in exploring more and maybe opening a PR?

**Comment by andersio** [comment]
@mdiep It should be a valid issue. The `didSubscribe` block supplied by `rac_valuesForKeyPath:` is executed on a private queue (as pointed by @dmcrodrigues) asynchronously. I am not sure what the design contract is for the Objective-C version, but the Swift's version of design contract mandates that events should be sent synchronously for vanilla signals (https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/DesignGuidelines.md#events-are-sent-synchronously-by-default), which I think `DynamicProperty` is qualified for as it is a standard .

**Comment by mdiep** [comment]
This is just a limitation because the existing depends on the Obj-C implementation of RAC KVO observing. This will be fixed naturally as we split up the repository. (#2807)

**Comment by andersio** [comment]
Fixed in the implementation of `NSObject.values(forKeyPath:)`.
