### ISSUE TITLE
Remove Objective-C APIs

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveCocoa#2830]
As discussed in #2807, we will move the Objective-C APIs to a separate repo and also move the Obj-C/Swift bridging to a separate repo.

This will need to happen as part of the 5.0 release because it is a breaking change.

**Comment by mdiep** [comment]
This could now be done in a PR that targets the `RAC5` branch.

**Comment by mdiep** [comment]
I think it will be best to create the ReactiveObjC repo from the `2.x-maintenance` branch. I just backported several RAC2 PRs to that branch. I think it’s now up-to-date wrt to `master` except that

1. It's missing tvOS and watchOS targets
2. Deprecated APIs were removed on `master`

It should be easier to add tvOS and watchOS targets than to make re-add the deprecated APIs and remove all the Swift code.

**Comment by ikesyo** [comment]
I've backported one more PR to `2.x-maintenance`: afd53b9
