### ISSUE TITLE
Remove SignalProducer.buffer()

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveCocoa#2831]
As discussed in #2744.

This is a breaking change, so it will need to be part of the 5.0 release.

**Comment by ikesyo** [comment]
We should also refactor `SignalProducer.replayLazily` not to use `buffer` or consider removing it as well.

**Comment by filblue** [comment]
+ for removing `replayLazily`

**Comment by mdiep** [comment]
This was done in #3028.
