### ISSUE TITLE
CompositeDisposable how clear from old value?

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#2832]
I have next scheme get SignalProducer

transport -> service -> viewModel -> controller

If I start SignalProducer and leave from screen my controller deinit, viewmodel deinit but because I use inside closure [unowned self] I can crash if I leave in process handler.

So I add each disposable object to CompositeDisposable and call dispose() in deinit. Now I don't crash but my bag still have old disposable

How can I resolve this problem with clear old ComplisiteDisposable?
Or what I do wrong?

**Comment by RuiAAPeres** [comment]
A `SignalProducer` once started, will [create a retain cycle](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L40#L80) between its inner `Signal` and the `Observer`. So although both your ViewModel  and `SignalProducer` get released, that retain cycle will remain. There are ways for taking care of this, like:

* You dispose of the `SignalProducer` via the `Disposable` returned when used with a `start...`. I find it odd that this is not working.  Anyway, you should avoid doing this, as it goes against RAC best practises
* You use methods like take, `takeWhile`, `until`, which will terminate the `SignalProducer` and its inner `Signal`. This is the preferred way.

There might be another retain cycle. Do you have some code you could show?

**Comment by ajjnix** [comment]
@RuiAAPeres thanks for answer, after watch init method at links I all understood )
