### ISSUE TITLE
Debug events

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2833]
RxSwift provides a quite handy mechanism for debugging events via the `debug` operator ( more info [here](https://github.com/ReactiveX/RxSwift/blob/77d72dcaee908bcf61baf88080661e748e367557/Documentation/GettingStarted.md#debugging)). There is a `resourceCount` as well, that could be interesting, although I think it would force us to [scatter some macros](https://github.com/ReactiveX/RxSwift/search?utf8=%E2%9C%93&q=resourceCount) around the code base.

I am up for doing the `debug()`, but I would like your opinion on the `resourceCount`). 

Thanks @scotteg for the reference!

**Comment by dmcrodrigues** [comment]
This `debug` operator can be extremely handy, sometimes I do this manually to figure out what's going on which is not ideal to be honest. 

Big 👍 to add this operator.

**Comment by dmcrodrigues** [comment]
About `resourceCount` I think it can be helpful, probably using protocol extensions to introduce this behaviour in a meaningful way and internally use a swift flag to enable/disable this tracing. @jckarter has pointed [here](https://twitter.com/jckarter/status/725354658286325760) that empty functions may be optimized away by the compiler.

**Comment by mdiep** [comment]
👍 for `debug`. In RAC2, this was called `logAll`. I think it's useful.

`resourceCount` doesn't seem as useful to me, and it adds quite a bit of complexity, so I'm 👎 on that.
