### ISSUE TITLE
Propagating errors

### ISSUE THREAD

**Issue by jozsef-vesza** [ReactiveCocoa/ReactiveCocoa#2843]
In my project, I have a few operations, which can fail with errors (e.g. saving/importing files). An example:

```swift
func storedComics() -> Result<[ComicDescriptor], ComicKitErrorType>
```

My view models invoke these methods, but in turn, they expose properties, my view controllers bind to. In order to enable binding, I have to make my producers' error type `NoError`:

```swift
let loadComics = SignalProducer<[ComicType], NoError> { observer, disposable in
    
    let result = fileManager.storedComics().flatMap(Comic.create)
    
    switch result {
    case .Success(let comics):
        observer.sendNext(comics)
    case .Failure(let error):
        // ???
    }
    
    observer.sendCompleted()
}
```

My question is the following: What would be an elegant way to propagate the errors of these operations to the level of the view controllers (so they can show an alert, when appropriate)?

For now, I have come up with the following solution:

My view models expose an error signal:

```swift
public let error: Signal<ComicKitErrorType, NoError>
```

Internally, I use pipes to send errors through these signals:

```swift
let (signal, pipe) = Signal<ComicKitErrorType, NoError>.pipe()
error = signal

let loadComics = SignalProducer<[ComicType], NoError> { observer, disposable in
    
    let result = fileManager.storedComics().flatMap(Comic.create)
    
    switch result {
    case .Success(let comics):
        observer.sendNext(comics)
    case .Failure(let error):
        pipe.sendNext(error)
    }
    
    observer.sendCompleted()
}
```

And in my view controller, I subscribe to the error signal:

```swift
viewModel.error.observeNext { error in
    // handle error
}
```

I feel like this is a proper way of doing this, but this could be a common issue, and I'm wondering if I've missed something. Is there a better way to do this?

**Comment by dmcrodrigues** [comment]
An alternative could be using an [Action](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/FrameworkOverview.md#actions) to implement that kind of operations, I find them quite idiomatic since they clearly declares the types expected: `Input`, `Output` and `Error`.

An `Action` has the benefit of giving you two signals that can be extremely helpful: [values](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Action.swift#L25) and [errors](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Action.swift#L31). Your view controller can bind into the `values` signal without being worried about the error type and you continue to have a signal to handle the errors that may occur. Internally you continue to have your `SignalProducer` so they are quite straightforward.

I know that @RuiAAPeres is also using them, maybe he can also share some insight about this.

**Comment by jozsef-vesza** [comment]
@dmcrodrigues I am familiar with actions, but I always think of them, when I explicitly want to perform some work:

- I want to add an item to my collection -> Action
- I want to load my items on launch -> Just bind to an observable property, which in turn will start the signal producer to load the data.

In my view model implementation, I combine these two, and bind them to the observable property, so it gets updated on launch, and when an addition is invoked:

```swift
addToCollection = Action { url in
    return SignalProducer { observer, disposable in
        
        let result = comicImporter.importComicsFromUrl(url).flatMap(Comic.create)
        
        switch result {
        case .Success(let comics):
            observer.sendNext(comics)
        case .Failure(let error):
            pipe.sendNext(error)
        }
        
        observer.sendCompleted()
    }
}

let loadComics = SignalProducer<[ComicType], NoError> { observer, disposable in
    
    let result = fileManager.storedComics().flatMap(Comic.create)
    
    switch result {
    case .Success(let comics):
        observer.sendNext(comics)
    case .Failure(let error):
        pipe.sendNext(error)
    }
    
    observer.sendCompleted()
}

let addProducer = SignalProducer(signal: addToCollection.values)
let combinedProducer = SignalProducer(values: [addProducer, loadComics]).flatten(.Merge)

comics = AnyProperty(initialValue: [], producer: combinedProducer)
```

**Comment by RuiAAPeres** [comment]
The best way I found to propagate erros and still be able to bind is via an enum that groups the different states:

```enum
enum FetchResult<T> {
   case Success(T)
   case Failure(ComicKitErrorType)
   case InProgress
}
```

And your property being defined as: 

```swift
let loadComics = SignalProducer<FetchResult<[ComicType]>, NoError>
```

**Comment by jozsef-vesza** [comment]
@dmcrodrigues @RuiAAPeres thanks, these are both great suggestions. I think I'll give another try to actions. We can close this one 👍
