### ISSUE TITLE
Handling errant multiple UIKeyboardWillShowNotification notifications due to custom keyboard

### ISSUE THREAD

**Issue by nickvelloff** [ReactiveCocoa/ReactiveCocoa#2855]
Apparently (having nothing to do with RAC), having a custom keyboard like Word Flow installed can cause 3 (in my case) `UIKeyboardWillShowNotification` events to fire in rapid succession, causing all kinds of havoc with animated constraint management.

I'm new to RAC, and have tried a few things but really would like to know the _correct_ way to handle this.

```
let keyboardShowNotificationProducer = NSNotificationCenter.defaultCenter()
        .rac_notifications(UIKeyboardWillShowNotification)

keyboardShowNotificationDisposable = keyboardShowNotificationProducer
            .startWithNext { [weak self] notif in
                // do all the things
                print("UIKeyboardWillShowNotification")
            }
```
Any help is appreciated 🙇

**Comment by nickvelloff** [comment]
This appears to have the desired affect, but not sure if the approach is sound.
``` Swift
keyboardShowNotificationProducer
            .observeOn(UIScheduler())
            .takeUntilViewControllerDisappears(self)
            .skipRepeats { notifA, notifB in
                return notifA != notifB
            }
            .startWithNext { [weak self] notif in
                print("UIKeyboardWillShowNotification")
        }
```

**Comment by nickvelloff** [comment]
Wow so as it turns out with custom keyboards, the `UIKeyboardWillShowNotification` fires multiple times and only the last one has the correct frame measurement for `UIKeyboardFrameEndUserInfoKey` (the ending frame for the keyboard). So I need to figure out how to capture the _last_ one.

**Comment by nickvelloff** [comment]
OK this is not a RAC issue, sorry for the spam :)

**Comment by iv-mexx** [comment]
You can try the [`throttle`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift#L993) operator: 

> Throttle values sent by the receiver, so that at least `interval`
> seconds pass between each, then forwards them on the given scheduler.
>
> If multiple values are received before the interval has elapsed, the
> latest value is the one that will be passed on.

**Comment by nickvelloff** [comment]
Thanks @iv-mexx!
