### ISSUE TITLE
how to call a RACCommand

### ISSUE THREAD

**Issue by pradeepb28** [ReactiveCocoa/ReactiveCocoa#2856]
I have a raccombmand example:

```
var back:RACCommand = RACCommand { _ in return RACSignal.empty() }
```

I want to call 'back' from some other method. Is it possible?

**Comment by rcgary** [comment]
Base on your example, it shoule be something like this:
```swift
back.execute(input)
```
But I think you may want check out `Action` and `CocoaAction` if you are using swift

**Comment by ikesyo** [comment]
Thanks for the answer! @rcgary Closing.
