### ISSUE TITLE
Introducing `Single` type

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2873]
### Description
This was taken from the [RxJava's `Single`](http://reactivex.io/documentation/single.html) description:

> A `Single` is something like an `Observable`, but instead of emitting a series of values — anywhere from none at all to an infinite number — it always either emits one value or an error notification.

> For this reason, instead of subscribing to a Single with the three methods you use to respond to notifications from an `Observable` (`onNext`, `onError`, and `onCompleted`), you only use two methods to subscribe:

>`onSuccess`
a `Single` passes this method the sole item that the Single emits
`onError`
a `Single` passes this method the Throwable that caused the `Single` to be unable to emit an item
A `Single` will call only one of these methods, and will only call it once. Upon calling either method, the `Single` terminates and the subscription to it ends.

### Motivation

Most of the `SignalProducer` I create manually, act pretty much as a `Single`: after one value has been acquired/created and sent (as a `.Next` event), it is immediately followed  by a `.Completed`. Out of my head, the only cases where my Producer sends more than one `.Next` event, is when it's used as part of a `Property`. Having a `Single` type would help the developer to better express his/her intent. 

### Cons

FRP central concept is the idea of values over time. `Single`, doesn't really play well with that concept, since it acts more like a Promise/Future. On the other hand [RAC is inspired by FRP, not really a true FRP implementation](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1342).

### Breaking changes

There are no breaking changes, since this is a new type/api.

**Comment by amccarri** [comment]
Is this like +RACSignal:return?

**Comment by mdiep** [comment]
> Is this like +RACSignal:return?

`+[RACSignal return:]` returns the equivalent of a `Signal<Value, Error>` that just happens to send a single value. @RuiAAPeres is proposing a new type that only sends a single value.

I've definitely wanted something like this before. But usually I want `.Completed` to have a value so that I can also send progress. Unfortunately, that would mean adding another type parameter.

I think there's some room for us to do something here, but I think we should wait until after RAC 5 to do it. I think we'll have our hands full splitting up the APIs and adding new UI bindings.

**Comment by erikprice** [comment]
> But usually I want .Completed to have a value so that I can also send progress.

I assume you're currently doing progress/final value with some sort of `Either<Progress, FinalValue>` type?

I like the simplicity of `.Completed` having a type of `()`. If it _did_ have a value, then would one expect that the various operations (e.g., `map:`) would affect that value? Seems to introduce some complexity.

**Comment by RuiAAPeres** [comment]
@mdiep what do you think about opening a 6.0 milestone for this?

**Comment by mdiep** [comment]
We may as well wait to do that until we migrate repositories—because this would be a ReactiveSwift issue. ☺️

**Comment by RuiAAPeres** [comment]
Makes sense. 👍 I will re-open once we go it!
