### ISSUE TITLE
Add missing Signal's operators @ Playground

### ISSUE THREAD

**Issue by RuiAAPeres** [ReactiveCocoa/ReactiveCocoa#2875]

**Comment by tomj** [comment]
hey @RuiAAPeres just starting to knock this off now, do you think it best to follow the structure you've established with `SignalProducer` over [here](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa.playground/Pages/SignalProducer.xcplaygroundpage/Contents.swift)?  I can drop an initial few operators on my branch and you can point out whether you think it's heading in the right direction, I'd hate to do all the operators only to have it not match the style you'd intended.

I'll start with: `collect`, `combineLatest`, `delay`, `skip` and `materialize` unless any objections 😀

**Comment by RuiAAPeres** [comment]
@tomj make yourself at home. The way I went with the SignalProducer's was by order and using their own documentation.

**Comment by tomj** [comment]
Rock and roll - will do.  Cheers 😄

**Comment by tomj** [comment]
fyi I'm pushing my work on this up to [my fork](https://github.com/tomj/ReactiveCocoa/tree/signal_playground) just in case anyone is working on this at the same time

**Comment by mdiep** [comment]
The playground has moved to ReactiveSwift, but I think this has been completed anyway.
