### ISSUE TITLE
Method to get `.NotEnabled` ActionEvent`s from an Action

### ISSUE THREAD

**Issue by startupthekid** [ReactiveCocoa/ReactiveCocoa#2882]
When `apply` is called on an action, `.NotEnabled` is sent on the signal producer resulting from `apply` but not on the `events` or `errors` observer. So if an action is wrapped in a CocoaAction and added to a button, without directly calling apply, there's no way of knowing that the `.NotEnabled` error occurred. 

One useful situation would be if you have an action added to the `.EditingDidEnd` event of a text field and you wanted to show a confirmation dialog in the cases where the user hits done on the keyboard but the action isn't enabled.

Any thoughts?

**Comment by mdiep** [comment]
Typically, we'd set it up that the button is disabled if the action is not enabled. The Obj-C API does this with `RACCommand` and [Rex](https://github.com/neilpa/Rex/) does this with it's extension on `UIButton`.

**Comment by startupthekid** [comment]
What I'm saying though is say you want to do this:

```swift
self.showErrorDialog <~ self.someAction.errors.filter { $0 == .NotEnabled }.map { _ in }
```
Without directly calling `apply()`, we can never get at the `.NotEnabled` error and react in response to that happening.

**Comment by ikesyo** [comment]
Sending `.NotEnabled` on `events` (and `errors`) makes sense to me. `Action`s would not necessarily be bound with a `UIButton` and its `enabled` state.

I'll submit a PR to address this.

**Comment by mdiep** [comment]
The types of `events` and `errors` don't support sending `.NotEnabled`.

I think the only way to support something like is to add a new property that's a `Signal<Output, ActionError<Error>>`.

**Comment by ikesyo** [comment]
Oh, I overlooked that point. 💦

**Comment by iv-mexx** [comment]
Maybe `events` and `errors` should have `ActionError<Error>` instead of `Error` directly?

**Comment by ikesyo** [comment]
> Maybe `events` and `errors` should have `ActionError<Error>` instead of `Error` directly?

Those are breaking changes, so even if we introduce that changes, that should be done in 5.0.

**Comment by mdiep** [comment]
Closing because the core Swift code has been moved to https://github.com/ReactiveCocoa/ReactiveSwift/. Please re-open there if you're still interested in this.

**Comment by ikesyo** [comment]
https://github.com/ReactiveCocoa/ReactiveSwift/issues/32
