### ISSUE TITLE
A problem between cocoa pods and ReactiveCocoa

### ISSUE THREAD

**Issue by BiggerGao** [ReactiveCocoa/ReactiveCocoa#2886]
There are 20 errors like that 'Duplicate interface definition for class 'RACStream'' after I #import "ReactiveCocoa.h" in my project. I can't import 'ReactiveCocoa' at first because of the part of swift, so I append  'use_frameworks!' at the end in pod file.But it's another problem。I had version <b>cocoapods-0.39.0</b>,and I downgrading to <b>cocoapods-0.38.2</b> to fix it but it doesn't work.
there is my pods file：

```
platform :ios, ‘8.0’
 
pod 'ReactiveCocoa'
pod 'Mantle'
pod 'LBBlurredImage'
pod 'TSMessages'
use_frameworks!
```
Thanks in advance!

**Comment by MCKapur** [comment]
Hey. I'm having this issue right now - how did you end up fixing it?

**Comment by BiggerGao** [comment]
If you using it in your project and you using objc,you should using version lower than 3.Like using `pod 'ReactiveCocoa', '~> 2.5`
