### ISSUE TITLE
Throttle misdescribed in the README

### ISSUE THREAD

**Issue by tditchek** [ReactiveCocoa/ReactiveCocoa#2890]
The online search example in the wiki claims the `throttle` operator "prevents values from being sent less than 0.5 seconds apart, so the user must stop editing for at least that long before we’ll use their search string." However, it's not working that way for me. Instead of waiting 0.5 seconds, it is sending the values every 0.5 seconds, even as i continuously type. Here's my code:
```
textField.rac_textSignal()
.toSignalProducer()
.map { $0 as! String }
.throttle(0.5, onScheduler: QueueScheduler.mainQueueScheduler)
.startWithNext { text in
   print("throttled text: \(text)") }
```

Did `throttle` get changed at some point? If not, does anybody know what I'm doing wrong? Thanks!

**Comment by mdiep** [comment]
Unfortunately, that's an error in the documentation in the RAC README.

RAC 2's `throttle` behaved like that. However, that operator should actually be called `debounce`. When the README was updated, it probably was mistranslated to Swift. Would you be interested in opening a PR to fix the documentation in the README?

There is an issue open to implement debounce (#2075), but it hasn't been implemented.
