### ISSUE TITLE
Reactive cocoa 4.+ how to use Action and CocoaAction

### ISSUE THREAD

**Issue by pcwang0205** [ReactiveCocoa/ReactiveCocoa#2894]
I use it like this, but crash. why ?
 
       var clickButton: UIButton! = UIButton()
       clickButton.frame = CGRectMake(100, 100, 50, 50)
       clickButton.backgroundColor = UIColor.redColor()
       self.view.addSubview(clickButton)
        
       let a = Action<Bool, Void, NoError> { val in
            return SignalProducer { sink, _ in
                print("I has a value: \(val)")
                sink.sendCompleted()
            }
        }
        let cocoaAction = CocoaAction(a) { _ in
            return true
        }
        
        clickButton.addTarget(cocoaAction,
                              action: CocoaAction.selector,
                              forControlEvents: UIControlEvents.TouchUpInside)

**Comment by ikesyo** [comment]
It seems that the created `cocoaAction` is deallocated immediately. Holding a strong reference to the instance would fix it.

**Comment by pcwang0205** [comment]
@ikesyo thanks

**Comment by pradeepb28** [comment]
@pcwang0205 how did you fixed this one. I am having similar issue.

**Comment by andersio** [comment]
Retain the `CocoaAction`.

**Comment by pradeepb28** [comment]
@andersio so declaring cocoa action at class level will solve the problem?
