### ISSUE TITLE
Accessing Signals created by SignalProducers, outside of .startWithSignal

### ISSUE THREAD

**Issue by mfclarke** [ReactiveCocoa/ReactiveCocoa#2898]
I'm wondering if there's some way to access the Signal created by a SignalProducer, but outside the .startWithSignal method? Basically, I have a long running operation that I'm using a SignalProducer for. But this SignalProducer could be used by other parts of my app in different Signal chains, and what I want to avoid is kicking off this operation a second time.

In a trivial use case, I can simply hold onto the signal created by the startWithSignal and observeNext off that if it's still running (I nil it out on terminated). But when this SignalProducer is used in the middle of a different chain, I have a signal in the startWithSignal which is for that entire chain. What I'd like is the signal for just my long running operation SignalProducer.

What makes sense to me is having access to the signal created in the signal producer's .on(started: { }) method. That way I can keep a dictionary of signals up to date with what's running, and simply observeNext or wrap the existing signal in a signal producer.

Can anyone help?

**Comment by RuiAAPeres** [comment]
> But this SignalProducer could be used by other parts of my app in different Signal chains, and what I want to avoid is kicking off this operation a second time.

Have you considered using [`replayLazily`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/b007a029ad536a29cc1f2afb5a49ea30d4eea8a7/ReactiveCocoa/Swift/SignalProducer.swift#L1400#L1442)? 

> In a trivial use case, I can simply hold onto the signal created by the startWithSignal and observeNext off that if it's still running (I nil it out on terminated)

 👎 

> What I'd like is the signal for just my long running operation SignalProducer.

Why don't you use a `Signal` instead? Seems to me thats's what you want.

**Comment by mfclarke** [comment]
> Have you considered using replayLazily?

No but after reading the docs for it, it looks like the kind of thing I need. Thank you!

> Why don't you use a Signal instead? Seems to me thats's what you want.

I'll also check out using plain Signals for this again. I tried earlier but I have learnt a lot about ReactiveCocoa since then, so I might be able to implement it correctly now.

Thanks @RuiAAPeres!
