### ISSUE TITLE
Swift 2 RAC4 Merge UITextField Signal and UISwitch Signal

### ISSUE THREAD

**Issue by galfaroth** [ReactiveCocoa/ReactiveCocoa#2899]
Hello, I asked a question here and can't get it to work. Could anyone help me with merging two signals using Swift 2?

http://stackoverflow.com/questions/37174772/swift-2-rac4-merge-uitextfield-signal-and-uiswitch-signal

Thank you!

#help-wanted

**Comment by iv-mexx** [comment]
Hi, I've posted an answer to your question on stackoverflow. If that helps you please close this issue.

**Comment by galfaroth** [comment]
Thank you! It works like a charm!
