### ISSUE TITLE
Installing using Carthage, force use of iOS

### ISSUE THREAD

**Issue by szweier** [ReactiveCocoa/ReactiveCocoa#2907]
I'm installing RAC using Carthage and the compile phase seems to randomly use whatever type it wants.  Sometimes building tvOS sometimes watchOS and sometimes iOS.  The problem is I need it to always build iOS and when it picks these other ones I get compile issues, is there something I'm missing in the setup of either the Cartfile, or the linked frameworks that will force it to always use iOS target?

I am using `carthage update --platform iOS --use-submodules --no-use-binaries --no-build` for the update but it doesn't seem to stick to using iOS.

Thanks.

**Comment by joshbax** [comment]
`--platform` is ignored when `--no-build` is present. see `carthage help update`

**Comment by szweier** [comment]
Ah thanks, I'm seeing that the projects when added to my project still show frameworks for iOS, tvOS, watchOS and during compile it seems to still randomly select between which one to use.  Do you have any thoughts on that?  Seems like --no-build is what I would want to use when updating when using the framework in an app.

**Comment by joshbax** [comment]
I just use 'carthage update --platform iOS' omitting the '--no-build' option. You should not see the other targets in the /Build folder. You can wipe everything under /Carthage and run over to check

**Comment by mdiep** [comment]
Because you're including `ReactiveCocoa.xcodeproj` in your project, you're going to see a scheme for every platform.

I've had issues with projects building the wrong platform of RAC too. The solution has been to turn off find implicit dependencies for that scheme and explicitly list them.

**Comment by szweier** [comment]
@mdiep if the other dependencies are installed via cocoa pods I can't add them in the target dependencies build phase because they're not listed as options.  What would I do to handle that?
