### ISSUE TITLE
Action based UIButton takes a while to reenable

### ISSUE THREAD

**Issue by gbuela** [ReactiveCocoa/ReactiveCocoa#2913]
Hi, RAC newbie here.

I have this:

```
        fetchCocoaAction = CocoaAction(self.viewModel.fetchUsers, input: "")
        self.goButton.addTarget(fetchCocoaAction, action: CocoaAction.selector, forControlEvents: UIControlEvents.TouchUpInside)
        self.viewModel.fetchUsers.enabled.producer.startOn(UIScheduler()).startWithNext {
            self.goButton.enabled = $0 }
```

The action is set up to enable based on a validation on some field. The last line above effectively applies this enabled state to the button. When the action is executed (a network request) the button automatically disables itself which is nice, I guess RAC is handling that somehow? because I did nothing to get that... now when SignalProducer making the request completes, the UIButton takes a while to show as enabled again. Can you guys shed some light on this disable/enable mechanism going on under the hood and why the reenabling is not happening right after the action is done?

**Comment by mdiep** [comment]
> When the action is executed (a network request) the button automatically disables itself which is nice, I guess RAC is handling that somehow?

That's what your last line of code is doing:

```
self.viewModel.fetchUsers.enabled.producer.startOn(UIScheduler()).startWithNext {
            self.goButton.enabled = $0 }
```



> Can you guys shed some light on this disable/enable mechanism going on under the hood and why the reenabling is not happening right after the action is done?

That should be happening as soon as the execution your `self.viewModel.fetchUsers` `Action` completes.

**Comment by gbuela** [comment]
OK, so I added _print("enabled \($0)")_ to the startWithNext closure above, and I can clearly see that the action gets disabled when the execution starts and it gets reenabled when it completes. 

Now the button still remains disabled on screen long after completion. At first I thought this was called on a non-main thread but even with .startOn(UIScheduler()) the same thing happens. Any ideas on that?

**Comment by gbuela** [comment]
Oh, I got it. I should have used observeOn() rather than startOn().

Thanks
