### ISSUE TITLE
Playground instruction missing  carthage build

### ISSUE THREAD

**Issue by simonxcheng** [ReactiveCocoa/ReactiveCocoa#2916]
I found that I need to do carthage build in order to run the playground otherwise I got "no such module" for Result and ReactiveCocoa. Here is the command:
carthage build --verbose --platform OSX

After run this command the error sign is still there but the playground is fine.

**Comment by tomj** [comment]
hey @simonxcheng did you perform the following steps?:

```
	1.	Open ReactiveCocoa.xcworkspace
	2.	Build ReactiveCocoa-Mac scheme
	3.	Build Result-Mac scheme
	4.	Finally open the ReactiveCocoa.playground
	5.	Choose View > Show Debug Area
```

**Comment by simonxcheng** [comment]
Yes, I did every steps.

**Comment by dougbeal** [comment]
I ran into the same problem on an unbuilt checkout.  I think one of the following is easiest
```
scripts/bootstrap # OR
carthage checkout
```

**Comment by mdiep** [comment]
Would someone like to open a PR to add that to the list of steps?

**Comment by tomj** [comment]
I'll take care of it, I have a couple of commits cleaning up some typos etc
in the playgrounds which I'll add to it

**Comment by tomj** [comment]
This is a candidate for closing now that #2930 has been merged
