### ISSUE TITLE
Curated list of ReactiveCocoa projects

### ISSUE THREAD

**Issue by Palleas** [ReactiveCocoa/ReactiveCocoa#2919]
Hello!

I’ve been using ReactiveCocoa for a long time now but I’ve always struggled with finding examples from
real-world applications. Recently I was looking for an application using the MVVM design pattern to see 
how I could do things differently and I realized I was probably not the only one. That’s why I created “Racurated”, a list of curated open-source projects using ReactiveCocoa.

The page is available at http://racurated.github.io/ and shows only a few projects for now. I'll be adding more soon and people will be more than welcome to contribute with their own project. I wanted to see what you though about the idea before announcing it to the world (well, twitter). 

I have plans to improve the website a little with a search so people looking for an iOS app using the MVVM pattern can find that easily, but that’s for another day.

Please let me know what you think, hopefully this will help having more people embracing ReactiveCocoa!

**Comment by mdiep** [comment]
Very cool!

**Comment by RuiAAPeres** [comment]
@Palleas really cool! What do you think about merging it into the [RACCommunity](https://github.com/RACCommunity)?  It would work like this one [RxSwiftCommunity](https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io).

**Comment by Palleas** [comment]
I'm all for that! How can we do that? I guess I'll have to transfer ownership and be granted push access to the new repository so I can keep working on it?

**Comment by RuiAAPeres** [comment]
@Palleas I give you access and that's pretty much it. You can then transfer ownership and keep working on it. I did the same thing with [RACNest](https://github.com/RACCommunity/RACNest).

**Comment by Palleas** [comment]
@RuiAAPeres I transfered the ownership but I don't think I have push access to this repository :x

**Comment by RuiAAPeres** [comment]
@Palleas Can you give it a spin?

**Comment by Palleas** [comment]
It works now, thanks! I'll update it soon because the URL changed and the layout is broken now.

I'll move the discussion there now. 😄
