### ISSUE TITLE
RAC 4.+ how to use buffer

### ISSUE THREAD

**Issue by pcwang0205** [ReactiveCocoa/ReactiveCocoa#2927]
in RAC2.5, create signal like this，when the signal have subscribe, the block will execute

```
return [RACSignal createSignal:^(id<RACSubscriber> subscriber) {
                //do something here
		return nil;
	}];
```

but RAC4.+ 
I want to do something when the signal have subscribe. what should I do?
`let (signal, observer) = SignalProducer<JSON, NSError>.buffer(1)`

**Comment by andersio** [comment]
You can use the initialiser of `SignalProducer`.

```
let producer = SignalProducer { observer, disposable in
    /// Side effect at the time the producer was started.
}
```

**Comment by pcwang0205** [comment]
solve
