### ISSUE TITLE
Intermediate RAC release e.g. 4.2, before Swift 3.0?

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#2933]
Hi Team,

I'm curious about intermediate RAC release, before Swift 3.0. Since there're already some features that would be great to use, but there're not in release, e.g.
1. merge for SignalProducers
2. map for Properties

So it would be great to have some Swift 2.2 release.

Thanks!

**Comment by mdiep** [comment]
There will definitely be a release soon! I'd like to get #2912 tested and hopefully merged first. I'm hoping to get to that in the next week.

**Comment by larryonoff** [comment]
Thanks!
