### ISSUE TITLE
Is there a better way to realize network request and show the HUD

### ISSUE THREAD

**Issue by huanghe810229530** [ReactiveCocoa/ReactiveCocoa#2934]
override func viewDidLoad() {
        super.viewDidLoad()

        view.showLoading()
        viewModel.listSignal.startWithNext {[weak self] (list) in
            self?.tableView.items = list
        }
        
        viewModel.listSignal.startWithCompleted {
            self.view.hideLoading()
        }
    }

as above, Is there a better way to realize network request and show the HUD? help want!

**Comment by RuiAAPeres** [comment]
With that code, you are starting two requests. You can easily inject some side effects to handle the UI bits:

```swift
    viewModel.listSignal.on(
            next: {[weak self] list in
                self?.tableView.items = list
            }, 
            completed: {
                self.view.hideLoading()
           })
           .start()
```

**Comment by huanghe810229530** [comment]
@RuiAAPeres  Is a good solution. Thank you!
