### ISSUE TITLE
Project structure (files hierarchy) 

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#2937]
Hi Team,

I think this would be good approach for understanding, grouping project classes / structs and navigating the project.

One of the steps I see is to split Disposable.swift into the files below and place them into folder 'Disposables'.
- Disposable.swift with protocol declaration only
- SimpleDisposable.swift
- ActionDisposable.swift
- CompositeDisposable.swift
- ScopedDisposable.swift
- SerialDisposable.swift

If this suggestion works we can discuss other items.
I can do PR to split Disposable.swift

**Comment by RuiAAPeres** [comment]
I am not keen on this. 👎 I prefer, in this specific context of ReactiveCocoa, to have the Disposables in the same place, so it's easier to see them all. I would hate for us to have something like [this](https://github.com/ReactiveX/RxSwift/tree/master/RxSwift) (I find it to be a tremendously PITA to find stuff) .

**Comment by mdiep** [comment]
I think we should stick with the current structure for the time being. But we will be splitting things into Swift/Cocoa/Bridge soon.

**Comment by larryonoff** [comment]
@mdiep 
> But we will be splitting things into Swift/Cocoa/Bridge soon.

Do you mean RAC5?

**Comment by larryonoff** [comment]
@RuiAAPeres I still think that some split should happen. Maybe the approach that I suggested not the best on. But it's still hard to navigate via the implementation of concrete class / classes, especially if there're more and more functions / properties, e.g. see [Signal.swift](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/Signal.swift) has 1501 lines.

Swift core can be reviewed as an example of structure, see this [link](https://github.com/apple/swift/tree/master/stdlib/public/core).

**Comment by RuiAAPeres** [comment]
@larryonoff I agree with Signal, maybe try to group operators in categories: transformation, combining, filtering, like [this](http://rxmarbles.com/).

**Comment by larryonoff** [comment]
@RuiAAPeres I like the idea. Hope that it won't be difficult to group operators sometimes. Should I create PR for this?

What about moving support classes like `CollectState `, `CombineLatestState`, `SampleState` into separate private swift files?

**Comment by RuiAAPeres** [comment]
Let's just wait for what @mdiep said first, since we are about to shake things a bit #2807.

**Comment by larryonoff** [comment]
@RuiAAPeres could you please reopen this issue then.

**Comment by RuiAAPeres** [comment]
@larryonoff we are about to open a new repo for Swift only (which is privately right now). It would make sense to re-open this there.

**Comment by larryonoff** [comment]
@RuiAAPeres I understand. Thanks!

**Comment by mdiep** [comment]
> Do you mean RAC5?

Yes, but I also think we'll split up the files ahead of that to prepare.

**Comment by larryonoff** [comment]
@mdiep Thanks!
