### ISSUE TITLE
Initializing SignalProducer with Signal vs Block

### ISSUE THREAD

**Issue by dougbeal** [ReactiveCocoa/ReactiveCocoa#2940]
I was adding a example to the SignalProducer playground, and it didn't behave as I expected.  I thought there would be no difference between supplying the SignalProducer initializer with a signal instead of a block.  Instead it behaved exactly like the Signal case.  [Playground](https://github.com/dougbeal/ReactiveCocoa/tree/playground-signalproducer-init-signal)
# Expectation
 - observers would receive all results up that point
# Observation
- observers saw events from start call forward

```swift
scopedExample("Subscription with signal") {
    // Signal.pipe is a way to manually control a signal. the returned observer can be used to send values to the signal
    let (signal, observer) = Signal<Int, NoError>.pipe()
    let producer = SignalProducer<Int, NoError>(signal: signal)
    let subscriber1 = Observer<Int, NoError>(next: { print("Subscriber 1 received \($0)") } )
    let subscriber2 = Observer<Int, NoError>(next: { print("Subscriber 2 received \($0)") } )
    
   
    print("Subscriber 1 starts the producer")
    producer.start(subscriber1)
    
    print("Send value `10` on the signal")
    // subscriber1 will receive the value
    observer.sendNext(10)
    
    print("Subscriber 2 starts the producer")
    // Notice how nothing happens at this moment, i.e. subscriber2 does not receive the previously sent value
    producer.start(subscriber2)
    
    print("Send value `20` on the signal")
    // Notice that now, subscriber1 and subscriber2 will receive the value
    observer.sendNext(20)
    
}
```
 expected output (bold line is not in actual output)

--- Subscription with signal ---

Subscriber 1 starts the producer
Send value `10` on the signal
Subscriber 1 received 10
Subscriber 2 starts the producer
 **Subscriber 2 received 10**
Send value `20` on the signal
Subscriber 1 received 20
Subscriber 2 received 20

**Comment by mdiep** [comment]
Subscriber 2 shouldn't receive the first value because the producer wasn't started for that subscriber until after the value was sent. Why do you expect that in the output?

**Comment by dougbeal** [comment]
I thought it would buffer the events.  

Is there any difference between using the Signal directly vs SignalProducer in the simple subscription case?  

I see now that using a SignalProducer allows using replayLazily, which would get the behavior I wanted.

**Comment by mdiep** [comment]
> Is there any difference between using the Signal directly vs SignalProducer in the simple subscription case?

Not in this case. `Signal`s are shared, while `SignalProducer`s are per-observer. And `SignalProducer`s may do work when the subscription starts. But neither of those affects this case.
