### ISSUE TITLE
StartOn method behaves differently when playing with SignalProducer.buffer

### ISSUE THREAD

**Issue by craigzour** [ReactiveCocoa/ReactiveCocoa#2942]
```swift
let sut = SignalProducer<String, NoError>(value: "bla")

sut
  .startOn(UIScheduler())
  .startWithNext { value in
    print(value)
}
```
"print(value)" is properly dispatched on the Main thread queue

![main-thread-proof]
(http://i.imgur.com/hVvjLfq.png)

```swift
let sut = SignalProducer<String, NoError>.buffer(1)

sut.1.sendNext("bla")

sut.0
  .startOn(UIScheduler())
  .startWithNext { value in
    print(value)
}
```
"print(value)" is dispatched on a different queue

![]
(http://i.imgur.com/eYkCjuu.png)

====
Can you guys confirm if that is a bug or not ?

**Comment by mdiep** [comment]
`startOn` doesn't guarantee which scheduler the events will be delivered on—it only guarantees what thread a producer is started on. If you want to deliver on a specific scheduler, you can use `observeOn`.
