### ISSUE TITLE
Is possible to simplify this code? (UIButton rac_command)

### ISSUE THREAD

**Issue by krypt-lynx** [ReactiveCocoa/ReactiveCocoa#2945]
A have an UITableViewCell subclass with item property in it. Cells uses "dequeueReusableCellWithReuseIdentifier".

``` 
    self.uploadButton.rac_command = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
        return [[RACSignal return:@YES] doNext:^(id x) { // workaround for RACCommand <-> RACSubject issues? If I will return uploadAction directly - it will not work.
            @strongify(self);
            [self.item.uploadAction sendNext:self.item];
        }];
    }];
```

In project used ReactiveCocoa v2.4.7 (via CocoaPods)

**Comment by mdiep** [comment]
What is `self.item.uploadAction`?

> If I will return uploadAction directly - it will not work.

Can you share more detail about what this means?

You haven't given the detail necessary for us to help. ☺️
