### ISSUE TITLE
Avoiding explicit disposable management in a view controller

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveCocoa#2946]
I have a feed table view, which is one of a few different tabs in an iOS app. I'm trying to work out the cleanest way to express the following rules in RAC:
- When the feed appears, trigger a refresh.
- While the feed is on screen, observe when the data is refreshed and reload the table.
- When the user reaches the bottom of the feed, fetch the next page of data.
- When a new page is fetched, append it to the bottom of the feed.
- When an error occurs, show it to the user.
- When the user switches tabs, stop observing.

This is all fairly typical stuff. I created a `FeedController` which manages a couple of different `Action` properties, exposing various action methods and observable signals to the UI. Here's a snippet of what I ended up with:

``` swift
// called in viewWillAppear()
func observeFeedUpdates() {
  let observation = CompositeDisposable()
  observation += feedController.fetching.producer.filter(!).observeOn(UIScheduler()).startWithNext { [weak self] _ in
    self?.refreshControl?.endRefreshing()
  }
  observation += feedController.feedItems.signal.observeOn(UIScheduler()).observeNext { [weak self] _ in
    self?.reloadFromCache()
  }
  self.observation = observation
}

// called in viewWillDisappear()
func stopObservingUpdates() {
  observation?.dispose()
  observation = nil
}
```

I'll be honest, there's plenty I can do here to simplify this code. I can move the `.observeOn(UIScheduler())` stuff into `feedController` to ensure it happens automatically, I can combine both of these into a single observation, etc.

I don't like having to weakify my references here, because I know that I screw up this stuff all the time. I _loved_ how in RAC 2, if I was using bindings, that was just taken care for me. So I thought: **what if I could have a binding that just called a method every time a value was sent on a signal?** It would handle the weak reference thing, and I'd have a higher level way of wiring this stuff up. That was the motivation behind this PR: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2880

I have a version of that PR in my project at the moment. Here's how it's used:

``` swift
RAC(selectControl, "enabled") <~ controller.selectionEnabled
RAC(submitButton, "enabled") <~ controller.submissionEnabled

RAC(controller, MyController.submit) <~ selectionSubmitted
RAC(self, MyViewController.clearSelection) <~ controller.shouldClearSelection
RAC(self, MyViewController.showPollResults) <~ controller.alreadySubmitted.forEach(showAlreadyAnsweredAlert).take(1)
RAC(self, MyViewController.showPollResults) <~ controller.submitted.throttle(0.5, onScheduler: QueueScheduler.mainQueueScheduler).take(1)
RAC(self, UIViewController.show(error:)) <~ controller.unexpectedErrors
```

I like this because it's really high level. On the right hand, you have the events that should trigger an action. On the left, you have what should be done. All these bindings use weak references to ensure that they're torn down when the view controller goes away.

How do others solve this problem? Should I be using [Rex](https://github.com/neilpa/Rex)? I'd love some help with this!

**Comment by mdiep** [comment]
> Should I be using Rex?

Definitely. 😄 That would provide a better solution for binding the `enabled` state of `UIControl`s.

It's hard to discuss this without a complete code example. Here's a few thoughts:

* You might be interested in looking at `forwardWhileActive` from ReactiveViewModel. It's RAC2, but it's a potential solution for part of this.

* I think `UIRefreshControl` would ideally have a RAC extension that makes it easy to bind a boolean `SignalProducer`. (Also removing the need to call `beginRefreshing`)

* There's probably no benefit to disposing of the refresh control subscription when the view disappears.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
