### ISSUE TITLE
Internal signal not being disposed by flatMap operator on outter SignalProducer

### ISSUE THREAD

**Issue by guidomb** [ReactiveCocoa/ReactiveCocoa#2949]
I'm not sure if this is a bug or expected behavior but given my interpretation of the docs, in particular to the comments of the `observe` method

> Observes the Signal by sending any future events to the given observer. If the Signal has already terminated, the observer will immediately receive an `Interrupted` event.
> 
> Returns a Disposable which can be used to disconnect the observer. Disposing of the Disposable will have no effect on the Signal itself.

which says that the disposable returned by this method is used to remove the observer and given https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2453 and https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2582. I understand that if I have a producer of signal which is flattened and then the producer is disposed, it should also dispose the internal signal inside the closure provided to flatMap.

The following is an example that reproduces the issue that I describe in the title

``` swift
let signal = Signal<Int, NoError> { observer in

    func next(count: Int = 0) {
        let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(1 * Double(NSEC_PER_SEC)))
        dispatch_after(delayTime, dispatch_get_main_queue()) {
                observer.sendNext(count)
                next(count + 1)
        }
    }

    next()

    return nil
}

let action = Action { (_: AnyObject) -> SignalProducer<(), NSError> in
    return SignalProducer { observer, _ in
        let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(2 * Double(NSEC_PER_SEC)))
        dispatch_after(delayTime, dispatch_get_main_queue()) {
            observer.sendNext(())
            observer.sendCompleted()
        }
    }
    .on(
        terminated: { print("action producer terminated") },
        disposed: { print("action producer disposed") },
        interrupted: { print("action producer interrupted") }
    )
}
let result = action.executing.producer
    .filter { $0 }
    .flatMap(.Latest) { executing -> Signal<[Int], NoError> in
        print("action executed")
        return signal
            .scan(Array<Int>()) { acum, current in
                print("Accumulating")
                var newAccum = acum
                newAccum.append(current)
                return newAccum
            }
            .on(
                terminated: { print("scan signal terminated") },
                disposed: { print("scan signal disposed") },
                interrupted: { print("scan signal interrupted") }
            )
    }
    .on(
        terminated: { print("result producer terminated") },
        disposed: { print("result producer disposed") },
        interrupted: { print("result producer interrupted") }
    )

let disposable = result.startWithNext { print($0) }

action.apply("").start()

let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(12 * Double(NSEC_PER_SEC)))
dispatch_after(delayTime, dispatch_get_main_queue()) {
    print("disposing")
    disposable.dispose()
}
```

and the output generated is 

```
action executed
Accumulating
[0]
action producer terminated
action producer disposed
Accumulating
[0, 1]
Accumulating
[0, 1, 2]
Accumulating
[0, 1, 2, 3]
Accumulating
[0, 1, 2, 3, 4]
Accumulating
[0, 1, 2, 3, 4, 5]
Accumulating
[0, 1, 2, 3, 4, 5, 6]
Accumulating
[0, 1, 2, 3, 4, 5, 6, 7]
Accumulating
[0, 1, 2, 3, 4, 5, 6, 7, 8]
Accumulating
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Accumulating
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
disposing
result producer interrupted
result producer terminated
result producer disposed
Accumulating
Accumulating
Accumulating
Accumulating
Accumulating
```

I would expect the internal signal to be terminated when the disposable is executed. What is happening is that the signal returned by applying the `scan` method is not being disposed and its observer is kept alive and that is why the `Accumulating` message keeps appearing after the `result` producer has been terminated.

I know that the signal is an infinite signal (a completed event is never sent inside the infinite loop that send a value every one second) that I think that the observer should be remove when the outer producer has been disposed.

Thanks!

**Comment by mdiep** [comment]
`Signal`s don't terminate when you dispose of the observation. But I would expect to see `scan signal disposed` in the output.

**Comment by guidomb** [comment]
@mdiep I understand that the signal will continue to emit values no matter what but I would expect the signal derived from the `scan` method to stop accumulating values in the array or am I incorrect?

**Comment by guidomb** [comment]
I guess I answered my own question with the following example

```swift
final class Timer: NSObject {
        
    var observer: Observer<Int, NoError>? = .None
    var counter = 0
    var timer: NSTimer? = .None

    init(observer: Observer<Int, NoError>) {
        self.observer = observer
    }

    @objc
    func tick(timer: NSTimer) {
        print("Timer tick")
        counter += 1
        observer?.sendNext(counter)
    }

    func fire() {
        timer = NSTimer.scheduledTimerWithTimeInterval(
            1.0,
            target: self,
            selector: #selector(tick),
            userInfo: nil,
            repeats: true
        )
        timer?.fire()
    }
    
    func termiante() {
        timer?.invalidate()
        timer = .None
        observer = .None
    }
    
}

let signal = Signal<Int, NoError> { observer in
    let timer = Timer(observer: observer)
    timer.fire()
    return ActionDisposable { timer.termiante() }
}

let d1 = signal
  .scan(Array<Int>()) { acum, current in
      print("Accumulating")
      var newAccum = acum
      newAccum.append(current)
      return newAccum
  }
  .on(
      terminated: { print("signal terminated") },
      disposed: { print("signal disposed") },
      interrupted: { print("signal interrupted") }
  )
  .observeNext { print("d1 -> \($0)") }

let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(5 * Double(NSEC_PER_SEC)))
dispatch_after(delayTime, dispatch_get_main_queue()) {
  print("disposing")
  d1!.dispose()
}
```

I know that this is not how one should use signal but this is just for the sake of understanding what happens when you derive new signals.

I always thought that when you derived a new signal using any operator, like `scan`, the original signal was being observed and the the resulting signal was disposed the observation to the original signal would be terminated. If this the expected behavior, Why is it done this way?

**Comment by mdiep** [comment]
> I understand that the signal will continue to emit values no matter what but I would expect the signal derived from the scan method to stop accumulating values in the array or am I incorrect?

Yeah, sorry. I specifically meant the signal that was returned from the `flatMap`.

> If this is the expected behavior, Why is it done this way? Why not removing all intermediate observers?

This was brought up [here](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2588#issuecomment-161566055). (I looked for that earlier, but forgot that it was in a PR, not an issue.)

**Comment by guidomb** [comment]
@mdiep Thanks for taking the time to look for that PR. I skimmed through the conversation (I will read it in more detail later). I write this issue because the particular problem that I was having was a memory leak (of a view model) caused by capturing it inside a filter operation in an intermediate signal (which now I understand this intermediate signal won't be terminated when the observed signal is).

My code looked something like this

```swift
disposable += intsMutableProperty <~ producer.flatMap(.Latest) { [unowned self] someValue in 
  getSignalForValue(someValue).filter { self.someFilter($0) }.scan([], combine: +)
}
```

where `someFilter` is a closure that is initialized when the object that holds this piece of code is created. I was getting a leak because this closure was initialized with some other view model's instance method which matched the type signature (that filter method actually depends on the internal state of the view model and that is why it cannot be a free function).

For what I seen in the PR you referenced, the discussion was about using pure functions in this method. My understanding of pure is that the function should not perform any side effects but I think a pure function can still access non-mutable state to compute a value. Which happens to be the case. The filter function that I am using is using the objects internal immutable state to decide if the current value passes the filter. If my understanding of pure functions is correct I think this is a valid case that is not violating the signal's contract (functions passed to `filter` or `map` must be pure, an invariant that cannot be assured by the type system). 

Again I have to read the full discussion to understand why this is the case but whether I agree or not with the design of how this works I thinks we (as a community) should do something about this. At least document it because this sort of bugs are really hard to track and almost impossible to fix by a person that is not experienced with the internals of the library. 

Just to make it clear I want to understand if I am misusing the library or this is a valid use case. In case I am misusing the library, What can be done to avoid this sort of issue for other users?

**Comment by guidomb** [comment]
@mdiep After reading the PR you mentioned and other PR mentioned in that one I tried doing

```swift
let d1 = SignalProducer(signal: signal)
  .scan(Array<Int>()) { acum, current in
      print("Accumulating")
      var newAccum = acum
      newAccum.append(current)
      return newAccum
  }
  .on(
      terminated: { print("signal terminated") },
      disposed: { print("signal disposed") },
      interrupted: { print("signal interrupted") }
  )
  .startWithNext { print("d1 -> \($0)") }
```

And the output was the one I expected.

This could be a "solution" (even though I still think that intermediate signals / observers should be terminated with the external signal is disposed). What makes me wonder is why this is not what `SignalProducer`'s `flatMap` does in the overload version that receives a `Signal` as a parameter?

**Comment by mdiep** [comment]
> If my understanding of pure functions is correct I think this is a valid case that is not violating the signal's contract (functions passed to filter or map must be pure, an invariant that cannot be assured by the type system).

I think the reluctance was based on the fact that the type system can't guarantee that `filter` or `map` is pure.

> What makes me wonder is why this is not what SignalProducer's flatMap does in the overload version that receives a Signal as a parameter?

Because here you've used `SignalProducer.scan` instead of `Signal.scan`.

You should almost always use a `SignalProducer`.

To be clear: I'm not saying that we shouldn't change the behavior of `Signal`. I'm only trying to describe how it currently works and what I understand of the rationale.

**Comment by guidomb** [comment]
I think that at least this corner cases should be stated in the documentation with clear examples, not an ideal though because for me this was quite counter intuitive and people (me included) don't pay to much attention to documentation.

What I am trying to say is that ReactiveCocoa makes you to forget about memory management because for 90% of the cases things just work. That is why I think this is a problem that is hard to track and I am think I'm not only one. At least several of my co-workers made similar mistakes in their code. 

I've found that there was a proposal to change the `Signal` contract [here](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2591) but that PR was closed. Do you know why?

**Comment by andersio** [comment]
@guidomb It was closed because @jspahrsummers said:
> Since signals are expected to evaluate side effects regardless of whether anyone is listening, they must stay alive until termination to preserve the semantics. This is, as @neilpa says, by design.
> 
> I don't mind if it gets changed, but that was the rationale so far.

The obvious solution is like what @mdiep said: use SignalProducer everywhere unless you have a specific use case. I agree that we need to discourage the use of `Signal` for new users though.

**Comment by guidomb** [comment]
Personally I don't agree with what @jspahrsummers said. I think that the framework should not favor the use of side effects in `Signal` but I am probably lacking more information in the subject to make a strong argument. I would said that if users have a strong case for side effects when there are no observers of a signal they should probably use a different type or roll out their own solution. But that is my opinion.

If `SignalProducer` is the way to go I think the documentation should strongly emphasize this and show examples of valid and invalid use cases for `Signal`. @andersio If you should use `SignalProducer` everywhere, What do you think are valid specific use cases for `Signal`. Why `Action` uses `Signal` in `values` and `errors`? I know the difference between hot and cold but just wonder what's your opinion. 

For example in the case of `Property` you can get both `Signal` and `SignalProducer` out of them. At first you may think that hot observers would make more sense because the property can be mutated and therefore its value would change whether there is somebody observing it or not. On the other hand `SignalProducer` lets you get the current value of the property when you start it which is pretty handy. So why `Property` is exposing `Signal` and `SignalProducer` if `Signal` should be discouraged?

Are there any use cases that can be done with a `Signal` but not with a `SignalProducer`? Because if somebody needs to starts a chain of `Signal`s that perform side effects without anyone observing the result they could do it by starting a `SignalProducer` with a empty handler and keeping a strong reference to the returned disposable.

**Comment by mdiep** [comment]
I want to give this some thought. I'm tending to a few other things right now (like releasing RAC 4.2), so it may take a little time for me to get to it.

**Comment by guidomb** [comment]
@mdiep Sure and again thanks for your time! I think this shouldn't be taken little so the more people in the conversation and the more time we have to thing about it the better!

**Comment by andersio** [comment]
I haven’t given it a deep thought yet. But my own rule of thumb is that signals are mainly used as sources of values which have their lifetimes determined by their respective owners, while transformations with an observer-end lifetime should be done by signal producers due to the lifetime management.

**Comment by andersio** [comment]
@mbrandonw The main bullet point of `SignalProducer` is the deferral of signal creation to the time a subscription happens, or in other words "customise a signal for each observer". As a result, `SignalProducer` ultimately binds the lifetime of everything it produced to an instance of observer.

IMO it is not really about cold or hot, but simplifying the lifetime management - especially in the cases involving multiple signals. Specifically, you don't need a `takeUntil` on every signals, and a produced signal (tied to an observer) would clean up everything it produced at disposal.

**Comment by mbrandonw** [comment]
@andersio thanks for explaining that! i'm starting to see where everyone is coming from now.

I still think signals have the simplest semantics, and so would prefer for its lifetime management to be taken care of in a reasonable manner. However, clearly I need to think about this a bit more.

**Comment by guidomb** [comment]
My 2 cents on this is that I think that the framework should favor best practices. If we all agree that having side effects in functions like `filter`, `map`, `scan` is not "good" then I think the framework shouldn't do trade offs just in case somebody wants to use side effects where he/she shouldn't. On the other hand I know that someone may have a strong use case for side effects in which case he/she should use `SignalProducer` or the `on` method. I haven't came with a valid use case where I need side effects in a signal that has no observers but Swift is not a pure functional programming language and a lot of times Cocoa makes going for the pure functional approach really hard (and even sometimes impossible). But in those cases I think that probably you shouldn't use ReactiveCocoa.

**Comment by FranDepascuali** [comment]
I think that we are focusing on the problems that `Signal` brings, and the recommendation of using `SignalProducer` just sounds as "yeah, you should use it because you can dispose it".
 As I see it, it's like we are focusing on the implementation (and the problems regarding `Signal` lifetime) rather than on the contract that `Signal` and `SignalProducer` provide. 

@andersio ```Given that Signal is push-driven, IMO recommending SignalProducer is not really about cold or hot, but simplifying the lifetime management - especially in the cases involving multiple signals```

`Signal` or `SignalProducer` should be really about cold or hot! That is why we have them as two separate entities, that is the main difference between RAC and other FRP frameworks like `RxSwift`.
That's the value that `ReactiveCocoa` provides.
Regarding properties
```For example in the case of Property you can get both Signal and SignalProducer out of them. At first you may think that hot observers would make more sense because the property can be mutated and therefore its value would change whether there is somebody observing it or not```
I find that this correct. The way I see it, the stream of values from a property should be a signal. I mean, the property itself is independent from wether someone is observing it or not (hot); it emits values, and all observers should share the same stream. 

I mean, the problem that @guidomb states is real and it's currently happening to us in a project: the solution seems to be "use `SignalProducer` instead", but no focusing on why we should do it.

**Comment by andersio** [comment]
@FranDepascuali 
> Signal or SignalProducer should be really about cold or hot! That is why we have them as two separate entities, that is the main difference between RAC and other FRP frameworks like RxSwift.
That's the value that ReactiveCocoa provides.

Sorry to have confused you - I meant to say *"in the case of recommending SignalProducer over Signal for the public facing API, it is not about cold or hot"*. I certainly agree the separation is what makes RAC shine.

> I find that this correct. The way I see it, the stream of values from a property should be a signal.

It is now. Not sure if it has been part of a release already though. :)

> I mean, the property itself is independent from wether someone is observing it or not (hot); it emits values, and all observers should share the same stream.

The producer now produces a signal by acquiring the recursive lock, emitting the current value and finally attaching this signal to the `Property`'s signal.

**Comment by andersio** [comment]
@guidomb I do share your view as I couldn't justify such use back in the time #2591 and its related issues were discussed. But it was preferred not to change it due to backward compatibility for those specific use case.

As 5.0 would break a lot of things anyway, should we also take the chance to re-evaluate the `Signal` semantics?

**Comment by mdiep** [comment]
It seems like it'd make things simpler if `Signal`s continued to work only while (a) retained or (b) observed. In cases where a `Signal` goes out of scope and isn't observed, or is observed but later disposed, the `Signal` should deallocate. That would eliminate a lot of confusion.

Does that sound right?

**Comment by andersio** [comment]
@mdiep Yes. This is what was proposed in #2591.

> When Signal has been deallocated:
> It means the signal will have no new observer in the future. So if the signal has no observer at the same moment, the signal can be safely terminated even without a terminating event.
> 
> When an observer detaches itself from a signal:
> If the resulting number of observers is zero, and if the respective Signal instance was deallocated already, the signal can be safely terminated without a terminating event.

**Comment by mdiep** [comment]
Yeah, I'd be 👍 on something like that for RAC5. (A PR could target that branch today.)

I'd probably take the approach of retaining the `Signal` in the `Disposable`, which is a little different than the approach in #2591.

**Comment by andersio** [comment]
@mdiep If we need to know whether a signal is gone out of scope, `Signal` can only be retained by the external world.

**Comment by andersio** [comment]
@mdiep `Signal` cannot be retained IMO, since we need it as a clue of the possibility of future subscriptions. Moreover, if you are talking about the returned disposable from `observe`, it can be deinitialised while the corresponding observer is still present.

**Comment by andymatuschak** [comment]
(I got surprised by this, too; c.f. #3075)

**Comment by mdiep** [comment]
Changes were made to this.
