### ISSUE TITLE
memory  leak ??

### ISSUE THREAD

**Issue by DepaJun** [ReactiveCocoa/ReactiveCocoa#2950]
[[Button rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(id x) {}}];

when  ViewController dealloc , I  log  the signal which's  created by this way ,  but  it doesn't be dealloced??  how  can  I release the signal??

**Comment by mdiep** [comment]
You haven't given enough detail for us to help you. You probably have a retain cycle in your code. If you provide a complete, self-contained example, we can try to help you find it.

**Comment by RiuHDuo** [comment]
use  weak var  weakSelf = self 
[[Button rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(id x) {weakSelf.xxx()}}];

**Comment by mdiep** [comment]
That signal should complete once `Button` is deallocated. Has `Button` deallocated?

**Comment by DepaJun** [comment]
sorry, I have found the bug,cause in the block, I have a retain cycle in my code,thanks for your guys answer!!
