### ISSUE TITLE
4.2 Release 

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveCocoa#2953]
I'd like to go ahead and release 4.2. Any objections? @ReactiveCocoa/ReactiveCocoa

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.2.0

**Comment by rpowelll** [comment]
Can someone with the correct access rights attach a prebuilt framework binary to the release for Carthage users?

**Comment by mdiep** [comment]
I just did. 👍

(It takes some time to compile after creating the release. 😉)

**Comment by rpowelll** [comment]
Thanks! I wasn't sure if that was automated or somebody did it manually.
