### ISSUE TITLE
Add flatten variants that operate on SequenceTypes

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveCocoa#2956]
This would help with otherwise ambiguous uses of `flatMap` like [this](https://github.com/Carthage/Carthage/pull/1329/files#r65486309).

You should be able to write something like this:

```swift
SignalProducer<[Int], NoError>(value: [1, 2, 3]).flatten(.Concat)
```

**Comment by joedaniels29** [comment]
Wouldn't that code sample be identical to: 
```swift
SignalProducer<[Int], NoError>(values:  [1, 2, 3])
``` 
why both? for more complex cases? if so why not just a flatMap operator? 

```swift
someSequenceTypeValuedSignalProducer.flatMap(.Concat) { .init(values: $0) }
``` 

The flatten/flatmap operator has always been operating on the Signal itself, wouldn't it be a serious increase in complexity to add such an operator?

**Comment by mdiep** [comment]
> Wouldn't that code sample be identical to:

Yes, it would. It was meant to illustrate the behavior, not the utility.

> if so why not just a flatMap operator?

This is a relatively common operation (it's the inverse of `collect()`), and adding a `flatten` variant that flattens Signals-of-Collections isn't unlike the `flatMap` variants in the Swift standard library.

Using `flatMap` works, but is unnecessarily verbose—especially once you've added the type annotations necessary to disambiguate the use of `flatMap`.
