### ISSUE TITLE
Different Int values delivered for same Signal

### ISSUE THREAD

**Issue by nickvelloff** [ReactiveCocoa/ReactiveCocoa#2958]
I'm new to this, so I know this is something dumb I'm doing...

In my view model I have 
``` Swift
private let _currentSiteHash: MutableProperty<Int>
let currentSiteHash: AnyProperty<Int>

init() {
        _currentSiteHash = MutableProperty<Int>(0)
        currentSiteHash = AnyProperty(_currentSiteHash)
        super.init()
        currentSiteHash.signal
            .observeNext { anInt in
                print("TheViewModel currentSiteHash.signal.observeNext \(anInt)") // WORKS PERFECTLY
            }
}

// then later after some data loads I set the value once
self._currentSiteHash.value = 123

```
But in my view controller I observe the signal

``` Swift
init() {
     super.init(node: _cvView)
     _viewModel.currentSiteStateHash.signal
            .observeNext { anInt in
                print("TheViewController currentSiteHash.signal.observeNext \(anInt)")
            }
}
```

The output is:
TheViewController currentSiteHash.signal.observeNext `-4799450060423276786`
TheViewModel currentSiteHash.signal.observeNext `123`

No idea what I'm doing wrong here. Any suggestions? This value does need to be retained (not a "hot" signal) which I think means ephemeral in nature if I understand correctly ... this is a "cold" signal.

**Comment by mdiep** [comment]
What is `_viewModel.currentSiteStateHash`? It has a slightly different name than the property in your code sample here. Is that a typo?

> TheViewController currentSiteHash.signal.observeNext `-4799450060423276786`
> TheViewModel currentSiteHash.signal.observeNext `123`

That looks like a signed/unsigned integers conversion bug. 😕

**Comment by nickvelloff** [comment]
@mdiep Oh no. Feel a little embarrassed... that's another Signal. 😱
Really been staring at this too long. Sorry for the misfire. No bugs (at least on your end).
