### ISSUE TITLE
RAC4 KVO for AVPlayer

### ISSUE THREAD

**Issue by tomj** [ReactiveCocoa/ReactiveCocoa#2965]
(via @chrishulbert)

AVPlayer uses KVO - would there be a low friction way to wrap this up with RAC4?

Cheers 😀

**Comment by mdiep** [comment]
`DynamicProperty` is the best way to do this with RAC4. 😄

**Comment by tomj** [comment]
Superb - thanks for the rapid response @mdiep 😊
