### ISSUE TITLE
bind to observed property

### ISSUE THREAD

**Issue by tcurdt** [ReactiveCocoa/ReactiveCocoa#2967]
From the docs it's not clear to me how bring this pattern best from ObjC into the Swift world with RAC4

    RAC(self.pagingControl, currentPage) = RACObserve(self.pagingView, index);

The only thing I could come up with is

    let index = MutableProperty(0)
    ...
    self.pagingView?.index.producer.startWithNext({ (newIndex) in
        self.pageControl?.currentPage = newIndex
    })

...but that's pretty verbose compared - and the boxing of the value quite ugly. I guess I could add this:

    var _index: Int {
        get {
            return index.value
        }
        set {
            index.value = newValue
        }
    }

but I am not sure that that's nicer or worse - certainly not quite the KVO elegance.
Any suggestions?

(also asked at http://stackoverflow.com/questions/37676994/observing-and-assigning-properties/37677228)

**Comment by mdiep** [comment]
The response on SO is correct: You'd use properties and `<~` to bind them.

Ideally, there would be an extension on `UIPageControl` that adds a `MutableProperty` for `currentPage` like [Rex](https://github.com/neilpa/Rex) does for many `UIControl`s.

**Comment by tcurdt** [comment]
@mdiep so it should like this in the end?

    self.pagingControl?.currentPage <~ self.pagingView?.index

**Comment by mdiep** [comment]
Yup!

**Comment by tcurdt** [comment]
@mdiep Hm, but when I try that (with a patched Rex)

    self.pageControl?.rex_currentPage <~ self.pagingView?.index

I get

> Binary operator '`<~`' cannot be applied to two '`MutableProperty<Int>?`' operands.

**Comment by tcurdt** [comment]
Odd - this compiles:

        let mutableProperty1 = MutableProperty(0)
        let mutableProperty2 = MutableProperty(0)

        mutableProperty1 <~ mutableProperty2

but this doesn't

    extension UIPageControl {
        public var rex_currentPage: MutableProperty<Int> {
            return associatedProperty(self, key: &currentPageKey, initial: { $0.currentPage }, setter: { $0.currentPage = $1 })
        }
    }
    private var currentPageKey: UInt8 = 0


    let mutableProperty1 = MutableProperty(0)
    self.pageControl?.rex_currentPage <~ mutableProperty1

What am I missing?

**Comment by mdiep** [comment]
It's because your `pageControl` is an `Optional.`.

```swift
if let pageControl = self.pageControl {
  pageControl.rex_currentPage <~ mutableProperty1
}
```

**Comment by tcurdt** [comment]
@mdiep OK - that I didn't decode from the error message. Sneaky!
Thanks!

**Comment by iv-mexx** [comment]
Maybe you could open a PR to add your UIPageControl-Extension to [Rex](https://github.com/neilpa/Rex)

**Comment by tcurdt** [comment]
Added! https://github.com/RACCommunity/Rex/pull/148
