### ISSUE TITLE
[Request] CocoaPods Podspec for ReactiveCocoa 4.2

### ISSUE THREAD

**Issue by minuscorp** [ReactiveCocoa/ReactiveCocoa#2968]
As the title says, I kindly request the update of the Podspec regarding the ReactiveCocoa 4.2 version published days ago.

Thank you.

**Comment by mdiep** [comment]
@ashfurrow has been maintaining the RAC podspec, but I'm not sure if he plans to continue doing so.

Other than that, I know nothing about the podspec.

**Comment by ashfurrow** [comment]
I'm helping maintain it, there's a group of us but we could always use some help. The podspec is on [this repo](https://github.com/mhuusko5/Podspecs), you can also open an issue requesting a new version. It might be worth linking to this from the readme.

**Comment by minuscorp** [comment]
I've opened an issue on the repo you mentioned. It was always surprising to me that the repo didn't maintain the podspec inside it!

**Comment by ashfurrow** [comment]
Agreed, thanks for opening the issue! I'm going to close this one so we can follow-up there.
