### ISSUE TITLE
Cannot convert value of type 'Action<Void, Void, NSError>?' to expected argument type 'Action<_, _, _>'

### ISSUE THREAD

**Issue by KiranPanesar** [ReactiveCocoa/ReactiveCocoa#2971]
I've worked with RAC 2.X extensively in the past, and have recently picked up RAC 4 for a side project.

I am trying to bind a `UIButton`'s tap event to perform an action in my View Model. As per the docs, I am using an `Action` and `CocoaAction` to do this like so:

```swift
let cocoaAction = CocoaAction(viewModel?.submitOrderAction, input: Void) 
self.nextButton.addTarget(cocoaAction, action: cocoaAction.selector, forControlEvents: UIControlEvents.TouchUpInside)
```
I am getting the following compiler error on the first line:
```
Cannot convert value of type 'Action<Void, Void, NSError>?' to expected argument type 'Action<_, _, _>
```
The ViewModel is defined as a protocol, and the action is defined like so:
```swift
var submitOrderAction: Action<Void, Void, NSError> { get }
```

Could someone explain what I'm doing wrong here? As I mentioned, I'm familiar with RAC 2.X and have used `RACCommand`s for this type of thing in the past, so would be extra appreciative if someone could compare `RACCommand` with `Action` in their explanation. Thanks! 👍

**Comment by mdiep** [comment]
> ```
> Cannot convert value of type 'Action<Void, Void, NSError>?' to expected argument type 'Action<_, _, _>
> ```

The issue is that pesky `?`. Very subtle in an error. But you'll need to `map` over the `Optional`.

Feel free to comment/reopen if you have any followup questions. ☺️
