### ISSUE TITLE
`Atomic.modify` and inout

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#2974]
`modify` does not take advantage of `inout` parameters with compiler optimizations. I wonder if there was a reason for such design choice, hmm? Using `inout` can avoid the need of shadowing the parameter and returning the mutated value.

**Comment by mdiep** [comment]
I'm not sure why `inout` wasn't used. It seems like a good fit. Is `inout` still a thing in Swift 3?

**Comment by andersio** [comment]
@mdiep Yes, absolutely. It has been further constrained to non-escaping contexts for safety too.

**Comment by ikesyo** [comment]
Closed by #2984.
