### ISSUE TITLE
Use Xcode Markup for RAC5 source code documentation

### ISSUE THREAD

**Issue by tomj** [ReactiveCocoa/ReactiveCocoa#2982]
Following on from the suggestion by @andersio in #2923 it would be great to have [Xcode markup](https://developer.apple.com/library/ios/documentation/Xcode/Reference/xcode_markup_formatting_ref/MarkupFunctionality.html#//apple_ref/doc/uid/TP40016497-CH54-SW1) for the RAC5 source code.

**Comment by mdiep** [comment]
:+1: 

But I think we should use [`- parameters:`](https://developer.apple.com/library/ios/documentation/Xcode/Reference/xcode_markup_formatting_ref/Parameters.html#//apple_ref/doc/uid/TP40016497-CH24-SW1) instead of `- parameter`.

This could be done on`master`; it doesn't need to be done on the RAC 5 branch.

**Comment by eimantas** [comment]
I'd like to give it a go.

**Comment by tomj** [comment]
@mdiep no problemo.  I was thinking at a minimum `- parameters:` and we could also do some other stuff like `- complexity`, `- warning` and `- important` if time permits.

@eimantas happy to help out too.  Do you want to compare notes on a couple of small commits on a public branch?  I'm happy to add you as a contributor to my fork if you want to collaborate.

**Comment by eimantas** [comment]
@tomj sure. I did a small experiment on `Event.swift` file. I'd be glad to create PR to your fork.

**Comment by tomj** [comment]
@eimantas nice!

for anyone else checking this one out, @eimantas and I are taking a look at this on a [PR on my fork](https://github.com/tomj/ReactiveCocoa/pull/1) before making a PR to the main repo.

**Comment by mdiep** [comment]
This was done in #2995! 🎉
