### ISSUE TITLE
don't work Action after update from 4.1 to 4.2

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#2983]
For example I have code like this

``` Swift
import UIKit
import ReactiveCocoa

class ViewController: UIViewController {

    @IBOutlet weak var button: UIButton!
    var action: Action<AnyObject, Void, NSError>!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        action = Action<AnyObject, Void, NSError> { _ -> SignalProducer<Void, NSError> in
            return SignalProducer<Void, NSError> { observer, _ in
                print("click on button")
                observer.sendCompleted()
            }
        }
        button.addTarget(action.unsafeCocoaAction, action: CocoaAction.selector, forControlEvents: .TouchUpInside)
    }
}

```

It worked on 4.1 version but don't work in 4.2

**Comment by mdiep** [comment]
This is because of the change in #2910.

**Comment by mdiep** [comment]
Would it be better to change the direction on this? So that `CocoaAction` had a weak reference to the `Action` and `Action` had a strong reference to the `CocoaAction`?

It seems a little weird, but that would enable the pattern above. It just means that you'd need to always hold on to the base Action.

**Comment by aehlke** [comment]
What's the best practice here now? We must keep a strong reference to the `unsafeCocoaAction`?

**Comment by mdiep** [comment]
> We must keep a strong reference to the unsafeCocoaAction?

That's the status in 4.2, yes.
