### ISSUE TITLE
Document slack channel

### ISSUE THREAD

**Issue by dougbeal** [ReactiveCocoa/ReactiveCocoa#2986]
If you search the repo you get Issue #871, which states the channel is no longer open to everyone.  If the intent is to be a general community, it should probably appear in the ReadMe.  I could create a pull request, but what will the signup process be?

**Comment by RuiAAPeres** [comment]
Hey @dougbeal we can either:

1. Tell people to ask the account @reactivecocoa on Twitter to add him/her
2. Create a new slack group and make it publicly. 

I would personally prefer the 2. If @mdiep is cool with that, I will take care of it.

**Comment by mdiep** [comment]
I don't know. There are some perks to the slack instance we're on, but there would also be some perks to having one just for RAC.

Any opinions from @ReactiveCocoa/reactivecocoa?

**Comment by tomj** [comment]
Not sure if any of you guys have experience with Gitter but I find it can be pretty good for the "drop in" public style conversation which it sounds like you're looking for (ie: you don't want the chat room to be "too good" as then people will avoid filing issues etc here which is I agree is important for the project).  Doesn't involve much maintenance either as you can make it public so anyone can join/you don't have to worry about invites, and the [pricing page](https://billing.gitter.im/) shows that it _seems_ to be more free than Slack.  Just a thought 😄

**Comment by RuiAAPeres** [comment]
@tomj the argument in favour of Slack, is that a lot of people already use it for a lot of other things: work, personal, etc. Having a different communication channel, would make people less compelled to use it.

**Comment by tomj** [comment]
Understand.  I use Slack for a number of orgs right now and the idea of having _yet. another. tab._ which slows down the Slack app startup even more is something I'd avoid if I could 😄  Also I find the Gitter integration with GH pretty seamless, which really just makes it feel like a "live issues chat" for want of a better description.  Anyways, appreciate all the work you guys do (including stuff like this), just throwing it out there as a thought.

**Comment by dmcrodrigues** [comment]
Create a new slack group and making it public seems a good option to me 👍

I understand that could be some advantages with the current group but seems odd having multiple channels not entirely related with RAC or Reactive Extensions, _#swiftgit2_, _#mantle_, _#electron_, _#dont-talk-in-here_ (???), ...

I think having something dedicated to RAC can be more welcoming for newcomers and facilitate discoverability.

**Comment by mdiep** [comment]
I think that's fair. I'm 👍 on a new instance.

**Comment by erikprice** [comment]
Will the new Slack org have the perpetually searchable archive? If not, I'm 👎 .

**Comment by RuiAAPeres** [comment]
@erikprice no it won't. On the other hand, someone else is paying for us to be there, hence why we cannot have the channel publicly available. Imagine that 1/10 of RAC users would join the group, I would hate to be the guy who has to pay for that.

**Comment by dmcrodrigues** [comment]
It would be wonderful if Slack could adopt a similar model to GitHub and offer a plan without the limits of Free package, at least for well-known OSS projects. It might be worth to try?

**Comment by filblue** [comment]
Hey guys, can I get into the channel whichever it is today?

**Comment by mdiep** [comment]
There's now [an open slack](https://reactiveswift.slack.com). Sign up here: https://reactiveswift.herokuapp.com

(This is documented in the ReactiveSwift README)
