### ISSUE TITLE
the time of reactivecocoa swift-3 release?

### ISSUE THREAD

**Issue by RiuHDuo** [ReactiveCocoa/ReactiveCocoa#2988]
how to transfer my code to swift - 3 with reactivecocoa?

**Comment by andersio** [comment]
That won't formally happen before Nimble, Quick and Result have a preliminary branch for Swift 3. So you have to manually convert the codebase if you want to use ReactiveSwift now.

**Comment by mdiep** [comment]
Yes. This will be a priority for us over the next several months. We should have support by the time that Xcode 8 is released.
