### ISSUE TITLE
Rename ignoreNil to skipNil?

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveCocoa#2990]
I was thinking about some RAC operators yesterday and realized that we use both `ignore` and `skip` to skip events. These do the same-ish thing, so they should probably use the same name. `ignoreNil` does change the type of `Value`, but I'd prefer to think of that as type-refinement.

Likewise, if we add `ignoreErrors`, it should probably be called `skipErrors`.

**Comment by andersio** [comment]
What about following the collection types? They use `drop` instead of `skip`. 💭

**Comment by eimantas** [comment]
skip implies that there is something that will be passed after it skips something (like `skip(5)`). While `ignoreNil` states that will never pass anything of `nil` value. And maybe verb `ignore` better conveys the type-refinement intention since skipping 5 `int`s will let the 6th `int` pass.

**Comment by mdiep** [comment]
> How about following the collection types? We may rename the `ignore*` and `skip[*]` operators to `drop*` and that looks like the `Sequence` methods.

I don't really want to follow the collection types here. I think `skip*` is a better name than `drop*`. And `take` is infinitely better than `prefix`, which is what the Swift stdlib uses. But I think `drop` also works in a narrower set of circumstances. `drop(value: 5)` reads a little weird to me, for instance.

It's much more important to me that the follow the general guidelines than that we follow the specific names.

> skip implies that there is something that will be passed after it skips something (like skip(5)). While ignoreNil states that will never pass anything of nil value. And maybe verb ignore better conveys the type-refinement intention since skipping 5 ints will let the 6th int pass.

I don't follow. That's the behavior of `skip(5)` because that's the semantics of skipping _n_ values. I can easily imagine a `skip(value: 5)` operator that skips all `5`s (because RAC2 had this operator but called it `ignore:`). Whichever name we chose, there will be different variants that behave differently.

**Comment by mdiep** [comment]
> But I think drop also works in a narrower set of circumstances. drop(value: 5) reads a little weird to me, for instance.

Thinking about this more, `drop` seems to generally apply to removing elements from either the beginning or end of a sequence. In that sense, it's the opposite of `take`.

`skipNil`, etc. are more generic in that they remove elements wherever they occur. `skip*` is then the opposite of `filter`, which is a more generic version of `take`.

**Comment by andersio** [comment]
Do you think we need to be more specific though? Say `takeFirst(3)` and `skipFirst(3)` instead of just `take(3)` and `skip(3)` to avoid ambiguity at call site.

**Comment by eimantas** [comment]
> I don't follow. That's the behavior of skip(5) because that's the semantics of skipping n values. I can easily imagine a skip(value: 5) operator that skips all 5s (because RAC2 had this operator but called it ignore:).

That's what I mean. The skip implies that there still will be values passed by the signal regardless of their type while `ignoreNil` will not let any `nil` values through, but let by other type of values.
