### ISSUE TITLE
Call for a basic guide

### ISSUE THREAD

**Issue by mirrorinf** [ReactiveCocoa/ReactiveCocoa#2994]
As nearly all tutorials and other materials are in objective-c, and the objc fashion is now unusable in swift. For example, swift compiler complains a lot about `AnyObject!`. All things cannot be used any longer, like the tutorial on RayWenderlich.com which uses signals. Is anyone to write a basic guide to beginners?

**Comment by tomj** [comment]
Hey @mirrorinf - the Playgrounds are a great place to start.  They're really easy to onboard with, and all in Swift 😄

**Comment by RuiAAPeres** [comment]
@mirrorinf you can find a lot of work done at [RACNest](https://github.com/RACCommunity/RACNest).
