### ISSUE TITLE
Official CocoaPods support

### ISSUE THREAD

**Issue by dmcrodrigues** [ReactiveCocoa/ReactiveCocoa#3000]
I'm aware about the preference for Carthage over CocoaPods, personally I fit myself in that group, but seems unreasonable not having any official support for CocoaPods which is broadly used by many developers and many projects.

The last release of ReactiveCocoa, 4.2.0, introduces not only some important fixes but also new additions and yet the last version available on CocoaPods is the previous one, 4.1.0. Right now, people are depending on the goodwill of volunteers.

I know that it will require some effort to support a new dependency manager like CocoaPods but I think for a project like ReactiveCocoa it really should be done to facilitate adoption, integration and migration. I've mentioned this some time ago and I know there's some reluctancy around it but I really think the project is being affected by this limitation/restriction.

**Comment by RuiAAPeres** [comment]
I think we discussed this before in other threads and in the Slack room. I up for maintaining this if needed, so I think we should move forward with it. There are just too many people using CocoaPods and ReactiveCocoa, for us to not to take it seriously. 

cc @mdiep @NachoSoto

**Comment by mdiep** [comment]
I'm okay with adding this to the repo with official support. But we need to document what needs to be done to update the podspec as part of the release process.

**Comment by tunidev** [comment]
Please do that, I like Carthage but my project use some library which is available with CacoaPods and I don't want to mix CacoaPods with Carthage and I think it's the same situation for other developers

**Comment by ashfurrow** [comment]
Pretty cool! I should now have more time to help than I have the past few months, too. A group of us is currently maintaining the podspec at https://github.com/mhuusko5/Podspecs , but the 4.2.0 podspec isn't linting right now. I'm in email correspondence (moving to a GH issue) with someone keen to help address it. 

Moving the podspec into the ReactiveCocoa repo would be a great step towards making ReactiveCocoa even more accessible by developers in the community. Really excited to see where this leads!

**Comment by chrrasmussen** [comment]
As @ashfurrow mentioned, I have taken a look at the linting errors and posted my discoveries at https://github.com/mhuusko5/Podspecs/issues/9. The discoveries are based on the Podspec located in said repository.

**Comment by nikita-leonov** [comment]
@ashfurrow since 4.2.1 was released not so far ago, can someone release 4.2.2 too? Looks like a small effort that will pay a lot. There are not many active contributors left who still can release Podspecs ;(

**Comment by nikita-leonov** [comment]
@ashfurrow thanks for sharing podspec access right, 4.2.2 released.

**Comment by ashfurrow** [comment]
@nikita-leonov would you mind sending a pull request to the [community Podspecs repo](https://github.com/mhuusko5/Podspecs/) that updates the ReactiveCocoa podspec?

**Comment by nikita-leonov** [comment]
@ashfurrow I will do it today. I was not aware of this repo. Thanks.

**Comment by ashfurrow** [comment]
Soon we won't need a separate repo anymore :) We'll need to update the pod spec for the repo split, might make sense to add it to this repo then?

**Comment by mdiep** [comment]
That sounds great. Just please include instructions for updating it! Since I don't use CocoaPods personally, I'm not very familiar with pod specs.

**Comment by pixel4** [comment]
Curious about what happened to this thread.. I'm trying to use @ashfurrow podspec but it's not easy since it conflicts with an unofficial podspec that exists on `https://github.com/CocoaPods/Specs.git`. 

We really need this official support! Now that Xcode 8 is out and 5.0 (Swift 3.0) is around the corner it would be awesome to get this going. Any updates?

**Comment by andersio** [comment]
We have #3219 and #3252 pending.

**Comment by andersio** [comment]
@pixel4 Try https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3252. :)

**Comment by andersio** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/5.0.0-alpha.2
:tada:

**Comment by ikesyo** [comment]
> Please push the pod to trunk.

Done 🚀 

> $ pod trunk push
> 
> [!] Found podspec `ReactiveCocoa.podspec`
> Updating spec repo `master`
> Validating podspec
>  -> ReactiveCocoa (5.0.0-alpha.2)
> 
> Updating spec repo `master`
> 
> --------------------------------------------------------------------------------
>  🎉  Congrats
> 
>  🚀  ReactiveCocoa (5.0.0-alpha.2) successfully published
>  📅  October 23rd, 09:58
>  🌎  https://cocoapods.org/pods/ReactiveCocoa
>  👍  Tell your friends!
> --------------------------------------------------------------------------------
