### ISSUE TITLE
Successfully linted 4.2.0 podspec?

### ISSUE THREAD

**Issue by nickvelloff** [ReactiveCocoa/ReactiveCocoa#3003]
Does anyone know of a dependable 4.2.0 podspec?

**Comment by nickvelloff** [comment]
No love for CocoaPods apparently 😿. @NachoSoto

**Comment by cythb** [comment]
Please try this repo. `source 'https://github.com/cythb/Specs.git'`
Add this line on top your podfile.

**Comment by nickvelloff** [comment]
Thanks @cythb... worked great.
