### ISSUE TITLE
RAC Playground & Tutorial

### ISSUE THREAD

**Issue by FranDepascuali** [ReactiveCocoa/ReactiveCocoa#3006]
Hello! In iOS department at Wolox (where I work) we relay heavily on RAC. Frankly, it's great, we love this framework, and we really appreciate what you've done for us (one of our technical leaders, @guidomb has been actively contributing with some issues).

We found that learning RAC is a great barrier for the new iOS developers; we made everyone who entered iOS complete a form after their trainning and almost all of them stated that RAC was the most difficult part. 
I remember that (back on obj-c RAC) I also had lots of difficulties for understanding this completely new way of doing things.

I've been working on a tutorial written in swift playgrounds (with markdown) for RAC, which has explanations, examples and use-cases. I think it could be helpful for other people learning RAC. There are some screenshots on the project's README.

I would really appreciate if you could take a look at it, and obviously you can make any contribution. It is really difficult to write about a topic you know to someone who has never heard of it. Thank you very much and I hope that RAC continues growing!

link: https://github.com/FranDepascuali/RACPlayground

**Comment by RuiAAPeres** [comment]
This pretty cool @FranDepascuali !! Thanks! Do you think it's something that could live and be supported, by the existing members at [RACCommunity](https://github.com/RACCommunity)?

**Comment by peterlondon1** [comment]
I am very keen to use ReactiveCocoa and to use your Playground Tutorial - which looks like it is exactly what I've been looking for!

However, I am unable to use the Playground so far. I open "RACPlaygroundWorkspace.xcworkspace" per your instructions. It builds without errors. I then close "RACPlaygroundWorkspace.xcworkspace" and open the file "RACPlayground.playground", but when I get to the "Signals" page, I get an error on the "import Result" line with the following message in the log:

```
Playground execution failed: Signal.xcplaygroundpage:2:8: error: no such module 'Result'
import Result
       ^
Signal.xcplaygroundpage:3:8: error: no such module 'ReactiveCocoa'
import ReactiveCocoa
       ^
```
 
Any suggestions? I've searched for a solution, but nothing has worked so far. Xcode 7.3.1, other versions as follows: 

```
Mac-mini:RACPlayground xxx$ ./bootstrap
*** Fetching Rex
*** Fetching ReactiveCocoa
*** Fetching Result
*** Checking out Result at "2.1.1"
*** Checking out ReactiveCocoa at "v4.2.0"
*** Checking out Rex at "v0.9.0"
*** xcodebuild output can be found in /var/folders/7k/nbkx8hc5169c9kg7gyq43sjw0000gn/T/carthage-xcodebuild.eqNTWM.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveCocoa-iOS" in ReactiveCocoa.xcworkspace
*** Building scheme "Rex-iOS" in Rex.xcworkspace
Mac-mini:RACPlayground xxx$ carthage version
0.16.2
```

**Comment by andersio** [comment]
@peterlondon1 You need to open the playground within the workspace. Otherwise, Xcode would not be able to discover the frameworks built.

**Comment by peterlondon1** [comment]
Thank you so much! I feel such an idiot! (but perhaps this simple thing should be added to the GitHub page for other idiots like me?)

thanks again. am now really looking forward to finally understanding reactivecocoa this week!

**Comment by peterlondon1** [comment]
@FranDepascuali  Would you mind if I ask you questions as I work through your tutorial?  for example on the "Signal page" you say: 

 _If I could, I would avoid using pipe() here, but we haven't other way to manually create and control a signal. In a real app, we should avoid creating a signal with pipe() whenever possible.”_

     Why?

**Comment by FranDepascuali** [comment]
@peterlondon1 Great! I added a comment to the README for having the workspace opened. Regarding this last comment, please would you mind creating an issue [here](https://github.com/FranDepascuali/RACPlayground/issues)? So other people can see it and also I remember to change it, and answer there! Thank you!

**Comment by mdiep** [comment]
Awesome! ✨ 

Closing this since it doesn't seem like there's any action to be taken here.
