### ISSUE TITLE
Question: How to test signal producers that use .throttle

### ISSUE THREAD

**Issue by raphaeloliveira** [ReactiveCocoa/ReactiveCocoa#3008]
Hi guys, question, I'm struggling to find a way to test SignalProducers that use throttle.

```Swift
lazy var searchResultProducer: SignalProducer<SearchResult, NoError> = { [unowned self] in
    return self.searchTermSignalProducer
      .filter { $0?.characters.count >= 3}
      .throttle(0.5, onScheduler: QueueScheduler.mainQueueScheduler)....
```
My class that contains the `searchResultProducer` property receives the `searchTermSignalProducer` as a dependency so I can easily pass a stubbed one but I can't seem to make it work. If I put logEvents here 
``` Swift
return self.searchTermSignalProducer
      .filter { $0?.characters.count >= 3}.logEvents() 
```

I can see the events being logged but if I put `logEvents` after `throttle` I only see the start event.

That's my test:

```Swift
        myClass.searchTermSignalProducer = SignalProducer<String?, NoError>(value: "abcde")
        
        let searchResult = myClass.searchResultProducer.first()!.value!
        // stuck on first() because no next events are actually being sent to the throttled signal producer. 
```

I made some attempts with buffer to capture the observer and send next events, I also tried to use delay with TestScheduler but nothing really works. I'm probably missing something.

I appreciate any help. Thanks!

**Comment by andersio** [comment]
It is stuck because `throttle` delivers the event on main queue in the future. But at that time, your main thread is blocked by `first` which is waiting for the event. So a circular wait happened.

If you are using Nimble, you can observe the result on another thread, and use `toEventually` to test the asynchronously delivered result.
