### ISSUE TITLE
Bind Multiple TextFields text value in UITableViewCell to the ViewModel

### ISSUE THREAD

**Issue by tunidev** [ReactiveCocoa/ReactiveCocoa#3009]
I have a ViewModel: 

```
class FormField {
    var title:String
    var value:String?
}

class SignupViewModel {
   
    var formFields = [FormField]()

    init() {
        setupFormFields()
    }
    
    func setupFormFields() {
        // Setup the fields of the signup form
        let firstNameField = FormField(title: ... )  
        let anotherField = ...
        self.formFields = [firstNameField, anotherField,...]
    }
}
```

My view controller is has a `UITableView` with custom cells that contain a `UITextField` each. 

I want to bind the value of the textField to my ViewModel:

1. Each textField in the table can be populated in the first load by the value property of `FormField`

2. When user type a text in a textField, the respective `FormField` value property should be updated

Something like that 

```
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier(TextFieldCell.identifier(), forIndexPath: indexPath) as! TextFieldCell
        
        let formField = self.viewModel.formFields[indexPath.row]
        formField.value <~ cell.textField.text

        cell.setupCellWithFormField(formField)

        return cell
    }
```

I want to take in consideration the reuse case something like `takeUntil`

and also what do you think about the architecture of my solution

**Comment by tunidev** [comment]
I found an interesting blog post about what I want to achieve here

[Managing Reactivecocoa observations on UITableViewCell]( http://gentlebytes.com/blog/2015/09/30/managing-reactive-cocoa-observations-on-uitableviewcells/)
        
```
        cell.textField.rac_textSignal()
            .takeUntil(cell.rac_prepareForReuseSignal) // Ignore after cell gets reused
            .distinctUntilChanged() // Only take value if different from previous one
            .skip(1) // Skip cell dequeue event
            .subscribeNext { _ in
                formField.value = cell.textField.text
            }
```

and it seems to work, but I an still interested in your feedback about my hole solution and if is there a better approach

**Comment by mdiep** [comment]
I think `<~` is a good choice here. It returns a `Disposable`. You'll need to use that to dispose of the binding when the cell prepares for reuse.
