### ISSUE TITLE
RACSignal Bridging Issue

### ISSUE THREAD

**Issue by codyrobb** [ReactiveCocoa/ReactiveCocoa#3017]
Hello All,

I have recently been playing around with ReactiveCocoa 4.X. I currently work on a team that is still using the legacy 2.X version. We have a mostly Objective-C codebase that uses RAC pretty extensively. Now, I am trying to move us to the new 4.X version so we can use it rightfully in our new Swift code.

So here is the task I am faced with, I’m having a bit of trouble getting this to work.

We have a concept of a `ConsistencyController`. This is able to give us the latest persisted state of all of our models. It is returns a hot `RACSignal` that emits a `next` event with the updated model each time it gets updated. 

```objc
- (RACSignal *)modelForId:(NSString *)uniqueId class:(Class<EVTConsistentObject>)aClass;
```
*Method signaure for reference*

Now I need to be able to access and use this value in my Swift ViewModels. I am currently trying to figure out how to be able to access and use this stream of values.

To me, this sounds like it should be a `Signal<T, E:ErrorType>`. The only availble Objective-C bridge from `RACSignal` is a conversion to a `SignalProducer<T, E:ErrorType>`.

This is pretty crutical to me being able to use it in our project. I am pretty unsure of what to do here. I only need to be able to have some sort of stream of values I can direct to `MutableProperty<T>` and the likes.

**Comment by codyrobb** [comment]
Would something like this possibly work correctly?

```swift
let consistencyController = ConsistencyController()
let (signal, observer) = Signal<User?, NoError>.pipe()

consistencyController
    .userRACSignal // For example this is the hot RACSignal
    .toSignalProducer(resultingClass: User.self)
    .start(observer)


signal.observeNext {
    print($0)
}
```

```swift
extension RACSignal {
    
    func toSignalProducer<T>(resultingClass type: T.Type) -> SignalProducer<T?, NoError> {
        return self
            .toSignalProducer()
            .map { $0 as? T }
            .flatMapError { _ in SignalProducer<T?, NoError>.empty }
    }
    
}
```

**Comment by andersio** [comment]
You have the `startWith*` overloads that basically creates a signal behind the scene, and attaches the observer for you. You do not need to forward it yourself TBH. `SignalProducer` is not necessarily exclusive for cold signals, but is also commonly used as a facade of a signal for composition due to its lifetime management model.

**Comment by codyrobb** [comment]
@andersio Thanks for the reply!

Would you mind showing me how exactly that would look? I'm trying to figure out how to be able to still manipulate the values and bind them to different `MutableProperty<T>`s.

For example, I'm mostly interested in how to get from 

`RACSignal` -> `Signal<T, E:ErrorType>`. 

When using `startWithSignal`. The `Signal` it produces is captured in a closure. I need to use it outside of that closure.

Also, you say that `SignalProducer` is not necessarily exclusive for cold signals, but would that really work in this case? I can't get it to work. 

If I have:
```swift
consistencyController
    .userSource
    .toSignalProducer(resultingClass: User.self)
```

```swift
extension RACSignal {

    func toSignalProducer<T>(resultingClass type: T.Type) -> SignalProducer<T?, NoError> {
        return self
            .toSignalProducer()
            .map { $0 as? T }
            .flatMapError { _ in SignalProducer<T?, NoError>.empty }
    }

}
```

I never end up getting events emitted or binded to my `MutableProperty`

```swift

let bio = MutableProperty<String?>(nil)

bio <~ userSource
    .map { $0?.bio }
    .skipRepeats { $0.0 == $0.1 }
```

**Comment by andersio** [comment]
```
consistencyController
    .userRACSignal // For example this is the hot RACSignal
    .toSignalProducer(resultingClass: User.self)
    .startWithNext { value in
        print("New shiny value: \(value)")
    }
```

If you really demand for a `Signal`, you can always retain the signal supplied to you in `startWithSignal` anyway. As for your bindings, hmm, I do not see a problem in the snippets.

I would recommend you to inspect the raw producer first using `start { event in print("\(event)") }` first, to see if it still behaves correctly across the boundary.
