### ISSUE TITLE
How to be subscribed to a row change signal in a UIPickerView?

### ISSUE THREAD

**Issue by yotam-supersonic** [ReactiveCocoa/ReactiveCocoa#3021]
Hi,

I am trying to be notified about a change in the selected row of a UIPickerView element, and I currently have no success. Is there a way to do so?

Thanks

**Comment by mdiep** [comment]
You might want to check out the approaches that [Rex](https://github.com/neilpa/Rex) takes to observe changes to UIKit elements.
