### ISSUE TITLE
possible leak in Action initialization

### ISSUE THREAD

**Issue by gbuela** [ReactiveCocoa/ReactiveCocoa#3026]
Instruments is reporting a leak on this Action consistently, though I have other ones created in much the same way and they seem fine. 

![screen shot 2016-07-02 at 22 27 50](https://cloud.githubusercontent.com/assets/19420015/16543314/528bc508-40a4-11e6-9a50-1856e6bb1df6.png)

The last bit of code from my project in the trace looks like this:

`        fetchUserAction = Action<Void, User, FetchError> { [unowned self] _ in
            return self.userFetchSignalProducer()
        }`

Doesn't say much without context but the whole project is available [here in github](https://github.com/gbuela/github-users-coord) and I can provide simple steps to reproduce, if needed.

**Comment by andersio** [comment]
Please try the 4.2.1 release. I cannot reproduce the leaks on it, and 4.2.1 has a fix of a leak due to the mutable property binding, which `Action` uses.

**Comment by gbuela** [comment]
Cool, will report back.

**Comment by gbuela** [comment]
I still get the leak :-(

**Comment by andersio** [comment]
Can you describe how you, hmm..., lead to the leak?

**Comment by gbuela** [comment]
Using my project, the easiest way is to run the github-users-vc target which lets you try out individual view controllers in isolation. It shows a table view, just select "Detail" either from the test data section or network data section. It is reproducible in both.
Running the other target, you can make a user search, then you get a list of users, and then you select any user to get to the details vc. The leak happens here, where it creates the Action that fetches the user's data.

**Comment by andersio** [comment]
Caught it. It seems the property binding is still indirectly leaking. I will look into it ASAP.

**Comment by andersio** [comment]
Hmm, it should have been fixed 4 days ago in `master`. Now I know why I wasn't able to catch it at the beginning. I used my own pre-built binaries instead of running Carthage again. :p

https://github.com/ReactiveCocoa/ReactiveCocoa/commit/49f82c42e9de9006f8d862d4b21eb47f6581d632

**Comment by gbuela** [comment]
Great, thanks :)

**Comment by andersio** [comment]
Just wanna note that while I can no longer catch the reproducible `Atomic<Bool>` leak in the screenshot, I wasn't sure about whether some others are false positives or not, since Xcode reports clean if I just take two snapshots before and after the whole back-and-forth navigation stack traversals.
