### ISSUE TITLE
Getting Use of unresolved identifier QueueScheduler, SignalProducer, UIScheduler, when compiling successfully on the same time

### ISSUE THREAD

**Issue by evgeniyd** [ReactiveCocoa/ReactiveCocoa#3036]
I am using [Carthage](https://github.com/Carthage/Carthage) to add ReactiveCocoa to my **Swift 2.3** & **Xcode 8 Beta** project.

My _Cartfile_ has this:

    github "ReactiveCocoa/ReactiveCocoa" "swift2.3"

There is three-steps building process:

    $ sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer
    $ carthage update --no-build
    $ TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage build

After that I am following the instructions from ReactiveCocoa page (e.g. adding frameworks to the project, etc..)

I copied sample code from ReactiveCocoa's README.md

The project build & run is going well, the app is working fine, **BUT** there are three **Use of unresolved identifier** error in the editor and issue navigator. See screenshot.

Is it something related to the build configuration or using Swift or what else?

![screenshot 2016-07-06 12 52 51](https://cloud.githubusercontent.com/assets/5212518/16614218/9af2fff6-4378-11e6-9caf-67eff1b046ea.png)

**Comment by evgeniyd** [comment]
The issue has been fixed by re-adding frameworks to the project, cleaning up, restarting Xcode and so forth. 

Also, I noticed that in order to be able to jump to definitions of the symbols in ReactiveCocoa framework, I had to add path to **Header Search Path** where Carthage placed all the frameworks.

Basically, this:
**Framework Search Path**: `$(SRCROOT)/../Carthage/Build/iOS`
**Header Search Path**: `$(SRCROOT)/../Carthage/Build/iOS`

**NOTE:** I had the project in a workspace, hence `/../`

**Comment by mdiep** [comment]
Thanks for reporting back that you managed to fix it! That's a huge help.

(And sorry I didn't respond to this before now!)
