### ISSUE TITLE
Observer on RACSignal backed by RAC4 AnyProperty is still firing after class deallocated

### ISSUE THREAD

**Issue by TheDom** [ReactiveCocoa/ReactiveCocoa#3038]
We are using ReactiveCocoa 4.1. I did not test this with a newer version.

In our Swift code we define an `AnyProperty` and a `RACSignal` like that:

```
class X {
  let xProperty: AnyProperty<Bool>
  let xSignal: RACSignal

  init() {
    let xPropertyUpdateSignalProducer = ...
    
    xProperty = AnyProperty(
      initialValue: false,
      producer: xPropertyUpdateSignalProducer)
    
    xSignal = xProperty.producer.map { NSNumber(bool: $0) }.toRACSignal()
  }
}
```

In an `UIViewController` in Objective-C we subscribe to this `RACSignal`:

```
- (void)viewDidLoad {
  // (...)

  @weakify(self);
  
  [[self.xInstance.xSignal subscribeNext:^(NSNumber *x) {
     @strongify(self);
     // (...)
  }];
}
```

The issue is that this block which we pass to `subscribeNext:` is still called even after the `UIViewController` is deallocated. (In our case this lead to crash which is why we noticed it.)

We can fix this by changing this to:

```
[[self.xInstance.xSignal 
  takeUntil:[self rac_willDeallocSignal]]
  subscribeNext:^(NSNumber *x) { 
    // (...) 
  }];
```

Note that this is not necessary for `RACSignal`s created by RAC2's API.

Is this behavior expected?

**Comment by andersio** [comment]
You may want to try `master`. It has the fix of leaking property binding, which is used in `AnyProperty(initialValue:producer:)`.

**Comment by mdiep** [comment]
@TheDom Have you tried this with `master`?

**Comment by TheDom** [comment]
Sorry for not getting back to you earlier. I just tried it again against the current `master` and was able to reproduce it.

**Comment by andersio** [comment]
Closed since the semantics of `Property` (previously `AnyProperty`) have been changed, and the ObjC bridge had been spun off.
