### ISSUE TITLE
Should methods that return Disposables have discardable results?

### ISSUE THREAD

**Issue by mdiep** [ReactiveCocoa/ReactiveCocoa#3039]
This came up in https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3001/files#r68795757.

Should `Signal.observe()` return a discardable result? Or should you explicitly have to do  `_ = signal.observe(...)`?

**Comment by andersio** [comment]
I believe the disposable from `Signal.observe` is rarely used, as written in #3024.

> On the other hand, despite being part of the public API, the disposable returned from signal observation Signal.observe is rarely used because of three main reasons:

> 1. the user has explicit control to the signal lifetime.

> 2. the user composes a signal via takeUntil, which ends the subscription upon events from a signal that the user has explicit control or has a deterministic lifetime.

> 3. A SignalProducer - which always propagates interruption to the upstream - is used.

**Comment by NachoSoto** [comment]
Okay, that's fair. I agree now that making it not-discardable is a bit overzealous.
