### ISSUE TITLE
[Pitch] Replace `PropertyType.signal`.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3040]
While it makes absolute sense to expose `signal` on `MutableProperty`, the situation has slightly changed as now we have composed properties.

Due to the semantics of `Signal` which is uninterruptible from the downstream observers, any `signal`s created from a composed property but then left unused would actually **leak** until the upstream is terminated.

```
var disposable: Disposable?
func scope() {
    disposable = property.map { $0 + 1 }.map { $0 + 1 }.signal.observeNext { _ in }
}

scope()
disposable?.dispose()

// The signal is still alive at this point, and will terminate only when `property` is deinitialised.
```

Together with the semantics of composed properties (_respects the lifetime of its ultimate sources_), there is hardly a solution to this, unless we change the semantics of `Signal` to allow signals without observers to be automatically disposed of.

Therefore, I would like to propose that `PropertyType.signal` should be replaced by a producer ~~`PropertyType.changes`, and consequently `PropertyType.producer` should be renamed to `PropertyType.values` to make its role clear.~~

(The renaming can be done regardless of the change in type.)

-
Edited: Expand the scope for a bit.

**Comment by RuiAAPeres** [comment]
> Therefore, I would like to propose that PropertyType.signal should be replaced by a producer PropertyType.changes, and consequently PropertyType.producer should be renamed to PropertyType.values to make its role clear.

What would be the difference between these two producers then? I like the hot semantics that the exposed signal provides. Specially when we are dealing with things like `rex_text` (versus the producer's cold nature).

**Comment by andersio** [comment]
Still the same difference: emitting the current value, or not. Moreover, you still have access to `signal` on the concrete types in the case of `MutableProperty`.

It is worth noting that the `AnyProperty` in `RAC5` has a different lifetime w.r.t. `master`'s. The one in `RAC5` is a lens to the original property, so that:
```
/// property: MutableProperty<MutableProperty<Value>>
property.producer.flatMap { $0.producer }
property.flatMap { $0 }.producer
```
are identical. The one in `master` is a standalone property that determines its own lifetime and just happens to have a binding.

**Comment by andersio** [comment]
Hmm, a more illustrative example I can think of:
```
let tweetListViewModel = appViewModel.flatMap { $0.tweetList }
```
where the `appViewModel` is alive as long as the application. A repeated binding `rex_backgroundColor <~ appViewModel.flatMap { $0.unreadCount }.signal` would leak, regardless of the flattened `unreadCount` being retained or not.

Even if the binding is properly disposed of, `signal` on composed properties can only be initialised from the relay, and to receive values the relay must be retained. `Signal` has no mechanics to interrupt from the observers' end, so it would just leak.

**Comment by NachoSoto** [comment]
> I like the hot semantics that the exposed signal provides. Specially when we are dealing with things like rex_text (versus the producer's cold nature).

Yup, exactly. Semantically the suggested API would be incorrect. It has to be a `Signal` because:
- All observers see the same version of the stream.
- Stream is controlled by the emitter, not observers.
- We want to document and guarantee that subscription has no side effects.

**Comment by andersio** [comment]
@NachoSoto 
If we have to stick to the semantics, then either these should happen:

1. Removes `signal` from `PropertyType`;
2. Moves `signal` into a new protocol, e.g. `SourcePropertyType` that guarantees `self` owns `signal` and would not leak it, and obviously `Property` should not conform to it;
3. Leaves the leaking behaviour on composed properties as is, with just a comment that probably no one will notice.

**Comment by andersio** [comment]
After a second thought though, it seems it is fair to say extracting a signal from a composed property is as "dangerous" as composing an equivalent signal. Both are sticking to the semantics just right. It doesn't seem an issue for now then.
