### ISSUE TITLE
Cannot build swift2.3 branch from [5e634b8] via Carthage

### ISSUE THREAD

**Issue by evgeniyd** [ReactiveCocoa/ReactiveCocoa#3044]
Build process via Carthage breaks between these two commits:

[5e634b8] "[beta 2] Remove the weird workaround for linker error on Xcode 8 beta 1" **// <== NOT building**
[fe6dec1] "Update Result and fix code signing on Xcode 8 for device builds" // <== building

Steps to reproduce:
Step 1: My _Cartfile_ content:

    github "ReactiveCocoa/ReactiveCocoa" "swift2.3"

Step 2: In Terminal issue these commands:

    $ sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer
    $ carthage update --no-build
    $ TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage build

----> **Expected:** Build completes successfully

----> **Result:** Build fails with this error in the Terminal:

    ** BUILD FAILED **
    
    
    The following build commands failed:
	    Ld /Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework/Versions/A/ReactiveCocoa normal x86_64
	    GenerateDSYMFile /Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework.dSYM /Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
    (2 failures)
    /Users/admin/Documents/MyProject/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:1479:69: warning: 'buffer' is deprecated: Use properties instead. 'buffer' will be removed in RAC 5.0
    /Users/admin/Documents/MyProject/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/Swift/SignalProducer.swift:1479:69: warning: 'buffer' is deprecated: Use properties instead. 'buffer' will be removed in RAC 5.0
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: cannot parse the debug map for "/Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework/Versions/A/ReactiveCocoa": No such file or directory
    A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/admin/Documents/MyProject/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.xcworkspace -scheme ReactiveCocoa-Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
    --- xcodebuild: WARNING: Unable to open project file '/Users/admin/Documents/MyProject/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.playground' in workspace '/Users/admin/Documents/MyProject/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.xcworkspace'.
    ** BUILD FAILED **
    
    
    The following build commands failed:
	    Ld /Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework/Versions/A/ReactiveCocoa normal x86_64
	    GenerateDSYMFile /Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework.dSYM /Users/admin/Library/Developer/Xcode/DerivedData/ReactiveCocoa-faojnsjxemymqygfuaspgmerqsad/Build/Products/Release/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
    (2 failures)

...and this into the Console `.log`:

    ...
    ld: 2 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ...

**Comment by evgeniyd** [comment]
**UPDATE:**

Seems like, there was some 'typo" during re-adding classes to a build phase for macOS target during last commit.

iOS target is built OK using this command:

    $ TOOLCHAINS=com.apple.dt.toolchain.Swift_2_3 carthage build --platform iOS

**Comment by mdiep** [comment]
Which version of Xcode are you using?

**Comment by evgeniyd** [comment]
It was Xcode 8 Beta 1

**Comment by ikesyo** [comment]
As the commit message says, the branch is updated to support only beta 2. Please update to the latest beta.

**Comment by evgeniyd** [comment]
Sorry. I misunderstood the commit message had been related to Xcode beta 2.
