### ISSUE TITLE
How should we deal with the `rac_` prefixes in Swift 3?

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3049]
The Swift API guidelines set a convention of lower camel cases.

Currently, we have two exceptions in the Swift codebase: `NotificationCenter.rac_notifications(forName:object:)` and `URLSession.rac_data(with:)`. Moreover, since IIRC we are going to merge Rex in as part of the Cocoa Bindings repo at some point, how the `rex_` prefixes are handled should be considered too.

Should we follow, or leave them as is?

-
~~For the two extensions in this repo, the most uncreative name is probably `makeProducer`. But it might not suit everyone's tastes, hmm.~~

> Begin names of factory methods with “make”, e.g. x.makeIterator().

Edit: After a second thought, for producers, they do not have any side effect applied until they are started. So a non-mutating name describing what it would deliver would be appropriate IMO, e.g. just `notifications(forName:object:)`.

**Comment by mdiep** [comment]
We could drop the prefixes since the types make the names unambiguous—at least in most cases. Or we could keep them. I'm on the fence.

If we do keep them, we should use `rac_` here (including the code from Rex) and find a new prefix for ReactiveSwift.

**Comment by andersio** [comment]
Another approach can be introducing a "magic" variable that returns a wrapper of binding points, so that we have things like `view.rac.text <~ property`. It could make the bindings easier to discover too.

**Comment by mdiep** [comment]
ReactiveCocoa 5+ doesn't need to be compatible with Rex. RAC will subsume Rex.

**Comment by andersio** [comment]
Sure, I just meant those bindings brought in by Rex. Sorry if it reads like a mess. :smh

**Comment by andersio** [comment]
`outlets` would be a contender too.

**Comment by bobgodwinx** [comment]
"reactive" is suites better with swift language. "rac_" and "rex_" are very bad namings. I will go for "reactive", "active" or "signal"  so we could have view.reactiveText or view.activeText or view.signalText

**Comment by NachoSoto** [comment]
With Swift and modules there's no longer a risk for runtime collisions, and therefore no need for prefixes. So let's just drop 'em! :D

**Comment by andersio** [comment]
It is fine for the methods. But we can't have overloads for the properties.

**Comment by andersio** [comment]
I think it is safe to draw the conclusion that we cannot avoid/disambiguate compile-time collisions in any way. Suggestions like using operators or magic property just limit the reach of collision to one entity.

I would risk an operator collision in exchange of a nicer shorthand though...

**Comment by mdiep** [comment]
I think we're stuck with prefixes for properties for now.

**Comment by robertjpayne** [comment]
One of the things we've done with SnapKit is create a struct that hosts the extensions, the RAC api's could be stored like:

```
struct UIButtonRACDSL {
    var pressed: Signal<UIButton, NoError>
    init(button: UIButton) { }
}

extension UIButton {
    var rac: UIButtonRACDSL { return UIButtonRACDSL(button: self) }
}
```

Going down this route provides some flexibility and reduces the collision scope of the extensions.

**Comment by andersio** [comment]
Yeah, I have brought it up before. It replaces the underscore with a dot, and allows the introduction of an operator shorthand. But there seems having no interests from others.

**Comment by ianbytchek** [comment]
`rac` property would look so much cleaner… SOOO MUUUCH!!! :heart_eyes:

**Comment by mdiep** [comment]
I think we should steal the approach that RxSwift has taken.

https://github.com/ReactiveX/RxSwift/blob/4952adb27c684b47792923b00015516849061eab/RxCocoa/Common/Reactive.swift
https://github.com/ReactiveX/RxSwift/blob/4952adb27c684b47792923b00015516849061eab/RxCocoa/iOS/UIControl%2BRx.swift

They added a struct, `Reactive` that's generic over the type they want to extend. They then added methods on constrained extensions to `Reactive`. Evidently they modeled this after Swift's `.lazy`.

**Comment by andersio** [comment]
https://github.com/RACCommunity/Rex/pull/143

😜
