### ISSUE TITLE
swift2.3 branch: number of failures when building via Carthage

### ISSUE THREAD

**Issue by evgeniyd** [ReactiveCocoa/ReactiveCocoa#3050]
The latest commit breaks building ReactiveCocoa via Carthage via Xcode 8 Beta 2 (Swift 2.3 toolchain)

[2a23524] Update Quick and Nimble

[carthage-terminal-output.txt](https://github.com/ReactiveCocoa/ReactiveCocoa/files/356014/carthage-terminal-output.txt)

**Comment by ikesyo** [comment]
That was successfully built on my local environment and on Travis CI too (#3005, https://travis-ci.org/ReactiveCocoa/ReactiveCocoa/builds/144701985). Could you please make sure that you are using `xcodebuild` of Xcode 8 beta 2 by `xcode-select` or `DEVELOPER_DIR=/Applications/Xcode-beta.app xcodebuild`? And also clearing your derived data directory might be a help.

Closing.

**Comment by evgeniyd** [comment]
Hello, @ikesyo 

is "swift2.3" branch removed? Which one should I use for swift 2.3 support?

**Comment by ikesyo** [comment]
That was merged into `master` now.
