### ISSUE TITLE
Set of network extensions

### ISSUE THREAD

**Issue by badeleux** [ReactiveCocoa/ReactiveCocoa#3055]
I'm planning to build set of extensions for RAC which will make building network requests easier. I want to create layer for __caching__, __retrying__, __updating__ . I haven't thought about architecture cause firstly I'd like to ask whether this idea is worth doing whether it doesn't abuse FRP, and it's possible to do cause I'm kinda surprised there is no such a thing yet.

```swift
let racCache = ArchiverCache()
let fetchCriticalData = Alamofire...
fetchCriticalData.updateOn(didEnterForeground).cache(racCache, policy: CacheFallbackRemote).retryOn(retryButtonTapped)
```

**Comment by RuiAAPeres** [comment]
@badeleux unsure if it makes sense to have it here, but definitely at [RACCommunity](https://github.com/RACCommunity/contributors). Please open an issue [here](https://github.com/RACCommunity/contributors/issues/new).

**Comment by badeleux** [comment]
Sure, sorry.
