### ISSUE TITLE
Legacy build?

### ISSUE THREAD

**Issue by AlexeyPoldeo** [ReactiveCocoa/ReactiveCocoa#3065]
Hello everyone,

I'm new to FRP and ReactiveCocoa.
I have no plans to switch to Swift (yes, I know it's great for FRP, but not for me).

Trying to build ReactiveCocoa for ObjC and faced with multiple issues.
Looks like the legacy version is completely broken.
First of all, iOS library targeted for Mac OS. Second, it lacks of 'Results' framework and I have no idea where to get it.
But even after manual fix of many build issues, I still unable to build the library.
Usually well maintained framework has no such critical issues right 'out of the box'.

Are someone able to build it?
Is it still can be considered as production solution?

**Comment by andersio** [comment]
Could you give a little more details, like which branch/release you are using, and what Xcode version are you using?

The `master` branch is perfectly fine, and our CI tests of the Objective-C are all functional and passing. Our releases must pass the CI tests before shipping.

**Comment by andersio** [comment]
Have you followed our steps in [Getting Started](https://github.com/ReactiveCocoa/ReactiveCocoa#getting-started) to set it up? We have also dependency on `xcconfigs`, and downloading the source code directly won't work.

**Comment by AlexeyPoldeo** [comment]
Thank you for prompt response!
Yes, I followed Getting Started (from the legacy docs of course).
And I've used direct sources download.
Should I add it as my repository mode?
Will it fix my issues?
(And yes, sources .zip does not have xcconfigs inside...)

**Comment by andersio** [comment]
Yes, you can follow the instructions for our current documentation in fact, since the current 4.x releases are for **both** Swift and Objective-C. You may as well consider Carthage.

**Comment by AlexeyPoldeo** [comment]
Thank you for details - I will try to make it later, unfortunately too busy now.

So far I suggest to update the legacy Getting Started docs:

1. Fix library name (it's different from the real one)
2. Add note that it will not build from directly downloaded sources

Also a statement "Copy the library project to your project" is confusing - usually it means that directly downloaded sources are fine. This is not true in this case.

**Comment by mdiep** [comment]
This will all be changing soon because the Obj-C code will be moving out of this repo.
