### ISSUE TITLE
RACCommand and Action

### ISSUE THREAD

**Issue by codyrobb** [ReactiveCocoa/ReactiveCocoa#3068]
Hi,

Another 2.X to "How to do this in RAC 4.0" question.

In our app, we currently have a flow like this (RAC 2.X style):

```objc 
/// Database Layer
RACCommand *starMessageCommand = [[RACCommand alloc] initWithSignalBlock:^RACSignal(RACTuple *messageIdAndState) {
	RACTupleUnpack(NSString *messageId,
				   NSNumber *starred) = messageIdAndState;

	return [self.client starMessage:messageId starred:starred.boolValue];
}];


/// View Model Layer
RACCommand *starMessage = [[RACCommand alloc] initWithSignalBlock:^RACSignal(id _) {
	return [self.messageServices.starMessageCommand execute:RACTuplePack(self.message, !self.message.starred)];
}];
```

Two important things I'm trying to figure out:

- What pattern to use for "chaining" `RACCommands` (well now `Actions`).
- How to get around the inability to do concurrent executions for `Actions`.

A bigger problem is the lack of concurrent executions for actions. I'm not sure with this flow how I could get around that. I'm very interested in what type of solutions the RAC team uses.

**Comment by mdiep** [comment]
It would help to have some more detail about what you're trying to do.

**Comment by aehlke** [comment]
Did you find a way to get around the lack of concurrent actions?
