### ISSUE TITLE
Include of non modular header inside framework module "reactivecocoa.swift" 

### ISSUE THREAD

**Issue by sgup77** [ReactiveCocoa/ReactiveCocoa#3069]
After updating my cocoapods to 1.0.1. whenever i try to run my project i am getting this error

1.) Include of non modular header inside framework module "reactivecocoa.swift" 
2.) Duplicate interfaces definition for class "RACStream"

**Comment by raylillywhite** [comment]
I "solved" this for our project a while ago with adding the following code to my Podfile. I'm not sure if there's now a better way to handle this with Cocoapods or not.

```ruby
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
```

**Comment by ikesyo** [comment]
Clearing your derived data dir might fix it?

**Comment by andersio** [comment]
Inactivity for three months. Pleas reopen if you need further help. 😄
