### ISSUE TITLE
Substitution for SignalProducer.buffer()

### ISSUE THREAD

**Issue by dev4dev** [ReactiveCocoa/ReactiveCocoa#3070]
Deprecation warning says nothing to me - Use properties instead. 'buffer' will be removed in RAC 5.0

What properties? Could someone provide clear example. Thanks.

**Comment by andersio** [comment]
`buffer(0)`: semantically the same as `Signal.pipe` but more efficient.
`buffer(1)`: effectively a `MutableProperty`. This is the most common use case AFAICT, and hence probably why the deprecation recommends it as the replacement.
`buffer(n)` for n > 1: You may consider `SignalProducer.replayLazily`.

**Comment by dev4dev** [comment]
@andersio oh, thanks a lot, I thought not about _right_ properties

**Comment by benji-bou** [comment]
Hy, 

What if I wanted to send back an error to the buffered SignalProducer? 
In the MutableProperty there is NoError in the Signal or SignalProducer 

Regards

**Comment by andersio** [comment]
If you really need the same functionality, you may create a `Signal` pipe, wrap it with a `SignalProducer` and use `replayLazily`. Note that `replayLazily` starts buffering events only if it has ever been started.

```
let (signal, observer) = Signal<Int, TestError>.pipe()
let replayedProducer = SignalProducer(signal: signal).replayLazily(1)

// Start the buffering immediately.
replayedProducer.start()
```

**Comment by benji-bou** [comment]
Thanks, It's what I was looking for

**Comment by wdcew** [comment]
Thanks，

**Comment by shuoshi** [comment]
replayLazily seems has side effect.

take a look at example below

    let (signal, observer) = Signal<Int, NSError>.pipe()
    let replayedProducer = SignalProducer(signal: signal).replayLazily(1)

    // Start the buffering immediately.
    replayedProducer.start()

    func someAsyncProcedure() {
        observer.send(error: NSError())                           //<------------       LINE 2
    }

    func someProcedure {
        replayedProducer.startWithResult {
            switch($0) {
            case .success(let value):
               print(value)
            case .failure(let error):
               print(error)                                        //<------------      LINE 1
            }
        }
        someAsyncProcedure()
    }
    
    someProcedure() //everything is fine
    someProcedure() //LINE 1 is called before LINE 2

I didn't read the code of replayLazily, but it seems used a cached value instead of using observer sent value. Problem is when observer send value, the failure procedure is called instead of success.

To solve this problem I have to create a Signal every time I call someProcedure, don't think it's a good practice... any comment is welcome

**Comment by andersio** [comment]
When the second time you call `someProcedure`, the underlying producer has already terminated with an error, and the replayed producer caches the error. That's why you get "Line 1" called before "Line 2" - it is replaying the error.

**Comment by shuoshi** [comment]
@andersio Thanks for replying. 

I guess since the producer is terminated, it's OK to create a new signal to handle the async procedure like this

    class SomeClass {
        private var observer: Observer<String, NSError>!
        
        //delegate method
        func someAsyncProcedure() {
            observer.send(error: NSError())                           //<------------       LINE 2
        }

        func someProcedure -> SignalProducer<String, NSError> {
            let producer SignalProducer<String, NSError> { [weak self] sink, _ in
                self!.observer = sink
            }
            someAsyncProcedure()
            return producer
        }
    }

    func xxx() {
        SomeClass.someProcedure().startWithResult {
            switch($0) {
                case .success(let value):
                    print(value)
                case .failure(let error):
                    print(error)                                        //<------------      LINE 1
            }
        }
    }
    
    xxx()
    xxx()

I guess what I want is Future semantics here...

I've read [#2744](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2744) and noticed

> PropertyType has the exact same semantics as SignalProducer.buffer

But as benji-bou said, Property does not emit errors. It seems I have to use two Property to handle error, one is Success Property, wrapping the value I want, the other is an Error Property, and I have to observe on both of them, right?

**Comment by andersio** [comment]
It seems what you'd want is wrapping a delegate pattern as streams of values. In this case, I think you'd be better off with an internal `Signal<Result<Value, Error>, NoError>` signal, and derive producers from it.

```
let asyncResult: Signal<Result<Value, Error>, NoError>

func work() -> SignalProducer<Value, Error> { observer, disposable in
    // Perhaps you'd want mutual exclusion here too.
    disposable += asyncResult.observeValues { result in
        switch result {
        case let .success(value):
            observer.send(value: value)
        case let .failure(error):
            observer.send(error: error)
        }
    }
}
```

**Comment by shuoshi** [comment]
@andersio Thanks for your patience, problem solved 👍
