### ISSUE TITLE
textField.rac_textSignal does not work when textField.text has changed

### ISSUE THREAD

**Issue by johnMaster** [ReactiveCocoa/ReactiveCocoa#3072]
I want to clear my textfield by custom clear button. But I also  bind rac_texSignal to check textField length and hide clear button.    

```
RAC(weakSelf.clearButton, hidden) = [_textField.rac_textSignal map:^id(NSString *value) {
        return value.length > 0 && weakSelf.textField.editing == YES ? @NO : @YES;
   }];
```

I clear textField.text when I touch up inside clear button. 

```
[_clearButton bk_addEventHandler:^(id sender) { 
      weakSelf.textField.text = @"";`
 } forControlEvents:UIControlEventTouchUpInside];
```

It does not work when I set textField.text. It seem change textField.text does not trigger any event.

**Comment by mdiep** [comment]
That's because this is how `UIControlEventAllEditingEvents` works.

**Comment by johnMaster** [comment]
@mdiep I see the source code that ReactiveCocoa just binding `UIControlEventAllEditingEvents `. It does not work when I try combineLatest value observe signal and editing signal.
`RAC(weakSelf.clearButton, hidden) = [RACSignal combineLatest:@[RACObserve(_textField, text),`
`                                                        _textField.rac_textSignal]`
 `                                             reduce:^id(NSString *value){`
 `                                                  return value.length > 0 && weakSelf.textField.editing == YES ? @NO : @YES;`

**Comment by johnMaster** [comment]
I find  [http://stackoverflow.com/a/6051404/6575781](UIKit is not KVO-compliant).So we must to find other way to achieve it. :(

**Comment by johnMaster** [comment]
combine two signal about textfield : RACObserver(textfield.text) and textField.rac_textSignal. then you can return textfield.text by getter method . the map the signal which map and return _textField.text. as result , it will return the correct value

**Comment by johnMaster** [comment]
this issues can close
