### ISSUE TITLE
Observe when an object's property changes?

### ISSUE THREAD

**Issue by xanderbuck** [ReactiveCocoa/ReactiveCocoa#3073]
Is there any way to observe when an object's property changes?

For example. If my viewModel, has a property "Person" and this Person object has a property "name".

Is there a way for a viewController to observe when the name property of the person object changes (or any other properties the Person object may have)?

Currently, I can only seem to observe when the whole Person object changes, but can't seem to observe when any of its properties change value as well.

Thanks!

**Comment by xanderbuck** [comment]
For example I can observe changes to the person object, but how do I also observe changes to the person object's properties?:

> viewModel.person.producer.startWithSignal {(observer, _) in
>             observer.observeOn(scheduler).observeNext {person in
>                 
>                //handle next event
>                 
>             }
>         }

**Comment by andersio** [comment]
Unless `Person` is an `NSObject` subclass, you must model also the properties of `Person` as `Property` types.

**Comment by xanderbuck** [comment]
@andersio I currently have the Person class as a subclass of NSObject, but I can't seem to get events when its properties change. Am I missing something?

**Comment by andersio** [comment]
You still need to subscribe specifically to that key path on the object. In 4.x, you may use `rac_valuesForKeyPath` from Objective-C to achieve this.

**Comment by xanderbuck** [comment]
Thank you so much for your help :)
