### ISSUE TITLE
[5.0] Potential leakage when using `signal` of composed properties

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3080]
Due to the signal lifetime semantics we currently have, `signal` of composed properties could have a potential to leak if either:

1. It is repeatedly called; or
2. It is called but left unused.

Consider the following snippet:
```
let mapped = property.map { $0 + 1 }
for _ in 0 ..< 100000 {
    _ = mapped.signal
}
```
It would create 100000 signals from the property that would live as long as `property`.

Note that even if we share the signal across invocations, the lifetime issue of such `signal` still persists, since the current semantics of `Signal` is **purely** emitter-controlled and push-driven.

We should revisit this after #3075 concludes. 🎄

**Comment by mdiep** [comment]
This was resolved by #2959.
