### ISSUE TITLE
Alternative to startWithNext on SignalProducer?

### ISSUE THREAD

**Issue by xanderbuck** [ReactiveCocoa/ReactiveCocoa#3081]
I see that startWithNext is deprecated... what is the alternative? In my case I don't care to know if it fails, completes, or is interrupted 

I know I can do the following, but its not as short and doesn't feel as clean:

> .startWithSignal {(signal, _) in
>                 
>                 signal.observe(Signal.Observer { event in
> 
>                     switch event {
>                     case let .Next(url):
>                         print(url)
>                     case let .Failed(error):
>                         print("Failed: \(error)")
>                     case .Completed:
>                         print("Completed")
>                     case .Interrupted:
>                         print("Interrupted")
>                     }
>                     
>                     })

**Comment by andersio** [comment]
`startWithNext` is deprecated for producers that may fail, i.e. Error != NoError. You may use `startWithResult` instead.
