### ISSUE TITLE
timeoutWithError for NoError should not require promoteErrors

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#3083]
If signal/producer does not initiate any error (NoError), currently we have to adopt it to any error type with promoteErrors if we want to use timeoutWithError on it.

Can we add timeoutWithError for NoError type also, in similar way it was added for flatMap functions  https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2542

**Comment by NachoSoto** [comment]
Yeah I think that's reasonable.
