### ISSUE TITLE
Installation with Carthage fails

### ISSUE THREAD

**Issue by aschuch** [ReactiveCocoa/ReactiveCocoa#3088]
> Since the following installation error only occurs with ReactiveCocoa, I am reporting it here.

I am trying to install v4.2.2 of ReactiveCocoa using Carthage 0.17.2. 
Installing v4.2.1 works as expected, but I am unable to install v4.2.2 due to the following git error.

```bash
$ carthage update --no-use-binaries --platform iOS --use-ssh
*** Fetching Result
*** Checking out Result at "2.1.3"
*** Checking out ReactiveCocoa at "v4.2.2"
A shell task (/usr/bin/env git checkout --quiet e2cfb86c8379417c9272bb853e9f0c407167d486) failed with exit code 128:
fatal: reference is not a tree: e2cfb86c8379417c9272bb853e9f0c407167d486

$ git version
git version 2.7.4 (Apple Git-66)
```

**Comment by RuiAAPeres** [comment]
I can confirm I am seeing the same issue on my side.

**Comment by aschuch** [comment]
Update: This seems to be fixed by 47bd333aac35d00acee1ff2710f42efdde33b466, so we probably need a new release.

**Comment by RuiAAPeres** [comment]
Related to #3086

**Comment by mdiep** [comment]
@sharplet Could you restore that commit to your fork of Quick?

**Comment by RuiAAPeres** [comment]
@mdiep Could we make a patch release to solve this issue?

**Comment by mdiep** [comment]
It would be better if @sharplet restored that commit—because then everything that's pinned to 4.2.2 will continue to work. Otherwise _everything_ needs to be updated off 4.2.2.

But if that doesn't happen, we can create a new release later today.

**Comment by sharplet** [comment]
I had no idea RAC was pinned to my fork! 😅

I've just pushed Quick's current master https://github.com/Quick/Quick/commit/816489f39f590d87801ba4cd24c68e86635855de to [sharplet/Quick](https://github.com/sharplet/Quick), which includes the previously pinned commit.

**Comment by RuiAAPeres** [comment]
@sharplet seems to be working again. 👍

**Comment by mdiep** [comment]
Thank you, @sharplet! Sorry to "pin" this on you. 😜

I hadn't considered that pinning to someone's branch might break in the future. I'll watch this more carefully in the future!
