### ISSUE TITLE
Question: when does `first()` return nil?

### ISSUE THREAD

**Issue by raphaeloliveira** [ReactiveCocoa/ReactiveCocoa#3089]
Hi, the documentation about `first()` is

```
    /// Starts the producer, then blocks, waiting for the first value.
    @warn_unused_result(message="Did you forget to check the result?")
    public func first() -> Result.Result<Self.Value, Self.Error>?
```

Can I please get some clarification in what circumstances this method return `nil`?

**Comment by ikesyo** [comment]
It is when the producer completes without sending any value. So `SignalProducer<Int, NoError>.empty.first()` would return `nil`.
