### ISSUE TITLE
How to RacObserver a NSDictionary property

### ISSUE THREAD

**Issue by taojigu** [ReactiveCocoa/ReactiveCocoa#3090]
For example 

I have to keep the NSDictionary property of MyViewController has the same value with the counterpart of MyViewModel. 

How could Rac Observer the change  of NSDictionary Property(not the elements in it)

```swift
class MyViewModel
{
     var myInfoDict:[String:AnyObject]? = nil;
}


class MyViewController
{
     var myInfoDict:[String:AnyObject]? = nil;
     var viewModel:MyViewModel? = nil;

     init()
    {
      // I initiate here
       self.viewModel.myInfoDict = self.myInfoDict
     }

    // this message will be invoked by clients
     func changeDictaryProperty(newDict:[String:AnyObject])
     {
            self.myInfoDict = newDict;
           // I expect self.viewModel.myInfoDict is updated too
     }
}
```

**Comment by mdiep** [comment]
Well you could (a) set the value on the view model directly or (b) use a `didSet` on the property to set the view model property or (c) use a computed getter and setter to back the property with the view model property. But none of those use RAC.

The RAC way to observe/react to property changes is to use a `PropertyType`.

**Comment by taojigu** [comment]
Thanks
