### ISSUE TITLE
Odd Swift warning related to RACKVOChannel subscript operation.

### ISSUE THREAD

**Issue by eric-robinson** [ReactiveCocoa/ReactiveCocoa#3091]
This is a question more than an issue, but was hoping for some insight into some odd Swift behavior I'm seeing in RAC 4 & Swift 2.2.

We're using RAC heavily in our project, just started noticing some odd issues when building in release mode when doing dictionary accessors on `AnyObject?` (e.g. `JSON["key"] as? String`).

Swift is warning me `Cast from 'RACChannelTerminal!?' to unrelated type 'String' always fails`.  I strongly believe this is swift matching against the subscripting support added `RACKVOChannel` in `RACKVOChannel.h`. In our project this issue only presents itself in release configuration and was introducing subtle bugs extracting values from dictionaries (especially related to generic function arguments not being inferred correctly).

This can be observed by adding the following to the Sandbox playground in the RAC project.

```
public extension RACSignal {
    func someJSONMapFunction() -> RACSignal {
        return flattenMap { JSON in
           // The next line throws a warning
           // WARNING: Cast from 'RACChannelTerminal!?' to unrelated type 'String' always fails
            if let string = JSON?["key"] as? String { 
                // do something
            }
            return nil
        }
    }
}
```

Again, I don't believe this to be an issue with RAC, and we've updated our usage to do an optional cast here (e.g. `if let JSON = JSON as? NSDictionary {`), which is safer for reasons unrelated to RAC. But I wanted to reach out to the community and see if anyone has had similar issues. Thanks for reading.

**Comment by mdiep** [comment]
I've seen issues like this in Objective-C before too—where the compiler decides on a particular variant when the type of an object is unknown. I don't think there's anything to do about it besides cast it to the correct type.

**Comment by eric-robinson** [comment]
@mdiep Got it.. that's what I expected. Thanks for responding!
