### ISSUE TITLE
use ReactiveCocoa (2.5) crash log

### ISSUE THREAD

**Issue by wells1013** [ReactiveCocoa/ReactiveCocoa#3092]
use ReactiveCocoa (2.5) crash log

EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
0	libobjc.A.dylib
1	libobjc.A.dylib
2	libobjc.A.dylib
3	libobjc.A.dylib
4	UIKit
5	UIKit
6	UIKit
7	jike	__swizzleDeallocIfNeeded_block_invoke	[NSObject+RACDeallocating.m line 50]
8	libobjc.A.dylib
9	libobjc.A.dylib
10	CoreFoundation
11	CoreFoundation
12	CoreFoundation
13	CoreFoundation
14	GraphicsServices
15	UIKit
16	jike	main	[main.m line 14]
17	libdyld.dylib
18	libdyld.dylib

**Comment by mdiep** [comment]
There's not enough detail here to be actionable.
