### ISSUE TITLE
combineLatest() starts SignalProducers in reverse order

### ISSUE THREAD

**Issue by chrrasmussen** [ReactiveCocoa/ReactiveCocoa#3094]
I have some code that downloads images from a HTTP API. When I call `combineLatest()` on a list of SignalProducers (`[SignalProducer<NSData, NSError>]`) the network requests are started in the reverse order. I do get the results back in the same order as the SignalProducer are placed though. Is this expected behavior?

I tried to investigate the problem and created a workaround:

```swift
@warn_unused_result(message="Did you forget to call `start` on the producer?")
public func reversedCombineLatest<S: SequenceType, Value, Error where S.Generator.Element == SignalProducer<Value, Error>>(producers: S) -> SignalProducer<[Value], Error> {
    var generator = producers.reverse().generate() // Added reverse()
    if let first = generator.next() {
        let initial = first.map { [$0] }
        return GeneratorSequence(generator).reduce(initial) { producer, next in
            producer.combineLatestWith(next).map { [$0.1] + $0.0 } // Reversed array concatenation
        }
    }
    
    return .empty
}
```

I guess a better way to fix the problem is to change `Signal.combineLatestWith()`, but I was not able to figure out how.

Example code:

```swift
import Result
import ReactiveCocoa
import Foundation


// Helper function

func createRequest(number: Int) -> SignalProducer<Int, NoError> {
    return SignalProducer { (observer, disposable) in
        print("Sending request #\(number)")
        
        observer.sendNext(number)
        observer.sendCompleted()
    }
}


// Example #1: combineLatest()

print("Example #1: combineLatest()")

let requests = [
    createRequest(1),
    createRequest(2),
    createRequest(3)
]

combineLatest(requests).startWithNext { result in
    print("Result: \(result)")
}


// Example #2: Reversed version of combineLatest()

print("\nExample #2: Reversed version of combineLatest()")

// FIXME: Insert implementation of reversedCombineLatest() from above here

reversedCombineLatest(requests).startWithNext { result in
    print("Result: \(result)")
}
```

Which will print:

```
Example #1: combineLatest()
Sending request #3
Sending request #2
Sending request #1
Result: [1, 2, 3]

Example #2: Reversed version of combineLatest()
Sending request #1
Sending request #2
Sending request #3
Result: [1, 2, 3]
```

The examples can be run from the Playground page named "CombineLatest" in this fork: https://github.com/chrrasmussen/ReactiveCocoa/blob/master/ReactiveCocoa.playground/Pages/CombineLatest.xcplaygroundpage/Contents.swift

**Comment by mdiep** [comment]
Hmm… that's definitely not expected. (At least not by me.)

**Comment by chrrasmussen** [comment]
@mdiep Thanks for agreeing!

I looked a bit closer at the problem and figured out that I could switch places of `self.startWithSignal()` and `otherProducer.startWithSignal()` in [`SignalProducerType.combineLatestWith()`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L827-L848). It seems like the callback needs to complete before the SignalProducer can start, and since `otherProducer` will complete first it is started before `self`.

The updated code:

```swift
@warn_unused_result(message="Did you forget to call `start` on the producer?")
public func combineLatestWith<U>(otherProducer: SignalProducer<U, Error>) -> SignalProducer<(Value, U), Error> {
	// This should be the implementation of this method:
	// return liftRight(Signal.combineLatestWith)(otherProducer)
	//
	// However, due to a Swift miscompilation (with `-O`) we need to inline `liftRight` here.
	// See https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2751 for more details.
	//
	// This can be reverted once tests with -O don't crash.
	
	return SignalProducer { observer, outerDisposable in
		otherProducer.startWithSignal { otherSignal, otherDisposable in
			outerDisposable.addDisposable(otherDisposable)
			
			self.startWithSignal { signal, disposable in
				outerDisposable.addDisposable(disposable)
				
				signal.combineLatestWith(otherSignal).observe(observer)
			}
		}
	}
}
```

Should I also change `liftRight` to `liftLeft` in the comments?

**Comment by mdiep** [comment]
Yeah, want to open a PR for that with a test? `zipWith` should follow suit.

@neilpa @NachoSoto You were involved with adding `liftLeft` and `liftRight` in #2571. `lift` has always been `liftRight`, but it does seem more intuitive to me for `combineLatestWith` and `zipWith` to be left associative. Is there any reason it shouldn't be?

**Comment by andersio** [comment]
AFAICT the difference of `liftLeft` and `liftRight` is the execution order of start handler, which seemingly doesn't matter in `combineLatest` and `zip`.

**Comment by chrrasmussen** [comment]
Sure :-)

The original test for `it("should combine the events to one array")` failed after I changed the underlying code, so I made the test more explicit.

**Comment by neilpa** [comment]
For `combineLatest` and `zip` I didn't consider the start handler associativity since the unified signals are semantically independent as @andersio already mentioned. I just had to pick one to handle the combining.
