### ISSUE TITLE
Executing order of SignalProducer.on(start:) is reversed compared to SignalProducer.on(next:)

### ISSUE THREAD

**Issue by Wangdi** [ReactiveCocoa/ReactiveCocoa#3095]
I am using `on(start: next:)` to delivery states from view model and refresh on view controller, as follows:

```
// in view model
loadDataProducer.on(start: { // closure 1
    loading = true
})
// in view controller
.on(start: { // closure 2
    cover.hidden = viewModel.loading
})
```

It is a trivial example above, but the point is that it cannot make state dependent chaining closure of `on(start:)`, since `closure 2` is executed before `closure 1`, which is against order of signal flow like `next` and `complete`. 

I wonder if this is intentional? If so, how should I use `on(start:)` to react on each layer?

**Comment by andersio** [comment]
IMO this is a bug. Thanks for pointing it out.

**Comment by mdiep** [comment]
This isn't necessarily a bug. It's the different between willStart and didStart in Cocoa parlance. The current willStart behavior matches RAC2's `-initially:`. 😕 

In your example, @Wangdi, you might want to make `viewModel.loading` a `Property` and then observe it in the controller.

**Comment by andersio** [comment]
The argument label is `started` though... Should we introduce both variants in `on` then?

**Comment by andersio** [comment]
The argument label is `started` though... Should we introduce both in `on` anyway?

**Comment by mdiep** [comment]
Maybe we should offer both `starting` and `started`?

**Comment by Wangdi** [comment]
Thank you guys, excellent improvement 👍
