### ISSUE TITLE
Signal is already bound to key path crash

### ISSUE THREAD

**Issue by tunidev** [ReactiveCocoa/ReactiveCocoa#3100]
I have inside `cellForRowAtIndexPath`  this code for binding : 

```
PostCell *myCell = (PostCell*)cell;
RAC(myCell, username) = [RACObserve(self.viewModel, selectedUser.name) takeUntil:[myCell rac_prepareForReuseSignal]];
```
and inside my cell:

`RAC(self.usernameLabel, text) = RACObserve(self, username);`

But I get as error when scroll:

`Signal <RACDynamicSignal: 0x7f899833ccb0> name:  is already bound to key path "username" on object <PostCell: 0x7f899831da40; baseClass = UITableViewCell; frame = (0 0; 375 44); hidden = YES; autoresize = W; layer = <CALayer: 0x7f89983161d0>>, adding signal <RACDynamicSignal: 0x7f8994d6d340> name:  is undefined behavior`

**Comment by mdiep** [comment]
The line inside your cell must be getting called twice. You can't bind it again because the previous binding still exists. You need to either bind once or cancel the previous binding beforehand.
