### ISSUE TITLE
Signal deallocation timing

### ISSUE THREAD

**Issue by yoching** [ReactiveCocoa/ReactiveCocoa#3103]
I have questions about the deallocation of `Signal`.
I'm using RAC v4.2.2.

1. When will a `Signal` be released?
1. Are there any ways to handle signal deallocation like `deinit` closure of swift object?

I wrote 2 cases that I don't understand the behavior of `Signal`.
Would you tell me when the `Signal` be released in each case?

**Case 1: using `pipe`**
``` swift
class A {

    let signal: Signal<Void, NoError>
    let observer: Signal<Void, NoError>.Observer
    
    init() {
        (signal, observer) = Signal<Void, NoError>.pipe()
    }
    
    deinit {
        print("A deinit")
        // observer.sendCompleted() // *
    }
}

var a: A?
a = A()
a = nil // prints "A deinit"
// -> Will 'signal' be released too? Or, should I call 'observer.sendCompleted()'(*) in deinit closure in A?
```

**Case 2: using `SignalProducer`**
``` swift
class B {
    init() {
        
        SignalProducer<Void, NoError> { observer, disposable in
            observer.sendNext()
            }
            .startWithSignal { signal, disposable in
                // When will this 'signal' be released?
        }
    }
    
    deinit {
        print("B deinit")
    }

}

var b: B?
b = B()
b = nil // prints "B deinit"
// Will signal created by producer be released? Or, should I call 'observer.sendCompleted()' somehow?
```

P.S. I'm learning and using RAC for about half a year. Thank you for the awesome library!😄

**Comment by andersio** [comment]
Case A: any references captured by the signal is released.

Case B: The subscription would not stop. The produced signal stops only if its input observer receives a terminating event (which never happens in this case), or it is interrupted by the disposable passed to you in `startWithSignal`.

**Comment by yoching** [comment]
Thank you!
I understood Case B, but didn't understand Case A clearly.

> any references captured by the signal

What does this mean? Some variables used in observers attached to the Signal? Or some values of `Next` events?

**Comment by andersio** [comment]
Closures capture references. An observer is fundamentally a closure. So if your observers capture any references, they would be retained by the signal until it terminates, which then the observers would be freed.
