### ISSUE TITLE
RAC5 pod install failed

### ISSUE THREAD

**Issue by mobilinked** [ReactiveCocoa/ReactiveCocoa#3105]
Hi, 

I am migrating project to swift 3, and installing RAC5 branch via CocoaPods

`pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git', :branch => 'RAC5'`

RESULT: 

> Analyzing dependencies
> Pre-downloading: `ReactiveCocoa` from `https://github.com/ReactiveCocoa/ReactiveCocoa.git`, branch `RAC5`
> [!] Unable to find a specification for 'ReactiveCocoa'.

I have tried "rm -rf ~/.cocoapods/repos/master"

Would you please help to suggest the solution? 

Thanks,

**Comment by mdiep** [comment]
I have no idea. I'm not a CocoaPods user. Sorry. Someone else may know.

**Comment by andersio** [comment]
Sorry to say but RAC does not formally support CocoaPods yet. The `RAC5` does not carry any pod spec.

**Comment by mobilinked** [comment]
Thanks the response. 

Right now, my solution is to install the formal reactivecocoa package to my project, then manuall replace the files (with a little changes) by the files of RAC5.
