### ISSUE TITLE
UISearchBar is not available in Objective-c.

### ISSUE THREAD

**Issue by EMakadiya** [ReactiveCocoa/ReactiveCocoa#3109]
I am unable to use this code.

    [[RACSignal merge:@[self.searchBar.rac_textSignal, RACObserve(self.searchBar, text)]] subscribeNext:^(NSString* text) {
		NSLog(@"Text: %@", text);
	}];

Can you please help me.

**Comment by Palleas** [comment]
It seems weird to me to merge what are basically two of the same signal, but maybe I'm mistaken. 🤔
If you're only trying to observe the changes in the content of your UISearchBar, subscribing to  `self.searchBar.rac_textSignal` should be enough..?

Can you tell us more about your issue? How are you using RAC in your app? Carthage or Cocoapods? Also what do you mean by "unable to use this code"? Does it compile?

**Comment by EMakadiya** [comment]
@Palleas I mean there is no category class for UISearchBar in reactivecocoa for objective-c.

**Comment by mdiep** [comment]
There is a PR open for this on ReactiveObjC. https://github.com/ReactiveCocoa/ReactiveObjC/pull/2
