### ISSUE TITLE
No such module Result in import enum Result.NoError

### ISSUE THREAD

**Issue by aadilkeshwani90** [ReactiveCocoa/ReactiveCocoa#3124]
Hi I have just copied the swift library into my project and compiles it. I am getting error on Lifetime.swift : `import enum Result.NoError`

Below is the screenshot for the same : 

![screen shot 2016-08-09 at 11 07 55 am](https://cloud.githubusercontent.com/assets/13597934/17505833/97786dca-5e21-11e6-8a8d-4f6e6feaf1fb.png)

**Comment by andersio** [comment]
Did you follow the steps in [Getting Started](https://github.com/ReactiveCocoa/ReactiveCocoa#getting-started) to fetch all the dependencies?

**Comment by aadilkeshwani90** [comment]
Yes i did and below are the screenshots for the same : 

![screen shot 2016-08-09 at 11 36 54 am](https://cloud.githubusercontent.com/assets/13597934/17506338/afcb48e4-5e25-11e6-8aeb-7db18abda820.png)
![screen shot 2016-08-09 at 11 37 01 am](https://cloud.githubusercontent.com/assets/13597934/17506341/b314bf26-5e25-11e6-8a54-174c4d812ce9.png)

**Comment by andersio** [comment]
Would you mind to try building the `Result-iOS` target, and see if it succeeds? Please specify your Xcode version too.

**Comment by andersio** [comment]
Are you using Xcode 8? Is your project Swift 2.x or Swift 3.0? How do you set it up?

Our `master` branch now targets Swift 3.0, and I saw that your dependency `Cheapjack` is not Swift 3.0 ready. So you would probably want to switch to the `v4.2.2` tag.

**Comment by aadilkeshwani90** [comment]
My xCode Version is Version 7.3 (7D175) and Swift 2.3

**Comment by andersio** [comment]
Our `master` branch now targets Swift 3.0. However, I saw that your dependency `Cheapjack` is not Swift 3.0 ready. So you would probably want to switch to the `v4.2.2` tag.

```
github "ReactiveCocoa/ReactiveCocoa" ~> 4.2.2
```

**Comment by aadilkeshwani90** [comment]
Okay thanks for quick & helpful reply, will surely do that. Thanks once again 👍

**Comment by vishalvirodhia** [comment]
Everything was working fine just Updated to the latest version and getting this error.
