### ISSUE TITLE
Observer Auto-Completion

### ISSUE THREAD

**Issue by jersonperpetua** [ReactiveCocoa/ReactiveCocoa#3126]
I was combing over the milestone issues for RAC 5, and found your discussions regarding the new Lifetime class instructive. Then I realized how a similar (but simpler) mechanism can be used to make sure that observers are completed when they go out of scope.

I apologize for the potentially stupid question, but are there other technical hurdles why this isn't the case, other than observers are value types? Does it even make sense to do this?

I’m thinking of something akin to the following:

```swift
private class _Deinitializer {
  var action: (() -> Void)?
  
  deinit {
    action?()
  }
}

public struct Observer<Value, Error: Swift.Error> {
  public typealias Action = (Event<Value, Error>) -> Void

  public let action: Action
  private let _deinitializer = _Deinitializer()

  public init(_ action: Action) {
    self.action = action
    _deinitializer.action = { action(.completed) }
  }
  ...
}
```

I am asking this since the current observer behaviour does make it inconvenient to use signal pipes in value types:

```swift
struct Value {
  let dependency1: Dependency1
  let dependency2: Dependency2
  let dependency3: Dependency3

  let pipe = Signal<Void, NoError>.pipe()

  // The pipe’s signal will stay alive unless we add a lifetime, and an
  // initializer that binds the observer's lifetime to the latter:

  let lifetime = Lifetime()

  init(dependency1: Dependency1, dependency2: Dependency2,
    dependency3: Dependency3)
  {
    self.dependency1 = dependency1
    self.dependency2 = dependency2
    self.dependency3 = dependency3

    lifetime.ended
      .observeNext(pipe.sendCompleted)

    // This makes it a bit unwieldy though since we could've skipped this custom
    // initializer and used the default member-wise initializer if not for the
    // above binding
  }
}
```

**Comment by andersio** [comment]
I don't get what you want to achieve here. If you expose a lifetime for something, it must have an identity, which means generally it would be a reference type.

`Observer` is made a reference type in #3120, by the way.
