### ISSUE TITLE
Semantics of combineLatestWith:

### ISSUE THREAD

**Issue by pheuberger** [ReactiveCocoa/ReactiveCocoa#3142]
The naming of the function suggests that the latest value of the receiver will be combined with all values out of the given producer, whereas it's the other way around. I'd suggest renaming the function to `combineWithLatestOf` or now perhaps with Swift 3 upon us `combineWithLatest(of:)`.

**Comment by mdiep** [comment]
> The naming of the function suggests that the latest value of the receiver will be combined with all values out of the given producer, whereas it's the other way around.

It's not the other way around. Whenever a new value is sent on either signal, it is forwarded with the latest even from the other signal.

> I'd suggest renaming the function to combineWithLatestOf or now perhaps with Swift 3 upon us combineWithLatest(of:).

I don't think either of those is clearer.

`master`, which will be RAC 5 and targets Swift 3, calls this `combineLatest(with:)`, which is hopefully a little clearer since it emphasizes the combine latest part.

**Comment by pheuberger** [comment]
> It's not the other way around. Whenever a new value is sent on either signal, it is forwarded with the latest even from the other signal.

And wouldn't you say it's formulated the wrong way then? Maybe it's just my perception but when calling `combineLatestWith` on producer1 with producer2 I expect the latest value of producer1 to be combined with all of the values out of producer2. 

See the example from the ReactiveCocoa Sandbox:
```Swift
let producer1 = SignalProducer<Int, NoError>(values: [ 1, 2, 3, 4 ])
let producer2 = SignalProducer<Int, NoError>(values: [ 1, 2 ])

producer1
  .combineLatestWith(producer2)
  .startWithNext { value in
    print("\(value)")
}
```
Which prints
```
(1, 2)
(2, 2)
(3, 2)
(4, 2)
```
So from my point of view it's the other way around, as the last value of producer2 is combined with all the values out of producer1.

**Comment by eimantas** [comment]
It's not really that. The values are combined with latest values of _any_ participants of combination. If `producer2` had more values, they'd be combined with the latest value of `producer1` too.

**Comment by pheuberger** [comment]
Thank you for the reply @eimantas! That helped me wrap my head around it. Seems I completely missed the concept.
I'll close the issue.

Cheers,
Philipp
