### ISSUE TITLE
Why is `-map:` so complicated?

### ISSUE THREAD

**Issue by hfossli** [ReactiveCocoa/ReactiveCocoa#3143]
I'm asking because I want to learn. 

In the latest obj-c implementation it is implemented like this
```obj-c
- (instancetype)map:(id (^)(id value))block {
	NSCParameterAssert(block != nil);

	Class class = self.class;
	
	return [[self flattenMap:^(id value) {
		return [class return:block(value)];
	}] setNameWithFormat:@"[%@] -map:", self.name];
}
```

Why isn't is something simpler like
```obj-c
- (RACSignal *)map:(id(^)(id value))block
{
    return [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        [self subscribeNext:^(id value) {
            id mapped = block(value);
            [subscriber sendNext:mapped];
        } error:^(NSError *error) {
            [subscriber sendError:error];
        } completed:^{
            [subscriber sendCompleted];
        }];
    }];
}
```

I am sure there are good reasons for this decision. I'm asking because I want to learn. 😊

The first commit I found was this by @jspahrsummers (`bind:` was later renamed to `flattenMap:`)
```obj-c
- (instancetype)map:(id (^)(id value))block {
	return [self bind:^(id value) {
		return [self.class return:block(value)];
	}];
}
```

**Comment by hfossli** [comment]
In RxJava they implemented it like this
```
    public final <R> Observable<R> map(Func1<? super T, ? extends R> func) {
        return create(new OnSubscribeMap<T, R>(this, func));
    }
```

https://github.com/ReactiveX/RxJava/blob/ed92ba833f05b7eb04ff7d592040656f9bcbcf32/src/main/java/rx/internal/operators/OnSubscribeMap.java

**Comment by mdiep** [comment]
Because `map` can be implemented with `flatMap` and that reduces the size of the code. The emphasis in RAC has been on keeping the implementation small and simple.

**Comment by hfossli** [comment]
Thanks for answering @mdiep though I must say it's not the answer I expected. 

1. In terms of understanding the code and what's going on I find the `createSignal`-way much simpler than the `flattenMap:`-way. 
1. This is such a fundamental method. The added runtime complexity and excessive callstack is also a bit, well, excessive.

Is size of code the only reason for choosing `flattenMap:` over `createSignal:` in this case? I also notice that the same class is being used for the new signal, but I don't understand why – to conform to `instancetype` as return type?

**Comment by hfossli** [comment]
> While it’s true that shorter is often better, the soul of good communication is clarity.

**Comment by mdiep** [comment]
If you understand `flatMap`, which is a prerequisite for understanding the RAC codebase, then the `flatMap` version is simpler and clearer.

**Comment by hfossli** [comment]
Thanks for getting back to me. 

A few extra lines gives 
- clarity
- understanding without any prerequisites (you don't need to be an expert in RAC)
- more shallow call stack

On such a fundamental method as `map:` I wouldn't throw these wins away. I understand we disagree on this point :)

I didn't quite understand if less code / simpler code is the only motivation for the current implementation or if `self.class` logic plays an important role.

**Comment by CosynPa** [comment]
I think the approach of RAC 4 is better: implement `map` and `flatten`, then `flatMap` is simply derived from the two. (RAC 2: implement `flattenMap`, then `map` and `flatten` is simply derived)

**Comment by hfossli** [comment]
Yes, the swift implementation is good!
