### ISSUE TITLE
Recurring signal

### ISSUE THREAD

**Issue by datwelk** [ReactiveCocoa/ReactiveCocoa#3144]
I have the following code:

```objective-c
- (RACSignal *)addSyncTask:(RACSignal *)task withInterval:(NSTimeInterval)interval
{
    return [[task concat:[[RACSignal empty] delay:interval]] then:^RACSignal *{
        return [self addSyncTask:task withInterval:interval];
    }];
}

- (void)setupFooSync
{
    RACSignal *signal = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        [self.API syncFooWithCompletion:^(id response, NSError *error) {
            [subscriber sendError:error];
            [subscriber sendCompleted];
        }];
        return nil;
    }];
    [self addSyncTask:signal withInterval:60];
}
```

The idea is that once `setupFooSync` is invoked, the sync will occur once every 60 seconds until the containing instance is deallocated. However, with the code above, the sync never occurs. When I change `+createSignal:` to `+startLazilyWithScheduler:`, it occurs only once. I am guessing that since the same sync signal is being reused every time, there needs to be some sort of reset. Any pointers would be greatly appreciated.

**Comment by mdiep** [comment]
```objc
        [self.API syncFooWithCompletion:^(id response, NSError *error) {
            [subscriber sendError:error];
            [subscriber sendCompleted];
        }];
```

You're always sending an error here, which will bail out of the delay. Try sending it only if there's an error.

**Comment by datwelk** [comment]
@mdiep Thanks for the suggestion. Removing the sendError: call does not seem to help unfortunately.

**Comment by datwelk** [comment]
When I change it to this, it works. Is there a cleaner way to start the infinite signal instead of passing an empty subscribeCompleted: block?

```objective-c
- (void)addSyncTask:(RACSignal *)task withInterval:(NSTimeInterval)interval
{
    [[[task then:^RACSignal *{
        return [[RACSignal interval:interval onScheduler:[RACScheduler mainThreadScheduler]] take:1];
    }] repeat] subscribeCompleted:^{
    }];
}
```

**Comment by mdiep** [comment]
You could use `publish:` + `autoconnect`?

You could also change the logic around to be like this:

```objc
[[[[RACSignal
    interval:interval onScheduler:[RACScheduler mainThreadScheduler]]
    map:^(id _) { return task; }]
    concat]
    subscribeCompleted:^{}];
```

(I wrote that in the browser, so it's untested.)
