### ISSUE TITLE
Asynchronous spinner best practice

### ISSUE THREAD

**Issue by ZeroFactor** [ReactiveCocoa/ReactiveCocoa#3146]
I've seen several references to how to control spinners that display while performing network operations, but I haven't come across one that describes the scenarios that I often work with.

The example app has locally cached data that it updates from a network call.  Often this will happen in the background, so the user does not need to take any action.  On it's own, this is a simple series of signal transforms from the network response all the way to the UI update code.

The complication is when I allow the user force a refresh.  Now there is a spinner displaying that is waiting for the full round trip across the network, data transformation, then UI update to disappear.  

A simple implementation of this would just wait for the next UI data update to hide the spinner.  However, there are a couple of complications that can occur with this approach:

- If an error occurs during this forced refresh, I'd like to keep the current data available for display.  This means I can't practically send an error down the signal because that would kill the data feed for the UI.
- Since different processes can cause the data to update in the UI, waiting for the next update means that I may hide the spinner before the forced network operation is complete.  This can create odd scenarios where the display appears to update in response to the user's action, but it then updates again at a later time with new data or even prompts the user that there was an error.

One approach I've thought of is sending a UNID along with the forced refresh request that would bubble all the way back up with the data from the network response.  This would enable the UI to pair the response with the request.  However, this muddies the data signal all the way though the app just for one UI process (there are other observers of this data) and it doesn't really handle the network or transform error scenario.

The best approach I've been able to think of is to send a reference to an Observer along with the forced UI refresh.  The UI ViewController owns this Observer and can use it to kill the spinner or present any errors to the user.  Unfortunately, it seems like this reference would have to be sent all the way down to the network request and even back up to the parser/transformer before an event or error could be sent to it.  In this scenario, the Observer has to be handed off through quite a few classes/operations that have nothing to do with it.  It works, but it makes the connections between the layers much messier than I would hope for.

Am I missing something?  Is there a simpler way that I'm just not seeing?  Any help or insight would be appreciated.

**Comment by mdiep** [comment]
One way to do this is to use an `Action`.

Your `Action`'s block calls the network code that returns a `SignalProducer`. That producer can error without a problem. You can bind the spinner to the `Action`'s `isExecuting` property. You can also watch for errors from the `Action`. The UI can update via a standard path. This also prevents the user from reloading during a reload.

More generally, you probably want to have an object that exposes a `Property` with the latest dataset that you can observe. You probably also want the errors to be available via a property.

**Comment by ZeroFactor** [comment]
Thanks for the info.  Most of the examples I've seen using `Action`s involve managing the `Action` from the `UIViewController`, including the networking code.  However, I did come across this [one example](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2245) of someone spreading the code out across a MVVM architecture that is similar to what I am trying to achieve.  

For my purposes, I hid the `Action` within the ViewModel layer and only exposed `Signal`s, `Observer`s, and properties that the View/ViewController uses.  In particular, I have a property mirroring the `Action`'s `isExecuting` property that you mentioned.  This enables the `UIViewController` to respond to the `Action`'s state change without having to manage the operation of the `Action` itself.
