### ISSUE TITLE
then can be applied just to signals with same ErrorType

### ISSUE THREAD

**Issue by Igor-Palaguta** [ReactiveCocoa/ReactiveCocoa#3148]
If we want to combine with then ```NoError``` with ```NSError``` signal we should use ```promoteErrors```  

```
let s1: SignalProducer<Void, NoError> = ...
let s2: SignalProducer<Void, NSError> = ...
s1.promoteErrors(NSError.self).then(s2).startWithCompleted {}
```

Can we add for ```then``` ```NoError``` specifications, in similar way it was added for flatMap functions #2542 and for timeout #3083

**Comment by mdiep** [comment]
Want to open a pull request to add these overloads?

**Comment by Igor-Palaguta** [comment]
Yes, sure let me try

**Comment by Igor-Palaguta** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3149
