### ISSUE TITLE
Hello Author,My question is rac_willDeallocSignal when to excute?

### ISSUE THREAD

**Issue by SkyHarute** [ReactiveCocoa/ReactiveCocoa#3150]
My english is poor,Maybe some sentence you could not understand.
Old code is:

 [[[NSNotificationCenter defaultCenter] rac_addObserverForName:UIKeyboardWillShowNotification object:nil]
     subscribeNext:^(id x) {
         NSLog(@"%@", x);
     }];

but the code make signal can't be release.So I change the code is:

    [[[[NSNotificationCenter defaultCenter] rac_addObserverForName:UIKeyboardDidShowNotification object:nil]
    takeUntil:[self rac_willDeallocSignal]]
     subscribeNext:^(id x) {
         
         NSLog(@"showKeyboard");
     }];

but rac_willDeallocSignal,this signal when to excute?It is not just in controller's method of 'dealloc',when textFiled is not firstResponder, rac_willDeallocSignal is excuting

**Comment by mdiep** [comment]
The signal will terminate when `self` is about to dealloc—at the very beginning of the `dealloc` process.

Does that answer your question?

**Comment by SkyHarute** [comment]
Thank you for your answer,I know 'The signal will terminate when self is about to dealloc—at the very beginning of the dealloc process',but when I push the controller,do not pop it,so the method of dealloc is not excute.it is just the textfiled  be cancel of the firstResponder.So the notification signal is released by 'rac_willDeallocSignal',So I cant understand why textfiled is not firstResponder can send 'rac_willDeallocSignal'.

**Comment by mdiep** [comment]
In that case, you will need to find another event to terminate the subscription.

**Comment by SkyHarute** [comment]
Thank you for your answer.Maybe just a coincidence that the effect can be reached .
Finally, I would like to use native language to thank you.

谢谢你

**Comment by mdiep** [comment]
Glad I could help!
