### ISSUE TITLE
Best way to implement Promises

### ISSUE THREAD

**Issue by victoraugustolls** [ReactiveCocoa/ReactiveCocoa#3152]
Hi! First of all, great work with ReactiveCocoa. I just started learning it this week and enjoying it a lot. Taking a look at videos, reading documentation and etc.

Now my question...

I wanna substitute PromiseKit in my project for ReactiveCocoa, and for this I need to find the best way to chain async calls like I'm doing right now (something similar), example below:

    LocksmithWrapper.getUserHash()
        .then { hash -> Promise<JSON> in
            let router = UserRouter.GetAddress(hash)
            return AlamofireWrapper.perform(request: router)
        }
        .then { json -> Void in
            let address = Address(withJson: json)
            completion(Result.Success(address))
        }
        .always {
            UIApplication.sharedApplication().networkActivityIndicatorVisible = false
        }
        .error { error in
            completion(Result.Failure(error))
        }

Can anyone point me into the right direction? I'm still feeling kind of lost and think the best way was to ask here, sorry if I'm wrong! And thanks in advance!

**Comment by mdiep** [comment]
While a _promise_ sends exactly 1 value or errors, `Signal`s and `SignalProducer`s send 0-n values and can complete, fail, or interrupt (be cancelled).

If you want to do multiple asynchronous tasks in series, using `flatMap`. If you want to transform a value synchronously, use `map` or `attemptMap`.

You'll need to start to the `SignalProducer` to actually run it.

I _think_ this might be the sort of thing you're looking for based on my understanding of your snippet.

```
LocksmithWrapper.getUserHash()
    .flatMap(.Concat) { hash -> SignalProducer<JSON, NSError> in
        let router = UserRouter.GetAddress(hash)
        return AlamofireWrapper.perform(request: router)
    }
    .map { json -> Address in
        return Address(withJson: json)
    }
    .on(terminated: {
        UIApplication.sharedApplication().networkActivityIndicatorVisible = false
    })
    startWithResult { result in
        completion(result)
    }
```

**Comment by victoraugustolls** [comment]
Thanks for the answer Matt!

So all my functions must have a return type of `SignalProducer<T.Type, NSError>` right? Could this `NSError` be a `ErrorType`? And in the case I want to put more async calls, should I just put more `.map`, like so:

    LocksmithWrapper.getUserHash()
    .flatMap(.Concat) { hash -> SignalProducer<JSON, NSError> in
        let router = UserRouter.GetAddress(hash)
        return AlamofireWrapper.perform(request: router)
    }
    .map { json -> Address in
        return Address(withJson: json)
    }
    .map { address -> User in
        return User(withAddress: address)
    }
    .on(terminated: {
        UIApplication.sharedApplication().networkActivityIndicatorVisible = false
    })
    startWithResult { result in
        completion(result)
    }

**Comment by mdiep** [comment]
> So all my functions must have a return type of SignalProducer<T.Type, NSError> right? Could this NSError be a ErrorType?

Yes and yes. The errors can be any `ErrorType`.

> And in the case I want to put more async calls, should I just put more .map, like so:

If you want more async calls, chain them with `flatMap`. You can read up on the different strategies to choose the correct one.

**Comment by victoraugustolls** [comment]
If any of the methods returns a error, will it break the chain and go to `.on(failed...)`?

**Comment by mdiep** [comment]
> If any of the methods returns a error, will it break the chain and go to .on(failed...)?

Yes

> If so, would I be able to retry from where the chain broke?

You'd need to use `retry` or something inside the `flatMap`.

**Comment by victoraugustolls** [comment]
But if it return an error, wouldn't it just skip the `flatMap` and just go to `.on(failed...)`?

**Comment by mdiep** [comment]
```
producerThatSucceeds
    .flatMap(.Concat) { value in
        return producerThatFailsTheFirstTimeButSuceedsTheSecond
            .retry(upTo: 4)
    }
    .on(failed:...)
```

The inner producer there would fail the first time, be retried, succeed the second time; and the `failed` block would never run.

**Comment by victoraugustolls** [comment]
I think I got everything right now! Thanks for the big help Matt, it was really helpful!

**Comment by victoraugustolls** [comment]
If each of my calls have a different `ErrorType`, I can't `flatMap` them is this the expected behaviour?

Example below:

    AlamofireWrapper.generateRequest(withRouter: router)
    .flatMap(.Concat) { request > SignalProducer<JSON, EncodingError>
        return AlamofireWrapper.perform(request: request).ret
    }
    .flatMap(.Concat) { json -> SignalProducer<JSON, NSError>
        hash = json["data","hash"].string!
        let router = UserRouter.GetInfo(["hash":hash])
        return AlamofireWrapper.perform(request: router)
    }
    .flatMap(.Concat) { json -> SignalProducer<Bool, ErrorType>
        let user = User(withJson: json)
        let account = Account(email: info.email, password: info.password, hash: hash, user: user)
        return KeychainWrapper.save(user: account)
    }
    .on (terminated:  {
            completion(Result.Success(success))
        }

**Comment by mdiep** [comment]
Yup! It makes sense if you think about it. The producer that's created has to have a signal error type. Any errors that probate through to it need to have the same type. Otherwise it would send an error that's not of its error type.

You can use either `flatMapError` to transform errors or `promoteErrors` to contain them in an `enum` or something.
