### ISSUE TITLE
Composing Actions

### ISSUE THREAD

**Issue by aehlke** [ReactiveCocoa/ReactiveCocoa#3155]
I use `Action`s for my API requests, mostly because they provide a handy way of knowing that something is in-flight. This sometimes leads to situations where I need to call an API from within another `Action`, which makes error-handling awkward: the outer action could raise either its own `ActionError`, or it could raise the inner action's `ActionError`, or the inner action's actual error type.

Is there a good way I can "collapse" the inner action's `ActionError` into one that looks like the outer action's? Basically I don't want callers of the outer action to have to worry about both `ActionError.disabled` AND `ActionError.producerFailed(ActionError.disabled)`, for example.

**Comment by aehlke** [comment]
Am I just barking up the wrong tree trying to use Action for API requests?

**Comment by mdiep** [comment]
I would use `SignalProducer`s for API requests and then wrap them with `Action`s when you expose them to users.

There's not currently a way to flatten `ActionErrors` like that. (This would be something to discuss in https://github.com/ReactiveCocoa/ReactiveSwift going forward.)

**Comment by aehlke** [comment]
> I would use SignalProducers for API requests and then wrap them with Actions when you expose them to users.

Makes a lot of sense, thanks.
