### ISSUE TITLE
Make 'Action' a class and sub-classable(?)

### ISSUE THREAD

**Issue by KevinVitale** [ReactiveCocoa/ReactiveCocoa#3159]
I feel I spend a lot of time duplicating the interface of `Action` on my view models; it's especially valuable to have `errors` and `values` available on those view models that perform networking tasks. Before long, most of these networked view models adopt `ActionType` which are simply exposing all of `Action`'s interface computed from its private `action` variable.

What are the reasons for it being a `struct`, and/or what are other developers doing when faced with having to duplicate a lot of the behavior `Action` provides already?

**Comment by mdiep** [comment]
If you're duplicating `Action`, why don't you use it?

It'd probably be useful to post a longer snippet that demonstrates what you're doing. It's very hard to discuss these questions abstractly.

`Action` should maybe be a class, but I think we're unlikely to make it open since subclassing is usually terrible. It'd be better to rethink the abstraction if there's a piece that needs to be reused.

**Comment by KevinVitale** [comment]
> _but I think we're unlikely to make it open since subclassing is usually terrible_

That's fine, and perhaps I'm approaching the problem wrong; my view models often feel like very coordinated, but specific, networked actions. 

For instance: performing an auth call, loading table views with remote resources, and the like, are predicated their UI state on the lifecycle and results of an `Action` — so having to type `viewModel.action.apply`, or `... <~ viewModel.action.{errors,values}` feels weird, in that, I'm exposing the internal of an otherwise opaque interface. 

Obviously, these aren't enough of a case to warrant such a change, so I'm open to other suggestions. Issue can be closed.

**Comment by mdiep** [comment]
FWIW, I wasn't trying to shut down the discussion. I was trying to redirect it from discussing one possible solution to a discussion of the larger problem. Saying "RAC isn't helping me here" is valuable, and I think it's important to discuss those points. I'm just skeptical that subclassing is ever the best solution.
