### ISSUE TITLE
Official support of CocoaPods 

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#3163]
On this year RACDC there was a discussion of official support CocoaPods that was accepted pretty positively, but unfortunately It still not happening. There are 100k+ downloads of ReaciveCocoa through CocoaPods just this week. However, CocoaPods releases are lagging behind. 4.2.2 is not released in CocoaPods yet, but it was released officially 1.5 months ago. Do you plan to reconsider support of CocoaPods anytime soon?

**Comment by mdiep** [comment]
This is discussed in #3000 as well.

Someone just needs to do the work. Pull requests welcome. 😄

**Comment by nikita-leonov** [comment]
@mdiep hunting for a maintainer who can release a Podspec getting harder and harder every time ;(
