### ISSUE TITLE
TO MUCH ISSUES IN MY WORK USE COCOAPODS XCODE 8 BATE6

### ISSUE THREAD

**Issue by hatjs880328** [ReactiveCocoa/ReactiveCocoa#3170]

**Comment by mdiep** [comment]
`v4.2.2` should support Xcode 8ß6. That [should be available on CocoaPods](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3000#issuecomment-244251046).

Swift 3 support is still in progress.

**Comment by hatjs880328** [comment]
if  xcode8 bate6 could use it,tell me plz.

**Comment by ikesyo** [comment]
You should use CocoaPods 1.1.0 beta to be used with Xcode 8. And also if you are expecting Swift 3, current `master` is already updated to GM and not compatible with beta 6.
