### ISSUE TITLE
swift 3 support

### ISSUE THREAD

**Issue by constantineSafronov** [ReactiveCocoa/ReactiveCocoa#3172]
I'm using xCode8 GM, pod 'ReactiveCocoa', '4.2.2'. There are lot of errors in Result an ReactiveCocoa connected with new syntax.

**Comment by andersio** [comment]
Sorry but we do not have any official CocoaPods releases for Swift 3 yet. Our WIP `master` branch has been updated for GM though.

**Comment by constantineSafronov** [comment]
Thank you for the answer.
