### ISSUE TITLE
Start handler called after completion for very short-lived Signals

### ISSUE THREAD

**Issue by mattprowse** [ReactiveCocoa/ReactiveCocoa#3173]
In RAC5, the start handler is called _after_ completion under certain circumstances.

The following code:
```swift
SignalProducer<String, NoError>(value: "String")
    .observe(on: UIScheduler())
    .logEvents()
    .start()
```

Produces this console output:
```
[] next String
[] completed
[] terminated
[] disposed
[] started
```

The same behaviour is seen with SignalProducers that produce a single error. This code:
```swift
enum TestError: Error {
    case anError
}

SignalProducer<(), TestError>(error: .anError)
    .logEvents()
    .start()
```

Produces this console output:
```
[] failed anError
[] terminated
[] disposed
[] started
```

Tested with ReactiveCocoa a135a1f755c5e4435634a5432a0b622eb323f5d7, Xcode 8.0 GM, on macOS 10.12 GM.

**Comment by andersio** [comment]
`observeOn` is asynchronous, and at this point the order of logging event is indeterministic. But the start handler is definitely called before the events, or else you wouldn't be able to receive the events.

**Comment by andersio** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3097

The behavior of `started` had been changed, and `starting` was introduced for the original pre-start behavior.

**Comment by mattprowse** [comment]
Thanks for the quick response, and for clarifying the new behaviour!
