### ISSUE TITLE
Multiple Swift 3.0 build issues

### ISSUE THREAD

**Issue by garethcurtis** [ReactiveCocoa/ReactiveCocoa#3188]
Hi there,

I've just updated to Swift 3.0 and I'm having some trouble getting ReactiveCocoa going. I was using it as a Pod but understand that's not ready yet, so have used Carthage instead. I'm getting the following errors. Any ideas please? Have I missed something?

I believe we last had it compiling with Swift 3.0 in Xcode 8.0 Beta 6.

Thanks,

Gareth.

![screen shot 2016-09-14 at 16 09 19](https://cloud.githubusercontent.com/assets/9380217/18517875/c8d6e4a6-7a95-11e6-923e-883365e17303.png)

**Comment by andersio** [comment]
You would need to import `ReactiveSwift` too.
