### ISSUE TITLE
NSPhotoLibraryUsageDescription key issue from apple during submission.

### ISSUE THREAD

**Issue by amol-c** [ReactiveCocoa/ReactiveCocoa#3190]
Issue:

Received an email from Apple for rejecting the binary.

```
This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.
```

Solution:

To get around the above submission issue, i had to comment out `UIImagePickerController+RACSignalSupport.h` and remove the files from the target. 

I was wondering if there is a better way, since our app doesn't use the `UIImagePickerController` to exclude the above extension.

Thanks

**Comment by mdiep** [comment]
The Objective-C code has been moved to https://github.com/ReactiveCocoa/ReactiveObjC/, which will solve the issue for the moment. But it may recur when we incorporate the bindings from Rex.

I'm not aware of a way to improve this. I'd file a radar with Apple about it and include a dummy description in your app.

**Comment by amol-c** [comment]
Yea. That's what I ended up doing.

Thanks.

**Comment by sfla** [comment]
Oh. My. God. This caused me so much headache! Thanks.

**Comment by axelguilmin** [comment]
As a workaround, I forked the repository and removed `UIImagePickerController+RACSignalSupport`. In my podfile :
`pod 'ReactiveObjC', :git => 'https://github.com/axelguilmin/ReactiveObjC.git'`
