### ISSUE TITLE
takeUntilReplacement `complete` behavior

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#3191]
Currently, takeUntilReplacement completes only when replacement completes. If source completes, chain stays as is. This kinda strange, as a replacement, in theory, may never complete. For example, I was thinking that following structure is totally legit:
```
producer.takeUntilReplacement(sideffectErrors)
```

Errors are optional, while producer should perform and complete if everything is fine. 
I expected from takeUntilReplacement following behavior:
Complete producer if source completed but was not replaced, _or_ if it was replaced by the second prodcer and it was completed? 

Also, what would be a preferred way to implement structure as explained above with a currently available operators and behaviors?

**Comment by mdiep** [comment]
The best way I can do this would by to use `replayLazily`.

```swift
let replayed = producer.replayLazily(upTo: 0)
return replayed.take(untilReplacement: sideffectErrors).take(until: replayed)
```

Ugly, but I think it has the semantics you're looking for. 😕 

You might need to examine a larger portion of your code to find a better way to represent it.

**Comment by nikita-leonov** [comment]
Oh... isn't replayLazily will be removed in further releases? I remember some serious discussions on RACDC about this. Also about takeUntilReplacement, I assume it is hard to change the behavior with such big amount of consumers but isn't suggested flow meaningful? 
ps Closing ticket, as in general question answered, the rest is just a theoretical exercise.

**Comment by nikita-leonov** [comment]
here is a final "answer" that I have in case if someone will need it:
```
let replayed = producer.replayLazily(upTo: 0)
let replayedCompleted = replayed.materialize().filter { $0.isTerminating }.map(() |> const) //In case  replayed has value & error.
return replayed.take(untilReplacement: sideffectErrors).take(until: replayed)
```

**Comment by NachoSoto** [comment]
> Oh... isn't replayLazily will be removed in further releases? I remember some serious discussions on RACDC about this.

Nope, that probably was `SignalProducer.buffer`, which is now gone.

**Comment by nikita-leonov** [comment]
@NachoSoto right, my bad. Anyway, this use of replayLazily is the first occurrence of use, in our code fully RAC huge code base, not sure is it good or bad.
