### ISSUE TITLE
MutableProperty not found in RAC 5

### ISSUE THREAD

**Issue by hermannkuschke** [ReactiveCocoa/ReactiveCocoa#3192]
Hi guys

We just tried to update to RAC 5, but it seems like there is no MutableProperty to be found. All our uses of MutableProperty gives error messages. We went and checked online and it seems like the file Property.swift in https://github.com/ReactiveCocoa/ReactiveCocoa/tree/master/ReactiveCocoa/Swift cannot be found. Could you please inform me as quickly as possible as to what is going on?

Regards,

Hermann Kuschke

**Comment by andersio** [comment]
`MutableProperty` is available in [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift), which is now one of the dependency of ReactiveCocoa.

**Comment by hermannkuschke** [comment]
Thank you for your quick reply.

**Comment by andersio** [comment]
Please be noted that the Objective-C API, and the bridge between ReactiveObjC and ReactiveSwift would receive a similar deal (#3182). If your codebase depend on them, you might have to include them as separate dependencies.

**Comment by justinvallely** [comment]
Hi guys,

I'm having the same issue as @hermannkuschke. Looks like ReactiveSwift is being installed with ReactiveCocoa via cocoapods. I'm still getting the build errors about MutableProperty not being found. Am I missing a step? Thank you.

**Comment by hermannkuschke** [comment]
@justinvalley what we did was to not install them through cocoapods, but to instead include them as dependencies. We then manually ensured that ReactiveSwift's syntax conformed to that of Swift 3. This is just temporary though, but it works.

**Comment by andersio** [comment]
The podspec would include ReactiveSwift for you. But in your code, you would need to explicitly import ReactiveSwift, since ReactiveCocoa does not reexport ReactiveSwift at this moment.

**Comment by justinvallely** [comment]
That solves the mystery. Thanks gents!
