### ISSUE TITLE
Xcode8 RACMulticastConnection.h file not found

### ISSUE THREAD

**Issue by Wilson2014** [ReactiveCocoa/ReactiveCocoa#3196]
My project's written with Swift.All works fine in Xcode 7.x. After upgrading Xcode 8, it keeps getting error which says 'RACMulticastConnection.h file not found'. I have set the 'Use legacy swift language version' to YES but it doesn't work. Anyone can show some ideas?
![snip20160918_8](https://cloud.githubusercontent.com/assets/10293397/18613794/3a44ac4c-7db4-11e6-98e8-3ae4006d7441.png)

**Comment by xwbeast** [comment]
My project's written with Objective-C, and get the same error...

**Comment by arielpollack** [comment]
Mine is objc & swift and `metamacros.h` is missing...
![image](https://cloud.githubusercontent.com/assets/1862153/18616234/7826fed2-7dc0-11e6-99f2-c2b26b755ccb.png)

**Comment by arielpollack** [comment]
I've installed ReactiveCococa with Carthage instead of CocoaPods and it worked fine. maybe there's something CocoaPods is missing...

**Comment by mdiep** [comment]
The Objective-C code has been moved to https://github.com/ReactiveCocoa/ReactiveObjC.

I have no idea how the podpsec is set up. But this sounds like a CocoaPods issue.

**Comment by sunxiaoju** [comment]
@Wilson2014 @xwbeast     
 I also encountered this problem. Will you solve it, how to solve. Help!!!!!

**Comment by sunbohong** [comment]
@sunxiaoju Are you user Swift 3.0?

**Comment by sunxiaoju** [comment]
@sunbohong  yes

**Comment by sunbohong** [comment]
@sunxiaoju  As a temporary solution, I use submodules in my project.

**Comment by sunxiaoju** [comment]
@sunbohong  thank you, I try

**Comment by KhaHC** [comment]
hi @Wilson2014 ,
I have the same same issue when upgrade XCode 8, I fixed by update cocoapod  [https://cocoapods.org/?q=reactivecocoa](url):
# Xcode 7 + 8
$ sudo gem install cocoapods --pre

Hope that help,
