### ISSUE TITLE
Reactive Cocoa for Swift 3.0

### ISSUE THREAD

**Issue by alijawadGGS** [ReactiveCocoa/ReactiveCocoa#3201]
I am updating a project from Swift 2.x to 3.0. I have ReactiveCocoa version v4.2.2 installed via Carthage. To update reactive cocoa I have updated my cart file as

github "ReactiveCocoa/ReactiveCocoa" "master"
When I run command Carthage update, it gives the following error in terminal:

No tagged versions found for github "ReactiveCocoa/ReactiveSwift"
How do I fix this?

**Comment by alijawadGGS** [comment]
Following link helped solve the issue

https://github.com/Carthage/Carthage/releases/tag/0.15.1

**Comment by ainopara** [comment]
try
```
github "ReactiveCocoa/ReactiveObjc" "master"
github "ReactiveCocoa/ReactiveObjcBridge" "master"
github "ReactiveCocoa/ReactiveSwift" "master"
```
