### ISSUE TITLE
XCode 8.0 error

### ISSUE THREAD

**Issue by sunxiaoju** [ReactiveCocoa/ReactiveCocoa#3204]
![image](https://cloud.githubusercontent.com/assets/13308871/18696851/afd58d46-7fee-11e6-9e4e-59b9e4dc64c3.png)

What is the problem in Xcode8？？help

**Comment by mdiep** [comment]
The Objective-C codebase has been moved out of this repository to https://github.com/ReactiveCocoa/ReactiveObjC. I can't speak for whether the podspec continues to work because we don't maintain it.
