### ISSUE TITLE
Swift 2.3 migration with cocoapods

### ISSUE THREAD

**Issue by suparngp** [ReactiveCocoa/ReactiveCocoa#3207]
I am using cocoapods and the community podspec for version 4.2.2 . I saw that the latest 4.2.2 release added support for Swift 2.3. However, XCode8 is still complaining about Flatten.swift (which I also think was fixed in tag 4.2.2).

**Comment by ikesyo** [comment]
You shoud update to CocoaPods 1.1.0 to be used with Xcode 8: `gem update cocoapods --pre`
