### ISSUE TITLE
XCode 8.0 error

### ISSUE THREAD

**Issue by DDCry** [ReactiveCocoa/ReactiveCocoa#3208]
![2016-09-22 12 05 25](https://cloud.githubusercontent.com/assets/18590205/18736770/0313fe56-80bd-11e6-828f-1c4e6075448b.png)
![2016-09-22 12 14 29](https://cloud.githubusercontent.com/assets/18590205/18736895/2ed7e330-80be-11e6-991f-8fbb61f67576.png)

What is the problem in Xcode8？？help

**Comment by hermannkuschke** [comment]
Hi, I'm not proposing this as a solution, but we imported the framework (not using pods) into our project and then compiled it ourselves. We didn't have the issue that you're describing so you might want to give that a try.

**Comment by rahthakor** [comment]
I'm also getting error while using carthage 
Module compiled with Swift 2.3 cannot be imported in Swift 3.0: /Volumes/Workspace/Personal Projects/FrameworkPractice/Carthage/Build/iOS/ReactiveCocoa.framework/Modules/ReactiveCocoa.swiftmodule/x86_64.swiftmodule

When I build xcworkspace separately then it succeeds build.
But not able to build once I embed them into binary into my project using standard carthage procedure it gives me above error.

**Comment by eltonf** [comment]
@hermannkuschke Did you also have to update the code to Swift 3.0 syntax after importing it into your project? I'm also having the same issue where I can't use this project via Carthage.

**Comment by ikesyo** [comment]
RAC's Swift 3 supoort is still in progress. You should check the master branch of this repo and https://github.com/ReactiveCocoa/ReactiveSwift. AFAIK there is no podspec which can be used for Swift 3 yet.

**Comment by hermannkuschke** [comment]
@eltonf, we did not need to convert the RAC code to Swift 3. We simply imported it as per the instructions on the RAC GitHub repo, but we did also separately import the latest versions ReactiveSwift as well as Result. The version of Result in the podspec of RAC (please note that the podspecs are unofficial) is too low to be compatible with Swift 3. Does this help somehow?
