### ISSUE TITLE
RACSignal in RAC 5?

### ISSUE THREAD

**Issue by hermannkuschke** [ReactiveCocoa/ReactiveCocoa#3209]
Hi guys,

Could you tell me where RACSignal went?

**Comment by kaybutter** [comment]
It's in the [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC) repository.

**Comment by tatlacas** [comment]
Hi @kaybutter , is there an alternative to using RACSignal while using ReactiveCocoa repo?

**Comment by kaybutter** [comment]
In swift you'd probably want to use the Signal or SignalProducer types. They're in the ReactiveSwift repo, but they are a direct dependency of ReactiveCocoa so you should already have them.
