### ISSUE TITLE
Build with "Use Legacy Swift Language Version" by "No" option, build failed:

### ISSUE THREAD

**Issue by jjksam** [ReactiveCocoa/ReactiveCocoa#3212]
I have a project that need to use swift 3.0 and when I tried to build with 3.0, the ReactiveCocoa project give me a bunch of errors. I'm using Carthage to build it. And I tried to build from the workspace, it also fail. Any plan to upgrade to Swift 3.0 full support ? I tried to use Xcode's convert, but it only give me a lot more errors.

**Comment by ikesyo** [comment]
This would be a duplicate of #3211.

RAC's Swift 3 supoort is still in progress. You should check the master branch of this repo and https://github.com/ReactiveCocoa/ReactiveSwift.
