### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by v-silin** [ReactiveCocoa/ReactiveCocoa#3213]
Hi.

Do you have any plans about swift 3?

Best regards.

**Comment by andersio** [comment]
`master` works with Swift 3, but the release is still WIP.

**Comment by v-silin** [comment]
Great, thanks!)

**Comment by v-silin** [comment]
Can't use master branch with cocoapods:
Pre-downloading: `ReactiveCocoa` from `https://github.com/ReactiveCocoa/ReactiveCocoa.git`
[!] Unable to find a specification for 'ReactiveCocoa'.

Could you help me?
