### ISSUE TITLE
Swift 3.0 Support

### ISSUE THREAD

**Issue by chrisdhaan** [ReactiveCocoa/ReactiveCocoa#3214]
The framework README.md suggests that ReactiveCocoa supports Swift 3.0 but when I installed the framework via Carthage it seems it's build using Swift 2.X. Is there a timeline for when this framework may be updated for Swift 3.0?

**Comment by mdiep** [comment]
The `master` branch targets Swift 3, but there hasn't been a release yet.

You can use the master branch with Carthage:

```
github "ReactiveCocoa/ReactiveCocoa" "master"
```

But please be aware that there may still be some breaking changes.
