### ISSUE TITLE
How can I use Action on button action to execute a method.

### ISSUE THREAD

**Issue by pradeepb28** [ReactiveCocoa/ReactiveCocoa#3218]
I am trying to use RAC's Action for executing a method in Swift upon clicking on the button. But I dont see any basic example how to use it. Any help is appreciated. Thanks.

**Comment by pradeepb28** [comment]
```let action = Action<AnyObject?, Void, NoError> { _ in
  print("action")
return SignalProducer.empty
}

let cocoaAction = CocoaAction(action) { _ in }
button.addTarget(cocoaAction, action: CocoaAction.selector, forControlEvents: .TouchUpInside)```

I tried the above snippet, it didn't work.

**Comment by sharplet** [comment]
What exactly didn't work? At the very least, it looks like you'll need to add explicit type parameters for `Action` to get your example to compile.
