### ISSUE TITLE
Improve performance of `setNameWithFormat:`

### ISSUE THREAD

**Issue by hfossli** [ReactiveCocoa/ReactiveCocoa#3220]
Close this issue at will. I felt it was cleaner to continue the discussion in a new thread instead of discussing in a closed thread from 2014 (#1083).

I think I found a way to improve the performance of `setNameWithFormat` using blocks. Memory and performance could potentially be improved in debug builds. I haven't had any problems with this my self, but reading that issue thread #1083 made me think it's a problem for some people.

Well, instead of creating the strings directly we can defer (and cache) this operation:
https://gist.github.com/hfossli/3682cd8769bd4d167f6e05ee4b34af8c

**Comment by hfossli** [comment]
I wrote this test. And my prototype passes that test fine. This should mean better performance and lower memory usage.
```
@interface Foo : NSObject
@property (nonatomic, assign) int descriptionRequestedCount;
@end

@implementation Foo

- (NSString *)description
{
    self.descriptionRequestedCount++;
    return @"<Foo 0xFOOBAR>";
}

@end

@interface RACSignalTest : XCTestCase
@end

@implementation RACSignalTest

- (void)testFooIsolated
{
    Foo *foo = [Foo new];
    XCTAssertTrue(foo.descriptionRequestedCount == 0, @"");
    [foo description];
    XCTAssertTrue(foo.descriptionRequestedCount == 1, @"");
    [foo description];
    XCTAssertTrue(foo.descriptionRequestedCount == 2, @"");
}

- (void)testWithSignal
{
    Foo *foo = [Foo new];
    
    RACSignal *signal = [[RACSignal new] someOperatorWithObject:foo];
    XCTAssertTrue(foo.descriptionRequestedCount == 0, @"");
    XCTAssertEqualObjects([signal name], @"transformed using `someOperatorWithObject` with object <Foo 0xFOOBAR>");
    XCTAssertTrue(foo.descriptionRequestedCount == 1, @"");
    XCTAssertEqualObjects([signal name], @"transformed using `someOperatorWithObject` with object <Foo 0xFOOBAR>");
    XCTAssertTrue(foo.descriptionRequestedCount == 1, @"");
}

@end
```

**Comment by andersio** [comment]
This should belong to ReactiveObjC now. :)

**Comment by hfossli** [comment]
Ah, sorry and thanks!

**Comment by hfossli** [comment]
Moved to https://github.com/ReactiveCocoa/ReactiveObjC/issues/6
