### ISSUE TITLE
Question: Swift, ObjC, Bridging, Cocoa libraries

### ISSUE THREAD

**Issue by v-silin** [ReactiveCocoa/ReactiveCocoa#3222]
Hi.

Could you please provide some details about these 4 libraries:
1) https://github.com/ReactiveCocoa/ReactiveCocoa
2) https://github.com/ReactiveCocoa/ReactiveSwift
3) https://github.com/ReactiveCocoa/ReactiveObjCBridge
4) https://github.com/ReactiveCocoa/ReactiveObjC

Are they work together or independently?

As I understand, ReactiveCocoa is the main lib and the others are parts of it. Am I correct?

Thanks.

Best regards,
Vasili Silin.

**Comment by mdiep** [comment]
Please see https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3118/files.
