### ISSUE TITLE
Why did I got Result Library at version "2.1.3" by using Carthage?

### ISSUE THREAD

**Issue by baei2048** [ReactiveCocoa/ReactiveCocoa#3224]
Hi,

I am switching my project to Swift 3.0, however I found the Result Library which required by RAC is still "2.1.3". 

My Cartfile only has this line github "ReactiveCocoa/ReactiveCocoa"

Is there anything I did wrong with Carthage.

Thanks.

**Comment by iv-mexx** [comment]
Not sure about this, but seems like Carthage takes the latest release if you dont specify anything, so for me at least it checks out ReactiveCocoa at [v4.2.2](https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/v4.2.2) which is still for Swift 2.3, and which requires Result 2.1.3.

Try specifying the master branch of ReactiveCocoa like this
```
github "ReactiveCocoa/ReactiveCocoa" "master"
```

For me, this checks out Result at 3.0.0 as expected.

**Comment by iv-mexx** [comment]
Keep in mind that ReactiveCocoa is not yet "done" for Swift 3, have a look at [this comment](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3223#issuecomment-249610952) for some useful information.

**Comment by baei2048** [comment]
Thank you.
