### ISSUE TITLE
你好 请问怎么运行demo啊？没搞明白呢

### ISSUE THREAD

**Issue by hhb19900618** [ReactiveCocoa/ReactiveCocoa#3227]

**Comment by andersio** [comment]
If what you mean by "demo" is the _Playground_, you need to [setup your local copy property by fetching all the dependent framework](https://github.com/ReactiveCocoa/ReactiveCocoa#getting-started).

Then you can open the **ReactiveCocoa.xcworkspace**, and follow the instructions written at the top of the _Playground_ (i.e. building the macOS targets of Reactive* and Result.

**Comment by wwwyiqiao** [comment]
去看SwfitGoal
