### ISSUE TITLE
Hello, I am using use_frameworks!Pod 'ReactiveCocoa', '- >' out 'after installation, t

### ISSUE THREAD

**Issue by sunnycn2013** [ReactiveCocoa/ReactiveCocoa#3228]
Hello, I am using use_frameworks!Pod 'ReactiveCocoa', '- >' out 'after installation, there are a large number of swift error, excuse me this how to solve

**Comment by andersio** [comment]
If you are looking for RAC for Swift 2.x, please use `~> 4.2`. If you are looking for RAC for Swift 3, I am sorry to tell the support is still a work-in-progress.

https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3219

**Comment by allenlinli** [comment]
Can I use it only for Obj-C (without Swift lib) via Cocoapod?

**Comment by andersio** [comment]
You can still use `~> 4.2`, which includes the ObjC APIs and Xcode 8 support. Note that the ObjC APIs are now hosted separately in [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC), which you may want to target once there is a release (and CocoaPods support).

**Comment by allenlinli** [comment]
CocoaReactive 4.2 forces me to use the library with Swift, I can not use ObjC only. And if I include Swift library by "use_frameworks!", I need to convert to Swift 3.0.

It said:
"[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: ReactiveCocoa and Result".

I would try ReactiveObjC instead. Thank you for supporting.

**Comment by andersio** [comment]
Just in case you missed it: ReactiveObjC has an official podspec now. :)
