### ISSUE TITLE
`collect()` not sending its last aggregated signal

### ISSUE THREAD

**Issue by hery** [ReactiveCocoa/ReactiveCocoa#3231]
I have 2 `flatMap` chained, at the end of which I `collect()` an array of `SignalProducer` results. When I observe my signals directly, `collect()` happens properly and the aggregated signal is sent.
By properly, I mean that it sends all `completed`, `terminated`, and `disposed` event.

The issue is when I add a location update `SignalProducer` at the beginning of the chain, and map the 2 `flatMap` to it, then the last `flatMap` has all its `next` events properly firing, but somehow `collect()` doesn't fire the aggregated signal. All final 3 events fired in the case above are not sent here.

What could the location update `SignalProducer` be messing up? Could it be the signal is observed on a different queue? Or a deallocation issue? What are reasons `collect()` does not send any event? Could a bad network connection result in no event being sent? I tried to debug the stream using `on()` and `logEvents()`, but nothing seems to be sent.

Here is the general structure of the broken chain with the location updates signal producer:

        locationUpdateSignalProducer()
            .flatMap(.Latest) { (result) -> SignalProducer<(NSData, NSURLResponse), NSError> in
                return firstSignalProducer(locationResult)
            }
            .flatMap(.Latest) { (data, response) -> SignalProducer<(NSData, NSURLResponse), NSError> in
                // Here I have an array of `SignalProducers` that I'll need to `collect()`
                let producers = data.map { (value) -> SignalProducer<(NSData, NSURLResponse), NSError> in
                    return secondSignalProducer(value)
                }
                return SignalProducer.merge(producers)
            }
            .logEvents() // for debugging
            .collect() // this does not send an event
            .observeOn(UIScheduler())
            .startWithResult { (result) in // this is never printed
                print(result)
        }

**Comment by mdiep** [comment]
It sounds the location update producer isn't completing, which would prevent the `flatMap`s from completing and prevent the `collect` from sending anything (since it can't send anything until completion).

**Comment by hery** [comment]
Thanks! That makes sense, I may have not properly created my signal producer. Am I missing something below? My understanding was that the `toSignalProducer()` method handles sending these events.

I have this dynamic variable:

    dynamic var currentLocation:CLLocation?

That I observe as follow:

    func locationSignal() -> SignalProducer<AnyObject?, NSError> {
        return self.rac_valuesForKeyPath("currentLocation", observer: self)
            .toSignalProducer()
    }

**Comment by mdiep** [comment]
That handles sending those events, but `rac_valuesForKeyPath` only completes when the object deallocates.

**Comment by hery** [comment]
That makes sense, and I realized that by definition, the location update signal producer is not supposed to end, since these are continuous  🙉
