### ISSUE TITLE
Parameterize `CocoaAction` with its assumed sender type.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3239]
Implementation: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3210/commits/21e3ae2e6aabd9ad692ba066886c6b05ca38c9a9#diff-6760ae63506f0524be20defc2a26e3b8R8

The documentation said that:

> You must cast the passed in object to the control type you need since there is no way to know where this cocoa action will be added as a target.

While it is true that we cannot constraint how `CocoaAction` is added as a target, we usually have in mind what it _expects_ to be bond with.

e.g.
```
// The initializer can infer `Sender` from `button.reactive.pressed`.
button.reactive.pressed = CocoaAction(action) { button in }
```

It is for sure a `UIButton`. So why not make `CocoaAction` be generic over its expected sender type, so that the construction becomes typesafe?

```
class CocoaAction<Sender> {
    init<Input, Output, Error>(_ action: Action<Input, Output, Error>, inputTransform: (Sender) -> Input)
}
```

The old behavior can still be exhibited by `CocoaAction<AnyObject>`.

**Comment by mdiep** [comment]
That seems reasonable to me. 👍
