### ISSUE TITLE
How to use  'Carthage' to download RAC5

### ISSUE THREAD

**Issue by cly6226700** [ReactiveCocoa/ReactiveCocoa#3240]
I use  Carthage with github "ReactiveCocoa/ReactiveCocoa" to download RAC5 ,but I get
"Build/iOS/Result.framework/Result compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64"

**Comment by andersio** [comment]
Please target the `master` branch for the time being. We do not have any (pre-)release for Swift 3.0 yet.
