### ISSUE TITLE
How  to use Macro  in Swift???

### ISSUE THREAD

**Issue by hatjs880328** [ReactiveCocoa/ReactiveCocoa#3241]
How  to use Macro  in Swift???
FOR EXAMPLE:(OC)
    RACObserve(self, userName);

**Comment by mdiep** [comment]
The macros aren't compatible with Swift.

**Comment by iv-mexx** [comment]
If for some reason you have to use RAC 2.5 with Swift, [here's how you can do that similar to the macros](http://blog.scottlogic.com/2014/07/24/mvvm-reactivecocoa-swift.html#bindings).

Keep in mind that you don't need the `~>` operator anymore, that was just used a short time in RAC 3 before Swift introduced Protocol Extensions.

However, if you are able to use RAC > 2.5, you'd better use `Signal` and `SignalProducer` in your Swift Code, `RACSignal` in ObjC and [bridge between these](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/Documentation/ObjectiveCBridging.md) using [ReactiveObjCBridge](https://github.com/ReactiveCocoa/ReactiveObjCBridge)
