### ISSUE TITLE
combineLatest total amount of results is affected by order of arguments

### ISSUE THREAD

**Issue by nikita-leonov** [ReactiveCocoa/ReactiveCocoa#3244]
Currently `combineLatest` with following inputs may provide different amount of results:
```
let p1 = SignalProducer<String, NoError>(values: ["foo"])
let p2 = SignalProducer<Int, NoError>(values: [1, 2, 3])
```

Results depends on an order of arguments.
`combineLatest(p1, p2).startWithResult { print($0) }` results:
```
.Success(("foo", 3))
```

`combineLatest(p2, p1).startWithResult { print($0) }` results:
```
.Success((1, "foo"))
.Success((2, "foo"))
.Success((3, "foo"))
```

This reproducible for RAC 4.2.2 and it differs from an example available in RAC Marbles — http://neilpa.me/rac-marbles/#combineLatest 

Is it expected behavior? Should not it provide the same amount of results, but just an order of values in a tuple should be different? It seems that current operation can be used to write really fragile code.

**Comment by mdiep** [comment]
This is true only because you're using `SignalProducer(values:)`, which sends all values immediately upon subscription. If you were to use pipe instead, you'd see the expected results.

The given example is basically this:

```swift
extension SignalProducer {
	static func pipe() -> (SignalProducer, ProducedSignal.Observer) {
		let (signal, observer) = ProducedSignal.pipe()
		let producer = SignalProducer(signal: signal)
		return (producer, observer)
	}
}

let (p1, p1o) = SignalProducer<String, NoError>.pipe()
let (p2, p2o) = SignalProducer<String, NoError>.pipe()
combineLatest(p1, p2).startWithResult { print($0) }

p1o.send(value: 1)
p1o.send(value: 2)
p1o.send(value: 3)
p2o.send(value: "foo")
```

If you send the _foo_ upfront, then you get 3 results.

```swift
p2o.send(value: "foo")
p1o.send(value: 1)
p1o.send(value: 2)
p1o.send(value: 3)
```

Also, future issues regarding `SignalProducer` should be filed on https://github.com/ReactiveCocoa/ReactiveSwift.
