### ISSUE TITLE
Merge two SignalProducer's with different type

### ISSUE THREAD

**Issue by Unihilator** [ReactiveCocoa/ReactiveCocoa#3246]
I want to merge two signalProducer and handle their results on completion both. These signal producers are with a different type. Example:
```swift
SignalProducer<String?, NoError> 
SignalProducer<Int?, NoError>
```
Combine latest do the thing but it execute one after another.
Thank you so much guys

**Comment by mdiep** [comment]
You'll need to first `map` or `flatMap` them into `SignalProducer`s with the same types. Then you can merge the mapped producers.
