### ISSUE TITLE
.collect method with not ordered results

### ISSUE THREAD

**Issue by Unihilator** [ReactiveCocoa/ReactiveCocoa#3247]
```swift
return SignalProducer.merge([OneSignal.getSignal(productId), TwoSignal.getSignal(recentlyViewed), ThreeSignal.getSignal(recentlyViewed), FourthSignal.getSignal(trendProductsPayload)])
        .collect()
```
Code above returns array of results in unexpected order(in order FirstFinished-FirstInArray). Is there a way to order result in way I wrote it earlier? Thanks

**Comment by mdiep** [comment]
Merge doesn't specify order, as you're discovering. Check out `zip` and `combineLatest`.

**Comment by Unihilator** [comment]
`combineLatest` - good choice in case of ordering. But the problem is in request execution. It executes each producer one after previews signal completes(as far as I understand). 
Will try zip. Thanks

**Comment by Unihilator** [comment]
Zip concatenate it into pairs.

**Comment by andersio** [comment]
You may transform the results as `(Int, Value)` with an integer literal specifying the expected order. Then you can reduce the collected, unordered `[(Int, Value)]` array into the desired order of yours.

**Comment by Unihilator** [comment]
Good idea @andersio . I have found another way.. I have created four mutable properties and bind it like this:
```swift
prop1 <~ OneSignal.getSignal(productId)
prop2 <~ TwoSignal.getSignal(productId) 
...
```

and then I combineLatest them to get the result when all of them finished(have changed their properties):
```swift
let allCombined = combineLatest(prop1.signal, prop2.signal, ...)
        allCombined.observe{[weak self] event in
        
```
