### ISSUE TITLE
when to support swift 3.0?

### ISSUE THREAD

**Issue by arden** [ReactiveCocoa/ReactiveCocoa#3248]
when to support swift 3.0?

**Comment by andersio** [comment]
`master` already supports 3.0. We'd likely have a prerelease once #3210 is landed.

**Comment by Denis1992** [comment]
@andersio
Only Carthage or Pod too?
Thank for answer.

**Comment by andersio** [comment]
We have Pods support pending.

**Comment by bitomule** [comment]
Is there a way to add master version using cocoapods or help getting a cocoapods version running?

**Comment by andersio** [comment]
Try to use #3219.

**Comment by bitomule** [comment]
Thanks @andersio , used branch add-podspec and seems to work. Hope it gets merged soon.

**Comment by Dominionys** [comment]
@bitomule Can you show your podfile?

**Comment by bitomule** [comment]
Sure!

Here's the ReactiveCocoa line:

`pod "ReactiveCocoa", :git => "https://github.com/ReactiveCocoa/ReactiveCocoa.git", :branch => 'add-podspec'`
