### ISSUE TITLE
Syncronized signal execution

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [ReactiveCocoa/ReactiveCocoa#3254]
Hi,

I've a cold signal that gets subscribed several times. However, since the signal code is not thread safe and need to make sure that execution is sequencial. This means that subscription code should execute by each subscription but only one at once.

What's the best pattern for this ? I'm still tight to objective-c version :(

Thanks in advance,

**Comment by andersio** [comment]
If you need to serialise signals and producers, `flatten` and `flatMap` with the concat strategy sounds like what you'd need.

**Comment by vitorhugomagalhaes** [comment]
That would work but it does not solve concurrent execution of the subscription code which is the problem i have right now.

**Comment by andersio** [comment]
Oh, sorry. I thought you mean serialising signals. ;)

You can use `startOn` (RAC 4.x) or `start(on:)` (RAC 5.x), which takes a Scheduler that does the work for you.

**Comment by vitorhugomagalhaes** [comment]
Example code:

`        return licensingService.update().then({ () -> RACSignal! in
            return self.licensingService.revision().flattenMap({ (argument) -> RACStream! in
                let number = argument as! NSNumber
                self.licensingRevision = number.integerValue
                return self.fetchLicensedProductOffers().flattenMap({
                    self.licensingProductOffers = $0 as? LicensingProductOffers
                    return RACSignal.`return`(self.apiCatalog).map(self.mapCatalog).map({
                        self.catalog = $0 as? SSCatalogProtocol
                        return $0
                    })
                })
            })
        })`

The goal is to make sure that the signal path (then, flattenMap, etc) executes atomically per each subscriber.

My understanding of the startOn indicates that it does not enforce such atomicity. 

Correct ?

BR,

**Comment by andersio** [comment]
If I understand you correctly, you want to ensure mutual exclusion in the returned producer. I believe there isn't a standard operator that covers this specific case yet.

You may choose to wrap your producer with semaphores or other sync primitives, or you might hack the behaviour using `concat`.

```
let (queue, queueObserver) = Signal<SignalProducer<String, NoError>, NoError>.pipe()
let queueOutput = queue.flatten(.concat)

func serialized<U, E>(_ work: SignalProducer<U, E>) -> SignalProducer<U, E> {
  return SignalProducer<String, NoError> { observer, disposable in
    queueObserver.send(value: work
      .on(starting: { disposable += queueOutput.observe(observer) },
          terminated: observer.sendCompleted))
  }
}
```

**Comment by vitorhugomagalhaes** [comment]
Thanks I'll have to port this to 2.5 version ...

**Comment by andersio** [comment]
If you mean RAC 4.x, you would have to use `started` (pre-start), which has been renamed to `starting` in RAC 5.

**Comment by vitorhugomagalhaes** [comment]
I'm still using the Objective-C API ...

**Comment by andersio** [comment]
In that case, that would be `initially`.

Anyway, please file ObjC-related questions in [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC) next time. 😸

**Comment by vitorhugomagalhaes** [comment]
Just for reference I did found this gist from justin that solved my problem

https://gist.github.com/jspahrsummers/9756674#file-ghreadwritequeue-m

**Comment by andersio** [comment]
Glad that you sorted it out. 😸
