### ISSUE TITLE
Bridge file for Objective-C generated does not have any methods

### ISSUE THREAD

**Issue by DilipSabat** [ReactiveCocoa/ReactiveCocoa#3257]
Hi,
Bridge file for Objective-C generated does not have any methods. So currently it cannot be used in objective-C project.
Please add keywords like @objc , public and inherit class from NSObject so it can be used in Objective-C project as well.  

Thanks in advance.

**Comment by andersio** [comment]
Please visit [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC) for the legacy Objective-C API.

**Comment by DilipSabat** [comment]
Hi,
I have already tried ReactiveObjc but it has compiler issues if it used in pod along with other swift pods. It throws some duplicate interface definition error for RACSignal and RACStream.

**Comment by mdiep** [comment]
You must be using older versions of ReactiveCocoa that include both Swift and ReactiveCocoa.
