### ISSUE TITLE
Rename intercepting APIs.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3258]
> http://www.merriam-webster.com/dictionary/trigger
> 
> Simple Definition of trigger
> : a lever on a gun that you pull to fire the gun
> : something that causes something else to happen

`NSObject.reactive.trigger(for:)` and `UIControl.reactive.trigger(for:)`, on the other hand, are not something that is active and aggressive like what _trigger_ really means. They are instead a signal of the host _being triggered_ in a specific circumstance.

So I'd like to propose to rename them as `intercept`:
```
public func intercept(_ selector: Selector) -> Signal<(), NoError>
public func intercept(_ controlEvents: UIControlEvents) -> Signal<(), NoError>
```

**Comment by sharplet** [comment]
> They are instead a signal of the host _being triggered_ in a specific circumstance.

My understanding is that it's more about using the returned signal to _trigger something else_. That is, the returned signal has no value, `()`, and so it is only useful as a pure event, to trigger some effect.

You can see this kind of use in the declaration of [`signal.take(until:)`](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Signal.swift#L990):

```swift
public func take(until trigger: Signal<(), NoError>) -> Signal<Value, Error>
```
