### ISSUE TITLE
[Xcode 8] Cannot run Unit Tests

### ISSUE THREAD

**Issue by slashmo** [ReactiveCocoa/ReactiveCocoa#3259]
Hi, since I've installed the SocketIO Swift client, I get the following error when trying to run my unit tests:

```
ld: framework not found RxCocoa for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This may is a duplicate of [this issue](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2317), but I wasn't sure since *aventurella* did build a framework & not a Xcode project.

It would be awesome if someone push me in the right direction to solve this problem. :]

**Comment by NachoSoto** [comment]
That's not `ReactiveCocoa`, that's [RxSwift](https://github.com/ReactiveX/RxSwift/tree/master/RxCocoa).
