### ISSUE TITLE
A "navigationItem.rightBarButtonItem" Exception

### ISSUE THREAD

**Issue by taojigu** [ReactiveCocoa/ReactiveCocoa#3260]
I define an enable RACSignal ,which is bind to RAC(RAC(self.navigationItem.rightBarButtonItem,enabled), at same time , its also be a enableSignal of "self.navigationItem.rightBarButtonItem.rac_command".
Then the excetpion is thrown:

OG: error: session_id=3EFB33D463E8F6453C31794E3A35EECA, context=Signal <RACDynamicSignal: 0x15d503e50> name:  is already bound to key path "enabled" on object <UIBarButtonItem: 0x15d5a8100>, adding signal <RACReplaySubject: 0x15d544f90> name:  is undefined behavior
(null)
((
	0   CoreFoundation                      0x0000000182126dc8 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018178bf80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182126c80 <redacted> + 0
	3   Foundation                          0x0000000182aac1c0 <redacted> + 88
	4   ReactiveCocoa                       0x00000001006d2684 -[RACSignal(Operations) setKeyPath:onObject:nilValue:] + 2216
	5   ReactiveCocoa                       0x00000001006d1da4 -[RACSignal(Operations) setKeyPath:onObject:] + 116
	6   ReactiveCocoa                       0x00000001006fa4d8 -[UIBarButtonItem(RACCommandSupport) setRac_command:] + 308
	7   Neighbours                          0x000000010003f834 -[FillMobileVC bindRac2ThisVC] + 800
	8   Neighbours                          0x000000010003f3b8 -[FillMobileVC viewDidLoad] + 368

The Code throw Exception is listed below, if "RAC(self.navigationItem.rightBarButtonItem,enabled) = enablSginal" is removed ,  it works fine.

   RACSignal* enablSginal = [self.mobileTextField.rac_textSignal map:^id(id value) {
        NSString* mobile = (NSString*)value;
        BOOL nextEnabled = [MobileFormatUtil isValideMobile:mobile];
        return @(nextEnabled);
    }];
   
    RAC(self.navigationItem.rightBarButtonItem,enabled) = enablSginal; //The bug Line//
    
    __weak FillMobileVC* weakSelf = (FillMobileVC*)self;
    self.navigationItem.rightBarButtonItem.rac_command = [[RACCommand alloc]initWithEnabled:enablSginal signalBlock:^RACSignal *(id input) {
        return [weakSelf requestVeiryCodeSignal:weakSelf.mobileTextField.text];
    }];

**Comment by andersio** [comment]
Please file Objective-C bug reports in https://github.com/ReactiveCocoa/ReactiveObjC. 😸
