### ISSUE TITLE
ReactiveCocoa 5 not working as Pod. Xcode can't access properties

### ISSUE THREAD

**Issue by MaximusMcCann** [ReactiveCocoa/ReactiveCocoa#3268]
Easy repeat:

```
pod playgrounds ReactiveCocoa
```

Change Podfile to:
```
use_frameworks!

target 'ReactiveCocoaPlayground' do
  pod 'ReactiveCocoa', '5.0.0-alpha.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

build

try to do `UITextField.textValues`

Zip:

[ReactiveCocoaPlayground.zip](https://github.com/ReactiveCocoa/ReactiveCocoa/files/560145/ReactiveCocoaPlayground.zip)

**Comment by MaximusMcCann** [comment]
Nor using Carthage :(

Cartfile:
```
github "ReactiveCocoa/ReactiveCocoa" "master"
```

Frameworks added and building successfully:
![image](https://cloud.githubusercontent.com/assets/1643285/19832758/28426f4e-9df2-11e6-995a-d4cf3816f4fd.png)

But
![image](https://cloud.githubusercontent.com/assets/1643285/19832765/57ff3a78-9df2-11e6-8bf5-ebe49a28dbb5.png)

**Comment by MaximusMcCann** [comment]
But `import ReactiveSwift` builds fine

![image](https://cloud.githubusercontent.com/assets/1643285/19832837/def450b2-9df3-11e6-9610-9231bf97f137.png)

**Comment by MaximusMcCann** [comment]
Appears everything works except the UI elements.  Things that look like `extension Reactive where Base: UI<thing> `

**Comment by chrrasmussen** [comment]
In ReactiveCocoa v5 the UI extensions are namespaced behind the [Reactive struct](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Reactive.swift), as you have seen references to. You could try accessing the methods like this (note the extra call to `.reactive`):

```
UITextField().reactive.textValues
UIControl().reactive.trigger(for: .touchUpInside)
```

Btw, which version of CocoaPods do you use? If you are using CocoaPods v1.1.1 it should not be necessary to include the `post_install` script to set Swift version or build dir.

**Comment by MaximusMcCann** [comment]
@chrrasmussen  Wow... So many thanks!  I was going through docs, but didn't see that.  Pretty key point, ha

Cheers!!
