### ISSUE TITLE
"The command is disabled and cannot be executed"

### ISSUE THREAD

**Issue by fancyydk** [ReactiveCocoa/ReactiveCocoa#3271]
A couple of users using our Electron-based app ran into the following error message:

"The command is disabled and cannot be executed"

It seems it happened when Squirrel.Mac, which depends on ReactiveCocoa, successfully downloaded an update but then failed to update. But I cannot figure out how to reproduce the issue. All Google search results I could find pointed to ReactiveCocoa so I'm posting this question here in hopes to find out more about this error message.

Squirrel/Squirrel.Mac#189

**Comment by joshaber** [comment]
This would be specific to Squirrel.Mac and since you already have an issue open on that repo I'm going to close this.
