### ISSUE TITLE
could not build Objective-C module 'ReactiveCocoa'

### ISSUE THREAD

**Issue by SethCody** [ReactiveCocoa/ReactiveCocoa#3279]
Xcode8.1 
Cocoapods 1.1.1

umbrella header 'ReactiveCocoa.h' not found
umbrella header "ReactiveCocoa.h"
                        ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'

**Comment by mdiep** [comment]
What version of ReactiveCocoa are you trying to use?

**Comment by mdiep** [comment]
You probably need to use https://github.com/ReactiveCocoa/ReactiveObjC, which is the new home of the Objective-C APIs.

**Comment by SethCody** [comment]
I use  ReactiveCocoa v5.0.0-alpha.2,but i do not want to use Obj API.



发自网易邮箱大师
On 11/07/2016 00:27, Matt Diephouse wrote:

You probably need to use https://github.com/ReactiveCocoa/ReactiveObjC, which is the new home of the Objective-C APIs.

**Comment by andersio** [comment]
How did you setup RAC in your Podfile?

**Comment by SethCody** [comment]
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9'

use_frameworks!

target 'ParkSwift'do

pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git'

pod 'SCLAlertView'

pod 'FlatUIKit'

pod 'SDAutoLayout'

pod 'pop', :git => 'https://github.com/facebook/pop.git'

pod 'MJRefresh'

pod 'ReachabilitySwift', '~> 3'

pod 'BRYXBanner'

end













At 2016-11-07 09:17:25, "Anders Ha" <notifications@github.com> wrote:


How did you setup RAC in your Podfile?

**Comment by andersio** [comment]
Try to specify also the tag, since we have only prerelease for 5.0.
```
pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git', :tag => '5.0.0-alpha.3'
```

**Comment by SethCody** [comment]
OK,I'll try.Thanks!


发自网易邮箱大师
On 11/07/2016 09:36, Anders Ha wrote:

Try to specify also the tag, since we have only prerelease for 5.0.

pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git', :tag => '5.0.0-alpha.3'
