### ISSUE TITLE
Swift 3 Rac 5 replacement for method "rac_liftSelector"

### ISSUE THREAD

**Issue by Samyro** [ReactiveCocoa/ReactiveCocoa#3287]
``` swift
self.rac_liftSelector(#selector(self.updateUIWith(_:data2:)), withSignalsFromArray: [signal1, signal2])
```
I'm now migrating a project to the latest version of ReactiveCocoa. And I've got problem about migrating method "rac_liftSelector" to the latest syntax. And there's nowhere I can find proper documents or migration guide. May I ask how to deal with cases like above in rac 5?
Regards,

**Comment by mdiep** [comment]
You could use `ReactiveObjC`—which is where `rac_liftSelector` lives. Admittedly that's not a great solution.

Otherwise you can use `combineLatest` + `take(during:)` + `startWithResult`.

**Comment by andersio** [comment]
`rac_liftSelector` would probably not be ported in its ObjC form, as it could have a possible type-safe form in Swift.

**Comment by andersio** [comment]
@mdiep It is not quite an equivalent yet (even assuming everything is `NoError`), since Swift 3.0 removed tuple splat for 2+ arguments. We would need a collection of operators for piping n-ary tuple into n-argument closure in ReactiveSwift.

**Comment by andersio** [comment]
@mdiep It is not quite a syntactic equivalent yet. We might need something like:

```
func apply<A, B>(_ action: @escaping (A, B) -> Void, _signal: Signal<(A, B), NoError>) -> Disposable?
```

**Comment by mdiep** [comment]
That version of `lift` seems more interesting to me than the old one—especially if it can also be used with `map` and `flatMap`.

**Comment by andersio** [comment]
@mdiep I just tried in the sandbox, and `lift` isn't needed at all.

**Comment by mdiep** [comment]
Oh, right. 🙈
