### ISSUE TITLE
ReactiveCocoa for Xcode 8.1 and swift 3

### ISSUE THREAD

**Issue by rameeznkhan** [ReactiveCocoa/ReactiveCocoa#3294]
Hey i'm using pod for installing ReactiveCocoa. But i'm getting errors in the result library. Don't know what the issue is can someone please help? Also attaching a screenshot of the issue i'm getting.
<img width="852" alt="screen shot 2016-11-14 at 5 48 36 pm" src="https://cloud.githubusercontent.com/assets/3940637/20264662/b882d75e-aa92-11e6-8497-0de2aa6a7917.png">

**Comment by andersio** [comment]
Specify `:tag => "5.0.0-alpha.3"` in your Podfile if you are using Swift 3.

**Comment by rameeznkhan** [comment]
Unknown external source parameters for `ReactiveCocoa`: `{:tag=>"5.0.0-alpha.3"}`. I'm getting this error. Following is how i have added my pod: 
```  
  pod 'ReactiveCocoa', :tag => '5.0.0-alpha.3'
```

**Comment by andersio** [comment]
The RAC thunk podspec is 5.0.0-alpha.3. If you are having problem, you might want to see if your pods repo is up to date.

You may also point to the repo directly, i.e. `:git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git'`

**Comment by andersio** [comment]
Yeah. If you want to use a pod with a prerelease semver tag, you need to be explicit.

**Comment by ikesyo** [comment]
@andersio `pod 'ReactiveCocoa', :tag => '5.0.0-alpha.3'` is not a valid syntax as @rameeznkhan said. `pod "ReactiveCocoa", "5.0.0-alpha.3"` or `pod "ReactiveCocoa", "~> 5.0.0-alpha.3"` will be.

**Comment by rameeznkhan** [comment]
hey @ikesyo it solved my issue thanks. You can close the issue, thank you :)

**Comment by andersio** [comment]
Sorry about the mistake. 😛

**Comment by rameeznkhan** [comment]
np @andersio :)
