### ISSUE TITLE
Conditionally start different producers in an action

### ISSUE THREAD

**Issue by akaralar** [ReactiveCocoa/ReactiveCocoa#3298]
There used to be an `[RACSignal if:then:else:]` operator to conditionally forward events from 2 signals. It seems it's been removed and I'm looking for a way to do the following:

There are email, username, password fields that need to be validated and a button to register. There is a corresponding `let isFieldValid: MutableProperty<Bool>` for each field and the value changes when text changes depending on whether text is valid or not. I then combine these into a single `let isFormValid: MutableProperty<Bool>`. I don't want to disable the button when the fields are not valid (so that when a user taps a button, I can show an error and the user can change the input accordingly.)

So I make an `Action` without using `enabledIf` parameter and a `CocoaAction` from that action. What I want to achieve is that when the user taps the button and fires the action, it should make a network request by starting a producer if `isFormValid` is true, and send an error while performing some side effects (like highlighting the fields with red). How can I go about achieving this?

Any help would be appreciated, thanks!

**Comment by sharplet** [comment]
If I understand correctly, it doesn't sound like you should need something like `if:then:else:`—because you don't need to respond to `isFormValid` _reactively_, only when the button is pressed:

```swift
submit = Action { [isFormValid] input in
  guard isFormValid.value else { return SignalProducer(error: FormError(reason)) }
  return submitTheForm(with: input)
}
```

Does that help?

In any case, you could get the behaviour of `if:then:else:` like this:

```swift
isFormValid.producer
  .flatMap(.latest) { isValid in
    isValid ? thenProducer : elseProducer
  }
```

**Comment by akaralar** [comment]
Thanks @sharplet , yeah that lights up a few ideas, thanks. I ended up doing something very similar to yours, only I am returning the `isFormValid.value` from the CocoaAction along with a tuple of username, email and password. May I ask why you captured `isFormValid` in your example?

**Comment by sharplet** [comment]
> May I ask why you captured `isFormValid` in your example?

I tend to prefer a capture list over capturing `self` where appropriate, but it's not crucial to the example (which is of course devoid of other context, like what `self` even refers to).

**Comment by akaralar** [comment]
@sharplet I didn't know you can capture properties separately instead of capturing self, because in Objective-C any reference to a property was implicitly capturing self. So I guess  that changed in Swift, I'll read the docs in more detail, thanks!

**Comment by sharplet** [comment]
Closing this for now. Feel free to rep on if this is still an issue!
