### ISSUE TITLE
`trigger(for:)` KVO interoperability bug

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3300]
ReactiveCocoa and ReactiveObjC do not correctly swizzle an instance if it had already been swizzled by KVO. Any invocation would raise an unrecognised selector exception.

```
// Swizzled by KVO.
object.reactive.values(forKeyPath: #keyPath(object.value)).start()

// Swizzled by RAC.
_ = object.reactive.trigger(for: #selector(setter: object.value))

// Unrecognized selector exception is raised.
object.value = 1
```

[Failing test case](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3286/commits/fe2f27c7207f398b474e6f4cefe2dea2060db1fe#diff-f1f2377061825177a6887d9ace987d1cR150
)

Expected to be fixed when ~~https://github.com/ReactiveCocoa/ReactiveObjC/pull/33 is back-ported~~ #3302 is merged.

**Comment by mdiep** [comment]
Fixed by #3302.
