### ISSUE TITLE
Can't get Signal using continuousTextValues when set text on textfield !!!

### ISSUE THREAD

**Issue by dhnghia22** [ReactiveCocoa/ReactiveCocoa#3301]
Hello everyone !
I need help. I can't get value of text field when i set text on textfield, i'm use both continuousTextValues and textvalues , i can get when i type on textfield, i don't know why !!! Someone help me get value when set text. Thanks

**Comment by andersio** [comment]
Without any context we can’t offer much help. But one thing to note is the optionality of the signal. You cannot directly bind a signal of `U?` to a target that is simply `U`.

**Comment by dhnghia22** [comment]
Example: 
`
@IBOutlet weak var textField : UITextfiled!
let sValue = MutableProperty<String?>("")
sValue <~ textField.reactive.continuousTextValues
textField.text = "TEST"  // Here, when i set text, sValue is not change to "TEST", it's still ""
`
but, when i type on textfield on UI, everything ok, i don't know why

**Comment by andersio** [comment]
This is the expected behavior of UIKit/AppKit. Programmatically setting any control values would not trigger any action messages. Only user interactions will.
