### ISSUE TITLE
RAC5 (rac_signalForSelector: fromProtocol)

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#3303]
How can I rewrite this code from RAC4 to RAC5?

```Swift 
rac_signalForSelector(fooSelector, fromProtocol: FooProtocol.self).toSignalProducer()
         .map({ $0 as? RACTuple })
         .map({ $0?.second as? MyObject })
         .ignoreNil()
```

In now I see only reactive.trigger(for:) but it return just Signal<Void, NoError> but I need trigger my signal (or signalProduce) when second argument inside fooSelector not nil.

**Comment by andersio** [comment]
The variant with method call arguments is pending (#3302).

As a note on the `fromProtocol` parameter, if you use it to dynamically implement optional requirements, with RAC 5 you would have to implement a dummy one, as we do not intend to bring it over.

**Comment by ajjnix** [comment]
@andersio Sounds like it could be right up my alley. Thanks! But when it will be in release?
