### ISSUE TITLE
UI Binding isn't working using <~ operator

### ISSUE THREAD

**Issue by EvilNOP** [ReactiveCocoa/ReactiveCocoa#3304]
I found that the following code snippet in the README.md isn't working:

```swift
// Bind the `name` property of `person` to the text value of an `UILabel`.
nameLabel.text <~ person.name
``` 

so, I figure it out by looking the related source code, turns out the following should work now:

```swift
// Bind the `name` property of `person` to the text value of an `UILabel`.
nameLabel.reactive.text <~ textField.reactive.continuousTextValues
```

The right hand side should be an object adopts  SignalProtocol.

**Comment by sharplet** [comment]
When you say "isn't working" what do you mean? Could you share the error message?

**Comment by EvilNOP** [comment]
```swift
nameLabel.text <~ textField.reactive.continuousTextValues
```

Xocde complains binary operator <~ cannot be applied to operands of type 'String?' and 'Signal<String?, NoError>', cuz the left hand side should be adopted to 'BindingTargetProtocol'

then the following code snippet works.

```swift
nameLabel.reactive.text <~ textField.reactive.continuousTextValues
```

**Comment by sharplet** [comment]
Ah, of course—it should be enough to change the left side to `nameLabel.reactive.text`.

**Comment by andersio** [comment]
Fixed in https://github.com/ReactiveCocoa/ReactiveCocoa/commit/4686919b74bc2bc24581a02212dc39392402055e. Thanks for catching it.
