### ISSUE TITLE
Successfully,create private lib ,But search no result

### ISSUE THREAD

**Issue by hengchengfei** [ReactiveCocoa/ReactiveCocoa#3306]
search no result.

![wechatimg2](https://cloud.githubusercontent.com/assets/3182964/20478504/5b27184e-b015-11e6-9852-191bce4b12e0.jpeg)

**Comment by ikesyo** [comment]
Looks unrelated.

**Comment by hengchengfei** [comment]
@ikesyo but why search no results?

**Comment by andersio** [comment]
For general CocoaPods issues that are unrelated to ReactiveCocoa, please visit [CocoaPods](https://github.com/CocoaPods/CocoaPods/issues).
