### ISSUE TITLE
MutableProperty(_ value: Value) don't call signal or producer

### ISSUE THREAD

**Issue by ajjnix** [ReactiveCocoa/ReactiveCocoa#3308]
I have next code
``` Swift
let v = UIView()
MutableProperty(v.frame).producer.startWithValues { (r) in
   print(r)
}
v.frame = CGRect(x: 0, y: 0, width: 10, height: 10)
```

But closure `print(r)` don't call. Replacing producer to signal also do nothing.

> ReactiveSwift (~> 1.0.0-alpha.3)

**Comment by dmcrodrigues** [comment]
You can't do that, `MutableProperty` doesn't provide any automatic observation mechanism to be aware of that change, it only notifies changes within the inner value itself. 

Also be aware that `UIView`'s `frame` doesn't support observation (through KVO), so you cannot use a `DynamicProperty` to monitor that change either.

You could swizzle `setFrame` to keep your mutable property up-to-date but unless there's a very strong reason that should be avoided IMHO.

**Comment by andersio** [comment]
As @dmcrodrigues said, `MutableProperty` is just a container that holds any arbitrary value - it does not track other's properties, but only what is being assigned to it.

If you want to hook on `frame`'s change, KVO is not the documented way to do either. You should override or intercept `layoutSubviews` instead.

```
view.reactive.trigger(for: #selector(view.layoutSubviews))
     .map { [unowned view] in view.frame }
```

**Comment by ajjnix** [comment]
I'm sorry. I'm very mistaken.
