### ISSUE TITLE
serializing SignalProducers with delays in between

### ISSUE THREAD

**Issue by gbuela** [ReactiveCocoa/ReactiveCocoa#3316]
Can you provide some guidance on how to implement this? I want to have a network layer where my app at any time can issue a request (via SignalProducer) but I'd guarantee that all requests are a) serialized in a single queue and b) there's a minimum delay in between actual request calls. Client code should not be concerned about either of those things.

Right now instead of requests I'm just using SignalProducers that send a dummy value and then a completed event, to see if I can produce those values with the delay.

I'm adding the SP's to a Signal, and I tried two things: 1) adding them with a delay, and 2) for each SP add first an empty SP with delay. 

In either case it seems I get a delay first and then all values are produced without delay.
Any suggestions...? thanks
Using swift 3

**Comment by mdiep** [comment]
You could do this with an `Action` where the `enabledIf` depends on the time since the last completion.

**Comment by gbuela** [comment]
Hm. Not sure about that but I can give it a shot. 
Closing it for now! thx
