### ISSUE TITLE
[Bikeshedding] How should the Actions of controls be named?

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3323]
In the codebase, we have "-ed" that are brought from Rex, and are not derived from any terminology in the corresponding components:
```swift
UIButton.reactive.pressed
UIBarButton.reactive.pressed
```
It should be `touch` or `touchUpInside` if we stick to the UIKit terminology.

In #3321, we have the preferable:
```swift
UIRefreshControl.reactive.refresh
```

In #3322, we have one that followed `UIButton` et al:
```swift
UISwitch.reactive.toggled
```
[`UISwitch` docs describe the manipulation as "flipping" instead.](https://developer.apple.com/reference/uikit/uiswitch)

It sounds better if we can come up with a consistent nomenclature for them.

I am leaning towards having just the verb alone now, e.g. `refresh`, since it makes sense when we treat it as `refreshAction` with `Action` implied by the type.

/cc @ReactiveCocoa/reactivecocoa

**Comment by mdiep** [comment]
I think it makes sense to have 2 patterns:

1. Past tense when something has happened and you have a chance to respond: `pressed`, `toggled`, etc.

2. Base form when the `Action` is the thing itself: `refresh`

**Comment by andersio** [comment]
It is fair. But `UIButton` and `UISwitch` sounds falling into category (2) too.

**Comment by akashivskyy** [comment]
Maybe it's a good idea to put these naming conventions in Documentation/ folder?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
