### ISSUE TITLE
Delete fixit for `Reactive<UIControl>.trigger(for:)` before 5.0

### ISSUE THREAD

**Issue by sharplet** [ReactiveCocoa/ReactiveCocoa#3325]
See #3324. `trigger(for:)` was first introduced in a prerelease, and if accepted will be renamed in a subsequent prerelease, so I don't think it makes sense to keep the fixit around in the final 5.0 release.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
