### ISSUE TITLE
Error when observing value with <~ operator

### ISSUE THREAD

**Issue by ninjagal21** [ReactiveCocoa/ReactiveCocoa#3326]
When I'm trying to use your first example:
`label.reactive.text <~ self.viewModel.loadPercentString`
I have an error:
`Binary operator '<~' cannot be applied to operands of type 'BindingTarget<String?>' (aka 'BindingTarget<Optional<String>>') and 'String'`

**Comment by sharplet** [comment]
Bindings won't work with regular Swift properties. The easiest way to observe changes to `loadPercentString` is to change its type to `MutableProperty<String>`. That will allow the binding to work, then you can change its value with `loadPercentString.value = ...`.

There are other ways to achieve this with `Property` or signals too, depending on what triggers changes to your data.

**Comment by XueChenChen** [comment]
```
//            self.cellLabel.text = newValue?.name
//            let newName: MutableProperty<String> = MutableProperty<String>("dd")  //MutableProperty<String>
//            DynamicProperty(object: self.cellLabel, keyPath: "text") <~ SignalProducer(value: newValue?.name)
            let newCellLableText = newValue?.name      //MutableProperty<String>?
            self.cellLabel.reactive.text <~ newCellLableText!
```
Question is my `newValue?.name` is `MutableProperty<String>` ,why this code`self.cellLabel.reactive.text <~ newValue?.name` have a error `:34:42: Binary operator '<~' cannot be applied to operands of type 'BindingTarget<String?>' (aka 'BindingTarget<Optional<String>>') and 'MutableProperty<String>?'` . i must change to : 
```
 let newCellLableText = newValue?.name      //MutableProperty<String>?
            self.cellLabel.reactive.text <~ newCellLableText!
```
