### ISSUE TITLE
Missing 'reactive' property for UIKit controls

### ISSUE THREAD

**Issue by gileze33** [ReactiveCocoa/ReactiveCocoa#3328]
I've been pulling my hair out over this for hours now - I've got the following in my Podfile:

```
pod 'ReactiveSwift', '1.0.0-alpha.4'
pod 'ReactiveCocoa', '5.0.0-alpha.3'
```

And in a view controller, importing:
```
import ReactiveSwift
import ReactiveCocoa
```

I'm unable to see the `reactive` property on any UIKit classes. It was working until I updated pods, did it get removed or something? (viewModel.time below is a MutableProperty<String>)

```
self.detailsTimeLabel.reactive.text <~ self.viewModel.time
```

Gives build error `Value of type 'UILabel' has no member 'reactive'`

**Comment by mdiep** [comment]
It should be there!

**Comment by andersio** [comment]
Try to remove `1.0.0-alpha.4`, and let CocoaPods fetch the right dependency for you. ReactiveCocoa hasn't been updated for `1.0.0-alpha.4`.

**Comment by gileze33** [comment]
Damn DerivedData causing havoc again, sorry!
