### ISSUE TITLE
Sort call sequence for subscribers.

### ISSUE THREAD

**Issue by bimawa** [ReactiveCocoa/ReactiveCocoa#3332]
Hi guys, i'm have a question about RAC2.5
I have 3 subscribers on my signal, i'm don't know when they will be subscribed, but know one of it signals must called before other all. How can i do that on RAC2.5? 

Now solve this feature with adding delay:.1 for another subscribers.

**Comment by mdiep** [comment]
RAC 2.5 questions should be raised on https://github.com/ReactiveCocoa/ReactiveObjC, which is the new home of the ObjC APIs.

**Comment by bimawa** [comment]
Ops missed. Thank you ^_^
