### ISSUE TITLE
Please update podspec file to ReactiveSwift alpha 4

### ISSUE THREAD

**Issue by anekk** [ReactiveCocoa/ReactiveCocoa#3334]
Podspec in cocopods has dependency for ReactiveSwift 1.0.0-alpha3. Please update to 1.0.0-alpha4.

**Comment by larryonoff** [comment]
I think it would be quicker if you create PR.

**Comment by ikesyo** [comment]
We need RAC 5 alpha 4 release first.

The podspec in this repo itself has been updated, so you can use it by `pod "ReactiveCocoa", :git => "https://github.com/ReactiveCocoa/ReactiveCocoa.git"`
