### ISSUE TITLE
Crash when passing "nil" to "execute" method

### ISSUE THREAD

**Issue by grzegorzkrukowski** [ReactiveCocoa/ReactiveCocoa#3338]
```
let updateAction: Action<Void, Void, NoError>  = Action {
    return SignalProducer(value: ())
}
let viewUpdateAction: CocoaAction<String?> = CocoaAction(updateAction) {
    str in
    if let str = str as String? {
       print(str)
    }
    return ()
}
viewUpdateAction.execute(nil)
```

The application crashes with `EXC_BAD_INSTRUCTION EXC_I386_INVOP`

The problem in my opinion is in [CocoaAction](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/CocoaAction.swift) class:

```
@IBAction public func execute(_ sender: Any?) {
		_execute(sender as! Sender)
	}
```

it allows to send "Any?" objects to method and tries to force cast it to Sender by "!"

**Comment by andersio** [comment]
We expect it not to be used directly, but only as an adapter for the Cocoa target-action pattern, which would always provide the sender.

**Comment by grzegorzkrukowski** [comment]
Thanks for an answer - I may  be miss using those elements, I'm not so experience in ReactiveCocoa - just getting started.
I just wanted to have same code executing on UIButton touchdown + another event execute not by Cocoa itself.
I can also do updateAction.apply().start() - I guess that solves my problem
