### ISSUE TITLE
.../UIBarButtonItem.swift:24:23: Value of optional type 'Disposable?' not unwrapped; did you mean to use '!' or '?'?

### ISSUE THREAD

**Issue by oronbz** [ReactiveCocoa/ReactiveCocoa#3349]
Hi,
I've created fresh new iPhone Swift 3.0 project with Xcode 8.2,
I've `pod init`
inserted `pod 'ReactiveCocoa', '5.0.0-alpha.3'` on my target
`pod install`
opened the workspace, tried to build, and I've got the following error:
`/Users/oron/Development/iOS/ReactiveCocoaExample/Pods/ReactiveCocoa/ReactiveCocoa/UIKit/UIBarButtonItem.swift:24:23: Value of optional type 'Disposable?' not unwrapped; did you mean to use '!' or '?'?`

**Comment by mdiep** [comment]
Yes, the return value of `<~` with a producer changed from `Disposable` from `Disposable?`.

**Comment by oronbz** [comment]
Your framework is failed to build. It's not that I'm using it incorrectly

**Comment by andersio** [comment]
@oronbz This is caused by the CocoaPods of 5.0.0-alpha.3 pulling the wrong version of ReactiveSwift prerelease. For the meantime, please use:
```
pod 'ReactiveCocoa', :git => 'https://github.com/ReactiveCocoa/ReactiveCocoa.git', :tag => '5.0.0-alpha.4'
```

**Comment by oronbz** [comment]
Thanks a lot @andersio
