### ISSUE TITLE
How to better combine signal sequences ?

### ISSUE THREAD

**Issue by pigfly** [ReactiveCocoa/ReactiveCocoa#3352]
Hi all, 

I'm having a sequence of signals that need to get combined and mapped, the scenario looks like the following:

```swift
// all these four signals are of same type ` Signal<Bool, NoError>`
 Signal
      .combineLatest(validNameSignal, validEmailSignal, validCitySignal, dateSignal)
      // there is a better way...
      .map { $0 && $1 && $2 && $3 }
      .observeValues {[unowned self] isValid in
        self.checkButton.isEnabled = isValid
    }
```

In my case, I'm wondering if there is a better way to map `(Bool, Bool, Bool, Bool)` into `Bool`,
given this type of mapping is very common.

I've noticed that in the earlier version of RAC, there is one `and` operation to achieve this. 
```swift
RACSignal.combineLatest([nameSignal, emailSignal, citySignal]).and()
```
However I'm using 5.0.0-alpha.5, I guess things have changed in this case.

Appreciate for any meaningful responses :)

**Comment by andersio** [comment]
So far we haven't provided logical operators yet. But there is a pending PR. Meanwhile, you may try:
```swift
 Signal
      .combineLatest([validNameSignal, validEmailSignal, validCitySignal, dateSignal])
      .map { $0.reduce(true) { $0 && $1 } }
```

**Comment by andersio** [comment]
P.S. I notice that you use these `Signal`s directly. You might need to be aware that:

1. the UI control `Signal`s only reacts to user interactions, and they would not emit the initial value for you.
2. The first `value` event is sent only if `combineLatest` catches at least one value from all involving `Signal`s.

**Comment by pigfly** [comment]
@andersio Appreciate your help :)

> the UI control Signals only reacts to user interactions, and they would not emit the initial value for you

Yes, I've realised that, actually I've opened an issue regarding emitting the initial value with signal [issue 3351](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3351). 

Do you think using `SignalProducer` , in my case , is a better idea ? 
i.e. convert all these four signals into SignalProducer, then combine and map.

Or there is a better approach to achieve this ?

**Comment by andersio** [comment]
We think this is a sign of [fragile layering](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3353). The "truth" should have been maintained in the Controller layer (MVC) or the View Model layer (MVVM), and you'd run your business logic in those layers instead of in the views.

But everyone has a certain constraints. So if tweaking your codebase for proper layering is not an immediate goal, `SignalProducer.prefix` as suggested by @sharplet is the interim solution.

**Comment by pigfly** [comment]
@andersio That's very insightful approach.

I'm totally with encouraging proper layering and not to have state in my UI components.

Thanks for your thoroughly explanation.
