### ISSUE TITLE
Using ReactiveCocoa 5.0.0-alpha.6 in the project with both Swift & ObjC: could not build Objective-C module 'ReactiveCocoa'

### ISSUE THREAD

**Issue by VojtaStavik** [ReactiveCocoa/ReactiveCocoa#3357]
Hey guys,

I'm trying to use RC5-alpha6 in **the Swift part** of my ObjC+Swift codebase. Even though I'm not importing RC to any of my ObjC files, I'm getting the "could not build Objective-C module 'ReactiveCocoa'" error. **EDIT:** + Umbrella header 'ReactiveCocoa.h' not found.

I'm using Xcode8.2, Swift3.0, CocoaPods 1.2.0.beta.1.

podfile:
```pod 'ReactiveCocoa', '5.0.0-alpha.6'```

I tried to:
- clean build folder
- delete derived data
- clean cocoapods cache
- remove all Pods and install them again (pod deintegrate)

 Is there something I'm missing? ~~Could you please tell me if it's even possible to use it in the project with mixed codebase?~~

**EDIT: When I use Carthage, everything works OK.**

Thank you very much!

**Comment by VojtaStavik** [comment]
When I use Carthage, everything works OK.

**Comment by ieatworld** [comment]
Hi @VojtaStavik,
I had the same issue and after reviewing project build settings I found out that `USER_HEADER_SEARCH_PATHS` setting included pods directory 
```USER_HEADER_SEARCH_PATHS = "\"${PROJECT_DIR}/Pods\"/**```. Removal of this setting fixed problem.
