### ISSUE TITLE
How to prevent mutable property deadlocks in RAC4

### ISSUE THREAD

**Issue by gbrhaz** [ReactiveCocoa/ReactiveCocoa#3365]
I have a scenario where setting `ValueA` sets `ValueB` which then wants to set `ValueA` again (in each of the corresponding observers). Obviously this is not ideal, and a bit awkward. What would be the best solution to this problem? 

It seems I can resolve this by doing an `async main` call - is this really the best solution though...?

**Comment by andersio** [comment]
You are hit by the fact that `Signal` does not permit recursive event sending (for a good cause). What you are doing is basically an infinite feedback loop anyway, unless there is a terminal condition.

Going asynchronous is the apparent solution without knowing what it is expected to be solved.

**Comment by gbrhaz** [comment]
Thanks. There is a terminal condition in most scenarios; there was just one small one where it wasn't. Either way, I'm not doing anything synchronously here so all good :)

**Comment by NinoScript** [comment]
I had had a signal bound to a MutableProperty, and there was a case where a change in that property made one of it's observers send an event to the original signal.
It's an intrinsic property of the system I'm modeling, and that feedback loop can only happen once.

I changed the binding `mutableProperty <~ signal`
To this: `signal.observe(on: QueueScheduler.main).observeValues { mutableProperty.value = $0 }`

The `.observe(on: QueueScheduler.main)` broke the chain and fixed the deadlock.
Something like this may help in your situation too, but I'm not 100% sure if this is safe, I'm really new to ReactiveCocoa (and RFP in general).
