### ISSUE TITLE
combineLatestWith many signals (RAC4)

### ISSUE THREAD

**Issue by gbrhaz** [ReactiveCocoa/ReactiveCocoa#3367]
The result of `combineLatestWith` on three or more signals results in the values being kept in quite cumbersome tuples. For example, if I have combined a signal from `one`, `two`, `three`, `four`, and I call `map` on the resulting signal, I have to do something like:

```
let one = $0.0.0.0
let two = $0.0.0.1
let three = $0.0.1
let four = $0.1
```

Is this really the best way of getting back these values?

**Comment by sharplet** [comment]
Take a look at the static versions of `combineLatest` (available on each of `Signal`, `SignalProducer` and `Property`), e.g.:

```
Signal.combineLatest(one, two, three, four)
  .observeValues { one, two, three, four in
    // ...
  }
```
