### ISSUE TITLE
Where is memory for address allocated by AssociationKey<Value>.init(default:) deallocated

### ISSUE THREAD

**Issue by vttrifonov** [ReactiveCocoa/ReactiveCocoa#3370]
In AssociationKey<Value>.init(default:)  memory is allocated for the UnsafeRawPointer address, but this memory seems never to be deallocated (as far as I can tell). Swift 3 docs are pretty clear on pointer memory management (e.g. no automatic management). Anyone care to elaborate? What is the magic here?

**Comment by mdiep** [comment]
It's not deallocated (and doesn't need to be). There are a fixed number of these, and they act as per-process unique values. This is like adding a global constant string (but it requires less memory). In fact, the proper behavior relies on not deallocating them—otherwise the value might be reused.

**Comment by vttrifonov** [comment]
Gotcha. Very few of them, a byte each, not much to worry about... I am using the addresses of global variables for id's of associated objects, but then I saw yours implementation and figured  I would learn something new.
