### ISSUE TITLE
'Signal' Memory Leak in 10.2 

### ISSUE THREAD

**Issue by krishnans** [ReactiveCocoa/ReactiveCocoa#3373]
Xcode's Memory graph debugger (and Instrument's MemoryLeak) shows memory leak  whenever i use "Signal" or "MutableProperty".  But its not the case in signal producer.

It happens only in iOS 10.2, if i choose iOS 9.2 in simulator then there is no leak.

I have uploaded the sample project here. I am using Xcode 8.2 and iOS 10.2
https://github.com/krishnans/ReactiveSwiftSample

Code:
```
import UIKit
import ReactiveSwift
import Result

class ViewController: UIViewController {
	let database:DatabaseManager = DatabaseManager()
	override func viewDidLoad() {
		super.viewDidLoad()
		database.statusChangedSignal.skipRepeats().observeValues { print($0) }
	}
}

struct DatabaseManager {	
	let statusChangedSignal:Signal<Bool, NoError>
	private let status = MutableProperty<Bool>(false)
	init() { self.statusChangedSignal = status.signal }
}
```

// 2 leaks  

// just creating a instance
`database() `
//or observering it
```
database.statusChangedSignal
			.observeCompleted {
			print("Completed ")
		}
```

// 9 leaks if i add UIScheduler
```
database.statusChangedSignal
			.observe(on: UIScheduler())
			.observeCompleted {
			print("Completed ")
		}

```
// 17 leaks - if i add skipRepeats
```
database.statusChangedSignal
			.observe(on: UIScheduler())
			.skipRepeats()
			.observeCompleted {
			print("Completed ")
		}

```
is this an iOS 10.2 issue or am i doing something wrong here?

similar question
https://github.com/ReactiveCocoa/ReactiveSwift/issues/216
https://github.com/ReactiveCocoa/ReactiveSwift/issues/92

I found a similar issue in another library 'SnapKit' 
https://github.com/SnapKit/SnapKit/issues/363

Instead of posting it in ReactiveSwift issues, i posted it here.  :(

**Comment by andersio** [comment]
Instruments do not work well with Swift's reference counting implementation, which delays deallocations till the last weak reference is accessed. Unless you really see a memory growth after repetition, there is nothing to worry about.

**Comment by krishnans** [comment]
@andersio thank you.   Just to make sure i am not doing anything wrong. I added `on(disposed:) ` to ever signal observer.
When the view controller / view model containing the observer is reinitialized the signal is not disposed.

signal is disposed only when i use `take(during:lifetime)` or store the the disposable in an instance property and dispose it in view controller / view model `deinit`

is take(during) or any of the other take operators or the dispose method   is must for properly releasing the observer?

**Comment by andersio** [comment]
Is the concerned `Signal` something in your control?

**Comment by krishnans** [comment]
@andersio yes, that particular signal is under my control.  Now i got it. I am not sending any terminal event and i am not removing observers.  BTW when you say 'remove observers' you mean the dispose or any one of those take()   api's. right?

I should start add this take(during:) to every signals. Thank you very much @andersio

**Comment by andersio** [comment]
> BTW when you say 'remove observers' you mean the dispose or any one of those take() api's. right?

Yes. A unterminated `Signal` is kept alive if (1) it has at least one observer; or (2) it is retained. So let's say if you have a `Signal` that is long-living, while you have transient views that observes it, generally you should clean up the observations whenever it is not needed. `take(during:)` or `take(until:)` is usually recommended over dealing with the `Disposable`s.
