### ISSUE TITLE
How to disambiguate flatten?

### ISSUE THREAD

**Issue by memmons-ntst** [ReactiveCocoa/ReactiveCocoa#3378]
Updated to latest ReactiveCocoa and trying to compile some inherited code. I'm getting "ambiguous use of the word 'flatten'" in a bunch of places. I'm not sure how to specify the template to disambiguate and unconfuse the compiler. The only example I've seen suggests something like `let signal = SignalProducer<SignalProducer<Void, NSError>, NoError>(values: signalProducers).flatten(.Concat)` which fails because `NoError` is apparently no longer a thing. Can someone walk me through what I'm supposed to do here?

```
let signalProducers = assessmentArray.map({ self.viewModel.searchForPlans().apply((senderAppSettings: senderAppSettings, planName: $0, ntstOrgID: self.baseDocumentInfo.ntstOrgID)) })
let signal = SignalProducer(values: signalProducers).flatten(.Concat)
                        signal
                            .observeOn(UIScheduler())
                            .on(started: { [weak self] event in
                                    if let wself = self {
                                        wself.presentProgressHud(wself.loading, view: nil)
                                    }
                                }
                                ,
                                next: { [weak self] value in
                                    if let wself = self {
                                        if let displaySummary = value.searchResults.first {
                                            var documentID: [CareFabricID]?
                                            if let linkedAssessment = wself.linkedAssessments?.filter({$0.assessmentDisplayPlanID?.id == displaySummary.assessmentDisplayPlanID?.id }) {
                                                if linkedAssessment.count > 0 {
                                                    documentID = [CareFabricID]()
                                                }
                                                linkedAssessment.forEach({ (assessment) -> () in
                                                    if let docID = assessment.assessmentDocumentID {
                                                        documentID?.append(docID)
                                                    }
                                                })
                                            }
                                            let docInfo = FKDocumentInfo(documentID: documentID, patientID: wself.baseDocumentInfo.patientID, encounterID: wself.baseDocumentInfo.encounterID, ntstOrgID: wself.baseDocumentInfo.ntstOrgID, planName: displaySummary.name ?? "")
                                            docInfo.documentPlanID = displaySummary.assessmentDisplayPlanID
                                            let avm = FKAssessmentDisplayViewModel(documentInfo: docInfo)
                                            wself.assessmentViewModels.append(avm)
                                        }
                                    }
                                },
                                failed: {[weak self] error in
                                    self?.removeProgressHUD()
                                    switch error {
                                    case .ProducerError(let err):
                                        self?.showError(err)
                                    case .NotEnabled:
                                        self?.showError(NSError.newError("Unknown error"))
                                    }
                                },
                                completed: {[weak self] _ in
                                    if let wself = self {
                                        wself.createLists()
                                    }
                                })
                            .start()
```

**Comment by andersio** [comment]
1. The compiler likes to complain things that are irrelevant to what causes a problem. It is improving over time, but sometimes it would still hit you.
1. The `FlattenStrategy` enum uses lower case in Swift 3.
1. `NoError` still exists.
1. `NSError` might have been imported by Swift as `Error` instead.

**Comment by memmons-ntst** [comment]
1. Yep
2. This isn't swift 3, it's swift 2.3
3. Not according to Xcode
4. Error is not valid. NSError is fine.

Aside from `import Results` I have no idea how to force Xcode to recognize NoError.

**Comment by andersio** [comment]
Hmm, so are you using ReactiveCocoa 4.x?

**Comment by memmons-ntst** [comment]
`github "ReactiveCocoa/ReactiveCocoa" ~> 4.1.0`

Let me track down why NoError is missing and I'll post from there. Seems like there not much that can be done without fixing that.

**Comment by andersio** [comment]
Note that the last release of 4.x is 4.2.2.

**Comment by andersio** [comment]
Oh, 4.2 might actually help.

> https://github.com/ReactiveCocoa/ReactiveCocoa/releases?after=v4.2.1
> [...]
> Overloads for flatMap() and flatten() for Signals and SignalProducers with NoError (#2885, thanks @mdiep, @NachoSoto, and @andymatuschak!)

**Comment by memmons-ntst** [comment]
Found the missing `NoError`. Just needed to hit Xcode over the head a few times. In any case, once the template was in place it still gave an error, but at least this one indicated that the initializer was wrong and told me what was expected.  So, seems to be all good now.

@andersio Thank you for the input!

**Comment by memmons-ntst** [comment]
The fix was too good to be true I guess. Although I can compile and archive from within Xcode, as soon as I try a command line compile it craps out:

```FKMultiAssessmentDisplayViewController.swift:155:140: error: value of type '(values: _) -> SignalProducer<SignalProducer<SearchAssessmentDisplayPlanOutputPayload, ActionError<NSError>>, NoError>' has no member 'Element'```

So, back to square one again. :-/
