### ISSUE TITLE
Swift package manager

### ISSUE THREAD

**Issue by toddbluhm** [ReactiveCocoa/ReactiveCocoa#3379]
Just curious about what happened to swift package manager support? It looks like a PR was merged in here: https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3132 to support it, but I don't see a Package.swift file in master anymore.

I searched the issues/PRs and did not see any discussion on removal of swift package manager support. Possibly removed by mistake?

**Comment by toddbluhm** [comment]
Going to close this as its now obvious to my why swift package manager support was removed. Completely missed this important line in swift package manager docks: `Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms.` It does not support UIKit and other such dependencies. So no reason why this should support it yet either. Sorry about this, but at least its now documented as an issue for other people to find.

**Comment by mdiep** [comment]
Also ReactiveSwift _does_ support SwiftPM. That's where the support went.

**Comment by NachoSoto** [comment]
FYI I'm working on this now.

**Comment by NachoSoto** [comment]
I wasn't able to finish this FYI, no longer working on it.

**Comment by gcox** [comment]
Handled in PR #3693

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
