### ISSUE TITLE
Is ther any sample ?

### ISSUE THREAD

**Issue by ZhangZihe** [ReactiveCocoa/ReactiveCocoa#3380]
Such as binding for UITableView

**Comment by andersio** [comment]
Sadly we do not have a solution for collection views yet. :(

**Comment by ZhangZihe** [comment]
@andersio But how to use the field: `tableView.reactive.reloadData`

**Comment by andersio** [comment]
Well, it is a binding target. So you can establish a binding towards it.

```swift
tableView.reactive.reloadData <~ button.reactive.controlEvents(for: .touchUpInside).map { _ in }
```

**Comment by ZhangZihe** [comment]
@andersio Do you have a plan to solve the problem of binding for collection views. And can you tell me the time period when it was solve? I think a lot of developer need it like me. RxSwift seems has implement this. The progress of ReactiveCocoa seems  fall behind the RxSwift. 
Thanks.

**Comment by summerHearts** [comment]
请查看饿了么的开源项目，有你想要的！
发自网易邮箱大师
On 01/22/2017 16:11, 张子何 wrote:

@andersio Do you have a plan to solve the problem of binding for collection views. And can you tell me the time period when it was solve? I think a lot of developer need it like me. RxSwift seems has implement this. The progress of ReactiveCocoa seems fall behind the RxSwift.
Thanks.

**Comment by ZhangZihe** [comment]
@summerHearts  请问是哪一个项目, 可以把地址发我吗, 谢谢

**Comment by summerHearts** [comment]
IPDMVVMkit


发自网易邮箱大师
在2017年01月22日 17:05，张子何 写道:

@summerHearts 请问是哪一个项目, 可以把地址发我吗, 谢谢

**Comment by ZhangZihe** [comment]
@summerHearts  我并未在github上搜索到这个项目的名字啊, 可以直接给我发地址吗, 谢谢

**Comment by Insofan** [comment]
@ZhangZihe This is my simple about RAC OC version https://github.com/Insofan/ReactiveCocoaNote
我最近开始看reactivecocoa自己闲暇写的sample 大概看看吧  谈不上sample 常用的用法吧 oc版本 代码质量谈不上 就是写着玩 有什么想法可以一起交流

**Comment by ZhangZihe** [comment]
已解决

**Comment by ZhangZihe** [comment]
已解决
