### ISSUE TITLE
Why NSObject+Association is private and internal?

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveCocoa#3381]
I'm playing around with `NSControl` reactive extension and finding  how it makes use of `trigger`, which uses `associatedValue`. If want to reuse them I need to reimplement all of that logic. Any reason why they were hidden in first place?

**Comment by mdiep** [comment]
We try to default to internal/private access unless something is explicitly part of a public API. This maximizes our ability to improve the code and not leak implementation details.

If there's something that you'd like to see made public, open an issue describing what you want and what your use case is.
