### ISSUE TITLE
Memory Leak on custom signal

### ISSUE THREAD

**Issue by ssumar** [ReactiveCocoa/ReactiveCocoa#3386]
I'm new in Reactive Cocoa for Swift, and trying to make a custom signal for my Web Service calls. I got memory leak on profiler, however I can't figure out where to dispose the Signal in order to avoid the leaks.

```
public func GetGroups() -> Signal<[GroupModel], SError>? {

        let accToken:String? = KeychainWrapper.standard.string(forKey: "access_token")
        let headers = ["Authorization":"Bearer " + accToken!]

        let signal = Signal<[GroupModel],SError>({(obs:Observer<[GroupModel],SError>) -> Disposable?
            in
            Alamofire.request(serverUrl+"/api/group/groups",method:HTTPMethod.get,parameters:nil,encoding:URLEncoding.default,headers:headers)
            .responseArray(completionHandler: {(data:DataResponse<[GroupModel]>) -> Void in

                if data.error != nil{

                   //handle error

                }else{
                    obs.send(value: data.result.value!)
                }


            })
            return nil
        })

        return signal;

    }
```

```
_ = groupService.GetGroups()?
            .observeResult{
            self.dataSource = $0.value
            self.collectionView?.reloadData()


        }
```

**Comment by andersio** [comment]
Unless repetitive accesses to the concerned `Signal` result in monotonically increasing memory consumption, it is usually a false positive due to Instruments not working well with Swift's reference counting (yet).

**Comment by ssumar** [comment]
It means everything is fine with code above? and no memory leaks could be there ?

**Comment by andersio** [comment]
It is a bit late, but you might want to avoid capturing `self` in `observeResult`. Another side note is that you might want to use `SignalProducer` for `GetGroups`, which guarantees the request is fired _after_ you start (or "subscribe") the producer.

We have also improved interoperability with memory debugging tools, so in the upcoming ReactiveCocoa 6 release, you would see
