### ISSUE TITLE
KVO

### ISSUE THREAD

**Issue by JQHee** [ReactiveCocoa/ReactiveCocoa#3392]
I want to use kvo, but all I know is that one kind of implementation method, I also want to know is do you have any other way?Here is one way I know.

        let result = self.view.reactive.values(forKeyPath: "bounds")
        result.start { [weak self](rect) in
            print(self?.view ?? "")
            print(rect)
        }

**Comment by andersio** [comment]
`DynamicProperty(object: self.view, keyPath: "...")` also uses KVO, but it uses `values(forKeyPath:)` internally anyway.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
