### ISSUE TITLE
DynamicProperty Optional Type

### ISSUE THREAD

**Issue by calebd** [ReactiveCocoa/ReactiveCocoa#3393]
`DynamicProperty` expects its type to always be `T` even when the underlying type may be `T?` and exposes a `signal` and `producer` that always send `T?` even when the underlying type may be `T` (as is always true when observing primitives on Objective-C classes). `DynamicProperty` should be updated to handle that logic internally and allow the consumer to express the exact type of value they expect instead of having to write code to defend against situations that will not happen.

**Comment by mdiep** [comment]
Care to open a PR against `master-next` that fleshes this out? It sounds like a good idea.

**Comment by andersio** [comment]
The problem is that you cannot have `value` that is of `T?`, as required by the weak referencing, while having `producer` and `signal` sending out `T`.

**Comment by sharplet** [comment]
What if instead of sending `nil` the producer instead completed immediately if it's underlying object was `nil`?

**Comment by sharplet** [comment]
That seems like it would also mirror the semantics of other properties, that complete when their lifetimes end.

**Comment by andersio** [comment]
`DynamicProperty` already behaves differently w.r.t. ReactiveSwift Properties when the underlying object has deinitialized.

**Comment by andersio** [comment]
It seems `DynamicProperty` can be folded into `Reactive` as `property(forKeyPath:)`, or as a convenience initializer of `Property`. It does not have anything different from `Property(unsafeProducer:)`.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
