### ISSUE TITLE
Mixing two SignalProducers of different types and other simple use cases

### ISSUE THREAD

**Issue by alper** [ReactiveCocoa/ReactiveCocoa#3399]
I've googled around for a bit now to figure out how to run two SignalProducers of different types simultaneously while waiting for them both to finish. I've been able to find the detritus of several generations of documentation and examples but nothing that I can apply to my project right now.

My issue isn't that per se, I'm sure that with another couple of hours of noodling around I can find something that works, it's an issue I have with reactive programming in general:

- Easy things should be easy
- Easy things should be easy to figure out

I don't know yet how to move things forward on this, but since I'm working in a reactive codebase I'm very interested in anything I can do to either improve this, to learn more and to help others to learn more.

**Comment by mdiep** [comment]
You can't combine SignalProducers of different types.

If you have one producer that sends `A`s and another that sends `B`s, what would it mean to combine them? The resulting producer can't send both `A`s and `B`s. You need to map to a common type in order to combine.

**Comment by alper** [comment]
So flatMap them to return the same type? Actually I care about the output of one but not about the output of another.

Suppose they were the same type, how could they be parallelized waiting for both of them to complete?

**Comment by alper** [comment]
Also, I'm interested to learn the answers to this specific case but I'm more interested to learn what path of documentation I could follow to find out the same. If there is no path, we may need to create an issue to fill a hole there.

**Comment by mdiep** [comment]
> So flatMap them to return the same type?

It doesn't need to be `flatMap` specifically. It could be `map`.

> Actually I care about the output of one but not about the output of another.

In that case, you probably want to use `then` with an `empty` producer.

```swift
producerOfBs.then(SignalProducer<A, Error>.empty)
```
```

> Suppose they were the same type, how could they be parallelized waiting for both of them to complete?

That's what `flatten` and `flatMap` do. In this case, it sounds like you want the _merge_ strategy, so you could use `SignalProducer.merge(producerOfAs, producerOfBs.then(SignalProducer<A, Error>.empty)`.

> Also, I'm interested to learn the answers to this specific case but I'm more interested to learn what path of documentation I could follow to find out the same. If there is no path, we may need to create an issue to fill a hole there.

Totally. PRs to that end would be very welcome. TBH, it's hard for me to evaluate beginner documentation needs because I've been doing this for a while.

The playgrounds that are included in https://github.com/ReactiveCocoa/ReactiveSwift are probably the best documentation for you.

**Comment by alper** [comment]
OK. Thanks for these examples, they're very helpful.

I've just now gotten the ReactiveSwift playground to work after struggling a bit with the ReactiveCocoa one (those still don't work but now that I've found this one it does not matter that much).

One thing that immediately does not make sense to me is: `observer.send(value: 10)`

Does the observer send a value? Or is a value sent to the observer? Shouldn't on the `(signal, observer)` tuple returned from the Signal creation values be sent into the signal and received on the observer?

**Comment by mdiep** [comment]
> Does the observer send a value? Or is a value sent to the observer?

Both?

An internal `Observer` sends values to external `Observer`s.

**Comment by alper** [comment]
> An internal Observer sends values to external Observers.

So yeah, now I've lost it. I think this is an issue.

**Comment by mdiep** [comment]
It's probably most accurate to say that values are sent to observers.

But an observer is also used internally.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
