### ISSUE TITLE
Text input modification/autocompletion in MVVM

### ISSUE THREAD

**Issue by nikolai42** [ReactiveCocoa/ReactiveCocoa#3400]
The problem, user types text into UITextView, I want to pass data to VM after each entered character where the modification/autocompletion (simple example, replacing occurrences of word with other word or hashtag autocompletion) would take a place and if the result text is different it would pass back to UITextView to reflect the changes.

In MVVM without reactive code, I could do so using simple delegates for UITextView text change and callback from VM that text needs to be updated to reflect modification/autocompletion.

I was able to do two binding similar to this example: http://stackoverflow.com/questions/36153489/how-to-achieve-two-way-binding-using-reactivecocoa-4-0-and-mvvm
But once, I try to modify the text I get deadlock.

Is there good approach to achieve this using reactive cocoa?

**Comment by Duraiamuthan** [comment]
@nikolai42 - MVVM.Are your using Xamarin or something ?
If yes,Can you share some link on how to integrate ReactiveCocoa with Xamarin ? :)

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
