### ISSUE TITLE
我只想要 Object-C ，我应该怎么做才能支持 ios7+？

### ISSUE THREAD

**Issue by Jason-xuguoyong** [ReactiveCocoa/ReactiveCocoa#3402]
我只想要 Object-C ，我应该怎么做才能支持 ios7+？

**Comment by Jason-xuguoyong** [comment]
I just want the Object - C, what should I do to support ios7 +?

**Comment by mdiep** [comment]
The Objective-C APIs are available here: https://github.com/ReactiveCocoa/ReactiveObjC

**Comment by faimin** [comment]
or  `pod 'ReactiveCocoa', '~> 2.5'`
