### ISSUE TITLE
using cocoa pod, trying to update from 4.2.2 to 5.0.0 But I see many errors 

### ISSUE THREAD

**Issue by yoshiakiokuma** [ReactiveCocoa/ReactiveCocoa#3403]
using cocoa pod, trying to update from 4.2.2 to 5.0.0

But I see many errors 
Use of undeclared type ' RACStream'
Use of undeclared type ' RACSignal'
Use of undeclared type ' RACCommand'
Use of undeclared type ' RACDisposable'

What should I do?

**Comment by andersio** [comment]
If you use only ObjC, please check [ReactiveObjC](https://github.com/ReactiveCocoa/ReactiveObjC/). The ObjC API has been spun off in its own repo.

**Comment by yoshiakiokuma** [comment]
Hi,
which version of ReactiveObjC is equivalent to ReactiveCocoa4.2.2?

**Comment by mdiep** [comment]
1.0 is closest, but some minor (breaking) changes have been made. I'd recommend using the latest version of ReactiveObjC.

**Comment by yoshiakiokuma** [comment]
If possible, I do not want to make any changes to my source code.
Is that possible? I have tried 1.0 and the latest. It seems like I need to change more than one or two hundred parts. Isn't they're exactly the same version... the thing is I need to turn off use swift legacy version option. Any help and help will be so much appreciated. Thank you.

**Comment by andersio** [comment]
Do you mind sharing what prevents your project from building with ReactiveObjC? Without sufficient information, we can't really help much.

**Comment by andersio** [comment]
The framework is more or less the same. But since Swift 3.0 now imports the ReactiveObjC framework based on the Swift 3 API Guidelines, this causes changes in a lot of method base name and parameter labels. Pretty much like any Cocoa frameworks.
