### ISSUE TITLE
Cannot make binding between  BindingTarget<Bool> and DynamicProperty<Bool>

### ISSUE THREAD

**Issue by szpako1** [ReactiveCocoa/ReactiveCocoa#3406]
I'm trying to make binding between UISwitch.reactive.isOn and DynamicProperty<Bool>, but can't compile. 

```
@IBOutlet weak var sendReciptSwitch: UISwitch!
...
self.sendReciptSwitch.reactive.isOn <~ self.profileViewModel.profileEmailsEnabled

...

private(set) internal var profileTouchidEnabled: DynamicProperty<Bool>!
...
self.profileEmailsEnabled = DynamicProperty<Bool>(object: UserProfileManager.shared, keyPath: "emailsAllowed")

```
And the error is: 

> Binary operator '<~' cannot be applied to operands of type 'BindingTarget\<Bool\>' and 'DynamicProperty\<Bool\>!'

What's wrong?

**Comment by sharplet** [comment]
Does explicitly force-unwrapping `profileEmailsEnabled` work?

```
self.sendReciptSwitch.reactive.isOn <~ self.profileViewModel.profileEmailsEnabled!
```

If so, you could possibly remove the optionality by making `profileEmailsEnabled` a `lazy var` and making it non-optional.

**Comment by szpako1** [comment]
@sharplet After adding ! I've got:

> Expression type 'Disposable?' is ambiguous without more context

The strangest thing is that the same but with String instead of Bool works like charm.

```
@IBOutlet weak var phoneNumberTextField: UITextField!
...
self.phoneNumberTextField.reactive.text <~ self.profileViewModel.profilePhone

...

private(set) internal var profileName: DynamicProperty<String>!
...
self.profilePhone = DynamicProperty<String>(object: UserProfileManager.shared.profile, keyPath: "phone")
```

**Comment by andersio** [comment]
`DynamicProperty<Value>` is actually a `Property` of `Value?`, due to its weak reference to the object. You need to handle the optionality e.g. `skipNil()`.

**Comment by szpako1** [comment]
@andersio skipNil() on what?

`DynamicProperty<Bool>(object: UserProfileManager.shared, keyPath: "emailsAllowed")`
points to:
`dynamic internal var emailsAllowed: Bool = UserDefaults.standard.bool(forKey: "email")`

**Comment by szpako1** [comment]
@andersio , @sharplet I found that this works: 

`self.sendReciptSwitch.reactive.isOn <~ self.profileViewModel.profileEmailsEnabled.signal.skipNil()`

**Comment by andersio** [comment]
`skipNil` on the producer of the property. Replacing `nil` with a default value works too.
