### ISSUE TITLE
Availability for Xamarin

### ISSUE THREAD

**Issue by Duraiamuthan** [ReactiveCocoa/ReactiveCocoa#3409]
Will it be made available for Xamarin..I mean Nuget ?

Basically I am moving to xamarin but existing source code in Objective C makes use of ReactiveCocoa.

So I am thinking on how to go about this since its not available for Xamarin so far ?

If its avaialable for xamarin.. Kindly share some link 

Thanks

**Comment by mdiep** [comment]
The older Objective-C APIs are now at https://github.com/ReactiveCocoa/ReactiveObjC.

I don't know anything about RAC being available on Xamarin/Nuget.
