### ISSUE TITLE
MutableProperty value is different inside a closure

### ISSUE THREAD

**Issue by Gofake1** [ReactiveCocoa/ReactiveCocoa#3412]
I have a `MutableProperty<Array<T>>` called `devices`, and I  read its value from inside a closure:
```swift
[weak devices = self.devices] in
guard let devices = devices else { ... }
let address = ...
if devices.value.contains(where: { device -> Bool in return device.address == address }) {
    ...
}
```
Outside of the closure I modify `devices.value`:
```swift
devices.value.append(aDevice)
```
The problem is that the closure's "copy" of `devices.value` doesn't contain the new `aDevice`.
Is this the expected behavior for a `MutableProperty<Array>` ?

**Comment by mdiep** [comment]
Where are you appending it?

This is a timing question. You could be reading `devices.value` before or after you append. You haven't given enough detail above to know which.

**Comment by Gofake1** [comment]
I register the closure and set `devices.value` at init, and the closure gets called randomly after init. I should have mentioned that the closure itself appends to `devices.value` when the `if devices.value.contains` returns false, and `devices.value` will contain the new item (as expected) when the append operation takes place in the closure.

**Comment by Gofake1** [comment]
This appears to be an issue with the way I'm using closures instead of an RAC bug.

**Comment by sharplet** [comment]
> Outside of the closure I modify devices.value:
>
> ```swift
> devices.value.append(aDevice)
> ```

I'm not sure if this will fix your issue, but FWIW I'd recommend changing this to:

```swift
devices.modify { $0.append(aDevice) }
```

The reason why the former is unsafe is described in more detail in https://github.com/ReactiveCocoa/ReactiveSwift/issues/269.
