### ISSUE TITLE
Bind custom property in swift

### ISSUE THREAD

**Issue by NikKovIos** [ReactiveCocoa/ReactiveCocoa#3414]
Hello!  
Could you please help with my issue. I've posted it to SO : http://stackoverflow.com/questions/42844339/bind-swift-propertys-value-to-viewmodels-property

I'm using Swift 2.3  
pod 'ReactiveCocoa', '~> 4'

**Comment by andersio** [comment]
For now it isn't possible to bind towards a field of a structure. You would need to write a full observer to achieve it, e.g.:

```swift
signal.observeValues { viewModel.item.id = $0 }
```
