### ISSUE TITLE
flatten what difference between switchToLatest?

### ISSUE THREAD

**Issue by longjianjiang** [ReactiveCocoa/ReactiveCocoa#3415]
I'm new to ReactiveCocoa. Now i learn some operation about signal; i know switchToLatest operation can get nexts from the latest signal it sends; but the following example confused me, cause it had the same solution as the operation flatten;

```
    RACSignal *signal2 = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        [subscriber sendNext:@"jiang"];
        [subscriber sendNext:@"longjian"];
        [subscriber sendCompleted];
        return nil;
    }];
    
    
    RACSignal *signal1 = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        [subscriber sendNext:@"nancy"];
        [subscriber sendNext:@"botwen"];
        [subscriber sendCompleted];

        return nil;
    }];

    RACSignal *signal = [RACSignal createSignal:^RACDisposable * _Nullable(id<RACSubscriber>  _Nonnull subscriber) {
        [subscriber sendNext: signal1];
        [subscriber sendNext: signal2];
        [subscriber sendCompleted];
        return nil;
    }];
    
    RACSignal *newSignal = [signal switchToLatest];
    [newSignal subscribeNext:^(id  _Nullable x) {
        NSLog(@"-=-=======-=%@", x);
    }];
```
These code whatever i use flatten or switchToLatest, the log is same; (nancy \n, botwen \n, jiang \n, longjian \n);

so, i want to know at what situation, switchToLatest can  get nexts from the latest signal?

**Comment by mdiep** [comment]
The output is the same in this case because the values on the inner signals are sent _immediately_.

If send the values asynchronously after some time, you'd only see the values from `signal2`.

**Comment by longjianjiang** [comment]
right! when i add the delay in signal1 or signal2, then sendNext in delay that won't be logged ; 

```
 RACSignal *signal2 = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        [subscriber sendNext:@"jiang"];
        
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
             [subscriber sendNext:@"longjian"];
        });
       
//        [subscriber sendCompleted];
        return nil;
    }];
    
    
    RACSignal *signal1 = [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
       
       
        [subscriber sendNext:@"nancy"];
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            
             [subscriber sendNext:@"botwen"];
        });
//        [subscriber sendCompleted];
        
        return nil;
    }];
    
    RACSignal *signal = [RACSignal createSignal:^RACDisposable * _Nullable(id<RACSubscriber>  _Nonnull subscriber) {
        [subscriber sendNext: signal1];
        [subscriber sendNext: signal2];
        [subscriber sendCompleted];
        
        return nil;
    }];
    
    RACSignal *newSignal = [signal switchToLatest];
    [newSignal subscribeNext:^(id  _Nullable x) {
        NSLog(@"-=-=======-=%@", x);
    }];
```
but in the same case, flatten operation always send the four logs; so at this example , picture explain switchToLatest is wrong?
<img width="710" alt="2017-03-19 11 02 54" src="https://cloud.githubusercontent.com/assets/15277239/24077781/c7c20c90-0c93-11e7-8126-61cb76a79ced.png">
cause, at the picture they say switchToLatest always send the latest signal's sendNext value;

at the same time, next picture explain switchToLatest also wrong?
<img width="902" alt="2017-03-19 11 07 10" src="https://cloud.githubusercontent.com/assets/15277239/24077810/56791d66-0c94-11e7-93c9-869191b7a885.png">
as you can see, when i not add delay, the log will as same as flatten.

So, the right explain to the operation  switchToLatest can be that?  when the inner signal sent immediately, it will as same as flatten; but if the the inner signal send the values asynchronously after some time, so values send delayed that won't be switchToLatest operation's returned signal sendNext value.

i don't know my explain is right? so please give me some help about this, thank you~

**Comment by andersio** [comment]
It is correct. But it is just the semantic of the `switchToLatest` operator. In your case, the behavior is a consequence of values being sent serially.

The subscription side effects (`didSubscribe`) of `signal1` and `signal2` are invoked in `signal` directly based on the semantic of `RACSubscriptionScheduler`. So until the subscription side effect of `signal1` returns, that of `signal2` would not be subscribed to.

**Comment by longjianjiang** [comment]
Thanks for your explain! but listen your words, i have two question.

first: your say until the subscription side effect of `signal1` returns, `signal2` would not be subscribed to. At there,  `signal` return mean this signal sendCompleted or just this signal's didSubscribe block return?   and this side effect i even don't know, i know the side effect is one signal be subscribed several times, the signal's didSubscribe block will excuse more times. May be this new kind of side effect connected with  the `takeUtil` operation that used in `switchToLatest`?

second: i use GCD send the signal in `signal` concurrently, and the result it logs as same as flatten too(four logs).
```
  RACSignal *signal = [RACSignal createSignal:^RACDisposable * _Nullable(id<RACSubscriber>  _Nonnull subscriber) {
        
        dispatch_async(dispatch_get_global_queue(0, 0), ^{
             [subscriber sendNext: signal1];
        });
       
        dispatch_async(dispatch_get_global_queue(0, 0), ^{
             [subscriber sendNext: signal2];
        });
       
//        [subscriber sendCompleted];
        return nil;
    }];
```
so, your say the behavior of switching to latest only if the signals to be flattened (not the values of these signals) are sent concurrently. i am confused, i don't know your say that behavior what exactly is? may be also is my explain above? and the two picture above , is there a picture can explain that behavior. If not, could you illustrate this behavior;

**Comment by andersio** [comment]
> At there, signal return mean this signal sendCompleted or just this signal's didSubscribe block return?

The `didSubscribe` block. It is invoked whenever an `RACSignal` is subscribed to.

> i am confused, i don't know your say that behavior what exactly is? may be also is my explain above?

The `switchToLatest` operator (which yields `signal`) subscribes to `signal1` and `signal2` **synchronously**. So the `didSubscribe` block of `signal1` must always happen before that of `signal2`. Since everything is sequential, and both `signal1` and `signal2` terminates within `didSubscribe`, and what you get is effectively a concatenated signal.

The situation changes when you introduce concurrency. When `signal2` is being sent to the flattened signal, it replaces `signal1` regardless of it being still active or not. So assuming if the enqueued `sendNext` on `signal1` happens after `signal2` has been sent, that `signal1` value would be dropped.

After all the key is whether concurrency is involved. These diagrams primarily illustrate how the operator behaves in a _concurrent_ environment, which doesn't exist if all your signals and their values are sent synchronously (i.e. your first very code snippet in this issue).

---

P.S. The statement is not entirely true. I apologize for the mistake. Better ignore it for less confusion.

> IOW, the behavior of switching to latest is exhibited only if the signals to be flattened (not the values of these signals) are sent concurrently.
