### ISSUE TITLE
I Cannot run ReactiveCocoa 2.5 in my project

### ISSUE THREAD

**Issue by zichenJack** [ReactiveCocoa/ReactiveCocoa#3421]
Xcode give me an error 
`/Users/yaotiancheng/Desktop/roadshow_ios/RoadshowFinance/Pods/Headers/Public/ReactiveCocoa/NSObject+RACPropertySubscribing.h:81:121: Cannot create __weak reference in file using manual reference counting`

when i put `#import <ReactiveCocoa/ReactiveCocoa.h>` in pch, it was error from xcode.
I use the CocoaPods  version is 1.2.0 and Xcode version is 8.3

**Comment by faimin** [comment]
[#2761](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2761)

**Comment by mdiep** [comment]
ReactiveCocoa 2.5 is no longer supported. If you're going to continue to use the Obj-C APIs, you should migrate to https://github.com/ReactiveCocoa/ReactiveObjC.

**Comment by zichenJack** [comment]
Thanks. I will try it
