### ISSUE TITLE
 Binary operator '<~' cannot be applied to operands of type 'BindingTarget<String?>' (aka 'BindingTarget<Optional<String>>') and 'String?'

### ISSUE THREAD

**Issue by jveryl** [ReactiveCocoa/ReactiveCocoa#3422]
I had: 

`import ReactiveCocoa

import Result

import ReactiveSwift

 match_info.reactive.text <~ self.viewModel?.infoStr  `

**Comment by mdiep** [comment]
`infoStr` would need to be a `Property` or something else that behaves as a `BindingSource`.
