### ISSUE TITLE
`continuousTextValues` doesn't emits new value on autocomplete

### ISSUE THREAD

**Issue by almassapargali** [ReactiveCocoa/ReactiveCocoa#3423]
I've a `gmm` snippet which expands to my email configured on iPhone keyboard settings. Now I want to implement classic login form where submit button enabled when both fields are valid. But that autocompletion doesn't emit new value on `continuousTextValues` so my submit button still disabled after I "entered" email.

**Comment by andersio** [comment]
Would you mind to try `UIControl.reactive.controlEvents(for:)` to see if other control events respond in this case? RAC currently registers only `editingChanged` for `continuousTextValues`.

**Comment by almassapargali** [comment]
Ok, here I've typed `almas` first, then removed it and used shortcut:

```
.allEditingEvents 
.allEditingEvents a
.editingChanged a
.allEditingEvents al
.editingChanged al
.allEditingEvents alm
.editingChanged alm
.allEditingEvents alma
.editingChanged alma
.allEditingEvents almas
.editingChanged almas
.allEditingEvents alma
.editingChanged alma
.allEditingEvents alm
.editingChanged alm
.allEditingEvents al
.editingChanged al
.allEditingEvents a
.editingChanged a
.allEditingEvents 
.editingChanged 
.allEditingEvents g
.editingChanged g
.allEditingEvents gm
.editingChanged gm
.allEditingEvents gmm
.editingChanged gmm
.allEditingEvents almassapargali@gmail.com
```

Please note that `. allEditingEvents` initially fires with field's value. But I think it fits the `continuousTextValues` wording.

**Comment by ikesyo** [comment]
ReactiveObjC already uses `.allEditingEvents` so that should be fine I think.

https://github.com/ReactiveCocoa/ReactiveObjC/blob/2.1.2/ReactiveObjC/UITextField%2BRACSignalSupport.m#L27
