### ISSUE TITLE
RACCommand's executionSignals's subscribeNext block or error's block execute more times? 

### ISSUE THREAD

**Issue by longjianjiang** [ReactiveCocoa/ReactiveCocoa#3424]
i use RACCommand to send a network request in a sendController, you can click this controller right `barbuttomitem`, then will execute a command; if success, this sendController will be dismissed;
but when fail, you know i add the log in the errors's subscribeNext block; i click `barbuttomitem` first time, the log will be show one time; but when i click at the second time, the log will be show two times; and it will always added one times if i continue click;

so, i want to know is there some solution to settle this problem? thanks!

**Comment by mdiep** [comment]
This question is for https://github.com/ReactiveCocoa/ReactiveObjC. Can you please ask it there?
