### ISSUE TITLE
[RACStream(Operations) reduceEach:]_block_invoke

### ISSUE THREAD

**Issue by wujunyang** [ReactiveCocoa/ReactiveCocoa#3427]
1：testLoginViewModel.m

- (RACSignal *)isValidUsernameAndPasswordSignal
{  
    return [RACSignal combineLatest:@[RACObserve(self, username), RACObserve(self, password)] reduce:^(NSString *username, NSString *password) {
        return @([self isValidEmail:username] && [self isValidPassword:password]);
    }];
}

//验证
- (BOOL)isValidEmail:(NSString *)data
{
    NSString *emailPattern =
    @"(?:[a-z0-9!#$%\\&'*+/=?\\^_`{|}~-]+(?:\\.[a-z0-9!#$%\\&'*+/=?\\^_`{|}"
    @"~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\"
    @"x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-"
    @"z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5"
    @"]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-"
    @"9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21"
    @"-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])";
    NSError *error = nil;
    NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:emailPattern options:NSRegularExpressionCaseInsensitive error:&error];
    NSTextCheckingResult *match = [regex firstMatchInString:data options:0 range:NSMakeRange(0, [data length])];
    return match != nil;
}

- (BOOL)isValidPassword:(NSString *)password
{
    return password.length >= 6;
}

2：I do unit testing on the above file，But it has been reporting the problem above；[RACStream(Operations) reduceEach:]_block_invoke

#import <Kiwi/Kiwi.h>

#import <ReactiveCocoa/ReactiveCocoa.h>
#import "testLoginViewModel.h"

SPEC_BEGIN(testLoginViewModelSpec)

describe(@"testLoginViewModel", ^{
    __block testLoginViewModel* viewModel = nil;
    
    beforeEach(^{
        viewModel = [testLoginViewModel new];
    });
    
    afterEach(^{
        viewModel = nil;
    });
    
    context(@"when username is wujunyang and password is freedom", ^{
        __block BOOL result = NO;
        
        it(@"should return signal that value is YES", ^{
            viewModel.username = @"wuyang@126.com";
            viewModel.password = @"123456";
            
            [[viewModel isValidUsernameAndPasswordSignal] subscribeNext:^(id x) {
                result = [x boolValue];
            }];
            
             [[theValue(result) should] beYes];
        });
    });
});

SPEC_END

Where is the problem?

**Comment by mdiep** [comment]
The Objective-C APIs have moved to https://github.com/ReactiveCocoa/ReactiveObjC. Please file a new issue there to ask your question.
