### ISSUE TITLE
NSButton inside NSStackView does not emit state

### ISSUE THREAD

**Issue by ohbargain** [ReactiveCocoa/ReactiveCocoa#3432]
After upgrade to 5.0.2, NSButton embedded inside NSStackView stopped emitting state signals. 

I will make pull request with test case.

Xcode version: 8.3
macOS version: 10.12.4

**Comment by andersio** [comment]
This is due to a KVO interoperability issue with the swizzling logic in `ActionProxy`. Fixed in #3435.
