### ISSUE TITLE
Re-export reactiveswift and result frameworks

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveCocoa#3450]
I'm certain I'm not the only one sickened by this on top of everything else that gets imported, whenever I need to use reactive stuff.

```swift
import ReactiveCocoa
import ReactiveSwift
import Result
```

ReactiveSwift is not always needed, but Result is pretty much required all the time only to make ReactiveCocoa work.

I'm suggesting to re-export ReactiveSwift in ReactiveCocoa and re-export Result in ReactiveSwift with `@_exported import …`, which turns out to be a hidden gem. Since using custom operators it may cause some issues, redeclaring them (not redefining, definitions re-exported fine) in exporting target solves the issue. 

With that, to import everything needed by ReactiveCocoa we can simply `import ReactiveCocoa`, same with ReactiveSwift.

**Comment by andersio** [comment]
Last time when we had a discussion on this, the main concern is still it being a private attribute i.e. subject to breaking at any time without official support.

/cc @ReactiveCocoa/reactiveswift

**Comment by sharplet** [comment]
The other concern is that last time I checked, `@_exported` didn't re-export operator declarations (only types). So if you wanted to use `<~`, you'd still have to know to `import ReactiveSwift`. This is a real bummer.

**Comment by ianbytchek** [comment]
Yes, operator drop is a bummer, but there's only one that ReactiveSwift uses and redeclaring it as suggested above solves the issue. Actual definitions are carried on. The total of two lines would do it:

```swift
@_exported import ReactiveSwift
infix operator <~ : BindingPrecedence
```

Consequences of it it being an unofficial / wip feature are completely understood. But every part of the api has been evolving over the past two and a half years. Some of my projects stop compiling even between minor swift updates when using official features and I don't mind this in the name of progress. But… But! `@_exported` is absolutely amazing and is a huge step towards decent module interdependency organisation. 

One of the most amazing libraries depending on it would make a statement and increase developer awareness, which should in return help it getting an official status faster. More to that, it doesn't introduce significant risks – dependency modules can always be manually specified like we do now in case if it stops working in the next release.

**Comment by andersio** [comment]
True. It is also used in Swift overlays.

**Comment by mdiep** [comment]
I'm 👎 on this for the same reasons as last time. It's liable to break, which is a burden for both maintainers and consumers.

I don't think multiple `import`s is the end of the world. It wouldn't even make my top 10 list of things I hate in Swift.

**Comment by andersio** [comment]
@ianbytchek Perhaps instead you may consider creating an umbrella framework on your end, and having it reexported all your dependencies. This way even if it breaks, you still get to work it around.
