### ISSUE TITLE
Deadlock caused by resignFirstResponder

### ISSUE THREAD

**Issue by szpako1** [ReactiveCocoa/ReactiveCocoa#3452]
At latest version (5.0.3). Related to this change:

> Continuous text signals of UITextField now emits the latest value for all editing events emitted. In other words, replacements due to autocompletions are now covered by the signals. (#3442 , kudos to @andersio)

Code snippet:

```
import UIKit
import ReactiveSwift
import ReactiveCocoa

internal class ViewController: UIViewController {

    @IBOutlet internal var textField: UITextField!
    
    internal var textProperty: MutableProperty<String> = MutableProperty("")
    
    internal override func viewDidLoad() -> Void {
        super.viewDidLoad()
    
        let textSignal = self
            .textField
            .reactive
            .continuousTextValues
            .skipNil()
            .filter({ (value: String) -> Bool in
                return (value.characters.count == 4)
            })
            .map { (value: String) -> String in
                self.textField.resignFirstResponder() //*** -[NSLock lock]: deadlock (<NSLock: 0x6000000d2b40> 'org.reactivecocoa.ReactiveSwift.Signal.sendLock')

                return value
        }
        
        self.textProperty <~ textSignal
    }
}
```

**Comment by andersio** [comment]
This does seem a legitimate use case. That's said we are limited by the UIControl API here, and we need a sensible cover-it-all default.

To revert to the old behaviour, you might use `controlEvents(for:)` which is what backs `continuousTextValues`.

**Comment by szpako1** [comment]
@andersio thanks for hint, `controlEvents(for: .editingChanged)` has resolved my issue.
