### ISSUE TITLE
Version 5.0.3 giving swift 3.0 compatibility issue

### ISSUE THREAD

**Issue by salmannetsol187** [ReactiveCocoa/ReactiveCocoa#3454]
I have made project using xcode 8 and swift 3.0 but installed ReactiveCocoa using CocoaPod (5.0.3). Its mentioned in its released notes that this version is fully compatible with siwft 3.0 but I am getting this alert
"The project “Pods” has targets that contain source code developed with an earlier version of Swift.
Choose “Convert” to update the source code in this project to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3."

**Comment by andersio** [comment]
Apparently you have other Pods that have not been updated to Swift 3. You cannot mix Swift 2 and Swift 3.

**Comment by salmannetsol187** [comment]
I just got one Pod dependency in my POD file. I have created new project. This is my Pod file:

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoaTesting' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveCocoaTesting

pod 'ReactiveCocoa', '~> 5.0.3'

end

**Comment by andersio** [comment]
I just tried with CocoaPods 1.2.1, and didn't manage to reproduce it. Try to update CocoaPods, and check with `xcode-select -p` to see if it points to Xcode 8 (if you haven't removed Xcode 7).

**Comment by salmannetsol187** [comment]
I was using an older version of CocoaPods (1.0.3) just updated to 1.2.1. Now its working fine. Thanks.
