### ISSUE TITLE
Build error: redefinition of module 'ReactiveCocoa'

### ISSUE THREAD

**Issue by singular78** [ReactiveCocoa/ReactiveCocoa#3455]
Xcode's verison is 8.3.2 and carthage's version is 0.20.1. Build command is 
`/usr/bin/xcrun xcodebuild -workspace /Users/user/project/SpechtLite/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa.xcworkspace -scheme ReactiveCocoa-macOS -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/ReactiveCocoa/5.0.0-alpha.3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build`

This is the build log :
> Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/module.modulemap:1:18: error: redefinition of module 'ReactiveCocoa'
framework module **ReactiveCocoa** {
               
> Library/Caches/org.carthage.CarthageKit/DerivedData/ReactiveCocoa/5.0.0-alpha.3/Build/Intermediates/ReactiveCocoa.build/Release/ReactiveCocoa-macOS.build/module.modulemap:1:18: note: previously defined here
framework module **ReactiveCocoa** {
                 

I am a beginner in OC and Swift. I have google the problem and spent hours in trying to solve it.

**Comment by mdiep** [comment]
It looks like you're using an old version of ReactiveCocoa that may not work with the latest Xcode. Can you try with ReactiveCocoa 5.0.3?

**Comment by singular78** [comment]
@mdiep Thank you! The problem doesn't occur when I use the ReactiveCocoa 5.0.3 instead of 5.0.0-alpha.3.
