### ISSUE TITLE
How to write function work like Signal.merge in pureswift

### ISSUE THREAD

**Issue by hprobotic** [ReactiveCocoa/ReactiveCocoa#3456]
Hi 
In our case, current application didn't use Reactive Cocoa yet, but i still wanna use function like Signal.merge to reduce some lines of code. 
Anyone have idea to write a function working like that but in pure swift?
Please let me know. 
Thanks 💯

**Comment by andersio** [comment]
[The implementation is open source](https://github.com/ReactiveCocoa/ReactiveSwift). Note that ReactiveCocoa is _not_ bundled with ReactiveSwift, so you could very well use ReactiveSwift and not to reinvent the wheel.
