### ISSUE TITLE
UIButton / UIBarButtonItem action pressed bindings?

### ISSUE THREAD

**Issue by larryonoff** [ReactiveCocoa/ReactiveCocoa#3462]
Hello Community,

My ViewModel applies view bindings by receiving special struct from view, see an example:

```swift

protocol MyViewModel {
      func setupBindings(_ bindings: MyViewBindings)
}

struct MyViewBindings {
    let showActivity: BindingTarget<Bool>
    let showError: BindingTarget<AnyError>

    let nameDidChange: Signal<String?, NoError>
    let detailsDidChange: Signal<String?, NoError>
}


class DefaultMyViewModel: MyViewModel {
    func setupBindings(_ bindings: MyViewBindings) {
        bindings.showActivity <~ state.isExecuting
        bindings.showError <~ state.errors.producer.skipNil()
    }
}
```

I need to add buttons presses as bindings into `MyViewBindings` struct.

The only way that I've found now to assign action to UIButton / UIBarButton is assigning `CocoaAction<Sender>` to `reactive.pressed` property of UIButton or UIBarButtonItem. This way doesn't work with my approach.

So I would like to open discussion about this case.

1. Introduce type erased CocoaAction? (I don't like the idea of CocoaAction in ViewModel, I'm trying to avoid using UIKit stuff there).
2. Introduce BindingTarget for UIButton / UIBarButtonItem?
3. Some other ideas?

**Comment by andersio** [comment]
You may use `reactive.controlEvents(.touchUpInside)` if you would like to avoid `Action` for whatever reasons.

**Comment by larryonoff** [comment]
Thank you for the answer!

Good point about `CocoaAction`. The problem is that it erases `Action` output and error types, but introduces it's own `Input = Sender`.

I thought about `reactive.controlEvents(.touchUpInside)`, but it this case I won't have `isEnabled` binding that Action / CocoaAction introduces. But It looks that my case can be easily connected with `Signal`.

What about introducing `BindingTarget` for UIButton / UIBarButtonItem?

**Comment by andersio** [comment]
> Good point about CocoaAction. The problem is that it erases Action output and error types, but introduces it's own Input = Sender.

It doesn't require `Input` to be `Sender`. You can supply a transform to map from `Sender` to the `Input`, provide a constant `Input`, or just wrap it if `Input` is `()`.
