### ISSUE TITLE
`UITextField.reactive.textValues` should cover `editingDidEndOnExit`.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3465]
When the text field is dismissed by the return key, `editingDidEndOnExit` is emitted by the text field instead of `editingDidEnd`.

**Comment by liscio** [comment]
To be clear: the OptionSet should be appended and not replaced. That is, `[.editingDidEnd, .editingDidEndOnExit]`

Correct?

**Comment by andersio** [comment]
Yeah.
