### ISSUE TITLE
Found a button event bug

### ISSUE THREAD

**Issue by leiyong316** [ReactiveCocoa/ReactiveCocoa#3471]
Jump between the application of the button will be repeated calls, I provided a demo. 
demo to WeChat as an example..
Use the function event method ok

[TestReactive.zip](https://github.com/ReactiveCocoa/ReactiveCocoa/files/1047286/TestReactive.zip)

**Comment by AbooJan** [comment]
I get this error too, in swift 4

**Comment by andersio** [comment]
Have you tried `primaryActionTriggered`?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
