### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 4.0

### ISSUE THREAD

**Issue by jerryzhoujw** [ReactiveCocoa/ReactiveCocoa#3473]
When I import this by Carthage,
Build with XCode 9, it always show the error as above "Module compiled with Swift 3.1 cannot be imported in Swift 4.0"

**Comment by andersio** [comment]
Try `--no-use-binaries`.

**Comment by mdiep** [comment]
What version of Carthage are you using?

**Comment by ZeroFactor** [comment]
I had this problem as well while using Carthage 0.23.0.  I appears that ReactiveSwift 1.1.3 is for Swift 3.1 and compiling for 3.2/4.0 doesn't change this.  

I changed to ReactiveCocoa 6.0.0 alpha 1 to use the new ReactiveSwift releases targeting Swift 3.2 and the error went away.

Carthage command:
`carthage update --platform iOS --no-use-binaries`

Xcode error:
`Module compiled with Swift 3.1 cannot be imported in Swift 4.0: /<Project Path>/Carthage/Build/iOS/ReactiveSwift.framework/Modules/ReactiveSwift.swiftmodule/x86_64.swiftmodule`
