### ISSUE TITLE
Abort trap 6 Cross-reference to module 'ReactiveSwift'

### ISSUE THREAD

**Issue by wordlessj** [ReactiveCocoa/ReactiveCocoa#3482]
I got this issue when upgrading one of my projects, so I created a new project with a simple call to reactive extension on `NotificationCenter`:

`NotificationCenter.default.reactive.notifications(forName: .UIApplicationDidEnterBackground)`

It compiles ok when importing ReactiveSwift only, but importing ReactiveCocoa at the same time produced an error:

```
1.	While type-checking 'viewDidLoad' at /Users/javier/Downloads/Reactive/Reactive/ViewController.swift:16:14
2.	While type-checking expression at [/Users/javier/Downloads/Reactive/Reactive/ViewController.swift:19:9 - line:19:100] RangeText="NotificationCenter.default.reactive.notifications(forName: .UIApplicationDidEnterBackground)"
3.	While loading members for extension of Reactive<Base> in module 'ReactiveCocoa'
4.	While deserializing 'makeBindingTarget' (FuncDecl #519)in 'ReactiveCocoa'
5.	While deserializing decl #1510 (XREF)in 'ReactiveCocoa'
6.	Cross-reference to module 'ReactiveSwift'
	... Scheduler
```

I have tried cleaning caches and set optimization level to whole module, but none of them works.

**Comment by mdiep** [comment]
Can you upload your sample project somewhere?

**Comment by wordlessj** [comment]
I used carthage to update ReactiveCocoa again (which I did several times) and the problem solved, then I copied the old framework back to the project and it works too. I think it's a cache issue, thanks for your reply @mdiep .
