### ISSUE TITLE
RxDataSources Port

### ISSUE THREAD

**Issue by alexpopov** [ReactiveCocoa/ReactiveCocoa#3488]
### Preamble

I used to use RxSwift, but I am now porting my code over to ReactiveSwift. I made extensive use of the wonderful [RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources) and I was wondering if 

  1. Anyone would have any use for it
  2. It's even possible to implement using ReactiveCocoa

If either one of these is answered "no", I'll just move on and use Changeset. If both are yes, I understand that ReactiveDataSources would be in a separate, optional framework. 

### Issues

  1. Rx{Swift,Cocoa}'s DelegateProxy isn't generic; in RxCocoa UITableView returns a TableViewDelegateProxy property in place of the ScrollViewDelegateProxy; I don't think this is possible with our DelegateProxy
  2. DelegateProxy is internal in ReactiveCocoa; I tried just copy-pasting it into my project for now
  3. `subscribeProxyDataSource` is missing; I don't even understand what it does 😔 

### Alternatives

I don't like using [Changeset](https://github.com/osteslag/Changeset) because equality isn't always how I want to decide whether an item changed. I could also fork Changeset and make it use some TableItemEquatable protocol instead of Equality, but I'd still be missing the other RxDataSources conveniences:

  1. functional UI{Table,Collection}View data source delegation
  2. Easy animation configuration
  3. The Section/Item model, instead of using the data items directly

Thanks for your time; please let me know how I could improve this issue if it carries any value.

**Comment by andersio** [comment]
There are progress making on it, but not as a direct port.

https://github.com/ReactiveCocoa/ReactiveSwift/pull/444
https://github.com/ReactiveCocoa/ReactiveSwift/issues/322

There are also a (partially) working implementation in ReactiveCollections, which I'd like to transfer to RAC at some point.
https://github.com/RACCommunity/ReactiveCollections/pull/19

**Comment by alexpopov** [comment]
Thanks for the response! I guess I'll use Changeset for now, and look into helping out any way I can. Should I close this issue, since my questions were answered?

**Comment by mdiep** [comment]
Yeah, I think let's go ahead and close this. 👍
