### ISSUE TITLE
`reactive` and Smart Key Path.

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3492]
As we approach the fall, we might want to start preparing ReactiveCocoa for Swift 4. Here is a proposal on how we would support Smart Key Path comprehensively:

1. Baseline support. #3489 

    All objects, both native and Objective-C, can be subscripted on `reactive` with writeable key paths as binding targets.

    ```swift
    object.reactive[\.property] <~ SignalProducer(value: "Welp")
    ```

1. UIControl/NSControl support as #3463.

    We would provide subscripts that can be used for uni- and bidirectional bindings, with configurable options like control events, continuousness vs discreteness, etc.

   Named variants continue to exist for now, as determined in #3477.

1. NSObject KVO support?

    The KVO extensions would support Smart Key Paths. #3491

    In addition to the baseline support, we may consider supporting a KVO shorthand. However, it has concerns in ambiguity if `KeyPath` is to be supported, instead of only `WritableKeyPath`.

    ```swift
    viewModel.name <~ model.reactive[\.property]
    ```

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
