### ISSUE TITLE
Compiler Errors with ReactiveCocoa 6.0.0 and Xcode 9 beta

### ISSUE THREAD

**Issue by BigSauce** [ReactiveCocoa/ReactiveCocoa#3497]
I'm getting a lot of compiler errors in ReactiveCocoa v 6.0.0.  ReactiveCocoa/ReactiveSwift was added to this brand new Xcode workspace.  The project was created by `Xcode version 9.0 beta 3 (9M174d)`, and the workspace was created using `pod install`.

Here are the relevant pods that were installed:
```
ReactiveCocoa (6.0.0)
ReactiveSwift (2.0.0)
Result (3.2.3)
```

These are the compiler errors that I receive in Xcode 9 beta 3 (the version of Xcode mentioned above):
![image](https://user-images.githubusercontent.com/1718470/29005537-42c539d2-7aab-11e7-867d-7fed900d6900.png)

Here is my `Podfile`:

```# Uncomment the next line to define a global platform for your project

def appPods

  pod 'ReactiveSwift'
  pod 'ReactiveCocoa'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
end

target 'Everything Random' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  appPods

  # Pods for Everything Random

  target 'Everything RandomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by ikesyo** [comment]
That is a known issue of CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/6791. Closing.

**Comment by BigSauce** [comment]
Got it.  Thanks for the info!
