### ISSUE TITLE
Xcode9 Beta5 crash

### ISSUE THREAD

**Issue by dev-xdyang** [ReactiveCocoa/ReactiveCocoa#3499]
Xcode version: Xcode9 Beta5
carthage: 0.24.0
Xcode command line tools: Xcode9 

when I run a simple demo like:
```
view.reactive
        .signal(for: #selector(view.didAddSubview(_:)))
        .take(duringLifetimeOf: view)
        .observeValues({ (views) in
            guard let vs = views as? [UIView] else { return }
            for v in vs {
                v.removeFromSuperview()
            }
        })
    }
```
ReactiveCocoa will crash every time

![screen shot 2017-08-11 at 5 16 44 pm 2](https://user-images.githubusercontent.com/7471748/29207774-f7ea5e66-7eb9-11e7-8579-5410e1dfe8a7.png)
![screen shot 2017-08-11 at 5 16 55 pm 2](https://user-images.githubusercontent.com/7471748/29207781-fb132a28-7eb9-11e7-9a20-f5edcc1631a0.png)
![screen shot 2017-08-11 at 5 17 20 pm 2](https://user-images.githubusercontent.com/7471748/29207784-feb06cae-7eb9-11e7-9d5c-a83227c50490.png)

**Comment by mdiep** [comment]
This will be addressed by https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3498.
