### ISSUE TITLE
Implicit declaration of function 'RAC' is invalid in C99

### ISSUE THREAD

**Issue by NikhilDevgire** [ReactiveCocoa/ReactiveCocoa#3505]
I have installed ReactiveCocoa through pod. previously it was v.4.4.2 and working perfectly for swift 2.3. But as now when I compiled it with xcode v.8.3.2 I am getting error. So I updated my Pod with 'Pod Update' Command. and Now it is showing ReactiveCocoa v.6.0.1 But still it is showing above error.

Please help.

**Comment by mdiep** [comment]
`RAC` is part of the Objective-C APIs which now live at https://github.com/ReactiveCocoa/ReactiveObjC
