### ISSUE TITLE
RAC 6.0.1 + ios11 + xcode 9  crash

### ISSUE THREAD

**Issue by RiuHDuo** [ReactiveCocoa/ReactiveCocoa#3514]
crash in follow
`
dyld: Symbol not found: __T013ReactiveSwift25SignalProducerConvertibleMp
  Referenced from: /private/var/containers/Bundle/Application/DADA61B0-F959-49B2-95ED-BEE1B6B85775/Victini.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
  Expected in: /private/var/containers/Bundle/Application/DADA61B0-F959-49B2-95ED-BEE1B6B85775/Victini.app/Frameworks/ReactiveSwift.framework/ReactiveSwift
 in /private/var/containers/Bundle/Application/DADA61B0-F959-49B2-95ED-BEE1B6B85775/Victini.app/Frameworks/ReactiveCocoa.framework/ReactiveCocoa
`

**Comment by andersio** [comment]
It feels like a corrupted build. You might want to clear `~/Library/Developer/Xcode/DerivedData/` and see how it goes.

**Comment by Exp-AngeloLobo** [comment]
I have a similar issue and tried clearing derived data a few times. This didn't help.

**Comment by akashivskyy** [comment]
If you're installing using Carthage, did you add `ReactiveSwift.framework` to `carthage copy-frameworks` build phase?

**Comment by Exp-AngeloLobo** [comment]
Yes, I did. I added `ReactiveSwift.framework`,  `ReactiveCocoa.framework` and `ReactiveObjc.framework`. Add for good measure added `Result.framework` too.

**Comment by andersio** [comment]
Could you share your Cartfile and the resolved Cartfile?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄

**Comment by AngeloGLobo** [comment]
Thank you all for your help on this! Apologies for not following up at the time - there were several issues then. Also, my team moved ahead with all the new changes on iOS so we never did get around to solve this.
