### ISSUE TITLE
Can't compile RAC

### ISSUE THREAD

**Issue by antonincharvat** [ReactiveCocoa/ReactiveCocoa#3519]
Xcode 9 + Swift 4 project.
Tried all last releases of RAC, none of them works.
Can't even compile the project because of errors in RAC. Getting following errors in the pod:
![snimek obrazovky 2017-09-21 v 13 06 58](https://user-images.githubusercontent.com/19424035/30693081-56af315e-9ece-11e7-84b7-5d94920d270c.png)

**Comment by andersio** [comment]
6.0.2 and 6.1.0 alpha 2 are supposed to fix this, and I heard that it works. Have you tried these versions?

**Comment by stevegomez17** [comment]
NSObject+intercepting+Swift

**Comment by antonincharvat** [comment]
Yes, I tried both of them, I clean the project, delete derived data, but the errors keep showing up.
![snimek obrazovky 2017-09-21 v 16 31 43](https://user-images.githubusercontent.com/19424035/30701453-98055626-9eea-11e7-90ab-cfb1c9fb00a8.png)

**Comment by alexpopov** [comment]
Similar issues but I have more errors. ReactiveCocoa 6.0.2 through Cocoapods 
<img width="80" alt="Cocoapods errors" src="https://user-images.githubusercontent.com/903856/30720369-ff369260-9edb-11e7-8b4f-a61b023f76e1.png">

**Comment by andersio** [comment]
I will investigate. In the meantime, you may override the Swift version for RAC in your Podfile.
https://github.com/CocoaPods/CocoaPods/issues/6791

**Comment by antonincharvat** [comment]
Apparently this temporary solution with overriding Swift version to 3.2 for RAC is working, thank you. I will be regularly checking new releases of RAC to have working Swift 4 version asap.

**Comment by andersio** [comment]
7.0.0 alpha 2 should now work with both Swift 3.2 and Swift 4.0. Feel free to report if you still encounter any issue.
