### ISSUE TITLE
crash on iphone5s with iOS 8.1，don't appear on iOS 8.3

### ISSUE THREAD

**Issue by FlutterDown** [ReactiveCocoa/ReactiveCocoa#3523]
RAC:6.0.2
RAS: 2.0.1

will crash with log:
fatal error: Unexpected pthread mutex error code: 11: file /Users/xcar/development/***/Pods/ReactiveSwift/Sources/Atomic.swift, line 190

**Comment by ikesyo** [comment]
This is already fixed in RAC 6.1.0-alpha.2 (RAS 2.1.0-alpha.2).

https://github.com/ReactiveCocoa/ReactiveSwift/pull/508

**Comment by FlutterDown** [comment]
i have updated to RAC 6.1.0-alpha.2, but same crash appear, and 5s is 64-bit. @ikesyo

**Comment by ikesyo** [comment]
I'm not sure 😕

**Comment by drumih** [comment]
@ikesyo i have similar issue with iPhone 5s iOS 8.4.1
RAC 6.1.0-alpha.2
it can be fixed by using `PTHREAD_MUTEX_NORMAL` for DEBUG and non DEBUG (if it possible)

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
