### ISSUE TITLE
Swift 4 migration issue: Nil is not compatible with expected argument type 'IMP' (aka 'OpaquePointer')

### ISSUE THREAD

**Issue by joelorenz20** [ReactiveCocoa/ReactiveCocoa#3525]
Hi

I am trying to migrate to swift 4 but I am caught up with these error messages.
Any idea how I can fix this?

Thanks

<img width="628" alt="screen shot 2017-10-03 at 8 42 31 pm" src="https://user-images.githubusercontent.com/11159818/31125671-a90f8c6c-a87b-11e7-9a49-e94e3f662703.png">

**Comment by antonincharvat** [comment]
Solving the same issue few days ago. Apparently there are still some issues with RAC and Swift 4. We have figured out a temporary solution. Check out my thread: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3519

**Comment by andersio** [comment]
ReactiveCocoa uses Swift 3.2, and apparently CocoaPods has problems in supporting mixed source use cases. As mentioned by @antonincharvat there is an intermediate solution linked in #3519.

**Comment by joelorenz20** [comment]
Fix in [#3519](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/3519) seems to solve this issue. 

Thanks @antonincharvat & @andersio

**Comment by alper** [comment]
Ah, Swift 4 support means that it works _with_ swift4 project, not that the project itself has migrated to swift4!? Now I get it.

**Comment by andersio** [comment]
@alper Yes. Swift 3.2 frameworks work with anything that is built by the same compiler regardless of the language modes used, and the interoperability does work well for Carthage and Xcode project users.

It is just CocoaPods who hasn’t managed to support it properly.
