### ISSUE TITLE
crash on iphone5s with iOS 8.1，don't appear on iOS 8.3

### ISSUE THREAD

**Issue by FlutterDown** [ReactiveCocoa/ReactiveCocoa#3528]
RAC:6.0.2 or 6.1.0-alpha.2
RAS: 2.0.1 or RAS 2.1.0-alpha.2

will crash with log:
fatal error: Unexpected pthread mutex error code: 11: file /Users/xcar/development/***/Pods/ReactiveSwift/Sources/Atomic.swift, line 190

**Comment by ikesyo** [comment]
Please file an issue on ReactiveSwift, not on ReactiveCocoa.
