### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

### ISSUE THREAD

**Issue by laizhouzhang** [ReactiveCocoa/ReactiveCocoa#3530]
xcode 9.0.1  , The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

**Comment by andersio** [comment]
Which version are you using?

**Comment by laizhouzhang** [comment]
6.0.1, use pod

**Comment by NachoSoto** [comment]
The version is set in the project, so this must be a Podspec issue.
