### ISSUE TITLE
"take(until: cell.reactive.prepareForReuse)" get crash  

### ISSUE THREAD

**Issue by AbooJan** [ReactiveCocoa/ReactiveCocoa#3534]
here is my code in UITableView datasource "cellForRowAt" function
```
 cell.btn.reactive.controlEvents(.touchUpInside).take(until: cell.reactive.prepareForReuse).observeValues({ (_) in
     // do something
});
```

it is well in swift 3.1;

but when I update swift 4, it get crash
```
[Gold.MsgCell prepareForReuse]: unrecognized selector sent to instance 0x7fae97864a00
2017-11-03 10:16:16.947032+0800 
Gold[10823:333074] invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution.
libc++abi.dylib: terminate_handler unexpectedly threw an exception
```

---
OS: `ios 11.1`
rac: `6.0.2`
swift: `4.0`
xcode: `9.1`

**Comment by andersio** [comment]
Could you possibly have used other ObjC swizzling framework? I didn't manage to reproduce it under the Swift 4.0 language mode.

**Comment by AbooJan** [comment]
Maybe it is crash by my changes. 
Because I pod the version 6.0.2 in swift 4, xCode 9 build fail, and I change some code as Xcode fix tips😂
