### ISSUE TITLE
Xcode9 + RAC5 + some bindings - Infinite recursion

### ISSUE THREAD

**Issue by ziryanov** [ReactiveCocoa/ReactiveCocoa#3535]
osx + Xcode9.1 + ReactiveCocoa 5.0.4
![settingscontroller swift 2017-11-09 17-41-16](https://user-images.githubusercontent.com/750109/32608282-500ee9ac-c575-11e7-8532-246827942bb6.png)
![actionproxy swift 2017-11-09 17-42-52](https://user-images.githubusercontent.com/750109/32608349-897148ac-c575-11e7-87c7-839fe1342866.png)
![nsobject lifetime swift 2017-11-09 17-43-28](https://user-images.githubusercontent.com/750109/32608355-8e0213f6-c575-11e7-93f1-348ca975c4bc.png)

**Comment by ziryanov** [comment]
another crash
![editdailyupdatecontroller swift 2017-11-09 17-50-34](https://user-images.githubusercontent.com/750109/32608693-a0fd7152-c576-11e7-8253-c608b98f2924.png)
![objc runtimesubclassing swift 2017-11-09 17-50-52](https://user-images.githubusercontent.com/750109/32608710-abe5bafc-c576-11e7-917a-c2cf3dfbb449.png)

**Comment by ziryanov** [comment]
Am I doing something wrong?

**Comment by andersio** [comment]
This was a resolved issue in ReactiveCocoa 6.0.1. Please upgrade to the latest versions.
