### ISSUE TITLE
Crash in ObjC+RuntimeSubclassing.swift

### ISSUE THREAD

**Issue by jeroenzonneveld** [ReactiveCocoa/ReactiveCocoa#3537]
Hi there,

I've got a crash in the function:
`internal func swizzleClass(_ instance: NSObject) -> AnyClass`

Line 
`if let existingClass = objc_getClass(cString) as! AnyClass?`

In the file `ObjC+RuntimeSubclassing.swift`. Is there any reason why this line is forced instead to be optional?

The problem is since we used Xcode 9.

Thanks!

**Comment by andersio** [comment]
The issue had been resolved in ReactiveCocoa 6.0.1.
