### ISSUE TITLE
DynamicProperty of optional property: Fatal error on force unwrap

### ISSUE THREAD

**Issue by iv-mexx** [ReactiveCocoa/ReactiveCocoa#3547]
Consider the following snippet:

```
class MyObject: NSObject {
    @objc dynamic var name: String?

    init(name: String) {
        self.name = name
    }
}

let object = MyObject(name: "Joe")

let dynamicProperty = DynamicProperty<String?>(object: object, keyPath: "name")
dynamicProperty.producer.startWithValues { print("Dynamic: \($0)")}
object.name = "Jack"
object.name = nil
```

When setting the property to nil, the following crash occurs 
> Fatal error: Unexpectedly found nil while unwrapping an Optional value

in [NSObject+KeyValueObserving.swift:79](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/NSObject%2BKeyValueObserving.swift#L79)

```
init(object: NSObject, keyPath: String) {
  self.producer = object.reactive.producer(forKeyPath: keyPath).map { $0 as! Value }
}
```

This was introduced in #3461 that was intended to strip the optionality of DynamicProperty - but what about DynamicProperties that are Optional to begin with?

**Comment by andersio** [comment]
Oh dear, the limits of optional bridging. This needs an overload.

**Comment by mdiep** [comment]
And a test! 😅

**Comment by iv-mexx** [comment]
I'll take a look
