### ISSUE TITLE
How to parallelize some work

### ISSUE THREAD

**Issue by gbuela** [ReactiveCocoa/ReactiveCocoa#3551]
I want to do some work in parallel that is not network requests and I can actually write it as a synchronous function like someOperation() below. I would expect to see the print's from the two producers mixed but it appears the calls to the function are sequential. Am I missing something, or am I just supposed to resort to GCD for this? Thx
  
    func parallelWork() {
        let spA = SignalProducer<String, NoError> { return someOperation(id: "A") }
        let spB = SignalProducer<String, NoError> { return someOperation(id: "B") }

        SignalProducer.merge(spA, spB).collect().startWithValues { values in
            dump(values)
        }
    }
    func someOperation(id: String) -> String {
        for i in 0...100 {
            print("\(id) \(i)")
        }
        return "Done with " + id
    }

**Comment by sharplet** [comment]
> Am I missing something, or am I just supposed to resort to GCD for this?

You're not missing anything, `Signal` and `SignalProducer` don't impose any specific threading/queueing semantics.

One way to add parallelism in your example would be to use the `start(on:)` operator on each individual producer to force the work to occur on the queue of your choice:

```swift
let spA = SignalProducer<String, NoError> { return someOperation(id: "A") }
  .start(on: QueueScheduler(queue: queueA))
let spB = SignalProducer<String, NoError> { return someOperation(id: "B") }
  .start(on: QueueScheduler(queue: queueB))
```

Another would be to have `someOperation` instead return a `SignalProducer<String, NoError>`, and build the parallelism into the implementation.
