### ISSUE TITLE
How to use RAC to get UITextField input characters？

### ISSUE THREAD

**Issue by yasencoder** [ReactiveCocoa/ReactiveCocoa#3552]
How to use RAC to get UITextField input characters, and according to the input characters to decide whether to allow input?

**Comment by andersio** [comment]
Presumably what you want is [this delegate method](https://developer.apple.com/documentation/uikit/uitextfielddelegate/1619599-textfield). RAC does not have any feature that builds on top of this (yet).

**Comment by pjocer** [comment]
`rac_signalForSelector:fromProtocol:` maybe works to you

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
