### ISSUE TITLE
Consider additional notes on trigger and signal for selector

### ISSUE THREAD

**Issue by iby** [ReactiveCocoa/ReactiveCocoa#3558]
Spent good part of this morning figuring out what's wrong with this code:

```swift
class MyView: NSView {
    @objc func foo() { Swift.print("foo") }
}

let view = MyView()

view.reactive.trigger(for: #selector(view.foo))
    .observeValues({ Swift.print("Intercepted foo") }) // Not invoked… 🤔

view.reactive.trigger(for: #selector(view.viewDidHide))
    .observeValues({ Swift.print("Intercepted viewDidHide") }) // Works as expected…

view.foo()
view.viewDidHide()
```

Those who jumped from Objective-C into Swift will probably see the issue right away, others not involved with Objective-C runtime as much will start thinking… For ReactiveCocoa to work `foo` must also be `dynamic`. I propose to mention this on all interception-related docs to ease off suffering of stupid ones.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
