### ISSUE TITLE
MutableProperty with tuple compiled in 3.2 no longer compiles in 4.0

### ISSUE THREAD

**Issue by sonnytron** [ReactiveCocoa/ReactiveCocoa#3559]
The code:  
  
    fileprivate let _requestState = MutableProperty<(canBegin: Bool, token: String?)>(canBegin: true, token: nil)  
  
  
Compiled fine in 3.2, trying to update to 4.0 and getting "Extra argument 'token' in call".  
Google search says that [tuple transformations are not supported in Swift 4](https://github.com/ReactiveX/RxSwift/issues/1473).  
I don't want to refactor where this variable is used, I'd like to rewrite it in this line only so that it will compile. Please help, thank you.

**Comment by ikesyo** [comment]
This should work as described in [the link](https://github.com/ReactiveX/RxSwift/issues/1473) you posted above.

`MutableProperty<(canBegin: Bool, token: String?)>((canBegin: true, token: nil))`
