### ISSUE TITLE
Inconsistent trigger for selector behaviour

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveCocoa#3560]
Interesting case! I need to observe a property value whilst it's being set, so when new value is set, I want to dismiss all observers on old one and start observing the new one. I use setter selector trigger signal to `take(until: …)`, which works well, but:

![2018-01-11 12 15 00](https://user-images.githubusercontent.com/1086845/34815015-396b4580-f6c9-11e7-9704-28c8f3a692fd.gif)

After initial interceptor setup signals get sent immediately after being observed, which is unexpected behaviour, unless you figure out what's going on behind scenes. I can hack around this with something like this:

![2018-01-11 12 15 24](https://user-images.githubusercontent.com/1086845/34815019-3e2a512e-f6c9-11e7-9a56-41225ea3fbe2.gif)

It would be great for this behaviour to be consistent. Doesn't look like a simple job from interception implementation perspective, but maybe during interceptor setup it could check stack trace and immediately send signal if selector is being currently invoked? Or maybe there's a better way?

**Comment by ianbytchek** [comment]
Alternatively, observing key path change signals solves my case more elegantly, but feels like an overkill. The original issue remains, though.

![2018-01-11 12 46 30](https://user-images.githubusercontent.com/1086845/34816219-b6b56a58-f6cd-11e7-944c-e6dc8bebc597.gif)

**Comment by andersio** [comment]
Swift property observers are invisible to ObjC even if you mark it as `dynamic`.

**Comment by ianbytchek** [comment]
That's a fact.

**Comment by andersio** [comment]
The behaviour is correct here, because the trigger observation is set up _after_ the setter is invoked, i.e. in `didSet`. So since the setting has happened, it can only see values in the future.

Based on the snippet, you could very well establish one observation before all mutations could ever happen, and then you could catch all the changes. If you want to do some other work derived from the values over time, you could explore `flatMap` for the purpose, instead of managing it yourself.

Using KVC is perfectly fine too. TBH both KVC and RAC interception use the same technique.

**Comment by ianbytchek** [comment]
Agree and understand. Technically it makes perfect sense, but from usability perspective this specific case looks out of line. End users shouldn't be concerned with implementation and expect it to do what it says – send signal after invocation, which it does inconsistently as shown above. Obviously not a critical issue, but an issue never the less, don't you think?

> TBH both KVC and RAC interception use the same technique.

I didn't check out implementation in detail, but judging by results something is definitely done differently. It works as expected and solves my case – makes me happy.

> If you want to do some other work derived from the values over time, you could explore flatMap for the purpose, instead of managing it yourself.

Cool! Would [OnlineSearch.md](https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/Example.OnlineSearch.md#making-network-requests) be the best example?

**Comment by ianbytchek** [comment]
> The behaviour is correct here, because the trigger observation is set up after the setter is invoked, i.e. in didSet. So since the set has already happened, the observation never gets to see it.

Actually, I think this is not what happening. Correct if I'm wrong, but `didSet` is a part of setter and what happens is not precisely that. Based on my understanding and results:

1. When `trigger(for: …)` is first invoked the interceptor is set up and overrides setter.
2. If interceptor is setup within selector it misses this initial invocation and doesn't send signal.
3. On second invocation it catches it and sends two signals – see how old values are different.
4. Because we take only first signal, things get straightened out on 3rd invocation.

**Comment by andersio** [comment]
`didSet` is not part of the setter. It happens _after_ the setter is invoked at the call site. In this case it is after `objc_msgSend` is called with `setFoo:` plus the value, which in turn means both the message forwarding routine RAC relies on, and the backing synthesised setter (that accesses the ivar).

**Comment by ianbytchek** [comment]
Ok, then by that logic taking observer into `willSet` would work, because it would be either before setter invocation or as part of it. But result is the same.

![2018-01-12 01 31 16](https://user-images.githubusercontent.com/1086845/34848469-52933314-f738-11e7-876c-3c7596ffcd7c.gif)

**Comment by andersio** [comment]
Welp, apparently I was wrong. Swift did include the property observer in the synthesised setter.

<img width="421" alt="screen shot 2018-01-13 at 5 11 22 pm" src="https://user-images.githubusercontent.com/11806295/34908276-d88bf2ec-f884-11e7-962f-2de6d0fde7c6.png">

**Comment by andersio** [comment]
In this case, it is an ordering issue. At the first time `foo.set` is called, the interception has not been set up yet. So the ObjC runtime resolves the selector directly to the synthesised setter, which would then return to the call site directly. The interception only kicks in when the second time `foo.set` is called, where the ObjC runtime resolves it to the message forwarding mechanism.

**Comment by andersio** [comment]
Either way, you could very well avoid `willSet` and `didSet` directly, which is what FRP meant to offer in the first place.

```swift
object.producer(forKeyPath: #keyPath(object.foo))
    .flatMap(.latest) { foo in
        // Do something asynchronous that would be cancelled
        // & restarted in case there is a new value.
    }
```
