### ISSUE TITLE
Observing UserDefaults key for change does not work with `.`'s in the key

### ISSUE THREAD

**Issue by nnascim** [ReactiveCocoa/ReactiveCocoa#3569]
**Line 187** in **NSObject+KeyValueObserving.swift**:

`let components = keyPath.components(separatedBy: ".")`
in
```
static func observe(
		_ object: NSObject,
		keyPath: String,
		options: NSKeyValueObservingOptions,
		action: @escaping (_ value: AnyObject?) -> Void
	) -> AnyDisposable { }

```

Separating the keyPath String by components is not compatible with UserDefaults:

```
let key = "io.chuva.token"
let producer = UserDefaults.standard.reactive.producer(forKeyPath: key)
```
The key is just a String and as such is valid for UserDefaults, however, the above producer will not emit any values.

I have included a test file. Test `testKeyWithDotIsObserved()` fails.
[DefaultsTests.swift.txt](https://github.com/ReactiveCocoa/ReactiveCocoa/files/1715135/DefaultsTests.swift.txt)

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
