### ISSUE TITLE
Umbrella header 'ReactiveCocoa.h' not found

### ISSUE THREAD

**Issue by SHERLOCKG** [ReactiveCocoa/ReactiveCocoa#3574]
framework module ReactiveCocoa {
	umbrella header "ReactiveCocoa.h"      //there report an error“Umbrella header 'ReactiveCocoa.h' not found”
	private header "ObjCRuntimeAliases.h"

	export *
	module * { export * }
}

Somebody in this question？

**Comment by Jeroenbb94** [comment]
ReactiveCocoa doesn't support Cocoapods 1.5.0 yet, so you'll still need to use `use_frameworks!` in your pod file. The new Cocoapods property `modular_headers` doesn't do the trick for ReactiveCocoa yet.

**Comment by IzzetYildirim** [comment]
Hi @Jeroenbb94 when do you suppose `modular_headers` support will be released? It is going to be a huge improvement in terms of launch time performance for projects like ours which have plenty of third party Swift libraries along with ReactiveCocoa.

**Comment by mishagray** [comment]
I think I have a fix candidate here: #3590
Would love people to test it themselves.

You can add 
```     pod 'ReactiveCocoa', :git => 'https://github.com/mishagray/ReactiveCocoa.git', :branch => 'cocoapod-static-lib' ```
to your cocoa pod file to test it..

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
