### ISSUE TITLE
take(until: continuousTextValues)

### ISSUE THREAD

**Issue by nmtitov** [ReactiveCocoa/ReactiveCocoa#3577]
I am trying to cancel networking requests on UISearchBar input. I have `searchStrings` signal (similar to Online Search tutorial):

    let searchStrings = searchController.searchBar.reactive.continuousTextValues.skipNil().debounce(0.3, on: QueueScheduler.main).logEvents()

Next, the request signal producer:

````
let searchResults = searchStrings.flatMap(.latest) { (text: String) -> SignalProducer<[GiveawaysItem], MoyaError> in
    return self.http.reactive.request(.searchGiveaways(term: text)).take(until:[???]
````

But I don't get what should be used as an argument for `until:`. Seems I have to map `searchStrings` to `<(), NoError>` signal, but I don't understand how to do that. 

Could you give me a hint? Thanks in advance.

**Comment by nmtitov** [comment]
Does this look like a good idea?
````
     let voidSignal = searchStrings.map { _ -> Void in
         return
     }
     [...].take(until: voidSignal)
````

**Comment by nmtitov** [comment]
Turns out `flatMap(.latest)` cancels previously started requests automatically, so `take(until:)` is not needed here?

**Comment by sharplet** [comment]
Yep, cancelling in-progress search requests is a pretty common use case for `flatMap(.latest)`. I usually end up using `take(until:)` for handling cancellation on some other event, say when a user taps a cancel button, or dismisses a screen.

It sounds like you've resolved your issue, so I'm going to close this, but feel free to reopen if you need to.
