### ISSUE TITLE
Installing KVO through producer(forKeyPath:) corrupt memory

### ISSUE THREAD

**Issue by zintus** [ReactiveCocoa/ReactiveCocoa#3578]
Basically, something is wrong in deinit sequence, consider following playground. Paste this code into ReactiveCocoa-iOS/Sandbox file.

A little bit of background. I've came up with raw KVO API, because i need to implement recursive signal, changing object property. Recursive signals aren't supported so, only way is out of reactive land. Maybe there is a better way and i'm doing it wrong?

```
import Result
import ReactiveCocoa
import ReactiveSwift
import UIKit

_ = {
    let object = NSObject()
    
    object.reactive.producer(forKeyPath: #keyPath(NSObject.hash)).start()
    let observation = object.observe(\.hash, options: [.initial, .new]) { (_, _) in }
    
    object.reactive.lifetime.observeEnded {
        observation.invalidate()
    }
}()
```

**Comment by zintus** [comment]
Gentle bump @andersio @mdiep

**Comment by andersio** [comment]
This appears to be a clash between our implementation and the swizzling done in the Foundation overlay.

**Comment by andersio** [comment]
It appears that if you don't invalidate the observation as `lifetime` ends, the error doesn't happen. It is probably an issue in deinit order.

**Comment by andersio** [comment]
While I am able to patch the issue for iOS 11.0, macOS 10.13 and friends, what complicates the situation is that:

1. Earlier OS versions do not support auto-cleanup of KVO observers.
2. The test case for this issue is therefore non-applicable to earlier OSes.
3. The typed KVO API is therefore _not compatible_ with the RAC Lifetime API, since `NSKeyValueObservation` holds a weak reference to the observed object, which would be `nil` during the deinitialisation phase.

I think the best course of action is moving #3491 forward despite it utilising the underscored API. Given the upcoming ABI freeze, it should be part of the ABI anyway.

cc @mdiep

**Comment by mdiep** [comment]
Trying to follow along here, but I'm not nearly as familiar with the internals of this.

Is there a reason that `KeyValueObserver` has to use an `unowned(unsafe)` reference to the observed object instead of a `weak` reference? Would switching to a `weak` one solve the issue here?

**Comment by andersio** [comment]
@mdiep Weak references to an object are `nil` when the object is deinitialising. This means that at the time `-dealloc` is invoked, we can’t remove the KVO observer through a weak reference, _unless_ we poke the object directly. Hence the use of `unowned(unsafe)`.

**Comment by andersio** [comment]
Switching to `weak` solves the issue on iOS 11.0 (and friends). But it doesn’t help earlier OSes since they would throw an exception for undetached observers at deinitialisation.

**Comment by zintus** [comment]
Could you give a little more detail on why that happens?

If i enable zombie objects, i see double release on `NSKeyValueObservation` in test case above. Why setting up `KeyValueObserver`, and cleaning up it later, results in removing of KVO observer setup through different API?

**Comment by andersio** [comment]
> double release on NSKeyValueObservation in test case above.

That part I haven't figured out.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
