### ISSUE TITLE
Cannot rebuild the module with Swift 4.1

### ISSUE THREAD

**Issue by Maxador** [ReactiveCocoa/ReactiveCocoa#3582]
I'm using ReactiveCocoa 6.0.2 and ReactiveSwift 2.0.1 and trying to build with Carthage.

**Comment by mdiep** [comment]
You might need to upgrade to newer releases. But you'd need to include more detail here to get help.

**Comment by Maxador** [comment]
Yeah I was afraid of upgrading but there's were not many breaking changes. I did upgrade and everything works fine now. However, does that mean ReactiveCocoa 6 and ReactiveSwift 2 will be locked to Swift 3 and 4.0? Maybe that should be documented.

**Comment by andersio** [comment]
We did list supported Swift versions for every release in https://github.com/ReactiveCocoa/ReactiveCocoa/releases. The problem in general is that both SDK breaking changes and compiler regressions might lead to breakage in older versions, and it is kinda pointless for us to maintain multiple branches, both in terms of resources and the lack of library evolution support at the moment.
