### ISSUE TITLE
Question: How to ensure only a single tap is responded to on a UIButton?

### ISSUE THREAD

**Issue by nasht** [ReactiveCocoa/ReactiveCocoa#3592]
Apologies if this is obvious - I'm still relatively new to ReactiveSwift...

Right now I have some code like this

``` 
myButton.reactive
            .controlEvents(.touchUpInside)
            .observeValues  { 
 <some async operation here>
}

```
If I tap the button multiple times, the code above will reasonably run for each tap.

What is the best (reactive) way to disregard multiple taps, and respond to a single tap only? I can solve this using semaphores, and setting the button disabled / enabled, but surely there is a more elegant way to do it?
 
I've tried using `debounce(X)` but that lets me keep tapping the button for a while, and can still sometimes yield multiple taps.

Also to be clear, I don't want the signal to run _only once_, so skipDuplicates() doesn't seem quite right either...

Many thanks!

**Comment by sharplet** [comment]
Is your goal to prevent the async code from running multiple times in parallel? The way I'd recommend doing that is to wrap your async work in a `SignalProducer`, and then use an `Action` to bind it to your button.

First define your async work in a function that returns a new `SignalProducer`:

```swift
func work() -> SignalProducer<Foo, MyError> {
  // ...
}
```

Then wrap it in an action:

```swift
let workAction = Action(execute: work) // Action<(), Foo, MyError>
```

Now you can bind it to your button:

```swift
func viewDidLoad() {
  super.viewDidLoad()

  workButton.reactive.pressed = CocoaAction(workAction)
}
```

Whenever the button is tapped, the action will be executed. The button's `isEnabled` property is also bound to the action's `isEnabled` property, meaning that it is disabled while the work is executing. You can read a bit more about `Action` here: https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Documentation/ReactivePrimitives.md#action-a-serialized-worker-with-a-preset-action.

There are other ways to compose signals and signal producers, but for the purposes of binding work to a button, `Action` is a really useful tool. (For example, it allows you to display/handle errors separately via its `errors` signal.)

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
