### ISSUE TITLE
Question about renamed classes (4.0 to 7.0)

### ISSUE THREAD

**Issue by NikKovIos** [ReactiveCocoa/ReactiveCocoa#3594]
Good day for everybody. This issue is a question. I just want those, who have enough of free time and some kindness, to help me upgrade code, written in ReactiveCocoa 4.0 to 7.0
Next you would see pieces of code, that i can hardly find out how to update. I would be very grateful if you would help =)

1.
```swift
func onEvent(event: (ReactiveCocoa.**Event**<Self.Value, Self.Error> -> Void)) -> SignalProducer<Self.Value, Self.Error> {
        return on(event: event)
    }
No type named 'Event' in module 'ReactiveCocoa'
```

2.
```swift
let property = MutableProperty<T>(getter())
        property.producer.startWithNext {
            setter($0)
        }
Value of type 'SignalProducer<T, NoError>' has no member 'startWithNext'
```

3.
```swift
refreshControl.rac_signalForControlEvents(.ValueChanged).subscribeNext { [unowned self] _ in
Value of type 'UIRefreshControl' has no member 'rac_signalForControlEvents'
```

**Comment by sharplet** [comment]
1) The `Event` type is now nested on `Signal`: i.e., `Signal<Value, Error>.Event`
2) `startWithNext` is renamed to `startWithValues`
3) Try `refreshControl.reactive.controlEvents(.valueChanged)`

Hope that helps!

**Comment by NikKovIos** [comment]
Thank you very much @sharplet!

There is a few more questions:
4. What is  `observer.sendNext(object)` and `observer.sendFailed(error)` equivalent now?

**Comment by sharplet** [comment]
4) You are correct
5) For Objective-C bridging, take a look at https://github.com/ReactiveCocoa/ReactiveObjCBridge
6) `<~` is still there, but you need to explicitly `import ReactiveSwift`
7) The syntax for that would be `MutableProperty(())` — this was a recent change to Swift (I think maybe part of Swift 4). Although if you can I'd avoid using `MutableProperty<Void>`, I'd recommend instead using `Signal<(), NoError>.pipe()` or something similar

**Comment by NikKovIos** [comment]
Thank you very much for the support! The example how to wrap into Signal producer:
```swift
var textProducer: SignalProducer<String, NoError> {
        return SignalProducer(rac_textSignal())
            .map { $0 as String? }
            .skipNil()
            .flatMapError { _ in SignalProducer<String, NoError>.empty }
            .observe(on: UIScheduler())
    }
```

If someone would have questions, write to me)
