### ISSUE TITLE
[Question] ReactiveCocoa, ReactiveSwift and ReactiveObjC in one project

### ISSUE THREAD

**Issue by AYastrebov** [ReactiveCocoa/ReactiveCocoa#3595]
Hello! I have a question about using `ReactiveCocoa`, `ReactiveSwift` and `ReactiveObjC` in one project.

Currently we have a big objective-C project, where we use `ReactiveObjC`. Now we are planning to develop new features in Swift, using modern `ReactiveCocoa` and `ReactiveSwift`. I've also added `ReactiveObjCBridge` to the project. For now it seems to be all fine.

Is there any drawbacks of using `ReactiveCocoa`, `ReactiveSwift` and `ReactiveObjC` together? Does they play well together?

Thanks!

**Comment by mdiep** [comment]
They should all work fine together. 🙂

**Comment by liscio** [comment]
They all play very well together. Both [FuzzMeasure](http://rodetest.com) and [Capo](http://capoapp.com) are shipping apps that combine `ReactiveCocoa`, `ReactiveSwift`, and `ReactiveObjC`.

Just don't forget to also add `ReactiveObjCBridge`, which allows for you to bridge between your ObjC and Swift code bases.

**Comment by AYastrebov** [comment]
Thanks, guys!
