### ISSUE TITLE
Crash when debug on iPhone6 Plus

### ISSUE THREAD

**Issue by FantasyWind2016** [ReactiveCocoa/ReactiveCocoa#3598]
Device: iPhone6 Plus (MGAA2CH/A)
System: 8.3(12F70)

ReactiveCocoa (7.2.0)
ReactiveSwift (3.1.0)

When I run `let textSignal = contentTextView.reactive.continuousTextValues`this code, the app crashed on`pthread_mutex_trylock`,and it's return code is 11.

similar to the issue:
#3507 

> Change PTHREAD_MUTEX_ERRORCHECK to PTHREAD_MUTEX_NORMAL resolved the problem!

This action can resolve the problem too.

**Comment by mdiep** [comment]
@andersio Any idea if we should just be using `PTHREAD_MUTEX_NORMAL` everywhere?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
