### ISSUE TITLE
Remove newly-added recommended build settings by Xcode 9.4 once jspahrsummers/xcconfigs is updated

### ISSUE THREAD

**Issue by ikesyo** [ReactiveCocoa/ReactiveCocoa#3605]
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3604#discussion_r194756068

A PR is wellcome on https://github.com/jspahrsummers/xcconfigs.

**Comment by ianbytchek** [comment]
[jspahrsummers/xcconfigs](https://github.com/jspahrsummers/xcconfigs) has migrated to [xcconfigs/xcconfigs](https://github.com/xcconfigs/xcconfigs) awhile back, should the dependency be updated and rechecked whether this is still valid?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
