### ISSUE TITLE
Make it easier to work with table views / collection views

### ISSUE THREAD

**Issue by rhysforyou** [ReactiveCocoa/ReactiveCocoa#3608]
I've been using ReactiveSwift + ReactiveCocoa on a variety of personal and professional projects for around a year now, and one aspect I've found lacking is the way it deals with table views. Currently, a basic version of how I'd write a view model which has to provide data to a table view looks like this:

```swift
class ThingsViewModel {
    let things: Property<[Thing]>

    init(thingsProducer: SignalProducer<[Thing], NoError>) {
        things = Property(initial: [], then: thingsProducer)
    }
}

extension ThingsViewModel {
    var numberOfSections: Int {
        return 1
    }

    func numberOfItems(in section: Int) -> Int {
        return things.value.count
    }

    func item(at indexPath: IndexPath) -> Thing {
        return things.value[indexPath.row]
    }
}
```

This can then be bound to the table view like so:

```swift
class ThingsViewController: UITableViewController {

    let viewModel: ThingsViewModel

    init(viewModel: ThingsViewModel) {
        self.viewModel = viewModel

        super.init(style: .grouped)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError()
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        tableView.register(UITableViewCell.self, forCellReuseIdentifier: .cellIdentifier)

        viewModel.things.signal
            .take(during: reactive.lifetime)
            .observeValues { [unowned self] _ in
                self.tableView.reloadData()
            }
    }

    // MARK: - Table view data source

    override func numberOfSections(in tableView: UITableView) -> Int {
        return viewModel.numberOfSections
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return viewModel.numberOfItems(in: section)
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: .cellIdentifier, for: indexPath)
        let item = viewModel.item(at: indexPath)

        cell.textLabel?.text = item.uniqueID

        return cell
    }
}
```

This is already a decent amount of code for something that most iOS apps will need to implement, and this version of the code doesn't handle fine grained updates to the table view, handle editing, implement any sort of interactivity with the table view, or any number of other responsibilities.

I think this is somewhere where we could offer users of ReactiveCocoa a much nicer API, and in deciding what that API might look like, it's hard to ignore RxCocoa's approach. In Rx, once I have an `Observable` (equivalent to a `Signal` or `SignalProducer`) representing my model objects, all the code above becomes this much simpler snippet:

```swift
viewModel.things
    .bind(to: tableView.rx.items(cellIdentifier: .cellIdentifier, cellType: UITableViewCell.self)) { index, item, cell in
        cell.textLabel?.text = item.uniqueID
    }
    .disposed(by: disposeBag)
```

Now this is obviously different from the API we'd build for ReactiveCocoa, but it demonstrates how much nicer the process of binding a view model to a table view could be. This helper also supports animations, sectioned data, and so on.

I think this kind of convenience is something we should be aiming for with ReactiveCocoa, and I'd really love to hear others' suggestions for how we could improve this use case.

**Comment by sharplet** [comment]
I think this would be a really important addition that I'd love to see come to ReactiveCocoa soon. Thanks for opening up the discussion.

Just as food for thought, here's a stripped-down version of what I came up with for my latest project:

```swift
protocol ReactiveDataSource: AnyObject {
    var backgroundView: SignalProducer<UIView?, NoError> { get }
    var elementsChanged: Signal<(), NoError> { get }
    var emptyView: UIView { get }
    var isScrollEnabled: Property<Bool> { get }
    var tableViewDataSource: UITableViewDataSource { get }
}

extension Reactive where Base: UITableView {
    /// Set up a reactive data source binding. Uses the binding target internally.
    func setDataSource<T: ReactiveDataSource>(_ dataSource: T) {
        self.dataSource.action(dataSource)
    }

    /// A binding target that allows you to dynamically update the data source over time.
    var dataSource: BindingTarget<ReactiveDataSource> {
        let disposable = SerialDisposable()
        lifetime += disposable
        return makeBindingTarget { base, dataSource in
            disposable.inner?.dispose()
            base.dataSource = dataSource.tableViewDataSource
            disposable.inner = CompositeDisposable([
                base.reactive.backgroundView <~ dataSource.backgroundView,
                base.reactive.isScrollEnabled <~ dataSource.isScrollEnabled,
                base.reactive.reloadData <~ dataSource.elementsChanged,
            ])
            base.reloadData()
        }
    }

    var backgroundView: BindingTarget<UIView?> {
        return makeBindingTarget { $0.backgroundView = $1 }
    }
}
```

Then in my view controller I'm able to write this:

```swift
tableView.reactive.setDataSource(myDataSource) // concrete type omitted for now
```

In addition to the core functionality of reloading the table view, this also adds the ability to dynamically set a background view whenever the data is empty.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
