### ISSUE TITLE
Cannot create trigger signal on any UIView

### ISSUE THREAD

**Issue by piotr-sekara** [ReactiveCocoa/ReactiveCocoa#3611]
I discovered that app is crashing when I call `view.reactive.trigger(for: #selector(UIView.layoutSubviews)`. This is happening on all subclasses of UIView and UIView itself.
Can you check that?

**Comment by andersio** [comment]
Would you mind to provide the Xcode version, the framework version and the stack trace of the crash?

**Comment by piotr-sekara** [comment]
Yes, sure - I've discovered that on Xcode 9.4.1 with iOS 11.4 and ReactiveCocoa 7.2.0.

Stack trace:
`0   ???                                 0x000000010a09c72c 0x0 + 4463380268
1   ApplicationX                       0x00000001026b90a0 main + 0
2   ReactiveSwift                       0x0000000102bdecb0 _T013ReactiveSwift0A18ExtensionsProviderPAAE8reactiveAA0A0VyxGvg + 72
3   ReactiveCocoa                       0x0000000103d38144 _T0So8NSObjectC13ReactiveCocoaE9intercept33_C5DE7BC1D42D5B7EBFD255C8B4746371LL0B5Swift6SignalCyyXl6Result7NoErrorOG10ObjectiveC8SelectorVFALycfU_ + 284
4   ReactiveCocoa                       0x0000000103d37dc4 _T0So8NSObjectC13ReactiveCocoaE9intercept33_C5DE7BC1D42D5B7EBFD255C8B4746371LL0B5Swift6SignalCyyXl6Result7NoErrorOG10ObjectiveC8SelectorVF + 212
5   ReactiveCocoa                       0x0000000103d37b18 _T013ReactiveSwift0A0V0A5CocoaSo8NSObjectCRbzlE7triggerAA6SignalCyyt6Result7NoErrorOG10ObjectiveC8SelectorV3for_tF + 40
6   ApplicationX                       0x00000001026852e4 _T013ApplicationX8HomeViewC12awakeFromNibyyF + 924
7   ApplicationX                       0x00000001026869b0 _T013ApplicationX8HomeViewC12awakeFromNibyyFTo + 40
8   UIKit                               0x000000018b3e1288 <redacted> + 2112
9   UIKit                               0x000000018b212adc <redacted> + 372
10  UIKit                               0x000000018ae560f0 <redacted> + 176
11  UIKit                               0x000000018ad7ab90 <redacted> + 172
12  UIKit                               0x000000018ad7aacc <redacted> + 28
13  ApplicationX                       0x00000001026ae7c0 _T013ApplicationX18HomeViewControllerC5_view33_D4FBC5E7572324019373332484FB84DBLLAA0bC0Cvg + 68
14  ApplicationX                       0x00000001026aed10 _T013ApplicationX18HomeViewControllerC16configureWidgets33_D4FBC5E7572324019373332484FB84DBLLyyF + 28
15  ApplicationX                       0x00000001026aea9c _T013ApplicationX18HomeViewControllerCAcA0bcD6Output_p6output_AA0B6RouterC6routertcfc + 384
16  ApplicationX                       0x00000001026ae8b0 _T013ApplicationX18HomeViewControllerCAcA0bcD6Output_p6output_AA0B6RouterC6routertcfC + 56
17  ApplicationX                       0x0000000102682ab0 _T013ApplicationX10HomeRouterC34createTabBarItemRootViewControllerSo06UIViewJ0CyF + 244
18  ApplicationX                       0x00000001026832a8 _T013ApplicationX10HomeRouterCAA06TabBarC4ItemA2aDP06createdeF18RootViewControllerSo06UIViewJ0CyFTW + 28
19  ApplicationX                       0x000000010266ad08 _T013ApplicationX12TabBarRouterC29createAndSetupViewControllers33_78EAD9B103500D4E2601B68587A9DA19LLSaySo16UIViewControllerCGyFAgA0bcD4Item_pcfU_ + 72
20  ApplicationX                       0x000000010266ad50 _T013ApplicationX16TabBarRouterItem_pSo16UIViewControllerCs5Error_pIgiozo_AaB_pADsAE_pIgirzo_TR + 36
21  ApplicationX                       0x000000010266b14c _T013ApplicationX16TabBarRouterItem_pSo16UIViewControllerCs5Error_pIgiozo_AaB_pADsAE_pIgirzo_TRTA + 40
22  libswiftCore.dylib                  0x0000000104126888 _T0s10CollectionPsE3mapSayqd__Gqd__7ElementQzKcKlFTf4gn_n + 684
23  libswiftCore.dylib                  0x000000010404f284 _T0s8SequencePsE3mapSayqd__Gqd__7ElementQzKcKlFTm + 24
24  libswiftCore.dylib                  0x0000000103f68894 _T0s10CollectionPsE3mapSayqd__Gqd__7ElementQzKcKlF + 20
25  ApplicationX                       0x000000010266ac2c _T013ApplicationX12TabBarRouterC29createAndSetupViewControllers33_78EAD9B103500D4E2601B68587A9DA19LLSaySo16UIViewControllerCGyF + 180
26  ApplicationX                       0x000000010266aac4 _T013ApplicationX12TabBarRouterC6showInySo8UIWindowC6window_tF + 336
27  ApplicationX                       0x00000001026ae4ac _T013ApplicationX12LaunchRouterC15setupNavigation33_7BB2092E05A046F01A7B3518FB81D66ALLySo8UIWindowC9forWindow_tF + 120
28  ApplicationX                       0x00000001026ae408 _T013ApplicationX12LaunchRouterC22presentInitialScreenInySo8UIWindowC6window_tF + 56
29  ApplicationX                       0x00000001026b8dd4 _T013ApplicationX11AppDelegateC22presentInitialScreenInySo8UIWindowC6window_tF + 172
30  ApplicationX                       0x00000001026b83bc _T013ApplicationX11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tF + 136
31  ApplicationX                       0x00000001026b84c8 _T013ApplicationX11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tFTo + 216
32  UIKit                               0x000000018ad6ee38 <redacted> + 408
33  UIKit                               0x000000018ad6e240 <redacted> + 3484
34  UIKit                               0x000000018ad3b65c <redacted> + 1680
35  UIKit                               0x000000018b36ba0c <redacted> + 784
36  UIKit                               0x000000018ad3ae4c <redacted> + 160
37  UIKit                               0x000000018ad3ace8 <redacted> + 240
38  UIKit                               0x000000018ad39b78 <redacted> + 724
39  UIKit                               0x000000018b9cf72c <redacted> + 296
40  UIKit                               0x000000018ad39268 <redacted> + 432
41  UIKit                               0x000000018b7b49b8 <redacted> + 220
42  UIKit                               0x000000018b902ae8 _performActionsWithDelayForTransitionContext + 112
43  UIKit                               0x000000018ad38c88 <redacted> + 248
44  UIKit                               0x000000018ad38624 <redacted> + 368
45  UIKit                               0x000000018ad3565c <redacted> + 540
46  UIKit                               0x000000018ad353ac <redacted> + 364
47  FrontBoardServices                  0x000000018399c470 <redacted> + 364
48  FrontBoardServices                  0x00000001839a4d6c <redacted> + 224
49  libdispatch.dylib                   0x0000000104939220 _dispatch_client_callout + 16
50  libdispatch.dylib                   0x0000000104945850 _dispatch_block_invoke_direct + 232
51  FrontBoardServices                  0x00000001839d0878 <redacted> + 36
52  FrontBoardServices                  0x00000001839d051c <redacted> + 404
53  FrontBoardServices                  0x00000001839d0ab8 <redacted> + 56
54  CoreFoundation                      0x0000000181147404 <redacted> + 24
55  CoreFoundation                      0x0000000181146c2c <redacted> + 276
56  CoreFoundation                      0x000000018114479c <redacted> + 1204
57  CoreFoundation                      0x0000000181064da8 CFRunLoopRunSpecific + 552
58  GraphicsServices                    0x0000000183047020 GSEventRunModal + 100
59  UIKit                               0x000000018b04578c UIApplicationMain + 236
60  ApplicationX                       0x00000001026b90ec main + 76
61  libdyld.dylib                       0x0000000180af5fc0 <redacted> + 4`

**Comment by andersio** [comment]
The fact that it crashes _in_ ReactiveSwift is incredibly odd. I tried to reproduce it but it appears to work fine in the playground. Would you mind to try a clean build and/or disable optimisations and see if this persist?

**Comment by piotr-sekara** [comment]
Sorry for late response - I think the problem lied in Carthage and version of ReactiveSwift. After limiting ReactiveSwift to version 3.1.0 and running Carthage update one more time, everything started working. Don't know why but ReactiveCocoa 7.2.0 has installed with ReactiveSwift 4.0.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
