### ISSUE TITLE
for循环中使用reactive.controlEvent(.touchUpInside).observerValue{}

### ISSUE THREAD

**Issue by HeyuanXie** [ReactiveCocoa/ReactiveCocoa#3612]
let btns = [btn1,btn2,btn3]
for btn in btns {
  btn.reactive.controlEvents(.touchUpInside).observeValues({ (sender) in
     print('btnClick')
 })
}
everyTime i click the btn, the method will be executed more than once, why？

**Comment by mdiep** [comment]
Are you calling `.observeValues` multiple times on `btn`?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
