### ISSUE TITLE
Use of undeclared type 'Observer'

### ISSUE THREAD

**Issue by asheesh5391** [ReactiveCocoa/ReactiveCocoa#3630]
I am using Xcode 9.0

I am using following version:

pod 'ReactiveCocoa', '~> 7.1.0'
Pod 'ReactiveSwift', '~> 3.1' 

Also importing both of the library in the file.

`func handleResponseStatus(observer: Observer<ResponseStatus, ApplicationError>, response: DataResponse<ResponseStatus>)` 

But unable to build the project and getting the following error:

Use of undeclared type 'Observer'

**Comment by mdiep** [comment]
`Observer` has moved to be `Signal.Observer`.
