### ISSUE TITLE
Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<Value, Error>.Observer, CompositeDisposable) -> ())'

### ISSUE THREAD

**Issue by asheesh5391** [ReactiveCocoa/ReactiveCocoa#3632]
I am using Xcode 9.0

I am using following version:

pod 'ReactiveCocoa', '> 7.1.0'
Pod 'ReactiveSwift', '> 3.1'

Also importing both of the library in the file.

```
let signalProducer = SignalProducer(startHandler)
            return signalProducer.attachAzureTokenRetry(session, azureService: azureService)
```

But unable to build the project and getting the following error:

```
Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<Value, Error>.Observer, CompositeDisposable) -> ())'
```

**Comment by amolpict-ios** [comment]
I am also facing same issue. "Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<SignalProducer<Value, Error>.Value, SignalProducer<Value, Error>.Error>.Observer, CompositeDisposable) -> ())'"

I am using Xcode 10.1
Using ReactiveCocoa (9.0.0)
Using ReactiveObjC (3.1.1)
Using ReactiveSwift (5.0.1)
Using Result (4.1.0)

static func createProducer(service:serviceName, handler: @escaping (Signal<Value, Error>.Observer, CompositeDisposable) -> ()) -> SignalProducer<Value, Error> {
let sigProducer = SignalProducer(handler) // **Error : Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<SignalProducer<Value, Error>.Value, SignalProducer<Value, Error>.Error>.Observer, CompositeDisposable) -> ())'**
}

Please update if any one has update on this issue. I am facing this issue when I updated libraries.

**Comment by mdiep** [comment]
If you look at the `SignalProducer` API, it has been updated to take a `Lifetime` instead of a `CompositeDisposable`.
