### ISSUE TITLE
Cannot invoke 'collect' with no arguments

### ISSUE THREAD

**Issue by asheesh5391** [ReactiveCocoa/ReactiveCocoa#3633]
I am using Xcode 9.0

I am using following version:

pod 'ReactiveCocoa', '> 7.1.0'
Pod 'ReactiveSwift', '> 3.1'

Also importing both of the library in the file.

```
let nonGiftCardPaymentMethods = payments
                .map({ $0.storedPayments })
                .flatMap(.concat, { (paymentMethods) -> SignalProducer<PaymentMethod, NoError> in
                    return SignalProducer<PaymentMethod, NoError>( paymentMethods as [PaymentMethod])
                })
                .filter({$0.payment != .card(.unknown)})
                .collect()
                .flatMap(.concat) { (paymentMethods) -> SignalProducer<PaymentMethod, ApplicationError> in
                    return SignalProducer(paymentMethods)
            }
```

But unable to build the project and getting the following error:

Cannot invoke 'collect' with no arguments

**Comment by mdiep** [comment]
That method definitely exists. You must have another error and type inference isn't giving you a good diagnostic.

I would add explicit types to help find the bug.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
