### ISSUE TITLE
Ambiguous use of operator '<~'

### ISSUE THREAD

**Issue by asheesh5391** [ReactiveCocoa/ReactiveCocoa#3638]
I am using 
Xcode 10.0
Swift 3.x

Deployment Target 9.0

I am using following version:

pod 'ReactiveCocoa', '5.0.3'
Pod 'ReactiveSwift', '1.1.3'

Also importing both of the library in the file.

`detailsCell.pickupTimeLabel.reactive.text <~ orderSummaryViewModel.pickupTimes.signal.filter({ !$0.timeSlots.isEmpty}).map({ [weak self] pickupTimes in
            guard let strongSelf = self else { return "" }
            
            let timeString = "\(Date.todayString) \(pickupTimes.timeSlots.first!) \(strongSelf.orderSummaryViewModel.storeDetails.value!.utcOffset)"
            
            let formatter = DateFormatter()
            formatter.locale = Locale.serverFormatterLocale
            formatter.dateFormat = Constants.Date.standardFormat
            
            if let date = formatter.date(from: timeString) {
                formatter.dateFormat = "h:mm a"
                return formatter.string(from: date)
            } else {
                DDLogDebug("Pickup time \(timeString) is invalid")
                return ""
            }
        })`
But unable to build the project and getting the following error:
Ambiguous use of operator '<~'

Note: it seems working on other places in project.

`productNameLabel.reactive.text <~ viewModel.productName.producer.map({ (name) -> String in
            self.productNameLabel.accessibilityLabel = NSLocalizedString("Customize", comment: "") + " " + name
            return name
        })`

It would great to help me out on this. Thanks.

**Comment by rocketnik** [comment]
This appeared to me the first time after upgrading to Xcode 12. Xcode 11.x still builds my code. I will investigate and put more information tomorrow.

**Comment by NeerajGupta03** [comment]
Same issue is happening with me in Xcode 12. Everything was working fine in earlier versions. @rocketnik Let us know if you find any solution. Thanks

**Comment by rocketnik** [comment]
So in my case I was binding a `SignalProducer<String>` to a `UITextFields`'s `reactive.text`. Even though the type of the SignalProducer can with no doubt be  inferred to be `String`, the compiler can not decide which instance to use for `<~`: `String` or `String?` as parameter to the SignalProducer. I could fix it by providing the return type in the closure. example:
`someLabel.reactive.text <~ someSignalProducerOfOptionalItem.map{ (item: Item?) -> String in  ... }`

**Comment by rocketnik** [comment]
"no doubt": I used a string literal in the end. But actually this can be interpreted as `String?`, because Swift automatically casts values of `SomeType` to their `Optional<SomeType>` counterpart. So maybe the Swift type inferrer/compiler got enhanced, to also allow the type of the closure to be determined by the context it is used in. This would be consistent. But it reveals more for the implicit cast of Optionals problematic, I am complaining about for years to my colleagues. my2¢: I wish the automatic casts would go away and you had to use `.some(value)` to make a value into an Optional. @Apple: please take a look at Haskell, there it was done right.

**Comment by NeerajGupta03** [comment]
> So in my case I was binding a `SignalProducer<String>` to a `UITextFields`'s `reactive.text`. Even though the type of the SignalProducer can with no doubt be inferred to be `String`, the compiler can not decide which instance to use for `<~`: `String` or `String?` as parameter to the SignalProducer. I could fix it by providing the return type in the closure. example:
> `someLabel.reactive.text <~ someSignalProducerOfOptionalItem.map{ (item: Item?) -> String in ... }`

Thanks, This works for me.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
