### ISSUE TITLE
__TEXT  __dof_RACSignal  __dof_RACCompou

### ISSUE THREAD

**Issue by matchboxy** [ReactiveCocoa/ReactiveCocoa#3639]
Recently I checked linkmap of my proj, and I found some RAC sections: __dof_RACSignal  __dof_RACCompou in __TEXT segment. So I search 'dof' in my proj, but nothing found. -------  so I want to ask where do these sections be used? Thank you!

**Comment by matchboxy** [comment]
it relates to dtrace

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
