### ISSUE TITLE
Generic KVO signals using new block syntax?

### ISSUE THREAD

**Issue by ianbytchek** [ReactiveCocoa/ReactiveCocoa#3640]
Swift 4 introduced [new block-based KVO with generic type support](https://github.com/ole/whats-new-in-swift-4/issues/6#issue-237129196), implementation [reference](https://github.com/apple/swift/blob/0d4a5853bf665eb860ad19a16048664899c6cce3/stdlib/public/Darwin/Foundation/NSObject.swift#L195-L210). It would be awesome to have this alongside the existing `signal(forKeyPath:)` to skip the mapping/casting step.

```swift
class Foo: NSObject {
    @objc dynamic var hello: String = "World"
}

Foo().reactive.signal(forKeyPath: \.hello) // 🥺
Foo().reactive.signal(forKeyPath: #keyPath(Foo.hello)).filterMap({ $0 as? String }) // 😖
```

**Comment by mdiep** [comment]
I don't remember the specifics, but I think we've avoided doing that because of limitations of the new KVO API. It behaves differently and IIRC is somewhat broken.

**Comment by ianbytchek** [comment]
Right… The native observer implementation seems to do a lot of voodoo magic along lines of what ReactiveCocoa already does. Shim would still be a great addition to compliment the Swift 4 functionality, though?

```swift
extension Reactive where Base: NSObject {
    func signal<V>(forKeyPath keyPath:KeyPath<Base, V>) -> Signal<V, NoError> {
        guard let keyPathString = keyPath._kvcKeyPathString else { return .empty }
        return self.signal(forKeyPath: keyPathString).map({ [unowned base] in $0 as? V ?? base[keyPath: keyPath] })
    }
}

class Foo: NSObject {
    @objc dynamic var hello: String = "World"
}

let foo = Foo()

foo.reactive.signal(forKeyPath: \.hello).observeValues({ Swift.print("new api:", $0) })
foo.reactive.signal(forKeyPath: #keyPath(Foo.hello)).filterMap({ $0 as? String }).observeValues({ Swift.print("old api:", $0) })

foo.hello = "Bar"
foo.hello = "Baz"

```

**Comment by mdiep** [comment]
We've talked about that. I've been against it since `_kvcKeyPathString` isn't a supported API, is liable to break/change, and there's no way to guard against calling it with a `KeyPath` that doesn't have a KVC key path string.

https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3491
