### ISSUE TITLE
proxy.invoked of NSControl should be exposed

### ISSUE THREAD

**Issue by cxa** [ReactiveCocoa/ReactiveCocoa#3645]
In UIKit, if you don't want to use `CocoaAction` (it is complex and verbose for simple task), it's possible with `reactive.controlEvents(_ controlEvents: UIControl.Event)` e.g. 

```swift
downloadButton.reactive.controlEvents(.primaryActionTriggered).observeValues { _ in 
  dispatcher.send(event: .handleDownload) 
}
```

but is impossible for AppKit because you hide the `proxy.invoked` for `NSControl`.

So I think it's better to expose `proxy.invoked`, and rename it to a more sensable API name if necessary.

**Comment by andersio** [comment]
We could expose it as `NSControl.reactive.triggered`. That's said `NSButton` has a `states` signal which should serve your use case. Is that not suitable?

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
