### ISSUE TITLE
Could you release a new with ReactiveSwift 5.0 for carthage?

### ISSUE THREAD

**Issue by RiuHDuo** [ReactiveCocoa/ReactiveCocoa#3651]
Could you release a new with ReactiveSwift 5.0 ?
The version 8.0.2 can be build with Xcode 10.2

**Comment by mdiep** [comment]
We're just waiting on a couple PRs to be merged

**Comment by dashared** [comment]
Is there any progress with that issue? Still `project itself failed to compile` :(

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3665

**Comment by andersio** [comment]
Dup #3665 and #3668. 9.0.0 for RAS 5 and 10.0.0 for RAS 6 have been released.
