### ISSUE TITLE
Xcode 10.2 build failure

### ISSUE THREAD

**Issue by gilroykilroy** [ReactiveCocoa/ReactiveCocoa#3652]
Xcode updated and I updated my Cartfile to the latest. Now the build fails because LlamaKit build fails:

error: Value for SWIFT_VERSION cannot be empty. (in target 'LlamaKit-iOS')

**Comment by mdiep** [comment]
That doesn't seem related to ReacitveCocoa

**Comment by gilroykilroy** [comment]
Could be ReactiveSwift, sorry.

**Comment by mdiep** [comment]
It doesn't seem related to ReactiveSwift either. The error clearly says its from LlamaKit.
