### ISSUE TITLE
Carthage build issue with Xcode 10.2

### ISSUE THREAD

**Issue by gilroykilroy** [ReactiveCocoa/ReactiveCocoa#3653]
OK, there is something wrong either with your Carthage dependancies or with Carthage.

This works by itself:

JeffMac-3:test kilroy$ cat Cartfile
github "ReactiveCocoa/ReactiveSwift" ~> 5.0

JeffMac-3:test kilroy$ carthage update --no-use-binaries --platform iOS
*** Fetching ReactiveSwift
*** Fetching Result
*** Checking out Result at "4.1.0"
*** Checking out ReactiveSwift at "5.0.0"
*** xcodebuild output can be found in /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/carthage-xcodebuild.Cwq3og.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveSwift-iOS" in ReactiveSwift.xcworkspace

This fails because ReactiveSwift 4.0 doesn't compile under Xcode 10.2 (expected):

JeffMac-3:test kilroy$ cat Cartfile
github "ReactiveCocoa/ReactiveSwift" ~> 4.0
github "ReactiveCocoa/ReactiveCocoa" ~> 8.0

JeffMac-3:test kilroy$ carthage update --no-use-binaries --platform iOS
*** Fetching ReactiveCocoa
*** Fetching ReactiveSwift
*** Fetching Result
*** Checking out ReactiveSwift at "4.0.0"
*** Checking out Result at "4.1.0"
*** Checking out ReactiveCocoa at "8.0.2"
*** xcodebuild output can be found in /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/carthage-xcodebuild.doNkC7.log
*** Building scheme "Result-iOS" in Result.xcodeproj
*** Building scheme "ReactiveSwift-iOS" in ReactiveSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/kilroy/Documents/Code/test/Carthage/Checkouts/ReactiveSwift/ReactiveSwift.xcworkspace -scheme ReactiveSwift-iOS -configuration Release -derivedDataPath /Users/kilroy/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/ReactiveSwift/4.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/ReactiveSwift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/kilroy/Documents/Code/test/Carthage/Checkouts/ReactiveSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/carthage-xcodebuild.doNkC7.log

However look what happens when I change it to 5.0:

JeffMac-3:test kilroy$ cat Cartfile
github "ReactiveCocoa/ReactiveSwift" ~> 5.0
github "ReactiveCocoa/ReactiveCocoa" ~> 8.0

JeffMac-3:test kilroy$ carthage update --no-use-binaries --platform iOS
*** Fetching ReactiveCocoa
*** Fetching ReactiveSwift
*** Fetching Result
*** Fetching Box
*** Fetching LlamaKit
*** Checking out LlamaKit at "v0.6.0"
*** Checking out ReactiveCocoa at "v3.0-beta.1"
*** Checking out ReactiveSwift at "5.0.0"
*** Checking out Result at "4.1.0"
*** xcodebuild output can be found in /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/carthage-xcodebuild.Pzwyxo.log
*** Building scheme "LlamaKit-iOS" in LlamaKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/kilroy/Documents/Code/test/Carthage/Checkouts/LlamaKit/LlamaKit.xcodeproj -scheme LlamaKit-iOS -configuration Release -derivedDataPath /Users/kilroy/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/LlamaKit/v0.6.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/mt/5c87hjvx1db1xxlhtr0h1trh0000gn/T/LlamaKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/kilroy/Documents/Code/test/Carthage/Checkouts/LlamaKit)

It brings in both Box and LlamaKit (which doesn't compile) and it says it is checking out ReactiveCocoa at "v3.0-beta.1".

Something is clearly wrong here.

P.S. If I just have "ReactiveCocoa/ReactiveCocoa" ~> 8.0 it checks out ReactiveSwift at "4.0.0"

**Comment by mdiep** [comment]
This is a Carthage bug that can occur when you have incompatible constraints.

**Comment by gilroykilroy** [comment]
OK, I reported it to them. Any suggestions to work around it?

**Comment by mdiep** [comment]
You can't use ReactiveSwift 5 and ReactiveCocoa 8 together. You'll have to stay on ReactiveSwift 4 until we get ReactiveCocoa 9 released.
