### ISSUE TITLE
there is no 8.0.2 tag

### ISSUE THREAD

**Issue by smolskyaleksey** [ReactiveCocoa/ReactiveCocoa#3655]
Tag 8.0.2 does not support swift 4.2 
swift 4.2 is located in master branch 
Could you create tag 8.0.2 and merge swift 4.2 inside

**Comment by mdiep** [comment]
There will be a new 9.0 release soon

**Comment by smolskyaleksey** [comment]
Do you support swift5 in 9.0?

**Comment by mdiep** [comment]
Yes

**Comment by Kalvin126** [comment]
The current `9.0` does not include #3661 does it? Is `9.0` tag going to be republished along with a cocoaPods publish?

**Comment by ikesyo** [comment]
That will be 10.0.

**Comment by ikesyo** [comment]
Closing this as 9.0 had been released.
