### ISSUE TITLE
Crashed on Smart Key Path KVO when values are enums

### ISSUE THREAD

**Issue by wordlessj** [ReactiveCocoa/ReactiveCocoa#3660]
Current implementations of `producer(for:)` and `signal(for:)` use old Objective-C API, which get values from `value(forKey:)`. It works for most types except enums, `value(forKey:)` returns an `NSNumber`, then force-casted to the original enum type, which crashes. Maybe we should use Swift KVO API instead?

**Comment by ikesyo** [comment]
A good news is that is exactly https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3491.

**Comment by wordlessj** [comment]
I may not have made It clear, this PR is the origin of the crash. It gets values from `value(forKey:)` which returns `NSNumber` for enums, then `producer(for:)` and `signal(for:)` force cast `NSNumber` to the specific enum type which will crash. If we use the Swift KVO api, values passed to the closure will be the correct type.

**Comment by ikesyo** [comment]
#3667 should had fixed this.
