### ISSUE TITLE
Carthage broken with ReactiveSwift 6

### ISSUE THREAD

**Issue by gilroykilroy** [ReactiveCocoa/ReactiveCocoa#3662]
The Carthage bug where it hangs on update is triggered with Cartfile

github "ReactiveCocoa/ReactiveSwift" ~> 6.0
github "ReactiveCocoa/ReactiveCocoa" ~> 9.0

**Comment by mdiep** [comment]
ReactiveCocoa hasn't been updated for ReactiveSwift 6. (There's on open PR.)

This is a known Carthage bug.
