### ISSUE TITLE
New release for ReactiveSwift 6.0.0

### ISSUE THREAD

**Issue by SzymonMrozek** [ReactiveCocoa/ReactiveCocoa#3668]
Hello great ReactiveCocoa team! I am extraordinary grateful for your work!
Could you please release new `ReactiveCocoa` tag what now includes bumping `ReactiveSwift` to `6.0.0`?

**Comment by iv-mexx** [comment]
A new release is already on its way: #3665

**Comment by andersio** [comment]
10.0.0 has been released. Apologies for the long release gap. :)
