### ISSUE TITLE
ReactiveCocoa 10.0.0 uses ReactiveSwift 6.0, which drops support for swift 4.2

### ISSUE THREAD

**Issue by CamilleLong** [ReactiveCocoa/ReactiveCocoa#3669]
ReactiveCocoa 10.0.0 claims to support swift 4.2, but the version of ReactiveSwift it uses (6.0.0) has [dropped support](https://github.com/ReactiveCocoa/ReactiveSwift/releases/tag/6.0.0) for Swift 4.2. Installing ReactiveCocoa 10.0.0 in my Swift 4.2 codebase does not work, because the ReactiveSwift version no longer supports Swift 4.2. 

I am not asking for this even to be fixed, but hopefully the documentation can be updated correctly that ReactiveCocoa 10.0.0 also drops support for swift 4.2.

**Comment by andersio** [comment]
I think there is an ambiguity area here. Both RAS and RAC should work while still interoperating with Swift 4.2 as a compatibility mode with the Swift 5 compiler. In any case, I have updated the documentation as such.

**Comment by CamilleLong** [comment]
Thanks for the quick response!
