### ISSUE TITLE
Swift Shield in README.md should be 5.0

### ISSUE THREAD

**Issue by JohnTheBastard** [ReactiveCocoa/ReactiveCocoa#3671]
Currently says 3.0.x, which is a deterrent for adoption by people comparing to Rx.

I'd make a PR myself, but my employer makes that complicated. 😉

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
