### ISSUE TITLE
Extension of a generic Objective-C class cannot access the class's generic parameters at runtime

### ISSUE THREAD

**Issue by amolpict-ios** [ReactiveCocoa/ReactiveCocoa#3672]
I have update my Reactive libraries as below 
Using ReactiveCocoa (9.0.0)
Using ReactiveObjC (3.1.1)
Using ReactiveSwift (5.0.1)
Using Result (4.1.0)

On : Xcode 10.1.

Below is the function we used earlier:

```
public func toSignalProducer(file: String = #file, line: Int = #line) -> SignalProducer<AnyObject?, NSError> {
}
```

and after compiling I am getting this error : 

```
Extension of a generic Objective-C class cannot access the class's generic parameters at runtime
```

Totally blocked due to this issue and can not compile existing code now. Could not find any pointers/solution on how to deal with this issue ?
If any one has solution then please update on or provide path forwards to deal with this.
Thanks in advance.

**Comment by mdiep** [comment]
There's not really enough info here to help you.

That error means that you have an Objective-C type that's defined with lightweight generics. Something in Swift is trying to use those generics, but that's not possible.
