### ISSUE TITLE
Cannot invoke initializer for type SignalProducer<Value, Error>

### ISSUE THREAD

**Issue by amolpict-ios** [ReactiveCocoa/ReactiveCocoa#3673]
I am using Xcode 10.1
Using ReactiveCocoa (9.0.0)
Using ReactiveObjC (3.1.1)
Using ReactiveSwift (5.0.1)
Using Result (4.1.0)

static func createProducer(service:serviceName, handler: @escaping (Signal<Value, Error>.Observer, CompositeDisposable) -> ()) -> SignalProducer<Value, Error> {
let sigProducer = SignalProducer(handler) // **Error : Cannot invoke initializer for type 'SignalProducer<Value, Error>' with an argument list of type '((Signal<SignalProducer<Value, Error>.Value, SignalProducer<Value, Error>.Error>.Observer, CompositeDisposable) -> ())'
}**

Please update if any one has update on this issue. I am facing this issue when I updated libraries.

**Comment by mdiep** [comment]
Please don't open multiple issue for the same thing.

You need to update to use `Lifetime` instead of `CompositeDisposable`.
