### ISSUE TITLE
Use of undeclared  type 'Observer' on Reactive Cocoa 9.0.0 when library updated.

### ISSUE THREAD

**Issue by amolpict-ios** [ReactiveCocoa/ReactiveCocoa#3674]
I am using Xcode 10.1 and recently update libraries as below : 
Using ReactiveCocoa (9.0.0)
Using ReactiveObjC (3.1.1)
Using ReactiveSwift (5.0.1)
Using Result (4.1.0)

Earlier we had code like this :: static func createProducer(arg1: arg1, **startHandler: @escaping (Observer<Value, Error>, CompositeDisposable)** -> ()) -> SignalProducer<Value, Error> 
And it was working fine but after updating libraries we are getting this error ::
  " Use of undeclared type 'Observer "

**Comment by mdiep** [comment]
`Observer` is now a nested type.
