### ISSUE TITLE
look for help with a crash when dispose

### ISSUE THREAD

**Issue by yuyifeng** [ReactiveCocoa/ReactiveCocoa#3679]
I met a crash when rac dispose,  in iPhone 7 Plus, iOS 12.3.1，v3.0.1. Anybody can help me?

![image](https://user-images.githubusercontent.com/7882115/62619060-65e80880-b948-11e9-85b2-841b327bf4cf.png)

0               __destroy_helper_block_ (in News)
1               ___21-[RACSubscriber init]_block_invoke (in News) 52
2               -[RACDisposable dispose] (in News) 96
3               -[RACCompoundDisposable dispose] (in News) 192
4               -[RACSubscriber sendCompleted] (in News) 120
5               -[RACPassthroughSubscriber sendCompleted] (in News) 128
6               -[RACSubscriber sendCompleted] (in News) 144
7               -[RACPassthroughSubscriber sendCompleted] (in News) 128
8               -[RACSubject enumerateSubscribersUsingBlock:] (in News) 284
9               -[RACReplaySubject sendCompleted] (in News) 76
10              -[RACDisposable dispose] (in News) 96
11              -[RACCompoundDisposable dispose] (in News) 192
12              ___swizzleDeallocIfNeeded_block_invoke (in News) 68
13  libobjc.A   (anonymous namespace)::AutoreleasePoolPage::pop(void*) (in libobjc.A.dylib)
14  UIKitCore   -[UIView dealloc] (in UIKitCore)
15  libobjc.A   (anonymous namespace)::AutoreleasePoolPage::pop(void*) (in libobjc.A.dylib)
16  UIKitCore   -[UIView dealloc] (in UIKitCore)
17  libobjc.A   (anonymous namespace)::AutoreleasePoolPage::pop(void*) (in libobjc.A.dylib)

**Comment by topws** [comment]
+1

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
