### ISSUE TITLE
about DelegateProxy

### ISSUE THREAD

**Issue by snlo** [ReactiveCocoa/ReactiveCocoa#3680]
Why can't we extend DelegateProxy in the case of pods.

**Comment by snlo** [comment]
Similar to ‘PickerViewDelegateProxy’
internal
internal class DelegateProxy<Delegate: NSObjectProtocol>: NSObject

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
