### ISSUE TITLE
Inconsistent text signals between `UITextField`, `UITextView` and `UISearchBar`

### ISSUE THREAD

**Issue by Azureblade3808** [ReactiveCocoa/ReactiveCocoa#3682]
Is there any reason that text signals of `UISearchBar` still emit optional values, while those of `UITextField` and `UITextView` no longer do?

I ran into a compilation failure just like what #3659 described, after updating ReactiveCocoa from V8 to V10. Compilation failures are totally OK to me but the error message was quite confusing:
```
Property 'continuousTextValues' requires that 'UITextField' inherit from 'UISearchBar'
```

While the message was given by the compiler, I think this confusion can be avoided if these text signals with same names work in a consistent way.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
