### ISSUE TITLE
Intermediate release so ReactiveCocoa builds on Xcode 11

### ISSUE THREAD

**Issue by Lewion** [ReactiveCocoa/ReactiveCocoa#3684]
There's already a PR merged in to master which updates the dependencies to support building with Xcode 11, it would be nice to create a `10.0.1` for everyone to start using rather than using the commit hash.

**Comment by gilroykilroy** [comment]
Yes, yes it would.

**Comment by hieuhuynh0412** [comment]
@Lewion would you please to show me how to build with Xcode 11 when still not have offical release?

**Comment by krris** [comment]
The release version of Xcode 11 is available: https://apps.apple.com/us/app/xcode/id497799835
@mdiep Is there any chance to release a new version of ReactiveCocoa?
