### ISSUE TITLE
Use GitHub Actions for CI

### ISSUE THREAD

**Issue by ikesyo** [ReactiveCocoa/ReactiveCocoa#3687]
It would make the CI jobs faster with the much higher usage limits than Travis: https://help.github.com/en/articles/workflow-syntax-for-github-actions#usage-limits

> - You can execute up to 20 workflows concurrently per repository.
> - ...
> - You can run up to 20 jobs concurrently per repository across all workflows.

@ReactiveCocoa/reactivecocoa Could someone with the admin right sign up for the beta?

https://github.com/features/actions

**Comment by mdiep** [comment]
Done 👍

**Comment by andersio** [comment]
Moved to GitHub Actions in #3706.
