### ISSUE TITLE
[SwiftPM on Xcode] Package resolution failed

### ISSUE THREAD

**Issue by BeerPoldet** [ReactiveCocoa/ReactiveCocoa#3695]
Please fix this

![image](https://user-images.githubusercontent.com/7531231/71781625-7f7aa280-3003-11ea-8ddb-a808989ffac7.png)

**Comment by ikesyo** [comment]
#3693 was merged but not released yet. Please specify `master` branch for now.

**Comment by ikesyo** [comment]
10.2.0 has been released https://github.com/ReactiveCocoa/ReactiveCocoa/releases/tag/10.2.0
