### ISSUE TITLE
why RACObserve(self.scoreStepper,value) not available?

### ISSUE THREAD

**Issue by JyyJDast1** [ReactiveCocoa/ReactiveCocoa#3700]
I have the code:
`@property(weak) IBOutlet UIStepper *scoreStepper;  
[[[RACObserve(self.scoreStepper,value) skip:1] take:self.viewModel.maxPointUpdates] subscribeNext:^(id newPoints) {
		@strongify(self);
		self.viewModel.points = [newPoints doubleValue];
		self.scoreUpdates++;
	}];`
but the code of subscribe cannot be excute.
when I change the code like this:
` [[[self.scoreStepper rac_signalForControlEvents:UIControlEventTouchUpInside]
      take:10]
     subscribeNext:^(UIStepper * x) {
        @strongify(self);
        NSLog(@"value:%f",x.value);
        self.viewModel.points = x.value;
        self.scoreUpdates++;
    }];
`
it works!
So,I wonder why "RACObserve(self.scoreStepper,value) subscribeNext ..."cannot work?

**Comment by ikesyo** [comment]
Please open an issue on https://github.com/ReactiveCocoa/ReactiveObjC for the the Objective-C ReactiveCocoa.
