### ISSUE TITLE
UISearchBar delegate proxy crash on Mac Catalyst

### ISSUE THREAD

**Issue by andersio** [ReactiveCocoa/ReactiveCocoa#3707]
Related: https://github.com/ReactiveX/RxSwift/issues/2161

UISearchBar test spec has been temporarily disabled.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
