### ISSUE TITLE
Build error when using ReactiveCocoa via Swift Package Manager

### ISSUE THREAD

**Issue by mluisbrown** [ReactiveCocoa/ReactiveCocoa#3709]
If I add ReactiveCocoa as a dependency using Swift Package Manager, when I `import ReactiveCocoa` I get the error: `Missing required module 'ReactiveCocoaObjC'`

I tried adding `ReactiveCocoaObjC` as a `product` in `Package.swift` in a fork of the repo, and then adding `ReactiveCocoaObjC` as a dependency in Xcode, in addition to `ReactiveCocoa`, but that didn't seem to make any difference.

I suspect that this is either an Xcode or SPM bug, but I'd love to know if anyone has a workaround.

**Comment by mluisbrown** [comment]
Ok, after following some links [mentioned here](https://stackoverflow.com/a/58630277/368085) I tried adding:

```
-Xcc -fmodule-map-file=$(PROJECT_TEMP_ROOT)/GeneratedModuleMaps/iphonesimulator/ReactiveCocoaObjC.modulemap
```

To `OTHER_SWIFT_FLAGS` in the app target build settings, and this fixed it. This works without needing to add `ReactiveCocoaObjC` as a product in Package.swift.

It's a workaround, but looks like this is an Xcode bug 😢

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄

**Comment by NachoSoto** [comment]
I'm encountering this right now too. For some reason not in the main app target, but on extension targets :/
