### ISSUE TITLE
can not deinit

### ISSUE THREAD

**Issue by xujialiang** [ReactiveCocoa/ReactiveCocoa#3711]
// My ViewModel can deinit 
showAPIHelperAction = Action<(), Void, Never>{[unowned self] _ in
            return self.showAPIHelperActionExec()
        }

// My ViewModel can't deinit 
showAPIHelperAction = Action(execute: showAPIHelperActionExec)

func showAPIHelperActionExec() -> SignalProducer<Void, Never> {
        return SignalProducer<Void, Never> { [unowned self] observer, disposable in
            observer.sendCompleted()
        }
    }

**Comment by kaybutter** [comment]
That's just how Swift works. Not much ReactiveCocoa can do about that. Passing a method as a closure parameter like in `Action(execute: showAPIHelperActionExec)` will always capture self as a strong reference.

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
