### ISSUE TITLE
Xcode12  ReactiveObj archive error

### ISSUE THREAD

**Issue by zombieSmile** [ReactiveCocoa/ReactiveCocoa#3713]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/31536005/93882319-a5231580-fd12-11ea-8492-e63fbab9cd69.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/31536005/93884805-f54fa700-fd15-11ea-8ef2-3ad324b7e02a.png">

**Comment by zhangxxyz** [comment]
very

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄

**Comment by zhangxxyz** [comment]
都没改
