### ISSUE TITLE
EXC_BAD_ACCESS Cash with NSURL

### ISSUE THREAD

**Issue by 623637646** [ReactiveCocoa/ReactiveCocoa#3718]
**Short description of the issue**:

  EXC_BAD_ACCESS Crash

<img width="1420" alt="Screenshot 2020-11-14 at 9 34 00 PM" src="https://user-images.githubusercontent.com/5275802/99148216-79446080-26c1-11eb-91d2-8f1b305365cd.png">

**Self contained code example that reproduces the issue**:

```swift
let url = NSURL.init(string: "https://www.google.com")!
_ = url.reactive.trigger(for: #selector(getter: NSURL.host)).on {a in
    print("")
} failed: { (a) in
    print("")
} completed: {
    print("")
} interrupted: {
    print("")
} terminated: {
    print("")
} disposed: {
    print("")
} value: { (a) in
    print("")
}
let a = url.host
```

**ReactiveCocoa/ReactiveSwift version**

ReactiveCocoa (11.1.0)
ReactiveSwift (6.5.0)

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  Xcode 12.2
```

**Comment by RuiAAPeres** [comment]
Hello. 👋 Thanks for opening this issue. Due to inactivity, we will soft close the issue. If you feel that it should remain open, please let us know. 😄
