### ISSUE TITLE
ReactiveCocoa 11.1.0 incompatible with ReactiveSwift 6.6.0

### ISSUE THREAD

**Issue by opfeffer** [ReactiveCocoa/ReactiveCocoa#3720]
Hi there- I saw last night's release of ReactiveSwift and ReactiveCocoa.

I notice that ReactiveCocoa 11.1.0 has a lower minimum deployment target (8.0, see [podspec](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/11.1.0/ReactiveCocoa.podspec#L13)) than ReactiveSwift 6.6.0 (9.0, see [podspec](https://github.com/ReactiveCocoa/ReactiveSwift/blob/6.6.0/ReactiveSwift.podspec#L13)).

Is that intentional? 

I believe this is causing issues when trying to compile ReactiveCocoa, such as
```
ERROR | xcodebuild:  ReactiveCocoa/ReactiveCocoa/AnyObject+Lifetime.swift:2:8: error: compiling for iOS 8.0, but module 'ReactiveSwift' has a minimum deployment target of iOS 9.0: /Users/jenkins/Library/Developer/Xcode/DerivedData/App-fkafmlgfqciugzhfvtosogptnthk/Build/Products/Debug-iphonesimulator/ReactiveSwift/ReactiveSwift.framework/Modules/ReactiveSwift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

**Comment by opfeffer** [comment]
I believe https://github.com/ReactiveCocoa/ReactiveCocoa/pull/3712 should have included an update to the ReactiveCocoa.podspec file as well

**Comment by andersio** [comment]
Thanks. I will validate & make a release ASAP.

**Comment by macoscar** [comment]
We are also affected by this issue. Thank you very much for the fix!! 🙌 I'll wait impatiently 😅

**Comment by andersio** [comment]
11.2.0 has been released. Let me know there is any other issue.

**Comment by macoscar** [comment]
Thank you very much!! I'm testing we app with latest version of ReactiveCocoa (11.2.0) and so far everything is great!!
