### ISSUE TITLE
Xcode 12.5 beta 3 can't build ReactiveCocoa with SwiftPM.

### ISSUE THREAD

**Issue by iWECon** [ReactiveCocoa/ReactiveCocoa#3723]
<img width="397" alt="CleanShot 2021-03-29 at 09 55 48@2x" src="https://user-images.githubusercontent.com/16604027/112777490-f2db5a80-9074-11eb-9ccd-41bd225883c3.png">

<img width="993" alt="CleanShot 2021-03-29 at 09 56 02@2x" src="https://user-images.githubusercontent.com/16604027/112777498-fb339580-9074-11eb-9037-805e86f388cd.png">

<img width="1008" alt="CleanShot 2021-03-29 at 09 56 20@2x" src="https://user-images.githubusercontent.com/16604027/112777513-05ee2a80-9075-11eb-94df-3866cc6ff011.png">

how do i fix it?

**Comment by rlziii** [comment]
This still seems to be a problem with Xcode 12.5 RC (released 2021-04-20).

**Comment by TimPapler** [comment]
There seems to be missing an `#import <Foundation/Foundation.h>` in ObjCRuntimeAliases.h
