### ISSUE TITLE
Current version can't be compiled with the latest ReactiveSwift version

### ISSUE THREAD

**Issue by Vyazovoy** [ReactiveCocoa/ReactiveCocoa#3735]
Recently ReactiveSwift min deployment targets were bumped in a minor release. So now ReactiveCocoa has min iOS deployment target iOS 9 but it has `ReactiveSwift ~> 7.0` that resolves to the new ReactiveSwift 7.1 that has min deployment target iOS 10. As a result I'm getting
```
- ERROR | [iOS] xcodebuild:  ReactiveCocoa/ReactiveCocoa/AnyObject+Lifetime.swift:2:8: error: compiling for iOS 9.0, but module 'ReactiveSwift' has a minimum deployment target of iOS 10.0
```
 Could you please bump ReactiveCocoa min deployment targets to make it compatible with the ReactiveSwift 7.1

**Comment by mfstephens** [comment]
+1, same problem here.

**Comment by CaioSym** [comment]
Any news on this? its been 6 months since reporting and a PR with a Fix has been open for 2 months. Whats blocking this? Anything I can do to help?
