### ISSUE TITLE
do vs subscribe

### ISSUE THREAD

**Issue by mackross** [ReactiveCocoa/ReactiveCocoa#378]
I haven't been able to find a resource to explain what is and conversely what is not a side effect and therefore when to use _do_ vs _subscribe_.  Either a resource or an example of a _do_ and _subscribe_ and a brief explanation of why each is chosen would be hugely helpful to me.

Secondly, is it best practice that _any_ signal used to update the UI be wrapped in `deliverOn:[RACScheduler mainThread]`? Even one that simply observes a property set only on the main thread?

Lastly, thank you so much for this fantastic contribution to the community! I've used ReactiveCocoa in two shipping apps with another two on their way. It has greatly simplified a lot of complex code in all of them. :+1: love it!

**Comment by onmyway133** [comment]
Actually, the word "side effect" confused me at first. I thought the work inside the block used by `RACSignal createSignal` (the didSubscribe block) is the "main work", not the "side effect"
