### ISSUE TITLE
Cannot get RAC working in my project

### ISSUE THREAD

**Issue by enelson** [ReactiveCocoa/ReactiveCocoa#394]
Hi guys. Not sure if this is the right place for this, but can't find anywhere else to ask this. I'm trying to put RAC into my new project, and I think I've set everything up correctly, according to the documentation. My code compiles fine. But when I go to run it, I get an error every time. Here is my simple code I'm trying to get working:

``` objective-c
@implementation LoginViewcontroller
...
@property (nonatomic, copy) NSString *username;

- (void)viewDidLoad
{
    [super viewDidLoad];

    [RACAble(self.username) subscribeNext:^(id x) {
        NSLog(@"---> Username has changed to: %@", x);
    }];
}

...
@end
```

But as soon as I try running this in the simulator (iOS 6.1), I get an error:

``` objective-c
-[LoginViewController rac_signalForKeyPath:observer:]: unrecognized selector sent to instance 0xa27f660
```

This leads me to believe that it's calling RACAble on self, as opposed to self.username, but I have no idea why. And I have no idea what to try here. Any help would be greatly appreciated, as I'm loving what I'm seeing with this project and am excited to use it.

**Comment by mertnesvat** [comment]
I have same problem. Looks like readme hasn't been updated yet.
