### ISSUE TITLE
Why do you prefer flattenMap: over map:?

### ISSUE THREAD

**Issue by shpakovski** [ReactiveCocoa/ReactiveCocoa#448]
Hi guys,

There is a famous example from the RAC announcement blog post:

``` objective-c
[[[[client loginUser] flattenMap:^(User *user) {
    return [client loadCachedMessagesForUser:user];
}] flattenMap:^(NSArray *messages) {
    return [client fetchMessagesAfterMessage:messages.lastObject];
}] subscribeCompleted:^{
    NSLog(@"Fetched all messages.");
}];
```

It looks like the same effect would be from code like this:

``` objective-c
[[[[client loginUser] map:^(User *user) {
    return [client loadCachedMessagesForUser:user];
}] map:^(NSArray *messages) {
    return [client fetchMessagesAfterMessage:messages.lastObject];
}] subscribeCompleted:^{
    NSLog(@"Fetched all messages.");
}];
```

Could you please explain why do you prefer `flattenMap:` over `map:`? Maybe there is some less visible pitfall? Is it correct at all to use `map:` for such cases?

Thanks in advance!

**Comment by onmyway133** [comment]
A very interesting explanation is in this article http://www.raywenderlich.com/62699/reactivecocoa-tutorial-pt1

`
[[[self.signInButton
   rac_signalForControlEvents:UIControlEventTouchUpInside]
   flattenMap:^id(id x) {
     return [self signInSignal];
   }]
   subscribeNext:^(id x) {
     NSLog(@"Sign in result: %@", x);
   }];
`

**Comment by hsavit1** [comment]
Very cool @onmyway133 . I've never used flattenMap like that. Thanks for sharing

**Comment by alper** [comment]
What do you mean with: _map from an input value to an output value that is a signal, and you want that output signal to be flattened into the receiver's stream._

**Comment by andersio** [comment]
`map` maps discrete time value one-to-one.

`flatMap` is essentially `map-then-flatten` — It first maps a value to a signal of `U` values. This means the resulting signal would become a signal of signals of `U` values. Then it would flatten the signal of signals of `U` values into just a signal of `U` values, based on the strategy you choose (concat, merge or switchToLatest).

**Comment by devbackstage07** [comment]
private void flattenMap(String prefix, Object value, Properties properties) {
    if (value instanceof Map<?, ?>) {
        Map<?, ?> map = (Map<?, ?>) value;
        for (Map.Entry<?, ?> entry : map.entrySet()) {
            String newPrefix = prefix.isEmpty() ? entry.getKey().toString() : prefix + "." + entry.getKey();
            flattenMap(newPrefix, entry.getValue(), properties);
        }
    } else if (value instanceof List<?>) {
        List<?> list = (List<?>) value;
        for (int i = 0; i < list.size(); i++) {
            flattenMap(prefix + "[" + i + "]", list.get(i), properties);
        }
    } else {
        properties.setProperty(prefix, value != null ? value.toString() : "");
    }
}
