### ISSUE TITLE
NSControl -rac_textSignal doesn't work when programatically setting text

### ISSUE THREAD

**Issue by indragiek** [ReactiveCocoa/ReactiveCocoa#765]
If I set text on an `NSTextField` programatically via `-setStringValue:` or `-setAttributedStringValue:`, this doesn't trigger `NSControlTextDidChangeNotification`, which means that `-rac_textSignal` won't pick up the change either. It only works when the text is being edited by user interaction.

Easy fix would be to use `-rac_signalForSelector:` to intercept calls to the setters as well (in addition to registering for `NSControlTextDidChangeNotification`). Any other ideas?

**Comment by TolyaAfanasev** [comment]
@startupthekid thanks, it helps for me.

**Comment by kornerr** [comment]
@startupthekid thanks a ton!
