### ISSUE TITLE
Best design pattern for starting only one async operation and share signal result

### ISSUE THREAD

**Issue by notxcain** [ReactiveCocoa/ReactiveCocoa#828]
Let's pretend that RACSignal *updateSignal encapsulates some async task. When subscription occurs I want every new subscription during the async task to receive same result as the first subscriber.
Right now my code looks like this:

``` obj-c
- (RACSignal *)doWork
{
    if (_sharedWorkSignal) return _sharedWorkSignal;

    RACSignal *requestSignal = ...;
    _sharedWorkSignal = [[[[requestSignal publish] autoconnect] doCompleted:^{
        _sharedWorkSignal = nil;
    }] doError:^(NSError *error) {
        _sharedWorkSignal = nil;
    }];

    return _sharedWorkSignal;
}
```

It works but I don't really like how it looks. Do I miss something important here?

**Comment by fabiomassimo** [comment]
I'm facing a kind of same issue with a shared signal that I won't to "re-trigger" when it's needed.
I've tried a lot of possible solution in RACMultiConnection fashion but no matter what I'm always facing the same problem: every time I want to re-trigger my source signal it sends next: to all previous subscribers.

More in detail:

1) the network request is made by a convenience methods that wraps up an old delegate implementation:

```
RACSignal *performRequestSignal =
    [RACSignal createSignal:^RACDisposable *(id<RACSubscriber> subscriber) {
        // Create data received signal
        RACSignal *dataReceivedSignal = [[self rac_signalForSelector:@selector(dataReceived:forRequest:) fromProtocol:@protocol(CWMainDataControllerDelegate)] filter:^BOOL(RACTuple *returnTuple) {
            CWDataRequest *request = returnTuple.second;
            CWDataResponse *dataResponse = returnTuple.first;
            
            return ((request.type == dataRequest.type) && ([dataResponse.value isKindOfClass:dataResponseClass]));
        }];
        
        // Subscribe
        [dataReceivedSignal subscribeNext:^(RACTuple *returnTuple) {
            CWDataResponse *dataResponse = returnTuple.first;
            [subscriber sendNext:dataResponse.value];
            [subscriber sendCompleted];
            
        }];
        
        // Create data request failed signal
        RACSignal *requestFailedSignal = [self rac_signalForSelector:@selector(requestFailed:error:) fromProtocol:@protocol(CWMainDataControllerDelegate)];
        
        // Subscribe
        [requestFailedSignal subscribeNext:^(RACTuple *returnTuple) {
            NSError *error = returnTuple.second;
            [subscriber sendError:error];
        }];
        
        // Trigger the request to API
        [[CWMainDataController sharedInstance] addRequest:dataRequest delegate:self priority:queuePriority];
        
        return [RACDisposable disposableWithBlock:^{
            [[CWMainDataController sharedInstance] cancelRequest:dataRequest];
        }];
    }];
    
    return performRequestSignal;
```

2) This method uses previous one to create a convenience signal which we are calling "retrieveThingsSignal"

```
- (RACSignal *)retrieveThings
{
    if (_retrieveDebtors) return _retrieveDebtors;
    
    RACSignal *requestSignal = [self retrieveThingsSignal];
    _retrieveDebtors = [[requestSignal replayLast] finally:^{
        _retrieveThings = nil;
    }];
    
    return _retrieveThings;
```

3) every time I won't to re-trigger the signal a run this code

```
[[self retrieveThings] subscribeNext:^(NSArray *things) {
        @strongify(self);
        self.things = things;
    } error:^(NSError *error) {
        @strongify(self)
        self.things = nil;
    }];
```

My ```self.things``` gets updated accordingly to every time I need to make a new request to ```retreiveThings``` but, by putting a breakpoint inside the 1) step, I'm receiving that the ```next:``` is sent to ALL previous subscribers. If I call ```retrieveThings``` twice, I'm receiving, from that breakpoint, that the base signal is sending ```next:``` to two different subscribers (one will actually run the ```subscribeNext:``` block). If three to three subscribers, and so on...

I can  I prevent this behaviour?

I would like to share the last sent value from my ```retrieveThings``` method without trigger EVERY time the network request but, when needed, I need to clean it such that next subscribe will actually trigger the network request.

**Comment by jlawton** [comment]
Your problem is that you're using `self` as your delegate, and so you're calling back to the same object for every network call, which is then passed on to all of your signals. Create a new delegate for each request.

After that, something like what you have will work.I'd probably chose to bundle up the cached signal check into `defer:` but that's just a preference in the semantics for me.

```obj-c
- (RACSignal *)retrieveThings
{
    return [RACSignal defer:^{
        @synchronized(self) {
            if (!_cachedSignal) {
                _cachedSignal = [[[self actuallyRetrieveThings]
                    finally:^{
                        @synchronized (self) {
                            _cachedSignal = nil;
                        }
                    }]
                    replayLast];
            }
            return _cachedSignal;
        }
    }];
}
```
