### ISSUE TITLE
Behavior of `+createSignal:` in `-subscribeOn:`

### ISSUE THREAD

**Issue by erikprice** [ReactiveCocoa/ReactiveCocoa#832]
I just wanted to make sure I understand the behavior of `-[RACSignal subscribeOn:]`. I have a signal that I create with `+[RACSignal createSignal:]`. The block passed to this latter method contains code that must execute on the main thread (as a requirement of the library I am using) whenever something subscribes to this signal. Is my understanding correct that if I chain the creation of the signal with `-subscribeOn:RACScheduler.mainThreadScheduler`, that the block will execute on the main thread?

**Comment by intoxicated** [comment]
I understand as erik about subscribeOn, however, i found that some of my code run in background thread even though I claimed to run the code in main thread with [RACScheduler mainThreadScheduler]...

**Comment by joshaber** [comment]
Could you post the code? It's hard to diagnose without that.

**Comment by intoxicated** [comment]
[[[self.imageUploader uploadPhotoAssets:photoAssets withKey:[self keyForUploading]]
      subscribeOn:[RACScheduler mainThreadScheduler]] subscribeNext:^(RACTuple *tuple) {
        RACTupleUnpack(MPPhotoAsset *photoAsset, NSString *uploadedUrl) = tuple;
        MPPhotoImageView *imageView = [photoAssetToImageViewDictionary objectForKey:photoAsset];
        imageView.uploadedUrl = uploadedUrl;
        [imageView setImage:[photoAsset thumbnail]];
    } error:^(NSError *error) {
        
    } completed:^{
        [[NSNotificationCenter defaultCenter] postNotificationName:NOTI_UPLOAD_BEGUN object:nil];
    }];

and uploadPhotoAsset is following

    - (RACSignal *)uploadPhotoAssets:(NSArray *)photoAssets withKey:(NSString *)key
    {
        return [RACSignal startLazilyWithScheduler:[RACScheduler scheduler] block:^(id<RACSubscriber>     subscriber) {
            [photoAssets enumerateObjectsUsingBlock:^(MPPhotoAsset *photoAsset, NSUInteger idx, BOOL     *stop) {
                NSString *uploadedUrl = [self uploadPhotoAsset:photoAsset withKey:key];
                [subscriber sendNext:RACTuplePack(photoAsset, uploadedUrl)];
            }];
            [subscriber sendCompleted];
        }];
    }

**Comment by joshaber** [comment]
`-subscribeOn:` determines which scheduler the signal's `didSubscribe` block is called on. `-deliverOn:` determines which scheduler values are sent on.

Change that `-subscribeOn:` to `-deliverOn:` and it'll be :sparkles:

**Comment by intoxicated** [comment]
Thanks!!! it fixed everything :)
