### ISSUE TITLE
Proper RAC pattern for UIBarButtonItem

### ISSUE THREAD

**Issue by bobspryn** [ReactiveCocoa/ReactiveCocoa#993]
Since `UIBarButtonItem` doesn't have something like `rac_signalForControlEvents`, we can't just pull off a signal to react to. `rac_command` is also `nil` by default. So in my mind that means the proper way to trigger something from a `UIBarButtonItem` is to return a signal from it's `rac_command` that you then observe and react to. For something like presenting a new view controller from an 'add' button, this feels like overkill. So instead I end up putting that kind of code in the command itself, and just returning a signal that nothing really pays attention to.

``` Objective-C
self.addButton.rac_command = [[RACCommand alloc] initWithEnabled:[RACSignal return:@YES] signalBlock:^RACSignal *(id input) {
    // present view controller
    return [RACSignal empty];
}];
```

**Comment by wangpeiyan** [comment]
no 3.0

**Comment by andersio** [comment]
ReactiveCocoa 3.0 was designated for **Swift 1.0**, which had already been deprecated.

**Comment by Agoer** [comment]
ReactiveObjC For 3.0 是 well

**Comment by Agoer** [comment]
ReactiveObjC For 3.0 is well
